### ISSUE TITLE
BUG: Ticket reply can't handle punctuation.

### ISSUE THREAD

**Issue by fizzle7** [yogstation13/yogstation#100]
The ticket gui doesnt show the reply properly if you put special characters such as ", cuts the string off before the ".

**Comment by george99g** [comment]
This has been a bug for a *very, very* long time.
You deal with it by just refreshing the ticket.

**Comment by X-TheDark** [comment]
I tried fixing this but I couldn't pinpoint the exact place this was happening, I tried doing regexps to replace all those characters with escaped ones, but I must suck at regexp, because it didn't work.

**Comment by nichlas0010** [comment]
Fixed
