### ISSUE TITLE
"Escape pod one", twice.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#10025]
- fulton beacons list both arrivals pods as "escape pod one" on Yogstation.

**Comment by SomeguyManperson** [comment]
Iirc every pod is listed as "escape pod one" because shitcode

**Comment by patpol4** [comment]
They have the same areas probably

**Comment by patpol4** [comment]
Needs creating new areas for each pod and mapping them in properly, shouldnt be hard i think

**Comment by patpol4** [comment]
It was more complicated than that
