### ISSUE TITLE
AI Holopad Speech Has No Bubble

### ISSUE THREAD

**Issue by Traece** [yogstation13/Yogstation#10028]
AI when communicating via :h on Holopads generate no speech bubble and the text isn't emphasized much in the chat box, making it extremely difficult to communicate with people via holopad because people don't actually read the chat box anyways.

JamieD told me to post about it on the Github Repository when I mentioned it in OOC, so I apologize if this was the improper place to mention it.

**Comment by redmoogle** [comment]
Fixed by Jamie
