### ISSUE TITLE
Cyroing an AI core does not provide a way for the player to get out

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#10038]
Admin cyro braindead AI, braindead Ai gets taken over but body is in cyropod, no way out, body gets cyroed and the player ghosted.

**Comment by redmoogle** [comment]
Step 1. Dont break game with badmin power.

**Comment by MegaEmpirical** [comment]
What the fuck are you talking about. It wouldn't break the game if it wasn't broken. Why did you close this?

**Comment by redmoogle** [comment]
> 
> 
> What the fuck are you talking about. It wouldn't break the game if it wasn't broken. Why did you close this?

Use offer control to ghosts? admin cryo should really only be used on normal players and not silicons.

**Comment by MegaEmpirical** [comment]
Cyroing frees up the player spot and let's a new AI late join

**Comment by redmoogle** [comment]
Well whatever niche case your triggered with the AI coming back last second isn't getting fixed

**Comment by MegaEmpirical** [comment]
It's not niche. This is how admin cyro works. It moves the body to the pod if a ghost doesn't taken it quickly and and then player the player has to leave the pod. AIs have no way to do this.
