### ISSUE TITLE
Spawning bug as wizard

### ISSUE THREAD

**Issue by BraveMole** [yogstation13/Yogstation#10056]
Spawned as a wizard [https://ibb.co/3B1PYGQ](url), no clothes or anything

couldn't move or do anything, the start game menu poped up (join or observe). 
My character was catatonic, and chosing observe did not cause the round to end

Issue reported from  Round ID: 32373 (Yogstation 13 (Main))

Reporting client version: 513.1532

**Comment by redmoogle** [comment]
Supposedly fixed. Make a new issue if it pops up
