### ISSUE TITLE
Using a stabilized gold extract can give you a clown bug as a pet

### ISSUE THREAD

**Issue by cuackles** [yogstation13/Yogstation#10092]
Issue reported from  Round ID: 32418 (Yogstation 13 (Main))
using a stabilized gold can give you a clown bug as a pet, the problem is this clownbug has the chance of spawn another clownbug when steped on, wich can lead to a lot of clownbugs in very little time and that would probably could crash the server

Reporting client version: 513.1534

**Comment by DiamondSentinel** [comment]
Yeah, so what happens here is that normally, when the clownbug dies, it spawns a new one. The issue is, stabilized gold core instantly spawns another one.

**Comment by redmoogle** [comment]
Fixed but git bad
