### ISSUE TITLE
May want to "rebase" again in a few weeks

### ISSUE THREAD

**Issue by Bawhoppen** [yogstation13/yogstation#101]
datum antags is happening, coiax is a madman

**Comment by oisin100** [comment]
WHEW LAD

**Comment by Bawhoppen** [comment]
its happening dont doubt it

**Comment by X-TheDark** [comment]
Goddamn madman.

**Comment by Bawhoppen** [comment]
yea datum antags entails a complete rewrite of gamemode code, and theres even a tg gamemode code freeze right now so its official
according to coiax he's finished traitor and is now wading around through changeling code

**Comment by timkoster1** [comment]
What does this include?

**Comment by Bawhoppen** [comment]
good gamemode code (big deal) aswell as ability to remove all roundtypes and create fully randomized antags in a round
