### ISSUE TITLE
Greed's slot machine is not working rigth

### ISSUE THREAD

**Issue by cuackles** [yogstation13/Yogstation#10150]
Issue reported from  Round ID: 32472 (Yogstation 13 (Main))

so i used the greed slot machine and it didnt took health from me, so i keep using it as it seemed like it wasnt affecting my health, but after some tries i falled into crit, but my health was still at 100%, someone tried to put me into cryo just for cryo to spit me out again because i was compleatly healthy
Reporting client version: 513.1534

**Comment by ToGWtF** [comment]
Greed doesn't deal damage. Greed STEALS your max HP. Using it enough time means your Max HP goes below crit, and you can never re-heal that damage back out of crit.

**Comment by ToGWtF** [comment]
Fixed in https://github.com/yogstation13/Yogstation/pull/10151
