### ISSUE TITLE
Cant apply patches to head while hardsuit helmet is down but suit is still on

### ISSUE THREAD

**Issue by Jarod1200** [yogstation13/Yogstation#10175]
I have tried this with both the CE hardsuit and the blood red hardsuit. If you take the helmet off but leave the suit on your body, you can't apply a patch to your head even though it is exposed.

**Comment by neeshacark** [comment]
deathsquad hardsuit also has this issue

**Comment by redmoogle** [comment]
Tested, you cannot apply patches with your helmet down and targeting head
