### ISSUE TITLE
Spawnplaces are not optimal!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1017]
What I experienced in a short amount of time:

1. Ashwalker front door leading to Bubblegum and Colossus within attacking distance for considerable amount of time (is there a way to make a no-go zone for monsters at these spawn places?)

2. Prisoner shuttle leading to lava..

![prisonerohgodlava](https://cloud.githubusercontent.com/assets/16806055/19401065/7d20bd94-9259-11e6-9551-a2ef1c5891db.png)

..in a way you can't see, with flashlight on.
Maybe we do need a buffer zone at the front doors of these places.

![prisonercantseejack](https://cloud.githubusercontent.com/assets/16806055/19401150/f5b8b32e-9259-11e6-8e1a-257c3f5046dd.png)

**Comment by ClaudeWicked** [comment]
Invisible lava's been a longstanding bug x.x
