### ISSUE TITLE
Conveyor Belts in Cargo don't work to well

### ISSUE THREAD

**Issue by JupiterFive** [yogstation13/yogstation#1018]
Just now, I tried to use the levers to push the crates onto a cargo shuttle, when only one tile responded to the lever. I don't know how easy it is to recreate the bug, but it is making things hard.

**Comment by JupiterFive** [comment]
I've also noticed that the conveyor belt works again after the cargo shuttle leaves.

**Comment by Kmc2000** [comment]
Hmmm someone may have disconnected them from the switch?

Next time, crowbar up the lever and all tiles, hit tiles with lever and THEN place lever back
