### ISSUE TITLE
goldgrubs dont eat

### ISSUE THREAD

**Issue by LazennG** [yogstation13/Yogstation#10190]
when theyre near ore and interact with it the 'the ore was swallowed whole!' message appears but the actual ore count doesnt change and their ores they drop dont seem to be affected

**Comment by SomeguyManperson** [comment]
which kind of ore

**Comment by LazennG** [comment]
tested it with a few ores like titanium and plasma but when i killed it titanium wasn't dropped and the plasma it gave wasn't noticeably greater in amount than the other ores

**Comment by Altoids1** [comment]
![image](https://user-images.githubusercontent.com/29939414/101158452-5b4b8b00-35f1-11eb-92a9-38b14a972a4e.png)

Bug confirmed. Goldgrubs are actually intended to not eat up things like plasma, but it seems this bug affects things like gold as well.
