### ISSUE TITLE
change the faithless wishgranter or faithless ruins

### ISSUE THREAD

**Issue by xbobsherex** [yogstation13/yogstation#1019]
there are two wishgranters. one where you battle the hoards of faithless dungeon style and another where you have to teleport in through telescience or bluespace crystals.  

the wishgranter where you have to teleport to the middle of a box of reinforced walls is awesome. it gives you hijack mission with various powers. there is simply no downside to it. the only question of weather youll get it or not is how many bluespace crystals you have.

then theres the wishgranter where you can get it from fighting an army of faithless, which ive seen many try but none actually succeed at, or use teleports.  now the rewards for this is kind of fucked. 

for fighting an army of faithless, no easy task, you have 4 options: 
1. wealth. gives a closet containing 2 full stacks of each mineral and i was told makes you a shadow person. (fairly uselsss as your already mining)
 shadow people die by light but regen in darkness. they also cant walk through walls and you dont even know your a shadow person. just that your dieing.
1. peace. i was told this one kills all the faithless in the game. also useless considering you might have just fought and killed all the faithless to get here. if you teleported into the wishgranter and do this you get no extra loot in the ruins. this is the only prize.
2. power. this grants you some powers and shadow person. aka death unless you have a health scanner or just know you become a shadow person. even then its still shit.
3. kill. this gives you hijack and shadow person. woo you have hijack, but you die to a flashlight.

problem with 3 and 4 is the other wishgranter gives you BOTH of these without the whole shitty shadow person. not only that but 1 will never get picked because people will always choose antag. fuck. even an antag would choose hijack because thats better than any objective they currently have.  2 is just stupid.

if anything i would say switch the 2 wishgranters. make it so the all powers + hijack come from the faithless and the shitty wish granter come from the reinforced walls.  at least then you might have a reason to attempt the faithless fight. right now the rewards just aren't worth it.  its the hardest ruin/challenge on lavaland with some of the shittiest rewards.

**Comment by Time-Green** [comment]
Isn't there also an immortality one?
Wich makes you a shadowperson with the spell to heal yourself from death at anytime?

**Comment by Cruix** [comment]
Yes, there is an immortality one that makes you a shadowperson and gives you a verb to admin-heal yourself from anything short of gibbing or dusting.

**Comment by ShadowDeath6** [comment]
Shadowperson should be a buff tbh :^)
