### ISSUE TITLE
Traitor chameleon kit UI

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#1020]
Since rebasing there is no traitor chameleon kit UI which means each piece needs to be set individually. Also, it seemed like there were several options missing like normal white/black shoes but I would have to take another look to confirm. The UI is a huge quality of life thing for traitors but also a huge advantage given the time it will save, especially on the fly, so I can also see an argument for leaving it out.

**Comment by Amelia0010** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/979 🤔

**Comment by MegaEmpirical** [comment]
So is it more desirable to not re-add this then?

**Comment by Amelia0010** [comment]
mane you didn't even click the link I posted did you?

**Comment by MegaEmpirical** [comment]
You are right, sorry. I looked at this right after I woke and missed the link. Sorry, thanks.
