### ISSUE TITLE
Jacob's ladder suffocates guy in a wall

### ISSUE THREAD

**Issue by PyGGy1** [yogstation13/Yogstation#10210]
## Testmerges: dunno.
![jacob's ladder goes brr](https://user-images.githubusercontent.com/73579535/97406871-8a8c1f80-1902-11eb-9a68-48bb0486c369.png)
![jacob's ladder goes brr](https://user-images.githubusercontent.com/73579535/97406884-8fe96a00-1902-11eb-955d-a5463a54269c.png)

**Comment by Takahiru** [comment]
arent they supposed to be random

**Comment by ToGWtF** [comment]
Jacobs Ladder goes up and down the same coordinates, only the Zlevel changes

**Comment by SomeguyManperson** [comment]
Ladder creates ladders on the same coordinate tile of every z level so it is entirely possible for them to end up in dangerous locations
