### ISSUE TITLE
Bounty Board shows incorrect name of Non-Human Backup Characters upon use

### ISSUE THREAD

**Issue by Firewolf34** [yogstation13/Yogstation#10213]
## Round ID: 32544

For Context: If you have a Non-Human save slot for your character, and you choose a Head Role, your character will become the Human with a "Backup Name" to prevent Non-Humans in Head Roles. 

The Bounty Board is not programmed to deal with this.

If you spawn as a Human character, because you chose a Head Role, but your character is normally Non-Human, the Bounty Board will still show your Non-Human name. It must not be getting the name from the ID card as it probably should.

## Reproduction:

Spawn as a Human because you were forced to, after choosing a Non-Human character, and selecting a Head Role job role. After you spawn in as your backup name, use the Bounty Board. See the wrong name appear.

**Comment by redmoogle** [comment]
Tested. Bank accounts seem to be initialized before ID cards and dont update their name.
