### ISSUE TITLE
A way to disable dimmed lighting setting

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#1021]
Would be nice for heads of staff and AI to have a means of disabling the dimmed light setting through maybe the power monitor or something (aside from setting alert to red).

Alternatively, do we even like this feature? Is it something we want to keep? Could be useful for antags in some fashion so I am not sure how it balances out in pros/cons.

**Comment by Amelia0010** [comment]
>Would be nice for heads of staff and AI to have a means of disabling the dimmed light setting through maybe the power monitor or something (aside from setting alert to red).

You can do that on an APC.

**Comment by MegaEmpirical** [comment]
Only one at a time, I was requesting a means of disabling globally.

**Comment by Amelia0010** [comment]
I'll never understand why you all hate dimmed lighting so much

**Comment by MegaEmpirical** [comment]
I still don't care for it but I am used to it now. Closing.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
