### ISSUE TITLE
Additional janitor lockers in the janitor closet

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#1024]
There are three janitor spots on the station and really only 1 locker (there are 2 but the other is just the bio suit). We used to have 2 (one of each locker so 4 total) before the rebase. If not, then please at least add a 4th wet floor sign to the single janitor locker, the cart holds 4 and there are only 3 in there.

**Comment by MegaEmpirical** [comment]
Closing because of:

https://github.com/yogstation13/Yogstation-TG/pull/2761

**Comment by Amelia0010** [comment]
https://github.com/yogstation13/Yogstation-TG/blob/7d2a976b3cbe8fe410c38e2d76f4bce402277b24/code/modules/jobs/job_types/cargo_service.dm#L274

You're an idiot

**Comment by MegaEmpirical** [comment]
It helps if you explain why you're calling someone an idiot. I assume because I said there were three janitor positions? A small mistake, I thought there were three. I was only asking for one more locker anyway.
