### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1025]
"Your form morphs into that of a animal."

If not specified, it should be "a(n)".

**Comment by JupiterFive** [comment]
I could fix it, despite the fact that I barely know DM. All I know is how to find text through all scripts.

**Comment by ShadowDeath6** [comment]
it works like "your form morphs into that of a [selected transformation option]", would be a pain in the ass to reformat

**Comment by 00aquir** [comment]
Well.. what you can do:
^ 1. a(n):  "your form morphs into that of a(n) animal"
2. using adjectives: "your form morphs into that of an average animal"
3. changing article depending on pronunciation of next word (good luck :D)
