### ISSUE TITLE
Re-enable borers

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#1025]
As titled, was enjoying having them about. Should likely include the fix to prevent them from infesting head revs too.

**Comment by Smudged** [comment]
If this'll ever happpen, we'll need to merge over the fiz to not allow borers to suicide their host as well

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.

**Comment by MegaEmpirical** [comment]
Bastards.
