### ISSUE TITLE
Blood Brothers: Too Much Brothers 2: Electric Boogalo

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/Yogstation#1027]
[Reproduction]: That's the problem
[For Admins]: Yeah kinda
Blood Brothers. 16 antags with 38 players. 
One team will totally get a hjack, so plasma/bombs/engine is out and grief is everywhere guaranteed, not counting all shittery from 14 other brothah.
I think that's too much and can you fix config number thaaaaaaanks

**Comment by Partheo** [comment]
TOO MUCH BROTHERS

**Comment by DLCabbose** [comment]
it's just called two brothers

**Comment by Amelia0010** [comment]
done
