### ISSUE TITLE
Map Does Not Appear

### ISSUE THREAD

**Issue by alao3alao3** [yogstation13/Yogstation#10282]
### Round ID:
32608
### Testmerges:
Server revision compiled on: 
Master commit: f3a81cbc275d68b105e7ac1d5d556ff3830066e3
The following pull requests are currently test merged:
9953: 'Makes Budget Insuls have two charges of absorbing shocks, After which they turn to ash.' by JamieD1 at commit 0c411558bf
10232: 'TGChat Test Merge - Because Gamer is a Turd and wont let us edit his branch' by JamieD1 at commit 406e62af81
### Reproduction:
When opening the Handheld Crew Monitor, viewing the Crew Monitor, or using the Station Map, no map appears.
![bpng](https://user-images.githubusercontent.com/62276730/97794715-d6c1b300-1bd3-11eb-9bfe-3661f7e12203.png)
Reconnecting does not fix this.

**Comment by ToGWtF** [comment]
Close and re-open the window a few times and let the resources load.

**Comment by redmoogle** [comment]
Fixed by Jamie
