### ISSUE TITLE
Swarmers can't eat

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#10281]
Issue reported from  Round ID: 32607 (Yogstation 13 (Main))

Reporting client version: 513.1536

![image](https://user-images.githubusercontent.com/36427443/97794126-31571100-1bcc-11eb-8e31-9e4cdd4fd2a5.png)
Not metal, not glass shards, not metal rods, not fire extinguishers, nothing, they can break walls and all but the items are _Incompatible with our internal matter recycler._
I hope I just missed something and they're actually carnivores now that would be pretty sugoi :^o

**Comment by SomeguyManperson** [comment]
probably related to #10176
