### ISSUE TITLE
Port: Our slaughter demons

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#103]
/tg/ nerfed the shit out of their slaughter demons so that they have to click a spell/action button, which gimped their lethality since they need to move their cursor off the screen/out of their range of attacking.

**Comment by ShadowDeath6** [comment]
I'll port this if people want it

**Comment by Super3222** [comment]
how 2 use action buttons:
1) buy a wireless mouse
2) plug it in
3) be able to click action buttons lightning fast.

**Comment by ShadowDeath6** [comment]
nevermind I'll do this whenever I stop playing overwatch, somebody remind me when I get on
