### ISSUE TITLE
When having custom tabs (Status and MC) up when there are two rows of tabs the bottom row is covered

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#10302]
![](https://i.imgur.com/hyofsMN.png)

**Comment by redmoogle** [comment]
Happens Often, but new statpanel pr fixes it

**Comment by JamieD1** [comment]
New chat panel and tabs being changed soon, reopen if its still an issue in a week.

**Comment by jcatjmeow** [comment]
"I'm getting rid of three of the bloody tabs soon, so it won't be an issue anymore" -Jamie

**Comment by JamieD1** [comment]
> "I'm getting rid of three of the bloody tabs soon, so it won't be an issue anymore" -Jamie

Thanks Jcat, everyone does need some good context 👍
