### ISSUE TITLE
Drone inhand is just a tophat

### ISSUE THREAD

**Issue by patpol4** [yogstation13/Yogstation#10311]
Reproduction:

pick up drone, see tophat in hand
![dreamseeker_lDSm0AjksH](https://user-images.githubusercontent.com/48154165/97917056-2e872800-1d54-11eb-8fb2-7d3be0f97249.png)

Moreso, if you put the drone on your head and place it back into your hand, the drone itself drops down on the floor but the inhand appears again:
![dreamseeker_d1Ng3IRYtA](https://user-images.githubusercontent.com/48154165/97917253-7efe8580-1d54-11eb-98eb-9c8e1535a021.png)

This way you can hold two drones in your hands without actually having anything in them:
![dreamseeker_VqKRpUxPnC](https://user-images.githubusercontent.com/48154165/97917876-78bcd900-1d55-11eb-8b88-f969327a0264.png)

**Comment by adamsong** [comment]
This has been fixed
