### ISSUE TITLE
Legion soul does not remove the stupid watcher chemicals

### ISSUE THREAD

**Issue by puremanbird** [yogstation13/yogstation#1031]
using a legion soul on yourself after fighting a watcher does not remove the watcher chemicals. There is no possible way this is a feature.

**Comment by Dagdammit** [comment]
Damage and chems are two different things. I don't see a problem?

That said, I didn't actually know watcher attacks dosed you; what chemical is it?

**Comment by ClaudeWicked** [comment]
Cryptobiolin, Im pretty sure.

**Comment by Super3222** [comment]
@puremanbird legion souls only heal physical damage (brute and burn i believe).

**Comment by puremanbird** [comment]
Super, i know. The legion soul should heal everything. It should remove the annoying chemical from spiders because honestly that would make it a ton more valuable to hold onto when hunting in lavaland.

**Comment by Dagdammit** [comment]
Any chem-purging item (that rapidly cleanses a fixed amount of
reagents/fixed amount of EACH reagent) would be really potent. I mean,
having it be a consumable dropped from a lavaland mob on death is a decent
counterbalance, but to have it be added to an item which already heals
brute and burn? Better to have it be a separate item which drops from a
different mob. Watcher, maybe? Call it "Watcher's Tear", and it's a
delicate crystal found within the eye?
