### ISSUE TITLE
Transit tubes - not for space?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#10329]
- new transit tubes and stations should create pressure+temp inside the transit pod, otherwise they are useless for space (which they were intended for).

**Comment by jcatjmeow** [comment]
@00aquir 

The pods "fill up" with air when they open and release it the next time, repeat. So if one end of the tube is vacuum, then they won't function as intended.

If this is what happened, not a bug

**Comment by 00aquir** [comment]
@jcatjmeow

That is why I mentioned stations too. I made stops where one end, or just the middle station was in space, for people to enter the station at a certain location, while others without hardsuit would just skip that and go to the other end, but it froze people.
