### ISSUE TITLE
Game crashes when writing OOC / LOOC

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#10328]
- weird, the game crashes in the middle of writing OOC / LOOC (after using hotkey)
- happens only sometimes, but happened in several rounds

**Comment by 00aquir** [comment]
yep that's what's "causing" it, I had some doubts but now it's really annoying.

**Comment by patpol4** [comment]
Probably due to https://github.com/yogstation13/Yogstation/pull/10308

**Comment by adamsong** [comment]
I've not seen this, and the test merge is question was closed, closing
