### ISSUE TITLE
Slight maint access increase?

### ISSUE THREAD

**Issue by Dagdammit** [yogstation13/yogstation#1033]
What if professions with limited access to a specific section on maintenance (i.e. their own space's back door) could also use any public accesses to that same section of maintenance, or at least the nearest two? 

e.g: Chaplain & librarian can use maint accesses by library & back of chapel, maybe also the one SW of holodeck. Sci staff can use the one by escape and the one west of robotics, possibly also the ones E and SW of Janitor. 

Would that be an improvement?

**Comment by Hydre** [comment]
But for what purpose?

**Comment by Dagdammit** [comment]
I know that it would be a nice bit of access to have as, say, chaplain or botanist because it would allow you to enter your workspace from the back. Lets you take shortcuts through your little stretch of maint rather than it just being a super-elaborate dead end. 

That's just a thing I want while playing, mind- in the same way I want to not die and have a good weapon. I honestly don't know if it would make the overall game better.

**Comment by AdamElTablawy** [comment]
talked with the council about it a while back, they said no
