### ISSUE TITLE
New addition to chemistry set

### ISSUE THREAD

**Issue by Do9Ta9** [yogstation13/yogstation#1034]
I suggest adding a single chem synthesizer to chemistry,it scans a chemical and replicate it,it recharges very slowly and can make 30u(max) worth of chemicals ,example: scans a tricordrazine beaker->10 seconds later the chem synthesizer will make 1u of that chemical,the process is slow but can be very helpful for other departments(botanics,virology,science,?security?),if upgraded it can either recharge faster like 5 seconds for chemical unit or recharge more units like 2 or 3 chemical units each 10 seconds (or both),the sprite can be a modified chem dispenser sprite,circuit boards should require lvl 2 bluespace,lvl 5 materials and 2 data theory

**Comment by ShadowDeath6** [comment]
Making free chems is shit and even where it's already used is unbalaced because it lets chem mass produce shit like mint toxin or traitor toxins provided they get their hands on it

**Comment by Yewmi** [comment]
![odysseus](https://cloud.githubusercontent.com/assets/22177874/19488388/46b300c0-952c-11e6-9a7e-b985f8ad1695.png)

The Odysseus does this already, but on steroids.
- scans and then synthesizes chemicals with a 75u max chem capacity
- can fire syringes filled with said chemicals
