### ISSUE TITLE
Recycler starting as emagged

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#10375]
As title, shit be fucked. Mo'fuckas be dying.

Also, I suspect the lights are on the sprite are wrong and have been for months, Please double check for me.

**Comment by redmoogle** [comment]
@jcatjmeow review bug, I cant replicate it

**Comment by ToGWtF** [comment]
Fixed in https://github.com/yogstation13/Yogstation/pull/10376
