### ISSUE TITLE
Airlock painter - no door sprites #2

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#10385]
If you use the airlock painter, it cannot load some sprites for some of the available door types. (Also you cannot check all possible door paints if you're painting just one type of door.)

tried it just now:
![ss13-doorpaint](https://user-images.githubusercontent.com/16806055/98744387-e8644100-23b1-11eb-9cd8-ec35bc9866e2.png)

After doing it, because the previous sprite cannot be re-applied, the door sprite permanently disappears for the round and the only way to interact with the door is with alt+click on the floor.

I asked another player, they saw the same.. nothing.

**Comment by redmoogle** [comment]
This helps alot more, i thought you meant with the paintsprayer sprite selection

**Comment by redmoogle** [comment]
Unique to the /hatch variant of doors
