### ISSUE TITLE
Lings can remove mindslave at will with horror form

### ISSUE THREAD

**Issue by puremanbird** [yogstation13/yogstation#1039]
Is this a joke?

**Comment by ShadowDeath6** [comment]
This isn't intended but lings are notoriously resistant to mind control

**Comment by puremanbird** [comment]
Then make the lings resist the implant without destroying it or something. Right now they get the mind slave message like anyone else would, so a ling that removes their implant is like an ai requesting antimov. The mindslave costs too much TC to have it wasted.

**Comment by vladlds** [comment]
>lings are notoriously resistant to mind control

@ShadowDeath6 can you link me where is that coming from?

**Comment by ShadowDeath6** [comment]
I'm working on having them just push the implant off or something without consuming it

I also don't have a source, but it's the same reason that loyalty implants don't/didn't work on non-conversion based antags in the past. Mindslave shouldn't work on traitors for the same reason, but that's more of a balance pass than anything else considering that it's much harder for them to just bug it out of their body.
