### ISSUE TITLE
Pacifist Doctor unable to "operate" on patients without direct assistance from patient or bystandard.

### ISSUE THREAD

**Issue by makkenhoff** [yogstation13/Yogstation#1041]
[Round ID]: # 16355 (prior round)

[Reproduction]: # In order to do surgery, you need to place them on an operating table. If you have the pacifist trait, you cannot place them on a table because you need a 'stronger' grip. This is not a bug per se, as it was intended to prevent harm, not helpful surgeries. This could lead to a pacifist doctor being unable to operate on a critical patient.

**Comment by Altoids1** [comment]
Is this still a thing?

**Comment by makkenhoff** [comment]
Haven't played Yogstation in awhile, it got to where it wasn't medium anymore. Easy to test though, try to put someone on the surgical table as a pacifist, if it still requires a stronger grip, you can't do it by yourself.
