### ISSUE TITLE
AI sees gases where there are none

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#1042]
This is a bug I have encountered repeatedly as AI now. I'll go to deal with a flood of whatever somewhere and then near by I will see more of it but it isn't really there and never goes away. It's getting annoying and I have falsely shouted plasma in the halls and shit because of it.

**Comment by Smudged** [comment]
Could it have been glitter in any of the cases?

**Comment by MegaEmpirical** [comment]
Yes, and it was in one case... that was funny/sad. However, this was not so in other cases. If I disconnect and reconnect, they go away and it's usually the same gas as whatever was just flooding an area.

**Comment by 00aquir** [comment]
yes same for crew sometimes

**Comment by MegaEmpirical** [comment]
Forgot about this one, haven't noticed it in a long time so yeah, resolved.
