### ISSUE TITLE
No critical overlay / sleep overlay

### ISSUE THREAD

**Issue by maxion12345** [yogstation13/Yogstation#10437]
Issue reported from  Round ID: 32876 (Yogstation 13 RP)

Reporting client version: 513.1536

When asleep/crit, there is no overlay (darkness, the white when near death, etc)

**Comment by SomeguyManperson** [comment]
this is a clientside issue that can generally be fixed by closing and reopening the game, not sure what causes it or if there's anything else that'll fix it

**Comment by UselessTheremin** [comment]
yeah this is clientside
