### ISSUE TITLE
One of holoporosites is OP

### ISSUE THREAD

**Issue by vladlds** [yogstation13/yogstation#1043]
I don't know which one of them and I couldn't find damage data except for https://tgstation13.org/wiki/Holoparasite , so I suppose it must be standard one.

My health before attack: 100%
Defended by HoS standard gear: -10% brute from security jumpsuit for arms/legs (?)
It made 2 hits, first one dismembering my left arm, second one dismembering left leg, resulting in KO I never could get up from - I think next attack has put me in crit.
All this time its owner could do anything else not even participating in combat with me.

IMO it's unbalanced. most of the time traitor can fight against one enemy at time, slipping/stun-proof holoporosite able to deal 1vs1 and even if something goes wrong his ability to pull stunned host is overwhelming.

**Comment by 00aquir** [comment]
I was a "bit" annoyed once too when I "tried" to fight a holo who easily outran all kind of laser beams! It ran left and right and when it passed I only saw ONE frame of it.. and it can also pull the owner with him.

**Comment by vladlds** [comment]
"Admin said the idea is that I have to target the owner rather than the holo" - that was Adam, I suppose. It won't work though in most of the cases when host and holo are competent.

We need public competition test when geared up traitor will fight standard equipped security 2vs1, 2vs2 and maybe even 2vs3 where second number is amount of security officers. They will get rekt so hard.

**Comment by puremanbird** [comment]
someone went on a huge holoparasite buffing spree when they really weren't weak to begin with.

**Comment by X-TheDark** [comment]
The problem is, I'm not sure how it's possible for a holoparasite to dismember with one hit. Any kind of information would be useful.

Did it spam your chat with "ATATATATATATATATAT" messages and the like?

**Comment by AdamElTablawy** [comment]
that was asssassin holo, the shit shadowdeath decided to buff

that specific holoparasite is intentionally overpowered in 1v1 and absolutely useless against large crowds. it can do heavy damage when it attacks someone alone and is easy enough to kill the hos with it, but 2 people or more, even an assistant, and it's dead.

also, armor doesn't do shit in general-it's basically paper.

**Comment by ShadowDeath6** [comment]
yeah I added assassin holos being able to dismember on hit because they sucked ass

their stealth attack is meant to ignore armor and has a high chance of dismembering the limb hit

**Comment by Paragonid** [comment]
I don't know mechanics, but I was dismembered and it didn't feel like "stealth". There was 4 people around, holo comes up to me, hits to death in seconds and continue fighting the rest of people around.

**Comment by Super3222** [comment]
It's overpowered.

**Comment by puremanbird** [comment]
it can hit, re-enter the dude, come back out in stealth, and hit again extremely fast.

**Comment by ShadowDeath6** [comment]
It can't come out while stealthed, but it can stealth like half a second after it comes out. Its strength is balanced out by the fact that literally all damage to the holo is transfered to the host.
