### ISSUE TITLE
Space pod tab not appearing

### ISSUE THREAD

**Issue by Dannyjake** [yogstation13/Yogstation#10445]
Issue reported from  Round ID: 32888 (Yogstation 13 RP)

Reporting client version: 513.1536

When you build a space pod and enter it, the space pod tab does not all ways pop up.

**Comment by redmoogle** [comment]
Fixed by: https://github.com/yogstation13/Yogstation/pull/10569

(Testmerged RN: will more than likely stay TM until merged)
