### ISSUE TITLE
Players able to be intentionally revived as husks

### ISSUE THREAD

**Issue by jachlompsky** [yogstation13/Yogstation#10455]

**Comment by redmoogle** [comment]
Has science gone too far. ~~this should just be labeled a feature tbh~~

**Comment by jachlompsky** [comment]
Yeah admin told me it didn't seem round-breaking, but cause it's a bug, I should report it anyways. Btw when I said "constantly bleed" I mean that husks have the "bleeding" status, but they don't drip blood anywhere and if bandaged they just bleed again.

**Comment by redmoogle** [comment]
"Feature"
