### ISSUE TITLE
Cyborgs suffer damage slowdown in 0G

### ISSUE THREAD

**Issue by maxion12345** [yogstation13/Yogstation#10490]
Issue reported from  Round ID: 32972 (Yogstation 13 RP)

Reporting client version: 513.1536

Cyborgs suffer damage slowdowns in 0 G environments. Not sure if intentional, because pretty sure humans dont suffer slowdowns in 0 G

**Comment by redmoogle** [comment]
Humans should have damage slowdowns :thonk:

**Comment by Takahiru** [comment]
I just tested it and it is a proper bug, borgs aren't supposed to get slowed by damage at all but when in space and damaged they get slowed.

**Comment by adamsong** [comment]
Borgs get slowed by damage in full g now, is this issue resolved?
