### ISSUE TITLE
no self destruct button as syndiborg

### ISSUE THREAD

**Issue by maxion12345** [yogstation13/Yogstation#10512]
Issue reported from  Round ID: 33038 (Yogstation 13 RP)

Reporting client version: 513.1536

no tab at all

jamiesi plz phix

**Comment by Altoids1** [comment]
![image](https://user-images.githubusercontent.com/29939414/101068525-71f4d200-355e-11eb-807e-5fe90195a1ac.png)

Couldn't reproduce it.

**Comment by redmoogle** [comment]
Supposedly fixed(?) Reopen/remake if it persists
