### ISSUE TITLE
Broken Atmos doesn't burn correctly anymore

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#10549]
That 5 layer burrito thing that was added last week broke atmos burn mixes.

**Comment by burn1cycle** [comment]
After testing I found the problem you basically need this https://tgstation13.org/wiki/Machines#Electrolyzer for max caps but we don't have one.

**Comment by ToGWtF** [comment]
Fixed in https://github.com/yogstation13/Yogstation/pull/10505

**Comment by burn1cycle** [comment]
Thanks! Being able to do hydrogen bombs made all the difference: 
[Common] The tachyon-doppler research array states coldly, "Theoretical: Epicenter radius: 2249. Outer radius: 4499. Shockwave radius: 8999."
