### ISSUE TITLE
YogStation Broken pipes

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#10579]
Waste loop for Medbay Treatment center on the YogStation(box) map doesn't go anywhere.

**Comment by patpol4** [comment]
Incredible mapping, whoever did this is really bad and stupid 
![chrome_XyfNjpqZJR](https://user-images.githubusercontent.com/48154165/101288017-51de4080-37f4-11eb-98f9-04894dbee113.png)
