### ISSUE TITLE
Cannot create grenades with igniter-proximity sensor assembly.

### ISSUE THREAD

**Issue by CzarSilvestrini2** [yogstation13/Yogstation#10578]
## Reproduction:
I don't think it's possible to create grenades with the igniter assembly at the moment. I tried to follow the wiki's steps for [creating grenades](https://wiki.yogstation.net/wiki/Grenade)  , but when I try to use the screwdriver at the assembly to change it to attachment mode, it disassembles the trigger and drops both the igniter and proximity sensor on the ground.

I've found no way to attach it to the grenade. And using the proximity sensor in the grenade's wire also does not seem to work.

I've tested this in a local server running the up-to-date yogstation code. To reproduce, just follow the steps for grenade creation until step 2.4, where you'll be unable to proceed because of the bug (using the screwdriver at the assembly).

![Screenshot 2020-12-03 175525](https://user-images.githubusercontent.com/75451379/101087272-c4e77d00-3590-11eb-9c8c-9533e7394272.png)

![Screenshot 2020-12-03 175313](https://user-images.githubusercontent.com/75451379/101087136-936eb180-3590-11eb-92b5-c494386aebd4.png)
![Screenshot 2020-12-03 175331](https://user-images.githubusercontent.com/75451379/101087145-949fde80-3590-11eb-8450-145cb3546ca5.png)
![Screenshot 2020-12-03 175357](https://user-images.githubusercontent.com/75451379/101087147-95387500-3590-11eb-8481-a01f048f0380.png)

**Comment by redmoogle** [comment]
Wiki(ish?) issue. you have to grab the component eg signaler or prox sensor and set it up by clicking on it with a component then attaching it to the wire.

**Comment by CzarSilvestrini2** [comment]
Possibly, but since nothing else is working, I'd say that it is more likely to be a bug.

Attaching the proximity sensor to the unsecured grenade wire does not seem to work. Also, if I try it with the igniter it gives the message that it "Needs an assembly to be able to attach it".
I also tried all kinds of combinations, prox with cables, prox with grenade casing wire, igniter with cables, assembly (this one without being in attacheable mode, since I can't) with cables. None of them seem to work.

Just for context, what I'm trying to do is a proximity mine with stabilized nitroglycerin. That's why I need the igniter, to heat up the nitroglycerin inside once the proximity sensor triggers.

And, just to throw some extra info, I know that Atmo can create bombs like this. But since we have the info on the wiki, I'll consider that it is implemented until someone who knows the code tells me that the wiki is out-of-date and these types of grenades are no longer available.

**Comment by redmoogle** [comment]
Wiki Updated.
