### ISSUE TITLE
Move ORM so that it can be accessed outside the cargo office. Please, for the love of all that is good, please move it.

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#1059]
Exactly as the title says. It is driving me fucking insane and I know others hate it too. I am about ready to start cuffing every non-supply that walks through that door.

**Comment by Ratvar** [comment]
Cut every non-supply that walks through the door instead, maybe? You kinda can. And call security.

**Comment by MegaEmpirical** [comment]
I would love to, believe me. The miners too.... I think they're all usually lazy.... especially the medic.

**Comment by MegaEmpirical** [comment]
Closing because of:

https://github.com/yogstation13/Yogstation-TG/pull/2760
