### ISSUE TITLE
Duplication glitch -- Robotics

### ISSUE THREAD

**Issue by madruckus** [yogstation13/Yogstation#10608]
If you click twice when you put the posibrain/B.O.R.I.S module inside of a cyborg, it'll pick up an empty finished cyborg with no battery. However, it will have fully cloned every other part.

**Comment by TheReddDragon** [comment]
Investigating.

**Comment by TheReddDragon** [comment]
@redmoogle cannot confirm, you might have better luck

**Comment by adamsong** [comment]
Also unable to reproduce
