### ISSUE TITLE
Showers don't put out fires

### ISSUE THREAD

**Issue by AmeloraIsTaken** [yogstation13/Yogstation#10611]
## Reproduction: Set yourself on fire, step into a shower

Showers fail to put out fires as opposed to how they previously functioned. I got caught in a plasma fire in atmos and rushed to the shower, where there was no fire. The shower failed to extinguish me. Several rounds later I stepped in lava on lavaland and ran to the shower in the airlock. Once more, the shower failed to extinguish me.

**Comment by ToGWtF** [comment]
It wont work if you turn it on while under it. You need to turn it on then get under, or step away and step back under it

**Comment by ToGWtF** [comment]
https://github.com/yogstation13/Yogstation/pull/10630
