### ISSUE TITLE
Fugitives is a broken mess

### ISSUE THREAD

**Issue by maxion12345** [yogstation13/Yogstation#10620]
Issue reported from  Round ID: 33215 (Yogstation 13 RP)

Reporting client version: 513.1536

![](https://i.gyazo.com/a395a2dba86029995b5f26ae1fd05113.png)

spawned both spacepol/russians, spacepol couldn't move their shuttle admins had to spawn another and teleport over, says fugitives didn't spawn but they did, etc etc

**Comment by ToGWtF** [comment]
Was adminbus.

Not taking away from the fact that fugitives is a mess.
YalpElor fugitives didnt spawn correctly so it was triggered again
