### ISSUE TITLE
Today I made a sun in toxins and it melted plasma tanks

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#10623]
When I say tanks I mean the tanks you connect to the TTV. My plasma was over 1.7 million degrees Celsius and when the tanks were filled and removed from their source(we tried both portable air pump and canister) they would vanish but leave behind a burning hot cloud of plasma.  Xoxeyos was administrating and also witnessed the problem, he guessed it might be the low amount of plasma moles in the tank if I understood him correctly.

A guy who was watching me came up with the idea to stick the tanks on the valve as soon as we pulled them off the pumps and this worked keeping the tanks from vanishing. This was the bomb score:
Epicenter radius: 3. Outer radius: 6. Shockwave radius: 12."
"Theoretical: Epicenter radius: 2776. Outer radius: 5553. Shockwave radius: 11107."
$51670.8, with a reward of 51670.8 points."

Round ID:33221

**Comment by ToGWtF** [comment]
Internal tanks have both a max pressure, which they will leak if gone over, and a max temperature which will "melt" them.

Specifically, the max temperature is 1million.

**Comment by boodaliboo** [comment]
i dont think that something melting at 1.7million degree is a bug
