### ISSUE TITLE
polysmorpth clothing, underwear and undershirts are kinda wonky

### ISSUE THREAD

**Issue by overlord12345** [yogstation13/Yogstation#10647]
naked polysmorpth:
https://imgur.com/hmR0yPr
the bodyshape is unlike other female characters which causes some issues with clothing.

polysmorpth with babydoll underwear:
https://imgur.com/hTFjDHZ
the body shape has changed and since its see trough it looks like the polysmorpth has breasts which it dosent normaly.

polysmorpth and human in ladies' thong underwear:
https://imgur.com/k5hQ5wu
https://imgur.com/9rOsIOQ

the polysmorpth is missing 1-2 pixels.

polysmorpth in a shirt(grey) undershirt:
https://imgur.com/WuHQ7JQ
the body shape has changed.

polysmorpth with a normal jumpsuit:
https://imgur.com/314THkX
the body shape has changed.

the same issue happens with other clothing, underwear and undershirts, i picked these as it can be seen clearly

theres also this
ladies' white neko underwear human and polysmorpth: 
https://imgur.com/agkFLvW
https://imgur.com/JkYdx3C
the polysmorpth has a few extra pixels or something and is missing one pixel in the bra area.

**Comment by Mqiib** [comment]
Fixing this requires figuring out how the fuck the code works for changing the appearance of clothing from male to female versions. Totally possible though, as I can see a "skinny" version of clothing working.

**Comment by Mqiib** [comment]
Am working on a fix

**Comment by overlord12345** [comment]
> Fixing this requires figuring out how the fuck the code works for changing the appearance of clothing from male to female versions. Totally possible though, as I can see a "skinny" version of clothing working.

wouldn't the easiest fix be to just give them the body shape every other female version of a roundstart race has?

**Comment by Mqiib** [comment]
> > 
> 
> wouldn't the easiest fix be to just give them the body shape every other female version of a roundstart race has?

Yes but that would make them even more "human but not" and thus less interesting. Also that would be easy and easy is boring too!
