### ISSUE TITLE
Cant launch multiple auxilery bases

### ISSUE THREAD

**Issue by AustinnK** [yogstation13/Yogstation#10666]
Round ID does not apply, I tested it out on a privately hosted server.

## Reproduction:

First, create and launch an auxiliary base/probe, deconstruct the management console, reconstruct it in the auxiliary base construction zone and attempt to launch, it'll say that its launching but nothing will happen. The wiki states that you can launch multiple auxiliary bases. PS: trying to build windows with the drone will deconstruct and trying to deconstruct will do nothing.

**Comment by TheReddDragon** [comment]
@JamieD1 this isnt a bug, is it?

**Comment by jcatjmeow** [comment]
The wiki is wrong. 

Sadly, you cannot launch multiple aux bases, although I would like to code this in the future
