### ISSUE TITLE
Preternis mutate in radstorms

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#10675]
Issue reported from  Round ID: 33334 (Yogstation 13 RP)

Reporting client version: 513.1538

I'm pretty sure that I've personally shot down every PR that was supposed to make preternis act more like inferior organics, but something must've slipped through. Radstorms cause preternis to mutate now. They're still immune to rads, though.
Please stop touching my OC species.

**Comment by TheReddDragon** [comment]
will investigate
