### ISSUE TITLE
invalid poster shows up in maint generation

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#10723]
## Round ID:

33432

## Testmerges:

#9953 
#10538 
#10602 

## Reproduction:

invalid poster shows up in maint generation
![](https://i.imgur.com/aPl5Pnw.png)

**Comment by maxion12345** [comment]
I say leave it in as a feature 👍

**Comment by ToGWtF** [comment]
The templates have on the walls /obj/structure/sign/poster/contraband
 when it needs to be /obj/structure/sign/poster/contraband/random

Yogstation/_maps/RandomRuins/StationRuins/maint/5x4/5x4_posterstore.dmm

**Comment by ToGWtF** [comment]
/obj/structure/sign/poster/official
probably should be
/obj/structure/sign/poster/official/random

10x10boxfactory
5x4posterstore
