### ISSUE TITLE
Defibs don't heal defibbed preternis, sometimes making them secretly and buggily undefibbable

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#10737]
Issue reported from  Round ID: 33460 (Yogstation 13 RP)

Reporting client version: 513.1539

I noticed I met all the criteria for being defibbable, but I wasn't waking up when the CMO did the shocky thing. I asked admins to defib me and tell me what message popped up, suspecting a bug
----------------------------------------------------------------------------
-- Administrator private message --
Admin PM from-ThatOneGuyWithTheFace: Successfull lmao
Click on the administrator's name to reply.
DEAD: IPHI-GEN intones, "debug ERT"
DEAD: (Nechronom) Argema Insularis hisses, "haha"
-- Sniblet -> Admins: epic coders break preternis completely once more, thanks
...
Health scan enabled.
Analyzing results for IPHI-GEN:
	Overall status: Deceased
	Severe tissue damage detected.
	Severe burn damage detected.
	Subject has the following physiological traits: Musician, Light Step, Light Drinker, Heavy Sleeper.
	Brain Activity Level: **80.528%.**
	==EAR STATUS==
	Subject has temporary hearing damage.
	==EYE STATUS==
	Healthy.
	Damage: Brute-Burn-Toxin-Suffocation
		Specifics: **112.7**-**170.8**-0-0
		Chest: 5.2-119
		Head: 88.1-0.4
		Left arm: 5-25.6
		Right arm: 4.9-15.1
		Right leg: 4.8-10.4
		Left leg: 4.7-0.3
	Mildly Damaged Organs: **heart**, stomach, ears
	Severely Damaged Organs: 
	Non-Functional Organs: 
	Genetic Stability: 60%.
Species: **Preternis**
Body temperature: 20.8 °C (69.4 °F)
Time of Death: 10:46:55
Subject died 1 minute and 44.2 seconds ago, defibrillation may be possible!
Subject is bleeding!
Blood level 94 %, 529.021 cl, type: A+
Detected cybernetic modifications:
IPHI-GEN is modified with a Reviver implant.
IPHI-GEN is modified with a implantable thrusters set.
IPHI-GEN is modified with a integrated toolset implant.
IPHI-GEN is modified with a surgical toolset implant.
IPHI-GEN is modified with a breathing tube implant.
IPHI-GEN is modified with a CNS Rebooter implant.
IPHI-GEN is modified with a anti-drop implant.
IPHI-GEN is modified with a Medical HUD implant.

*---------*
This is IPHI-GEN!
She is wearing  an engineer's jumpsuit with  a service guard armband.
She is wearing  an engineering beret on her head.
She is wearing  a hazard vest.
She is carrying  a T-ray scanner on her hazard vest.
She has  an industrial satchel on her back.
She has  some insulated gloves on her hands.
She has  a toolbelt about her waist.
She is wearing  some work boots on her feet.
She has  a welding mask on her face.
She has  a night vision meson scanner covering her eyes.
She is wearing  PDA-IPHI-GEN (Station Engineer).

**She is twitching ever so slightly.**

She is limp and unresponsive; there are no signs of life...
She has severe bruising!
She has severe burns!
She is bleeding!

Traits: Musician, Light Step, Light Drinker, Heavy Sleeper

*---------*
Health scan disabled.
----------------------------------------------------------------------------

-Sub-180 damage in burn and brute
-Ghost in body
-All organs in good-enough shape
-I was on a stasis bed so none of this changed between the attempted revive and the ghost healthscan
-_Defibrillator reads "successful"_
-Sad! Preternis stays dead

redmoogle says it's because I was damaged enough to have died in the first place, therefore I died again. I believe it.
With any species except preternis, the defib would heal the patient enough to live if the defib were successful.
Preternis don't get this healing for brute and burn because they don't get any such healing not specifically included in the shortsighted whitelist given to us by Alexkar, God of Preternii, so they die again instantly if their flesh wounds exceed 200 total, and no one involved gets any feedback as to that being the issue.
Time of death didn't reset and I didn't even appear in ghost deathrattles. By all appearances, except for the defib's "successful" message, I just never got revived.
There should either be some kind of feedback to clearly explain why it isn't working, or preternis should get the defib heal.

And unrelatedly, if you're going to give them the defib heal, kindly give them sentinel's compromise and vitality matrix and fleshmend and blood pylon healing while you're at it, because sometimes the healing that doesn't work on preternis even though it should by all sane reasoning is just dumb.

**Comment by ToGWtF** [comment]
I was wrong. You had 112 brute + 170 burn. You were too damaged to defib, but it said successful anyway, and didnt revive you

**Comment by Sniblet** [comment]
> I was wrong. You had 112 brute + 170 burn. You were too damaged to defib, but it said successful anyway, and didnt revive you

In my experience it needs _either_ 180 brute or 180 burn to block defib, 179 of both would still allow a successful defib
Unless this has been changed super recently, like in the past week, that isn't the issue

**Comment by redmoogle** [comment]
You die instantly due to having too much damage hence the successful message

**Comment by ToGWtF** [comment]
I didn't revive him though. There was "Defib was successful message" but no death message after that. It just did nothing

**Comment by redmoogle** [comment]
> 
> 
> I didn't revive him though. There was "Defib was successful message" but no death message after that. It just did nothing

more than likely an additional check that says hold up, this aint right chief
