### ISSUE TITLE
Revoke full access from syndicate cyborgs

### ISSUE THREAD

**Issue by Paragonid** [yogstation13/yogstation#1074]
Syndicate cyborgs have all station access.
Expected: syndicated cyborgs are not related to the station security access systems and don't have full station access.

**Comment by ClaudeWicked** [comment]
No, Im pretty sure the point of a syndicate cyborg is that they're able to access the station.

**Comment by Super3222** [comment]
Syndicate med borgs are meant to have all access

**Comment by ShadowDeath6** [comment]
They're cyborgs. This is intended. It's better than having them emag everything open, anyway.

**Comment by Paragonid** [comment]
I see you rely your answers on the fact that they are cyborgs. I don't understand the connection between being cyborg and having full access. Can anyone explain me it?

> It's better than having them emag everything open, anyway.
Well, it's good that we have better ways for it, something like pAI hacking or agent card access stealing

**Comment by aphielanis** [comment]
Paragonid raises some good points and as Shadow pointed out they have the emag. So why can't they just use the emag and have door access nerfed?

As .it is door control is pretty powerful, we aren't able to tell nuke ops have trespassed a door giving them free stealth and the borg can also bolt, shock or set it to crush

**Comment by ShadowDeath6** [comment]
the reason cyborgs have full access is because they're robots and can interface with any electrical system, same reason that drones can

**Comment by aphielanis** [comment]
I was going to make a point about how if I have a car key for a GMC truck then by your logic Shadow it should open every GMC truck but this actually happened to me.
 I had a red GMC truck at one point, left it out in the parking lot all day came back and found out some jerk must have broke in and adjusted the seat and mirrors, I then noticed that none of the stuff in the cab belonged to me, I figured this was not my car after noticing this and then tried starting it and it did start. It turned out GMC went cheap on randomizing my model of cars' keys.

 But still, the basic logic of my argument should apply in that just because it's a borg doesn't mean it should have NT-Borg access to everything on the station, heck their not even made by the same company :).

**Comment by Paragonid** [comment]
> they're robots and can interface with any electrical system

Electrical systems are quite diverse, I guess that's another "factory would do same wires" issue. I suppose cyborg is computer-alike systems, well then there are millions of ways they can prevent access of other unwanted programs.
Station borgs and drones due to space magic have station access, it's fine, but things which are not built and belong to the station? Only because you can get guest access to the system through interface doesn't mean you can control it fully.

**Comment by AdamElTablawy** [comment]
Can you stop making retarded requests?

They are expensive cyborgs. They have all access. That's it. Period.

**Comment by Paragonid** [comment]
You can change your opinion and requests will stop being retarded for you, but I guess that's all I can promise. But I like that you feel uncomfortable.

My mac book is pretty expensive PC as well, still it doesn't have access to pentagon. Any ideas why?

**Comment by ShadowDeath6** [comment]
Syndie cyborgs are currently either 60 or 80 tc. That's about a quarter of war ops funding and almost all of a regular ops funding. Your analogy with a macbook is a stupid stretch and you know it, considering a syndieborg is literally a modified cyborg from NT. The correct analogy would be that you had a better computer that used the pentagon's computers as a base but it had a grenade launcher and a burst fire LMG on it.

**Comment by Paragonid** [comment]
Alright, sorry about nuclear syndies round type, let's not discuss syndi borgs there.

Can we talk about syndi borgs during wizard round / magic carp rounds?
