### ISSUE TITLE
Fixing the drones (Overdue)

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#1075]
Obviously, most drones end up griefers. Since it's annoying problem, isn't it possible to basically make them like (wussier) cyborgs?

-No pickups (basically no hands), or at least no way of hitting/dragging (and, if possible breaking things like windows), making "help" the only intent.
-Module system like cyborgs (traditional tool set, soap/cleaner, smart trash bag, light replacer w/ infinite/cooldown bulbs, infinite/cooldown glass/metal/plasteel/wood/whatever stacks)
-Jetpack. WAY too many times I've seen someone (me) hold an arrow too long and forget you can't throw. 
-Alt-click hat copy ability similar to the morph's (no need to pick up the cap's hat and fuck off with it 'cuz style)

**Comment by ClaudeWicked** [comment]
I rarely see griefing drones, and they're outright breaking the rules of the server. I see no reason to change them, though, hat cloning sounds like a good idea, so they dont have to steal them hats for style.

**Comment by nazitra** [comment]
If giving them modules, maybe a pipe dispenser module too for fixing those large breaches?

**Comment by aphielanis** [comment]
Maybe it's better just to catch and punish rule breakers rather than code out fun because a small portion of players can't follow the rules?

**Comment by Drakkon** [comment]
I mean, although I made that the main topic, griffons aren't the only reason. If all this can be ported from cyborgs, make the drones less ghetto than they already are, make it so they don't have to take resources from the crew (which technically goes against the no interaction with crew), and ALSO prevent griefing, why not?

**Comment by EMT321** [comment]
I have rarely seen drones grief.

**Comment by ShadowDeath6** [comment]
Drone dispenser is shit

**Comment by Drakkon** [comment]
Tha hell? Ask anyone on during low-pop hours (when there's usually no staff). When no staff (or Adam) is on, it's pretty much the expected norm for most drones to grief/go against their laws in multiple obvious way. Maybe because those who are bothered to say they'll report it aren't bothered enough to scroll up their logs for the specific drone number (if there's even any evidence on their logs), check the round number, and copy it down into a low-priority ticket they don't expect the admins to care about.

(Not trying to diss the admins, it's just that so many people have said they'll report the drones and there's nothing showing they have.)

**Comment by Super3222** [comment]
Yep, yep. I completely understand your pain, and I've heard it from other players as well. In fact, on a non-bias level I opened up a PR removing the drone dispenser (which created an infinite amount of drones). No one spoke up on it to affirm the PR, and it was pretty one-sided to not merging the PR.

It was up for about two weeks, and than I closed it. I can always reopen it. Here it is -> https://github.com/yogstation13/yogstation/pull/488

**Comment by EMT321** [comment]
I'm confident that drones griefing is not the issue it is being made out to be here.

**Comment by AdamElTablawy** [comment]
I'll be changing drones from a mob to a faux cyborg soon.

**Comment by captainblobfish** [comment]
I do like the idea of adding a drone jet pack or something. Because drones have a really high movement speed and can zoom through doors without opening them. I've flown out of airlocks dozens of times and have gotten stuck in space
