### ISSUE TITLE
Mental Barrier can give revs mindshields, depsite it not supposed to. This does NOT deconvert the rev.

### ISSUE THREAD

**Issue by maxion12345** [yogstation13/Yogstation#10788]
I think they aren't supposed to get it at all, but it'll still show in a hud.

**Comment by adamsong** [comment]
There is code to prevent this, will confirm that it works later

**Comment by Bibby0110** [comment]
Can't confirm this in tests

**Comment by adamsong** [comment]
Cannot be replicated and there is code in place to prevent this. Closing
