### ISSUE TITLE
Darkness of Space

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#1078]
I'd think unlit objects and tiles (especially in space) should be shown (while alive) just as black shapes of themselves (I don't think those background stars are THAT close/bright? >->). Is it possible to make that happen? Better question is: Would I be lynched if it was implemented? EDIT: or if I even mentioned it

**Comment by ShadowDeath6** [comment]
What's blocking the light tho

**Comment by Drakkon** [comment]
I wish I knew how our solar panels worked, but until then, several lightyears of space?

**Comment by Drakkon** [comment]
Actually... are we revolving around a plasma star? I'll accept my stupidity if we are.

**Comment by 00aquir** [comment]
Um. There are solar panels, obviously they are powered by the nearby star:
![tg-station](https://cloud.githubusercontent.com/assets/16806055/19624680/6dd98d98-9902-11e6-8841-6f9ef05ee783.png)

There is no absolute darkness, you can see objects if they are close enough...

**Comment by Drakkon** [comment]
Alright alright. Guess I should've known from the... non-canon picture.
