### ISSUE TITLE
Slashing fabric

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#1079]
Slashing weapons would have a SLIGHT chance (You decide the percentage) to tear fabric off main article off clothing as if removed by hand. Seems like the only acceptable form of clothing deterioration, somewhat realistic, and a slight punishment for spamming fabric off clothing. Wouldn't work for any main article that doubles as armor, or at least  a lesser chance.

**Comment by ShadowDeath6** [comment]
why though

**Comment by Paragonid** [comment]
better add bleeding

**Comment by Super3222** [comment]
Get me a sprite for very small strands of clothing, and I'll see what I can do

**Comment by Super3222** [comment]
@Drakkon
