### ISSUE TITLE
(Request) Add actual Xenos to Lavaland Xeno Hives

### ISSUE THREAD

**Issue by DiamondSentinel** [yogstation13/Yogstation#1081]
So, round that I discovered this in was Round 16400. Now, I know that you can't get regular xeno organs from xenohives on lavaland because TG removed that a long time ago (unfortunate, I know), but it would be nice if you could replace it with an actual xeno, just with organ drops removed (if you absolutely despise having xeno organs out there).

The reason I mention this is that, if you bring a xeno queen back to the station, Lazarus Inject them, and then Mindswap with them, you are completely unable to move. You may only turn and fire neurotoxin or bite things immediately next to you. None of the other powers are available. 

Furthermore, I think that re-adding xeno organ drops from Xeno Hives would be fine, given that we have a bit more strict rules than TG-station about murderboning and generally ruining people's rounds, so if someone were to use them to be a complete shitler, something would likely be done.

**Comment by Ratvar** [comment]
I think that your problem is being able to Mindswap into megafauna/bosses of lavaland, too.

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.
