### ISSUE TITLE
Randomize wires for hacking airlocks

### ISSUE THREAD

**Issue by Paragonid** [yogstation13/yogstation#1082]
Currently each airlock on the station (high tech security airlock is exceptional group?) have same hacking wires. This allows to hack any airlock in 3 seconds if you know wires.
Random wires would make process more realistic and airlock "security" would actually make sense.

**Comment by Time-Green** [comment]
How would it be?
So they decided to make every door unique?
Factory made stuff is all the same, this would be an extreme nerf and wouldn't make sense at all

**Comment by X-TheDark** [comment]
He probably means that every airlock "type" should have their own randomized wires, as in, for example, Engineering Airlocks have the same wire configuration, but Common Access Airlocks have a different one (but still same within their type).

**Comment by Time-Green** [comment]
Ooooooh.
That makes sense I guess. I am still not a fan, but I can see how it would work

**Comment by Paragonid** [comment]
Well, no I meant each airlock in particular.
Sure, keep the wire color, I don't mind, that's what factory would do. Change their order in the hacking menu instead. Doors will be all the same, but it will be realistic that you actually have to find correct wire from [bunch of them](https://thumbs.dreamstime.com/z/bunch-wires-29628495.jpg).

What does it nerf? Restricted access time for assistants? It's good.

**Comment by X-TheDark** [comment]
Erm...in that case, the idea, in my opinion, is completely unnecessary, as people will just remember wires by colors, which is not hard.

**Comment by Paragonid** [comment]
there's huge difference between always pulsing first wire and searching for slightly more than green or kinda blue wire in stressful situation for each door.

**Comment by Super3222** [comment]
This'll cause a civil war between the coders and the powergamers.

**Comment by ShadowDeath6** [comment]
there's a difference between randomizing generated code shit and randomizing physical doors

also this is either a massive nerf by randomizing wires per door considering you can shock yourself on any door you hack no matter what wires you memorize or not a nerf at all considering you can just type "BLUE = TEST WHITE = BOLT" and have no actual problems beyond that

**Comment by puremanbird** [comment]
Not unless you revert the shitty change adam made where doors instant crit you on shock.

**Comment by ShadowDeath6** [comment]
>shitty

*************************************************

**Comment by Paragonid** [comment]
Oh hell, are you really arguing about possibility of using different color wires during automated manufacturing? SS13 itself isn't even close to be realistic, where for example "laser" gun projectile is slower than running human. 

[https://www.youtube.com/watch?v=9cOBirxSUc0](These automated manufacturing machines) are controller fully by the code. There are tons of way to make them use wires of different color. If you really doubt it I'll go waste some time and bring you technical descriptions of such machines. [Here's](https://www.youtube.com/watch?v=Y7jdpcpl3ws) the autoCAD alike software to control those machines.

It's my mistake for using triggering world realistic. the point of my suggestion is not realism though.

**Comment by Time-Green** [comment]
Actually, you're not faster then a laser.
I tried.

Unless you mean yourself, you're yourself

**Comment by EMT321** [comment]
I think this is a good idea, and makes insulated gloves valuable again.

**Comment by aphielanis** [comment]
This is a nerf to antagging and I think antagging is already hard enough.

**Comment by vladlds** [comment]
Antags have many other ways than plain hacking. Some of them rarely used because hacking is so easy.
Plain hacking is for assistants. Security has to hack quite often as well just to follow both antags and assistants.

I don't know why do you think antagging is hard, maybe you should discuss it as well. I personally feel pretty good as antag, can kill whole security force with couple toys. And yeah, what's fun in easy antagging anyway.
