### ISSUE TITLE
THE GATES OF HELL AND TINFOIL HATS

### ISSUE THREAD

**Issue by ghost** [yogstation13/Yogstation#10836]
Issue reported from  Round ID: 33631 (Yogstation 13 RP)

Reporting client version: 513.1527

Step 1: spawn in as space bartender.
Step 2: hack your autolathe for extra shit.
Step 3: misc category.
Step 4: watch as the gates of hell and tinfoil hats opens before you.
![image](https://user-images.githubusercontent.com/63614296/104034158-8734d000-519e-11eb-97cc-2a180a3ee17e.png)

**Comment by Marmio64** [comment]
tinfoil hat king hacked the autolathe, totally a feature, nothing to see here
