### ISSUE TITLE
Security Borg Invisible

### ISSUE THREAD

**Issue by TransAggressive** [yogstation13/Yogstation#10840]
## Reproduction:

Was running AI, and borg was created mid-round, assigned engineering. Left borg in robotics, prompted robotics to produce security borgs due to unprofitable situation snowballing. Returned to borg after to discover was... invisible. I assumed was a display issue (AI life), but when was commented by someone else, ahelped.

**Comment by adamsong** [comment]
Likely caused by donor skin, fixed in #11064
