### ISSUE TITLE
Can mindswap into Lavaland Xenos mobs, including megafauna boss queen

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/Yogstation#1085]
Can mindswap into megafauna-level fauna
Can mindswap into broken mobs you can't control

**Comment by DiamondSentinel** [comment]
The xeno queen is not even close to megafauna level. For starters, she has 200 health. The exact same as a player. (the difference is she regens 1 health per tick on weeds and crits at all 200, not 100). Secondly, she doesn't one-shot anyone. 

For comparison, the blood drunk miner, the weakest megafauna, has 950 health. 

There is no way to mindswap into any megafauna. This includes Ash Drake, Bubblegum, Colossus, Swarmer Beacon, Legion, and Blood Drunk Miner.

Finally, the Xeno queen, even when actually functional, is no more powerful, and is probably strictly weaker, than a changeling, which xenobiologists can get every round, and quicker than a queen.

**Comment by ThatLing** [comment]
Feature:tm:

**Comment by KrabSpider** [comment]
They can also lay eggs too, on top of being lava immune. That's definitely worth oatching up
