### ISSUE TITLE
removes snowflake magical turrets from electrified grills

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1091]
Electric grills throwing out chain lightning because something was thrown at them was never a good feature for multiple reasons. It does not shock the person specifically who threw the object but instead gets everyone near by and can even miss the person who threw the object in the grill. Sometimes it even puts up a giant road block to antagging, blocks off access that might be needed in an emergency, and adds security to the map design that was never meant to be a part of the map, and it was never balanced out with a reduction in security in some other area to cause a proportionately equal vulnerability.

 My other issue is that electricity doesn't work like this. It would take millions of volts at hundreds of amps to throw off a bolt into the air, the bolt's direction would be extremely random, it would most likely arc to the nearest metal surface and not a more distant resistive human body, a ungrounded object being thrown into the electrical field would have no effect, other than to charge the object and discharge it as soon as it touched ground. It's cringe-worthy of how much snow flake magic is perverting a law of science.

 My closing thoughts are this was a feature that was added by someone who doesn't understand the subtle nuances of the game with how there was never a vulnerability added to compensate for buffing security in another place giving the protagonists advantage and the antagonists disadvantage.

**Comment by Time-Green** [comment]
How else am I supposed to electrocute the HoP and everyone else near him?
Like, I could make a tesla engine there but that would be re- hmmmm...

**Comment by X-TheDark** [comment]
I'm pretty sure this was implemented (by /tg/) with the sole purpose of preventing shitters from breaking out of brig cells due to security incompetence/being broken out of by some random greytider.

**Comment by ShadowDeath6** [comment]
>hitting a supercharged grille with a toolbox in hand is safer than throwing said toolbox at said grille from 10 feet away

Balling

Also if you manage to break out of jail as a prisoner sec sucks at the game considering nothing available to you can break windows

**Comment by aphielanis** [comment]
Those brig windows also already have activate-able blast doors.

**Comment by Kmc2000** [comment]
Egh seeing as ive died to this when the tesla was set i feel ya


Perhaps we should alter it, so that it just throws sparks, as in light breaking sparks, off the grille.

As for the greytiding stuff, a good greytider doesnt use the windows anyways.

**Comment by darkwahn** [comment]
Yeah, it's pretty silly and removing or changing it could only really be beneficial.

**Comment by AdamElTablawy** [comment]
general consensus is no
