### ISSUE TITLE
Morph airlock disguise has no sprite and therefore no way to remove disguise

### ISSUE THREAD

**Issue by AJHcHenry** [yogstation13/Yogstation#10923]
## Round ID:
33842

## Reproduction:
I spawned in as a morph and changed into an airlock (named Port Quarter Solar Access). Upon doing so, my sprite totally disappeared, and I can no longer change back into my original form by any means, effectively ending my round.

**Comment by MegaEmpirical** [comment]
This is a reoccurring issue that I keep see players run into. So far I have seen it with the gravity generator and one of the telecomm machines.
