### ISSUE TITLE
AI shell teleporting to mech bug.

### ISSUE THREAD

**Issue by Obscarna** [yogstation13/Yogstation#10936]
## Round ID: 
33896

## Reproduction:
As an AI shell using a mech I attempted to enter another mech without first exiting the mech I was in. This caused my AI shell to be teleported onto the same tile as the new mech. The camera was then locked to the shell and any attempt to move the camera the message "You climb out of the durnad" plays and I would teleport the shell back on top of the mech wherever the mech was moved. When I was carded attempting to move my camera would warp me right back into the shell and back on top of the mech. Carding the shell and putting it into the mech was a solution found but it severly restricted what I could do as an AI. As there were multiple AIs that round my name was M.A.D.U.S.A.

**Comment by Moltijoe** [comment]
outdated with the ai rework
