### ISSUE TITLE
Mobs with PASSTHROUGH can't pass through windoors/firelocks they share a tile with

### ISSUE THREAD

**Issue by DerelictDrone** [yogstation13/Yogstation#10940]
## Reproduction: 
Turn the fire alarm on in any room, then try to walk through one of monster's firelocks.
Try to enter the genetics monkey pen, but find you can't ever leave(unless you're a drone)

Drones and mice cannot seem to pass through firelocks or windoors that they share a tile with, and need to open them(which they will do if possible) to escape.

Example of a mouse who has been trapped due to unpowered firelocks(and a particularly bad fire)
![image](https://user-images.githubusercontent.com/57756830/106304485-03ac5300-6221-11eb-8d07-327340d82eee.png)

Gif showing the bug occurring with windoors and drones.
![passthrough](https://user-images.githubusercontent.com/57756830/106302841-14f46000-621f-11eb-854b-f21fb7aef3b1.gif)

**Comment by redmoogle** [comment]
is your server up to date, https://github.com/yogstation13/Yogstation/pull/10773 fixed this

well this fixed windoors but, dunno about the firelocks

**Comment by redmoogle** [comment]
well this fixed windoors but, dunno about the firelocks

**Comment by DerelictDrone** [comment]
> 
> 
> is your server up to date, #10773 fixed this
> 
> well this fixed windoors but, dunno about the firelocks

Just tested it with some fresh code, windoors are fixed but firelocks are still doing the same thing as the windoors in the gif are.

**Comment by Cartlord** [comment]
I can confirm this still occurs with firelocks and drones

**Comment by adamsong** [comment]
Still an issue with firelocks and drones
