### ISSUE TITLE
Gas system completely wrong and removing all gases in the game by dividing them by zero.

### ISSUE THREAD

**Issue by Doominuke** [yogstation13/Yogstation#10951]
The code for the gasses keeps dividing all the tanks and canisters by zero and removing all the gasses entirely. It says something about extools and null. I can share screenshots or my compiled code if anyone needs it.

**Comment by jcatjmeow** [comment]
> The code for the gasses keeps dividing all the tanks and canisters by zero and removing all the gasses entirely. It says something about extools and null. I can share screenshots or my compiled code if anyone needs it.

Yes this would be nice bc i dont really know what you mean otherwise

The screenshots i mean. Your code isnt necessary unless you modified it

**Comment by Doominuke** [comment]
Sorry for not responding faster, I didn't get a notification and didn't think anyone would reply fast. Anyways, I meant screenshots of the Dream Daemon runtime or log if it makes one. I've run a server for myself before with code from a couple months ago and it was fine, so I'm not sure what i did wrong.

**Comment by adamsong** [comment]
I've not seen this happen, and it would be a very obvious bug when it does happen, do you have any further details?

**Comment by Doominuke** [comment]
From what i could tell, it was a problem with the byond client. The newest builds apparently handle the atmospherics incorrectly. I had talked to some coders on the Yogs discord and they gave me a link to an older build of byond, so that's how I'm basing my explanation. Nothing wrong with Yogstation code, just byond being funky.

**Comment by adamsong** [comment]
Should I close this then?

**Comment by Doominuke** [comment]
Yes please, thank you.
