### ISSUE TITLE
Sec Hud and Welding Mask does not blind you

### ISSUE THREAD

**Issue by halander1** [yogstation13/Yogstation#10967]
## Round ID: 33982

I was wearing SecHUD sunglasses and a welding helmet when i was welding. The status display on the right side indicated i was blind but I could see my screen fully just fine.

**Comment by redmoogle** [comment]
ummm chief, thats because you had the welding helm and sunglasses

**Comment by redmoogle** [comment]
ummm chief, thats because you had the welding helm and sunglasses

**Comment by halander1** [comment]
Isn't that supposed to black out my screen like when i am normally blind?

**Comment by redmoogle** [comment]
Normally yes, if you can reproduce it then it is a bug, but sometimes overlays break randomly

**Comment by adamsong** [comment]
Should this bug remain open? It seems to have just been left at 'overlay bug, won't fit'

**Comment by UselessTheremin** [comment]
this is likely a byond issue, sometimes overlays just break sometimes, not something i think could really be solved
