### ISSUE TITLE
Buff brute and burn surgery

### ISSUE THREAD

**Issue by puremanbird** [yogstation13/yogstation#1098]
It should remove all of the damage in one surgery, instead of only like 40 like it currently does. If they are messed up enough that they need surgery to be able to defib them, it simply takes too much time and resources to surgery them eight times. By the time you've got the brute and burn damage low enough to defib their heart will have decayed past the point of return.

**Comment by Super3222** [comment]
It should heal 50.

**Comment by puremanbird** [comment]
50 is too low. Its almost impossible to fix enough damage in time to be able to defib them without completely giving them a new heart, and at this point its simpler to just clone the guy which should not be the case. Theres a ton of ways we could improve this. We could either speed the steps up to instant with this particular surgery. We could make the surgery steps heal way more. We could come up with an easier way to get new hearts for transplant. We could make heart repair surgery a thing. Taking the more complicated rout of actually trying to repair a dead body should be more rewarding if done right then just throwing them in the cloner.

**Comment by Super3222** [comment]
I meant right now, it should heal 50. That's at least what I think it was after I ported it from our old repo.

Pretty sure the prime aspect of the feature was how it was able to save people from husking. You perform the surgery, lessen the amount of brute or burn damage they have, get it under 200, and than you can defib them.

Heart Repair surgery doesn't sound bad, but I'm not sure how or where it'd fit in terms of use in the game. Like when will it be used in the game? Those types of questions.

I don't think we should speed up the surgery steps. Surgery isn't suppose to be easy or quick like cloning or the cyro chamber. It's a different type of healing process for more advanced cases. The faster you go is determined by your experience, and how well you can read (the computer with) the steps.

The sound of expanding what it does isn't bad, as long as it isn't too overpowered. In contrast, with such a simple medical system we don't really have a lot of room to create concepts with.

**Comment by puremanbird** [comment]
Heart repair would be great for the cases where someone comes in after being dead long enough for their heart to decay. If they didnt have too much brute or burn damage, then you could surgery them and defib them, a process that actually gives medical something to do other then yell over coms for genetics to clone the body or smash the window in and do it yourself. Also, when cloning is destroyed this would give you a way to actually save people instead of just borging them or letting them rot until engineering/science does their  job and replaces cloning. Doctors have so little to do right now.

**Comment by puremanbird** [comment]
I also dont see how this could really end up being overpowered. Right now, if you dont hide a body well enough then its on you. If a person gets dragged to medbay then its expected that they will be back in play soon with a competent staff. I know adam has a giant medbay rework pr thing going, but if that isnt actually going to end up being a thing then we can start by adding little additions at a time.

**Comment by Cruix** [comment]
If you want to be able to do a heart transplant, you should prepare by grabbing a monkey from genetics or viro, taking out its heart, and storing it in the blood cooler in surgery at roundstart. Reviving people with surgery is supposed to be more difficult that throwing them in the cloner, but it is also faster for an experienced surgeon and has fewer negative consequences for the person being revived. The whole point of organ transplants was that you could store them for when you need them, and organ repair surgery would ruin that.

**Comment by Time-Green** [comment]
When I'm medical, I don't ever clone, and always use the surgery, it's annoying having to do it 10 times on every limb, within the timespan.

Heart transplants are useful but require the geneticist to help you and you need to do the whole surgery thing.

All in all I agree with manbird

**Comment by puremanbird** [comment]
I finally managed to successfully defib someone after doing brute surgery/burn surgery/heart surgery. The process is not any faster then just cloning them, not even close. If done right surgery should be undoubtedly faster because its more complicated.

**Comment by Cruix** [comment]
That is only necessary if they died in the vacuum of space, in which case you might as well just do brain surgery. If they died to bullets, lasers, or being beat with a toolbox, you probably only need one healing surgery to get them below 180 damage so you can defib.

**Comment by Time-Green** [comment]
It's more common then you think, if someone is murdering, they usually hurt them past easy defib.
I mean, brain surgery wirks, but I think the person rather gets cloned, at least do it in style and swap the heads, and have them scream for a new tongue cuz that shit destroys your tongue.

**Comment by AdamElTablawy** [comment]
No buff since defibbed people currently remember their death

**Comment by puremanbird** [comment]
They.. what? Thats stupid. Just fix the rule. I assumed they wouldnt remember their death because.. death.

**Comment by Time-Green** [comment]
It's another way to encourage defibbing, if you're a traitor, it's your mistake for having them saved

**Comment by Super3222** [comment]
Why the fuck are we letting defibbed people remember their death?

**Comment by darkwahn** [comment]
Because originally the limits for defib time were pretty short
