### ISSUE TITLE
Accidental Infinite Sustenance

### ISSUE THREAD

**Issue by Gawdzira** [yogstation13/Yogstation#10987]
Issue reported from  Round ID: 34078 (Yogstation 13)

Reporting client version: 513.1536

So I was in the kitchen butchering monkeys and adding their lightly fried organs to soup, it seemed I had an endless supply of organs from just two monkeys when it dawned on me... I DID HAVE AN INFINITE SUPPLY. Every time I added anything lightly fried to the bowl of water it spawned an un-fried version at my feet! 

Username: Gawdzira
IC name: Thomas Braun

EDIT: Somewhere around the 30 minute mark on round time if you wanna view the replay.

**Comment by adamsong** [comment]
Fixed by #11650
