### ISSUE TITLE
Players can cryopod players again

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#10993]
I am going to stab a mother fucker.

**Comment by Cartlord** [comment]
https://github.com/yogstation13/Yogstation/pull/11375 is open and looks to fix this

**Comment by MegaEmpirical** [comment]
I've a bad habit of swapping those two letters, that would do it.

**Comment by adamsong** [comment]
Does #11529 adequately fix this? #11375 appears to have gone stale but still might be merged.

**Comment by MegaEmpirical** [comment]
It doesn't.

I poked Ynot about the PR.

**Comment by adamsong** [comment]
#11529 was merged and #11375 was closed
