### ISSUE TITLE
Blood bags/IV drips are bugged like hell

### ISSUE THREAD

**Issue by Hydre** [yogstation13/yogstation#1103]
When you attach an IV drip to someone with the correct blood type you're instantly filled up to over 300% blood.

Now if you attach an IV drip with the wrong blood type you instantly get fucked with 1000u of toxin.

Credit goes to I Can Hear Colors for this one

**Comment by Hydre** [comment]
13:35:45 - I Can Hear Colors - they changed the name of reagent_containers/blood to reagent_containers/blood_pack

13:36:05 - I Can Hear Colors - tell em to look at https://github.com/yogstation13/yogstation/blob/cf6f716d477a08d5ae42fc3b44d3bb9aac50d2a6/code/game/machinery/iv_drip.dm

**Comment by aphielanis** [comment]
Save your money on that traitor poison kit, just use your own blood.
 Seriously though,  thanks for finding and reporting this, and thanks in advance to the coder who fixes this.

**Comment by puremanbird** [comment]
I Had someone refill a blood bag with the wrong type of blood and i poisoned some poor guy with 1,000 units of toxins because of it. On the flip side, you can completely heal blood loss by just turning the IV on and Off again. Looking forward to this being fixed.
