### ISSUE TITLE
Ionising Cellular Emission Does not appear to work at all even if thresholds are hit

### ISSUE THREAD

**Issue by Dinamitis** [yogstation13/Yogstation#11031]
Round ID:  34193

Reproduction: I did not reproduce this multiple times so far

Was playing around as a syndicate scientists (Ghost Role) and made a virus with the following, sneezing, revitiligo, viral revolutionary acceleration, shivering, alopecia, and ionising cellular emission, all of them were nurtured apart from the ionising cellular emission, tested it on some monkeys and even myself but the symptom did not spread radiation as i read it would and in fact did nothing at all from what it seems, i did wait a long time and tested it on a group of monkeys but nothing happened.

**Comment by redmoogle** [comment]
Will push in https://github.com/yogstation13/Yogstation/pull/11021

(provided I can figure out why)
