### ISSUE TITLE
stimpacks?

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#1105]
stimpacks are in a weird spot after they got buffed in #854, as they're extremely useful but no so useful that they're worth the 10 tc cost. I'd LIKE to see them used in conjunction with other items, but possible murderbone makes me want the tc to be high.

Option 1: Lower tc cost, maybe to something like 7 or 8, so it can be comboed with other items like holos or dual esword for 20 tc, short lived murderbone kits.

Option 2: Make the item itself last longer, maybe something like 75% metabolism rate to get more for your money and prevent cheese combos but also allowing people to be robust with it for longer

Option 3: take the middle road and slightly decrease tc and decrease metabolism rate, this might prove to be too strong

suggest other ideas or something

**Comment by Drakkon** [comment]
My vote for option 1.

**Comment by Super3222** [comment]
Eh. I'd suggest lowering the cost to 8. It's good, and it requires some actual hand-maneuvering to use it. It's still strong though, which is why I'd prefer an 8 over 7.

**Comment by Stealthkibbler** [comment]
Adrenals makes stim obsolete, Adrenal does the same thing AND injects omnizine into the users body healing them from damage over time. Stim can only be used once but adrenals can be used 3 times and stacked in rapid succession for pretty much the same effect that stim gives and for way longer.

Why stim is even there when we have adrenals is beyond me.

**Comment by ShadowDeath6** [comment]
How about having stims be 3 uses of 20u each for 8 tc? That's still as much as an emag.
