### ISSUE TITLE
Autolathe - inconsistent printing!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#11061]
- if you construct an autolathe and **_initially_** want to print 30 cables, often it prints 30 x 30unit cable coils. If I print something beforehand and wait it out, and then print cable coils, it prints only 1 x 30u cable coils. Happened **many** times, and now becoming annoying.

**Comment by redmoogle** [comment]
erm, the autolathe prints coils in sets of 30 pieces...

**Comment by 00aquir** [comment]
Again, it happened many times exactly as I describe. Normally, " Cable coil x 30 " = prints one WHOLE cable coil. " Cable coil x 1 " prints 1 tiny fraction of it. (when I construct autolathe on YogStation.)

But it changes the printing method as I described! (sometimes when it happens, and it did and still does many times, the printing gets inconsistent). If the other way is the normal one, fine, but the changing printing method is annoying me.

**Comment by redmoogle** [comment]
Cannot replicate at all

**Comment by 00aquir** [comment]
It happened with newly constructed autolathes. By now I just print anything, like an analyzer first, to avoid it printing 30 x full cable coils, then with the same "30 x " command, I print one whole cable coil.
