### ISSUE TITLE
Chaplain glitch can give them multiple bless hands

### ISSUE THREAD

**Issue by Yewmi** [yogstation13/yogstation#1107]
12:23:18 - Talon Hanford - found a glitch... I now have 8 bless hands from my bible... clicking the bible after you activate it but not after you pick your design choice adds more hands

**Comment by Yewmi** [comment]
I watched him use this bug to stack bless hands and go on a mass blessing spree.
![dreamseeker_2016-10-27_05-49-06](https://cloud.githubusercontent.com/assets/22177874/19764553/209b1f56-9c09-11e6-8d5b-64b4132c2614.png)

**Comment by ShadowDeath6** [comment]
How does this happen

**Comment by Ephemeralis** [comment]
Fairly easy to replicate. Use the book repeatedly while the dialogues for choosing a religion name are open and it adds a new Bless spell to your mob vars each time.

It's pretty hilarious and mostly harmless since bless does just about fuckall.
