### ISSUE TITLE
Chefs can't learn CQC

### ISSUE THREAD

**Issue by LazennG** [yogstation13/Yogstation#11089]
## Reproduction:
>be a real chef
>purchase cqc manual 
>become unable to use it and get the message about having already read it because the game confused close quarters cooking for close quarters combat whether the book is being read inside or outside the kitchen.

**Comment by BobTheButton** [comment]
have you tried doing it outside of the kitchen

**Comment by LazennG** [comment]
tried doing it on multiple occassions, outside of the kitchen in maint, on centcom, it doesnt work as chef

**Comment by adamsong** [comment]
Close quarters cooking registers as the same martial art as normal CQC
