### ISSUE TITLE
Camera monitors stop working during the round

### ISSUE THREAD

**Issue by Paragonid** [yogstation13/yogstation#1108]
1. Use security camera monitor (experienced it on both Research Monitor and Cargo shaft monitor), it works as expected by showing camera list
2. Something happens, both times after 15-20 minutes in the round
3. Attempting to use security camera monitor doesn't show up camera list anymore

It doesn't seem to happen often and I don't know what exactly breaks monitors. Maybe someone has experienced it as well or have any ideas.

**Comment by EMT321** [comment]
Is it possible the view tab was behind the main game screen?

**Comment by Paragonid** [comment]
I closed/reopened client to test it, I didn't work after that.
It also didn't work for KMC2000 when I created a ticket about it.
So I guess not? If only unclosed monitor tab somehow fucks new tabs up.
