### ISSUE TITLE
Feature to make borgs cuffable

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1110]
The problem with having to stop borgs is that there are not many non lethal ways to do it besides the lockdown console or pulling the battery both require special access and the console can be destroyed or inoperable. 

 I would like to see cuffing borgs so they can't use modules or move free of a grab like when human style mobs are cuffed. They also have the same  ability to resist.

 Maybe adding restraint jackets to useable items on borgs and even the blind fold to keep them from messing with consoles, doors, and interactables wouldn't be bad either.

 I think these changes would allow players to not die as often as borgs and give the rest of us something  to use against borgs that is not lethal

**Comment by AdamElTablawy** [comment]
HahahaahahaahahahahahahahahahahahahHHAHAHAHahahahahahah

**Comment by Kmc2000** [comment]
Oh god


I'm against this, you can stunfuck a borg P E R M A N E N T L Y by spamming a flash, and in most cases you want to stun the thing just long enough to beat it to death.

Cuffing borgs is like...clown gets flash, cuffs secborg, clown now has a helpless pet borg which no one would save because its a borg

**Comment by X-TheDark** [comment]
A magnetic leash item to bind the borg to an area, so it can ~~lapdance for all in~~ protect the Bridge.

**Comment by ShadowDeath6** [comment]
borgs are op make a way to disable them permanently instead of killing them so they can talk but not use modules
instead of cuffing let's call it lock down since it locks their modules 
also give it to RD since he can blow borgs too

**Comment by Super3222** [comment]
> instead of cuffing let's call it lock down since it locks their modules 
> also give it to RD since he can blow borgs too

it's already a feature and tied to the robotics computer. it's also called lockdown... but maybe you're thinking of a remote control lockdown? like maybe tie that to the RD's door remote? actually, nevermind. there's always laser pointers

**Comment by ShadowDeath6** [comment]
>it's already a feature

Woah that's crazy, I wonder everyone blows the borgs then!

**Comment by darkwahn** [comment]
Really super?

**Comment by AdamElTablawy** [comment]
no
