### ISSUE TITLE
Monster (probably) broke bubblegum aggro

### ISSUE THREAD

**Issue by LazennG** [yogstation13/Yogstation#11117]
## Reproduction:

Only experienced this twice ever and only after the megafauna music merge but what's happened both time is: bubblegum aggroes onto someone and without getting attacked, stays on them until he seemingly gives up but he doesn't, he keeps walking towards you no matter how far you get, only being stopped by rock walls. If you're on the other side of a wall you'll hear him walking fast towards you and see on the gps he's always walking closer. Only ways I've remedied this is by leaving the z level, making him attack something else, or of course finishing the fight, but I doubt people who play mining a lot less are gonna be able to try these if it happens to them too.

Most recent example: https://yogstation13.github.io/demo-viewer/?roundid=34434#15282;203.50;118.50;5;[0x3000128]

**Comment by Cartlord** [comment]
Round 35860 just got RUINED by this, I'm pretty sure.

**Comment by SomeguyManperson** [comment]
for some reason after certain attacks bubblegum just kind of decides to not reset its aggro range if necessary leading to passive 15 tile radius aggro megafuck

**Comment by MajManatee** [comment]
He is mad again
