### ISSUE TITLE
Replace the mining station cigarette machine

### ISSUE THREAD

**Issue by someoneunkown** [yogstation13/yogstation#1115]
I was told to leave a comment here if I wanted to make an improvement about the server. I would like to suggest for the better playability of the "Shaft miner" job, that the cigarette machine be replaced with a coffee machine, as it would be more useful to miner's who get hit by watchers and need to heat up quickly.

**Comment by Rocks4Free** [comment]
But my character is a vegan shaft miner who smokes and if you remove the cigarrettes I won't be able to play here anymore :(((((((((((((((((((((((((((((((((((((((((((((((((((((((

**Comment by someoneunkown** [comment]
So lemme get this straight... you saying you're a hippie?

**Comment by ShadowDeath6** [comment]
coffee is bean

**Comment by someoneunkown** [comment]
Coffee is a good thing to have. There's none of it on mining.

**Comment by Super3222** [comment]
Sure, why not?
