### ISSUE TITLE
AI law upload console not working

### ISSUE THREAD

**Issue by AJHcHenry** [yogstation13/Yogstation#11164]
## Round ID:
34540

## Testmerges:

10982 and 11139 are currently testmerged. 11139 is a likely culprit.

## Reproduction:

AI law upload console cannot find an active AI to select and upload laws to, even though one exists, is alive and connected, and is on the station Z-level. I tried it with the AI in its shell, as well as in its core, and neither worked.

**Comment by redmoogle** [comment]
Caused by #11139

**Comment by adamsong** [comment]
This was fixed right?

**Comment by adamsong** [comment]
AJ has confirmed this has been patched
