### ISSUE TITLE
Patient's entire blood volume disappears in mere seconds while in active medbay treatment

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#11176]
Issue reported from  Round ID: 34567 (Yogstation 13)

Reporting client version: 513.1542

The curious case of the vanishing bloodstream, featuring Bobby Blob the bartender
-Man comes to my attention dead at about 40% blood volume
-Revive him with SR, do a transfusion, get him up to about 79%
-Take him off the bed, do CPR
-10 reps in, he's in shallow crit or out of it entirely
-Then he seizes up and falls limp, his eyes dead and lifeless
-Health scan reads 0% blood volume
-?????
(Screenshots taken after it happened, look at chat)

![image](https://user-images.githubusercontent.com/36427443/111887103-22210600-89a9-11eb-9606-14d9a69ca909.png)
CPR'd him 10 times in this state and then he dropped dead from fairly good health (may have even been out of crit, I think)
![image](https://user-images.githubusercontent.com/36427443/111887105-24836000-89a9-11eb-94b0-11a10a4426aa.png)

Asking mentors didn't reveal anything
Sniblet: any idea what could cause a man to go from ~80% blood to 0% in under 5 seconds while under medbay treatment
Jarod1200->Sniblet: what race is he
Sniblet->Jarod1200: human
Jarod1200->Sniblet: and hes got no weird chems in him?
Sniblet->Jarod1200: spaceacillin, synthflesh, blood (from a failed transfusion), salbutamol, omnizine
Tatax->Sniblet: if he's bleeding it might've been a weird glitch or smething

The gamemode was traitor, he was no one's target and wasn't an antag himself
He was bleeding but he wasn't being dragged anywhere, his brute damage was nothing and he was being CPR'd so he was held still

**Comment by redmoogle** [comment]
Cannot replicate, likely something messed up in the background
