### ISSUE TITLE
Glitch with the demonic chainsaw

### ISSUE THREAD

**Issue by someoneunkown** [yogstation13/yogstation#1119]
Well... whenever you summon and unsummon the demonic chainsaw that you get from a possible drop at defeating bubblegum, it appears more spells appear with the demonic chainsaw that don't actually work.

![ss13 chainsaw glitch](https://cloud.githubusercontent.com/assets/22434266/19826368/2c3de908-9d56-11e6-989e-4f3587728053.PNG)

**Comment by Super3222** [comment]
@ShadowDeath6

**Comment by X-TheDark** [comment]
@ShadowDeath6 
Instead of `qdel(spell)`, use `user.mind.RemoveSpell(spell)`

**Comment by ShadowDeath6** [comment]
this was fixed in local testing, will removespell instead
