### ISSUE TITLE
Felinids show up as a different race on scanners and records

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#11248]
As title. I know in the code they're different races but as we don't treat them as their own race, they should be made to be human in all other respects of the game.

We no longer have the human specific malf objective, but for example they should be included with that.

**Comment by maxion12345** [comment]
they
they are a different race

**Comment by MegaEmpirical** [comment]
Not on Yogstation, they're humans.

**Comment by adamsong** [comment]
Felinids are a different race, even if they are treated as human by things such as command roles and silicon policy.

**Comment by MegaEmpirical** [comment]
> Felinids are a different race, even if they are treated as human by things such as command roles and silicon policy.

That is literally the issue.

**Comment by adamsong** [comment]
Are you suggesting that felinids should just be humans with ears and a tail with no other variances, therefore removing thing like laser pointers affecting them? If they are going to behave different that a human in any way they should show up as a different race.

**Comment by MegaEmpirical** [comment]
That is how we define them yes.

I never said to remove the laser pointer thing and that suggestion makes no sense. Doing something with a laser pointer is trivial and not a way to define something as a different race, might as well define anyone with a brain trauma as their own race at that point.

**Comment by adamsong** [comment]
Should scanner gates, nanites, and brain trauma also be reworked to not recognize felinids as a separate species?

**Comment by MegaEmpirical** [comment]
Would be nice.

**Comment by alexkar598** [comment]
Feature requests go on the forums

**Comment by MegaEmpirical** [comment]
Not a feature request if Felinids are not human whilst being human and there's a PR that'll close this anyway.

**Comment by Bibby0110** [comment]
> Not a feature request if Felinids are not human whilst being human and there's a PR that'll close this anyway.

Felinids aren't human simple as that. No matter what you rule felinids will not be human, they will be a subtype of human forever.

**Comment by Bibby0110** [comment]
cat fight between lyis and alexkar?

**Comment by Bibby0110** [comment]
This should be closed since we resolved it, no?

**Comment by MegaEmpirical** [comment]
Barely by some weird half measure that makes no sense, but I guess good enough.
