### ISSUE TITLE
Plasmaman vampires appear to be able to suck blood through their helmets?

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#11254]
Shit be busted.

**Comment by Gboster-0** [comment]
to be honest going under a shower for literally every person you want to suck would kinda get really boring and i imagine there would sometimes be officers just camping dorm showers for vampires

**Comment by MegaEmpirical** [comment]
I can live with that. I didn't even think plasmamen could be vampires until shortly before I posted this.

**Comment by MegaEmpirical** [comment]
Why was this closed?
