### ISSUE TITLE
Free Miners broken on OmegaStation

### ISSUE THREAD

**Issue by Cartlord** [yogstation13/Yogstation#11256]
## Round ID:

Round ID 34719 on YogStation.

## Testmerges:
Current testmerges were black overlay ( https://github.com/yogstation13/Yogstation/pull/10982 ), and Adds Station Traits ( https://github.com/yogstation13/Yogstation/pull/11134 ).

## Reproduction:

On OmegaStation, Free Miners are unable to dock with the station. I found this out by playing Free Miner Captain and going to the shuttle console, and there was not an option to go to the station or any aux dock - it only had one option, "Free Miner Asteroid"; when I went there, the option changed to "Deep Space". This seems... problematic, given it leaves me unable to sell my ore, interact with anyone who isn't a Free Miner, or even get renewable non-junk food.

**Comment by patpol4** [comment]
Solution would be either to make a docking port for omega which would be hard and tiresome, or just place the miner docking port object somewhere  in space by the station with road signs(?) leading to it.

**Comment by Cartlord** [comment]
Free Miners have Hardsuits & Internals, so you could just have them park NEXT to the station and spacewalk over to an external airlock.
