### ISSUE TITLE
Detomatix PDA cartridge does not work

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation#1125]
The detomatix cartridge no longer has options for detonating other PDA's. This was tested and independently confirmed. It can only open the syndicate door.

**Comment by Paragonid** [comment]
Tested during traitor round, not nuke ops round

**Comment by EMT321** [comment]
It was under 25 people, but I tested it with nuclear operatives spawned in as well.

**Comment by ShadowDeath6** [comment]
I think @Cruix was the last person to touch PDAs
