### ISSUE TITLE
Yogsmeta's top right solar maintenance airlocks arent depressurizing properly and open instnatly

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11272]
## Test Merges: 
Not Supplied / None
## Reproduction:
Yogsmeta's top right solar maintenance airlocks arent depressurizing properly and open instnatly
 Submitted by: Bibby (212531662305755137)

**Comment by Cartlord** [comment]
Can confirm, same issue also exists with the external airlock in Atmos.

**Comment by patpol4** [comment]
Not fixed yet

**Comment by Cartlord** [comment]
Same issue applies to the airlocks on the southwest corner of Atmospherics

**Comment by patpol4** [comment]
Taken care of
