### ISSUE TITLE
[Botanist] [Kudzu] Kudzu plant not working properly?

### ISSUE THREAD

**Issue by RandomUsername13753** [yogstation13/yogstation#1128]
Hello, i made a Kudzu plant as botanist. Kudzu should grow out of the tray and spread itself across the station. Hovewer, Kudzu did not growed out of the tray at all.

Second, i wanted to extract spreading trait of Kudzu using machine in the botanist backroom. I put Kudzu seeds in to DNA transfer machine for plants and it seems Kudzu lacks the spreading trait. There was no such trait avaliable to copy on disc. For example - when you put in glowing mushroom seed, you can extract the glowing trait. 

I think Kudzu may be broken, pleasse look in to it. 

Thank you alot! :)

**Comment by ShadowDeath6** [comment]
wasn't added as it was after the rebase

**Comment by RandomUsername13753** [comment]
Hello ShadowDeath6, thanks for reply. What should happen next if this is the case? Should it be fixed?

**Comment by Cruix** [comment]
Kudzu does not grow out of hydro trays, you have to plant the seeds on the ground by clicking them in your active hand. Kudzu also has its own mutation system that is much older than the plant DNA machine one, and was not updated to use the new system.

**Comment by RandomUsername13753** [comment]
Thanks for telling about ground @Cruix. Does this mean i cannot DNA machine kudzu to make it do all sorts of fun stuff? Or is there a way?

**Comment by Super3222** [comment]
I guess that would mean the kudzu is incompatible with the DNA machine.

**Comment by RandomUsername13753** [comment]
Does this mean i cannot mutate Kudzu? because there is basically no machine for it in teh game?
