### ISSUE TITLE
A hostile/carp/eyeball given fugu_gland had infinite health

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#11298]
Round: 34814

This thing took out a blob, it was beaten repeatedly and never received more than 54 damage but had health to a damned power.

![image](https://user-images.githubusercontent.com/36208065/113821701-70c0f500-974a-11eb-8279-d6de1033c5eb.png)

**Comment by Readystorm546** [comment]
After further testing the eyeball, its self without the gland was able to die however once receiving the gland it was then made invincible!
