### ISSUE TITLE
stupid swarmer thing

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11295]
## Test Merges: 
Not Supplied / None
## Reproduction:
Swarmers can break the wall for the incinerator which may or may not be filled with highly pressurized and burning gas, which would make the air more unsafe than exposing it to vacuum
 Submitted by: ThatGuyPhil (308057723394719754)

**Comment by Cartlord** [comment]
I can confirm this issue, I had a swarmer break my turbine wall and plasmaflood the entire room.
