### ISSUE TITLE
free posters

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11306]
## Test Merges: 
Not Supplied / None
## Reproduction:
If you wire cut a poster as you're putting it on a wall you can create infinite copies of it.
 Submitted by: Cowbot (97736956326207488)

**Comment by adamsong** [comment]
Unable to reproduce, switching to the poster while placing it causes the poster to drop

**Comment by adamsong** [comment]
Unable to reproduce, no further clarification provided. Closing.
