### ISSUE TITLE
pAI Cannot hear in Ratvarian

### ISSUE THREAD

**Issue by GenericDM** [yogstation13/Yogstation#1131]
[Round ID]: # 16462

[Reproduction]: # Download Universal Translator as pAI, activate it, and have someone speak Ratvarian at you

[Extra]: I was playing this round as a pAI named MalO if that helps anything.

**Comment by Amelia0010** [comment]
![image](https://user-images.githubusercontent.com/20558591/40886168-83dd9a5c-6733-11e8-9ad3-6704db50cf50.png)

Are you sure you turned it on? I was able to both understand and speak ratvarian with the universal translator active

**Comment by GenericDM** [comment]
I'm very sure it was turned on, could have just been a bug for that round though.
