### ISSUE TITLE
Security record consoles no longer have comments

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#11316]
Comments are gone, this is a travesty!

Important notes is fucking useful, comments were important.

**Comment by Tipy1802** [comment]
Arent comments and important notes the same?

**Comment by MegaEmpirical** [comment]
> Arent comments and important notes the same?

Nope.

Notes are a single entry that can only be edited and it only shows what's written, nothing else (like author, time stamp).

Also, notes currently doesn't have word wrap nor a horizontal scroll to see their full text.



Comments are similar to a forum thread. They show the comment, author, and time. There can also be more than one of them as well.
They're useful for various bits of info and for keeping track of which crimes have been served.

**Comment by Bibby0110** [comment]
Not a bug

**Comment by adamsong** [comment]
Comments were intentionally deprecated, with #11640 finalizing their removal from sec huds

**Comment by MegaEmpirical** [comment]
> Comments were intentionally deprecated, with #11640 finalizing their removal from sec huds

Which is fucking horse shit. And honestly I think he just forgot.
