### ISSUE TITLE
Zaukerite Sheets not yet implemented, crystalizer duplicates moles of gas by 10000%

### ISSUE THREAD

**Issue by Darthkill** [yogstation13/Yogstation#11312]
Issue reported from  Round ID: 34839 (Yogstation 13)

Reporting client version: 513.1542
Sheets are invisible
![image](https://user-images.githubusercontent.com/33874385/114108297-b99fb780-98ca-11eb-8ae4-d515c3fe0a91.png)
![image](https://user-images.githubusercontent.com/33874385/114108324-c4f2e300-98ca-11eb-8404-4565b8f4cf45.png)
also the crystalizer duplicates moles, i started with 30 moles, but once I started making the sheets it made alot of extra gas out of nowhere
![image](https://user-images.githubusercontent.com/33874385/114108673-77c34100-98cb-11eb-8e08-e7eeed1c73b6.png)

round ID is 34839 

I feel that this is just me being the atmos mad man I am and outpacing everyones expectations

**Comment by SomeguyManperson** [comment]
turns out sheets are modularized and I didn't put the images in the right file

**Comment by Darthkill** [comment]
nice, I hope I can make something out of it soon, still leaves a weird mole duplication glitch, it only happens when the gas needs to be held cold.

**Comment by UselessTheremin** [comment]
fixed in https://github.com/yogstation13/Yogstation/pull/11370
