### ISSUE TITLE
Players are able to cryo other players

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#11321]
This was supposed fixed before but it seems to be broken now.

**Comment by Cartlord** [comment]
Did you forget https://github.com/yogstation13/Yogstation/issues/10993 was open?

**Comment by MegaEmpirical** [comment]
Damn, I couldn't remember if I had done this yet and didn't see that when I did a search. Thanks for pointing it out.

Closing due to duplicate.

**Comment by Cartlord** [comment]
The reason you didn't see it when searching was because it doesn't show up at all when searching "cryo", even if you go under Closed Issues.
