### ISSUE TITLE
Wirecutters doesn't work as hemostat

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11379]
## Test Merges: 
Not Supplied / None
## Reproduction:
As said on title, wirecutters would not work as a hemostat in ghetto surgery
 Submitted by: Alv Cyktor (277567415049519105)

**Comment by Takahiru** [comment]
Okay but this is wrong

**Comment by UselessTheremin** [comment]
gonna test this in a bit but im pretty sure they do work my mans

**Comment by Lostlarry** [comment]
i have just tested it an using wirecutters as both retractor and hemostat works

**Comment by adamsong** [comment]
I can also confirm, this has been fixed
