### ISSUE TITLE
Goliath broodmother tendrils refuse to stop

### ISSUE THREAD

**Issue by Cartlord** [yogstation13/Yogstation#11385]

**Comment by Cartlord** [comment]
Hit enter too early hold on

**Comment by Cartlord** [comment]
OK it's good now

**Comment by Marmio64** [comment]
this has been a thing for a very long time

**Comment by overlord12345** [comment]
Spawn Tentacles: The Goliath Broodmother will start passively spawning burrowing tentacles around her once she goes below 50% health. The rate of which these tentacles spawn are doubled once she dips below 25% health. If you get hit by these tentacles, you will receive 10-15 brute damage and be stunned for 10 seconds. Try not to be hit by these. These tentacles continue to spawn even after the Goliath Broodmother dies.

**Comment by Cartlord** [comment]
...But how does one stop them, if the broodmother cannot be butchered? Does one just ditch the body?

**Comment by Cartlord** [comment]
Sorry, forgot lavaland elites existed & confused ancient goliath with goliath broodmother.
