### ISSUE TITLE
Crew Monitoring shows wrong ship

### ISSUE THREAD

**Issue by XeonFaux** [yogstation13/yogstation#1139]
The Crew Monitoring monitor shows the ship of the Colonial Marines server instead of the normal station. Now, I don't even play on the Colonial Marines server so I don't think it's an issue with cache or anything.

![untitled](https://cloud.githubusercontent.com/assets/13593924/19839963/32660212-9ea9-11e6-8494-c4364481cdd1.png)

**Comment by ShadowDeath6** [comment]
CMCs are bugged beyond belief

**Comment by EMT321** [comment]
How does something like this even happen

**Comment by Alek2ander** [comment]
The minimap image is cached locally on your computer. If the server didn't send you one, for some reason, it can end up using one that was used before, from a server you played on previously

**Comment by XeonFaux** [comment]
I don't play the CM server though, so I don't know how it happened.
