### ISSUE TITLE
Darkspawn mindlink chat prefix description is wrong

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11399]
## Test Merges: 
Not Supplied / None
## Reproduction:
darkspawn mindlink chat is prefixed with .w but the description in game tells you to use .k.
 Submitted by: The Grand Inquisitor (250794357211398144)

**Comment by Cartlord** [comment]
Can confirm

**Comment by adamsong** [comment]
Fixed by #11490
