### ISSUE TITLE
Bluespace Body-bags Hold Infinite Items

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11395]
## Test Merges: 
Not Supplied / None
## Reproduction:
Bluespace Body-bags Can Be Folded Inside Each Other If A Regular Storage Device Is Used In Between Each Bag, Resulting In Infinite Storage Inside A Tiny Item
 Submitted by: alexkar598 (304751952548462593)

**Comment by patpol4** [comment]
feature

**Comment by TheLinuxOS** [comment]
If this is a feature it should be closed

**Comment by adamsong** [comment]
Is this a feature or not?

**Comment by patpol4** [comment]
feature imo, just close

**Comment by adamsong** [comment]
Closing as feature
