### ISSUE TITLE
Multiple ghost role IDs show wrong age

### ISSUE THREAD

**Issue by Cartlord** [yogstation13/Yogstation#11400]
### Severity

Low

### Short Description

Ghost role IDs show you as a minor

### Reproduction

1. Spawn as Free Miner, Space Bartender, or Space Cop
2. Shift-Click ID to Examine
ID will say you are 13, and that you are not to be served drugs or alcohol.

### Round ID

Any round where space cops, space bartenders, or Free Miners spawn - one example being 35044

### Test Merges

https://github.com/yogstation13/yogstation/pull/11106 https://github.com/yogstation13/yogstation/pull/11195 https://github.com/yogstation13/yogstation/pull/11129 https://github.com/yogstation13/yogstation/pull/10764 https://github.com/yogstation13/yogstation/pull/11290 https://github.com/yogstation13/yogstation/pull/11278 https://github.com/yogstation13/yogstation/pull/11275

### BYOND Username

Cartlord

### Additional information

AHelped about this once, and they suggested this might be a placeholder - so maybe these values are just a default of some kind, and those with these roles don't spawn with an age set? Possibly??

**Comment by Marmio64** [comment]
default age of all cards is 13
take a brand new card out of a ID box and slot it into a ID modifier and you'll see it says they're 13

**Comment by Cartlord** [comment]
I don't know what to do with that information. I was under the assumption it'd be possible to assign some age to these cards, since they start off already linked to a person; is that not something that can happen?

**Comment by adamsong** [comment]
Just make it cannon that all ghost role characters are 13
