### ISSUE TITLE
Eldritch Horror won't let me and other person use Seek Target Soul ability.

### ISSUE THREAD

**Issue by QuirkySmirkyIan** [yogstation13/Yogstation#11429]
### Severity

Round Breaking

### Short Description

Literally won't let me get souls because I can't seek target it brings up no menu to select and there is no closed tab at the bottom. 

### Reproduction

1. I played the round as blood brother bartender died as usual.
2. I was a ghost for a few minutes.
3. Clicked yes as Eldritch Horror got selected.
4. I was trying to figure out what all the buttons do as I have never played. 
5. Went into a few bodies but wouldn't let me collect soul.
6. Figured out I needed to pick a weak soul from the locate but it wouldn't open anything.
7. Mentor helped in and they told me to disconnect.
8. Admin gave role to someone else because I forget to tell them and they couldn't locate the weak soul either.

### Round ID

35121

### Test Merges

#10535 #11366 #11415

### BYOND Username

QuirkySmirkyIan

**Comment by ChesterTheCheesy** [comment]
okay you weren't supposed to play as horror idk why the event happened it's literally disabled outside adminbus

**Comment by Bibby0110** [comment]
Never merged
