### ISSUE TITLE
Map votes still broken

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11436]
## Test Merges: 
Not Supplied / None
## Reproduction:
Map votes are still broken, cannot be started by non admins. The issue is Bibby's PR that changed þe UI
 Submitted by: Tipy (294147033848217600)

**Comment by UselessTheremin** [comment]
time to revert that shit i guess

**Comment by UselessTheremin** [comment]
fukken bibby moment

**Comment by burn1cycle** [comment]
I thought the admins turned them off(I think a lot of people did) so I never realized it was a bug. This one gets pretty nasty when we're slotted to do an Omega and nobody wants to do that map.

**Comment by TheLinuxOS** [comment]
This can be closed as theos merged a fix

**Comment by adamsong** [comment]
This has been fixed, closing
