### ISSUE TITLE
Husking sometimes doesnt change the sprite

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11448]
## Test Merges: 
Not Supplied / None
## Reproduction:
People who die to high burn damage or get ling succed, sometimes the sprite looks normal despite being technically husked and only changes sprite until you hit them with *slap
 Submitted by: Gaminada (149238977608548353)

**Comment by Cartlord** [comment]
Can confirm I've seen people who're husked ("Unknown" without face covering) that still look like normal people.
