### ISSUE TITLE
Disposals in the library broken

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11452]
## Test Merges: 
Not Supplied / None
## Reproduction:
throwing anything away in the disposals in the library (top right) sends it a few feet and into the wall, the pipes arent connected to anything. Has happened multiple rounds/any time i check.
 Submitted by: Fenris (271458414473773057)

**Comment by patpol4** [comment]
https://github.com/yogstation13/Yogstation/pull/11456
