### ISSUE TITLE
Lavaland legion's soul healing bug

### ISSUE THREAD

**Issue by someoneunkown** [yogstation13/yogstation#1145]
I've been seeing this a while, so i'm reporting it now. When you get hit by a watcher's beam, you move slowly and your move in random directions when you wanna move a specific direction. When you use a legions soul under this effect, you lose the slowness, however, you still move in random directions.

**Comment by ShadowDeath6** [comment]
Legion soul removes the chems but you still have confuse from the cryptobiolin

**Comment by someoneunkown** [comment]
Does not the legion's soul heal everything off you at it's full potential?

**Comment by ShadowDeath6** [comment]
It removes chemicals and heals damage but it doesn't heal everything
