### ISSUE TITLE
 Pin-Removal Gun Glitch

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11453]
## Test Merges: 
Not Supplied / None
## Reproduction:
So in the weapons section of the personal crafting menu, there seems to be an option to remove the firing pin from a gun that has one.  If you have a welding tool, a screwdriver, and a pair of wirecutters, you can complete it.  Standing over the gun and going through the process removes the firing pin, but doesn't actually give you the firing pin.

The bug gets funnier when you try to do it again, because the option remains available even though you just removed the pin from the gun.  Using it again goes through the process.  Instead of giving you a firing pin, it spawns under your original gun a small revolver simply called "gun".  It couldn't load any of the ammo I tried, and I found you could do it a bunch of times, leading to many tiny revolvers being created.  I have no idea how this happened, but it was a bug so I'm reporting it.
 Submitted by: Xaahdubc (222019245821657089)

**Comment by Marmio64** [comment]
Pins being destroyed from taking them out is intended

**Comment by alexkar598** [comment]
Intended.

The second part might not tho.
