### ISSUE TITLE
Devil power's dont mix with borers

### ISSUE THREAD

**Issue by Lightning38088** [yogstation13/yogstation#1146]
Getting taken over by a borer while jaunting as a devil causes your powers to glitch out and become non excitant as well as keep you forever jaunted

**Comment by Super3222** [comment]
Devils need a hard counter for borers.

**Comment by Time-Green** [comment]
They should just catch on fire

**Comment by Super3222** [comment]
> They should just catch on fire

If only borers COULD catch on fire.
