### ISSUE TITLE
Deltastation turbine bas a manifold leading nowhere

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11471]
## Test Merges: 
Not Supplied / None
## Reproduction:
See title
 Submitted by: Theremin (384040394515677184)

**Comment by Darthkill** [comment]
![image](https://user-images.githubusercontent.com/33874385/118176544-74baf380-b429-11eb-9d22-605c10061da0.png)
 I hope the image link works, i need to learn how to github
