### ISSUE TITLE
No Compatible Ammunition for the Missile Rack

### ISSUE THREAD

**Issue by NoahHuffstutler** [yogstation13/Yogstation#11485]
### Severity

Inconvenience

### Short Description

Rocket launcher and rocket ammo type are incompatible. 

### Reproduction

Research "Exosuit Weapon (BRM-6 Missile Rack)"
Print the Missile Rack and ammunition for the missile rack.
Whatever mech you install the missile rack on will not accept the ammunition.

### Round ID

Round #35358

### Test Merges

#11366 #11425 #11413 #11139

### BYOND Username

Dr. Nonnoob

### Additional information

The Missile Rack is called BRM-6 Missile Rack, and the ammunition is called SRM-8 Missle Rack Ammunition. I suspect that the research is unlocking either the wrong missile rack for the ammunition or the wrong ammunition for the missile rack.

**Comment by ghost** [comment]
[Confirmed](https://cdn.discordapp.com/attachments/849108945196810273/851492967374127114/unknown.png), I'll try to fix it.

**Comment by Lostlarry** [comment]
just tested this and it doesnt seem to be a problem anymore
