### ISSUE TITLE
Changeling rounds dont fire, restarting the lobby

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation#1149]
ADMIN LOG: Error setting up secret(changeling, /datum/game_mode/changeling). Reverting to pre-game lobby.

I dont believe we even run changeling-solo rounds any more.

**Comment by Super3222** [comment]
I don't think the mode has any weight as of right now. Changelings are only hanging on traitorchan.

**Comment by EMT321** [comment]
All I know is it tried to trigger,without any admin intervention preceding it.

**Comment by Super3222** [comment]
Well.. now that I think of it. Congratulations! There'd only be a 1 in a one millionth chance, but a mode with absolutely 0 weight has fired and you've brought proof of it. It's as if oxygen had just turned into gold. The same thing happens with modes with 0 weight that don't fire; they have an extremely, extremely, extremely low chance of every firing.

**Comment by Time-Green** [comment]
That's hilarious, so a monkey round could just trigger anytime?
Maybe it's because the weight isn't balanced

**Comment by Super3222** [comment]
In theory, monkey rounds could choeen, but the round would revert to pre game.

**Comment by Stealthkibbler** [comment]
It happened twice last week, I dont believe the designated weight for the antag rounds actually affects the chances at all.

**Comment by oisin100** [comment]
Changeling did have weight, Someone enabled it for some strange reason.

If anyone wants to fix this look at the changeling candidate picking code, its not using `pick_candidates` right.

**Comment by X-TheDark** [comment]
Should be fixed by #1193
