### ISSUE TITLE
Coughing makes you drop small things despite not meeting resistance threshold

### ISSUE THREAD

**Issue by TheMaggotGuy** [yogstation13/Yogstation#11496]
### Severity

Round Breaking

### Short Description

Coughing makes you drop small things despite not meeting resistance threshold, tested at a resistance of 5 (11 is the threshold)

### Reproduction

1. Get coughing symptom
2. Drop things despite not meeting threshold

### Round ID

35401

### Test Merges

 The following pull requests are currently test merged: #11366: 'Eldritch Horror' by ChesterTheCheesy at commit 6c897df042 #11425: 'Miningbase Rework' by Lovebird-Frungy at commit fa5acc376a #11413: '[Bounty] Kilostation' by wejengin2 at commit fc9d9adb3b #11139: 'Dynamic 2021 & Ghost Pool Protection' by Xoxeyos at commit 9271265bbd

### BYOND Username

The_Maggot_Guy

### Additional information

What it says on the tin

**Comment by overlord12345** [comment]
resistance 3 is the treshold for droping items, 10 is coughing fits.
https://wiki.yogstation.net/wiki/Infections#Symptoms_Table

**Comment by adamsong** [comment]
The description ingame is incorrect
