### ISSUE TITLE
assistant plasmen do not spawn with envirosuits on.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11517]
## Test Merges: 
Not Supplied / None
## Reproduction:
When spawning in roundstart as a plasman assistant, you'll spawn wearing a grey jumpsuit, and instantly ignite.
 Submitted by: Cowbot (97736956326207488)

**Comment by SomeguyManperson** [comment]
likely related to #11378

**Comment by Takahiru** [comment]
fixed

**Comment by adamsong** [comment]
This issue was causes by a test merge that is no longer merged, is apparently fixed on the test merge, and not a problem on the live version. Closing.
