### ISSUE TITLE
AI Bug issue (possibly client side?)

### ISSUE THREAD

**Issue by ValkorionBYOND** [yogstation13/Yogstation#1151]
[Round ID]: # 16499

[Reproduction]: The major issue I seemed to come across is that I was attempting to set the AI to Asimov. When I did, its laws changed, but it added multiple other laws on top of that, so I attempted to reset, then use ProtectStation, Asimov, and finally Purged and used ProtectStation. When I purged and used ProtectStation, the laws did not change to ProtectStation. It maintained a lack of laws and proceeded to vaporize me. I'm not sure how to reproduce it because it's potentially clientside, but it may be a combination of spamming the changes and/or doing the changes too quickly (reset, asimov, protectstation in quick succession).

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Altoids1** [comment]
Sounds like some clientside issue.
