### ISSUE TITLE
Crew Monitor Map repair or removal needed

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11523]
## Test Merges: 
Not Supplied / None
## Reproduction:
The map on the Crew Monitor medical item is still non-functional; doesn't indicate people's positions or anything. Ideally this feature should be repaired, but if that can't be done, then it should probably be removed so that the monitor doesn't take up a whole screen with a not working map.
 Submitted by: Gavius (162288884212957184)

**Comment by MegaEmpirical** [comment]
While it would be great if it worked, it's still nice to have a map especially for newer players .

**Comment by Cartlord** [comment]
You seem to forget we all have emergency boxes with maps.

**Comment by adamsong** [comment]
Removed in #11570
