### ISSUE TITLE
Revitiligo makes lizards vantablack

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11520]
## Test Merges: 
Not Supplied / None
## Reproduction:
As a lizard I (unknowingly) took a revitiligo virus and after several minutes, it turned me completely black suddenly.
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/846506618723237888/unknown.png)
 Submitted by: Mek (239144565422948352)

**Comment by adamsong** [comment]
This appears to be intended behavior, the symptom does not modify the skin tone until stage 5, when it sets either the skin tone to 'african2' or the color to pure black.

**Comment by adamsong** [comment]
Working as intended
