### ISSUE TITLE
Add a limit to the number of animal cubes that can be placed in a single tile. 

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11539]
## Test Merges: 
Not Supplied / None
## Reproduction:
My brother has successfully provided the clown with 275 goat cubes. To which 150 the clown decided to use at once in one tile. And almost crash the server.
 Submitted by: PhoenixFox (356215755504746496)

**Comment by MegaEmpirical** [comment]
This isn't a bug, it's a feature request and the only real issue is a player not using restraint where they should have.

**Comment by adamsong** [comment]
Feature requests go on the forums.
