### ISSUE TITLE
Plasmaman Botanists can get an unusable Heirloom

### ISSUE THREAD

**Issue by Cartlord** [yogstation13/Yogstation#11531]
### Severity

Inconvenience

### Short Description

Plasmaman Botanists with the Family Heriloom Quirk can spawn with a cown cob pipe, which they cannot smoke due to that requiring mask removal.

### Reproduction

1. Open Character Setup
2. Select Plasmaman under "Species"
3. Go into "Quirks" and pick "Family Heirloom"
4. Join the round as a Botanist
5. Sometimes, you will have a corn cob pipe, as that is in the pool of Botanist heirlooms.

### Round ID

35525

### Test Merges

#11464 #11139 #11505

### Additional information

Admittedly not sure if this is something easily fixed.

**Comment by Marmio64** [comment]
technically they can smoke corn cob pipes by going into a room that is 100% plasma and taking off their suit in there

**Comment by UselessTheremin** [comment]
yeah this is more of an oversight than anything, i think it's fine but if anyone wants to change it be my guest
