### ISSUE TITLE
Megafauna can spawn directly outside structures

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11537]
## Test Merges: 
Not Supplied / None
## Reproduction:
Several occasions:
- Orion Medical Doctor, bubblegum 10 tiles at most where the Facilities ash-proof tiles end

- Bubblegum visible from mining base 

I would definitely count this as a bug, as it can make ghost roles impossible and even result in all of mining destroyed
 Submitted by: PhoenixFox (356215755504746496)

**Comment by UselessTheremin** [comment]
not an issue, just bad luck. explained in dev public.
