### ISSUE TITLE
AI comms not working

### ISSUE THREAD

**Issue by azzzertyy** [yogstation13/Yogstation#11530]
### Severity

Round Breaking

### Short Description

AI's radio was not working, intercoms next to me were working fine.

### Reproduction

Join lategame ai as me
Comms will not work.
The messages are sent to telecomms server and put into log, but dont get displayed on the main chat.

### Round ID

35524

### Test Merges

#11464, #11139, #11505

### BYOND Username

azzzertyy

**Comment by UselessTheremin** [comment]
could i get a round ID?

**Comment by azzzertyy** [comment]
![image](https://user-images.githubusercontent.com/42524344/121422013-abbbf080-c966-11eb-90ad-84b6c5030e20.png)
It was there from the start @UselessTheremin

**Comment by ReddicusDragon** [comment]
No longer an issue.
