### ISSUE TITLE
Pod's ripping the wires apart

### ISSUE THREAD

**Issue by Darkstick** [yogstation13/Yogstation#11540]
### Severity

Inconvenience

### Short Description

The contractor's extraction pod will take everything on the tile with it. This includes wires, pipes and terminals.

### Reproduction

1. Get kidnapped by contractor
2. Contractor calls their extraction pod
3. Get shoved in the extraction pod
4. Watch in awe as the wires on the tile the extraction pod was on follows you into the dojo

### Round ID

Round #35544

### Test Merges

#11464, #11139, #11505, #11425

### BYOND Username

Darkstick

### Additional information

![problem](https://user-images.githubusercontent.com/55104120/120096213-1f086b80-c0f8-11eb-8197-1e7c020913ef.png)

Those wires shouldn't be there.

**Comment by adamsong** [comment]
This is fixed in #11612
