### ISSUE TITLE
Saline-glucose solution takes back more blood than it gives

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#11555]
### Severity

Inconvenience

### Short Description

Lizard rejecting type-L blood and saline-glucose solution

### Reproduction

I've had this happen a few times now

1. Lizard with low/no blood
2. Inject saline
3. They gain blood volume, temporarily, and then lose it despite not bleeding
Also, though I'm not sure:
4. Inject L-type blood (I think - I didn't get to see the bloodbag they brought in actually, but the doctors said it was L)
5. They lose blood volume and get toxins in their bloodstream

You can take their own blood and duplicate it with unstable mutagen, which they'll accept

### Round ID

Most recently in 35653

### Test Merges

#11464, #11139, #11505, #11425, #11503, #11526, #11544, #11529

### BYOND Username

Sniblet

### Additional information

Testmerges aren't a part of it, I've seen the same thing happening for months

**Comment by adamsong** [comment]
Unable to reproduce

**Comment by Sniblet** [comment]
It usually happens when I'm a mediborg, it happened again at about 1 hour 50 minutes round number 35982 in the medbay
You can watch the curator's blood level dropping with saline-glucose solution active in his system, no blood in him for him to reject, no bleeding wounds, and he's human
Same happened to the plant Mandrake after I gave him saline, it's like saline in people with already low blood only boosts the blood volume temporarily and then takes it back to lower than it was when it started

**Comment by adamsong** [comment]
Saline glucose will replenish 5 times is own volume, but as it metabolized, that 5 times decreases, and so does the blood volume. The value being lower than it started at is most likely due to them bleeding in the process.

**Comment by Sniblet** [comment]
> Saline glucose will replenish 5 times is own volume, but as it metabolized, that 5 times decreases, and so does the blood volume. The value being lower than it started at is most likely due to them bleeding in the process.

Okay, I didn't know that, but I think it's too early to close this because to the very best of my knowledge they could not have been bleeding. All of these patients had 0 brute damage, left no blood on the floor, and I had tried to gauze some of them just to make extra sure that wasn't the issue. There was no way I can think of for them to be left with less blood than saline gave them.
