### ISSUE TITLE
charlie station(oldstation) has no grav in its atmosphereics room but everywhere else

### ISSUE THREAD

**Issue by Ethan4303** [yogstation13/Yogstation#11560]
### Severity

Inconvenience

### Short Description

charlie station(oldstation) has no grav in its atmosphereics room but everywhere else Is fine and has grav, the area Should have grav as its location for the room has the words /has_grav/ in it

### Reproduction

1. observer
2. join as oldstation crew
3. goto repair the atmos section
4. walking fine with full gravity upto the two firelocks that lead to the turn into atmos
5. lose traction to ground and float around while your cry trying to place pipes while drifting around
6. make github report

### Round ID

Round #35682

### Test Merges

#11464 #11139 #11505 #11425 #11544 #11526 #11529 

### BYOND Username

ethan4303

### Additional information

i wasnt actually in the round i just saw charlie station and remember it had broken grav in its atmos section and decided to actually make a report about it since the area code literally says /has_grav/ not very immportant though, just an inconvenience

**Comment by patpol4** [comment]
could be intentional, will take a look later

**Comment by patpol4** [comment]
![vivaldi_wf7vPpfDWJ](https://user-images.githubusercontent.com/48154165/121512667-3f82d080-c9ea-11eb-95dd-0d98ce0e2648.png)
![Code_JNAN7A6c9Z](https://user-images.githubusercontent.com/48154165/121512680-4578b180-c9ea-11eb-9345-a796cdcb716e.png)
Completely intentional, the mapper probably wanted to make it feel broken.
If we were to change it it would be a simple code fix

**Comment by patpol4** [comment]
Now it's just a decision of what's more important, the abandoned feel, or the ability to fix everything.

**Comment by Ethan4303** [comment]
Well if you fix everything on charlie station and you don't have grav in atmos is kinda lame, but you dah map man, so its up to you

**Comment by patpol4** [comment]
The ideal solution would be to allow charlie engineers to enable gravity here, dont station blueprints do that by changing areas?

**Comment by Ethan4303** [comment]
Not sure but you could remove the floor hull tiles and give charlie a gravity generator so when they repair the hull they get grav, and theyd have to repair or power the grav gen
