### ISSUE TITLE
Spider abilities not working

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#1156]
Tried using Spider Web as a spider, pressed the button, and nothing would happen. Also, the cocoon ability all spiders are supposed to have was not anywhere to be seen.

**Comment by Amelia0010** [comment]
>the cocoon ability all spiders are supposed to have
https://github.com/yogstation13/Yogstation-TG/blob/8f717d01a239a069add9f0264f659f1f81864606/code/modules/mob/living/simple_animal/hostile/giant_spider.dm#L94

That said, yeah the spin web appears to be broken for regular spooders

**Comment by Amelia0010** [comment]
oh hey
https://github.com/yogstation13/Yogstation-TG/blob/8f717d01a239a069add9f0264f659f1f81864606/code/modules/mob/living/simple_animal/hostile/giant_spider.dm#L349

so it's meant to be exclusively for nurses 👏

**Comment by MegaEmpirical** [comment]
Guess the tg wiki is inaccurate then, said all spiders get both abilities. The spider web ability button still shows up for normal spiders though, not sure why it's visible if it's not supposed to be used though.

**Comment by ThatLing** [comment]
https://github.com/tgstation/tgstation/issues/38324
