### ISSUE TITLE
Cryoing and saying no to offering your body to ghosts offers it anyways.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11561]
## Test Merges: 
Not Supplied / None
## Reproduction:
Ninety Nine percent sure this has to do with the testmerge that Alexkar is doing but when I cryoed ghosts got a prompt to take my body even thought I said no
 Submitted by: Sgtdevel (263097655322869763)

**Comment by adamsong** [comment]
Pretty sure this was fixed @alexkar598
