### ISSUE TITLE
Chasms with items on top of them

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#1157]
I was a miner doing my mining job when suddenly I fell into a chasm that was completly undetectable to the naked eye because there was a mining satchel on top of it. There was another person in the lobby who also fell into the hole.

without right click: https://gyazo.com/c1775c2b752c8736aec3f962b18ce580

with right click: https://gyazo.com/20828ca340a771ca5ab570926fde494b

**Comment by Time-Green** [comment]
feature.

**Comment by drderp3635** [comment]
well if its a feature it shouldn't be because it is bullshit

**Comment by Time-Green** [comment]
It was a joke, it's retarted and hilarious.
Anyway, I'd wanna try and look up the prob of this, but I am busy with rl stuff
