### ISSUE TITLE
Research rad collectors not disabling when tritium oxygen mix empty.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11579]
## Test Merges: 
Not Supplied / None
## Reproduction:
Rad collectors disable when out of plasma, research varient doesnt disable when out of its mixed gas, will continue to create co2 and research points, creates an interesting loop of puffing out co2 and creating space wind.
 Submitted by: Darthkill (188378776780931072)

**Comment by Darthkill** [comment]
Round ID:35727
![image](https://user-images.githubusercontent.com/33874385/121757932-3ba09c80-cb17-11eb-86d1-0e6996253b63.png)
![image](https://user-images.githubusercontent.com/33874385/121757946-5115c680-cb17-11eb-816b-5ab064f42bad.png)
![image](https://user-images.githubusercontent.com/33874385/121757972-730f4900-cb17-11eb-8961-d23b8a4e041d.png)
![image](https://user-images.githubusercontent.com/33874385/121758062-bf5a8900-cb17-11eb-94b4-68a247eaa109.png)
