### ISSUE TITLE
Yogsdelta toxins burn chamber ignition switch is borked

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11592]
## Test Merges: 
Not Supplied / None
## Reproduction:
Hit ignition switch, no fire me very angy
 Submitted by: DukeBobRoss (305348676883316737)

**Comment by adamsong** [comment]
I just tried it on a test server and it worked fine

**Comment by patpol4** [comment]
![image](https://user-images.githubusercontent.com/48154165/122200298-32a72680-ce9b-11eb-9a37-bc3002581257.png)
no reason this wouldnt be working

**Comment by adamsong** [comment]
The button works fine
