### ISSUE TITLE
Synthflesh can still be spammed on dead bodies

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11604]
## Test Merges: 
Not Supplied / None
## Reproduction:
You can still spam synthflesh on dead people even though you're supposed to only be able to use 60 at a time.
 Submitted by: The Grand Inquisitor (250794357211398144)

**Comment by maxion12345** [comment]
Basically you stasjs bed then, splash beakers to heal. Then dropper into eyes 1 water and 1 potassium to explode and remove the synthflesh.
