### ISSUE TITLE
Ask player if he wants to be an alien before making him one

### ISSUE THREAD

**Issue by Paragonid** [yogstation13/yogstation#1160]
When new alien is created, ghosting player is not asked if he wants to become an alien, he just becomes one.
Player might be AFK or being revived during it, so he might not want to get control over an alien.

**Comment by Time-Green** [comment]
Being an alien is awesome, I would want to be anytime. And also, it filters out braindeads

**Comment by Drakkon** [comment]
Braindeads, but not all AFKs? I think a lot people are just like "Oh... Well shit" whenever they suddenly become a mid-round antag without any sort of notification. Even though you have it selected, I think people would prefer the 10 second (or so) choice.

**Comment by supernoodles13** [comment]
Same thing happens with borers.

**Comment by Time-Green** [comment]
There's a pref for that. And I do kinda agree, borers spam real hard.

**Comment by Paragonid** [comment]
Pref changes possibility of becoming and not if you are going to be questioned, isn't it?

**Comment by Time-Green** [comment]
Borer and alien force you inside, they don't even ask.
If you have a pref disabled, they'll never ask for it.

**Comment by AdamElTablawy** [comment]
Turn off your prefs if you don't want to be an alien.

**Comment by Paragonid** [comment]
You probably have missed what I said.
I want to make meaningful choice depending on my current in-game situation if I want to be an alien in exact moment or not.

**Comment by Time-Green** [comment]
Then stay in your body if whatever you are is more important then xeno

**Comment by Paragonid** [comment]
So you suggest to open antag tab and switch preferences each time I die, and each other time to adjust to current situation?
Do you find it improving gameplay or adding immersion? 

It's repetitive useless clicking, when game can just ask me if I want to be alien or not.
It's shitty game design. I'm really amazed you are even arguing about it.

So what's your justification for letting AFKs to be aliens?

**Comment by Time-Green** [comment]
Because it doesn't. AFK's don't get selected

**Comment by Paragonid** [comment]
Can you explain how does anti-AFK system it work?

From my experience, I was HoS, got killed, in 2 minutes I became an alien. 
I'm quite interested, if I stop user input immediately after dying, would it still select me? Do I have to press something each 2 minutes at least once to not be considered AFK?

I sometimes just alt-tab from the game after dying. I think once I became borer during such.

**Comment by AdamElTablawy** [comment]
done
