### ISSUE TITLE
nimjas

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#1161]
I wanna nerf them but I'm probably too lazy to actually code real things

basically:

make them un-turn invisible when interacting with any living thing or throwing something
make them un-invisible when taking power
make the ninja sword not a literal stun sword

**Comment by supernoodles13** [comment]
Come on... how often do you ever see a ninja??.    let people have some fun.

**Comment by ShadowDeath6** [comment]
Nah, revenants are balanced because they're hard to kill but it's almost impossible to kill people on their own. 

Ninjas are completely undetectable, can teleport, fuck your round over in multiple ways, and has a sword that stuns or KOes at least once in any fight, has the highest damage of ANY available melee weapon, including traitor dual esword and abomination slashes, as well as full armor pen and natual ephedrine speed, space resistance, and adrenals. The only balance is that if they get hurt they need to remove their suit, but WAIT, they can just spam patches. They're wizards if wizards had innate armor and invisibility at the sacrifice of AoE bullshit

**Comment by ShadowDeath6** [comment]
Not to mention all-access and an emag standard issue

**Comment by darkwahn** [comment]
I'd definitely be up for limiting ninja invis in the ways you proposed.

**Comment by Super3222** [comment]
First two are good. But the third one can't really be solved unless it's already stunning. Lowering their brute force would put them on par with eswords, which they aren't suppose to equal.

**Comment by Jc1469** [comment]
I wonder if the bug is still around where stealth drains 0.01% of energy per second. 

The only thing I agree with is this.
> make them **turn visible** when interacting with any living thing or throwing something

They emit sparks from anything they're taking power from, both making a noise and giving a visual indication of where they are.  All it takes is a brain.  Oh wait.

**Comment by captainblobfish** [comment]
The fact that ninjas rarely do get spawned and that their suit requires more power to run, power that runs out quickly, I really don't think a nerf would be necessary. Let's be quite honest, while Ninjas are annoying, most of them can be easily killed by the heads of staff and/or security simply by stunning them and lasering them. Sure they have the ability to phase jaunt, but half the time, while stunned, they end up in a wall, or not very far off from where they were before, and they're still stunned. And again, let me remind you that they're rarely spawned...

**Comment by ShadowDeath6** [comment]
Rarity doesn't excuse poor balancing

**Comment by captainblobfish** [comment]
True, but space ninjas aren't as poorly balanced as you make them out to be. And considering that they rarely are spawned, people aren't as concerned with them.

**Comment by ShadowDeath6** [comment]
Also, a competent ninja is impossible to kill unless you get multiple lucky stuns in, because if they jaunt out twice, they can just recall their katana and drain wires while invisible the entire time.

**Comment by captainblobfish** [comment]
Yes, that's possible. But generally, it's not lucky stuns, all the ninja powers recharge, so it's not like they can jaunt multiple times, their jaunt isn't that far from their original spot, and when they're stunned, they're still stunned when they jaunt. Killing them is a matter of competence and teamwork.

**Comment by AdamElTablawy** [comment]
stale
