### ISSUE TITLE
Cloning cannot use multiple pods to clone.

### ISSUE THREAD

**Issue by Sgtdevel** [yogstation13/Yogstation#11629]
### Severity

Inconvenience

### Short Description

Cloning doesn't work with multiples pods even though full biomass on all clone pods and linked

### Reproduction

1. Build another clone pod
2. Link to console
3. Fill clone pod with console
4. Try to clone
5. Can't clone even though full biomass

### Round ID

N/A

### Test Merges

#11139 #11505 #11425 #11526 #11548 #11614 #11612 (Shouldn't be applicable)

### BYOND Username

sgtdevel

### Additional information

![image](https://user-images.githubusercontent.com/64398933/123098441-2709b180-d3ff-11eb-8879-8fb7ac48b044.png)
Even though someone is being cloned you can't do another clone even while its linked.
Its something to do with biomass code from what I've figured out.

**Comment by adamsong** [comment]
Is it supposed to be able to use multiple pods?

**Comment by adamsong** [comment]
It can, you just can't clone the same person into each
![image](https://user-images.githubusercontent.com/4607006/124047632-9e80a780-d9e2-11eb-986b-7f92f3366bad.png)

**Comment by adamsong** [comment]
Cloning with multiple pods works, you just can't clone the same person into two pods
