### ISSUE TITLE
adrenaline sacs on lings dont work

### ISSUE THREAD

**Issue by rublax** [yogstation13/Yogstation#11627]
### Severity

Quality of Life

### Short Description

adrenaline sacs dont remove stuns

### Reproduction

1. be a ling
2. purchase adrenaline sacs
3. get hit with detectives baton and go into stamina crit
4. use adrenaline sacs
5. still be in stamina crit

### Round ID

35871

### Test Merges

#11139, #11505, #11425, #11526, #11614, #11612

### Additional information

"Removes all stuns instantly. Can be used while unconscious. Continued use poisons the body."
this is false

**Comment by UselessTheremin** [comment]
not a bug, it doesnt remove all stamina damage and you were probably just hit a bunch of times.
