### ISSUE TITLE
Mentors

### ISSUE THREAD

**Issue by supernoodles13** [yogstation13/yogstation#1164]
So what would you guys think about a mentor system

Players would be able to make a-helps and mentor-helps,
A player would need to go through a similar process to an admin application to become a mentor.
The only power a mentor will be given is to handle Mentor-helps,

I believe this would give mentors a little idea on what it's like to handle admin-related responsibilites.
Also with the amount of times no staff are on, This would have an extremley positive impact on the server.

Also takes some of the pressure off the admins when the server is busy.

**Comment by aphielanis** [comment]
I love your idea Supernoodles. I have so much evil- I mean helpful advice to give.
 Seriously though I think if were in a position to give ic in ooc advice I could help others enjoy the game more.

**Comment by nazitra** [comment]
I'd be all for this and might even think about being a mentor.

**Comment by puremanbird** [comment]
Sounds great. I'd apply.

**Comment by drderp3635** [comment]
I would strongly support this

**Comment by Dagdammit** [comment]
I'd love to see this and would be happy to pitch in.

**Comment by XeonFaux** [comment]
Hippie's had this for quite a while.

**Comment by Smudged** [comment]
I reaallly Like this, I can maybe even teach med bay if I get mentor

**Comment by RandomUsername13753** [comment]
I support the idea. I'm new to the game, so i would like to see system like this.

**Comment by Jc1469** [comment]
Been suggested many times, never implemented.

> A player would need to go through a similar process to an admin application to become a mentor.

Not really for you to decide, and the way it was talked about was mainly admins would just give it to players they feel are experienced.

> Also takes some of the pressure off the admins when the server is busy.

Shouldn't even be taken into reasoning.  There's not enough active admins.  Making it easier to admin doesn't fix that.

**Comment by supernoodles13** [comment]
Jc I do realise that is not for me to decide, Was just stating what *I* think it should be like.

While it doesnt fix the enough active admins problem, it's a start.

**Comment by EMT321** [comment]
I think this would be a good idea. I also think it would be a somewhat challenging idea to code.

@super322 Could this be ported from hippie code?

**Comment by Super3222** [comment]
> @super322 Could this be ported from hippie code?

Yes, it can.

**Comment by AdamElTablawy** [comment]
Unfortunately according to council this is a no no
