### ISSUE TITLE
Bag of... transport i guess?

### ISSUE THREAD

**Issue by supernoodles13** [yogstation13/yogstation#1170]
>Gives rnd the ability to research bags of transport
>Only ore can be put in this bag
>All ore that is put in this bag would be transported to the ore redemption machine in cargo

This would be for miners that dont care much for points and just want to explore lava land.

Ill go ahead and say it, Ive got 0 experience with coding. I dont even know if this could be coded in.

**Comment by Time-Green** [comment]
Coding this would be childsplay

**Comment by Trojanplunder** [comment]
I'm all for this, even though I cant really contribute much to help it along. I usually don't bring minerals back till I got a ton, so this could be useful to get R&D started earlier as well.

**Comment by ShadowDeath6** [comment]
paradox bag

**Comment by Drakkon** [comment]
Make it programmable by simply using the bag on the redemption machine? 'Cuz golems.

**Comment by supernoodles13** [comment]
Drakkon I wouldnt see the use in that,   You would need to go to rnd to pick these up so any golems wanting to would have to do the same.

**Comment by Drakkon** [comment]
Golems have a RnD circuits in their point vendor. The often have working RnD in long rounds.
