### ISSUE TITLE
Duplicate Atmospherics Monitoring Console on MetaStation

### ISSUE THREAD

**Issue by Asdjky** [yogstation13/Yogstation#11714]
### Severity

Inconvenience

### Short Description

There are two atmospherics monitoring consoles right next to each other on MetaStation.

### Reproduction

1. Load up MetaStation
2. Go to the Atmospherics Desk
3. See the two Atmospherics Monitoring consoles on the east wall

### Round ID

N/A

### BYOND Username

Asdjky

### Additional information

There are two Atmospherics Monitoring consoles right next to each other on the east wall of the Atmospherics Desk room. They are exactly the same and show the exact same information. No other map does this so I assume this is simply an oversight and the second console either shouldn't exist or should be something else (DeltaStation has an Engineering Console as it's fourth computer, for example).

**Comment by adamsong** [comment]
Confirmed, two atmos control (not atmos alert, despite the name) consoles present at the location described
