### ISSUE TITLE
"mutate spell no longer works"

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11721]
## Test Merges: 
Not Supplied / None
## Reproduction:
As a wizard, chose the spell mutate, but it would not give me either the old hulk gene, or laser eyes.
 Submitted by: Cowbot (97736956326207488)

**Comment by adamsong** [comment]
It worked when I tested it earlier

**Comment by adamsong** [comment]
Wearing anti-magic armor (gem hardsuit) prevents its function

**Comment by Hopekz** [comment]
> Wearing anti-magic armor (gem hardsuit) prevents its function

Why was this closed right after the issue was identified?

**Comment by adamsong** [comment]
Intended behavior
