### ISSUE TITLE
Syndicate bluespace capsule

### ISSUE THREAD

**Issue by supernoodles13** [yogstation13/yogstation#1172]
So basically a capsule that works exactly like the mining capsules but this can be brought with tc

Inside will have some random syndie-gear. Aswell as an operating table for those *steal brain* objectives.

Just an idea i had, leme know what you think

**Comment by Drakkon** [comment]
Always wanted to see more capsules. Would like this personally.

**Comment by captainblobfish** [comment]
I feel like this would be a pretty cool idea. I think one of the problems though would be the space it takes up, and the location. I feel many players will end up spawning it on station, destroying certain areas. I mean, sometimes it occurs with regular mining capsules. And generally, it seems less practical for a traitor trying to use stealth, as there are few places on station, where someone wouldn't notice a strange building.

**Comment by AdamElTablawy** [comment]
No. It'd just be used to block off the brig and that's a stupid idea.

**Comment by supernoodles13** [comment]
I doubt someone would buy a syndicate bluespace capsule to block off the brig when they can just go to mining and get a normal one
