### ISSUE TITLE
T-Comms Mapping Issue - Boxstation

### ISSUE THREAD

**Issue by MayhemSailor** [yogstation13/Yogstation#11733]
### Severity

Low

### Short Description

Telecommunications Sign Covers Fire Extinguisher Cabiner

### Reproduction

![tcomm issue](https://user-images.githubusercontent.com/20588296/124966075-aee2e480-dfd7-11eb-8b3a-fada8e59f6eb.png)

### Round ID

#36089

### BYOND Username

MayhemSailor

**Comment by patpol4** [comment]
Technically this is minor since it only happens if you stand in the doorway but can still be tweaked.
