### ISSUE TITLE
Laughter/Slaughter Demon Proposed nerf

### ISSUE THREAD

**Issue by Smudged** [yogstation13/yogstation#1173]
I kinda feel like a Slaughter or Laughter demons are a little on the strong side, especially when they can knock some one into crit and instantly suck them into a pool of blood to heal themselves.

The stand point I want to touch on is that laughter AND slaughter demons should regurgitate the bodies they ate when they die, most of the time it feels unfair and you're almost cheated when you get ambushed by a laughter/slaughter demon, get knocked into crit, and your character erased from the round forever, even if they die. 

Having a laughter/slaughter demon vomit the corpses when they die seems fair to me, so it's not just an instant round sit out for an unsuspecting player.

**Comment by Cruix** [comment]
Laughter demons do spit people out when they die, that's one of the reasons they are cheaper than slaughter demons in the wizard's spellbook.

**Comment by Smudged** [comment]
Oh, I did not know that, hmm, I may just close this or get this closed early then. . .

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/1155
