### ISSUE TITLE
Mapmerge doesnt work or me

### ISSUE THREAD

**Issue by Lostlarry** [yogstation13/Yogstation#11750]
### Severity

Development Issue Only

### Short Description

whenever i run the Mapmerge script it just says press anykey to continue

### Reproduction

1. run prepare maps
2. make change to yogbox
3. run Mapmerge
4. nothing happens

### Round ID

not on server

### Additional information

So the only thing that i think could cause this is the presence of outdated required programs. but requiremnets_install also does nothing for me

**Comment by UselessTheremin** [comment]
the mapmerger works, but if you're having problems with it use something that doesnt take the mapmerger. this isnt really an issue regarding the yogstation server but your own dev tools, on top of that it's incredibly nonspecific and essentially impossible to fix off this information given. if you disagree feel free to reach out to me on the discord, Theremin#3676
