### ISSUE TITLE
Mining Shuttle Notification

### ISSUE THREAD

**Issue by Trojanplunder** [yogstation13/yogstation#1176]
Hi all. This is my first time posting an issue, so be gentle! This might have been proposed before but I cannot recall.

Proposed change:
Have the mining shuttle give a notification to everyone on the supply channel when it is called.

Why I think it's necessary:
The number of times that miners, including myself, have been victim of a careless/dumb miner or QM calling the shuttle with no warning is ridiculous. The first couple times it happened was funny, now it's just annoying. Even if it was a 3 or 5 second warning before the shuttle moved, I think it would help reduce the rage caused by this.

I have no idea how to do the magical DM coding, so if anyone is willing to help on this, I'd be grateful!

**Comment by Rocks4Free** [comment]
I like it, would also be interesting if such a thing was controlled by telecomms and was sabotage-able.

**Comment by Trojanplunder** [comment]
Yeah, probably connecting it to tcomms would be good. I'm not sure how to sabotage it, unless it was something like making it move immediately when emagged.

**Comment by Trojanplunder** [comment]
Since super is awesome, this can be closed
