### ISSUE TITLE
visually human, set as different species.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11767]
## Test Merges: 
Not Supplied / None
## Reproduction:
I was customising my character as human, yet the species was set to lizard. Visually, everything about the customisation screen was human and yet the game was treating the character as lizard
 Submitted by: Ploofy (335827580718415883)

**Comment by adamsong** [comment]
Did you have a command role set to high?

**Comment by UselessTheremin** [comment]
yeah this aint a bug you were probably looking at your backup human with a command role selected
