### ISSUE TITLE
fixing decapitations is too hard just use a metal rod 

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1177]
Why does it have to be this neat perfect surgery? Should the cloner care? Why can't we just jab a metal rod into someone's neck hole and then jam a head on top of that for cloning?

**Comment by Rocks4Free** [comment]
If it fucks up they get cloned with a metal windpipe, unchokeable. It's a win-win.

**Comment by ShadowDeath6** [comment]
why not just shove their brain into their torso and clone them

**Comment by aphielanis** [comment]
Because using a rod in this way is metal as fuck, GG Allin would be proud
