### ISSUE TITLE
AI's cannot control shells while being slashed, so they cant save themselves from attackers

### ISSUE THREAD

**Issue by maxion12345** [yogstation13/Yogstation#11779]
### Severity

Inconvenience

### Short Description

see above title. is this intended? because it realllly pissed me off when it happened. I was right there, but I couldn't use my shell to save myself.

### Reproduction

be AI
use shell
get slashed
you get ejected from the shell automaticly
repeat until you die because you cant be in the shell long enough to survive

### Round ID

36188

**Comment by Bibby0110** [comment]
I'd wager this is intended

**Comment by bruhlookatthisdood** [comment]
Im 99% sure this is intended because if the AI is in a shell and gets attacked, it would not know it is being attacked.
So it would tleeport you back to the core.

**Comment by UselessTheremin** [comment]
this is intended yeah dont see why it wouldnt be, prevents ai from saving itself too easily
