### ISSUE TITLE
crit overlay doesn't work

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11814]
## Test Merges: 
Not Supplied / None
## Reproduction:
Sometimes the crit overlay flat out refuses to work, meaning you can see everything around you while in crit. I tried asking when it happened on the server but Alexkar is a massive stinky and didn't want to provide any info what so ever
 Submitted by: Bibby (212531662305755137)

**Comment by adamsong** [comment]
I think this is just an engine issue with overlays not working, or at least that is the response to multiple similar issues

**Comment by UselessTheremin** [comment]
yeah, engine issue
