### ISSUE TITLE
Player Forced to Move in One Direction Continuously

### ISSUE THREAD

**Issue by yellowface7** [yogstation13/Yogstation#11816]
### Severity

Inconvenience

### Short Description

This is a well known glitch that happens commonly. I'm now reporting this because it literally murdered me.

### Reproduction

1. Join the round as anything (including ghosts)
2. Move around (Does not always trigger it) (Sometimes you can go whole shifts without it happening)
3. Witness your character moving continuously in one direction.
4. Double press the key in which you are being forced to move in to stop it.

### Round ID

36259

### BYOND Username

yellowface7

### Additional information

Difficult to reproduce. due to it's random nature. 

Decided to write this bug report since no one else has.

Marked it as Inconvenience as it forced me to walk in lava which killed me after going several days without it happening.

**Comment by yellowface7** [comment]
My first bug report. Sorry if it's not good enough. Got fed up with this after it literally murdered me.

**Comment by Bibby0110** [comment]
I think I remember this being a BYOND issue, usually happens to me when the server is high on time dilation

**Comment by yellowface7** [comment]
Odd. Has this happened on other BYOND games?

**Comment by UselessTheremin** [comment]
you can fix this by pressing the movement wasd key and arrow key in the same direction as you are moving this is a byond problem
