### ISSUE TITLE
you cannot carry monkeys

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11846]
## Test Merges: 
Not Supplied / None
## Reproduction:
It's imposible to fireman carry or piggyback carry monkeys, in the case of piggyback carry it tells the monkey they don't have the dexterity to do this
 Submitted by: cuackles (237761038500626442)

**Comment by adamsong** [comment]
You can't aggressive grab monkeys, so of course you can't fireman or piggyback them
