### ISSUE TITLE
Observers unable to spawn as Harvesters

### ISSUE THREAD

**Issue by Cartlord** [yogstation13/Yogstation#11878]
### Severity

Inconvenience

### Short Description

Observed round, Nar'Sie spawned and I couldn't spawn as a Harvester. To reproduce it in the listed round, I asked admins to bus her in postround, and I was still unable to spawn as a Harvester - I am not bloodcultbanned, and wubawubadickcheney was also unable to spawn as a Harvester while Observing that same round, so I assume Observing is the main problem here.

### Reproduction

1. Observe round
2. Have Nar'Sie spawn
3. Click Nar'Sie
4. Double-click Nar'Sie
5. Spam-click Nar'Sie
6. Fly into Nar'Sie
7. Not be a Harvester

### Round ID

36312

### Test Merges

#11425 #11739 #11746 #11768 #11727 #11720 #11800 #11798 #11797 #11803

**Comment by SomeguyManperson** [comment]
Fixed
