### ISSUE TITLE
Metastation Grey Tide opens the toxins burn chamber

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#11886]
### Severity

Round Breaking

### Short Description

Nobody coded the toxins burn chambers doors out of the Grey Tide event(Yogstation/box does this)

### Reproduction

Trigger tide event until it hits science.

### Round ID

Round #12345

### BYOND Username

Aphielanisn

### Additional information

 I can't remember the round number but it happened on a round where someone was experimenting with fusion in the chamber so when tide virus hit it burned the floor tiles out of most of science and with all doors in science being opened up the fire spread far into most of it.

 Also worth bringing up is that the rest of our maps(besides box) should probably be checked to make sure they are correctly set up for the Grey Tide event.

**Comment by adamsong** [comment]
When I've brought it up before and the response was its intended, the box station one does this too.

**Comment by MajManatee** [comment]
it IS intended
