### ISSUE TITLE
Oriented drawings & buffered text

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation#1189]
If you write buffered text with a crayon while you already have an oriented drawing selected (outline, arrow) it applies the orientation to the buffered text too. Results in silliness.
https://i.gyazo.com/02e4c58f9a3717d9eebbe72d1ecf09ae.png

**Comment by ShadowDeath6** [comment]
not a bug...?

**Comment by Rocks4Free** [comment]
>not a bug

So text is supposed to appear upside-down?

**Comment by ShadowDeath6** [comment]
well if you wanna write it upside down then who's gonna stop you

**Comment by Rocks4Free** [comment]
The thing is, I didn't want to write "true" in 3 different directions.

**Comment by ShadowDeath6** [comment]
oh it's random

**Comment by AdamElTablawy** [comment]
BBCode error was already fixed
