### ISSUE TITLE
yogbot errors are vague

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11941]
## Test Merges: 
Not Supplied / None
## Reproduction:
Very vague
 Submitted by: adamsogm (177073258716200961)

**Comment by adamsong** [comment]
"No title/body detected in message. If this is a bug yell at someone!" Doesn't say 'You need a title, please put Title: before the message, or anything, it just give a vague error

**Comment by Bibby0110** [comment]
> "No title/body detected in message. If this is a bug yell at someone!" Doesn't say 'You need a title, please put Title: before the message, or anything, it just give a vague error

Pretty simple logical connection you have to make.
Why didn't you just change this yourself anyhow

**Comment by alexkar598** [comment]
Wrong repo

**Comment by Bibby0110** [comment]
Wrong repo as alexkar said
