### ISSUE TITLE
using bonesetter tells you bone has been put in its place but it dont

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11964]
## Test Merges: 
Not Supplied / None
## Reproduction:
using the bone setter in a dislocated joint on harm intent tells you the bone has been set to its place but examining the person again tells you the bone is still dislocated
 Submitted by: cuackles (237761038500626442)

**Comment by adamsong** [comment]
I think the confusion is the attack message look similar to the confirmation message, so beyond making the message more clear that it isn't being used, this is not an issue
