### ISSUE TITLE
the cryopod room's cryo-console that is usually one the wall is one tile forwards on box

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11965]
## Test Merges: 
Not Supplied / None
## Reproduction:
the console that you can check to view cryo'd people and retrieve items is no longer on the wall
 Submitted by: Cowbot (97736956326207488)

**Comment by alexkar598** [comment]
caused by computer shift pr

**Comment by patpol4** [comment]
map is fine
