### ISSUE TITLE
pand.e.m.i.c machine may not have a character limit on the naming of viruses

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11963]
## Test Merges: 
Not Supplied / None
## Reproduction:
As title, see screenshot.
 Submitted by: Darthkill (188378776780931072)

**Comment by Darthkill** [comment]
![image](https://user-images.githubusercontent.com/33874385/128564809-49ecea2e-77e1-488d-8839-d2e6dbf0c45f.png)

**Comment by Darthkill** [comment]
There is some limit somewhere, I put 100,000 digits of pi in, it went into the box, but didnt accept it. But I still think it has an unreasonable character count

**Comment by UselessTheremin** [comment]
Lmao

**Comment by redmoogle** [comment]
Fixed by: #12361
