### ISSUE TITLE
Harvesters don't have cult HUD

### ISSUE THREAD

**Issue by Badspler** [yogstation13/yogstation#1197]
Harvesters don't have cult HUD.
Implementing cult HUD would stop harvesters mistaking and attacking fellow cult members.

**Comment by Cruix** [comment]
Harvesters are supposed to harvest everyone who is not a construct, whether or not they are cultists.

**Comment by ShadowDeath6** [comment]
yeah tg did this because people got assmad about harvesters teamkilling

the only problem is that narsie vs ratvar is super one-sided because when narsie is summoned she immediately loses 9 followers and can't convert anyone

**Comment by AdamElTablawy** [comment]
this was disabled because 10000 harvesters showed up on end ronud report and will not be re-added
