### ISSUE TITLE
Medibots, Medibeams, nanites, and other items can't heal wounds from the wound system

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#12027]
### Severity

Round Breaking

### Short Description

Wound system https://github.com/yogstation13/Yogstation/pull/11955

### Reproduction

https://github.com/yogstation13/Yogstation/pull/11955
Doesn't work for medibots, medibeams, nanites, or other healing items. These items can't heal wounds.

### Round ID

Round #12345

### Test Merges

#11955

### BYOND Username

Aphielanisn

**Comment by SomeguyManperson** [comment]
intended game design
