### ISSUE TITLE
Make Ash Walkers speak a different language

### ISSUE THREAD

**Issue by Dagdammit** [yogstation13/yogstation#1202]
Make it so ash walkers have a unique language which is the only one they speak & understand. Code for this is already in place, as I understand it.

At the same time, make starting prompt less explicitly hostile regarding station crew, i.e: "Strange aliens have come from the stars, bearing weapons too advanced for us to understand. Their motives are unclear, but they seem intent on expansion. Protect the nest at all costs."

Lastly, put at least one more universal recorder somewhere in cargo or the mining station, since those things translate.

**Comment by Drakkon** [comment]
Don't think a lot of people would like the role change part, but I'm all in for everything else.

**Comment by Stealthkibbler** [comment]
both of these options do not work well with eachother, for example, creating a language barrier is cool and all, but you simply cannot make them less hostile as it creates another thing that distances them from everything else.

Their nest would also need to be remade and walkers would need something from the station that benefits them. A good example of this would be medical supplies, but theres nothing stopping them from just raiding mining or looting a miner.

The concept of prisoners of war is particularly cool and would create more interaction between walkers and miners. They can already craft restraints from sinew, however they have no way to non-lethally incapacitate their target, so to remedy that I think the best solution would be to make a copy/paste of a syringe gun for the ashwalkers, give it the skin of a crossbow and allow them to craft poison darts that can incapacitate humanoids. The other problem I see here is preternis, they have a natural immunity to all toxins and chems and Adams species rework will only increase their immunities, this would lead to many miners going preternis to avoid being captured by walkers.

Overall the amount of content that could be added on just based around these ideas is potentially large, but it would need more discussion and debate especially considering the massive problems and how everything ties together.

**Comment by Dagdammit** [comment]
The role change is BECAUSE a language barrier would make things more hostile, like it was purely a thought on how to offset that. I don't want to limit what role ash walkers can play in a round- to me they're coolest when they're both potential allies and potential foes.

I don't see any NEED to remake the nest before this could be implemented, though it could certainly help improve things.

**Comment by captainblobfish** [comment]
I think of Ash Walkers akin to Native Americans during and through the 1500s-1800s and I'd like to think that their starting message would be a little less harsh, so they can judge for themselves whether the shaft miners are hostile or not. This would definitely allow the Ash Walkers a bit more freedom, to be a little more peaceful, or extraordinarily hostile. Now, sometimes ashwalkers act peaceful, but that's extraordinarily rare.

**Comment by Dagdammit** [comment]
Captain says it better than I could.

**Comment by captainblobfish** [comment]
Thanks. I mean, I can see both sides of the argument and I was just stating my views on Ash Walkers and their aggressiveness. I should state that miners may not put in the effort to attempt to translate languages. I mean, when I play shaft miner, I mostly wander around, killing monsters and exploring ruins.

**Comment by Dagdammit** [comment]
Not to feature creep this request, but if you want the ash walkers to have
something of value to trade, simplest option might be to make all or
most tribal crafting options their schtick? Like they require a special
crafting tool (like screwdriver) ash walkers spawn with.

**Comment by Super3222** [comment]
@Dagdammit This was done in the ashwalker overhaul.

**Comment by Dagdammit** [comment]
Am aware, and I love it! Ash walkers still understand what's said to them,
though- was that a deliberate decision? Just a limitation of the language
system?

**Comment by Cruix** [comment]
Now that I look at the code I see that all ashwalkers can actually speak and understand human, it's just that they can also speak and understand ashwalker. Should probably fix that.

**Comment by Dagdammit** [comment]
Intent was the chief being the only bilingual one, right? That seemed like
a neat compromise.
