### ISSUE TITLE
as a pacifist zombie you cannot infect anyone at all or attack anyone

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12043]
## Test Merges: 
Not Supplied / None
## Reproduction:
Round: 36665
Get infected by a zombie and die reanimate and realize you are literally able to do nothing but break airlocks.
 Submitted by: Sgtdevel (263097655322869763)

**Comment by Bibby0110** [comment]
Hugbox

**Comment by UselessTheremin** [comment]
this is a feature but i will make a pr to change this i guess

**Comment by MajManatee** [comment]
i guess its intended. Skill issue.
