### ISSUE TITLE
Revolutionary keeps rev 'R' player marker after being turned into cyborg.

### ISSUE THREAD

**Issue by Badspler** [yogstation13/yogstation#1204]
I experienced this as a rev head - can not confirm if this is the same as a non-head rev.

Revolutionary leader when debrained and placed into a cyborg leaves the new cyborg with the ability to see who revolutionaries are with the 'R' symbol next to their person.

Given that IC your character should remember nothing. Having the HUD remain should be considered a bug.

**Comment by Trojanplunder** [comment]
I saw this too. As a normal rev I saw a Borg with a rev symbol. Can't remember if it was a red or blue one though.

**Comment by AdamElTablawy** [comment]
After reproducing this a few times this can safely be declared an edge case and closed
