### ISSUE TITLE
cyborgs cannot interact with machines

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12048]
## Test Merges: 
Not Supplied / None
## Reproduction:
no menus appear but hotkeys for airlocks and the like still work
 Submitted by: Maxim (181876893178527744)

**Comment by adamsong** [comment]
Were you out of power? Had you selected a module?

**Comment by UselessTheremin** [comment]
???
this not really a solveable issue, i havent seen this pop up anywhere else since either and this post seems dead in the water. closing, but if you want to give more details, be my guest
