### ISSUE TITLE
Alternate titles PR gives the table ID change program a massive list of jobs to choose from instead of the normal amount

### ISSUE THREAD

**Issue by maxion12345** [yogstation13/Yogstation#12055]
### Severity

Inconvenience

### Short Description

Basically, you can set jobs via department with the tablet. However, as each department has different job titles now (more then one Quartermaster title etc) you have options for all these titles despite them all having the same access

### Reproduction

download ID program
go to "jobs"
select cargo
you'll have to scroll to see all the cargo jobs despite there being just five

### Round ID

36683

### Test Merges

#12016 #11946 #11955 #11768 #11425 #12014 #11864 #11876 #11878 #11999 #12022 #11708 #11973 #12050 #12047

### Additional information

for the love of god stop testmerging so much

**Comment by adamsong** [comment]
Fixed
