### ISSUE TITLE
Weapon Disappears

### ISSUE THREAD

**Issue by XeonFaux** [yogstation13/yogstation#1205]
[Note]: Coming from a player (Corvex Mercer), if you slip on shards while carrying two sharp weapons (i.e. spear and holy claymore), you lose one of the weapons. It does not seem to get embedded, it just disappears.

**Comment by Time-Green** [comment]
Stuff can get launched quite a distance if you fall.
Are you sure it didn't just fly away and/or possibly hit and embedded someone else?
