### ISSUE TITLE
Flood lights dont depower once turned on and cut from grid

### ISSUE THREAD

**Issue by Ethan4303** [yogstation13/Yogstation#12053]
### Severity

Round Breaking

### Short Description

FLood Lights dont depower once cut off from the power grid if they are turned on and must be manually flicked off

### Reproduction

SLings thrawl me
people are building floodlamps
find one left alone and powered
cut the cables around it connecting it to the grid
cut the apc wires too to be sure
flood lamp still active and emitting light
cry becuase all slings are dead now

### Round ID

Round #36679

### Test Merges

#12016 #11946 #11955 #11768 #11425 #12014 #11864 #11879 #11999 #12022 #11708 #11973 #12050

### BYOND Username

ethan4303

**Comment by Sniblet** [comment]
This is extra funny when people build reinforced windows on top of the floodlamp creating a massive light source with no weaknesses whatsoever because they literally hate fun
