### ISSUE TITLE
Ghosts Cannot Orbit Shadowlings

### ISSUE THREAD

**Issue by yellowface7** [yogstation13/Yogstation#12069]
### Severity

Inconvenience

### Short Description

All ghosts couldn't orbit slings, making it difficult to spectate them. Only way to properly watch is to follow or autospectate. Reconnecting and relogging doesn't fix issue.

### Reproduction

1. Hit the observe button in a sling round
2. Wait for a sling to hatch
3. Try to orbit the sling once hatched
4. Observe how you don't move with the sling while orbiting

### Round ID

36696

### BYOND Username

yellowface7

### Additional information

Note: I was orbiting them as they were hatching but other ghosts reported that this is happening to them too.

**Comment by yellowface7** [comment]
UPDATE: There was one sling that round I was able to orbit out of the three.

**Comment by Oblisk234** [comment]
Shadowlings no longer exist, see #20581
