### ISSUE TITLE
weird wacky gene description

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12066]
## Test Merges: 
Not Supplied / None
## Reproduction:
.
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/877254675626344478/2021-08-15_20_52_53-Yogstation_13__Neckbeard_Edition_Delta.png)
 Submitted by: cuackles (237761038500626442)

**Comment by UselessTheremin** [comment]
hmmmmmm
