### ISSUE TITLE
IDs: Job-change does not change the job-icon on security HUD

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#12086]
### Severity

Inconvenience

### Short Description

Changing jobs does not replace the sec HUD icon.

### Reproduction

- change ID to different job
- on sec HUD it still shows the original job

### Round ID

36724

### BYOND Username

Aquir

**Comment by ShoziOffical** [comment]
You need to update sec record for this

**Comment by 00aquir** [comment]
Weird, I don't think I encountered this exact issue (job icon not changing on sechud) for a while now, actually.

**Comment by warface1234455** [comment]
> Weird, I don't think I encountered this exact issue (job icon not changing on sechud) for a while now, actually.

the sechud is synced to sec record console not the ID console one sooo yeah

**Comment by warface1234455** [comment]
but maybe i can make sec record sync to id console

**Comment by ShoziOffical** [comment]
Wait nvm, it doesnt do anything with sec record, my apologize

the bug seems to be not existed, tested

**Comment by 00aquir** [comment]
okay thanks
