### ISSUE TITLE
Crew monitoring is not working

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#12097]
### Severity

Round Breaking

### Short Description

Crew monitoring is not functioning throughout the shift.

### Reproduction

- check crew monitoring:

![SS13-crewmonitoring](https://user-images.githubusercontent.com/16806055/130325802-52c031eb-2159-412d-8329-c826f7f9e072.png)

### Round ID

36761

### BYOND Username

Aquir

**Comment by adamsong** [comment]
Fixed
