### ISSUE TITLE
Port over Rotatium from TG (chemistry)

### ISSUE THREAD

**Issue by puremanbird** [yogstation13/yogstation#1209]
Causes the victim's screen to display a rocking motion and deals moderate toxin damage. 

Made by 
1 part mindbreaker
1 part teslium
1 part neurotoxin
Metabolizes at 0.24 units per tick. 

Looks cool as fuck. We should port this.

**Comment by ShadowDeath6** [comment]
Slow metabolize and toxin damage gives me a bad feeling

**Comment by Ephemeralis** [comment]
Another poison/reagent nobody will ever use.

**Comment by AdamElTablawy** [comment]
Nope. Not being ported as it caused a massive fuckton of errors that took 10 PRs to fix over on /t/g
