### ISSUE TITLE
YogsMeta: Double-door tile

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#12103]
### Severity

Inconvenience

### Short Description

 Double-door on a tile.

### Reproduction

- see double doors at brig on YogsMeta, different accesses are needed
- sec officers can't access maint

![SS13-doubledoor](https://user-images.githubusercontent.com/16806055/130358766-8da2a45d-b30c-43d9-a0b5-d59378880494.png)

### Round ID

36780

### BYOND Username

Aquir

**Comment by adamsong** [comment]
Probably was resolved before the fullmerge
