### ISSUE TITLE
sheltered trait is broken 

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12107]
## Test Merges: 
Not Supplied / None
## Reproduction:
Round: 35787
Severity: gamebreaking
Brief Description: Sheltered trait doesnt work
Steps to Reproduce: join the round as someone with the sheltered trait
Byond Ckey: fireclaw787
Linked Github issue: n/a
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/879126099093749770/unknown.png)
 Submitted by: ThatGuyPhil (308057723394719754)

**Comment by N3D6** [comment]
this is intended. you can understand common but not speak it

**Comment by adamsong** [comment]
Intentional, #11994
