### ISSUE TITLE
Brig physician is eligible for antag

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#12102]
### Severity

Round Breaking

### Short Description

Seems someone forgot to check a flag, dot their i's, and cross a t

### Reproduction

1. Be Brig Physician
2. Get antag through RNG

### Round ID

Round #36769

### Test Merges

#11776

### BYOND Username

Aphielanisn

### Additional information

If this was intentional then I'm sure we can do without a brig physician because the problems they solve aren't worth the ones that they could cause.

**Comment by adamsong** [comment]
Intentional, they have the same brig access as lawyer, who can also roll antag. They are not sec, they are medical with sec access

**Comment by burn1cycle** [comment]
> Intentional, they have the same brig access as lawyer, who can also roll antag. They are not sec, they are medical with sec access

 I'm not sure you have a concept of game balance. Can you explain what this will do to game balance?
