### ISSUE TITLE
Airlocks painted 'external' are bugged

### ISSUE THREAD

**Issue by adamsong** [yogstation13/Yogstation#12135]
### Severity

Low

### Short Description

An airlock painted 'External' shows as invisible

### Reproduction

1. Obtain airlock painter
2. Use airlock painter on airlock
3. Select 'External'
4. 
![image](https://user-images.githubusercontent.com/4607006/130702029-b519d83f-f7ab-4e82-931f-93f6425d0ab4.png)
And yes, that airlock is closed.

### Round ID

N/A

### Test Merges

#11955 #11776 #12101 #12091 #12016 #11768

**Comment by 00aquir** [comment]
This was kinda like https://github.com/yogstation13/Yogstation/issues/10385

In round 36818 silly Marshall sprayed many doors the same way:

![SS13-airlock-paint](https://user-images.githubusercontent.com/16806055/130706049-8fa4299d-e84b-4e32-8668-cc2b9fc24371.png)
