### ISSUE TITLE
Abductor glands are unfun and completely unfair

### ISSUE THREAD

**Issue by Genesis720** [yogstation13/yogstation#1213]
In their current state, abductors are extremely unfun, and unfair to abductees. Abductors as an antagonist role are okay, but they should be a non-harming antagonist role. This is for a number of reasons, the main one being that abductors can disguise themselves, and have an instant stun. If an abductor wants you, there isn't much you can do about it, especially if you are just beginning your shift.

The glands I have an issue with are: Bodysnatcher, Plasma, and to a lesser extent, Bloody. The issue with these glands is they all directly fuck over anyone they are implanted in. For example, if you are abducted and implanted with a bodysnatcher gland, if the abductors sleep you before sending you back to the station, you will be asleep until it gibs you. The player has no recourse, cannot go to the medbay, cant call for help, etc. Its just a death sentence. The same goes for plasma. 

**Any gland that just straight up kills the player before they can respond is bad, and extremely not fun to play against.** 

It is just extremely unfun to be killed as a newspawn walking to your department because you got ambushed by an abductor masquerading as a security officer, implanted with a  bodysnatcher gland, and then gibbed before you wake up.

These glands need to be removed or balanced by significantly increasing the time it takes for them to kill you.

**Comment by puremanbird** [comment]
Going to agree with genesis here. I've seen abductors fuck over countless antags by giving them plasma or body snatcher glands. Its just not fun for anyone.

**Comment by ShadowDeath6** [comment]
I thought we removed all the gibbing glands when we added abductors to rotation

**Comment by xbobsherex** [comment]
eh ive been gibbed every single time when abducted. its usually when i have hijack too.

**Comment by Time-Green** [comment]
Those glands were removed, the only negative gland is blood spew thing.
Why are they bad? I enjoy having superpowers.

**Comment by Time-Green** [comment]
We forgot to remove them in the rebase it seems

**Comment by aphielanis** [comment]
I totally agree.  Abductors can be very disruptive to the round and with a good teleport agent nearly unstoppable with no recourse for security or anyone to do anything about them because they get special invulnerable teleport huts on a secured z-level.
 On top of all that they do barely anything to make the round more interesting for others.
 The least they could do is not kill or cripple the people they abduct.
