### ISSUE TITLE
broken piano

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12157]
## Test Merges: 
Not Supplied / None
## Reproduction:
Round: 36879 and forward
Severity: annoyance
Brief Description: Grand pianos will no longer play songs correctly.
 Submitted by: Alv Cyktor (277567415049519105)

**Comment by UselessTheremin** [comment]
This has been the case for quite a while but only for certain songs, it's well known that the SS13 song tool often doesn't play songs too well on piano, so there are specific piano songs. Not really an issue just a quirk, I'd say. The piano makes a different sound.
