### ISSUE TITLE
crash on join

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12162]
## Test Merges: 
Not Supplied / None
## Reproduction:
Round: Unknown
Severity: severe
Description: 8/26, updated BYOND to latest version, attempted to join a round as a ghost, game very briefly loaded then crashed. Attempted 1 hour later with similar results. TL;DR, unable to play due to consistent crashing
 Submitted by: SpaceCowboy (279983328881278976)

**Comment by adamsong** [comment]
Known bug, downgrade to 514.1554

**Comment by TheMommaDragon** [comment]
How do we downgrade?

**Comment by adamsong** [comment]
Duplicate of #12170
