### ISSUE TITLE
putting ammoboxes back into vendors will replenish the box with fresh ammo

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12173]
## Test Merges: 
Not Supplied / None
## Reproduction:
Round: 36881
Severity: severe
Brief Description: if you put beanbag box that bartenders come with that are empty into the vending machine, it will dispense a fresh box with ammo.
Steps to reproduce: take out beanbag shells from beanbag box, put into vendor, dispense said beanbag box, and you will see shells again
 Submitted by: Alv Cyktor (277567415049519105)

**Comment by Oblisk234** [comment]
Can't replicate, beanbag boxes cannot be inserted back into the vendor, logs and replay are non-existent.
