### ISSUE TITLE
BYOND in its latest version (514.1564?) creates an apparent game close?

### ISSUE THREAD

**Issue by TheMommaDragon** [yogstation13/Yogstation#12170]
### Severity

Inconvenience

### Short Description

Recently updated BYOND. Game keeps closing itself after having moved into Observe mode.

### Reproduction

1. Update to latest version (where it doesn't state on the program itself what the current version is, and if you're in beta or not, now)
2. Proceed to... probably do anything to join the game.
3. See the game close. Multiple times.
4. File a bug report and realize you can't put in a Round ID, because you can't get a round ID when the game closes really, really quickly on you.

### Round ID

N/A - cannot be acquired due to the rapid crash.

### Test Merges

This might be a version related issue - not a test merge related issue.

### BYOND Username

TheMommaDragon

### Additional information

Yes, it closes the window (crashes?) incredibly quickly, making it (near? almost?) impossible to check on things, including round ID. So, Momma Dragon can't do anything in this case.
The server might just need an update, though, is all, if that is the case.
It is defined as an Inconvenience as she doesn't exactly know what to call it.

**Comment by adamsong** [comment]
Known issue, downgrade link until fixed: http://www.byond.com/download/build/514/514.1554_byond.exe

**Comment by adamsong** [comment]
Fixed
