### ISSUE TITLE
Moving away from a borg you're buckling to makes the timer start again (and fail again)

### ISSUE THREAD

**Issue by ToasterBiome** [yogstation13/Yogstation#12180]
### Severity

Inconvenience

### Short Description

Moving away from a borg you're buckling to makes the timer start again (and fail again)

### Reproduction

1. be a human
2. drag yourself onto a borg
3. before the bar completes, move away
4. the bar will reset, you are now a tile away from the borg
5. it will fail 

### Round ID

36911

### Additional information

it's because of https://github.com/yogstation13/Yogstation/pull/12115

**Comment by adamsong** [comment]
Intended behavior

**Comment by ToasterBiome** [comment]
It starts the progress bar while there is a tile of distance between you. This is obviously a bug.
