### ISSUE TITLE
Non-Stealth Antags get a Sec HUD icon

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#12206]
## Brief Description
Non-stealth antags like shadowlings, xenos, zombies, wizard, etc get a hostile HUD icon

It turns out people like to dress kind of like antags but don't like it when security accidentally kills them and security players don't like getting drawn into a debate with the staff over whether it was an accident or not.

## Requirements
HUD icons for all non-stealth antags for sec

# Bounty:
$25

**Comment by Reed0506** [comment]
so basically deny the possibility of stealth for these antags because people are stupid?

**Comment by yacabo** [comment]
How blind do you have to be

**Comment by cuackles** [comment]
maybe just like, use your eyes ? or common sense maybe ? its not that hard

**Comment by num1bamf** [comment]
Maybe ask for a change in the way paint can cover a person so you don’t get confused.

**Comment by adamsong** [comment]
Are you paying the bounty, or is this something you want payed for out of server funds?

**Comment by nmajask** [comment]
Love this idea, though it may be a good idea to expand this to ALL antags, so sec doesn't accidentally arrest or kill the wrong person and always know who to arrest

**Comment by adamsong** [comment]
12 downvotes plus requester agrees its a bad request
