### ISSUE TITLE
New Alien Ruin to replace the old one (AKA Weyland lab or w/e)(feedback needed)

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation#1221]
Given the current alien ruin is rather outdated and for the most part just causes issues because of players deliberately running into the eggs and spawning xenos I think it could do with being completely replaced with another xeno themed block, so this is the idea i have pitched but I want feedback and opinions/ideas before I actually bother to spend time and effort into making it.

**Concept**
A Xenomorph Testing facility owned by the Syndicate, players who spawn as the ghost role will be able to experiment, test and even mess around with xenomorphs. The Xenomorphs in question WILL be player controlled (given a ghost has their prefs enabled) allowing for a rather unique experience everytime, one round the xenos might be new players, subject to the veteran syndies toys and tests as they see just what makes these xenos tick. Another round the xenos could end up being veteran players who easily break containment and really show how unpredictable and formidable the xenomorphs can be.

**Safety Measures**
The ruin will be completely surrounded by a sea of lava on all sides to prevent the xenomorphs from escaping, the Syndicates will have basic ballistics and some toys to play with, however they will have to exercise caution because the xenos breaking out of their containment is a very real threat. The syndicates WILL NOT be able to leave the ruin and heavy precautions will be taken to make sure that they cannot spread the infection outside of containment. I will go out of my way to ensure the ruin is designed to prevent this. However it is worth noting that there is still the possibility of a miner trying to break in to loot the place, it may also provide an experience for the miner if he arrives to a slaughter.

**Purpose**
The purpose of this ruin is to create a controlled environment allowing players to experience, practice and learn how to contain and fight xenomorphs as-well as how to play the different xenomorph castes. It will also allow players to gain a greater understanding of the xenomorph life cycle and the role that each caste plays in a xenomorph hive. Because of the rarity of xenomorph events or rounds, many players who eventually get to play xenomorph are clueless as how to succeed as them, because xenomorph is a very fast paced team orientated role this more often than not ruins the round for the other xenomorphs. Likewise many players also do not know how to combat xenomorphs and this will open up a chance for players to test weapons and find out the best ways to deal with them, as Xenomorphs do not have an established metashield and are considered a delta threat they are fair game for anyone.

**Other concepts**
Ontop of this idea ever since lavaland was introduced I've always thought of replacing the animal hospital, because it is a ruin that requires a moderate to high level of rp to enjoy and simply just doesnt fit the pace for lavaland or the game at all in general. It would be better off replaced with an elaborate ruin that can tutorial players on the medical system by using sleepers, surgery, cryo and vice versa. I very much like the syndicate theme of things because it puts players in the mindset for mischief, giving them a wider range of ways to mess around and experiment with what is available.

Inspiration from Kor Phaerons syndicate chemical plant base.

**Comment by Time-Green** [comment]
Where is my Weyland-Yutani?

**Comment by Ratvar** [comment]
And then syndie with full xeno organ kit inside of him flee after robusting miner with boat/bubblegum kills everything.Maybe,pit around them,not lava?Harder to get reward for miners,harder to flee,harder to destroy.

**Comment by captainblobfish** [comment]
I do have to agree, a sea of lava may not stop these syndies and xenos from escaping. A pit would work much better. But I feel some players may bored after a bit, having no contact with the outside world. Not to mention, with a sea of lava, one can only imagine the horror of a syndie scientist escaping and killing countless people on station.

**Comment by captainblobfish** [comment]
Though I do like the idea. It sounds pretty interesting.

**Comment by Stealthkibbler** [comment]
There's only one way the syndicates would be able to get across the lava, the spamming of a fire extinguisher and burn patches. If people do abuse these then they will not get nanomeds, if some players don't find it enjoyable to play this ghost role then quite simply they should not pick it.

**Comment by captainblobfish** [comment]
True, but they can also escape if a miner builds a boat and enters the ruin. And if a syndie kills the miner, they can take the boat.
