### ISSUE TITLE
items that are two hand required can't be picked up

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12225]
## Test Merges: 
Not Supplied / None
## Reproduction:
Round: Recent rounds
Severity: Gamebreaking
 Submitted by: N3D6 (315319488767852545)

**Comment by Cartlord** [comment]
Can confirm, would pick up potted plants but drop them instantly at my feet

**Comment by SomeguyManperson** [comment]
this should be resolved
