### ISSUE TITLE
attempting to buckling horizontal people as a borg just opens their clothes menu on help intent

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12221]
## Test Merges: 
Not Supplied / None
## Reproduction:
Round: Unknown
Severity: Annoying
Brief Description: Opens the menu instead of buckling if they’re dead/crit
 Submitted by: biome? (99679712363675648)

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/12212

 will probably fix
