### ISSUE TITLE
telekinesis not functioning properly

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12228]
## Test Merges: 
Not Supplied / None
## Reproduction:
Researched telekinesis and used mutator to achieve it.
I could interact with consoles / machines, but I could not grab any items / objects. It funnily enough also caused me to drop any potted plant I tried picking up immediately.
 Submitted by: Knejtstrup (150691184270901249)

**Comment by SomeguyManperson** [comment]
fixed this
