### ISSUE TITLE
game keeps crashing after sending welcome to yogstation 13! many times until it disconnects.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12244]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: Gamebreaking
As soon as i join the game the "Welcome to Yogstation 13!" message keeps getting spammed for a few seconds after it reconnects automatically, after a minute or so of this connection fails. Specifically started happening in round 37014 after the chat broke.
Screenshot: https://imgur.com/a/1WChtgY
 Submitted by: Deus Vult (782285978110001152)

**Comment by Yeetalorian** [comment]
I’m having the same issue

**Comment by TimeURSS** [comment]
Same here, I had no chance to play since this happened and nothing works, reconnecting, quitting and rejoining, and even cache purging. Not sure what will be of us...

**Comment by Oblisk234** [comment]
Can't replicate, no logs or replay either to indicate anything.
