### ISSUE TITLE
Ling chat.

### ISSUE THREAD

**Issue by AbrahamShnobelberg** [yogstation13/yogstation#1224]
Hello. I just wanted to notice that if you try to chat in changeling channel (say ":g*") while not a changeling makes one say something in a regular way. As found out later, it was for changelings only. The funny part of this is that one can still speak like any other generic crew member _while unconcious_.
In addition, I suspect all similiar non-radio channels will give the same result to unconcious human nonantags.
I guess that's enough.

I apologise for my bad knowledge of English.

**Comment by ShadowDeath6** [comment]
Using a prefix like :g or :s without access to that channel will make you speak on regular radio

**Comment by captainblobfish** [comment]
Well, I'd have to say that I haven't spoken while unconscious. Which I guess is a good thing.

**Comment by Cruix** [comment]
Nice catch, I am amazed no one had already discovered this.

**Comment by captainblobfish** [comment]
Idk. I mean, some people say :g in chat as a joke sometime when they're not a changling. But I don't think anyone does it while they think they can't talk
