### ISSUE TITLE
Cyborgs immune to light eaters

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#12256]
### Severity

Inconvenience

### Short Description

Cyborg floodlights stay on after being hit with a light eater

### Reproduction

1. Be me, a nightmare
2. Be charged at by an engineering cyborg with maxed floodlights and a sec officer riding him
3. Hit the cyborg
4. Its lights stay on
5. Hit it again
6. Its lights stay on
7. Skill issue
8. Watch in horror as the borg dabs at your cremation

### Round ID

37043

### Test Merges

#11955: 'Ports wounds from TG' by SomeguyManperson at commit c140ad0485 #12120: 'Added Advance tools to engineering cyborg' by JayBaez at commit 283d38b69b #12105: 'Ports Turnstiles from NSV13 (or beestation no clue where they came from)' by maxion12345 at commit b55180ecc6 #11768: 'Re-adds old cloaks along side new capes, Also makes dufflebags less shit.' by JamieD1 at commit 3ffa274c65 #12150: 'Adds emergency spare, a temporary ID with AA that heads can print' by adamsong at commit 00a6b62390 #12033: 'Makes Yogs Widescreen better - End screen fades properly without weird tiles, should also make round end sounds play 85% of the time.' by JamieD1 at commit beaaf23eeb #12242: 'Makes the Chat/Verbs actually work after reconnect *hopefully*' by JamieD1 at commit 9d938a8211 #12226: 'Reworks the sleeper so it passively heals instead of using chemicals' by SomeguyManperson at commit 0c23776c4e #12254: 'Applies pretty filter and OOC toggle to discord OOC channel' by adamsong at commit 17430b6795

### BYOND Username

Sniblet

### Additional information

The problem might be related to the sec officer riding the borg? But I know the light wasn't from the officer, I saw the borg's lights still on.
Man this severity dropdown doesn't have any accurate options does it

**Comment by Oblisk234** [comment]
Think it was fixed by #17639.
