### ISSUE TITLE
Character setup does not render all parts of characters (Windows 7, IE 11)

### ISSUE THREAD

**Issue by dragontamer8740** [yogstation13/Yogstation#12272]
### Severity

Inconvenience

### Short Description

Many parts of characters are not rendered at all in the sidebar

### Reproduction

1. Go to "character setup" in Windows 7 with IE 11 installed.
2. Characters all look like this:
![ss13](https://user-images.githubusercontent.com/6090083/132598186-af476573-f689-4b59-bb79-a2567f2fda6a.png)

### Round ID

37085

### BYOND Username

Dragontamer8740

### Additional information

I have a Windows XP (IE 8) laptop that I also tried this on, and the character seemed to render correctly there (although I had other problems on it that aren't relevant to this report).

I have tried clearing cache, turning off accelerated graphics, and so on.

If it matters, I am using Windows 7 in a Virtualbox VM under Debian. I believe it is fully up to date.

If there's a way that I can inspect the DOM of the page, please let me know and I'd be happy to poke around. I just don't know how to do it in BYOND/IE.

**Comment by Firewolf34** [comment]
Do you also have issues with icons rendering black in-game?

https://cloud.githubusercontent.com/assets/8237862/19582917/8e6632ee-9706-11e6-8b7f-5369b8d4ad09.png

There's a ancient BYOND issue if you have old or stock graphics drivers on very specific systems - where transparency ordering is not rendered properly. If so, there are a few fixes...  

Not sure how that affects a virtual machine though.

**Comment by UselessTheremin** [comment]
Yeah this is not really a bug for Yogstation specifically it seems to more be a hardware issue
