### ISSUE TITLE
You can use a chainsaw with only one arm.

### ISSUE THREAD

**Issue by Badspler** [yogstation13/yogstation#1229]
While the chainsaw is two handed to wield. If the user has only a single hand they can still pickup, start and use a chainsaw.

![saw](https://cloud.githubusercontent.com/assets/4272723/20430119/64cd44ce-adf7-11e6-93c3-755aced0544a.png)

**Comment by aphielanis** [comment]
I had this bug happen to  me when I was trying to replace a lost hand with a chainsaw. I was happy that the code would let me pick up the saw but being able to use it too was kind of ridiculous. 

 I hope when it's fixed we can still carry the chainsaw one handed but not be able to use it.

**Comment by Super3222** [comment]
I can probably make an unfun check for this

**Comment by AdamElTablawy** [comment]
Fixed
