### ISSUE TITLE
Solo Changelings can get the Absorb Another Changeling Obj

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#12313]
### Severity

Inconvenience

### Short Description

Solo Changelings can get the Absorb Another Changeling Objective

### Reproduction

Be solo changeling
spawn
get absorb another changeling objective
cry because objectives are impossible

### Round ID

37188

### Test Merges

#12120 #12105 #11768 #12242 #12226 #12298 #12270 #12292

### BYOND Username

TheBombMaker

**Comment by adamsong** [comment]
Wait for a latejoin ling
