### ISSUE TITLE
white pixels on digilegs with tacticool turtleneck

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12310]
## Test Merges: 
Not Supplied / None
## Reproduction:
same as title
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/887523220343914496/2021-09-14_22_43_57-Yogstation_13__Ticket_to_Midnight_Five.png)
 Submitted by: cuackles (237761038500626442)

**Comment by nmajask** [comment]
I took a look at the DMI file and couldn't find any white pixels on any of the syndicate uniforms. Have you been able to replicate it in any other rounds?

**Comment by 00aquir** [comment]
There is (or was, not sure if it's fixed) a similar thing when I got a white pixel sticking out of one foot of a human character in some rounds, with randomized clothing and the same footwear. Maybe one of sock sprites caused that one..

**Comment by nmajask** [comment]
> There is (or was, not sure if it's fixed) a similar thing when I got a white pixel sticking out of one foot of a human character in some rounds, with randomized clothing and the same footwear. Maybe one of sock sprites caused that one..

How long ago was this?

**Comment by 00aquir** [comment]
> How long ago was this?

It happened maybe less than a year ago, I'm not entirely sure. It was a white pixel sticking out sideways at the bottom of the foot.

**Comment by 00aquir** [comment]
Here it is, happened right now:
It shows up only from the front

![SS13-sockpixelbug](https://user-images.githubusercontent.com/16806055/133946085-af0a56b8-7b5f-4f90-8588-1eb69fa4310e.png)

**Comment by nmajask** [comment]
> Here it is, happened right now:
> It shows up only from the front
> 
> ![SS13-sockpixelbug](https://user-images.githubusercontent.com/16806055/133946085-af0a56b8-7b5f-4f90-8588-1eb69fa4310e.png)

Two questions, what are you wearing if it happens again and can you try relogging to see if that fixes it?

**Comment by 00aquir** [comment]
You mean socks? I generally don't know because I got randomized clothing.

**Comment by 00aquir** [comment]
The white pixel is visible in the round replay, so it's not just for me.

The "only" thing that changes is virtually everything about the character, including the undergarments. And I can't check them directly by name (the randomized character page shows different attributes every time you open it ([actually, the hair and skin color ingame can differ from what is shown in the security records, even](https://github.com/yogstation13/Yogstation/issues/9349)). At least I showed the socks on the picture. - but I tried all the sock types in another round, every sock was fine.. it's something else.

**Comment by SomeguyManperson** [comment]
original issue looks like it might be the pants not covering the body properly not sure about the pixel on the socks though

**Comment by 00aquir** [comment]
okay I had some time. That white pixel is caused by the Vomit Goose shirt.

**Comment by nmajask** [comment]
> original issue looks like it might be the pants not covering the body properly not sure about the pixel on the socks though

I'll look into fixing that later today

**Comment by nmajask** [comment]
> original issue looks like it might be the pants not covering the body properly not sure about the pixel on the socks though

Its not that, all the other digialts have that same space shown. As for the white pixel by the socks, I think my [new PR](https://github.com/yogstation13/Yogstation/pull/12356) will fix it.

**Comment by nesisknesis** [comment]
i think his new PR will fix it

**Comment by nmajask** [comment]
> i think his new PR will fix it

It didn't, it fixed a different bug mentioned in here, not the main one.
