### ISSUE TITLE
[Metastation Mapping] Missing disposals pipe in paramedics office.

### ISSUE THREAD

**Issue by Badspler** [yogstation13/yogstation#1233]
There is a missing disposals pipe under the maintenance exit door in the paramedics room.

This causes items dropped in the medical storage disposals shoot to come out into the paramedics room. 

Also while mapping changes happen. I would bring up that there is no Health Scanner HUD's in the paramedics room.

![wut](https://cloud.githubusercontent.com/assets/4272723/20452281/c8e0e52e-ae6a-11e6-8f27-d482f0a05235.png)

**Comment by matskuman5** [comment]
This has been fixed. #1246

**Comment by matskuman5** [comment]
This should be closed now
