### ISSUE TITLE
Ion guns(and probably EMPs too) don't work on sentient vending machines

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#12332]
### Severity

Inconvenience

### Short Description

xx

### Reproduction

1. Sentient vending machine
2. Shooty ions
3. Not work

### Round ID

37227

### Test Merges

xx

### BYOND Username

Aphielanisn

**Comment by UselessTheremin** [comment]
This is because they aren't a mob that's resistant to EMP's, the vending machines become living beings, this isn't a bug just a way that the game works
