### ISSUE TITLE
Monstermos doesn't space rooms exposed to space randomly

### ISSUE THREAD

**Issue by maxion12345** [yogstation13/Yogstation#12336]
### Severity

Round Breaking

### Short Description

Putting holes in the walls bordering space doesn't empty rooms of their air, and sometimes it stops at doorways/invisible firelocks for some fucking reason

### Reproduction

Go to a wall bordering space
remove wall
the air will not flow out

however, go to a random tile in the middle of the room
remove the floor with the RCD
now air flows out

Tl;dr, phantom walls
![](https://i.gyazo.com/8642b2ff1a43d05f18ef690ac244192b.png)

### Round ID

37249

### Test Merges

The following pull requests are currently test merged: #11901: 'Ports "Ship construction through the power of science!" and others' by nmajask at commit f35ad53c27 #12270: 'Infiltration game mode' by Absolucy at commit 13c8af884a #12226: 'Reworks the sleeper so it passively heals instead of using chemicals' by SomeguyManperson at commit ec42ca2925 #11708: 'Ports Automatic Station Stabilizer Bots from Bee (ASSBot)' by maxion12345 at commit 89393299d8 #12303: 'Force roll a number of security personnel based on roundstart pop' by adamsong at commit ca9e954664 #12207: 'Unifies the cloaks' by grimm-hollowknight at commit b6fd6ea5d5

### BYOND Username

wubawubadickcheney

**Comment by JamieD1** [comment]
Easy to fix, need a list of all events where monster mos doesnt update.

**Comment by maxion12345** [comment]
happened again

![](https://i.gyazo.com/5ea98ea67328032b518bafd7537f0a51.png)

**Comment by maxion12345** [comment]
standing in the breach will space the room after a second or two
sending you flying out into space

**Comment by maxion12345** [comment]
@JamieD1 
so far its shit like rods destroying walls, RCDs, and I think thermite

**Comment by maxion12345** [comment]
two more instances of this occuring, its been happening more and more often. First photo you can see a bomb hole, no firelocks blocking air to escape, but the air above the treatment center is A-OK.

Second photo you can see perma is spaced, but the area below perma isn't despite there being a clear path for air to flow

![050a838dc9b911f4ded59f3916ff473c](https://user-images.githubusercontent.com/23666142/143718937-fb69f2f5-fe4e-4a8e-947d-b04183a927d9.png)

![77b7e0c174d1436e94ece1eceab089e7](https://user-images.githubusercontent.com/23666142/143718946-2a775680-3c6f-45bb-a61e-69193aee64a0.png)

**Comment by maxion12345** [comment]
more photos of this happening
![ed1f7679989fdaf3d6b6f93fd20290e0](https://user-images.githubusercontent.com/23666142/144491350-ebadcc35-9c22-4914-a417-2a83bb9f2d38.png)
