### ISSUE TITLE
[Metastation Mapping] Prisoner shuttle brig door has no access restrictions.

### ISSUE THREAD

**Issue by Badspler** [yogstation13/yogstation#1234]
The highlighted door in the picture has no access restrictions on it. This really should have security access required to open. Any lifeform can open these 3 doors.
![wut](https://cloud.githubusercontent.com/assets/4272723/20452505/115e1ace-ae70-11e6-8aca-1541e877278b.png)

**Comment by captainblobfish** [comment]
I agree. Making these doors only for sec personnel would make escape a bit harder for prisoners...

**Comment by Stealthkibbler** [comment]
Is it just that door? If it is then its intended because if it had access restrictions then prisoners finishing their sentence wont be able to leave.

**Comment by AdamElTablawy** [comment]
That's the bottom door so prisoners can leave.
