### ISSUE TITLE
leather shawl visual bug                                                                                                    

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12357]
## Test Merges: 
Not Supplied / None
## Reproduction:
 Round (If Round specific): #37297
Severity: low
Brief Description:  the leather shawl is invisible when you wear it, no matters who wears it you wont be able to see it (still see it in a description or in your character slot)
Steps to Reproduce: just make a leather shawl and wear it
Byond Ckey: pu55yd3str0y3r
Linked GitHub Issue: (Optional)
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/890489546746241084/unknown.png)
 Submitted by: kokodril0 (509793285422710815)

**Comment by nesisknesis** [comment]
fixed
