### ISSUE TITLE
brig huge bug

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12358]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: Inconvenience
Round 37297. Brief Description: the new brig pop thing is totally broken, the thing told me the prisioner had 2 mins left in cell while to a admin it showed up 8 minutes past and the guy i brigged claimed that he was 17 minutes already (12 minute sentence)
Steps to Reproduce: just use the new broken brig machine. Byond Ckey: pu55yd3str0y3r
 Submitted by: Maxim (181876893178527744)

**Comment by maxion12345** [comment]
working on issue now, trying to reproduce in test server

**Comment by maxion12345** [comment]
unable to replicate issue, never saw it
