### ISSUE TITLE
In Circuit lists, empty entries cannot be deleted.

### ISSUE THREAD

**Issue by Hate9** [yogstation13/Yogstation#1236]
Issue reported from  Round ID: 16671 (Yogstation 13 [99% LAGFREE!])

Reporting client version: 512

[Round ID]: #16670

[Reproduction]: Create any kind of a list within a circuit (I think I used the "at" component, but it really shouldn't matter), add an item (I did string, but again, it should work regardless), and click cancel in the textbox (or click ok without entering: both work), now try to delete that item.

**Comment by Altoids1** [comment]
Circuits dead, closing.
