### ISSUE TITLE
xeno queens can contract viruses

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12370]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: Inconvience
Round 37325 A Xeno Queen kept on falling into unconciousness after somehow contracting a healing virus, unknown if bug or feature.
Byond Key: Xoxeyos
 Submitted by: Xoxeyos (127653089879523328)

**Comment by N3D6** [comment]
This isn't a bug afaik, xenos are supposed to catch viruses
