### ISSUE TITLE
YOU DONT KNOW YOUR FUCKING SEC TIME

### ISSUE THREAD

**Issue by boodaliboo** [yogstation13/Yogstation#12387]
### Severity

Low

### Short Description

UNKNOWN PRISON TIMERS

### Reproduction

GET ARRESTED WONDER HOW FUCKING LONG YOUR TIMER IS WITH NO INDICATORS AT ALL

### Round ID

EVERY ROUND WITH NEW SEC

### BYOND Username

BOODALIBOO

**Comment by maxion12345** [comment]
just
examine your ID
It lists the times and the crimes
not a bug

if they aren't handing you the ID then that's another problem entirely

**Comment by boodaliboo** [comment]
> just examine your ID It lists the times and the crimes not a bug
> 
> if they aren't handing you the ID then that's another problem entirely

you cant examine your id it just brings up what your wearing no matter what you do

**Comment by maxion12345** [comment]
![](https://i.gyazo.com/9416e4be1839b3f913a8f0428b932b9e.png)
 
unable to reproduce bug

**Comment by maxion12345** [comment]
tested on main server after feedback from bug reporter, still cannot reproduce

**Comment by adamsong** [comment]
Others were unable to reproduce, and the PR is closed
