### ISSUE TITLE
Golems might not be able to roll special_names or human surnames

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#12397]
### Severity

Low

### Short Description

Golems might not be able to roll special_names or human surnames despite there being code for those

### Reproduction

look at the code
![image](https://user-images.githubusercontent.com/36427443/135731490-a25df97d-e612-43b0-ae96-0b6463d67403.png)
determine using your coding expertise whether the order of those rolls make nonstandard golem names impossible
memorize the list of golem_names
make 200 golems in a test server and see if any of them draw names from elsewhere
scream

### Round ID

N/A

**Comment by adamsong** [comment]
I got it to spawn a human name with a boosted human name chance, indicating the code likely works, I'll take a closer look at a later time though
