### ISSUE TITLE
Meteor almost always destroys permabrig it might as well be the "F### permabrig event"

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#12395]
### Severity

Round Breaking

### Short Description

Perma-brig due is an essential function to the round but due to it's size and exposure to space always gets ruined by meteors

### Reproduction

Invoke Meteor event on a test server
Shoot holes in permabrig

### Round ID

xx

### Test Merges

xx

### BYOND Username

Aphielanisn

### Additional information

Hey, I'm not asking for the armory, lockers, HoS office, escape pod, or sec office to get shielded. I'm asking for a place that both protags and antags need to use but due to geometry it's one of the most likely places to get hit by meteors which is supposed to be random and not favor any one area of the station.

**Comment by patpol4** [comment]
This is supposed to happen, random event to give prisoners a possibility to escape
