### ISSUE TITLE
Firelocks suck

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#12401]
### Severity

Round Breaking

### Short Description

Firelocks have multiple bugs causing atmos to stop moving and crowbar situations to be random

### Reproduction

Today I got caught in a damn firelock bug where the locks decided it was ok to let me through halfway and then close them both and crowbar seal shut with me trapped in the vacuumed area between. Without a crowbar I died and had lots of salt. I've been playing around the (newish) firelock code for a year at least and it still seems random what situation needs a crowbar and what doesn't. I think it's just broken which **leads me to a question.**
Why the fuck do we need crowbars?! Can't they just open?

The other problem these dumb ass doors have is that if destroyed they freeze(stop, pause) atmos on that tile. You could build a fusion chamber out of invisible walls created out of destroyed firelocks it's really amusing but broken and wrong.

### Round ID

xx

### Test Merges

FUCK_U_Monstermos

### BYOND Username

Aphielanisn

### Additional information

Fastmos_Gang_4Ever

**Comment by UselessTheremin** [comment]
this is in no way a solveable bug, resubmit this as an actual request and not a paragraph of venting. we aren't your therapists, aphi
