### ISSUE TITLE
(Genetics) Mutation Anti-glow just makes you give off a blue light

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#12403]
### Severity

Low

### Short Description

Anti-glow is using the weak effect of something that will cause darkness but it's set so low on anti-glow that it will just glow blue even in dark areas. Reinforcing chromosomes do not make it much stronger either.

### Reproduction

1. Get Anti-glow mutation
2. Astound your friends with your "glow" that isn't "anti" in any way.

### Round ID

xx

### Test Merges

xx

### BYOND Username

Aphielanisn

### Additional information

For some reason humanized monkeys seem to get a much more powerful version. I've experimented with and without power chromosomes, too.

**Comment by MajManatee** [comment]
resolved
