### ISSUE TITLE
wizard curse of madness able to type whatever you want

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12423]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: Round Breaking
Wizards can type whatever message they want into curse of madness, allowing them to massively confuse players into breaking the rules to the point it requires admin intervention
 Submitted by: LynxJynx (171696800258981888)

**Comment by Cartlord** [comment]
Wait why is this bad

**Comment by patpol4** [comment]
Not an issue.
