### ISSUE TITLE
Implanter UNUSABLE #2

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#12431]
### Severity

Round Breaking

### Short Description

Mindshield injectors sometimes refuse to work (on anyone (it doesn't start the implanting process)) (while other injectors may or may not).

### Reproduction

- mindshield injector refuses to work sometimes
- WHEN you can print another injector, that can usually work
- otherwise, it breaks the round by sec not being able to actually implant people
- it happened in more than one round
---
- continuation of https://github.com/yogstation13/Yogstation/issues/7527

### Round ID

37572

### BYOND Username

Aquir

**Comment by Oblisk234** [comment]
Can't replicate, implanting people with mindshield implanters works fine and no logs or replays available.
