### ISSUE TITLE
brig physician rolling gang head

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12432]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: Moderate
Brig physician is able to roll gang head and it massively bugs out because the brig physician doesnt end up being given the gang tool or pen and they also dont spawn mindshielded so security can meta the fact they have no mindshield.
 Submitted by: LynxJynx (171696800258981888)

**Comment by nmajask** [comment]
Ah, fuck. I'll take care of this later today. _Should_ be an easy fix.

**Comment by nmajask** [comment]
I still haven't found what's going wrong. They are one of the restricted roles, so they _shouldn't_ be able to be a gang leader. Ill continue looking tomorrow for the issue.

**Comment by Oblisk234** [comment]
Going to say this was the fault of dynamic, since it was known to give roles that are restricted antag anyway. Also, since dynamic was disabled and removed in #22136 and #22661, it's likely solved, and if it wasn't, gangs were removed by (or something else did) #22635.
