### ISSUE TITLE
Security camera console Really slowed down

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#12451]
### Severity

Inconvenience

### Short Description

Security camera console view slowed down considerably in several rounds in the last month.

### Reproduction

- the window pop-up, or switching cameras slowed down **quite a bit** in several rounds compared to one month ago.

### Round ID

37605

### BYOND Username

Aquir

**Comment by 00aquir** [comment]
okay this is very slow, almost unmanageable sometimes, "You are either AFK, experiencing lag or the connection has closed." message popped up momentarily even twice when I used it today, only when I used the camera console.

**Comment by UselessTheremin** [comment]
I'm guessing this is lag on BYOND's end or client-side, I've never heard of anyone experiencing this and never experienced this

**Comment by 00aquir** [comment]
oh no, to me this is a very noticable and annoying change in experience compared to what it was before, it seemed like something was changed in the code, it became very delayed, and even dragging the camera console window became very choppy.

**Comment by 00aquir** [comment]
seems better nowadays
