### ISSUE TITLE
Cloning identity change

### ISSUE THREAD

**Issue by BlueishTsunami** [yogstation13/Yogstation#12465]
### Severity

Inconvenience

### Short Description

Identity when reading mind is changed after cloning

### Reproduction

1. Get cloned
2. have mind read
3. name is different

### Round ID

37666

### BYOND Username

blutsu

### Additional information

Inconvenient / possibly round breaking depending on how you categorize it. This may be intended, but very strange circumstance. After getting cloned, anyone who reads your mind sees a different identity than your own. On this round, I was accused of a ling and thrown in perma, because a clown read my mind and saw my name was different. On top of this, i was getting hunted down after release from perma due to said mindreaders. Again, this may be intentional, but seems really strange that my "real identity" changes after being cloned. This definitely seems like a bug, and everyone in the after-round OOC was very confused and bewildered by this.

**Comment by SomeguyManperson** [comment]
occurs because the new body spawns with its own information that is overwritten by the clone information iirc

**Comment by BlueishTsunami** [comment]
That certainly makes sense, is this intended behaviour though? You would think a clone would be grown from your DNA, and would retain the original identity

**Comment by Oblisk234** [comment]
Mind reader is no longer a gene, see #21513
