### ISSUE TITLE
Burning tips

### ISSUE THREAD

**Issue by BlueishTsunami** [yogstation13/Yogstation#12474]
### Severity

Low

### Short Description

burning fingertips showed up in my inventory

### Reproduction

1. not sure, noticed partway through round

### Round ID

37701

### BYOND Username

blutsu

### Additional information

Looked in my inventory and found burning fingertips, probably noticed around 1:45 or so? Not sure how

**Comment by Oblisk234** [comment]
Can't replicate, logs don't go back to 2021 and replays don't either.
