### ISSUE TITLE
irradiated items break

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12493]
## Test Merges: 
Not Supplied / None
## Reproduction:
Brief Description: Some items which are Irradiated will "break." Looking normal on the floor besides the Irradiated green glow, but being completely invisible in hand and being barely visible and unclickable in the bag. I haven't done any testing (sorry) but it's only happened to Irradiated items with no pattern I've spotted.
 Submitted by: DukeBobRoss (305348676883316737)

**Comment by Oblisk234** [comment]
Can't replicate, items worked fine while irradiated, also no round ID either.
