### ISSUE TITLE
Playing AI with traitor enabled rolls malf even if malf is disabled in preferences

### ISSUE THREAD

**Issue by maxion12345** [yogstation13/Yogstation#12505]
### Severity

Inconvenience

### Short Description

see title

### Reproduction

1. have traitor on, but malf off
2. set AI to high
3. roll antag
4. you are now malf good luck lolololol

### Round ID

37752

### Test Merges

#12270: 'Infiltration game mode' by Absolucy at commit 9b05590f27 #12226: 'Reworks the sleeper so it passively heals instead of using chemicals' by SomeguyManperson at commit c065dc1879 #12207: 'Unifies the cloaks' by grimm-hollowknight at commit 0af8068151 #12459: 'Removes the xray from eye of god cope seethe etc etc' by SomeguyManperson at commit 738f059a3e #12447: 'adds bone gel recipe for chemistry and alternative recipes for other stack healing items that require trekchems instead of botany' by SomeguyManperson at commit 3d160d757f #12418: 'Greyscales Polysmorphs Part Two' by Mqiib at commit e531c0dc0d

**Comment by UselessTheremin** [comment]
you rolled traitor ai not malf ai you dingus
