### ISSUE TITLE
Couldnt turn myself into an android as a technophile chaplain

### ISSUE THREAD

**Issue by GalacticBird** [yogstation13/Yogstation#12515]
### Severity

Round Breaking

### Short Description

as the title suggests, I tried to turn into a robot with the 350 favor ands strapped to the table and it said that it couldnt be done right now. Later, I tried with a friend and she could turn the first attempt.

### Reproduction

1. Join a round as a technophile chaplain
2. Gain enough favor to turn yourself into an android
3. Strap yourself to the Altar and hit it with the book
4. Select the Ritual and a message appears saying that you can't do it right now and you can't do it around this time.

### Round ID

Round #37770

### BYOND Username

GalacticBird

### Additional information

I really wanted to turn myself into a robot that round, doing the whole old mad man RP and allying myself with RnD and it was a sad conclusion the fact that I couldn't do the thing that I wanted to do because of a bug, atleast I still had fun.

**Comment by UselessTheremin** [comment]
I cannot seem to find a reason for this issue, I've never seen anything similar and it hasn't been reproduced. I admit, I'm not the most familiar with chaplain as a role, and there is the possibility you were just doing it incorrectly. Closing for now, if you disagree with this contact me.
