### ISSUE TITLE
cloning a starting zombie will make the cloner instantly malfunction

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12526]
## Test Merges: 
Not Supplied / None
## Reproduction:
cloning a roundstart zombie will make the cloner instantly make it a failed cloning
round ID:37796
 Submitted by: cuackles (237761038500626442)

**Comment by UselessTheremin** [comment]
From what I'm seeing, this really seems to be an intended feature, and isn't really a bug. If you don't agree with me, feel free to contact me
