### ISSUE TITLE
Inability to dispell heat when hot in space suit or space adapt broke a lot of things and is likely never going to be fixed

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#12530]
### Severity

Round Breaking

### Short Description

Someone just shoved this into the game and will never patch it up. We never needed this flaw for almost 9 years(or more) but for some reason we suddenly needed to add training wheels for little girls to the game. 

### Reproduction

1. catch fire in a spacesuit or with space adapt
2. bug the fuck out
3. burn to death from heat that can't ever be dispelled
4. die

### Round ID

xx

### Test Merges

xx

### BYOND Username

Aphielanisn

### Additional information

The rules for burning while wearing a suit or with space adapt are extremely stupid "Are you in a unremovable ninja suit or have space adapt? LOL get fucked, die."

**Comment by UselessTheremin** [comment]
this literally isn't a bug, this is an intended drawback of hardsuits and a major nerf to space adapt with an extra mutation added to compensate for that.
