### ISSUE TITLE
Ghosts can't see who's a Rev

### ISSUE THREAD

**Issue by Cartlord** [yogstation13/Yogstation#12545]
### Severity

Inconvenience

### Short Description

I was dead and a ghost, and despite it clearly being a Rev round, I couldn't see Revs. May be because I'm Revbanned.

### Reproduction

1. Be Ghost
2. Find Rev
3. See no R icon

### Round ID

37831

### Test Merges

#12270 #12226 #12207 #12523 

### Additional information

May well be caused by my Revban, here's a pic
![image](https://user-images.githubusercontent.com/78994376/139002215-820523aa-979d-44d1-9f31-3bcbc154c991.png)
This is some Sec lads in a fight with Revs, but you can't tell who the Revs are

**Comment by Cartlord** [comment]
Closed because I hit enter too early, also current round

**Comment by Cartlord** [comment]
Round over, reopening

**Comment by UselessTheremin** [comment]
iirc ghosts cannot normally see who's a rev or not.

**Comment by adamsong** [comment]
We have no system for ghosts to see any antag’s hud, even ghost visible antags are only visible in the orbit menu, which revs are not

**Comment by Bibby0110** [comment]
Not a bug
