### ISSUE TITLE
didn't receive any information about apc control

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12558]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: Moderate
empty,
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/903586290304442388/unknown.png)
 Submitted by: Debt (407757687334633473)

**Comment by adamsong** [comment]
Duplicate of #12557
