### ISSUE TITLE
Some station templates don't spawn until round starts

### ISSUE THREAD

**Issue by redmoogle** [yogstation13/Yogstation#12561]
### Severity

Development Issue Only

### Short Description

Some templates like the bar do not load but botany will

### Reproduction

1. Observe
2. Look at botany
3. Look at the bar
4. ???

### Round ID

N/A

### Test Merges

N/A

### BYOND Username

Redmooogle

### Additional information

![image](https://user-images.githubusercontent.com/20369082/139494628-f7625411-4621-497c-9556-bd8b2a28f43d.png)
![image](https://user-images.githubusercontent.com/20369082/139494731-d42df06d-d8bf-4622-b064-a8d68969828e.png)

**Comment by Bibby0110** [comment]
intended, can't spawn before bartender
