### ISSUE TITLE
can't put IDs in phones

### ISSUE THREAD

**Issue by SomeguyManperson** [yogstation13/Yogstation#12598]
### Severity

Inconvenience

### Short Description

ids will not fit in phones, preventing access restricted programs from being downloaded

### Reproduction

get phone
try to put ID in phone
can't
try to download programs with access locks
also can't

### Round ID

n

### BYOND Username

theos

**Comment by 00aquir** [comment]
did you get the card reader and the network thingy upgrade with that phone when you bought it?

**Comment by SomeguyManperson** [comment]
card reader is unrequired and didn't help with access restrictions when added anyways

**Comment by Cartlord** [comment]
I don't know WTF is up with you but I was able to put an ID in my phone as an Engineer just fine

**Comment by ToasterBiome** [comment]
@SomeguyManperson Did you have a roundstart one or one from the laptop vendor? Might be fixed with https://github.com/yogstation13/Yogstation/pull/12689

**Comment by SomeguyManperson** [comment]
probably has been fixed since
