### ISSUE TITLE
Roundstart grounding rods aren't machines apparently

### ISSUE THREAD

**Issue by Cartlord** [yogstation13/Yogstation#12609]
### Severity

Inconvenience

### Short Description

I took apart a roundstart grounding rod to upgrade the capacitor, and the thing vanished

### Reproduction

1. Join a round where the station spawned with Singularity/Tesla setup
2. Go to a grounding rod
3. Unwrench
4. Screwdriver
5. Crowbar
6. Have rod disappear

### Round ID

37997

### Additional information

Seen around 20 or 19 minutes into the round
This also means you can't use a BSRPED to upgrade the Capacitors in these grounding rods, that issue's been around much longer than any current testmerge

**Comment by UselessTheremin** [comment]
fucken
