### ISSUE TITLE
the fucking biohazard alarm says "confirmed level 5 biohazard abroad the station" in its warning, not aboard.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12600]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: You cannot unhear it now.
 Submitted by: Drywall Thief (142503340121522177)

**Comment by redmoogle** [comment]
I hate you and this

**Comment by Cartlord** [comment]
I KNEW IT!

**Comment by adamsong** [comment]
I thought this was intentional, especially since the level 7 doesn't

**Comment by UselessTheremin** [comment]
I cannot see how this is an issue and I don't know how it's something that can be fixed, so i'm not sure. contact me on discord if you disagree with this, but as of now I'm closing this
