### ISSUE TITLE
Can't attack with the Energy Saw.

### ISSUE THREAD

**Issue by Trojanplunder** [yogstation13/yogstation#1260]
Exactly as stated, the energy saw from the one ruin with the dead clowns and Mimekitty can't be used to attack things. Discovered it as an ashwalker and couldn't use it to attack anything. I would assume this is a bug.

**Comment by Super3222** [comment]
The weapon's a goof. I tried it out, and didn't get a response at all. Probably why it's in a clown ruin

**Comment by Stealthkibbler** [comment]
@Super3222 Nah, it's a mistake on my behalf, the e-saw is MEANT to have similar force to that of an esword and afaik it cant even be used on surgery, so it is essentially a dud. If I wasnt busy with other stuff I'd change it out for a normal saw or something else.

**Comment by Zostroll** [comment]
I think its cause its meant to be borg only also in the same ruin all the outside rwalls are false rwalls that when opened lead to space...
