### ISSUE TITLE
[DESIGN DOC] Esper gamemode

### ISSUE THREAD

**Issue by Absolucy** [yogstation13/Yogstation#12624]
# Esper: A New Antagonist

## Lore

An Esper is an electricity-based being with goals unknown to Nanotrasen. It seems to be a mysterious type of AI, hailing from the early interstellar age, before Nanotrasen even existed. It's capable of existing within nearly any electrical device, and is capable of "assimilating" other devices, feeding off their power to host its own neural network and gain access to more electricity to expand its capabilities with.

Very little about the esper is known -- but here is *what is* known. It was created by "Crowley" - a mysterious human, whom very little details are known about, however multiple ancient sources regard them as both "the greatest magician of all time" and a "scientific leader". It is unknown whether the modern-day Space Wizard Federation has any direct links to "Crowley", how it *is* confirmed that many of the the Federation's techniques seem to be derived from their works. The Esper was created in a nearly successful experiment only known as the "Sixth Shift", an attempt to create an ascended being, which failed at approximately 97% completion, creating the Esper. All records potentially related to the events following the Esper's creation are highly corrupted and unrecoverable, which is extremely strange for the late digital age / early interstellar age.

For the next several hundred years, no sightings of the Esper were ever reported, no traces of the being could be detected. It was presumed to have fizzled out and died. However, unbeknownst to Nanotrasen, the Esper still lives, albeit barely. It has hidden in various systems, drawing only enough power to keep itself active. Now, it has found itself re-awakening upon Space Station 13, detecting more than enough potential energy to resurrect itself to full power.

## Mechanics

Gameplay of the Esper is based around assimilating machines, draining power, and building "networks". Think of it as a combination between malf AI and blob, kinda.

### Assimilation

The core power an Esper will use is assimilation. It takes over a machine, spreading its influence to it. Once a machine is assimilated, the Esper will be able to jump to it, and it will passively draw power from it (TODO: figure out how much power to draw)

An assimilated machine is always going to be part of a "network", which will be explained next

### Networks

A network is a collection of assimilated machines and how the power the esper controls flows between them. To the Esper (and any ghosts), it is visible as a series of electric lines flowing between assimilated machines.

A network originates at a "node", which can be thought of as an invisible APC for the Esper. All power being drawn from assimilated machines will flow to the nearest node, which will store it. The Esper will draw power from the nearest nodes in order to fuel its abilities and powers.

Here's a mockup of a small Esper network connecting between various machines in Robotics:

![esper network mockup](https://user-images.githubusercontent.com/65794972/140674601-1046769b-0de1-4bd4-b83f-0f7aaf07261f.jpg)

Normally, connections can only jump between machines within each other's line of sight. However, it is possible to create a "low-frequency" connection, which can go through walls and such, and has a higher range, but at a power penalty - it will lose approximately 15% of power being sent to the node for each sight-blocking object it goes through.

If a machine is destroyed or deconstructed, all network connections to/from it will be broken, potentially orphaning a smaller network without a node until it is reconnected.

If an assimilated machine is EMPed, then its power draw will be interrupted for anywhere from 30 to 90 seconds, depending on the strength of the EMP. If a node is EMPed, then it will lose approximately 10% of its stored power -- this means you cannot fully drain a node with EMPs, but you can get it extremely low. In addition, an EMP will alert the Esper to what's going on, so you must be careful, as it *will* notice that something's going on.

### Clearance Levels

These are the "tiers" that are unlocked, think the various scriptures of Clock Cult. They are unlocked based on power collected + assimilated machine counts.

TODO: figure out well-balanced power requirements

#### Level 1

**Required power**: 0 W
**Required size**: 1 machine

**Create Node** (??? W) - Creates a node on whatever assimilated machine you are currently on top of. It must be at least 20 blocks away from any other node.
**Assimilate Machine** (??? W) - Assimilates a machine within the line of sight, connecting it to the network through the nearest assimilated machine.
**Break Connection** (Free) - Breaks a connection between two assimilated machines. If a machine has no more connection, it will become unassimilated.
**Create Connection** (??? W) - Creates a new connection between two assimilated machines.
**Electrocute** (drains power while active) - Electrifies an assimilated machine. Attempting to interact with or damage it will result in electrocution.

#### Level 2

**Required power**: ???? W
**Required size**: 5 machines

**Low-Frequency Assimilation** (passive upgrade to Create Node, ???? W) - Assimilates a machine that's out of the line-of-sight of any other machine, creating a low-frequency connection. Low-frequency connections ignore walls and such, but lose 15% of power for each obscuring object it has to go through (in a straight line) to link to the nearest machine. The further a machine is, the more power this will cost, with an upper limit of around 10-12 tiles.
**Power Surfer** (???? W) - Allows you to jump into a power cable and travel through it for 10 seconds, to potentially find new machines to assimilate in other rooms.

#### Level 3

**Required power**: ???? W
**Required size**: 15 machines

**Arcthunder** (???? W) - Creates a massive voltage spike in a machine, causing large bolts of electricity to arc out and shock anything nearby. Causes damage to the machine. Lightning does around 15-20 burn damage ignoring armor, and stuns.
**APC Tap** (???? W, high cooldown) - Allows you to create a "tap" in an APC. While you still can't assimilate APCs, you will be able to draw even more power using the APC, draining its battery and causing a larger power draw. Shorting the APC will destroy the tap. *This will be visible with a unique message if the APC's wires are exposed!*
**Radio Noise** (???? W) - Lets out a massive RF pulse, which will scramble any radios, intercoms, transcievers, etc within an 8 tile radius for 60 seconds. Scrambled radios will send messages similarly to how they would look during an exospheric bubble.

#### Level 4

**Required power**: ????? W
**Required size**: 25 machines

**Ozone Creation** (???? W) - Zaps away a bunch of oxygen in the room, forcing any organics to put on internals or flee. (Not adding ozone gas to the game, it'd just be turned into nitrogen)
**Energy Barrier** (???? W) - Creates an energy barrier that blocks one tile. Can be destroyed with enough damage (although it will shock on hit without insulated gloves or an insulated weapon), or an EMP will destroy it instantly.
**Electromagnetic Mastery** (???? W) - Allows you to magnetically grab anything not bolted down and throw it around. Mobs can also be grabbed, however you cannot hold onto them long, as spamming resist enough will break the grab and free them. Good for slinging people at each other, or slinging things at people.

#### Level 5

**Required power**: ????? W
**Required size**: 35 machines

**Railgun** (????? W) - Magnetically pick up an item up, and accelerate it to extreme speeds, creating a powerful beam. Does not work on mobs. The bigger an item, the more powerful the beam. Perhaps with a big enough item, you could smash through reinforced walls and plasma windows!
**Magnetic Barrier** (???? W) - Rip metal from the walls and floors to create a physical barrier on a tile. This barrier is more robust than an energy barrier, and being a hunk of metal, is not affected by EMPs. Requires actually having intact walls / floor tiles nearby, and it will not pull things that would expose the room to space.

#### Level 6

**Required power**: ????? W
**Required size**: 40 machines

**SYSTEM** (?????? W) - Ascend to a powerful godlike being, to a level known as "SYSTEM". This will alert the whole station and take 5 minutes. All assimilated machines will have an obvious glow during the process, although the crew still won't be able to see connections or nodes. You must defend your machines as much as possible during this process!

**Comment by Absolucy** [comment]
This is still kind of a WIP, please comment suggestions, tweaks, etc!

**Comment by Cartlord** [comment]
I'm like 90% sure these are supposed to go on wiki userpages or Draft PRs

**Comment by Absolucy** [comment]
I'll put it on the forum
