### ISSUE TITLE
atmos heat can bleed through airlocks

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1262]
When in a area seperated from a burning room by an airlock heat leaks through the airlock
Windows are probably bugged too

**Comment by SnekySnake7** [comment]
I think this is working as intended. I know windows aren't meant to block heat.

**Comment by aphielanis** [comment]
In older(better) atmos code it did not because coders recognized that putting a firelock on every door and window would add to the lag.

**Comment by AdamElTablawy** [comment]
non-existent
