### ISSUE TITLE
Ruins are spawning on top of each other

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation#1265]
and creating monstrosities like this;

![](http://image.prntscr.com/image/2942d5d977f84be1b31b321b3cf302ca.png)

**Comment by Stealthkibbler** [comment]
I have only even seen this happen with the wishgranter cube, once saw it spawn ontop of the animal hospital. I suspect this has somethng to do with the fact that ALL of the wishgranters terrain is /mining explored/ and not area/powered/unpowered. Also its template is fucking massive despite how small the cube is.

http://puu.sh/sri5j/5933f9273d.png

Will most definitely replace it with something else.

**Comment by ShadowDeath6** [comment]
but it so fun to see miners get stuck and die in the cubes ;_;

**Comment by Drakkon** [comment]
Had a REALLY lucky spawn with hermit, wishgranter spawned right next to puddle. and didn't harm the shelter.

**Comment by Stealthkibbler** [comment]
Recently saw it spawn inside an ashwalker nest, it seems lavaland gen cannot differentiate between what is normal miningexplored or ruins miningexplored; most likely due to the fact that ruins use the exact same area type.

**Comment by Dragonforcefive** [comment]
Hilarious. Reminds me of when weird stuff spawns together in Minecraft.
