### ISSUE TITLE
hawaiian shirt not in clothesmate

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12670]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: PR say hawaiian shirt in clothesmate. Hawaiian shirt not in clothesmate. I am sad
 Submitted by: DukeBobRoss (305348676883316737)

**Comment by DukeBobRoss** [comment]
Adding onto this since I've done some testing.

It works on my private server but not on the actual server!??!?!?!?!

**Comment by ToasterBiome** [comment]
![image](https://user-images.githubusercontent.com/5091394/141891618-35ddfeb6-84e6-4348-b964-87aa7fc253d4.png)

Hawaiian shirt shows up in the clothesmate on live server

**Comment by DukeBobRoss** [comment]
> ![image](https://user-images.githubusercontent.com/5091394/141891618-35ddfeb6-84e6-4348-b964-87aa7fc253d4.png)
> 
> Hawaiian shirt shows up in the clothesmate on live server

bro I dunno if I somehow got a weird round twice in a row, am stupid, or something is wrong with my client goddamn

**Comment by ToasterBiome** [comment]
you might have missed it

**Comment by DukeBobRoss** [comment]
> you might have missed it

Idk it wasn't there earlier today but it is now so idk. Guess this ain't a bug anymore

**Comment by UselessTheremin** [comment]
Don't worry, you're not stupid, you're just blind :^)
It's there
:^
