### ISSUE TITLE
ctf is fucked

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12691]
## Test Merges: 
Not Supplied / None
## Reproduction:
desc: the left wall of CTF is cut, meaning that the whole thing is depressurized, also, theoritically, people can use it to get to centcom as ghosts, which can be pretty dangerous
 Submitted by: Marunias (368473582981873664)

**Comment by patpol4** [comment]
great

**Comment by patpol4** [comment]
picture of the issue
![image](https://user-images.githubusercontent.com/48154165/142216608-a1939ad8-7052-40f9-8e61-24daa6452e59.png)

**Comment by patpol4** [comment]
![image](https://user-images.githubusercontent.com/48154165/142216717-e76970bd-a605-4dbf-a6db-02c40a2695e8.png)
the map is there, the area is there, no idea what caused this

**Comment by patpol4** [comment]
It was the #12270 testmerge

**Comment by patpol4** [comment]
fixed
