### ISSUE TITLE
monitoring console highlights clockies

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12693]
## Test Merges: 
Not Supplied / None
## Reproduction:
desc: I spotted an assistant in bold font, top of the list on monitoring console (just like a head of staff would appear), turns out they were a clock cultist. Maybe it highlights other non crew antags ? 
roundID: 38169
 Submitted by: HibiGros (319499903954976769)

**Comment by nmajask** [comment]
if this is because of alt titles again I'm going to scream

**Comment by nmajask** [comment]
*scream
