### ISSUE TITLE
Lava cooking is broken. Possibly lava itself.

### ISSUE THREAD

**Issue by SnekySnake7** [yogstation13/yogstation#1269]
Lava cooking meat in lavaland has been broken for a few months now. They seem to cook when lit on fire,but lava doesn't cause them to burn.

I don't know if this is a bug with the meat or lava itself,as may objects survive lava just fine. Circuit boards,kinetic accelerators,etc.

**Comment by Time-Green** [comment]
It's a weird thing, if you want it to work, you need to pull it onto the lava

**Comment by AdamElTablawy** [comment]
This is fixed
