### ISSUE TITLE
Can we just rename "Metal" (sheets) "Iron" or "Steel"?

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#1270]
So I requested this a long time ago on forums, but pretty much got insta-shunned. Am I the only one bothered?

-We have plenty other metals, why have a "metal"?
-We already have "iron" coins, doors, the chemical, and foam (all which are a product of "metal" sheets, mind you).
-"Iron" ore (Yeah, I was told that there are many more products of refined iron ore than just iron, so we might as well just keep it as "metal" since it covers them all, so renaming most of the above things and most  of the "meta" things "steel", not "iron", probably makes most sense)
-(This is probably all just a PTSD reaction from Minecraft's crafting recipe: ("Flint" & "Iron" = "Flint & Steel")

PLEASE, INFORM ME OF MY STUPIDITY. TELL ME HOW THIS IS A WASTE OF TIME. TELL ME HOW USELESS IT IS TO GO BACK AND RENAME SHIT. MY SELF-ESTEEM HAS BEEN DANGEROUSLY HIGH (*not as suicidal-low as it usually is) LATELY, MURDER ME WITH YOUR MEANIE WORDS.

**Comment by Stealthkibbler** [comment]
Its more along the lines of dont fix it if it aint broken, it would also require repathing/renaming a lot of stuff which can otherwise be avoided by just not renaming or repathing anything and leaving it as is.

**Comment by Dragonforcefive** [comment]
Well, let's be honest. Everyone can go and start doing copious amounts of work based off of technicalities. Or you can just accept 2D spessmen for right now. Currently I'd be all for technicalities if the coding team weren't working on anything. But they are, and I'd rather have cool ass maps and ruins than renaming something I barely deal with. On the other hand, you do make a point about the name, and while everything could be renamed, it's just a waste of time and energy.

**Comment by Oakboscage** [comment]
Unless you're planning to add dwarf fortress level autistic mining and smelting mechanics I think it can stay as metal since it's what it has been for ages and there is no reason to change it really since the mechanics themselves aren't realistic anyway.

**Comment by Cruix** [comment]
Changing the path would be a huge amount of work, but renaming it would be trivially easy.

**Comment by Stealthkibbler** [comment]
spess metal is universally used for everything - there's your realism lore
