### ISSUE TITLE
table in control room of infiltratr ship cannot be interacted with

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12725]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: Theres a table cornered by 2 consoles with donuts on it, thus making the table unusable
Severity: Inconvenience
 Submitted by: Roxy (143464728180555776)

**Comment by Absolucy** [comment]
fixed

**Comment by adamsong** [comment]
Fixed by commit [3613ede](https://github.com/yogstation13/Yogstation/pull/12270/commits/3613ede07c574d61e80fa37c9a62be394b4ed24e)
