### ISSUE TITLE
Preternis cannot be defibbed for some reason sometimes.

### ISSUE THREAD

**Issue by KittyNoodle** [yogstation13/Yogstation#12736]
### Severity

Round Breaking

### Short Description

Sometimes when you attempt to defib a preternis it will state that they are husked and fail to defib them, dispite them not being husked.

### Reproduction

1.Die as a preternis
2.????
3.Cannot be defibbed.

### Round ID

38265

### Test Merges

#12270

### BYOND Username

Noodlecat

**Comment by ToasterBiome** [comment]
Not a bug, got his organs ate by a marrow weaver, please close
