### ISSUE TITLE
these two buttons don't work.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12743]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: read title 
Servity: Inconvenience
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/913073147866140702/unknown.png)
 Submitted by: Debt (407757687334633473)

**Comment by nmajask** [comment]
Turns out if you have card modification access you don't have access to any regions. I should have a fix PRed soon.
