### ISSUE TITLE
space bartender can't access his own cleanbot

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12745]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: As the title says, Space Bartender's ID can't access the Cleanbot in the space bar.
Severity: Inconvenience
 Submitted by: Aquizit (910609167952257076)

**Comment by Aquizit** [comment]
Fixed this myself in PR #12739 

Just didn't know what the space bartender access was.

**Comment by bruhlookatthisdood** [comment]
Shouldn't this be closed then?

**Comment by Aquizit** [comment]
Yes but I cannot seem to do that myself.

**Comment by patpol4** [comment]
#16839
