### ISSUE TITLE
Using wire on glass causes weird shit to happen

### ISSUE THREAD

**Issue by KittyNoodle** [yogstation13/Yogstation#12760]
### Severity

Inconvenience

### Short Description

Used a wire on glass, got a empty warning in chat that had zero content.

### Reproduction

1. use wire on glass.
2. look at chat
3. be confused

### Round ID

38315

### Test Merges

#12270

### BYOND Username

Noodlecat

**Comment by UselessTheremin** [comment]
Completely unable to reproduce, this does not appear to be an ongoing issue
