### ISSUE TITLE
hulk mutation wont combine on console

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12798]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Combining to make mulk mutation on the genetics console combines but makes a 0 instability fake hulk that does nothing
 Submitted by: biome? (99679712363675648)

**Comment by Cartlord** [comment]
This actually happens every time you get Hulk from any source, it isn't just from combining. Source: Several rounds as Geneticist.
