### ISSUE TITLE
Floor cluwnes are above the floor

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#12806]
### Severity

Inconvenience

### Short Description

Floor cluwnes are visible even when not attacking. I don't know if this is from the moment they spawn or if it happens after they've sat for a while, but it means most of them don't get to emerge or even begin haunting someone before dying

### Reproduction

1. Floor Cluwne has been randomly triggered (Follow)
2. Urist McGreyshirt says, "Uh what is that"
3. Experienced Warden fires the compact combat shotgun! (x3)
4. ??? is hit by a buckshot pellet! (x18)
5. Urist McGreyshirt says, "Cool mask"
6. Urist McGreyshirt's body glows green, the glow dissipating only to leave behind a cluwne formerly known as Urist McGreyshirt!

### Round ID

Any

**Comment by KittyNoodle** [comment]
Can confirm that this is happening

**Comment by UselessTheremin** [comment]
you sure you were not a ghost while this happened, correct?

**Comment by Sniblet** [comment]
i was a ghost, but people were hitting it before it attacked
