### ISSUE TITLE
Nicotine Addiction Becomes Meth Addiction upon cloning

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#12828]
### Severity

Inconvenience

### Short Description

As a traitor with nicotine addiction trait, die and be cloned. Nicotine addiction becomes irremovable meth addiction upon completion of cloning. 

### Reproduction

Be traitor with nicotine addiction quirk
Die
Be cloned
Get meth addiction instead of nicotine

### Round ID

38477

### Test Merges

#12782

### BYOND Username

TheBombMaker

**Comment by Notamaniac** [comment]
Okay got it. The junkie trait rolls a random chem to get addicted to, and the smoker trait inherits from the junkie trait. Rather than use the nicotine as the value, it uses that random chem instead as your new addiction when you die and get cloned.
