### ISSUE TITLE
Mining: Lottery Machine

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation#1284]
So while filling out the PR message for Barometers I got a crazy idea.

We install a lottery machine either somewhere near the mining dock or on the actual mining station.

This lottery machine will accept lottery tickets, which can be purchased for 100 points from the mining vendor, but without any lottery tickets it'll remain deactivated.

The lottery ticket however needs to be SYNCED to an ID; so the miner will have to slap their ID with the lottery ticket, and put it in.

On each lottery ticket there'll be different symbols on it. It can range from 2 and 1 of these, have only 1 of each symbol, or have 3 of the same symbol.

The symbols would be: Goliath, Miner, and an Ashwalker.

Once a lottery ticket is inside, it will consistently (spam) inform the mining crew that the bets are on, and it's accepting more tickets over the next 3-7 minutes.

After it's done accepting tickets, it will spin for 3 of those symbols, and announce the winning ticket.
For example, [1] Ashwalker [2] Miner [3] Miner.

Whoever gets the exact order earns 500 points, 3 of the same random item from the vendor, and a voucher. This is known as a diamond win.

Whoever got one in the right spot, via an ashwalker in [1], but a goliath in [2] and [3] can gets 100 points, and that's it. This is known as an iron win.

If there's an instance where the winning ticket is [1] Ashwalker, [2] Miner, [3] Goliath, and your ticket is [1] Miner, [2] Miner, [3] Golaith, than you'll be entitled to 300 points. You got at least 2 symbols in the right place. This is known as a golden win.

So once the winning ticket is announced, the lottery ticket will stay active for possibly 10 minutes or so, constantly blinking and saying (not on radio chat) "WINNER! COME CHECK ME!".

For the winner to get his prize he needs to run to the lottery machine, and put his ID in it, and click the "Cash Out" button.

If they didn't win, then they don't get anything.

The lottery machine than deactivates for the next 15~ minutes, and when that timer is over it'll announce that it's alive again into the mining channel.

**Comment by ShadowDeath6** [comment]
Greed slot machine >

**Comment by Super3222** [comment]
> Greed slot machine >

That's pretty irrelevant.

**Comment by ShadowDeath6** [comment]
Something relevant is saying that this will just distract miners from doing their jobs and makes them still not do their jobs since they can just get free vendor items and do nothing after they get a hyper kinaccel. Trust me, miners already have things to do. I'd rather consider this something for cargo, since they use actual money.

**Comment by Super3222** [comment]
What if I told you this WON'T distract miners from their jobs? There's only a certain chance that you'll actually get the right ticket, and you have to wait about 15 minutes before another session starts again. At best this is encouraging miners to do their jobs, bring ores home, get points, and collect lottery tickets.

This is also the basis of planning. Nothing is strictly implemented so we have lots of room to move things around. We could give miners less of a reward when they get an accurate ticket. Maybe the amount of points that they get out of the raffle should compensate for a reward - so they won't get 3 of the same random item. Instead they get 1000~ points, and a voucher? I feel like that seems fair.

And taking a look at the prices (from the mining vendor), I think a golden win should be at least 500-600 points. Which in turn should raise an iron win to 300 points so they so a depressed miner buys more than just 50 bottles of liquor after wasting all of their points on lottery tickets to get the worst win possible.

This wouldn't fit cargo... I mean cargo points are fun and all, but this is situated for fun on lavaland.

**Comment by ShadowDeath6** [comment]
>this is situated for lavaland

how? cargo benefits from more points infinitely more than mining ever will

**Comment by Super3222** [comment]
> how? cargo benefits from more points infinitely more than mining ever will

You can't be honestly telling me that cargo needs another way to make points.
This is a feature for miners to take a break for a second, enter a raffle, and try to win diamond. Not another way for cargo to get another infinite amount of points.

**Comment by Jc1469** [comment]
don't forget the emag things.  emagging is fun.
having an ash drake spawned on you is fun, and is required, as ashwalkers need ash to walk on.
being able to buy miners is fun
having a goliath spawned on you is fun
