### ISSUE TITLE
Dynamic seems to ignore heads not being able to become traitors

### ISSUE THREAD

**Issue by KittyNoodle** [yogstation13/Yogstation#12864]
### Severity

Round Breaking

### Short Description

A HOP rolled traitor 

### Reproduction

1. Be head
2. Somehow test rolling traitor
3. Roll traitor on dynamic despite us having head antags off.

### Round ID

Round 38542

### Test Merges

None

### BYOND Username

Noodlecat

**Comment by ToasterBiome** [comment]
Fixed as of https://github.com/yogstation13/Yogstation/pull/13150
