### ISSUE TITLE
Wizard's Wild Shapeshift and the AI

### ISSUE THREAD

**Issue by chocolatemilk13** [yogstation13/yogstation#1286]
Problem Description: The wizard carded the AI and tried to escape using the wild shapeshift spell. Everything proceeded normally until the wizard came out of their shapeshifted form. The AI was immediately killed and the user ghosted. The ghost message you receive when someone is killed does NOT pop up. Example: AI has died at AI Upload Chamber will not show up on the screen.

What did you expect to happen: I expected once the Wizard to come out of their form for the AI to still be alive and intact.

What happened instead: Once the wizard returned from being a mouse the AI was deleted.

Why is this bad/What are the consequences: It kicks a player out of the round against another user's wishes.

Steps to reproduce the problem: 
1. Card the AI.
2. Cast Wild Shapeshift as a wizard.
3. Revert from Wild Shapeshift.
4. The AI will be immediately killed.

**Comment by AdamElTablawy** [comment]
This bug was fixed a while back, was due to wild shapeshift not storing items properly
