### ISSUE TITLE
free miners/whiteship can land on the infection core during infection round

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12860]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: Round Breaking (on infection rounds)
Description: Take the whiteship, find core area, land on core, round ends.
Steps to Reproduce: Look at description.
Byond Ckey: liljackrabbit25
Round: 38538
 Submitted by: The Lusty E (302595577793740801)

**Comment by bruhlookatthisdood** [comment]
idk why it submitted like that

**Comment by Absolucy** [comment]
based

**Comment by Absolucy** [comment]
![Free Miners vs Infection](https://user-images.githubusercontent.com/65794972/145493084-a7006084-34b5-4396-a4b9-5514fd2fec4f.gif)

**Comment by UselessTheremin** [comment]
hm

**Comment by bruhlookatthisdood** [comment]
rip infection gamemode
