### ISSUE TITLE
darkspawn "protect from dimliight" does not protect from welders

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12872]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: see title
 Submitted by: DukeBobRoss (305348676883316737)

**Comment by redmoogle** [comment]
"Dim Light", "Welders" antonyms

**Comment by UselessTheremin** [comment]
yeah not a bug welders ain't dim my friend
