### ISSUE TITLE
teal and green suitskirts do not have sprites on lizards

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12876]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: Inconvenience
Description: They do not have sprites when worn on lizards.
Steps to reproduce: Wear it
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/919368341515300885/unknown.png)
 Submitted by: Roxy (143464728180555776)

**Comment by nmajask** [comment]
*scream

**Comment by SomeguyManperson** [comment]
I suit

**Comment by UselessTheremin** [comment]
will fix this in a bit

**Comment by nmajask** [comment]
> will fix this in a bit

I already have a fix for it, just need to actually make the PR
