### ISSUE TITLE
you can have multiple positive quirks without a single negative one

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12886]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: I saw a dude have following quirks, i guess you can manually change your preference file or something to achieve this?
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/919882760229896222/unknown.png)
 Submitted by: Marunias (368473582981873664)

**Comment by Cartlord** [comment]
They mention the guy was named "Tartu Htoon", in the edited report in Discord
Also, for the record, Light Drinker is a negative - but it doesn't give NEARLY enough points for that setup
