### ISSUE TITLE
Microwave Becomes an inconveninece

### ISSUE THREAD

**Issue by galaxyxd94** [yogstation13/Yogstation#12889]
### Severity

Inconvenience

### Short Description

Microwave breaks and becomes less than useless

### Reproduction

1. Joined as Cook
2. Microwaved something
3.  Microwave went *splat* and became dirty.
4. Food can be taken out, was not cooked.
5. Microwave is dirty no matter how you interact with it. Cannot clean, cannot disassemble, cannot break, cannot use at all. 

### Round ID

38598

### Additional information

I tried everything to fix it as a player and all intents, it did not make a difference

**Comment by 00aquir** [comment]
you can craft food, also check the wiki: "Use the microwave to cook raw meats and raw eggs (also you can microwave other things, check the "guide to food" on the wiki). Trying to microwave other food will make it dirty and unusable until it gets a spray of space cleaner (call the janitor to clean it). And if a microwave gets broken, you need to use a tool box set to repair it."

**Comment by UselessTheremin** [comment]
yeah this ain't a bug, you need to use space cleaner to clean it.
