### ISSUE TITLE
Floors dry too fast.

### ISSUE THREAD

**Issue by Oakboscage** [yogstation13/yogstation#1289]
According to Adam there was a change regarding regents which led to wet floors drying almost instantly, ruining the little fun playing janitor had.

Please change it back so that floors stay wet for a reasonable amount of time. Thanks.

**Comment by Cruix** [comment]
It has been this way since we rebased to tg.

**Comment by Oakboscage** [comment]
Well can we get it reverted to how it was before the awesome decision to rebase to tg was made?

**Comment by X-TheDark** [comment]
It depends on how much chems was dumped on the tile, so 5u of stuff isn't going to keep the tile wet for ages anymore.

For water, the time is `5 + dumped_amount*0.2`
For space lube, it's `5 + dumped_amount`

**Comment by Super3222** [comment]
It should honestly be changed back / buffed.

**Comment by AdamElTablawy** [comment]
stale. If you want to fix it, fix it @Super3222
