### ISSUE TITLE
Slimepeople cannot swich bodies while stunned/laying down/ or sleeping

### ISSUE THREAD

**Issue by KittyNoodle** [yogstation13/Yogstation#12927]
### Severity

Round Breaking

### Short Description

i was a slimeperson ling, got sleep stunned by an abductor and was unable to switch, the same thing happens if you lay down or are stunned.

### Reproduction

1.be a slimeperson
2.have other bodies
3.sleep/lay down/ be stunned
4. be unable to swich bodies
5. round ruined

### Round ID

38674

### Test Merges

#12922, #12608, #12900, #12919

### BYOND Username

Noodlecat

**Comment by neeshacark** [comment]
i think this is intended.

**Comment by The-Sun-In-Splendour** [comment]
Intended feature

**Comment by Bibby0110** [comment]
Intended.
