### ISSUE TITLE
Recharger Sprite Disappearing

### ISSUE THREAD

**Issue by PotatoTomahto** [yogstation13/Yogstation#12929]
### Severity

Inconvenience

### Short Description

When I close the maintenance hatch of the recharger, the sprite disappears.

### Reproduction

1. Use screwdriver on recharger to open hatch.
2. Use screwdriver on recharger to close hatch.
3. Sprite has now vanished. It is still ingame however and can be interacted with normally.

### Round ID

38675

### Test Merges

#12608 #12900 #12919 #12922

### BYOND Username

PotatoPotahto

### Additional information

I was unable to test whether the bug is merely client-side or whether others also see the recharger disappearing. Also, the sprite reappears when you use a screwdriver to open the hatch again.

**Comment by 00aquir** [comment]
Connected to https://github.com/yogstation13/Yogstation/issues/12727
