### ISSUE TITLE
wizard gemsuit spell scam

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12925]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Robe spells cant be cast with gemsuit. The name is yelled and you hear the sound but there's no effect. Tried with regular wizard robes and it works fine. Tried without anything on and "cant do this without robe and hat"
 Submitted by: Gaminada (149238977608548353)

**Comment by Xoxeyos** [comment]
Which spell?

**Comment by Bibby0110** [comment]
They're antimagic. Probably not intended to not be able to cast spells

**Comment by Notamaniac** [comment]
Every single spell seems to work apart from mutate. I'm going to guess mutate isn't working due to something wonky like being in a hardsuit preventing the hulk transformation.

Were there any other spells that you couldn't castin a gem hardsuit?

**Comment by Notamaniac** [comment]
Okay, now I get it. I have no idea whether this is actually intended but yeah the hardsuit itself has antimagic, and mutate checks for antimagic on the target itself. 

So yes, you can cast magic, but you can't cast magic on yourself.
