### ISSUE TITLE
Spawner Posi Brains

### ISSUE THREAD

**Issue by j8uj8u** [yogstation13/Yogstation#12923]
### Severity

Inconvenience

### Short Description

Ghost spawner menu still has Posi Brains even after they have been used

### Reproduction

1. Be ghost
2. Click the spawners menu
3. Click jump to Posi brain
4. Just jumps me to a borg and no Posi Brains are in Robotics

### Round ID

#38664

### Test Merges

#12608 #12900 #12919 #12922

### BYOND Username

j8uj8u

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/12968
