### ISSUE TITLE
new ai system expansion bus bug/issue

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12934]
## Test Merges: 
Not Supplied / None
## Reproduction:
Made expansion BUS in room temperature, put in the cards. The BUS were offline, obviously, I then lowered the temps in the room. They switched to Online, were visible on the list, but were NOT contributing to the AI memory or processing power.
We then rebuilt the BUS but in cryo temps, put the cards when they were online and the it worked.
 Submitted by: Iocanthos (265578975064096770)

**Comment by Bibby0110** [comment]
Resolved already
