### ISSUE TITLE
changeling last resort bug

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12946]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: As a changeling when using "last resort" instead of exploding into a headslug it generates an explosion located around your body without gibbing you (and you can kinda spam it to kill people around you)
 Submitted by: Cowbot (97736956326207488)

**Comment by neeshacark** [comment]
it does also seem to debrain you and send your brain to that weird bug room with all the strange crystals.

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/13830
