### ISSUE TITLE
researching ai security scanner view thingy gives adv. med scanner as well

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12957]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: when you research and equip the sec hud for AI it gives some people med hud and others not.
 Submitted by: Cowbot (97736956326207488)

**Comment by Bibby0110** [comment]
Advanced med hud shows health if they don't have suit sensors
If they have suit sensors on max you'll see their health even without the upgrade
