### ISSUE TITLE
Roundstart metal rods don't mix with new ones

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#12951]
### Severity

Inconvenience

### Short Description

Roundstart metal rods don't mix with new ones.

### Reproduction

- find metal rods on a table (they can be in certain rooms and maintenance tunnels)
- when you make more metal rods, they do not mix with some of the rods already existing, you will end up with two piles. (e.g. 10 metal rods don't accept 2 metal rods)
- happened in several shifts

### BYOND Username

Aquir

**Comment by Notamaniac** [comment]
Rods that are mapped in have the path obj/stack/rods/twentyfive ect. so istype might be returning false when you hit it with the parent object.
