### ISSUE TITLE
crew can still not win a major victory

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12979]
## Test Merges: 
Not Supplied / None
## Reproduction:
Crew is supposed to win a "major" victory if they kill all nukeops and don't leave the station, this is broken and will give them a "minor" victory if they ever do win
 Submitted by: Cowbot (97736956326207488)

**Comment by Bibby0110** [comment]
Only way to win a major victory is to kill the ops *and* leave the station.
Not a bug, file a feature request if you believe that crew should be able to win a major without fleeing.
