### ISSUE TITLE
kilo station surgery apc mapping issue

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13011]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: Inconvenience
Brief Description: Kilo Station surgery does not have a wire node under the terminal for the apc.
Steps to Reproduce: at round start crow bar the tile in front of the kilo station surgery apc and the wire node is missing.
Byond Ckey: Zomgbees
 Submitted by: Zomgbees (190732034375811072)

**Comment by bruhlookatthisdood** [comment]
![image](https://user-images.githubusercontent.com/89947174/147776310-933fdb09-9f24-4205-8572-89d95a4fc4d4.png)
im pretty sure it does

**Comment by patpol4** [comment]
fixed in #13020
