### ISSUE TITLE
mystery fizz doesn't seem to be appearing in hacked vending machines

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#13045]
### Severity

Low

### Short Description

Upon hacking a soda vendor and looking for mystery fizz, i was unable to find it

### Reproduction

1. hack a vendor
2. find no fizz
3. fail to get the potential mutation toxins

### Round ID

N/A

### BYOND Username

Cark

**Comment by Marmio64** [comment]
tested it myself, doesn't work. this is really weird.

**Comment by Marmio64** [comment]
works when i do it in a private server but not on the main one...

**Comment by neeshacark** [comment]
> works when i do it in a private server but not on the main one...

must be a test merge then?

**Comment by Notamaniac** [comment]
the main server hasn't been updated yet

**Comment by neeshacark** [comment]
> the main server hasn't been updated yet

Am I stupid? I don't think that's how it works, my understanding is that when a pr is merged it's added next round

Updating the server isn't a thing... Right?

**Comment by Notamaniac** [comment]
> > the main server hasn't been updated yet
> 
> Am I stupid? I don't think that's how it works, my understanding is that when a pr is merged it's added next round
> 
> Updating the server isn't a thing... Right?

Yes it is. You can check the changelog on the server to see that the server is still working on the 03/01/22 build.

**Comment by Marmio64** [comment]
i had assumed the server updates every day
then this should be closed, just need to wait.
