### ISSUE TITLE
can't re-enter body when put in a mmi

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13055]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: If someone sever your head and butcher it, and putting the brain in the mmi you wont be able to re-enter the body and the mmi will be unresponsive 
Servity: Inconnvenience
 Submitted by: Debt (407757687334633473)

**Comment by neeshacark** [comment]
I think this is because server/butcher causes sufficient quantities of brain damage to make the brain inoperable for an mmi, unless you still are unable to re-enter the brain once it's damage is fixed, I think this is a intended feature or at least a non-issue

**Comment by UselessTheremin** [comment]
yup the butcher makes the brain inoperable this isn't a bug
