### ISSUE TITLE
Phone program ID slot

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#13072]
### Severity

Inconvenience

### Short Description

ID modification program on the phone requiring "ID slot".

### Reproduction

- was Captain
- on the YogsMeta station, phone bought from cargo with secondary card reader
-  ID modification program says: "This program requires an ID slot in order to function". 

I was a bit confused because other heads who have a phone did not have this problem, and I even bought the phone with a secondary card reader. Or it needs another component from the other vendor.. 

### Round ID

39021

### BYOND Username

Aquir

**Comment by Notamaniac** [comment]
Okay the crux of the issue seems to be that phones vended don't seem to come out with the secondary card reader module, even if you selected it. There's runtimes about a null fabricate and resale price, so it might be a typo on a path or something.
