### ISSUE TITLE
usint dest. tagger to set something to virology will loop it back to the delivery office

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13091]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: If you take something and give it the destination tag as virology, then throw it in delivery office it will loop back around to the delivery office.
Steps to Reproduce: Take something and tag it's destination as virology, throw it in the belt, watch it come back.
 Submitted by: The Lusty E (302595577793740801)

**Comment by maxion12345** [comment]
Fixed

**Comment by patpol4** [comment]
> 

please link pr

**Comment by patpol4** [comment]
@maxion12345

**Comment by patpol4** [comment]
appears to be fixed if this is about box
