### ISSUE TITLE
Lavaland creatures actually eat their food

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#1310]
Make meaty bodies (human and non-megafauna) a secondary target to marrow weavers, goliaths and ash drakes and meat slabs tertiary to marrow weavers and goliaths. Target's wearables would either be consumed and spill out when the predator is gibbed or be dropped onto where it was eaten.

At least if it's easy enough to code ai "eating".

Makes Lavaland a little more hellish (which is always nice), adds a luring mechanic, and makes sense (unless demonic monstrosities are vegan). Would this break things? If not, what about adding this for some other hostiles?

**Comment by Super3222** [comment]
Well than... that's a nice way to ruin someones round even more.

**Comment by Drakkon** [comment]
@Super3222 Is that a +1 or -1? Either way: "All part of the Lavaland experience~! (A.K.A. literally hell)"

**Comment by ShadowDeath6** [comment]
ash drake already does this, we don't need regular lavaland fauna gibbing corpses, I doubt anybody retrieves them anyway

**Comment by doerakpoes** [comment]
NOMNOMNOM for all monsters NO RACIST FOOD VOTE NOW!
