### ISSUE TITLE
Ethereal Darkspawn cannot manually divulge

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#13123]
### Severity

Round Breaking

### Short Description

You are only able to divulge in darkness!

### Reproduction

>Be Coma SM, ethereal darkspawn
>Go to maint
>Try to divulge
>You're too bright
>Wait 20 minutes for force divulge while your friends probably get massacred with welding tools

### Round ID

39160

**Comment by Sniblet** [comment]
This remains an issue

**Comment by NCRLouTenant** [comment]
Oh jeez, finding this out in round would be rough. Guess the current workaround would be a full suit like a bio suit or something, yeah?
