### ISSUE TITLE
metastation janitor's closet isn't connected to distro

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13128]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc:
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/933479193495355442/unknown.png)
 Submitted by: dukebobross (305348676883316737)

**Comment by Xoxeyos** [comment]
https://github.com/yogstation13/Yogstation/pull/13130

**Comment by Xoxeyos** [comment]
This issue has been resolved.
