### ISSUE TITLE
Plasmaman Dying roundstart

### ISSUE THREAD

**Issue by HarlandDavidSanders** [yogstation13/Yogstation#13137]
### Severity

Inconvenience

### Short Description

While spawning into a round, spawn in the lobby image thing, then die due to lack of internals/suit

### Reproduction

1. Press ready before the roundstart as plasmaman
2. Die

### Round ID

Round #39189 and the two rounds previous to it

### Test Merges

#12740 #13033 #12948

### BYOND Username

CoIoneISanders

### Additional information

Just a thought, I had my preferences set as if no roles available, go assistant, with no roles selected.

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/issues/11517
