### ISSUE TITLE
Revenant can break things while in invisible mode

### ISSUE THREAD

**Issue by Nostr0** [yogstation13/Yogstation#13149]
### Severity

Inconvenience

### Short Description

Revenant can break things while in invisible/god mode and being shot by emitters

### Reproduction

1. Be Revenant
2. Go to supermatter engine
3. Stand in the glass while emitters fire at you while being invisible
4. Glass breaks

Not sure if this works with other things aswell.
Image shows where to be (red circle) as Revenant to make this happen.
![Picture](https://user-images.githubusercontent.com/10816516/150572100-0d5374c5-d022-44e7-8a22-5f020fb1736d.png)

### Round ID

39197

### BYOND Username

Nostr0

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/issues/18767 closing in favor of newer one
