### ISSUE TITLE
sleeping carp doesn’t deflect shots when throw mode is activated.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13154]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: -have sleeping carp
-activate throw mode
-projectiles don’t get deflected
-redtext
 Submitted by: maninblack (247164643389210624)

**Comment by Yeetalorian** [comment]
#39218 round ID

**Comment by Oblisk234** [comment]
Per #22373 sleeping carp throw mode doesn't do this anymore.
