### ISSUE TITLE
space ninja: mining combat injectors don't inject.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13167]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Injector pens work on space ninjas, however the combat injectors on mining don't work without taking the suit off and exposing flesh.
 Submitted by: Rg4 (185114950354731008)

**Comment by Xoxeyos** [comment]
I was able to reproduce this issue. https://www.youtube.com/watch?v=Rf3lLFd0Rg0

**Comment by SomeguyManperson** [comment]
oh right for some reason hyposprays check thick clothing, unsure if this is intended orn ot

**Comment by Oblisk234** [comment]
Likely fixed by #15492, either way mining hypospray working.
