### ISSUE TITLE
space ninja blue space battery upgrade

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13166]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Blue Space Powercells don't work on space ninja suits. You cannot use them in anyway other than draining the powercell with the special interaction. All other cells are fine.
 Submitted by: Rg4 (185114950354731008)

**Comment by Xoxeyos** [comment]
I was not able to reproduce this issue. https://www.youtube.com/watch?v=COZ9z3zr_Vs

**Comment by SomeguyManperson** [comment]
maybe got confused with the ninja powercell using the same sprite as the bluespace cell
