### ISSUE TITLE
TGUI Crashes - Voting Panel

### ISSUE THREAD

**Issue by Xoxeyos** [yogstation13/Yogstation#13162]
### Severity

Inconvenience

### Short Description

I cannot access certain TGUI panels, the TGUI gives me a fatal error at "002B:C562F1B7"

### Reproduction

1. Click on vote panel within OOC tab.
2. Get an expansive NTOS error.
3. Fail to bring up a map vote.
4. There are other certain TGUI panels I cannot access, as I get a similar (or same err) crash.

The crash log will be listed in additional information.

### Round ID

39260

### Test Merges

#12740, #13033, #12948

### BYOND Username

Xoxeyos

### Additional information

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/yogstation13/Yogstation. Thank you for your cooperation. 
 Script error.
   at https://cdn.yogstation.net/assetcache/asset.3ce4e0e45212611796cd4c83ed1dc567.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"xoxeyos","interface":"Vote","window":{"key":"[0x21000048]-main","size":null,"fancy":1,"locked":1}}

**Comment by ToasterBiome** [comment]
Can you name some other tgui windows that crash for you?
