### ISSUE TITLE
nightmare's light eat not affecting secborgs.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13180]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Nightmare's lighteater doesn't affect secborgs for some reason. Other borgs lose their headlamps. Secborgs don't.,
 Submitted by: Rg4 (185114950354731008)

**Comment by Oblisk234** [comment]
Secborgs are disabled per #19531 (and are unlikely to come back), reopen if they are reenabled.
