### ISSUE TITLE
Genetics.

### ISSUE THREAD

**Issue by penguinfisher** [yogstation13/yogstation#1319]
Genetics has gotten way out of control these past few days. Every time I get on there's at least one person with every single super power. I wouldn't have a problem if all these powers weren't overpowered and super easy to get.

All you have to do is splash mutagen on something and record what genes change. The genetics console seems like it's just used to harvest genetic changes instead of actually using it to change and record changes. 

It wouldn't be as big of an issue if it didn't take 2 minutes into the round to find every power and distribute it to security. This seems like a pretty big powergaming issue since after the geneticists find the powers they roam the station and act as security.

A proposed change to this could be to have only 2 powers randomly spawn at roundstart but all the disabilities are there. It's incredibly difficult to shoot down a mini-hulk with TK, Xray and cold res.

**Comment by ShadowDeath6** [comment]
Good issue tbh

A better idea is to gib anyone who purposely gives themselves the manlet gene

**Comment by puremanbird** [comment]
Genetics could use a rework, but im sure this has been said many times over the past few years.

**Comment by AdamElTablawy** [comment]
genetics may yet get a rework pending me finally using gitext and stealing paragenetics

that being said i am tempted to replace our current powers of hulk, etc, with some other, more varied powers along the lines of goon's powers-human SMES cells, healing hands, telepathy, etc

**Comment by X-TheDark** [comment]
What kind of rework/powers would be necessary to make Genetics not OP but still worth bothering with?

**Comment by ShadowDeath6** [comment]
A good rework would remove dumb shit like tk and hulk in favor of cool stuff like polymorph and unable to be examined or whatever that's called

on second thought don't remove hulk because horrorform uses it and I would need to do work if if was removed
