### ISSUE TITLE
Space Bartender can't open kitchen cabinet

### ISSUE THREAD

**Issue by sehloiro** [yogstation13/yogstation#132]
You can't open the Kitchen Cabinet from the Space Bar Storage
http://prntscr.com/blhgmc

**Comment by X-TheDark** [comment]
Ok, I'll take a look at this.

**Comment by X-TheDark** [comment]
Seems like this isn't a bug. The locker is the same kind one finds in the **kitchen** so it requires kitchen access (the one Cook ID has).

**Comment by GrayRachnid** [comment]
Just give the lavaland bartender kitchen access.

**Comment by X-TheDark** [comment]
Ok, this is weird, testing this now and it seems that you can properly open the freezers...cannot reproduce locally on the latest 'master' build.

**Comment by Stealthkibbler** [comment]
It's because the space bartender uses a normal bartender ID, just have him spawn with a custom ID that comes with kitchen access.
