### ISSUE TITLE
Light Eaters created via eating a heart of darkness disappear after species change

### ISSUE THREAD

**Issue by KittyNoodle** [yogstation13/Yogstation#13201]
### Severity

Low

### Short Description

Lost Heart of darkness after species change

### Reproduction

1.Eat Heart of darkness.
2.Change Species via mutation toxin.
3.Heart and blade are vanished into shadow realm

### Round ID

39351

### Test Merges

#13033, #12948, #12912, #13185, #12959

### BYOND Username

Noodlecat

**Comment by ChesterTheCheesy** [comment]
probably because the heart itself disappears after a species change and turns into that species's one, pretty sure that's an intended feature

**Comment by Oblisk234** [comment]
Intended feature, not an issue.
