### ISSUE TITLE
Robotact Failure

### ISSUE THREAD

**Issue by SegaCD** [yogstation13/Yogstation#13216]
### Severity

Inconvenience

### Short Description

Robotact hardware error

### Reproduction

1. Join round as Robot
2. Select Modular Interface
3. Select Robotact
4. The following will show up "The modular interface flashes an "Hardware Error - Incompatible software" warning."

### Round ID

Round #39386

### Test Merges

#12948 #12912 #13185

### BYOND Username

RoroMonster

**Comment by adamsong** [comment]
Fix merged
