### ISSUE TITLE
robotact doesn't work

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13222]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: When i try to open the robotact app it keeps saying "The modular interface flashes an "Hardware Error - Incompatible software" warning."
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/938785912148607066/unknown.png)
 Submitted by: Debt (407757687334633473)

**Comment by nmajask** [comment]
Fixed by #13220

**Comment by adamsong** [comment]
Fix merged
