### ISSUE TITLE
Borer camera gets stuck when releasing host

### ISSUE THREAD

**Issue by MasterPenguin5** [yogstation13/yogstation#1322]
Played as a borer, and when I released my first host to move to a more desirable one, my camera was still locked to the original host's body instead of moving with my borer as I moved. Clicking Release Host again would display the message for deciding against releasing, even though I had already left the body, and then hitting the button once more would start the release process again, only I would already be outside the body. No matter what I tried, I could not seem to get the camera to follow my borer again instead of the host body.

**Comment by Super3222** [comment]
I just tested this out. I was able to hop in and out of my host just fine. I wasn't able to recreate this...

**Comment by MasterPenguin5** [comment]
Sorry, forgot to mention that my host was either in crit or dead when I tried this. See if that changes anything. Also, I just remembered that, after I had left the host's body, the borer icon was still over the host's head, and there was no icon over me.

**Comment by ShadowDeath6** [comment]
borers themselves don't get HUD icons

**Comment by MasterPenguin5** [comment]
But my point was that the host I had just left still had the icon, even though I was out of his body.

**Comment by utahclock** [comment]
#1274. Should have fixed this.
