### ISSUE TITLE
Makeshift Lungs Broken sprite

### ISSUE THREAD

**Issue by MusselMain** [yogstation13/Yogstation#13246]
### Severity

Inconvenience

### Short Description

Makeshift Lungs sprite invisible, this is problematic.

### Reproduction

1.be ghetto doc
2.need lungs
3.make "Makeshift Lungs"
4.realise they are invisible, requiring you to right click to "see" them via the name
5.report bug

### Round ID

N/A

### Test Merges

None

### BYOND Username

SKULLVANGUARD

**Comment by SomeguyManperson** [comment]
has since been fixed
