### ISSUE TITLE
Golem body swap does not swap antag status.

### ISSUE THREAD

**Issue by KittyNoodle** [yogstation13/Yogstation#13245]
### Severity

Round Breaking

### Short Description

After swapping your body as a golem, any antag status you might have had is removed.

### Reproduction

1.Be non-conversion antag.
2.Become Golem
3.Attempt to swap bodies.
4.Loose antag status
5.Cry

### Round ID

N/A

### Test Merges

None

### BYOND Username

Noodlecat

**Comment by MajManatee** [comment]
Issue already open. Stop playing golems.
