### ISSUE TITLE
veil breaks shadow emission plants

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13259]
## Test Merges: 
Not Supplied / None
## Reproduction:
Descriptions: It's pretty amazing how often I'm finding these bugs out. If you use a shadowling's Veil Ability you will remove the shadow emissions from the plant that has them. Of course I discovered this WHILE being a Sling and it completely ruined a strat I've wanted to try forever
 Submitted by: Rg4 (185114950354731008)

**Comment by Oblisk234** [comment]
Shadowlings was removed, see #20581
