### ISSUE TITLE
see-through turret control on box ai sat

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13261]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: You.. can see it through a wall?
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/941817366109646938/unknown.png)
 Submitted by: The Lusty E (302595577793740801)

**Comment by UselessTheremin** [comment]
result of pixel shifting, should be an easy fix.

**Comment by patpol4** [comment]
appears to be fixed
