### ISSUE TITLE
Crew Requested AI Control Codes Don't Work

### ISSUE THREAD

**Issue by GirdoMALF** [yogstation13/Yogstation#13275]
### Severity

Inconvenience

### Short Description

Inputting a requested AI control code gives feedback it's too short, despite being the exact code

### Reproduction

1. As Chief Engineer, built an AI Control Console.
2.  After construction, was given access to request AI Control Codes from the station terminal and did so.
3. Returned to console, entered the six digit AI Control Code
4. Was told "Incorrect code. Too short" as a feedback.

A staff member online at the time was able to re-request the codes on their end (unsure what they did), but after spawning in a new piece of paper with a different code, it worked successfully.

### Round ID

39551

### Test Merges

#12912 #13249

### BYOND Username

Girdo

### Additional information

Not much else to say. Pretty straightforward, the code just hated me for whatever reason. I might be shit at spelling and typing, but come on, even I know how to type six numbers right.

**Comment by Bibby0110** [comment]
can't reproduce. will try again later
