### ISSUE TITLE
The frames are a lie!

### ISSUE THREAD

**Issue by spaceboi123** [yogstation13/Yogstation#13287]
### Severity

Inconvenience

### Short Description

The machine frames in the AIs secondary core are not real

### Reproduction

1 Be science boi
2 go to build AI more expansion buses (In secondary AI core room, in sci)
3 see there are machine frames already there
4 go to use the machine frames with wire to build bus
5 not actually a useable machine frame that I can build with
6 cry because the room is too dam small to move in to remove them because you can't deconstruct the unusable ones

### Round ID

39587

### BYOND Username

Billybobdaboss113

**Comment by Bibby0110** [comment]
Should be fixed now as of secondary core rework
