### ISSUE TITLE
Text to speech circuits can't handle special characters (including apostrophes)

### ISSUE THREAD

**Issue by Hate9** [yogstation13/Yogstation#1330]
Issue reported from  Round ID: 16775 (Yogstation 13 [99% LAGFREE!])

Reporting client version: 512

[Round ID]: 16775

[Reproduction]: When using an integrated assembly text to speech circuit, any special characters are converted to HTML special character codes.
This means that using one to say `don't` results in the circuit saying `don&#39;t`.
Obviously, this is an issue.

**Comment by Amelia0010** [comment]
>This means that using one to say "don't" results in the circuit saying "don't".
>Obviously, this is an issue.

**Comment by Hate9** [comment]
I had to put it in code boxes so it wouldn't automatically change the html character code to a regular character.

**Comment by Altoids1** [comment]
Circuits dead, closing.
