### ISSUE TITLE
forced sig tech

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13314]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Three people now (me included) have been forced into signal technician job roundstart, even if its set to never on the preferences
 Submitted by: Alagoinha (372853004199657479)

**Comment by patpol4** [comment]
Could be the overflow trait

**Comment by SomeguyManperson** [comment]
would assume this was caused by the overflow trait since it hasn't occurred since
