### ISSUE TITLE
Player Telemetry showing up in Secret: Admin Log

### ISSUE THREAD

**Issue by Rayisken** [yogstation13/Yogstation#13331]
### Severity

Quality of Life

### Short Description

Player Telemetry is showing up in Secret -> Admin Log when it previously did not

### Reproduction

Shows up in the Secrets -> Admin Log throughout the round for different players. 

Telemetry data for ckey/(mob): {"connections":[{"ckey":"***","address":"169.254.255.255 ","computer_id":"CID*"},{"ckey":"rayisken","address":"169.254.255.250 ","computer_id":"CID*"},{"ckey":"rayisken","address":"169.254.255.251","computer_id":"CID*"},{"ckey":"rayisken","address":"169.254.255.252","computer_id":"CID*"},{"ckey":"rayisken","address":"169.254.255.253","computer_id":"CID*"}]}

This information isn't needed in this log and clutters up the information the log is intended for.

### Round ID

39722

### BYOND Username

rayisken

**Comment by Bibby0110** [comment]
Not a bug, intended behaviour. Talk to alexkar about it
