### ISSUE TITLE
The pirate ship appears to instantly flood with air and kill its crew with fastmos

### ISSUE THREAD

**Issue by KittyNoodle** [yogstation13/Yogstation#13336]
### Severity

Round Breaking

### Short Description

Pirate ship fills up with air

### Reproduction

1.Spawn in as pirate
2.Ship begins to fill up with air
3.Die from space wind

### Round ID

39729

### Test Merges

#13185, #13282, #13211, #13288, #13234

### BYOND Username

Noodlecat

**Comment by cowbot92** [comment]
this issue no longer happens
