### ISSUE TITLE
New AI machines bug out.

### ISSUE THREAD

**Issue by Iraq-Lobster548** [yogstation13/Yogstation#13353]
### Severity

Inconvenience

### Short Description

New AI machines don't always let you allocate them to the AI or don't show up on the AI server overview

### Reproduction

1. Join round as AI
2. Have someone make a new Cloud storage or data core OR remove an existing device and re-install it.
3. check server overview and don't see the device
4. Check resource allocation and don't see added resources available to distribute.

### Round ID

39768

### Test Merges

13185, 13282, 13211, 13288, 13234

### BYOND Username

Iraq Lobster

**Comment by patpol4** [comment]
@TheGamerdk
