### ISSUE TITLE
Lavaland locker traps miner

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#13356]
### Severity

Round Breaking

### Short Description

Miner cannot escape from locker in ruins.

### Reproduction

- miner gets trapped in some "experimentation machine" or what locker
- without an APC created, it is impossible to open it, move it, break it even from the outside!

![ss13-bug-lavalandlocker](https://user-images.githubusercontent.com/16806055/155974470-eda6f3ee-9b66-4799-ac70-59fd74e0e480.png)

### Round ID

39774

### BYOND Username

Aquir

**Comment by patpol4** [comment]
you can just break out with resist
