### ISSUE TITLE
bloodsucker antag coffin mechanics and vanishing act ability bug

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13362]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Upon using Vanishing Act to return to my lair, I was tele'd to my coffin to wait out the Sol where I was stuck in a cycle of not being able to close the coffin on myself despite it registering as closed initially and was unable to close the abilities menu as I leveled up upon teleporting back. Love the idea by the way!
 Submitted by: Egofapter (769390729646440468)

**Comment by tattax** [comment]
could you try recreating this anytime soon (round crash so no replay)

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/13918
