### ISSUE TITLE
Changeling Reviving Stasis not working

### ISSUE THREAD

**Issue by Wisami1** [yogstation13/Yogstation#13361]
### Severity

Round Breaking

### Short Description

Ling skill "reviving stasis" Not working. When i clicked its button the normal message appeared saying "We begin to heal rapidly." After some minutes, i should have revived but the icon didn't change and so didn't the button's description. Pressing after the first time will result in the message "We are alredy reviving." Waited more than 10 minutes and nothing.

### Reproduction

1.Join round as assistant and roll changeling
2.Get bola'ed multiple times in experimentor room, Bola someone else multiple times.
3.Get shot multiple times with beanbag from a sawed off riot in science hallway, in the chest
4.WALK towards the western experimentor room airlock, the tile next to it was wet, west one.
5.Get door crushed with western experimentor airlock and bashed with sawn off riot
6.When in crit, hit reviving stasis button. Then respec button.
7.Open ling skills panel, try to get these skills in this order: Adrenaline, Biodegrade, Fleshmend, Strained muscles. Which doesnt work becose youre in crit.
8.Bug appears, as described.

### Round ID

39803

### Test Merges

 #13185  #13211  #13288  #13234

### BYOND Username

Wisami

### Additional information

IC name: Tim Levett
Dont know if its important but i was wearing grey jumpsuit, armour vest, black shoes, insulated gloves, toolbelt, welding helmet, gas mask, sechud sunglasses and sec bowman

skill issue

site of the incident
![Site of the incident](https://user-images.githubusercontent.com/95562408/156256546-7704c0f8-438f-41d4-8160-ef62fa3fe106.PNG)

**Comment by SomeguyManperson** [comment]
Did you use the respec button

**Comment by Wisami1** [comment]
> Did you use the respec button

Dont really know what youre trying to mean here, but if you mean the respective button, yes.

**Comment by Wisami1** [comment]
> Did you use the respec button

Sorry, yeah i hitted readapt when i was in crit at the door. Forgot to write that

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/13911
