### ISSUE TITLE
Podperson Bloodsucker creates coffin hell

### ISSUE THREAD

**Issue by KittyNoodle** [yogstation13/Yogstation#13364]
### Severity

Round Breaking

### Short Description

Podpeople bloodsuckers loose health in darkness, going into a coffin in total darkness(or going in with a flashlight equipped and only a flashlight for light) results in you loosing health and healing for all eternity

### Reproduction

1.Be podperson
2.also be bloodsucker
3.go into coffin in dark area
4.infinite healing hell

### Round ID

39819

### Test Merges

#13185, #13273, #13211, #13288, #13234

### BYOND Username

Noodlecat

**Comment by tattax** [comment]
should be fixed in quick fix 3

**Comment by tattax** [comment]
fixed in the original pr ^^
