### ISSUE TITLE
invisible bayonet

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13369]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: toggling a kinetic accelerators attached gunlight causes the knife to disappear off the sprite, the knife is still there though and can be taken off and reattached to become visible again
 Submitted by: ☾ MidnightZero ☽ (525377778246484013)

**Comment by nmajask** [comment]
[This PR from TG](https://github.com/tgstation/tgstation/pull/47053) fixes it, I'll port it when I get home.
