### ISSUE TITLE
Cannot sell gases or do gas bounties

### ISSUE THREAD

**Issue by Ethan4303** [yogstation13/Yogstation#13378]
### Severity

Inconvenience

### Short Description

Selling canisters of gas give no credits or complete bounties for said gas

### Reproduction

1. make tritium farm
2. fill canister with 5k mols of tritium
3. sell it via cargo shuttle
4. check cargo console
5. Cry cause no money or bounty processed

### Round ID

Round #39846

### Test Merges

#13185 #13211 #13288 #13234 #13273

### BYOND Username

ethan4303

### Additional information

had martin try to sell hypernob before aswell and cargo didn't credit the hypernob or any of the bounties aswell so i think just selling gases entirely is borked

**Comment by tattax** [comment]
did you send tanks or canisters
cause it only works for tanks (big ones so that they can hold 20 mol)

also gases don't have any value, only if they're a bounty

https://github.com/yogstation13/Yogstation/pull/10727

**Comment by tattax** [comment]
@Ethan4303

**Comment by Ethan4303** [comment]
Tanks are the hand held and canisters are the dragged ones, right? because im fairly sure canisters are the large ones, probably just my mistake on that part for getting it mixed up, although i feel you should still be able to sell a canister of gas to complete a bounty asking for a smaller amount of gas,
 oh and yeah i sent a full canister of tritium

**Comment by nmajask** [comment]
> Tanks are the hand held and canisters are the dragged ones, right? because im fairly sure canisters are the large ones, probably just my mistake on that part for getting it mixed up, although i feel you should still be able to sell a canister of gas to complete a bounty asking for a smaller amount of gas,
> 
>  oh and yeah i sent a full canister of tritium

Canisters are the big ones and tanks are the handheld ones.

**Comment by tattax** [comment]
what i mean by big tanks is non belt tanks (i.e not the tank in your backpack but the one in the tank dispenser)

**Comment by tattax** [comment]
@UselessTheremin

**Comment by Oblisk234** [comment]
Per what has been said previously, #10727 means that simply selling gases doesn't work, it needs to be a bounty. Canisters don't work for bounties either, they need to be tanks.
