### ISSUE TITLE
More strange object effects [IDEAS WANTED]

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation#1339]
I was thinking of more strange object effects.
If you don't know what it is, it's basicly an object you can find in maint, and once discovered with the experimentor, has a special power.
When activated in-hand, it does some random shit. Like explode, teleport, spawn corgis, cleaner grenade etc

Anyway, I wanna make some more.

AND I NEED YOUR IDEAS

COMPLETED: (More to come, but it'll take time since I am bad at focussing)

- Turns the object into an exact clone of yourself.

**Comment by Time-Green** [comment]
Idea's:

- It swaps your gender
- It fake-swaps clothing with a random person for a few seconds
- it turns into a fake clone of you, but once interacted with, returns to normal
- It turns into a random object. Wich will dissipate once interacted with
- It turns into a wall. Wich will dissipate once interacted with
- it creates a fake explosion.
- It swaps your organs with someone elses
- It swaps a random limb with someone elses
- It straight up drops a limb, but it can be re-attached instantly

**Comment by ShadowDeath6** [comment]
>swaps your gender

hmm........................................................................................................................................................

also the limb thing can't be done without setting you to a race with easy limb attachment, maybe make you a zombie or something as well

**Comment by Time-Green** [comment]
Wouldn't be coding it it were easy

**Comment by utahclock** [comment]
Makes you drop all

**Comment by Shadowhawk31** [comment]
1. Mindswap
2. spawn slaughter demon (1 time use)
3. instant gib
4. lightning bolt strike you gibing you
5. teleports you randomly
6.creates some kind of room mabye a 5x5 mini bar room or mini medbay or mabye something demonic, muhaha the possibilitys are endless

**Comment by Shadowhawk31** [comment]
I feel like this would be a awsome new feature

I support this fully

**Comment by Time-Green** [comment]
Those are fun idea's, but stuff like slaughter demons is a bit TOO MUCH

**Comment by drderp3635** [comment]
1+2 separate ones that push/pull all of the objects  in the area, like sorium or dark matter
3 Full strips the user
4 Reusable smoke bomb
5 shoots out a tesla shot at the user chaining to nearby targets
6 catches the user on fire for several seconds
7 flips everything in a nearby area
8 small emp blast

Also in regards to shadowhawk's ideas, gibbing the user is pretty harsh and probably shouldn't be implemented

**Comment by Zostroll** [comment]
1. Spawns a random item of food(has a long cooldown) ((maybe a have it really rarely spawn a roburger or gatfruit))
2. Have it shoot a pie at the person activating the item's face (which in practice would be a ic message that the strange device launched a pie at them and them getting the effects of being hit with a pie)
3. Spawn thirty cook simple mobs that scream to many cooks and then break/melt(The chef simple mobs should be really easy to kill or not agro ever)
4. Randomly teleports you like a hand tele.
5.Dress the user in NODROP clown gear then breaks/melts
6. Gives the user a very small shock like one of those novelty pens.
7.Gives the user a random disease symptom then breaks/melts
8. Gives the user a random race then breaks/melts(even sling maybe?)
9.Gives the user a random objective like the abductor ones then it breaks/melts
10.Turns the user into a sentient egg.

**Comment by doerakpoes** [comment]
1. Turns user into a statue (temporary)
2. Turns user into a borg (1 use)
3. Creates an anomaly (1 use)
4. Gives user a fake armblade (removable only via surgery)
5. Gives user a loyalty implant (i ran out of ideas okay? being extreemly OP for sec)

**Comment by Kmc2000** [comment]
creates 3x3 room made of rwalls around you

cuts off one arm and attaches it to the object

spawns 50  bars of beef jerky around you, combine with corgi object for fun

sprays out lube and makes a loud vibrating hum

throws itself really fast away from you

**Comment by ShadowDeath6** [comment]
>beef jerky

**Comment by doerakpoes** [comment]
> throws itself really fast away from you
Time too send people outof the airlock and into electric grilles

**Comment by Drakkon** [comment]
No more?

**Comment by ShadowDeath6** [comment]
this was already implemented
