### ISSUE TITLE
borg hugging module doesn't reduce stun/sleep/knockdown from others

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13421]
## Test Merges: 
Not Supplied / None
## Reproduction:
borg hugging module only gives flavor text when hugging others and makes others get up when they're resting unlike carbon/human hugging which reduces stun/sleep/knockdown/etc on hug.
 Submitted by: Rune Knight (257721577028714496)

**Comment by tattax** [comment]
the unstunning part is kinda intended since borgs, well, are immune to most status effects and having them literally reduce all your stuns would not be very good
