### ISSUE TITLE
Xenomorphs cannot cool themselves down after reaching damaging levels of heat

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#13446]
### Severity

Inconvenience

### Short Description

title

### Reproduction

1.) Be Xeno
2.) Be exposed to damaging levels of heat
3.) Leave heated area
4.) Die because your body temperature never goes down, despite being exposed to space

### Round ID

#40049

### Test Merges

#13288 #13273 #13211 #13185 #13381 #13270 #13442

### BYOND Username

TheBombMaker

### Additional information

This has been a recurring thing with xenos + heat, for several months now, since monstermos, so much so that I can't tell if this is intentional

**Comment by Bibby0110** [comment]
you can't cool down in space, that's intentional i think

**Comment by alexkar598** [comment]
Correct, there's no air to transfer the temperature to. This was done to prevent being able to get overheated from spaced plasmaflooded rooms
