### ISSUE TITLE
yalp elor dies instantly (real footage)

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#13463]
### Severity

Round Breaking

### Short Description

yalp elor does not Fricking work

### Reproduction

1. Would you like to play as a fugitive?
2. You must protect your followers from Nanotrasen! Only your followers can hear you-
3. All of your followers are gone. (they are not gone they just spawned just now)
4. That means you cease to exist. (bro listen)
5. (F) DEAD: (Yeat) Sandy Loam says, "ew"

### Round ID

#40085

### BYOND Username

Sniblet

**Comment by Altoids1** [comment]
You must protect your followers from Nanotrasen! Only your followers can hear you-

All of your followers are gone.
![image](https://user-images.githubusercontent.com/29939414/162335287-b88ca1fb-8340-48b8-9adb-1a7a96bbc8b7.png)

**Comment by Sniblet** [comment]
oopsy
