### ISSUE TITLE
Downloading an AI does not show the correct name during the process.

### ISSUE THREAD

**Issue by Bluedazzled** [yogstation13/Yogstation#13464]
### Severity

Inconvenience

### Short Description

Essentially what the title says. When you're downloading an AI it always shows "G2" instead of the AI's name. Thank you bibby.

### Reproduction

1: Begin downloading an AI
2: Realize you're downloading some "G2"
3: Cry.

### Round ID

#40090

### BYOND Username

bluedazzled

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/13465
