### ISSUE TITLE
Blood changes

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#1347]
the current blood system is ass and more of a 'no effect for 90% of the time, then you're suddenly fucked' kinda thing.

I vote we change blood up a ton.

After playing on goon, I got an idea how.

See, we change our current blood level to, say, blood pressure. Blood level still exists-blood is still a unit-but pressure is a factor too.

Standard human bloodpressure is around or below the range of 120/80, so that's what we'll use-at roundstart, everyone human will have 120/80 or variations thereof blood pressure.

Going over this, hypertension, will cause various negative effects based on how high it is. Past 140/100, which is considered the hypertension level, the med scanner will read HYPERTENSIVE, and the patient will start off feeling a variety of symptoms. ''You feel sweaty!' 'Your heart thuds in your chest.' 'You can hear your blood rushing by your ears.' et cetera. You start taking o2 damage and random stamina damage. Incidentally, they also move faster at this point.

Past 180/120, the patient begins passing out randomly, taking brain damage, and suffocating randomly while being bombarded with messages such as how it's difficult to breathe, coughing up blood, etc. When they cough up blood, it applies the same effect as blood vomiting symptom-brute damage, blood appears on the floor. (This might help save the person, so consider it a part of positive effects.) They're also capped at 70 health (30 stamina damage remains, permanently) Bleeding at this point will apply the same 'uncontrollable bleeding' as heparin until blood returns to normal levels. They do not take slowdown from damage. Clotting can occur from this point and onward.

Past 200/130, the patient begins being stunned, passing out, and taking heavy o2 damage constantly, enough to kill within 10 minutes. They stop metabolizing poisons of any kind and suffer blurry_eyes constantly. Blindness can also result from accumulating eye damage. All the above effects still apply but the messages are scarier. Heart attacks will rarely, very rarely, occur due to this, and seizures may occur.

220/150, all of the above but it's fatal within 5 minutes and health is capped at 50 (50 stam damage) while also taking dizziness effects. When/if my new med system is implemented, toss in organ damage to the mix. Heart attacks can result due to this. Constant blood vomiting may occur.

250/180 essentially kills the person as their arteries and veins snap from the blood pressure and they hemmoharrage internally. Regardless of the fact that they're going to drop to normal blood levels, they will continue bleeding until given anticoagulants and will suffocate, period, no o2 gain whatsoever. It's the GG point.

HYPOTENSIVE occurs at or below 90/60. As the patient approaches hypotensitivity, they begin taking o2 damage and slowing down.

At hypotensitivity, they begin to experience the effects of current bloodloss-random stamina damage and passing out, slower movement, o2 loss.

As hypotensitivity becomes more severe they begin taking severe brain and eye damage as well as all the above effects, until they begin to suffer heart attacks and die.

Blood level can be regulated by several factors.

Firstly, when you're bleeding, you drop from your normal blood level down over time as you do currently. But instead of being 100% blood, 99% blood, it goes from 120/80 down down down. 

so, if you're hypertensive, there are a few ways to fix it, and all involve losing blood or mitigating the side effects. Firstly, heparin, now considered a medicine instead of a poison (and nerfed slightly accordingly) will start to drop the blood pressure and remove clotting. Overdosed at 30u, the patient develops the normal heparin effects-uncontrollable bleeding, vomiting blood, etc.

Otherwise, you can fix hypertension either via IV drainage or simply just bloodletting. Yeah, bloodletting. Hit yourself until you bleed then bandage yourself. Dangerous and innacurate, but hey. And it'll backfire if you're way too high blood pressure when the blood basically just gushes out as a result.

Hypotensitivity can be fixed by a new goon-taken chem, Filgrastim, or proconvertin. Proconvertin increases blood pressure without increasing blood units and has a 10% chance to stop bleeding per tick. 

Filgrastim directly adds blood units, which will increase blood pressure. by default.

And yes, to touch on the whole blood units thing-Blood units still exist, people start off with 500u. As it decreases, blood pressure decreases accordingly, but can be increased with certain chemicals. As it increases, blood pressure increases accordingly, but can be decreased with certain chemicals.

This entire thing is stolen from goon.

**Comment by Super3222** [comment]
Eh. I don't know how I feel about this. I'm 50/50 on this, the blood system right now isn't /that/ bad, and fairly player friendly where as it's easy to comprehend what you need to do when you're low on blood. On the other hand, approaching more advanced medical systems is a step forward for our server, and would be appreciated by our players. I also prefer taking medical, and what Doctors can do for patients a step forward.

As for the suggestion itself, I think it's fairly balanced. I'd suggest keeping pill bottles full of filgrastim and possibly /mild/ heparin in the medivendors so doctors can easily access them. I know some people are going to get on my case about letting the chemists collaborate with Doctors on that, but that's like saying all antitoxin should be made in the chemistry lab. Blood loss is going to be a reoccurring problem given the nature of ALL of our modes.
