### ISSUE TITLE
sprites bugged 

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13494]
## Test Merges: 
Not Supplied / None
## Reproduction:
new round, went to character editor, and i had no body. Loaded into the game, and this is what i see
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/956204417898659940/unknown.png)
 Submitted by: tom. (695086559665324083)

**Comment by Bibby0110** [comment]
BYOND issue
usually fixed by clearing your cache and restarting
