### ISSUE TITLE
When changing the priority of the paramedic or the roboticist, they change together.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#135]
As in. If you make roboticist high, then paramedic will also be high.
If you make paramedic high, then roboticist will also be on high.

**Comment by Super3222** [comment]
The fix was merged earlier.

**Comment by X-TheDark** [comment]
Indeed. https://github.com/yogstation13/-tg-station-yog-rebase/pull/128

**Comment by GrayRachnid** [comment]
Still happening.

**Comment by X-TheDark** [comment]
Ok, checking this out.

**Comment by X-TheDark** [comment]
Latest 'master' fixes this. I think this was merged but server wasn't updated.
