### ISSUE TITLE
cloning removes quirks

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13501]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: when you get cloned you lose your quirks, i noticed this due to trying to use self aware to see if i could figure out why i was in such a terrible state post cloning
 Submitted by: ☾ MidnightZero ☽ (525377778246484013)

**Comment by Altoids1** [comment]
![image](https://user-images.githubusercontent.com/29939414/164559375-4e401dbc-5007-483a-9cac-84c4a5998a3f.png)

Quirks in general seem to be cloning okay.

**Comment by Altoids1** [comment]
As far as I can tell, this person was just like, expecting Self-Aware is also give a reasonable description of cloning damage? Which it does not. That's more of a feature than a bug, so

# Not A Bug.

**Comment by Oblisk234** [comment]
Can't replicate, probably cloned with an unupgraded cloner resulting in cloning damage. Non-issue.
