### ISSUE TITLE
void jaunt as shadowling permanently kills you

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13502]
## Test Merges: 
Not Supplied / None
## Reproduction:
If you jaunt into space as shadowling and the server disconnects you due to lag, or if you disconnect yourself, you will go into an infinite crit state where your body is gone so you cannot be recovered by any means. the only way to get out of this is by succumbing or ghosting, as you cannot stop the jaunt.
 Submitted by: Runi (285815358408097792)

**Comment by Oblisk234** [comment]
Shadowlings no longer exist, see #20581
