### ISSUE TITLE
AI download is instant

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#13513]
### Severity

Round Breaking

### Short Description

AI download is instant

### Reproduction

1. Malf AI
2. RD makes control console in maint
3. Robotic talk, AI says "I'm being downloaded"
4. Robotic talk, Cyborg says "Where"
5. Robotic talk, AI says "I'm downloaded now"
6. Robotic talk, Cyborg says "What"

### Round ID

40191

**Comment by Bibby0110** [comment]
[2022-03-25 23:08:19.146] HREF: [THE AI] (usr:S.O.V.I.E.T.[(0,0,0)]) : S.O.V.I.E.T. src=[mob_567];instant_download=1;console=[0x2030d3c]
TL;DR
AI clicked the instant download button.

I'm going to add an explicit warning to doing that now though.
