### ISSUE TITLE
Mapping - screwdriver in security rooms

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#13547]
### Severity

Inconvenience

### Short Description

As far as I'm aware, the YogStation service sec room and YogsMeta security office are the only two security areas which are missing the screwdriver as included tool everywhere else.

### Round ID

40239

### BYOND Username

Aquir

**Comment by 00aquir** [comment]
also Kilo sec office has it too but there the sec posts have crowbar instead

**Comment by patpol4** [comment]
box has them in all

**Comment by 00aquir** [comment]
yes, now it's in the locker (on box)

**Comment by patpol4** [comment]
meta will have them too now
