### ISSUE TITLE
Preserve ghost tab settings between ghost sessions

### ISSUE THREAD

**Issue by Paragonid** [yogstation13/Yogstation#1355]
Ghost tab settings "Toggle Darkness", "Toggle Sec/Med/Diag HUD", "Toggle Health Scan" (maybe something else) could be stored so player doesn't have to retoggle it each time he becomes ghost.

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.
