### ISSUE TITLE
bluespace lockers break arrivals shuttle

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13551]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: enter a bluespace locker on the arrival shuttle, if there's nobody on the shuttle itself it'll depart to the lobby screen
 Submitted by: kooarbiter (194238977379663872)

**Comment by patpol4** [comment]
well yes

**Comment by patpol4** [comment]
This not an issue, it happens because you leave the shuttle when in the locker, it doesnt depart to the lobby screen but just to the transit zlevel
