### ISSUE TITLE
AIs can see in space without cameras

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation#1358]
Probably related to #1297

**Comment by monster860** [comment]
I'm pretty sure the AI always did that.

**Comment by Cruix** [comment]
If that were the case the AI would be constantly finding the nukeop's ship and ratting them out.

**Comment by ShadowDeath6** [comment]
AIs sometimes bug out and can see parts of space, unless you can see literally all of space 100% of the time it might just be some edge case thing

**Comment by Jc1469** [comment]
AI has always had a buggy camera in regards to space.  SOMETIMES it is staticy, sometimes you can see perfectly fine.

**Comment by Super3222** [comment]
You can see **a lot** of space.

**Comment by Cruix** [comment]
Leave a comment
