### ISSUE TITLE
 Clockie eminence has speech bubble, can also see rally orders

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13585]
## Test Merges: 
Not Supplied / None
## Reproduction:
I was able to see the eminence's speech bubble and rally orders, simple as.

 Submitted by: dukebobross (305348676883316737)

**Comment by Altoids1** [comment]
I think this is just a systemic problem with all ``/mob/camera`` mobs, and invisible mobs in general.

**Comment by ToasterBiome** [comment]
Fixed as of merge of https://github.com/yogstation13/Yogstation/pull/13435
