### ISSUE TITLE
Mapping - Kilo Station prisoner management

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#13596]
### Severity

Inconvenience

### Short Description

Kilo Station - without warden present, there are prisoner IDs in the labor dock, but no prisoner management console to set the points! Also the teleporter might have a problem?

### Reproduction

- no prisoner console at labor.
- Plus when I tried a while back, the labor camp teleporter didn't seem to work?

### Round ID

40342

### BYOND Username

Aquir

**Comment by patpol4** [comment]
kilo has been removed
