### ISSUE TITLE
 Character Creation Changing Appearance

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13624]
## Test Merges: 
Not Supplied / None
## Reproduction:
When entering the character creation clicking or changing anything including age or clothes completely alters the characters appearance

 Submitted by: The Dip (249916055286185994)

**Comment by patpol4** [comment]
Randomize was probably on

**Comment by Oblisk234** [comment]
Can't replicate since it's old preference menu, or at least before #17368 and #17381
