### ISSUE TITLE
Friendly Marrow Weavers Attack Their Reviver

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13660]
## Test Merges: 
Not Supplied / None
## Reproduction:
After reviving Marrow Weavers with the Lazarus Injector and pitting them against another mob, the Marrow Weaver becomes hostile to me, as if it were a normal mob. This occurs twice during this round, easist to see is after fighting the Herald.

 Submitted by: LouTenant (203218725086691328)

**Comment by LazennG** [comment]
i fixed this issue in #14295, so marrow weavers no longer attack people on their faction to try eating their guts
