### ISSUE TITLE
 Abductor Antag Icon Disappearance

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13673]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Shadowling thralled me, confirmed I had thrall HUD icon and was able to use thrall powers. Abductors got me, performed surgery one me, and processed me. After returning to station, the Thrall HUD icon was gone which led to a mild amount of confusion on part of a Shadowling. I was able to test and verify that I could still use thrall powers.

 Submitted by: TIP (224709768814526467)

**Comment by tattax** [comment]
fixed by antag pr
