### ISSUE TITLE
Muscle Stimulant for arms from DNA vault

### ISSUE THREAD

**Issue by IzzaBinS33n** [yogstation13/Yogstation#13671]
### Severity

Inconvenience

### Short Description

Before this I was able to hit the hotkey Q to drop items and E to fast equip things to my body, now both of them arent working. It says when i hit Q "you cant fit anything in"

### Reproduction

1. DNA Vault
2. Finish DNA vault and select Arm Stimulants program
3. Issue occured

### Round ID

40443

### BYOND Username

IzzaBinSeen

**Comment by SomeguyManperson** [comment]
potentially the game thought you were holding shift, which happens sometimes. Tapping shift again should fix it
