### ISSUE TITLE
Abductors could be cool guy if changed

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1369]
Abductors are mother fuckers. Why does it have to be like this?

 Can we change them so they get points based on healing, augmenting (cybernetics,  genetics, viro, etc ), and cloning?

 Good abductors will get ooc cool guy points at the end of the round for doing cool guy stuff.

**Comment by Super3222** [comment]
They're antags so they're not meant to help out the crew, but give them a challenge.

Abductors turning humans into abominations of their former selves sounds great in theory,  but than put in perspective how they can instantly zap down and than back up on a body that doesn't want to be changed.

**Comment by Time-Green** [comment]
Then make humans sign a contract for legal purposes and give permission to become an abomination.
I'd sign up.

**Comment by AdamElTablawy** [comment]
wtf

**Comment by ShadowDeath6** [comment]
what

**Comment by enailz** [comment]
ok
