### ISSUE TITLE
 "Snacks"

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13707]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Was making holy watermelons and they turn in invisible upon harvest and you are left with something called a "snack"
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/963466276473298944/I_am_concerned.png)
![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/963466276674613308/Snack.png)
![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/963466276892721182/invisible_food_sus.png)
 Submitted by: Eevee (881588458873831495)

**Comment by SomeguyManperson** [comment]
Fixed by #13715
