### ISSUE TITLE
Ionising Cellular Emission doesn't deal radiation damage

### ISSUE THREAD

**Issue by PotatoTomahto** [yogstation13/Yogstation#13741]
### Severity

Low

### Short Description

The description of Ionising Cellular Emission is "Causes the host's cells to emit ionizing radiation.", but it doesn't deal radiation damage.

### Reproduction

1. Give a virus the Ionising Cellular Emission symptom
2. Infect yourself with it

It seems to give some flavor text, but it doesn't seem to do anything beyond that: no radiation, no damage, no mutations.

### Round ID

40512

### Test Merges

#13419 #13435 #13603 #13698

### BYOND Username

PotatoPotahto

**Comment by Altoids1** [comment]
This looks like another case of "someone thinking that just adding an integer to a mob's damage stack variable actually informs anything in the game that this variable was modified."
