### ISSUE TITLE
Remove Talking Mimes

### ISSUE THREAD

**Issue by enailz** [yogstation13/yogstation#1375]
Clowns start with Clumsiness(Clown mutation), Mimes start with two spells, one allows them to... talk? AAHH!!! **PANIC.**
My proposal to fix this is:

- Remove the Vow of Silence

- Make mimes start with the Mute and Nervousness mutation (If they somehow manage to talk)

They can still talk if they use mutadone, but it's better than a silly spell that they can use whenever they want to scream "HELP LING MAINT!!"

**Comment by Cruix** [comment]
The mute mutation makes you unable to emote as well

**Comment by enailz** [comment]
Awww
