### ISSUE TITLE
 Sling veil doesn't shut off marker beacon lights

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13764]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Veil doesnt break or turn off marker beacons, allowing miners to spam them and get 100s for 30 points

 Submitted by: ImmortalPlagueRat (605167460450304019)

**Comment by VaelophisNyx** [comment]
pretty sure this has been fixed

**Comment by Oblisk234** [comment]
Shadowlings no longer exist, see #20581.
