### ISSUE TITLE
More random names for the uncreative nerd

### ISSUE THREAD

**Issue by enailz** [yogstation13/yogstation#1376]
Add random name/always random name to Clown, Mime , Chaplain Deity and Religion.

**Comment by Super3222** [comment]
You could start by making a list at least for each group...

**Comment by Drakkon** [comment]
This is how I waste my time. Just add & remove at will I guess. Some suck, but ain't that the point? Tried to make several without them being TOO original for random names. Adding Mr./Mrs./Ms./Dr. or Jr./The First/Second... would work with just about any of these:
## Clown
Honk, Donk, Donk Pocket, Cluwne, Honk Child, Cluwne, Neon, Rainbow, Ear Bleed, Vast Honk, Shakes, Pennywise, Donald McRonald, Squeak, Distraction, Chucklefuck, Giggles, Chuckles, Siren, Bike Horn, Air Horn, Soap, Bozo, Insanity, Clown, Grey Tide, Bananium, Bucko, Boink, Dumbo, Pickles, Dunce, Stinky, Bubbles, Freckles, Captain, Patchy, Racket, Lollygag, Shirraco...
## Mime
Black Noise, Footstep, Tiptoe, Whisper, Shush, Hush, Stalker, Nothing, Mute, Anti-Honk, Silencio, Quiet, Silence, Zero, Nothingness, Morse, Speechless, Voiceless, Honkless, Tranquility, Zilch, Null, Zip, Mimic, Charade, Static, Meme, Stripes, Reticence, Tranquility, Limbo, Baguette, Noodle, Beret, Sepia...

**Comment by doerakpoes** [comment]
Reticence
That's a mime mech

**Comment by Super3222** [comment]
I'll alert the council when I can

**Comment by AdamElTablawy** [comment]
done
