### ISSUE TITLE
 Imminence Speech Bubble appears

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13777]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Imminence's speech bubble appears to everyone when they talk. Thus allow you to determine what the gamemode will be.

 Submitted by: Rg4 (185114950354731008)

**Comment by ToasterBiome** [comment]
Fixed as of https://github.com/yogstation13/Yogstation/pull/13435/commits/8fbbd7b2fd7363e658b346d2dca98ac93fff7dd1
