### ISSUE TITLE
Check AI Laws verb is fucked

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#13775]
### Severity

Inconvenience

### Short Description

Check laws verb has been fucky for many months now and will fail to show laws for most silicons, or show incorrect information. Last round I had a borg that was shown as slaved to an AI but wasn't (Round: 40579).

### Reproduction

1) Press Check AI Laws in admin panel
2) Get fucked

### Round ID

40579

**Comment by Altoids1** [comment]
One nuance that the code seems to miss is that there's two variables tracking AI control of a borg: ``connected_ai``, which tracked who the borg is enslaved to, and ``lawupdate``, which tracks whether the borg's laws are updated when their corresponding AI's is altered.

**Comment by Altoids1** [comment]
![image](https://user-images.githubusercontent.com/29939414/163905968-5ae55235-d925-4484-9be6-bcc752ce78d6.png)

I *think* the issue might be that the chat subsystem is "batching" like lawsets together with the "x2" mechanic, making them not really appear correctly.
