### ISSUE TITLE
bloodsucker frenzy

### ISSUE THREAD

**Issue by Communismbelike** [yogstation13/Yogstation#13787]
### Severity

Round Breaking

### Short Description

I enter frenzy then unenter frenzy as a bloodsucker forcing me into a endless stun

### Reproduction

1. get a vassal
2.favorite them
3. enter frenzy due to low blood
4. come back to my senses then back to frenzy
4. burn to death in sol

### Round ID

40593

### Test Merges

baton nerfs, animated typing bubbles, demon of sin.

### BYOND Username

Communismbelike

### Additional information

Im pretty sure my frenzy limit was at 359 as well, but i was at 500, might want to look at that.

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/14126
