### ISSUE TITLE
Empaths can't tell when somebody is deaf anymore (may affect blindness too)

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#13786]
### Severity

Inconvenience

### Short Description

I've had the empath trait for a good while now, and in the past it gave short descriptions for people who were blind/deaf that informed players with empath that this was the case.  Of late, ESPECIALLY with deafness this text doesn't seem to appear.  I noticed this especially when playing medical roles, they were deaf on the analyzer but my empath trait wasn't telling me as such.  This seems to occur off and on with blindness as well, where the text for it doesn't show.

### Reproduction

1. take empath
2. blow someone up to deafen them
3. they arent deaf according to empath
4. they are deaf according to analyzer and themself
5. stab the shit out of their eyes
6. they arent blind according to empath
7. they are blind according to analyzer and themself

1. stab the shit out of someone elses eyes next round
2. empath says they are blind
3. be confused

### Round ID

N/A

### BYOND Username

Cark

**Comment by Altoids1** [comment]
what a particularly violent system of reproduction
