### ISSUE TITLE
Bloodsuckers can't unbuckle people from their meatspike/rack thing.

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#13818]
### Severity

Inconvenience

### Short Description

Split off from my original issue, bloodsuckers can't seem to manually unbuckle people from the rack they use to thrall people.  This can be annoying if the person in question is mindshielded and therefore cant be enthralled.  Breaking the rack and or waiting for the individual to resist out are the only ways of doing it.

### Reproduction

1. be bloodsucker
2. use spike
3. discover person is mindshielded
4. try to unbuckle them
5. fail

### Round ID

N/A

### BYOND Username

Cark

**Comment by TosterIMC** [comment]
Had the same issue in that round:
https://replays.yogstation.net/?roundid=41966#49547;79.50;90.50;2;tosterimc;-0.0
