### ISSUE TITLE
regenerate_organs() gives felinids invisible cat tails

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#13824]
### Severity

Bad

### Short Description

regenerate_organs() gives felinids invisible cat tails

### Reproduction

1. Be degenerate
2. Be rejuvenated/be a changeling and regenerate/be a changeling and use reviving stasis/be a bloodsucker and go into torpor/be a vampire, get a limb cut off, and revive from death/be hit with regenerate_organs() in any way
3. Your tail is invisible. It's still there because you can wag it. Didn't have a tail? Now you have an invisible one.
4. If someone pulls it out you can see it's a cat tail.
5. If you get it put back in it's still invisible.
6. If you do a changeling transform to someone else and then back, it's still invisible.

7. get meta'd as an antag because everyone can see you got an aheal from somewhere
8. die to mech meta

### Additional information

This only happens to felinids. We’re talking some hardcore systematic oppression.

 I've tried all sorts of update_body update_body_parts regenerate_icons procs, none of them help. Have your species reset or get a new cat tail. Yours is broken.

I spent three and a half hours just trying to find what's happening, I give up
The problem is in either
code/modules/mob/living/carbon/human/species.dm, ln 306-319
Or
code/modules/surgery/organs/tails.dm, ln 16-35
And it could be something to do with the tail's color not being set.
That's all I've got

**Comment by ghost** [comment]
Byond is just based
