### ISSUE TITLE
TG mutation toxins do not work

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#1384]
Whenever you combine ingredients to create the toxins, it destroys the ingredients, make the combining sound, and then creates nothing. 

you can re-create this by combining the reagents and then watching what happens .

**Comment by Time-Green** [comment]
@AdamElTablawy

**Comment by AdamElTablawy** [comment]
well what the fuck do you expect me to do, i can't test it out, i'm permabanned

tell me something specific beyond 'well it doesn't work lol' and i might be able to do something thanks

**Comment by enailz** [comment]
wtf why you're permabanned

**Comment by Time-Green** [comment]
And why are you coding then?

**Comment by drderp3635** [comment]
there is nothing more specific too it. you put the reagents together, it reacts, and then your reagents are gone with no final product. I tried it with three different ones and they all did the same thing.I think the problem is that it shouldn't have the

result= list(sampletext=1) 
and should instead just have
result= sampletext

**Comment by AdamElTablawy** [comment]
@Time-Green 
For the same reason you code, because I want to make improvements to the server and have people interact with those changes how they preform.

The difference between me and you is that I have a functioning brain.
