### ISSUE TITLE
Anti-glow does not look like anti-glow if used on a player

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#13849]
### Severity

Inconvenience

### Short Description

Anti-glow does not look like anti-glow if used on a player

### Reproduction

1. Create anti-glow
2. Inject a monkeyman
3. he antiglow, like shadow emission
4. Inject yourself
5. you just look kinda blue but it still counts as darkness

### Round ID

Any

### Additional information

AFAIK players always anti-glow blue and monkey men always anti-glow purple, so it’s not a mutant color thing
Glowy, probably related, always glows yellow on monkey men and always red on people

**Comment by VaelophisNyx** [comment]
long since fixed
