### ISSUE TITLE
22u of tricord is one of the deadliest poisons in the game

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1385]
This is eithera bug or else idiotic coding because tricord can kill as effectively as any poison..

 OD should be at 50u. Actually since I had to report this issue I am going to insist the OD window start at 80u. Tricord is not poison and it should not be able to kill people unless they really try.

**Comment by drderp3635** [comment]
50 and 80 od threshold is fucking ridiculous, it would be better to just need the of consequences then to make a drug that can be abused to he'll because you practically can't even od

**Comment by ShadowDeath6** [comment]
I think it's 30u OD

**Comment by AdamElTablawy** [comment]
it's a shitty weak healing chem and it's a shitty weak poison

stay off of git

**Comment by ShadowDeath6** [comment]
>shitty weak healing chem

twice as good as omnizine and has high OD, not weak at all
