### ISSUE TITLE
 Solar wiring done wrong

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13865]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: The NE/SE solar panel arrays are missing wire knots under every single solar panel, meaning they cannot be used to charge power. The NW solar array tracker console also is missing a wire knot under it.

 Submitted by: Cowbot (97736956326207488)

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/13974
