### ISSUE TITLE
Wizard Jaunt is bugged

### ISSUE THREAD

**Issue by AJHcHenry** [yogstation13/Yogstation#13860]
### Severity

Round Breaking

### Short Description

As wizard, tried to jaunt and it locked my camera on that tile, didn't mist me, and then moved my character back and forth.

### Reproduction

Blinked into sec pod, prepared El Nath, and tried to jaunt.

### Round ID

Round #40662

**Comment by ghost** [comment]
It is probably because you where inside an object
