### ISSUE TITLE
Experimental Multitool can't make changes on tcomm machines.

### ISSUE THREAD

**Issue by PotatoTomahto** [yogstation13/Yogstation#13888]
### Severity

Low

### Short Description

The RD's experimental holotool can't unlock tcomm machines when in multitool form.

### Reproduction

When on multitool mode, the holotool can't make changes to telecommunication machines.

### Round ID

40684

### BYOND Username

PotatoPotahto

**Comment by Altoids1** [comment]
Telecomms code is kinda old in some places; it's probably checking that it's *exactly* a regular multitool rather than calling multitool_act or whatever the heck it's called
