### ISSUE TITLE
Renaming our map file: "tgstation.2.1.3" to "yogstation.2.1.3"

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation#1389]
Alright, I know that we've been putting it off for awhile but, I'm asking for a cease on all PR's that have to do with changing ANYTHING to do with the station.

This'll require us to merge the following PR's that are currently up - and have to do with changing something to the map:

The ones tagged as _inactive_ will most likely not be finished in time.

https://github.com/yogstation13/yogstation/pull/1360 - Mining Medic PR: Adds a spawn to the map in the mining bay.
https://github.com/yogstation13/yogstation/pull/1340 - Morgue PR: Adds a note to the morgue room explaining what the different lights mean.
https://github.com/yogstation13/yogstation/pull/1147 (inactive)
https://github.com/yogstation13/yogstation/pull/1278 (inactive)

**Comment by ShadowDeath6** [comment]
:^)

**Comment by matskuman5** [comment]
fuk tg !!1!

**Comment by matskuman5** [comment]
I closed my morgue thingy because there was a merge error and I couldn't be bothered to figure it out

**Comment by matskuman5** [comment]
I closed my morgue thingy because there was a merge error and I couldn't be bothered to figure it out

**Comment by matskuman5** [comment]
You should probably do this as soon as your mining medic PR gets merged, I have some map edits I want to do

**Comment by Super3222** [comment]
@matskuman5 

It's been done inside of here: https://github.com/yogstation13/yogstation/pull/1480

**Comment by Super3222** [comment]
https://github.com/yogstation13/yogstation/pull/1498 now.
