### ISSUE TITLE
ban aph from github

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#1390]
jesus fucking christ it's rocks4free all over again man

**Comment by ShadowDeath6** [comment]
:salt:

**Comment by Rocks4Free** [comment]
I agree, his suggestions are all shit and he brings nothing but useless ideas

**Comment by Super3222** [comment]
Let's not form a lynch mob on the GitHub. Let's also never create another issue like this again, old fruit.

**Comment by ShadowDeath6** [comment]
super called adam an old fruit, please remove him from the github permanently

**Comment by Super3222** [comment]
> super called adam an old fruit, please remove him from the github permanently

its a saying, shadow. not an actual old fruit.
