### ISSUE TITLE
 New yellow wired solars are missing cables

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13906]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: There's no cables under the solar arrays, meaning its hard to connect roundstart solars without deconstructing each and every solar panel

 Submitted by: Marunias (368473582981873664)

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/13974
