### ISSUE TITLE
 Size bug using clown shoes

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13914]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Using growth serum and/or gigantism, then moving while wearing clown shoes, reverts your sprite to original size. After growth serum wears off/you remove gigantism you will shrink until moving with clown shoes on again. Instead makes you grow if you use dwarfism.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/968936450534047834/sizeglitch.PNG)
 Submitted by: Jink (84059574050525184)

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/13929
