### ISSUE TITLE
 Missing wire

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13920]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Box station singulo/ Tesla engine spawns without a wire running to the right side emitters 
https://i.imgur.com/8SR5tCm.png

 Submitted by: Gramredhel (124672649782624256)

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/13921
