### ISSUE TITLE
Some Kinetic Accelerators cannot be placed on back.

### ISSUE THREAD

**Issue by osiato** [yogstation13/yogstation#1392]
I cannot place the 'improved hyper-kinetic accelerator onto my back after removing my backpack.

**Comment by Time-Green** [comment]
They dont have the backbag belts. It can fit on your belt tho.

**Comment by osiato** [comment]
Ah, ok. I asked the admin that was on and they said that it should be able to. Maybe that's only default? I wanted it on my back because fannypack of holding is a belt item :(

**Comment by Time-Green** [comment]
They aren't made for your back. Weird admin.
