### ISSUE TITLE
 Can't print tape recorder tapes

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13940]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Had three different mentors tell me I could print tape for the tape recorder in autolathes. There was no tape in the tape recorder for autolathes

 Submitted by: dukebobross (305348676883316737)

**Comment by UselessTheremin** [comment]
you 100% can print tapes, i think you might've just missed it because it is just called "tape"
