### ISSUE TITLE
Sigtech timelock is broken

### ISSUE THREAD

**Issue by Moja10** [yogstation13/Yogstation#13960]
### Severity

Low

### Short Description

New players with 0 hours can show up and play sigtech, restrictions broken

### Reproduction

1. Join as new player
2. See that you can play sigtech 
3. play sigtech with literally no game knowledge and just upload stupid NTSL scripts

I don't know for certain but I think this is unintended. New players can't even play engineer but can play sigtech right out of the gate. Fairly sure something is broken. 

Round example is just one where's there is a new player playing sigtech. New players shouldn't play sigtech. 

### Round ID

40791

### BYOND Username

Yogurtshrimp69

**Comment by Altoids1** [comment]
Sure thing bestie

**Comment by Moja10** [comment]
> Sure thing bestie

YOGGER
