### ISSUE TITLE
Track Monster is a toggle, but why

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#13989]
### Severity

Low

### Short Description

Track Monster is a toggle but doesn’t have a lasting function

### Reproduction

1. Track Monster
2. Track Monster turns ON - you can tell because its background turns red - and starts its cooldown. You hold still 6 seconds even though it doesn’t say you have to because you know better, then it does what Track Monster does.
3. Cooldown ends. You use Track Monster again.
4. Track Monster is now OFF and starts its cooldown. You wait 6 seconds. Nothing happens because you all you did was you turned OFF its ongoing effect which does not actually exist.
5. Repeat

### Round ID

Any monster hunter round, like 40813 and 40812

### Test Merges

#13918 

### BYOND Username

Sniblet

### Additional information

In effect, this means that only every second use of the ability does anything.

**Comment by tattax** [comment]
it actually isn't a toggle and that's the problem

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/14126
