### ISSUE TITLE
Randomized mice spawns

### ISSUE THREAD

**Issue by Dagdammit** [yogstation13/yogstation#1398]
These can & should be a key bit of variety for engineers. Basically, can we roughly triple the number of mice spawns in maint (including at least two in maint south of arrivals hall, three in maint north of arrivals hall, one in maint north of dorms and two in maint north of escape hall?). But also make it so that mice spawns have a 30% chance to spawn a mouse at round start (and maybe another 10% chance to spawn a mouse every 10 minutes thereafter).

**Comment by Rocks4Free** [comment]
playable mice with objectives when

**Comment by Dagdammit** [comment]
When the admins feel like it

**Comment by doerakpoes** [comment]
Mouse objectives : bite all the wires

**Comment by Dagdammit** [comment]
chew as many delicious wires as possible
