### ISSUE TITLE
Eating penalty is too strict / Gauge for satiety

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#1398]
In a series of donuts at security, I ate **only one** donut bit "unwillingly" and -as officer, which was not really fun- already slowed down to walk speed. The limit simply has to be changed since there is no other "gauge" when you eat some food in succession.

**Comment by Ratvar** [comment]
You can see your food satiety bar in the right up corner of your screen.
To become fat, you should have 100 seconds of being over full treshhold (gray food bar).
So, look at the food bar.
If you want to eat food faster then others-you can get "voracious" quirk in character setup menu.
So, you both:
1. Have gauge to look at.
2. Have ingame fix for a problem.

**Comment by 00aquir** [comment]
"You can see your food satiety bar in the right up corner of your screen."

No.
Since the "grey food bar" appears much later than the "unwillingly" word about fullness, you get no sign when you are nearing satiety (when the game immediately punishes the player), thus what you said is kind of irrelevant. This is why it needs to be changed.

All it requires is displaying this "unwilling" eating for a lower level of satiety, or slowing down the player for an even higher level above 100%.

Not to mention fruits or food with yet higher nutriments per bite.. Now that I think of it, there really should be a gauge that instantly shows a detailed level of satiety (with tens of percentages), because of these problems. The characters should obviously feel how full they are anyways.
