### ISSUE TITLE
Blood altar objectives are not what they say they are

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#13987]
### Severity

Round Breaking

### Short Description

Blood altar objectives are not what they say they are

### Reproduction

1. Acquire blood altar objective to suck 163 units of pure blood
2. Begin sucking blood from catatonics to meet it
3. Consume over 200 units over the course of two nights
4. You can't turn it in
5. You can't find out why
6. You become lasombra and can't try out your sick resting place machine because the stupid blood altar objective is still active

7. ???
8. You die to a monster hunter spontaneously crowbarring into the viro lab during a grid check because lol Gaxstation and lmao explorer suit melee armor and rofl predatory lunge charge time and I guess mesmerize didn't want to work and why did I even GET these powers if they're not going to work on anyone until my punches are strong enough to KO anywayyyyyyyyyy

### Round ID

40813

### Test Merges

#13918

### BYOND Username

Sniblet

### Additional information

Does "pure" blood mean "from players?"
Does it need more than it asks for?
Does it break because a day passed?
I dunno there's really no feedback on these dumb things

**Comment by tattax** [comment]
pure blood is indeed from players only

**Comment by tattax** [comment]
they can be braindead though
