### ISSUE TITLE
Earmuffs OP pls nerf

### ISSUE THREAD

**Issue by enailz** [yogstation13/yogstation#1400]
**Expected:**
Wearer can't hear shit, in compensation he's immune to flashbangs/honker blaster.
**What it really does;**
Wearer can hear everything loud and clear while immune to flashbangs/honker blaster, ghetto bowman headset.

**Comment by ShadowDeath6** [comment]
No radio and extremely short supply why don't you git gud grr

**Comment by Cruix** [comment]
Also massive issue for the psychiatrist since he can now actually hear his patients while wearing his earmuffs.

**Comment by enailz** [comment]
> Super3222 added the Feature Request label 5 hours ago

> bug with FR label

wat

**Comment by ShadowDeath6** [comment]
not a bug

**Comment by enailz** [comment]
oh

**Comment by Super3222** [comment]
What Shadow said, but this should still be nerfed / patched by someone.

**Comment by ShadowDeath6** [comment]
no

**Comment by Super3222** [comment]
If someone wants to fix it, go right on ahead. Ignore Shadow.
