### ISSUE TITLE
Make Miners ineligible for rev head

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#1405]
reasons why: 
https://gyazo.com/a11d753436e74509dd87e72d41eb4527

Goddamnit this keeps happening make it stop

**Comment by Dagdammit** [comment]
I was just coming over to make the same request.

**Comment by Super3222** [comment]
Or that same check could not hold up for lavaland?

**Comment by drderp3635** [comment]
No i feel it should just be not miners. If you made the check not make them lose at lavaland they could you know, just be on lavaland and would bassically be immune to loss, not to mention miners are just shitty candidates for rev leaders because all they have acess to is people who don't wanna be on the station, and its very hard to even rev someone in cargo on high pop due to the fact that there is almost always 2 or more people there.

**Comment by Jc1469** [comment]
Just add a popup AFTER the blank notes popup saying "m8 no leave ok thanks"

**Comment by drderp3635** [comment]
Closing cuz pr
