### ISSUE TITLE
Scientists,Virologists, Bartenders, Chemists, Engineers got ORM access without access to ORM itself physically. Maybe more people.

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/Yogstation#1407]
Miners don't have ORM access, why others should? They can't even walk in.

**Comment by MegaEmpirical** [comment]
What do miners even use the stuff for? Also, I can't recall if cargo techs lack access, I feel like they did last I tried and if so that should probably be added so they can give stuff out as needed.

**Comment by Amelia0010** [comment]
>Also, I can't recall if cargo techs lack access, I feel like they did last I tried and if so that should probably be added so they can give stuff out as needed.

They don't
