### ISSUE TITLE
ERT CUMMANDER

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation#1407]
remove the arg boarder rifle for code blue and amber ert and only let the commander have it for code red.

It has 30 clips, it does 35 dmg per shot, it can fire in bursts and automatic and semi-automatic, it downs an unarmored target in 2 shots. Code blue as described on the tg wiki is for all intents an purposes a scouting and diplomacy team at best, Amber shouldnt need super overpowered weapons since they have access to the centcomm armory too. Also might want to remove the gyrojet pistol for the religious specialist.

**Comment by Super3222** [comment]
The religious specialist is practically a gimmicky ERT set to destroy successful cults TBH. I could be wrong about it given that I'm not the one who created it. Hopefully it isn't getting spawned regularly.

I can see what you mean. Red qualifications are for serious situations thus requiring weapons like the ARG. Not amber or blue.

**Comment by AdamElTablawy** [comment]
CC armory is weak as fuck and has nothing useful and ERT is only called in situations where they're hilariously outmatched. 

The issue beforehand was red was the only viable threat-clearing ERT and was a mini deathsquad and blue and amber were fucking worthless.

Hence the PR to buff them.

It's a shitty fucking autorifle. Taze the fucker and kill him. If an ERT is called you've already overrun half the station anyway.
