### ISSUE TITLE
bloodsucker gangrel clan human form can die while in bat form

### ISSUE THREAD

**Issue by Marmio64** [yogstation13/Yogstation#14082]
### Severity

Round Breaking

### Short Description

You can temporally survive sol while in fatbat form as a bloodsucker in the gangrel clan, but upon transforming back you will instantly die without any warning.

### Reproduction

1. transform into batform
2. stay in the sol's rays
3. you are fine without any indication of a problem
4. transform back
5. you are dead

### Round ID

40916

### Test Merges

#13918 , #13684 , #14061

### BYOND Username

Marmio64

### Additional information

I am sure you aren't meant to survive in batform but it also seems weird for you to be able to stay alive up until you transform back and instantly die.

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/14126
