### ISSUE TITLE
ninja mask stuck to hand

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#14092]
### Severity

Round Breaking

### Short Description

It removes one hand from gameplay - this is not a cluwne mask.

### Reproduction

- pick up a ninja mask accidentally.

### BYOND Username

Aquir

**Comment by ynot01** [comment]
This happens when the ninja dies while the suit is "locked"

`ADD_TRAIT(n_mask, TRAIT_NODROP, NINJA_SUIT_TRAIT)`
https://github.com/yogstation13/Yogstation/blob/master/yogstation/code/modules/ninja/suit/ninja.dm#L70

**Comment by tattax** [comment]
intended by original author despite if you find it good or not
