### ISSUE TITLE
Lavaland Seed vault ruin crate is missing it's gatfruit seeds.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#141]
It's in the code, it's in the map dmm file, but apparently doesn't spawn in.

https://github.com/yogstation13/yogstation/blob/acc35586ca50270fb93fe9f701bfe5b5a2cbc1d5/code/modules/ruins/lavaland_ruin_code.dm#L69

**Comment by timkoster1** [comment]
It's not. Every round a random seed spawns there, not necessarily gatfruit. Most likely it's hardcoded to randomize at roundstart.

**Comment by GrayRachnid** [comment]
Oh I see, I misread the code.
