### ISSUE TITLE
i may have caused a crash

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14108]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: so i was blood sucker and took the clan that gets the hertic like portals for power and i had been upgrading no real issues but as soon as I took the one for blanding into shadows the huge ammonut text came up saying that the tenticals where diapearing due to light hundreds of times a secound casuing me immense lag eventally i made it back to the maints but not a mintue after i did the server instently died

 Submitted by: higi (103257154034614272)

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/14126
