### ISSUE TITLE
Xenos spawn are messed up

### ISSUE THREAD

**Issue by Iocanthos** [yogstation13/Yogstation#14118]
### Severity

Round Breaking

### Short Description

Xenos spawn in the open

### Reproduction

Xeno spawns are either missing entirely or someone thought it would be an amazing idea to have the larva spawn in the middle of hallways/botany/rd etc. I havent obeserved a SINGLE xeno spawn in maintenance where it should occur.

### Round ID

40954

### BYOND Username

iocanthos

### Additional information

Needs checking the spawn for xenos if they are present in maints and if so, why they arent working.

**Comment by UselessTheremin** [comment]
which map?
