### ISSUE TITLE
Monster Hunter cucked of its most important ability

### ISSUE THREAD

**Issue by enkidienne** [yogstation13/Yogstation#14111]
### Severity

Low

### Short Description

The "track monster" ability of the monster hunter dosnt work. Its always on cooldown, and when you get lucky and its not, it just dosnt work. You can be on the tile next to a bloodsucker and it will still tell you no monster. 

### Reproduction

1. get monster hunter
2. use ability

### Round ID

40945

### Test Merges

#13684, #14061, #13954

### BYOND Username

enkidienne

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/14148
