### ISSUE TITLE
Bloodsucker candelabra don't check if there is a mindshield before allowing removal

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#14132]
### Severity

Inconvenience

### Short Description

(Feature?) Bloodsucker candelabra don't check if there is a mindshield before allowing removal

### Reproduction

1. Stick a sec officer on a candelabrum
2. Do the thing, 150 blood down, sing him a nice song for 60 seconds or something
3. Whoa! Something spooked you at the very last moment! You move! You're not sure if you finished or not because you were distracted for X reason, but it should tell you if you try again...
4. Try again...
5. Well you can do it again so-- **Blood! You need Blood, now! You enter a total Frenzy!**
6. Calmly finish and vassal him
7. He says in american sign language quote you actually did deshield me the first time and just frenzied yourself for nothing, good luck with that one idiot maybe you should've had a sechud 4head unquote

### Round ID

40820

### BYOND Username

Sniblet

### Additional information

Does it count as roundbreaking if it made me fail an objective once
This also probably shouldn't take the cost upfront if the cost is a lethal amount of bloodloss and the process is extremely interruptible, it's sort of like Lilith's Pact except if you're at a point where you're using a candelabrum you almost certainly have friends around and they will push you

@tattax

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/14126
