### ISSUE TITLE
Someone pranked the warden by pouring copious amounts of glue on his folder & pen.

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#14167]
### Severity

Inconvenience

### Short Description

In the warden's office on yogstation, there is a table on which sits a red folder and a pen.  Some scoundrel has glued these items to the space they are in and now the warden can't move them, nor can anyone else.  The only solution is ACID.

### Reproduction

1. go into wardens office on yog
2. try to move pen/folder
3. fail because glue

### Round ID

N/A

### BYOND Username

Cark

**Comment by VaelophisNyx** [comment]
Should be fixed?
