### ISSUE TITLE
 BS body bags cant hold bodys, fucking discount ass body bags

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14177]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: When a BS body bag is used to pick up a body, any items on the floor get picked up, but the body gets left behind.
https://yogstation13.github.io/demo-viewer/?roundid=41045#46893;116.50;171.50;2;boxta

 Submitted by: ImmortalPlagueRat (605167460450304019)

**Comment by ToasterBiome** [comment]
Fixed https://github.com/yogstation13/Yogstation/pull/14206
