### ISSUE TITLE
 Humans with monkey level blood

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14174]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: When turning a monkey into a human, the monkey retains the amount of blood that it wouldve had previously, rather then ending up with the amount of blood that humans need to survive, leading to the monkey-human dying quickly, making genetics incredibly tedious.

 Submitted by: Wooger (380977604603281408)

**Comment by Altoids1** [comment]
A fascinating result of https://github.com/yogstation13/Yogstation/pull/6437, I think.

**Comment by Altoids1** [comment]
![image](https://user-images.githubusercontent.com/29939414/170610225-d0e9d622-a006-447c-898f-20c7331357de.png)
Could not replicate.

**Comment by Altoids1** [comment]
Should be fixed by https://github.com/yogstation13/Yogstation/pull/14169
