### ISSUE TITLE
Syndicate lavaland base broke

### ISSUE THREAD

**Issue by Iocanthos** [yogstation13/Yogstation#14175]
### Severity

Inconvenience

### Short Description

APCs are all green, equipment on, nothing works

### Reproduction

Spawned as comms agent - could not get out of dorms, had to esword/crowbar my way out.
I got to engineering at the base - nothing works either. APC is on and running. Restarted everything but the devices remained messed up, nothing worked.

ahelped but nobody had an idea what to do - so making a bug report. Could be round specific.

### Round ID

41046

### Test Merges

#13684 #14061 #13954 #14053 #13634 #14085

### BYOND Username

iocanthos

### Additional information

send help cant troll station :<

**Comment by UselessTheremin** [comment]
huh, no clue what couldve caused this

**Comment by Moltijoe** [comment]
hasn't been a problem since a while ago
