### ISSUE TITLE
Gas injector placed in space not accessible

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#1418]
Gas injectors already placed in space, or even new ones placed on the same spot as the pre-start ones all work fine. Any built or moved elsewhere in space fail to bring up the interface menu. Everything worked fine in the station. I tried this multiple times but only during one round.

**Comment by Ratvar** [comment]
Yeah, because they're not being powered.
The station ones have been manually connected to the station's power grid by extending a room's definition into space and so have power

**Comment by MegaEmpirical** [comment]
I see, thanks. Just close this on up then, my bad. I have only recently started doing engineer instead of atmos and never thought of that.

**Comment by Ratvar** [comment]
Snowflake space pipes working with snowflake zones is bad, althought, eh
