### ISSUE TITLE
 veil randomly stops working

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14182]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: as sling veil randomly stopped working, it was glowing on the tab- but when pressed it wouldn't work, i tried restarting but died during it before seeing if that fixed it (extra details: i was spamming the veil button at the time, i also had anti-glow and thick skin from genetics, i was pulling someone)

 Submitted by: purr purr (843557080320442398)

**Comment by Oblisk234** [comment]
Shadowlings no longer exist, see #20581
