### ISSUE TITLE
Nerf Alien Queen spit machinegun

### ISSUE THREAD

**Issue by Trojanplunder** [yogstation13/yogstation#1422]
Yes, this is a "I ded" issue.

The current npc version of the alien queen is OP as hell. Any miner caught in the machinegun spit is downed instantly. 

Hell, I witnessed an alien queen take on a colossus and wipe the floor with it.

Either lower the amount of spits or reduce the damage please.

Edit: Alternatively, make them catch fire in lava. That might balance it out.

**Comment by Super3222** [comment]
This is the (latest) PR that buffed the xenohive.
https://github.com/yogstation13/yogstation/pull/1085

**Comment by Trojanplunder** [comment]
I'm fine with most of the buffs, but miners really cant do anything about that 3-shot spit. All it takes is one moron to lead it back to the mining base and the rest of us are screwed. If a nerf isn't likely to happen, could we add xenos to the lavaland fauna rule about not bringing them to the station? Assuming mining counts as the station, that is.

**Comment by AdamElTablawy** [comment]
That doesn't need to be a rule, trojan. It's griefing, plain and simple, and coders can't change rules anyway.

Also no there's not going to be a xeno queen nerf. She's locked away in a xeno hive and is only intentionally accessible-if you release her and die to her it's your fault for not being prepared. The xeno queen is a mini-megafauna tier boss, so don't fight her with starter gear and expect to win. She has her own arena and everything. If you're upset about being instadunked by the spit, prepare better/smarter for her before opening up her hive and her egg room and trying to fight her. It's the same as summoning legion-you brought it on yourself.

**Comment by ShadowDeath6** [comment]
this isn't a feature request, it's a balancing request

**Comment by Trojanplunder** [comment]
Thanks for the reply on this Adam, since if I recall it was your pr. If I recall correctly the Zeno hive was open to lava and the queen had escaped naturally. If a nerf is out of the question, is there any way to extend the boundary of the "ruin" by a few tiles so that lava can't breach the walls?

**Comment by Trojanplunder** [comment]
Apologies for any misspelling, I'm on my phone at work.

**Comment by Gintoki1** [comment]
From my experience with the Xeno Queen the machine gun spit is completely avoidable and can be kitted easily. Just don't Stand in a straight line and count the time it takes between each shots

**Comment by AdamElTablawy** [comment]
I'm not changing xenos. I might buff them more, but i'm not changing them otherwise.

**Comment by AdamElTablawy** [comment]
xeno queen does not spawn naturally anymore, the simplemob anyway
