### ISSUE TITLE
Positronics (possibly MMIs) in mechs don't count as living beings

### ISSUE THREAD

**Issue by MommaDragon** [yogstation13/Yogstation#14273]
### Severity

Inconvenience

### Short Description

It's... about as simple as it is. Positronics in a Mech don't get "you have survived" text.

### Reproduction

1. Positronic brain possession.
2. Ask (and become) a mech of any type
3. Round end comes
4. Didn't "survive"
5. Anger

### Round ID

#41200

### Test Merges

#14061 , #13479, #14192, #13634

### BYOND Username

TheMommaDragon

### Additional information

This is from most likely a few rounds back, but alongside that, she's currently testing it again (hence the round ID being current ongoing round at time of writing).

**Comment by VaelophisNyx** [comment]
Posis that are put directly into a mech first, also do not get any access rights at all, and no laws.
