### ISSUE TITLE
 Surgery with Anesthetic Internals Does Not Stop Flinching

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14286]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Despite doing surgery on a surgical table, with anesthetic internals on, your patient will still occasionally flinch, doing damage to themselves while you attempt to do surgery. This leads to surgery being done almost exclusively on stasis beds for living patients, because there is no upside to the table compared to the bed which just turns flinching off entirely, and doesn't require anesthetics.

 Submitted by: Vaelophis Nyx (She/Her) (319685669586862087)

**Comment by SomeguyManperson** [comment]
likely caused by #13479

**Comment by Moltijoe** [comment]
auxmos test
