### ISSUE TITLE
AI APC reconnection bug

### ISSUE THREAD

**Issue by ShalaxOfDellios** [yogstation13/Yogstation#14292]
### Severity

Round Breaking

### Short Description

AI cannot force APC back on

### Reproduction

Have your APC shut off.
Attempt to reconnect to it.
 Get all the way 'Recieving control data from APC'
then nothing

### Round ID

41232

### BYOND Username

Shalax

**Comment by ShalaxOfDellios** [comment]
I died because i couldn't turn it back on for whatever reason; a wizard left me for dead in my secondary core

**Comment by Moltijoe** [comment]
outdated with bibby ai rework
