### ISSUE TITLE
Firesuits protects from vaccum as long as you're on a (station) turf and not on a space tile

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/Yogstation#14301]
### Severity

Inconvenience

### Short Description

Normally you should take either pressure or temp damage at a maybe a reduced rate. But as long as you're on a station tile (even if you're surrounded by space tiles) you won't take damage. Tiles built in space won't ignore temp damage.

### Reproduction

1.  Get any firesuit
2.  Get exposed to space/vaccum
3.  Are you on a station turf? No damage.
4.  Are you in space/ freshly made floor tile in space? No pressure damage.

### Round ID

N/A

### Test Merges

#14061: '[TESTING ONLY] Adds lots of ways to mess with batons for +DEV' by JamieD1 at commit 6bfc285858  #13479: 'Auxmos' by jupyterkat at commit c3601a700c  #14192: 'Syringe guns now embed syringes' by nmajask at commit 6ee5bf69bb 

### Additional information

I'm only reporting this because it's a bug that has been around for yeaaars and no one has ever reported it.

**Comment by SomeguyManperson** [comment]
Firesuit protects from pressure damage, the temperature damage of being on a space tile is not present on non-space tiles since an old fix for monstermos prevents temperature regulation on tiles with extremely low pressure

**Comment by Altoids1** [comment]
> Firesuit protects from pressure damage, the temperature damage of being on a space tile is not present on non-space tiles since an old fix for monstermos prevents temperature regulation on tiles with extremely low pressure

Apparently that patch is also in auxmos, since this was during an auxmos test merge.

**Comment by Moltijoe** [comment]
auxmos test
