### ISSUE TITLE
Ashwalker has trouble breathing immediately after spawn

### ISSUE THREAD

**Issue by Firewolf34** [yogstation13/Yogstation#14313]
### Severity

Inconvenience

### Short Description

Ashwalker has trouble breathing immediately after spawn

### Reproduction

Ashwalkers gasp and have trouble breathing immediately after spawn. Medical scanner shows exactly 3 suffocation damage. It does not proceed any further and you do not die over time. However the O2 icon appears and you gasp repeatedly.

**This condition does not occur within the spawn area, only outside the spawn area.**

![image](https://user-images.githubusercontent.com/2159739/171798878-6a2d6dc8-031a-4713-8710-a0b7dd27c939.png)

### Round ID

41268

### Test Merges

The following pull requests are currently test merged: #14061: '[TESTING ONLY] Adds lots of ways to mess with batons for +DEV' by JamieD1 at commit 6bfc285858 #13479: 'Auxmos' by jupyterkat at commit c3601a700c #14192: 'Syringe guns now embed syringes' by nmajask at commit 6ee5bf69bb

### BYOND Username

Firewolf34

### Additional information

I died and tried with a new ashwalker. Situation continued.

There was some explosions at the start of the round in lavaland (I am not certain what caused them), maybe the air was somehow changed? Possibly related to Auxmos?

**Comment by SomeguyManperson** [comment]
likely caused by #13479

**Comment by Moltijoe** [comment]
def auxmos testmerge
