### ISSUE TITLE
 shifty eyes looking into non-living things

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14323]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: apparently you can make eye contact with stuff that shouldn't be made eye contacted with shifty eyes, like, for example, a bottle

 Submitted by: Mecha-phone (201740909279313930)

**Comment by Altoids1** [comment]
lol

**Comment by Altoids1** [comment]
So I think the issue here is not that you make eye contact with literal bottles, but rather that traitors or morphs disguised as items would still be able to make eye contact with you.

I think the problem also extends to invisible mobs.

**Comment by Altoids1** [comment]
As a note, being able to look at objects when social anxious is a feature, not a bug
```dm
// small chance to make eye contact with inanimate objects/mindless mobs because of nerves
/datum/quirk/social_anxiety/proc/looks_at_floor(datum/source, atom/A)
    var/mob/living/mind_check = A
    if(prob(85) || (istype(mind_check) && mind_check.mind))
        return

    addtimer(CALLBACK(GLOBAL_PROC, .proc/to_chat, quirk_holder, span_smallnotice("You make eye contact with [A].")), 3)
 ```
