### ISSUE TITLE
 Mood Bugged?

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14331]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: I was observing and took over for an (admin?) cryo'd miner who was in maints and blind. They had mood enabled for the character. Later on into the shift I went to pet park and utilized pets to boost the mood, it decayed normally. I went to do this again to refresh later and pet an entire pet park of pets, recycled the pet park and did it once more. I could no longer examine the moodlet icon and for the rest of the shift my mood did not seem to decay.

 Submitted by: Tea Love (148960217902743552)

**Comment by SuperTeaLove** [comment]
Confirmed bug. Works every round consistently.
