### ISSUE TITLE
False air alarms

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/Yogstation#14344]
### Severity

Inconvenience

### Short Description

Despite an air alarm saying that the pressure is nomimal, it will still trigger an alert, which can only be cleared by triggering the area alarm then clearing it again.

### Reproduction

1. Air alarm occurs
2. Air gets fixed
3. Air alarm still remains red despite pressure and temp reading fine
4. Screwdriver air alarm, and all is okay again?
![phantom air alarms](https://user-images.githubusercontent.com/17688334/172254130-f3c5eb24-26dc-4b00-b5cf-59d41322f838.PNG)
![airalarm](https://user-images.githubusercontent.com/17688334/172254672-55ba4282-6dbb-432e-bc65-83a61f212cf3.gif)

### Round ID

(Can't remember)

**Comment by ShoziOffical** [comment]
yeah this is very annoying
