### ISSUE TITLE
Rename everything

### ISSUE THREAD

**Issue by enailz** [yogstation13/yogstation#1435]
Port [22011](https://github.com/tgstation/tgstation/pull/22011) from /tg/

**Comment by Super3222** [comment]
Lame.

**Comment by Super3222** [comment]
Let me re-approach this here.

Descriptions in the interactive world of SS13 is like a message from a coder to the player. We right things to guide players, add lore to the game, and to make witty jokes/comments which can be sarcastic, criticize the player, make fun of something, or just have a big laugh. 

Taking that away kinda rips that apart, and throws it into the air like it's confetti.
