### ISSUE TITLE
 Negative Ram

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14360]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: netmin was removing servers to upgrade, and i was running the passive that gave 3 TB ram for 15% of my CPU. He removed both the last server board that had the CPU for said program and the final RAM board (whatever its called), it tried to disable the current programs i was running (the examine upgrade specifically) but due to my lack of RAM, it started to give me negative RAM

no screenshot, but it went to around negative 1750 TBs of ram

 Submitted by: tom. (695086559665324083)

**Comment by Bibby0110** [comment]
should be fixed now
