### ISSUE TITLE
Bloodsucker vanishing act fails under conditions I'm not sure about

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#14370]
### Severity

Round Breaking

### Short Description

Vanishing act doesn't do anything

### Reproduction

**Name: IPHI-GEN
Timestamp: 3 minutes before fourth or fifth sunrise
Emotional state: Very frustrated**

1. This tale begins with a classic setup: being random searched for something someone else did
2. Taken to brig for my flash
3. Insist on paying the fine, sec takes their sweet time repeatedly forensic scanning every innocuous item I own and discovering with shock and horror (maybe?) that I have touched them all
4. Held until sunrise before taking the fine even registers for them
5. Vanishing act!

...vanishing act?

1. Unusual conditions: I'm in cuffs, I'm being moved around to prevent breaking out of cuffs, I'm a preternis
2. Lights aren't flickering
3. I'm not getting a progress bar or any messages to confirm this is working
4. I'm on fire now
5. Nothing continues to happen
6. Crit
7. Ask to be put in a locker
8. On fire, in crit, in a locker, waiting for vanishing act to get me out
9. It doesn't
10. Alert security to the presence of bloodsuckers with my final death, defeated and driven to deadchat passive aggression once again by yet another surprising... feature... of this cursed gamemode

### Round ID

41353

### BYOND Username

Sniblet

### Additional information

The other bloodsucker of the round, Snorts-The-Coke, reports this happening to him too. He said no one else was around at the time.
I love you for porting this tattax but how do you not go insane trying to keep it running

**Comment by warface1234455** [comment]
Happened to me too :(

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/14478
