### ISSUE TITLE
Clown mirophone and adminhelp's replace ' with &#39;

### ISSUE THREAD

**Issue by Badspler** [yogstation13/yogstation#1437]
Title.

Looks like the lexical parser is replacing the single quote (') with (&#39;) instead.

Particularly annoying in adminhelp's.

**Comment by matskuman5** [comment]
I have bad eyes so it replace the single quote with WHAT instead?

**Comment by Dagdammit** [comment]
You type: Don't do that, man.
It shows: Don&39;t do that, man
