### ISSUE TITLE
 Cursed heart rapidly drains blood???

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14387]
## Test Merges: 
Not Supplied / None
## Reproduction:
Cursed heart drains blood rapidly somehow and you don't even recover it if you pump your blood which means if you use grand legion core you just implode if you use it once apparently.

 Submitted by: Sgtdevel (263097655322869763)

**Comment by SomeguyManperson** [comment]
should not be the case, the cursed heart should only remove blood if it hasn't been pumped
