### ISSUE TITLE
IEDs are unpredictable and useless.

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1439]
They used to be useful, now they can take up to 8 seconds to go off or explode in your face and kill you which is useless.

 Just put it back to 3 seconds.

**Comment by ShadowDeath6** [comment]
:^)

**Comment by Super3222** [comment]
Craftable stuff is suppose to be generally crap, but IED's are barely decent crap.

**Comment by Cruix** [comment]
The whole point of IEDs is that they are unreliable and might blow up in your face when you try to use them.

**Comment by 00aquir** [comment]
but they are used with a fuse, no?

**Comment by aphielanis** [comment]
There's no point in including them in the game if they are going to be THAT junky and useless. If you need to remove them then fine but you better also  remove flashbangs from sec because it's unbalance to have one but not the other.
IEDs are supposed to be the antag's counter weight to security's flashbangs.

**Comment by Cruix** [comment]
IED are incredibly easy to make, there has to be some risk involved in using them.

**Comment by ShadowDeath6** [comment]
I like the idea of removing flashbangs.

**Comment by AdamElTablawy** [comment]
IED's are crap, as is, and barely have an effect.
Will buff.

**Comment by 00aquir** [comment]
Basically, have a decent balance between blowing up in hand+self-damage or being not very effective when thrown (more chance) and being able to bomb through a grilled reinforced window (less chance).

**Comment by Frostben** [comment]
IEDs on lance grenades are somewhat useful. It removes the unpredictability involved with activating an IED and also does 20 brute damage from throwing the spear while instantaneously exploding on impact. As for actual damage from an IED i dont know how good it is.
