### ISSUE TITLE
Items blown into lava do not burn

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation#1443]
![glitch](https://cloud.githubusercontent.com/assets/17688334/21412104/817fe22c-c7e5-11e6-9a89-9438789102ef.PNG)

Seems that objects that get tossed into lava by explosions (or at least gibonite explosions) won't burn sometimes

**Comment by ShadowDeath6** [comment]
is ore supposed to burn

**Comment by Notamaniac** [comment]
I've also seen resonators that got blown into lava not burn, it's not just ore

**Comment by Time-Green** [comment]
It's with everything thats gets thrown on lava. Simply pull it on to have it burn.
But yeah, this also works with humans, so its a bug

**Comment by AdamElTablawy** [comment]
tested and functions
