### ISSUE TITLE
 Missing access from Network Admin

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14432]
## Test Merges: 
Not Supplied / None
## Reproduction:
On multiple rounds now I've noticed that if there's a skeleton crew and you gain extra engineering access as a Network Admin, you lose all access to the AI sattelite despite having it when there's a full crew.

 Submitted by: Davos (555869314784428032)

**Comment by ToasterBiome** [comment]
@TheGamerdk

**Comment by VaelophisNyx** [comment]
solved
