### ISSUE TITLE
 Bloodsucker not properly healed while in torpor

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14449]
## Test Merges: 
Not Supplied / None
## Reproduction:
i was badly burned during sol, after sol passed i went back to coffin to heal with spare 600 blood left, when i entered it i was healing me and damaging me for some reasons also i was losing my blood rapidly and entered frenzy and scummbed to death after that

 Submitted by: Bop (407757687334633473)

**Comment by ToasterBiome** [comment]
@tattax

**Comment by Moltijoe** [comment]
was fixed with the buff to torpor and coffin healing
