### ISSUE TITLE
 Ascended predatory lunge for tizimscene bloodsuckers doesnt tear out hearts

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14453]
## Test Merges: 
Not Supplied / None
## Reproduction:
Use dark embrace, ascended predatory lunge, on a dead body, dont tear out the heart, just aggro grab the body normally

 Submitted by: ImmortalPlagueRat (605167460450304019)

**Comment by ToasterBiome** [comment]
@tattax
