### ISSUE TITLE
 preternis are allergic to drills

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14460]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: preternis self surgery does not work with hand drills after the sounds were added, requiring normal screwdrivers

 Submitted by: zealot (343805692710486017)

**Comment by ToasterBiome** [comment]
@nmajask

**Comment by nmajask** [comment]
Doesn't work because drills aren't sharp
