### ISSUE TITLE
 Monkeys can be deep fried infinitely 

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14493]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: when picking up a monkey it becomes an item in your hand, you can then take the monkey and put it in a fryer. Upon frying it and consuming it the monkey body will appear back but you will still regenerate hunger from eating the fried monkey. This can be uses to infinitely eat a fried monkey.

 Submitted by: Neptune (362425279022497813)

**Comment by VaelophisNyx** [comment]
so to comment on this, in private testing I found that: Frying monkeys gives only the nutriment from cooking oil, which is not infinite, and no more efficient than just eating a melon from botany; and that you can grind the fried monkey for more oil. Additionally you can eat a flaming monkey off the oven tray and it ignores being on fire to eat it.
