### ISSUE TITLE
Critical issue: CentComm

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#145]
The AB-USE room appears to have gone missing.

This will severely affect the murderdrone capabilities of numerous members.

# _**FIX IT MAN FIX IT I WANT TO KILL I WANT TO KILL I WANT TO-**_

**Comment by timkoster1** [comment]
This is horrible. I will fix this ASAP

**Comment by timkoster1** [comment]
https://github.com/yogstation13/yogstation/pull/148

**Comment by Super3222** [comment]
What Timato linked.
