### ISSUE TITLE
HoS belt last slot doesn't work

### ISSUE THREAD

**Issue by AJHcHenry** [yogstation13/Yogstation#14508]
### Severity

Inconvenience

### Short Description

HoS belt doesn't hold the last item once you take it out.

### Reproduction

1. Have HoS belt
2. Take an item out (item does not matter)
3. Try to put item back in
4. Will fail

### Round ID

Round #41508

### BYOND Username

AJHcHenry

**Comment by ToasterBiome** [comment]
I think this comes from the belts not checking if their roundstart contents can actually fit into them. A few of the head clothing duffel bags behave in the same way.
