### ISSUE TITLE
More things to do with eyeballs!

### ISSUE THREAD

**Issue by Frostben** [yogstation13/yogstation#1454]
I think eyeballs aren't at the potential they can be at ya know? I think we should be able to pluck eyeballs out individually from a persons skull during surgery, to either replace their eyes with glass or bionic eyes or just to torture them and make them go blind! Also have things get embedded into eyes like a spear or glass shard causing massive amounts of sight damage. I think this would add some cool depth to surgery and opportunities to torture people as an antag doctor.

While we're on the subject of surgery could we also get some makeshift prosthetics? I just had a wiznerd round where there were 4 wizards blasting people apart. They usually lost all their limbs and were left with only their torsos and heads left, when they got revived we either had to use a suicide victim to get the limbs, and even then a few begged us to kill them so they could be cloned instead and not have to wait as long. As for prosthetics maybe a wooden peg leg or iron hook for a hand? Heck maybe someone can make a modular arm where they can attach and replace tools onto it like some weird pirate cyborg thingamaroo.

**Comment by doerakpoes** [comment]
Yes just make the chance of things going into eyes small

**Comment by Frostben** [comment]
Yes of course considering that eyes are quite a small target; also on the subject of eyeballs do we really have anything that can augment eyesight that can be made into a bionic that could be surgically placed into an eyesocket? That would be pretty neat!

**Comment by Stealthkibbler** [comment]
Cybernetic implants are about as close to enhanced vision as you get at the moment. Most notably Thermals.
