### ISSUE TITLE
Clown Mask doesn't appear on self

### ISSUE THREAD

**Issue by ReoDaProtovali** [yogstation13/Yogstation#14551]
### Severity

Inconvenience

### Short Description

Clown mask does not appear on mob while wearing it (blasphemy)

### Reproduction

1. Join round as clown
2. Metastation
3. Go into maints to look for toolbelt
4. Realize your mask isn't on
5. ahelp and get new mask
6. new mask doesn't work
7. Here I am

### Round ID

41547

### Test Merges

#14437 #14466 #14548

### BYOND Username

ReoiteAvali

### Additional information

Oh God my honks are ruined!

**Comment by ReoDaProtovali** [comment]
apparently it had something to do with a bedsheet that went in my head slot instead of my neck slot

**Comment by Oblisk234** [comment]
Can't replicate, sprite is visible.
