### ISSUE TITLE
Ashwalkers need to look like Ashwalkers and not like crew.

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1456]
From the depths of useless mining shit another one comes, Ashwalkers. They can just dress up like normal crew which is a problem.

 Give them a distinctive sprite.
 (or maybe just remove annoying mining all together and use the old system?)

**Comment by Super3222** [comment]
Ashwalkers are meant to sneak in and look like crew. They can't speak english, use machinery, and have very tribal like names. If you find all of these traits in someone (especially if they're wearing bloody mining clothes) than it is more than valid to kill them.

I'm not sure how a distinctive body sprite would help with someone covering up their entire body.

**Comment by aphielanis** [comment]
Can't speak english?  Can't use the machines? Have weird names? Are covered in blood? Well that just describes half the crew!
 Make it so they can't wear people clothes and have to wear very obvious Ashwalker clothes.

**Comment by ShadowDeath6** [comment]
>ashwalkers are meant to sneak in and look like crew

no, they are not.

**Comment by Super3222** [comment]
Okay.. maybe it's a stretch to say that they're _meant_ for that! However, making snowflake checks for clothes they wear isn't going to happen. It's bad for code, and bad for general gameplay.

**Comment by enailz** [comment]
Actually, that's a good idea. Wanna know why? If you're a lizard clown/mime/assistant with theatre access, you can't wear the gladiator suit while wagging your tail, or else...
you
are
valid
salad.

**Comment by Rocks4Free** [comment]
Aren't ass-walkers supposed to defend lavaland? Sneaking into the crew goes against their goals. It's retarded.

**Comment by Stealthkibbler** [comment]
There's a trend on tg where normal lizards are dressing in gladiator uniforms, it leads to lots of validating the salad.

**Comment by Hopekz** [comment]
"Aren't ass-walkers supposed to defend lavaland? Sneaking into the crew goes against their goals. It's retarded." 
The only way to defend lavaland is to get rid of the source to make sure that no more outsiders can be sent. The moment the ashwalkers cause an EVAC shuttle to be called is the moment the AshWalkers win.
