### ISSUE TITLE
 Negative ram

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14572]
## Test Merges: 
Not Supplied / None
## Reproduction:
I was somehow made to have... -1.5k ram capacity and it is constantly lowering
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/989552448832143410/unknown.png)
 Submitted by: Dragonfest (926900485775036427)

**Comment by Gboster-0** [comment]
Fuck you. *proceeds to steal 3K ram from you, requiring you to buy the slightest bit of ram from NT to not be braindead*

**Comment by Gboster-0** [comment]
Also its usefull to note: the round ID was 41569

**Comment by Moltijoe** [comment]
outdated with Bibby's PRs
