### ISSUE TITLE
 pAIs cannot receive pda messages

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14573]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: pAIs that download the digital messenger program can send messages, but they cannot receive messages, any messages sent to them do not go though to them, effectively getting lost to the void

 Submitted by: ☾ MidnightZero ☽ (525377778246484013)

**Comment by Oblisk234** [comment]
Probably fixed by #22671
