### ISSUE TITLE
Robotics fancy labcoat

### ISSUE THREAD

**Issue by Moltijoe** [yogstation13/Yogstation#14581]
### Severity

Low

### Short Description

When worn it doesn't show up and instead just puts the word "suit" in green text behind your character

### Reproduction

Start as roboticist
Use the Robodrone vending machine
get a fancy labcoat from it
wear it

### Round ID

Round#41579

**Comment by VaelophisNyx** [comment]
Cant reproduce this in testing

**Comment by Moltijoe** [comment]
was literally just a one-round issue, was fixed the very next
