### ISSUE TITLE
Change the bluespace shelter direction

### ISSUE THREAD

**Issue by Rafael450** [yogstation13/yogstation#1459]
When when use the bluespace shelter capsule, it shakes and spawns a shelter with its door facing south. I got stuck on lava doing that once.

SOO, my idea is, that when you use the shelter, on that time that it takes to spawn, you are able to click on it again on your hand, so it changes between, North, South, West and East.

**Comment by 00aquir** [comment]
using the direction the player is facing would do the same

**Comment by drderp3635** [comment]
or just don't be a dumbass and place it in a way that would screw yourself over   -_(' _ ')_-

**Comment by Rafael450** [comment]
yeah, i prefer the facing idea, and im always dumbass as miner, soo
