### ISSUE TITLE
Setting for OOC to be disabled during game and automatically re-enabled at round end

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#1459]
Would this be possible? Might help cut down on IC in OOC if people have this option. I know I sometimes forget to re-enable OOC come round end and end up missing a good bit too half the time.

**Comment by ThatLing** [comment]
Should already happen

**Comment by ThatLing** [comment]
https://github.com/yogstation13/Yogstation-TG/blob/master/code/controllers/subsystem/ticker.dm#L197

**Comment by Amelia0010** [comment]
that's global, he means the personal preference.

**Comment by ThatLing** [comment]
That's on you. I'm sure there's people that don't want this.

**Comment by MegaEmpirical** [comment]
Not wanting seems irrelevant as there is no reason for this to interfere with just normally turning it on/off. By the same logic, you wouldn't want/need the global option and admins could just do it manually like players. 

Since there is already a global setting for this, could it not easily be co-opt ed for personal use?

**Comment by ThatLing** [comment]
I have no clue what you're trying to say but from what I understand, this is stupid. I'm inclined to close the PR depending how it's done (if anyone can be bothered to do it that is). If people choose to mute OOC, they don't want it to get unmuted when the round ends (which is arguably the time when most of the shitposting happens). If you want to see OOC at roundend, don't mute OOC or learn to unmute before the round end.

**Comment by MegaEmpirical** [comment]
I'm saying that by saying it's on us, you can say the same thing about it being on the admins to unmute manually. It works both ways. This is a quality of life thing, just a minor improvement. How is this stupid?

That is incorrect. I mute OOC to A) avoid chat being flooded with OOC during the round and B) to avoid accidental IC in OOC (the latter of which there are rules against and accidents occur which may ruin the round, so this may help reduce that), I explicitly want it unmuted at round end and I'm sure others would also enjoy the feature for the same reasons. Muting OOC during the round has clear benefits. Remembering to unmute it after the round is fine and dandy but people forget. Hence why I am suggesting this. Again, it's a small quality of life thing.

**Comment by MegaEmpirical** [comment]
I don't expect this will make any headway so I'll close it.
