### ISSUE TITLE
 Accent is shared across characters in the customization thing

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14590]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: the accent selected is applied to all of your characters, meaning if you want different accents for your characters (or only want one character to have an accent) you have to remember to change it, doubt this is intentional design

 Submitted by: ☾ MidnightZero ☽ (525377778246484013)

**Comment by Oblisk234** [comment]
Going to guess that this was with the old preferences menu, not the one introduced by #17368. I can't replicate this on server, so make a new issue if it reoccurs (I have zero idea how preferences here worked then compared to now)?
