### ISSUE TITLE
remove the gladiator outfit from autodrobe + nerf the roman shield

### ISSUE THREAD

**Issue by enailz** [yogstation13/yogstation#1460]
Super is lazy so let's remove stuff, that's what coders do... right? [I dunno](https://github.com/yogstation13/yogstation/issues/1456).
Jokes aside, please nerf the roman shield from the autodrobe.
It's basically a cheap riot shield that you can obtain by having theatre access + any coin(You can find 3 coins at the dorms).

**Comment by Frostben** [comment]
Speaking about shields, what about the buckler shield that you can make out of wooden planks? I've never seen that thing block a hit is it even working right? And if not then how about a buff since its so crappy

**Comment by ShadowDeath6** [comment]
the roman shield actually got nerfed so it doesn't block anything, unless that was uh, not functional

**Comment by enailz** [comment]
[help me](https://github.com/yogstation13/yogstation/pull/1462)
