### ISSUE TITLE
Bad atmos leak in pipes?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1461]
Oxygen was pumped into Mixed pipes so that it could be pumped into the canisters that contained small amount of BZ gas.. I drained the canisters then I noticed the BZ went backwards into the yellow pipes. Pumps shouldn't allow that...

![ss13-atmospipeleak](https://cloud.githubusercontent.com/assets/16806055/21466866/10c91d1a-c9d8-11e6-9f23-8e4697c4efb9.png)

**Comment by Jc1469** [comment]
possible someone set the oxygen filter to BZ and released some, and it was scrubbed and automatically put in. Or it's just the usual atmos bug. Let's not forget the permafreeze bug, the bugs where atmos just outright stops working, many more.

**Comment by 00aquir** [comment]
Well, the Filtered gas cannot reach the mixed pipes the O2 is pumped into at the bottom right side.
