### ISSUE TITLE
remove abductor instant kill organs

### ISSUE THREAD

**Issue by xbobsherex** [yogstation13/yogstation#1465]
to my understanding these arent even supposed to be here. can we actually remove them already?

theres 3 organs that instant kill you when you get back to station.

**Comment by Super3222** [comment]
Oh god, these are still around?

**Comment by Frostben** [comment]
Dun dun dun!!!

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
can confirm extremely unfun

**Comment by AdamElTablawy** [comment]
removed
