### ISSUE TITLE
When will apostrophes in tickets ever be fixed?

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#1467]
The answer is NO~

**Comment by Notamaniac** [comment]
What&39;s the problem? I can&39;t possibly see how this could even be considered worth fixing, as it&39;s a textbook example of how to sanitize (or whatever other problem it is, not a coder) strings.

**Comment by nichlas0010** [comment]
https://github.com/yogstation13/yogstation/pull/2738
