### ISSUE TITLE
Plasmaman Bloodsucker can't succ

### ISSUE THREAD

**Issue by j8uj8u** [yogstation13/Yogstation#14678]
### Severity

Round Breaking

### Short Description

You can't succ as a plasmaman bloodsucker without removing helmet and catching on fire

### Reproduction

1. Spawn as plasmeme
2. Get picked as Bloodsucker
3. Find some monkeys and a quiet place in maint to get some early blood
4. Press feed button
5. "Your mouth is covered"
6. Take off helmet and mask to succ
7. Catch on fire, major ouch
8. Sadge

### Round ID

Round #41696

### Test Merges

#14466 #14528

### BYOND Username

j8uj8u

**Comment by warface1234455** [comment]
true tur I had to ahelp to become felinid
