### ISSUE TITLE
0G breaks Xenobio cameras

### ISSUE THREAD

**Issue by SynnGraffkin** [yogstation13/Yogstation#14682]
### Severity

Inconvenience

### Short Description

Xenobiology camera doesn't move when there isn't gravity

### Reproduction

1. Move Xenobio camera from default position, preferably in the middle of the room so it isn't against a wall / table
2. Shut down gravity
3. Xenobio camera refuses to move
4. Reconstruct Xenobio console to regain movement

### Round ID

41703

### Test Merges

#14466, #14528

### BYOND Username

BigFatAnimeTiddies

### Additional information

Camera refused to move when gravity came back online, and I tried buckling myself to my chair thinking it was still tied to my 0G movement but still didn't move.

**Comment by VaelophisNyx** [comment]
Cannot reproduce in testing
