### ISSUE TITLE
Spawned without wheelchair on boxstation, and not in medbay as doctor.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14734]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Spawned into round ready, was teleported into hallway in front of psych office no wheelchair.

 Submitted by: Tawaporah Koko (241348083907166219)

**Comment by patpol4** [comment]
needs more details which we wont get as this is a bot submitted bug, maybe try to contact user on discord
