### ISSUE TITLE
The garden [IDEA APPROVAL]

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation#1473]
NOTICE: I am not coding this YET, it's an idea I had in my mind for a while now, and I want to do it once I get better at coding

Basicly:
I want to make lavaland a cave, this wouldn't affect it's playstile so don't worry 'bout that. 
The above ground of lavaland would be a foresty and living planet. The mining shuttle would take the miners here instead of lavaland, and there will be an elevator waiting for them there, wich would take them to lavaland.

The Garden is the name of the area above ground. It has tree's, animals, plants. I am planning for it to have a complete ecosystem. Of course I also made up some monsters, aswell as a few ghost roles; as in a lizard, phytosian and a human, that went back to nature. 
Also, any chasms made there would bring you directly to lavaland, and it would give a  cool beam of light if you were to pass by it in lavaland.

It's a planet, so it has a solid atmosphere, so I am disabling the atmos there, as you can't really affect a whole planets atmosphere amirite?(greenhouse effect joke) So it doesn't consume much processing either.

I am kinda making this issue to make sure people would even want it. This wouldn't affect mining. 
Maybe add some sort of job to it? Tell me if you know one.

Suggestions and critics are appreciated.

Please don't crush my dreams

**Comment by Stealthkibbler** [comment]
In theory, you're just doubling lavalands size are you not? By creating two different z levels for miners to explore and mine on.

**Comment by Time-Green** [comment]
In theory, no
Miners shouldn't really explore there, it's just there. I wanted to make some sort of job for it.

**Comment by Super3222** [comment]
XenoFlora confirmed?!

**Comment by Time-Green** [comment]
Absolutely

**Comment by Stealthkibbler** [comment]
Will there be anything special about it other than being an extra step for miners to getting to mining?

**Comment by Time-Green** [comment]
Yeah, but I am not spoiling that here

**Comment by Frostben** [comment]
This sounds pretty cool! Maybe all the greytide assistants can be sent there to obtain valuables or foods and items for science and the chef?!

**Comment by Rafael450** [comment]
BUT.. BUT..  HOW WILL ASH DRAKES FLY IN A CAVE? Will lavaland be like a GIANT cave? With vulcanos, ashstorms, and stuff like the normal lavaland? I still love the idea.

**Comment by Slinky5890** [comment]
It'd be cool if there were garden-specific ingredients for cooking. Maybe have to take down a megaflora for some silly things like pizza plant seeds. For a job there, I guess there could be an anti-lifebringer who has to hunt wildlife and take down the flora, but with another roles that spawns at the same time who have to defend from the dicks.

**Comment by AdamElTablawy** [comment]
stale, open again if added
