### ISSUE TITLE
 can't drag shit like crate, canister, closet in space anymore

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14786]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: everytime i just try to drag shit in space, move up one tile, instantly stop dragging it very annoying i blame this pr #14751

 Submitted by: Bop (407757687334633473)

**Comment by GraveHat** [comment]
Unable to replicate the exact specifics but I did find something else. You know how moving in space sends both you and the object hurtling through it? If you, for example, move in the opposite direction of where you and the locker are headed then you stop dragging and get sent to different directions. Should also work for anything that can't pass through you as well.

**Comment by warface1234455** [comment]
Bug was happened awhile ago and has been fixed. It was just a code problem that prevent you from dragging shit in floaty environment
