### ISSUE TITLE
 Cloned Abductors lose super lingual matrix and ability to use abductor items.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14782]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: If by chance you get cloned by your scientist as an abductor agent. Then everything for you breaks, you cannot use any abductor item or hear your scientist.

 Submitted by: Rg4 (185114950354731008)

**Comment by GraveHat** [comment]
Can't replicate the cloning thing not giving you a sublingual matrix but they do lose the ability to use any abductor gear that has shove into eat shit from your own weapon protection.
