### ISSUE TITLE
uranium walls only emit radiation when touched 

### ISSUE THREAD

**Issue by pyronie** [yogstation13/Yogstation#14794]
### Severity

Low

### Short Description

uranium walls do not constantly emit radiation, only when interacted with do they emit any radiation

### Reproduction

1.make uranium wall
2. leave it alone
3. see as it does not make any radiation whatsoever
4. walk into or near wall, and suddenly get radiation

### Round ID

41815

### Test Merges

#14466,  #14600, #14582

### BYOND Username

pyronie

### Additional information

was trying to make pluoxium and couldnt because the walls wouldnt emit radiation for the pluoxium to form

**Comment by warface1234455** [comment]
Dude, just make the pluoxium farm near a tritburn

**Comment by pyronie** [comment]
i mean this isnt a atmos only problem, because if you wanted to make uranium walls as traitor but have them hidden they wouldnt work whatsoever.

**Comment by VaelophisNyx** [comment]
Intended iirc, performance issues were solved with this

**Comment by Bibby0110** [comment]
Intentional for performance reasons
