### ISSUE TITLE
Shitty TG things that I don't want, but which i'm bound to keep in till we've been rebased for a week

### ISSUE THREAD

**Issue by Amelia0010** [yogstation13/Yogstation#148]
- [ ] https://github.com/tgstation/tgstation/pull/19144
- [ ] https://github.com/tgstation/tgstation/pull/23699
- [ ] Chem macros

**Comment by ShadowDeath6** [comment]
is this your removal checklist

**Comment by Amelia0010** [comment]
yes

**Comment by Amelia0010** [comment]
but idk what to put here

**Comment by praisenarsie** [comment]
lol what's wrong with removing bats

**Comment by Amelia0010** [comment]
nothing's wrong with removing bats, which is why i'm gonna do it

**Comment by ThatLing** [comment]
Remove ugly new sprites

**Comment by Bawhoppen** [comment]
Sprite reverts are bad and should not happen

**Comment by Amelia0010** [comment]
>Sprite reverts are bad and should not happen

🤔
