### ISSUE TITLE
Mediborgs don't have access to tend wounds surgery

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/Yogstation#14805]
### Severity

Inconvenience

### Short Description

While mediborgs have access to other surgeries, and patch wounds, they don't have tend wounds even if they aim at the torso.

### Reproduction

1. Be mediborg
2. Apply drapes to chest
3. No tend wound surgeries

### Round ID

41824

### Test Merges

#14466: 'Bigger, blacker medbay' by ToasterBiome at commit 7c7913a127 #14600: 'Moves Around a few Admin Verbs' by JamieD1 at commit 201cc8f36a #14582: 'Ports IPCs from beestation' by redmoogle at commit f89b9636d4

**Comment by redmoogle** [comment]
> ### Severity
> 
> Inconvenience
> ### Short Description
> 
> While mediborgs have access to other surgeries, and patch wounds, they don't have tend wounds even if they aim at the torso.
> ### Reproduction
> 
>     1. Be mediborg
> 
>     2. Apply drapes to chest
> 
>     3. No tend wound surgeries
> 
> 
> ### Round ID
> 
> 41824
> ### Test Merges
> 
> #14466: 'Bigger, blacker medbay' by ToasterBiome at commit [7c7913a](https://github.com/yogstation13/Yogstation/commit/7c7913a127012703d698f41a976095290c4b1cd2) #14600: 'Moves Around a few Admin Verbs' by JamieD1 at commit [201cc8f](https://github.com/yogstation13/Yogstation/commit/201cc8f36acae66084c1fdb37bfdbe9d2ebb11da) #14582: 'Ports IPCs from beestation' by redmoogle at commit [f89b963](https://github.com/yogstation13/Yogstation/commit/f89b9636d43687961f12632577b4e07447b01534)
> ### BYOND Username
> 
> _No response_
> ### Additional information
> 
> _No response_

did you try scalpel?

**Comment by Notamaniac** [comment]
> did you try scalpel?

Also doesn't give you the tend wounds option
