### ISSUE TITLE
Unwrenching gas pipe with magboot enabled still sending you fly away!!!

### ISSUE THREAD

**Issue by warface1234455** [yogstation13/Yogstation#14813]
### Severity

Quality of Life

### Short Description

Magboot didn't stop you from getting blown by unwrenching gas pipe

### Reproduction

1. Join round as atmos tech
2. Fill TONS of gas in a pipe
3. Get magboot and enabled it
4. unwrench gas pipe
5. YOU GET SENT TO BRAZIL!!

### Round ID

Round #41833 or every rounds

### BYOND Username

Warface1234455

### Additional information

Unga bunga

**Comment by GraveHat** [comment]
Oops
