### ISSUE TITLE
Mousetraps do not appear to work

### ISSUE THREAD

**Issue by Cartlord** [yogstation13/Yogstation#14838]
### Severity

Inconvenience

### Short Description

Mice can seemingly walk through active mousetraps without harm.

### Reproduction

1. Arm mousetrap
2. Drop
3. Mouse walks in
4. Mouse keeps walking
5. Arm three mousetraps
6. Drop on same tile
7. Mouse walks in
8. Mouse keeps walking

### Round ID

41856

### Test Merges

#14466 #14600 #14582

### Additional information

The mouse did trigger the traps, it just doesn't seem to have done anything.

**Comment by redmoogle** [comment]
```
/mob/living/simple_animal/mouse/proc/splat()
	if(!key) // CKEY
		src.health = 0
		src.icon_dead = "mouse_[body_color]_splat"
		death()
	else
		adjustHealth(rand(7,12))
		if(health <= 0)
			src.icon_dead = "mouse_[body_color]_splat"
```

Intended

**Comment by Cartlord** [comment]
what

**Comment by redmoogle** [comment]
> what

# not a bug
Intended game mechanic

**Comment by Cartlord** [comment]
So it deals 7-12 damage?
How much health does a mouse have?

**Comment by redmoogle** [comment]
> So it deals 7-12 damage?
> How much health does a mouse have?

If its sentient. Also 15hp

**Comment by Cartlord** [comment]
There might be a problem here, then, because I was putting three to five on one tile and the house was walking it off - when, if I read the code there right, it's supposed to deal a minimum of 7 - so either there's a way for mice to get a substantial amount of bonus health, or something's wrong here, since 7*4>15.

**Comment by SomeguyManperson** [comment]
Unless the mouse was cheesed up for bonus health this is wakc
