### ISSUE TITLE
 ipc antenna colour inconsistency

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14853]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: if an ipcs head falls off and they put it back on the antenna are black instead of the colour they had before

 Submitted by: zealot (343805692710486017)

**Comment by redmoogle** [comment]
Replicated

**Comment by redmoogle** [comment]
Fixed and will be pushed.

IPCs antennas are dependent on hair color so I changed it to set the hair color if it has a color
