### ISSUE TITLE
Gaxstation: Cargo doesn't have a deny stamp and mailing doesn't work

### ISSUE THREAD

**Issue by SynnGraffkin** [yogstation13/Yogstation#14865]
### Severity

Inconvenience

### Short Description

No deny stamp and mailing doesn't work

### Reproduction

1. Join as Cargo tech 
2. See there isn't a deny stamp 
3. Try and mail stuff to medbay 
4. Crate just comes back through disposals even after being tagged

### Round ID

41885

### Test Merges

#14466 , #14600 , #14582 

### BYOND Username

BigFatAnimeTiddies

### Additional information

Someone probably needs to go through the disposal pipes and make sure the T sections that are labeled properly for mailing.

**Comment by VaelophisNyx** [comment]
PR is open to fix the mailing

**Comment by SynnGraffkin** [comment]
@VaelophisNyx What is the PR? I'm looking at the current Gax map on Fast and going to point out the issues I can see with mailing. 

Botany and Kitchen mailing pipes go against one another.
![image](https://user-images.githubusercontent.com/6519623/179881419-ff1c9e30-2f06-4efe-917c-83a2b854a360.png)

HoS has no SortType assigned
![image](https://user-images.githubusercontent.com/6519623/179881537-1d39e2d9-40e6-4fb5-9fc0-e642bc94c9c6.png)

Double pipe on the corner near HoS
![image](https://user-images.githubusercontent.com/6519623/179881620-45d2c9c0-07bc-4e0f-8d43-99dfb621db5b.png)

Medbay doesn't have a mail sort and CMO isn't connected
![image](https://user-images.githubusercontent.com/6519623/179881801-05b28e96-7528-46b6-b66a-e70bf884a48a.png)

**Comment by VaelophisNyx** [comment]
https://github.com/yogstation13/Yogstation/pull/14842 waiting on a merge

**Comment by ToasterBiome** [comment]
@VaelophisNyx is this completed?
