### ISSUE TITLE
Warden's disposal bin breaks if you put anything on it.

### ISSUE THREAD

**Issue by Andrymeda** [yogstation13/Yogstation#14887]
### Severity

Inconvenience

### Short Description

Title says it all.

### Reproduction

1. Be warden.
2. Put paper on bin.
3. Watch the pipe right in front of Perma's entrance burst.
![dreamseeker_m5UzQK20ez](https://user-images.githubusercontent.com/109443978/179380314-2c790e77-9b05-4124-937e-2add0d77e44a.png)

### Round ID

41900

### Test Merges

#14466, #14582

### BYOND Username

Andrymeda

### Additional information

It happened twice in the round, as the warden dog got thrown into the bin after a Cluwne skill issue'd me and burst the pipe as well.

**Comment by VaelophisNyx** [comment]
![ss (2022-07-18 at 03 56 56)](https://user-images.githubusercontent.com/1534478/179477622-ce64b52a-a5d5-46b9-9b21-e20690c7e4b2.png)
yep, that'll do it.

**Comment by Moltijoe** [comment]
haven't heard of this problem in a while, probably fixed
