### ISSUE TITLE
[Idea] Rubik's Cubes

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation#1488]
Basically a meme item for psychologist or a traitor item under Pointless Badassery. Clicking a solved cube in hand would scramble it, and doing the same with a scrambled cube would take 5-30 seconds (random) to solve it. Would cause a shit ton of brain damage to anyone in the immediate vicinity when solved. Honk.

**Comment by Frostben** [comment]
i kinda don't like the brain damage part unless its purely for the syndicate operative, otherwise this sounds like a fantastic memetoy

**Comment by ShadowDeath6** [comment]
he does it for free

**Comment by Alek2ander** [comment]
30 year old memes are the best memes
