### ISSUE TITLE
 Mouse (the mob) movement can break.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14899]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Possessed a mouse, and after being "placed on a table" by a player, I could not move anymore.

 Submitted by: Tawaporah Koko (241348083907166219)

**Comment by nmajask** [comment]
Probably caused by not being converted back from being an item into a mob, if so the same issue occurs if someone empties a container onto the floor with a mouse in it.

**Comment by MajManatee** [comment]
skill issue
