### ISSUE TITLE
 ipc/preternis(?) welder bug

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14901]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: welder probably isnt supposed to grow LEGS and KICK ME TO DEATH https://cdn.discordapp.com/attachments/578951348880408600/998320771657113630/unknown.png

 Submitted by: witherc6 (429012660869136394)

**Comment by redmoogle** [comment]
Needs context

**Comment by GraveHat** [comment]
Unable to replicate, attempting to use a welder on a missing limb only attempts to start a surgery.
