### ISSUE TITLE
RCD and anomalies

### ISSUE THREAD

**Issue by spaceboi123** [yogstation13/Yogstation#14909]
### Severity

Low

### Short Description

RCD deconstructed a grav anomaly 

### Reproduction

Be engineer (or shitter greytide) have RCD
find anomaly core (was grav anomaly, I think flux would just shock you)
use deconstruct on it
watch it go brr and deconstruct
Palidus Kane I am looking at you, PLEASE LEAVE MY ENGINEERING DEPARTMENT ALONE YOU KEEP DOING THINGS

### Round ID

41918(?)

### BYOND Username

Billybobdaboss113

### Additional information

I dont know how, but every damn time Kane leaves his department to 'learn' he finds new ways to boggle my nogle. he tried to deconstruct the floor in the SM to stop a delam and hit the grav anomaly in there instead, _and it fucking deconstructed_ ,I dont even know anymore

**Comment by VaelophisNyx** [comment]
could not reproduce in testing.

**Comment by warface1234455** [comment]
> could not reproduce in testing.

same
