### ISSUE TITLE
Unable to revive IPC with IPC revival board

### ISSUE THREAD

**Issue by warface1234455** [yogstation13/Yogstation#14911]
### Severity

Round Breaking

### Short Description

Was dead, and fully repaired, applied IPC revival board, nothing happened

### Reproduction

1. Be an IPC
2. Get EMPED
3. Dead
4. Getting fully fixed
5. apply IPC revival board
6. nothing happens

### Round ID

Round 41927

### Test Merges

#14582

### BYOND Username

Warface1234455

### Additional information

Not sure if intent do with this but admin told me it was a harm intent when using the revival board on the IPC body, meh

**Comment by redmoogle** [comment]
TM wasnt updated
