### ISSUE TITLE
After crash managed to join the shift again-Split Personality.

### ISSUE THREAD

**Issue by TosterIMC** [yogstation13/Yogstation#14941]
### Severity

Round Breaking

### Short Description

After crash i joined the shift even though previously was in it.

### Reproduction

**1.**Was as split pearsonality of catonic player.
**2.**The game crashed from nowhere. _(most likely couse i had newer version of beyond)_
**3.**Dont use the reconnect button but the replay in beyond.
**4.**Click the join game button and chose the job.

### Round ID

#41968

### Test Merges

#14582 #14466

### BYOND Username

Tosterimc

### Additional information

Version of the client: 1585

**Comment by MajManatee** [comment]
Duplicate
