### ISSUE TITLE
 Boxstation Medbay has no blood IVs

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14943]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: There are IV drips in medbay at the start of the round for patients, there is a blood box however.

 Submitted by: Tawaporah Koko (241348083907166219)

**Comment by ToasterBiome** [comment]
https://github.com/ToasterBiome/Yogstation/commit/354fb3c113c993190f34cadf0f6f3987e9eb99b5
