### ISSUE TITLE
Necropolis chests from rune scrimitar dont spawn any loot inside them

### ISSUE THREAD

**Issue by Mantlecrawler** [yogstation13/Yogstation#14942]
### Severity

Inconvenience

### Short Description

When a necropolis chest spawns from the rune scrimmy, no loot spawns inside it

### Reproduction

#1 get rune scrimmy
#2 Kill
#3 Roll necropolis chest
#4 wallow in sadness when you get no gamer gear

### Round ID

#41969

### Test Merges

#14582, #14466

### BYOND Username

Boxta

**Comment by patpol4** [comment]
will investigate if this is a mapping issue

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/15017
