### ISSUE TITLE
Broken lavaland loot cursed heart.

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#1495]
So,uh,i inserted cursed heart from lavaland tendrill loot into myself,clicking with it on my sprite.I was noblood creature,golem.I was pumping it,but it didnt heal me from brute harm at all.
What it meant to do:heal me with manual pumping,making healy abonimation.
What it made:suffering golem who pump unexistant blood into himself and then die cause he cannot even regenerate nonexisting blood.
Add healing properety to lavaland cursed heart?it broken.
Sorry for language,i am russian,kinda.

**Comment by Hopekz** [comment]
Golems don't have a heart. You gave your golem a heart, golem does not have the required body structure to move blood around to make the heart function. Golem died.

**Comment by Ratvar** [comment]
Fix et.

**Comment by AdamElTablawy** [comment]
not a bug
