### ISSUE TITLE
Sauce packets claim they're empty but they're not

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#15028]
### Severity

Low

### Short Description

Filled sauce packest claim they're empty

### Reproduction

Use a sauce packet on something and it will first say that it has transferred the sauce to the food item but then right after that it'll say this:

"You tear open the ketchup pack, but there's nothing in it."

If this was so then nothing would have been transferred.

### Round ID

42061

**Comment by Altoids1** [comment]
What a critical bug
