### ISSUE TITLE
 New armor plates doesn't work

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15027]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: new mk 1~4 body armor plates does not give any protection to wearer at all. Currently It just slows down (or speed up) the wearer. I'm just amazed NOBODY figured this out yet.
이동하기

 Submitted by: hwseo7 (271949665207975937)

**Comment by Mqiib** [comment]
It's because armor is a datum not a list so adding armor or setting armor is a little more annoying. Thankfully there's a proc for that!
