### ISSUE TITLE
 Ore Silo cannot be deconstructed

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15042]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Ore silo doesnt implement default procs for deconstruction (probably should make it do it on the base attackby instead of individual overrides)

 Submitted by: Redmoogle (193500935182352395)

**Comment by redmoogle** [comment]
Btw handling just a reminder

**Comment by MajManatee** [comment]
i hope you have handled it by now
