### ISSUE TITLE
Honkmother Sect is Broken

### ISSUE THREAD

**Issue by Silvore** [yogstation13/Yogstation#15050]
### Severity

Inconvenience

### Short Description

It seems that you cant sacrifice anything as Honkmother sect. It says that you sacrifice bananas, but I cant seem to do that.

### Reproduction

1. Join game as chaplain
2. Choose Honkmother Sect
3. Attempt to sacrifice bananas.

### Round ID

42081

### Test Merges

#14582 #13532

### BYOND Username

Silvorz

**Comment by VaelophisNyx** [comment]
being fixed

**Comment by Altoids1** [comment]
I think this is fixed now?? Maybe???
