### ISSUE TITLE
Cant get favor in honkmother religion.

### ISSUE THREAD

**Issue by TosterIMC** [yogstation13/Yogstation#15054]
### Severity

Inconvenience

### Short Description

I cant instert bananas to the altar.

### Reproduction

1.Chose the honkmother religion using the chaplain book on altar
2.Try to insert bananas
3.It doesnt accept bananas, no other way to gain favor

### Round ID

#42084

### BYOND Username

Tosterimc

**Comment by VaelophisNyx** [comment]
being fixed

**Comment by MegaEmpirical** [comment]
This appears to be a duplicate of https://github.com/yogstation13/Yogstation/issues/15050
