### ISSUE TITLE
Cannot leave the City of Cogs as a ghost if you were a Clockcultist once cultists are summoned to the City

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#15068]
### Severity

Round Breaking

### Short Description

Cannot leave City of Cogs as ghost 

### Reproduction

1) Be Clockcult (I was a scarab)
2) Be dead
3) Cult gets summoned home
4) Ghost you gets summoned as well
5) Ghost is trapped in this hell

Admin note: Admins can fix this by removing the antag datum from user.

### Round ID

42095

### BYOND Username

Lyis

**Comment by Cartlord** [comment]
already open https://github.com/yogstation13/Yogstation/issues/11888

**Comment by MegaEmpirical** [comment]
Ah, I missed that. Thanks.

Closing since this is a duplicate.
