### ISSUE TITLE
Another gag toy, the whoopee cushion. 

### ISSUE THREAD

**Issue by Hopekz** [yogstation13/yogstation#1507]
Sorry for two posts within a day.  

It would be funny / add to the experience if you could get a whoopee cushion and hide it on chairs/seats. All it would do is play a fake sounding/ authentic Nanotrasen fart whenever someone were to buckle themselves into it. This item can be introduced via Cargo crate or mining reward (because miners pranking the shuttle). While the coding to make something happen would be in place, maybe also add a chair trigger. When someone buckles themselves into a chair, it can trigger a pulse similar to a button being pressed. This can be used by traitors for sabotage (bombs) or create arbitrary hidden doors etc. The possibilities are endless!

**Comment by Super3222** [comment]
Why not let the clown spawn with one of these? Just send me some fart noises, and I'll work the rest of the magic out.

**Comment by Alek2ander** [comment]
*fart

**Comment by Hopekz** [comment]
After I get off work (around 8-9hr) I'll give you the fart-iest nanotrasen farts I can find.

**Comment by Hopekz** [comment]
Done, check discord.. Uploaded there.
