### ISSUE TITLE
MONEY!!

### ISSUE THREAD

**Issue by Rafael450** [yogstation13/yogstation#1512]
Guys, i just had an idea. WELL, as you know, we dont use money on SS13, just in some rare cases that we find money as a maint loot, or traitor  case with money that no one cares, BUT, if we make a full credit system, that you can get money, and you can keep it for the next round, i doenst need to be a REAL money system, just some credit that we lose everything if we die before the end of the round. So we make a TOP RANK and stuff, nothing to waste the "money"(but some fancy hats would be really cool), so we increase RP since we are giving people a reason to FEAR DEATH.

**Comment by Super3222** [comment]
If we're going to make a system for money it has to matter to everyone, and impact the round. This is a good thought, but doesn't completely paint the picture

**Comment by Rafael450** [comment]
its just an idea that i had a few moments ago, we can still talk about it, i still want to keep the part that makes the players FEAR DEATH, i dont want assistants that dont give a shit about their lifes welderbombing me as NUKE OP ;-;

**Comment by Hopekz** [comment]
Money does matter..a little bit currently... You get money, give it to cargo, they order shit for you without feeling bad...unless i'm missing something that's really it.

**Comment by Rafael450** [comment]
I mean like a "bank account", that you can carry the money to the next round, and you lose all the money if you die before the round end, and as i said, MAKE PEOPLE FEAR DEATH

**Comment by Hopekz** [comment]
But dying in space station 13 is almost as important as living.

**Comment by Rafael450** [comment]
You know when you really want a unique role, and someone else get it, AND THEY SUICIDE BECAUSE THEY ARE NOT ANTAGS((i used to do this, sorry world))

**Comment by Rafael450** [comment]
Closed by accident

**Comment by ShadowDeath6** [comment]
seems similar to gyb, but what would the money be used for?

**Comment by Alek2ander** [comment]
I wouldn't want to deal with the exponential increase in salt.
"HE KILLED ME 4NORAISIN I WAS JUST PASSING BY NOT HIS TARGET GIB BACK MY 14 BILLION CREDITS OR I DDOS U"
:-1: x 100
