### ISSUE TITLE
Weird ghost bug

### ISSUE THREAD

**Issue by Sabitix** [yogstation13/Yogstation#15140]
### Severity

Inconvenience

### Short Description

I cryod and wanted to spectate the round, logged off waited about 2 minutes logged on and i see everything is blurry

### Reproduction

1. went to cryo
2.  offered body to ghosts
3.  left game and closed byond for 2 minutes
4.  came back and everything is blurry
![image](https://user-images.githubusercontent.com/75314868/182686739-062331f5-b770-4212-bc46-87b2f3156cb9.png)

### Round ID

42162

### Test Merges

14582, 13532

### BYOND Username

Sabiti6

**Comment by 00aquir** [comment]
welcome to the club https://github.com/yogstation13/Yogstation/issues/12132

**Comment by MajManatee** [comment]
byond issue

**Comment by 00aquir** [comment]
@MajManatee what is this byond issue, when players have no problem when they are a ghost, only when they cryopod it happens.

**Comment by 00aquir** [comment]
@MajManatee  What is this byond issue which should be just like ghosting, and it simply only happens when players cryopod?
