### ISSUE TITLE
 Cloning Removes pacifism quirk, and possibly other quirks, and mood.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15162]
## Test Merges: 
Not Supplied / None
## Reproduction:
When being cloned, my pacifism quirk is removed and i can attack again, and player mood is turned off.  This is the only quirk i've noticed but there could be more.

 Submitted by: Tawaporah Koko (241348083907166219)

**Comment by MajManatee** [comment]
happens

**Comment by MajManatee** [comment]
dont be a pacifist mood user
