### ISSUE TITLE
Round ended when there are still zombies

### ISSUE THREAD

**Issue by warface1234455** [yogstation13/Yogstation#15160]
### Severity

Round Breaking

### Short Description

Rev round but there are zombies, headrev dies round ends

### Reproduction

1. Rev round
2. There are zombies
3. headrev dies
4. round ends 
5. zombies are now sadboy

### Round ID

Round #42184

### BYOND Username

Warface1234455

**Comment by VaelophisNyx** [comment]
intended kinda, revs just end the round no matter what

**Comment by warface1234455** [comment]
> intended kinda, revs just end the round no matter what

thats silly even admins were kinda questioning it

**Comment by MajManatee** [comment]
intended
