### ISSUE TITLE
Main AI core on YogsMeta dies Round start

### ISSUE THREAD

**Issue by spaceboi123** [yogstation13/Yogstation#15173]
### Severity

Round Breaking

### Short Description

The Main AI core on the AI sat dies within the first min due to lack of cooling

### Reproduction

Be round start AI (Or late join)
Watch as you get the '[Data core] in AI Chamber is on the verge of failing! Immediate action required to prevent failure.' message and get kicked out to the secondary core
cry (Important step)

### Round ID

42196

### BYOND Username

Billybobdaboss113

### Additional information

Started as AI, core died like as soon as the round started, on meta you cant even access your cooler because its in a 'maint' room on your sat that has no cameras, this kinda is round breaking for AIs as the sat core is, ya know, the safe one. I don't know if maybe AI cores and servers got nerfed by making them run 'hotter', but the AI sat just doesn't have the cooling to handle a core AND the servers anymore.

**Comment by AshCorr** [comment]
Happened to me too.

**Comment by spaceboi123** [comment]
I believe the issue comes from the fact that the AI sat on Meta does not have two coolers, only one, unlike Yogstation which has two. One cooler is not enough to cool the core AND server racks. I also noticed that the cooler round start is not set to the lowest setting, but is set to 80.

**Comment by patpol4** [comment]
appears to have been fixed

**Comment by patpol4** [comment]
actually no
