### ISSUE TITLE
 rev can block lasers while ghosted

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15172]
## Test Merges: 
Not Supplied / None
## Reproduction:
Title explanatory, rev blocks PA rifle aiming laser while being is ghost form. Check Dev-public for the picture I posted

 Submitted by: Cowbot (97736956326207488)

**Comment by MajManatee** [comment]
hmm yes ill check dev public from 8 months ago :clueless:

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/issues/18767
