### ISSUE TITLE
Makeshift 10mm pistol has no mag

### ISSUE THREAD

**Issue by spaceboi123** [yogstation13/Yogstation#15187]
### Severity

Inconvenience

### Short Description

Its got no mag for ammo and shootin

### Reproduction

Be a BB (Or a tot that buys makeshift, but who does that really)
Craft a makeshift pistol
Try to shoot it
it requires a 10mm pistol mag
cant get one as BB
Cry (As normal, a required step)

### Round ID

42203

### BYOND Username

Billybobdaboss113

### Additional information

I mean, pretty simple, there's no 10mm mag for the makeshift pistol, so you cant normally shoot it if you craft it, maybe make a 'makeshift' 10mm mag? Or make it start with one when you craft it? I dunno man, but it IS an issue.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
but there is a makeshift magazine, and you can craft it, its in the ammo tab lol
