### ISSUE TITLE
Odd shuttle behaviour on Gax

### ISSUE THREAD

**Issue by AshCorr** [yogstation13/Yogstation#15189]
### Severity

Low

### Short Description

Shuttle left 30 seconds before it was meant to (not through authorizations), did not actually leave the station,  instantly teleported to CC from the station after the 3 minute transit duration

### Reproduction

1. Shuttle gets hit by a meteor on Gax
2. Time till departure countdown reaches ~30s
3. Shuttle plays the leaving sound and knocks everyone over
4. Shuttle stays at the station
5. 3 minutes pass for shuttle transit
6. Shuttle teleports instantly from the station to Centcomm, no in between space

### Round ID

42205

### BYOND Username

AshCorr

**Comment by ToasterBiome** [comment]
This is a problem with the shuttle subsystem and meteors killing the server

**Comment by patpol4** [comment]
so not a bug, just lag breaking things?

**Comment by ToasterBiome** [comment]
Not a bug. Subsystem lag.
