### ISSUE TITLE
 Changeling Steal Identity obj bugged

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15188]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: "Objective #4: Escape on the shuttle or an escape pod with the identity of Joey Jowers, the Chief Medical Officer while wearing their identification card. Success!" - changeling didn't steal CMO's DNA, didn't appear as CMO, nothing. Had same issue as changeling before.

 Submitted by: Kojuh (239560674517188609)

**Comment by MajManatee** [comment]
Fixed (?)
