### ISSUE TITLE
 Guide Books are broken

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15206]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Guide books open as per normal but then turn into a blank white screen after a few frames, and stay that way.

 Submitted by: Vaelophis Nyx (She/Her) (319685669586862087)

**Comment by Altoids1** [comment]
Might just be an issue with Internet Explorer being bad at rendering the wiki, for some stupid webby reason.

**Comment by MajManatee** [comment]
Duplicate
