### ISSUE TITLE
 Bluespace Harvester Goal Never Completes

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15207]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: While observing this round I saw a completed Bluespace Harvester, but end of round report showed the goal as not complete

 Submitted by: Vaelophis Nyx (She/Her) (319685669586862087)

**Comment by Altoids1** [comment]
![image](https://user-images.githubusercontent.com/29939414/183309917-af3e5d58-55df-463b-b0a6-6b6c6e7f1c48.png)
# Could not replicate.
Note that in order to complete the objective, you need to not only build the thing but also send a lot of power to it.

**Comment by warface1234455** [comment]
You nees to mine at least 45000 points to complete the objective
