### ISSUE TITLE
 Vampire Permasleep

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15218]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: I climb into coffin as Lasombra Phytosian vampire, Sol comes. I enter Torpor and start regenerating Burn damage. I fall into sleep permanently, needing admin rejuvenate to wake up.

 Submitted by: Kojuh (239560674517188609)

**Comment by tattax** [comment]
fixed in bloodsucker prs, not a current problem
