### ISSUE TITLE
 Admin respawning areas bugged

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15223]
## Test Merges: 
Not Supplied / None
## Reproduction:
When admins regenerate areas when bombed or so, plating doesn't get spawned under floortiles
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1006215245750095872/unknown.png)
![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1006215245993353216/unknown.png)
 Submitted by: Kojuh (239560674517188609)

**Comment by patpol4** [comment]
code issue

**Comment by MajManatee** [comment]
Fixed
