### ISSUE TITLE
 Capes are broken bro

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15238]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: They are randomized every round

 Submitted by: N3D6 (315319488767852545)

**Comment by N3D6** [comment]
I may be the only person this happens to but I hate it

**Comment by warface1234455** [comment]
damn bro a unique feature for you

**Comment by MajManatee** [comment]
no longer an issue
