### ISSUE TITLE
 Emagged floorbots don't remove plating

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15231]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: floorbots got emagged by revenant. all they did is remove surface floortiles, leaving intact plating covered in rods. they never touched said plating.

 Submitted by: Kojuh (239560674517188609)

**Comment by Altoids1** [comment]
This is probably a bug with `/turf/proc/ReplaceWithLattice()`, rather than with the floorbot itself.
