### ISSUE TITLE
 invis admin/deadmin breaks visible antagonist observe for ghosts

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15248]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Orca Orca is a changeling. They are also an admin. They can't be followed from ghost observe menu, can't see there's a ling to observe.

 Submitted by: Kojuh (239560674517188609)

**Comment by redmoogle** [comment]
Likely invismin

`code\__HELPERS\unsorted.dm:290` contains code to skip a POI if invisminned and the ghost orbit uses that to get people

**Comment by adamsong** [comment]
Confirmed stealthmin, working as intended
