### ISSUE TITLE
 Donochat is very broken

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15277]
## Test Merges: 
Not Supplied / None
## Reproduction:
It cannot be seen by donators
Admins at least are not given the verb (They can see it though)

 Submitted by: adamsogm (177073258716200961)

**Comment by adamsong** [comment]
![image](https://user-images.githubusercontent.com/4607006/184417285-470db6b7-7e0b-4e9b-b44a-0e301b14a980.png)
No donator tab
GLOB.donators is a list of ckeys, you cannot send chat messages to ckeys

**Comment by Datt1234** [comment]
_ [](url)in

**Comment by redmoogle** [comment]
Should be fixed

**Comment by ThatLing** [comment]
I'm gonna assume this is fixed
