### ISSUE TITLE
 broodmothers spawning broodmothers spawning broodmothers

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15280]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: i triggered a Spider infestation event and many of the spiders that were spawned were, or had. brood mother abilities (cocoon, eggs, speak to offspring) and then those eggs would have the same abilities

 Submitted by: Gaminada (149238977608548353)

**Comment by MajManatee** [comment]
sounds intended
