### ISSUE TITLE
lots of adminlogs are missing

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#153]
okay so

the adminlogs for 'X has opened a canister of (contents) at (coordinates) is missing

the (plasma pump removed/unwrenched) shit is missing

the (x used a slime reaction) is missing

chemistry logs for creating CLF3/blackpowder/Potas/water is missing

priming a grenade is missing

setting off a fueltank explosion is missing

firing a flamethrower is missing

turning PA on is missing

crates being ordered and shipped (virus and Supermatter crates and such) are missing

**Comment by GrayRachnid** [comment]
PA logs are not missing.
flamethrower logs are not missing.
fueltank explosion is not missing.

I've seen all three.

**Comment by EMT321** [comment]
@Cruix @Adameltablawy Can this be closed? I've seen all the aforementioned logs.
