### ISSUE TITLE
Roboticists don't have Research Lab access on Box.

### ISSUE THREAD

**Issue by SynnGraffkin** [yogstation13/Yogstation#15302]
### Severity

Inconvenience

### Short Description

Robos lack access to Research lab

### Reproduction

1. Join as Roboticist without skeleton crew access
2. Try to go into Research lab since #15091 
3. Don't have access

### Round ID

42319

### Test Merges

#15195

### BYOND Username

BigFatAnimeTiddies

### Additional information

Roboticists have access on Meta to the Research lab, but with the #15091 change on Box, they don't. 
Roboticists need access to print off materials that aren't accessible from their lathes, such as capacitors and scanners.

**Comment by ToasterBiome** [comment]
Doors removed, no longer applicable
