### ISSUE TITLE
adamantine free golems cant do research, also likely not the mech fab

### ISSUE THREAD

**Issue by wonderinghost** [yogstation13/Yogstation#15305]
### Severity

Inconvenience

### Short Description

started round as free golem and tried to research, got access denied, likely going to be the same with the mech  fab

### Reproduction

access the rnd console and click on a research tab

### Round ID

42329

### Additional information

likely by the mech fab change

**Comment by Datt1234** [comment]
Change bi fab

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Partially solved by #15324
