### ISSUE TITLE
BYOND's downloading WHILE playing ???

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1531]
...and it's not enough that - when the game is downloading the cache again without any warning - it constantly lags, it basically STARTS when you JOIN the game, and suffer through the round. I got 20-second Complete freeze 2 times, when the game couldn't display anything else while you tried to move around.. completely ruins the round if you have to fight somebody, especially fun when it freezes but you hear yourself opening doors when you try to get away from an environmental danger. The hell happened to the download-before-playing method?
And the game cleared the cache of 48MB, even after playing a round it's around only 30 now... not fun when it freezes every time you try to do a new thing that comes with sounds.

**Comment by 00aquir** [comment]
and the game cleared cache of 47MB, even after playing a round it's around 30... not fun when the game freezes every time you try to do a new thing what comes with sounds.

**Comment by Time-Green** [comment]
It'll be a matter of time till the plebs realize it's fake downloading and we're actually hacking their PC
