### ISSUE TITLE
Russian Golems

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#15315]
### Severity

Round Breaking

### Short Description

Considering everything Russia does and stands for this is unacceptable

### Reproduction

Have some XXXXXXXXX admin XXXXXXXXX invoke Russian golem

### Round ID

42334

### Test Merges

dont know

### BYOND Username

Aphielanisn

### Additional information

Some of us(the smart ones) can't stand Russia and want anything that promotes Russia removed. I'll also raise hell with anyone who tries to say we should keep it because they're promoting war crimes.

**Comment by LoliconSlayer** [comment]
![image](https://user-images.githubusercontent.com/54045237/184575789-a428018b-c0c5-4eec-9831-24474dadc8de.png)

Take your pills

**Comment by isotope436** [comment]
SO THIS IS WHAT A SCHIZO MELTDOWN LOOKS LIKE :D

**Comment by VaelophisNyx** [comment]
as someone violently anti-russia rn


LOL
LMAO

**Comment by Bibby0110** [comment]
It’s a video game

**Comment by AshCorr** [comment]
> Some of us(the smart ones) can't stand Russia and want anything that promotes Russia removed. I'll also raise hell with anyone who tries to say we should keep it because they're promoting war crimes.

Lets not forget that its the russian **state** that is perpetuating the invasion of Ukraine and all of the other batshit insane stuff happening in Russia. A large part of general Russian population are either anti-war/anti-putin or have been brainwashed by propaganda, by cancelling the very idea of being Russian we're alienating innocent people and proving the point that Putins propaganda is trying to make.

Also most references to Russia and Russians in our codebases tend to be jokes or caricatures, I fail to see how they promote Russia.
