### ISSUE TITLE
 Cannot Purchase Build your own Shuttle, haven't met requirements.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15341]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Upon trying to purchase the build your own shuttle, I was met with the error of "You have not met the requirements for purchasing this shuttle." At the time of purchasing, we had 80k credits, but was unable to call it. Admin is unable to do it either.

 Submitted by: Zer0 (412038981669355560)

**Comment by redmoogle** [comment]
Non-bug you need to buy it before the 20 minute mark

**Comment by Zer0Tactics** [comment]
Time limit seems to be extremely short, engineering takes 10-15 minutes to get situated and get set up alone, could this time be increased to 30 minutes?
