### ISSUE TITLE
The mining medic job still exists

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#154]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by Super3222** [comment]
This is going to be fixed in my next PR.
In the future they will be revamped to become the recovery agents of lavaland.

**Comment by Super3222** [comment]
This is going to be fixed in my next PR.
In the future they'll be revamped to become the recovery agents of lavaland.

**Comment by Super3222** [comment]
#163
