### ISSUE TITLE
Byond 514.1569 has issues with interfaces

### ISSUE THREAD

**Issue by redmoogle** [yogstation13/Yogstation#15402]
### Severity

Development Issue Only

### Short Description

Interface doesnt work when not fullscreened and you only get the map itself

### Reproduction

be on mentioned bersion
Not have the game fullscreened from before (or use another screen)
Cry as you can only see the map

Can be fixed if fullscreened
1571 doesnt seem to fix it

Would suggest trying to update extools compatibility
Just here for nothing and fixing

![unknown](https://user-images.githubusercontent.com/20369082/185770614-447ea37b-a802-40ef-b0b7-8ada52f93c16.png)

### Round ID

N/A

### Test Merges

N/A

### BYOND Username

Redmooogle

**Comment by Bibby0110** [comment]
byond issue
