### ISSUE TITLE
barkeep autolathe crashes

### ISSUE THREAD

**Issue by wonderinghost** [yogstation13/Yogstation#15416]
### Severity

Inconvenience

### Short Description

when selecting the autolathe's misc tab in the space bar causes the autolathe to crash when clicking to other tab

### Reproduction

unlock the autolathe recipes (blue light)

use the autolathe

click on misc tab and see tab fill with tinfoil hats

click on any other tab

### Round ID

42440

**Comment by MajManatee** [comment]
fixed
