### ISSUE TITLE
 Mesons not preventing SM hallucinations and time broken

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15427]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Its happened multiple times now but I have noticed mesons not protecting me from having SM hallucinations. Also the time got really fucked up and would freeze, then jump forward every few minutes

 Submitted by: forhiti3 (294599429996937227)

**Comment by MajManatee** [comment]
dupelicate
