### ISSUE TITLE
Better better money 

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#1542]
Because I don't like KMC's money idea.

So, here's how it works.

Everyone's ID has a PIN number attatched, stored in their memory.

Crewmembers can use an ATM machine scattered around the station to withdraw physical money, but that isn't necessary. To use an ATM, swipe your ID card and enter your PIN.

Money would have numerous uses.

First off, money can be inserted into vending machines-public ones-To purchase the items in them. Or the crewmember can enter your PIN to purchase items, subtracting directly from their bank account.

The other use is, fairly obviously, putting them in the cargo shuttle for a minor cargo points boost. 

Otherwise, money retains it's normal use for personal values.

For example of what I mean-public nanomeds, clothing vendors, etc-put money in, purchase items that are of a certain value.

There could be random traders scattered around on other zlevels-sort of like that 'trading station' in lavaland-where you can give money to them for certain items, or whom will buy items in exchange for money.

Every job will start off with a certain amount of money in their bank accounts per round. The higher ranked the job, the more money in the account.

Every ten minutes, money is gained by those jobs. It's set at a certain value, but the Captain can modify how much each job gets. The higher the rank, the higher the wage. All heads except the Captain have the second highest wages on the station. The Captain gains the most per.

The captain has a 'station funds' computer, essentially a private laptop, that allows him to manage funds. The HoP has one as well. He can see how much money everyone has in their bank accounts, and how much they are paid each time funding comes in, and modify it. To be specific, he can withdraw funds directly from their bank account to add it to the station funds, or add station funds directly to their bank account. He can also set how much they are paid.

He can also suspend the station funds, meaning nobody gets paid until re-enabled. This triggers a stationwide announcement.

Most importantly, he can TRANSFER budgets. The station funds is essentially the main pool from which money is drawn to pay crewmembers. But the Captain can choose how much of the station funds go to the payroll, and how much goes to the cargo budgeting. Cargo points would essentially be the budget, allowing the Captain to add points to cargo from the station funds, or remove cargo points and turn them into station funds to add to the payroll (or not).

To give a layout of how this works-

Assume there are 10,000$ in the station funds, gained every ten minutes. Then, after the initial adding, the amount assigned to the payroll is removed from the 10,000$ and inserted into crewmember accounts. The amount added to the cargo budget is also subtracted and added to the cargo accounts.

A special computer in the vault would allow crew to withdraw funds directly from the station funds themselves. Hence, a theoretical breakin may occur into the vault, using the computer and draining the money from the station funds, turning it into physical space cash.

At the end of the round, the total amount of money in the station funds would be tallied up, and the station would recieve a grade on the amount of money in the station funds, from F to A+. Then a 'richest crewmember' would be checked, whomever had the most money in their account.

This system essentially allows Cargo to make a profit for the station-getting a massive surplus of points, which are added to the station funding total-via trading stocks, or selling minerals and important supplies. Additionally it means that ordinary crew would have a non-obtrusive, logical, use for money that doesn't revolve around meme cancer shit like the clerk which is a horrible job that I plan to remove at the earliest opportunity.

The AI, of course, can also interact with station funds through the computer. Admins can also modify station funds and crew payroll if needed.

A theoretical traitor objective would be to steal X amount of money, meaning that they would have to use the vault console or station funding computer to withdraw massive amounts of money from the station. Certainly no harder than 'steal a hand tele.'

Finally, a theoretical use for station funds themselves rather than going into payrolls or cargo would be the ability for the Captain to purchase certain things for certain prices. Upgrades for the station, possibly different shuttles (since numerous different shuttles exist in the maploader and /tg/ has a system for buying different shuttles, this wouldn't be hard to do). Possibly requesting a mercenary team for a large amount of money-sort of like flinging a cash-wrapped distress beacon into the dark, allowing for the request of mercenary aid to accomplish an objective written in the prompt. Meaning that yes, the Captain can purchase a mercenary team in an emergency with an objective he wrote for them in the prompt, or for a particularly wealthy traitor to purchase a mercenary team to help him with his objectives. This theoretical mercenary team would be a ghost role that spawns with a 30 second prompt, on the mercenary base stealth designed (but on the centcomm zlevel). And arrive on the station in a special shuttle.

**Comment by Rafael450** [comment]
We can add some traitor items for that, for example, an item that you attach with the ATM board, that transfer's a % of the money that people deposit and withdraw on that specific ATM,  a Black market random event would be fun too

**Comment by AdamElTablawy** [comment]
no, no,  and no

**Comment by Ratvar** [comment]
What to do with money tree?Remove,then?To easy to generate spess cash.And any method to transfer mineral coins into ATM or something?

**Comment by Zostroll** [comment]
Umm cargo gets an absurd amount of cargo points if someone good is on stocks like dzlan also there are tons of ways to get absurd cargo points through cargo like money trees, corgi farming, selling minerals etc...

**Comment by AdamElTablawy** [comment]
Yes, Zostroll.

**Comment by Kmc2000** [comment]
Could work yah, add in my clerk's trade station as a general machine, where you swipe ID and insert items and set price to set up your own little shop.

Then people can buy from any crew member's shop they want. Etc.etc.


Atm skimmer should be as i modelled, place on atm, every card used has their pin stolen and you can retrieve it by detaching the skimmer and reading it (so ANYONE can use them)

**Comment by Frostben** [comment]
it'd be neat to see something the miners can buy from their vendors that is really useful and expensive which could prompt them to auction off stuff from lavaland to the highest bidder in order to get the funds to buy it.
