### ISSUE TITLE
Depowered blastdoors not openable,bug

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#1543]
OOC: ClaudeWicked: also why did they make it so you can no longer crowbar de-powered blast doors?
OOC: Adam El-Tablawy: you still can crowbar depowered blast doors
[Admin] OOC: Zostroll: No you can't
[Admin] OOC: Zostroll: Cause it stopped working after the rebase...
OOC: Adam El-Tablawy: then, claude, that is a bug
OOC: Adam El-Tablawy: and i reccomend reporting it on the github
He couldnt do it,so i will.
Blastdoors are supposed to be openable with crowbar when depowered,but we lost it after rebase.
Make blastdoors weak again.

**Comment by Time-Green** [comment]
This is very much possible.
I think I know what happened.

If a door gets depowered, the door bolt lights go off. So the door was probably bolted, hell he couldn't crowbar it open.

**Comment by ShadowDeath6** [comment]
Blast doors don't have bolts, they're blast doors

**Comment by Time-Green** [comment]
OH THOSE, SHIT

**Comment by nichlas0010** [comment]
fixed in #1632
