### ISSUE TITLE
 can't scroll down horror menu

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15461]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: I open mutation menu, see abilities from Grow Tentacle to Spill Lube. See no scroll thing. Can't use down buttons to scroll either.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1012440217820598294/unknown.png)
 Submitted by: Kojuh (239560674517188609)

**Comment by Bibby0110** [comment]
Unable to reproduce due to lack of issue description. Horror menu scrolls fine normally
