### ISSUE TITLE
 Darkspawn Progenitors can Progenitor again infinitely. Also, Progenitoring doesn't end round.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15462]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Title.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1012499869048524881/unknown.png)
 Submitted by: Kojuh (239560674517188609)

**Comment by MajManatee** [comment]
Half intended, half resolved
