### ISSUE TITLE
 Multiple menus not scrollable

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15478]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Same issue as Eldritch Horror menu not being scrollable, but with more menus: Darkspawn evolution menu, Decal Painter menu, etc.

 Submitted by: Kojuh (239560674517188609)

**Comment by Bibby0110** [comment]
Not enough details to reproduce. Decal painter for one works fine
