### ISSUE TITLE
Can we implement the Separated Chemicals plant gene

### ISSUE THREAD

**Issue by Dagdammit** [yogstation13/yogstation#1547]
Apparently it's in the current code base, just no plants have it. I'd say give it to citrus plants? (Lemons, oranges and limes)

**Comment by ShadowDeath6** [comment]
What's it do

**Comment by Dagdammit** [comment]
Makes it so reagents in a plant don't mix upon harvest. (Those in plants which also have liquid contents SHOULD mix upon going splat, dunno if that will require additional code)

Right now if you make tomato smoke grenades or whatever you just get a giant smoke cloud the moment you pluck them.

**Comment by AdamElTablawy** [comment]
code for it is nonfunctional, also leads to potas/water tomatoes or whatever, so
