### ISSUE TITLE
 Access kit not working?

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15477]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: I don't know if I fucked up or what, (ign Patton Wright) as infiltrator I bought an access kit for engineer, applied it to my ID but it seemingly did nothing whatsoever, didn't have any engineering access at all for the rest of the shift

 Submitted by: Davos (555869314784428032)

**Comment by MajManatee** [comment]
Not a supported game mode
