### ISSUE TITLE
Freeze command for admins

### ISSUE THREAD

**Issue by ghost** [yogstation13/Yogstation#1548]
The freeze command for admins was incredibly useful especially for people who may be new and are ignoring ahelps.  Please re-add it.

**Comment by GuppyLaxx** [comment]
use admin jail you gay baby

**Comment by ghost** [comment]
IT'S NOT THE SAME AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH

**Comment by Kmc2000** [comment]
use admin jail you baby who likes other men

**Comment by ThatLing** [comment]
Afreeze was really useful so I'll look into it

**Comment by ThatLing** [comment]
Okay turns out afreeze code is actually horrible

**Comment by Ktlwjec** [comment]
Closing this as we have afreeze now.
