### ISSUE TITLE
No snowflake suicide

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#1550]
Ayyliens have no special suicide with advanced baton or any ayyequpement,they should have their special scientific snowflake sudoku.

**Comment by Kmc2000** [comment]
'Unknown inserts the science tool into his ass...is he probing himself?'

**Comment by Frostben** [comment]
"the fleshy mass violently expands blowing him up into a shower of gibs"

**Comment by Dagdammit** [comment]
"Unknown opens up his chest and starts removing their organs one by one. How the fuck?"
Ends with a husk under a neat pile of abductor organs and no blood whatsoever.

**Comment by Stealthkibbler** [comment]
Fun fact abductors only have appendixes

**Comment by Dagdammit** [comment]
Just a neat pile of half a dozen appendices.
