### ISSUE TITLE
 New PDA script error

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15508]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: When attempting to click on my own name in the sent messages log after I had already changed my PDA alias to something else, the following error came up:
Script error. at https://cdn.yogstation.net/assetcache/asset.b2f762b1c0d4462baf876921d490a79f.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; Zoom 3.6.0)
State: {"ckey":"sirdavosseaworth","interface":"NtosPdaMsg","window":{"key":"[0x2100f59e]-main","size":null,"fancy":1,"locked":0}}

 Submitted by: Davos (555869314784428032)

**Comment by ynot01** [comment]
#15507
