### ISSUE TITLE
Re-add export notes button

### ISSUE THREAD

**Issue by ghost** [yogstation13/Yogstation#1550]
It made it much easier to just hit the export button and copy paste that bitch but now it's gone into the aether.

**Comment by ThatLing** [comment]
This'll require some extra work to correctly process secret notes.

**Comment by Altoids1** [comment]
Now basically resolved by
https://github.com/yogstation13/yogbot/blob/master/models/Discord/Commands/DiscordCommandNotes.js

So I'm closing this.
