### ISSUE TITLE
Hacked Autolathe issue

### ISSUE THREAD

**Issue by SegaCD** [yogstation13/Yogstation#15516]
### Severity

Inconvenience

### Short Description

Hacking an autolathe fills up the misc tab with an ever growing number of tinfoil hat buttons

### Reproduction

1. hacked autolathe by cutting wire
2. selected misc tab
3. an ever growing number of tinfoil hat options show up

### Round ID

42561

### Test Merges

#15031 #14709

### BYOND Username

Roromonster

**Comment by tattax** [comment]
@redmoogle

**Comment by redmoogle** [comment]
> @redmoogle

Nonissue w/ new pr
