### ISSUE TITLE
 gunlight mitosis

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15620]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: miniature energy gun grows a second seclite on the sprite when you toggle its already existing gunlight which i dont think you can detach
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1016068001340080188/unknown.png)
 Submitted by: zealot (343805692710486017)

**Comment by MajManatee** [comment]
uh intended i think...?
