### ISSUE TITLE
Extools doesn't seem to be working/loading on 514.1585.

### ISSUE THREAD

**Issue by sergeirocks100** [yogstation13/Yogstation#15639]
### Severity

Round Breaking

### Short Description

Extools doesn't seem to work/load.

### Reproduction

1. Compile the code in the latest version of BYOND.
2. Start it in the latest version of Dream Daemon, with security set to Trusted.
3. It pops up a window saying "Failed to locate ToString", and it shits out a lot of division by zero atmos runtimes, consistent with what i saw on Citadel when i ran it on a BYOND version that Extools didn't work under.

### Round ID

Not applicable.

### Test Merges

Not applicable.

### BYOND Username

sergeirocks100

### Additional information

I tested again with a fresh clone of the repo and a fresh .zip copy of BYOND from the website, just to make sure the issue wasn't on my end, and it still didn't work.

When i compiled and ran it under 1583, it seemed to work fine.

**Comment by Bibby0110** [comment]
We recommend using 1583
