### ISSUE TITLE
Hats and IPCs dont mix well

### ISSUE THREAD

**Issue by redmoogle** [yogstation13/Yogstation#15635]
### Severity

Low

### Short Description

Screen is slightly to big for hat

### Reproduction

![image](https://user-images.githubusercontent.com/20369082/188511610-15009754-4892-48a4-a91a-6f8bae275254.png)
![image](https://user-images.githubusercontent.com/20369082/188512182-be1f1283-ad22-4a06-bb89-6b6f421fa064.png)

Screen needs to be shifted down 1 heads might need to be adjusted

### Round ID

N/A

### Test Merges

N/A

### BYOND Username

Redmooogle

**Comment by MajManatee** [comment]
wont be fixed. clipping exists unfortuatley
