### ISSUE TITLE
robotics can research but not on scientist rnd console

### ISSUE THREAD

**Issue by wonderinghost** [yogstation13/Yogstation#15659]
### Severity

Inconvenience

### Short Description

the rnd console 

### Reproduction

be a roboticist
go to the rnd console where the protolathe is 
try to research on it
get accessed denied

### Round ID

------

### Additional information

likely from the exofab gate keep merge, this is an inconvenience and is very dumb, cause if the robotics console is gone and the scientists are dead or mia then its a spell for bad luck

**Comment by ToasterBiome** [comment]
Intended for some reason
