### ISSUE TITLE
 IPCs do not get placed in cerulean clone bodies automatically & Color bug

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15698]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Cerulean cloned IPCs have null colors I assume as they are solid black, and when cloned this way their mind ghost does not auto-return to their body like other revival methods.

 Submitted by: Vaelophis Nyx (She/Her) (319685669586862087)

**Comment by MajManatee** [comment]
intended
