### ISSUE TITLE
Bo staff has 100% block chance on everything.

### ISSUE THREAD

**Issue by halueryphi** [yogstation13/yogstation#1571]
Bo staff blocks everything 100%. Tasers, crowbars, stun batons, thrown weapons, pushing them, you name it.

https://i.gyazo.com/thumb/1200/_b722a32013d6c353649c5095922204e5-png.jpg

Steps to recreate this bug:
1.Shoot at someone with a bo staff.
2. Witness true power.

**Comment by Cruix** [comment]
Already a PR to fix it

**Comment by ShadowDeath6** [comment]
Give eshields the ability to block everything pls
