### ISSUE TITLE
Rotatium sends ping over 1000s

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#15731]
### Severity

Round Breaking

### Short Description

Rotatium transforms movement into - very - still images.

### Reproduction

Round [42771 1:41:35 replay ](https://replays.yogstation.net/?roundid=42771#60902;145.50;135.50;2;aquir;0.0)

- 1:41:35 at med foyer a reported vampire shoots Lincoln Whiteman (me) with some rotatium and after a while sends my ping into even the 2000-3000s.

- I remove the beartrap and move again at 1:42:20.

- At that moment I would like to go to med (or at least in one direction), but it becomes so bad that the game won't update what's happening for several seconds, constantly.

- 1:42:20 - 1:44:12. Between these two times, the movements that you see from Lincoln Whiteman, were just still images for me and after a while I'm barely getting an updated image for seconds. If you think you see me standing around, that's when I don't get a normal visual update about what's happening. Movement, standing, they were ALL still images with huge delays.  It ends at 1:44:12, because it becomes so bad that I temporarily disconnect and reconnect.

- Admin said it is a byond bug, and I should make a bug report.

- I don't think that I've seen anything that can simply stop the gameplay like this chem.

### Round ID

42771

### BYOND Username

Aquir

**Comment by ShoziOffical** [comment]
it made a blackscreen too aye?

**Comment by 00aquir** [comment]
it's just that whatever you did, the game started to show seconds later, and became unmanagable

**Comment by ShoziOffical** [comment]
> it's just that whatever you did, the game started to show seconds later, and became unmanagable

Yeah that happened to me too

**Comment by ShoziOffical** [comment]
https://github.com/yogstation13/Yogstation/issues/14705#issue-1293748185

**Comment by MajManatee** [comment]
Not an issue anymore
