### ISSUE TITLE
People with self-respiration take brute damage when in crit

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#15748]
### Severity

Inconvenience

### Short Description

People with self-respiration take brute damage when in crit

### Reproduction

1. Self respiration
2. crit
3. brute damage

### Round ID

Any

### Additional information

I think this is intended to happen on a racial basis, but if it happens with self-respiration isn't that punishing people for having a beneficial virus

**Comment by Moltijoe** [comment]
intended
