### ISSUE TITLE
Space Adaptation never stops burning

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#15743]
### Severity

Round Breaking

### Short Description

You get in a hot room(not even on fire) and start burning then no source of cool(space, fire extinguisher, shower) stops it

### Reproduction

1. Get space adaptation
2. Go to a hot room
3. Die slowly

### Round ID

42782

### BYOND Username

Aphielanisn

### Additional information

We never needed this nerf to space adaptation and it's unclear what it was supposed to accomplish if it accomplished anything at all.

**Comment by 00aquir** [comment]
when it happens, try showers that are set to cold and drinking cold drinks.

**Comment by burn1cycle** [comment]
That's ridiculous. As far as I know the only way to get a cold drink is with ice from a vending machine that's been hacked and the only way to get a cold shower is to hack it. So basically a player needs obscure knowledge to fix the problem and it's questionable whether it's powergame for some character jobs to do hacking.

This is just **ass hole code** (someone decided to make everyone miserable). Furthering my claim it's **ass hole code** is that it conveniently ignores going to space or shooting yourself with a fire extinguisher because the **ass hole coder** thought those solutions were too easy.

**Comment by 00aquir** [comment]
I meant usual stuff. Some drinks that can cool you down: Iced Coffee, Iced Tea, Space Cola, Root Beer, Nuka Cola, Grey Bull, Space Mountain Wind, Dr. Gibb, Space-Up, Lemon Lime, Pwr Game, Shambler's Juice, Soda Water, Tonic Water, Monkey Energy.

**Comment by Moltijoe** [comment]
> That's ridiculous. As far as I know the only way to get a cold drink is with ice from a vending machine that's been hacked and the only way to get a cold shower is to hack it. So basically a player needs obscure knowledge to fix the problem and it's questionable whether it's powergame for some character jobs to do hacking.
> 
> This is just **ass hole code** (someone decided to make everyone miserable). Furthering my claim it's **ass hole code** is that it conveniently ignores going to space or shooting yourself with a fire extinguisher because the **ass hole coder** thought those solutions were too easy.

just alt-clicking a shower can swap it to cold

**Comment by ShoziOffical** [comment]
Space adaption only makes you cold proof and low pressure proof and not heat proof

**Comment by ShoziOffical** [comment]
if you want to get heat proof, get heat adapation

**Comment by Moltijoe** [comment]
> just alt-clicking a shower can swap it to cold

hey look, is me, either way, not an issue
