### ISSUE TITLE
hardsuit helmets fall off when you fall down

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#15769]
### Severity

Round Breaking

### Short Description

hardsuit helmets fall off when you fall down

### Reproduction

1. be in hardsuit
2. try getting stunned a few times
3. helmet disengages because you went horizontal
4. die to vacuum

### Round ID

42799

**Comment by ShoziOffical** [comment]
can you specify which hardsuit? also irrc hardsuit helmets should be based on head/helmet type and theres a hattable var for it not to drop when fall

**Comment by ShoziOffical** [comment]
also could not reproduce

**Comment by Sniblet** [comment]
it was an engineering hardsuit, the victim had a holoparasite and was being shot at with buckshot
specifically it was orca cora being controlled by pyronie, don't have a timestamp but it was late and obviously around the time they died

**Comment by ShoziOffical** [comment]
They probably accidentally open their hardsuit helmet, i sometimes accidentally hit the button

**Comment by Sniblet** [comment]
I can check the replay I pointed to tomorrow

**Comment by redmoogle** [comment]
it should be fixed all helmet subtypes (which hardsuit fall under) cant be hatted/fall off

**Comment by Sniblet** [comment]
https://replays.yogstation.net/?roundid=42799#45711;214.03;101.03;2;pyronie;0.6
looks like my guy just tried to toggle their jetpack and missed
