### ISSUE TITLE
 Quiet Mode ignored as user gets picked as a target anyway

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15782]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Invisible Man reportedly being picked as a target despite having quiet mode turned on. Suspected to be the Obsessed antagonist not respecting quiet mode which subsequently also might have the same reason as to why late join quiet mode is not functioning correctly.

 Submitted by: GravelyAnonymous (587541852044132352)

**Comment by MajManatee** [comment]
duplicate
