### ISSUE TITLE
Door Access Bug

### ISSUE THREAD

**Issue by MildlyConcussed** [yogstation13/Yogstation#15789]
### Severity

Quality of Life

### Short Description

Signed on as SysOp (Tcomms engineer) after round start, and could not access Tcomms

### Reproduction

1. Join round late as Tcomms engineer (SysOp technically)
2. Try to access your area
3. Can't
4. Cry
5. Ahelp

### Round ID

42823

### Test Merges

#14709, #15252

### BYOND Username

MildlyConcussed

**Comment by Bibby0110** [comment]
Not a bug
