### ISSUE TITLE
Beartraps Not Visibile on Inspect

### ISSUE THREAD

**Issue by Axemeaquestion** [yogstation13/Yogstation#15786]
### Severity

Quality of Life

### Short Description

Latched beartraps on player not visible on inspect

### Reproduction

1.Walk on beartrap
2.Inspect self

### Round ID

Round #42821

### BYOND Username

Axemeaquestion

### Additional information

There is no real indication you are beartrapped outside of the sprite (which is sometimes very difficult to spot) so its hard to tell that a beartrap is still on you.

**Comment by MajManatee** [comment]
resolbed
