### ISSUE TITLE
looc sugestion

### ISSUE THREAD

**Issue by EthanMalakay** [yogstation13/yogstation#1579]
[Note]: Add a LOOC button in the OOC tab, local OOC only local in-screen players can hear it

**Comment by Gintoki1** [comment]
I can see a few things wrong with this, but it seems nice +1

**Comment by EthanMalakay** [comment]
its my first time ok? i told people it had more logic getting sugestions tab in the forums :v

**Comment by Super3222** [comment]
Tried it, implemented it, people used it, it broke, people abused it, admins didn't like it, it was removed.
Another shot at it wouldn't hurt, but if someones doing it add in a way for admins to mute people.

**Comment by EthanMalakay** [comment]
WAIT, admins cant see it, it is local ooc, no one can except the people in screen

**Comment by matskuman5** [comment]
Eh...

I could see this being abused a lot.

**Comment by EthanMalakay** [comment]
oh yes, lots  it will be i assure you as much as other person used my favorite name and i could not create an account with it .-.  local ooc, perfect for abuse and in-screen explications when people dont understand something and in the typycal OOC they say IC IN OOC get banned you piece of sh-     :v

**Comment by ToGWtF** [comment]
Admins can see all LOOC

**Comment by Slinky5890** [comment]
With the ((This text is now OOC)) marks I don't see a real need for looc.
