### ISSUE TITLE
Cloners

### ISSUE THREAD

**Issue by EthanMalakay** [yogstation13/yogstation#1581]
[Note]: two cloners instead of one, it makes lot of work for medbay with so many corpses, and not so much space, we would like a bigger room of cloning, and with more scanners, thanks

**Comment by ShlohGaming** [comment]
This sounds good on paper. But what about after upgrades? Two, fast, autocloners? Might be a little powerful, plus a second cloner is always made when RnD know whats its doing.

**Comment by EthanMalakay** [comment]
I've never seen another one, are we talking about the same server?

**Comment by ShlohGaming** [comment]
Yes. Youve never been in a round with Lily Shots as a scientist have you? You are aware that Science can recreate most if not all of the stations machines, right?

**Comment by Cruix** [comment]
There is usually a second cloner, it's just hidden in science with all the powergamers.

**Comment by Stealthkibbler** [comment]
should just rename the area name of science to powergame fortress

**Comment by Dagdammit** [comment]
Tech Storage also has the parts, I often build a second cloner there or in cargo.
