### ISSUE TITLE
 do spiderbots genuinely have no brain

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15821]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: after condeming someone to be a worse drone i tried to remove their brain but it said there wasnt one
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1020851201560035389/unknown.png)
 Submitted by: zealot (343805692710486017)

**Comment by Maia-J** [comment]
As the defacto only person who cares about fixing spiderbots, I'll look into this.

**Comment by Maia-J** [comment]
Should be fixed once #15951 is merged
