### ISSUE TITLE
 Equipment is shown twice in personal crafting

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15823]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Equipment is shown twice in personal crafting
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1020895824009515018/unknown.png)
 Submitted by: GravelyAnonymous (587541852044132352)

**Comment by redmoogle** [comment]
Makeshift Toolbelt seems to be doing it due to CAT_EQUIPMENT being set for cat instead of subcat

**Comment by ShoziOffical** [comment]
no one checked on this smh
