### ISSUE TITLE
Can't examine spider bots

### ISSUE THREAD

**Issue by spaceboi123** [yogstation13/Yogstation#15848]
### Severity

Inconvenience

### Short Description

Title says all ready

### Reproduction

1. Look at a spider bot
2. Try to examine
3. Fail to do anything
4. Cry (As always with my bug reports, this is an important step)

### Round ID

42863

### BYOND Username

Billybobdaboss113

**Comment by Maia-J** [comment]
Should be fixed once #15951 is merged
