### ISSUE TITLE
pAI Externel Console Control Interface needs manual reload to update

### ISSUE THREAD

**Issue by valuial** [yogstation13/yogstation#1584]
As pAI installed the "IPv18 External Console Control Interface" (ECCI), connected to the Central R&D Core Console (Owner: RD).
First Problem: Textmessage that handshake was successful shows in the message log, but the Sofware Interface window of the pAI doesn't update. Re-open of the ECCI updates.

Opening the remote Console, Menu is displayed as normal (like I use it as a Scientist), but the buttons seem unresponsive. Closing and opening the window again shows the new state of the Console Screen. Updates are not automatic like using the Console as Scientist directly. This makes navigating menus very tedious.

**Comment by ShlohGaming** [comment]
This is the same with any console that you have walked away from. Is it possible the game believes there is no player interacting with the "console" and so, cant update?

**Comment by valuial** [comment]
Possible, but unlikely. I also tested this with the holder of my card standing directly adjacent to the console in question.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Please fix it's absolutely horrible
