### ISSUE TITLE
I AM SAD

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#15858]
### Severity

Quality of Life

### Short Description

Sad trombone is missing from borg emotes!

### Reproduction

- *help says you have sad emote
- you don't have sad emote
- you are sad

### Round ID

42872

### BYOND Username

Aquir

**Comment by Notamaniac** [comment]
uniquely fucked. No runtimes, doesn't give an invalid emote message when typed in for any species.
