### ISSUE TITLE
Yolo Griefers

### ISSUE THREAD

**Issue by EthanMalakay** [yogstation13/yogstation#1587]
[Note]: Sugestion. ban who fucks up outter orbit ghost roles just because yolo, trying to get the colossus near to destroy base/nest or calling the legion that is near, even if it is a prisoner who did it and the only base near is of golems, he did it to harrass. ._. frustrating for ghosts

**Comment by ShlohGaming** [comment]
Shouldnt this be in player complaints? If you feel like youve been griefed you should file a player complaint to go through the proper channels.

**Comment by ShadowDeath6** [comment]
The only possible change that could be made is to restrict ghost roles from opening Legion's door. Other megafauna are purely admin jurisdiction, though.

**Comment by EthanMalakay** [comment]
:V that idea from blocking the ghoost roles sounds good, with a text appearing saying "Your soul is not worth enough for calling the One"
