### ISSUE TITLE
 scrubbers backpressure gas/smoke event breaks lighting

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15875]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: anytime the scrubbers to the surge thing it breaks the lighting. Having to use the fire alarm to fix it. also seen admins enable/disable night lighting to fix it

 Submitted by: forhiti3 (294599429996937227)

**Comment by redmoogle** [comment]
https://github.com/yogstation13/Yogstation/pull/15867

Smoke doesnt cause lighting updates for some weird ass reason. When I force lighting updates only 50% of the light comes back. ??????????????????????? Removing the T.has_opaque_atom fixes it but causes light to bleed past a tile for doors and windows

**Comment by ShoziOffical** [comment]
Smoke has been causing this weird ass bug for a while now

**Comment by ShoziOffical** [comment]
#15913
