### ISSUE TITLE
 ghosts are fucking bluescreening

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15882]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: orbit menu bluescreens
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1022177818269982731/unknown.png)
 Submitted by: zealot (343805692710486017)

**Comment by redmoogle** [comment]
Unable to replicate
