### ISSUE TITLE
Microwave bugs if power outage occurs while in use

### ISSUE THREAD

**Issue by sukhoiboi** [yogstation13/Yogstation#15888]
### Severity

Inconvenience

### Short Description

Microwave bugs if power outage occurs while in use

### Reproduction

1. Put something in microwave
2. Turn microwave on
3. Power goes out
4. Microwave stays on forever, wont let you turn it off, remove contents, add contents, or disassemble.

### Round ID

42911

### BYOND Username

sukhoiboi

### Additional information

Microwave essentially just becomes completely unusable if its on when the power goes out. It will remain on, but will not allow you to turn it off, remove the contents, add more contents, take it apart, or anything. It essentially becomes non-interactable.

**Comment by MajManatee** [comment]
dupllicate
