### ISSUE TITLE
xenobio bug

### ISSUE THREAD

**Issue by isotope436** [yogstation13/Yogstation#15910]
### Severity

Inconvenience

### Short Description

If you pick up a slime as it goes to either grow up or split (in the exact frame) it will delete the slime from existence 

### Reproduction

1. feed a slime (doesn't matter what or what type)
2. once the slime hits 10/10 (either if it is going to grow or split) continuelessly pick it up till you lose the ability to place it or it grows/splits
3. if you cant place it back down after grabbing it congrats you just atomized it from exitance if it does grow up or split i guess he gets to live another day

### Round ID

42948

### Test Merges

#15225: '[AI] AI Rework 2.5 || The one with cables and golem AIs' by TheGamerdk at commit 8a0ea1baf1

### BYOND Username

Nightmare1243

**Comment by MajManatee** [comment]
id say intended feature, but its not and it wont be fixed
