### ISSUE TITLE
PDA BOMBS DONT WORK

### ISSUE THREAD

**Issue by boodaliboo** [yogstation13/Yogstation#15920]
### Severity

Round Breaking

### Short Description

THEY DONT WORK

### Reproduction

GET PDA BOMB THEY DONT WORK

### Round ID

EVERY ROUND AS NUKIES

### Test Merges

AI REWORK

### BYOND Username

BOODALIBOO

### Additional information

fuck you pda rework and fuck the ghosts

**Comment by MajManatee** [comment]
They work
