### ISSUE TITLE
 Interrogation monitor look at the infirmary

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15925]
## Test Merges: 
Not Supplied / None
## Reproduction:
The wall monitor that is supposed to let you watch the interrogation room show you the brig infirmary cam instead.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1023557773205721138/Capture_decran_2022-09-24_212325.png)
 Submitted by: JellyRain (846634033622417470)

**Comment by VaelophisNyx** [comment]
Should be fixed

**Comment by patpol4** [comment]
Fixed
