### ISSUE TITLE
Disappearing secret documents.

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#1593]
I put the secret documents into the photocopier and they disappeared. I then tested with three more sets of documents and they all disappeared.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
the photocopier was a paper shredder in disguise all along

**Comment by AdamElTablawy** [comment]
intended, docs are deleted in photocopy to prevent absue

**Comment by Cruix** [comment]
No this is a real bug

**Comment by ShadowDeath6** [comment]
Remove adam's open and close access pls

**Comment by Cruix** [comment]
He was only given it for ten minutes

**Comment by nichlas0010** [comment]
Fixed in #1634
