### ISSUE TITLE
Random Space Tiles in Maint

### ISSUE THREAD

**Issue by Silvore** [yogstation13/Yogstation#15944]
### Severity

Inconvenience

### Short Description

So, randomly in maints one round, about 1/4 of the doors in maint had a space tile under them.

### Reproduction

No clue if this can be reproduced, but all I know is that this can happen in the first place, and should be looked at

### Round ID

Round #43006

### Test Merges

None

### BYOND Username

Silvorz

**Comment by ToasterBiome** [comment]
@Silvore What map?
