### ISSUE TITLE
AI carding location is strategically stupid

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#15950]
### Severity

Inconvenience

### Short Description

You can card the AI from the back of science next to maints

### Reproduction

1. perform carding steps

### Round ID

n/a

### Test Merges

not sure

### BYOND Username

Aphielanisn

### Additional information

Someone changed the carding system to a computer that hangs out next to maintenance in a location as far from the sec department as possible with no turrets!

It's not even clear if someone could just build the same computer somewhere else on the station and card the AI from there, too. I have not tried.

 At one point we had the AI where telecoms is now and this worked great for us it made it easy to keep the AI secure. Then we moved it to telecomms(for reasons that were never explained?) and upload into engineering maintenance which made securing the AI more difficult. 

 The card location lacks turrets, double RWall, high security isolation, or even location to a well defended area.

 You could've done better to expand the clown office and put the carding system in there for the clown to guard. It would've been more secure due to physical location and would also be less of a joke then the current location is.

 My ideal solution would be to move telecoms back to where the AI is now and move all the AI stuff and carding back to where telecoms is(where we had it for a number of years). Give the AI back turrets to defend carding, and put the new AI lab (not sure..) -either where law upload is(Upload tucks in behind the HoP Office/Teleporter that's how we had it a long time ago) or leave it in science.

**Comment by VaelophisNyx** [comment]
non-issue now since AI rework is un-merged

**Comment by burn1cycle** [comment]
I'm confused about what was unmerged? I think the console that cards the AI was moved to the AI satellite but it's outside the AI chamber with turrets. If that's the case I would really rather the carding mechanic be where it's protected with turrets since that's the whole reason why we gave the AI turrets.
