### ISSUE TITLE
Drones are capable of messaging crew members via PDA.

### ISSUE THREAD

**Issue by ShlohGaming** [yogstation13/yogstation#1596]
Speaks for itself, another method of Drone to player communication.

**Comment by Time-Green** [comment]
This is more of an admin problem. Sure, we can code it out, but really?

**Comment by ShlohGaming** [comment]
Why give anyone the chance to use it? Why not take the chance to prevent a problem, instead of ignoring it because "but really?"

**Comment by Dagdammit** [comment]
Because it's work and there's other stuff to be done, that's all. (Or so I imagine)

**Comment by AdamElTablawy** [comment]
Too much work to do. PDA's don't have checks for people sending messages, @ShlohGaming and so in order to do that it'd be a lot of spaghetti code
