### ISSUE TITLE
Clockcult laws suck brass dick

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#1597]
"Purge untruths and praise Ratvar"
This is shittiest law for clockcult cyborgs.
It just says "Lol valid noncult" without forcing you to submit anything to actual cult.It just makes you hjack everything.Every time AI will just suck air from station,cyborgs will laser everyone and ignore real clock people,cause there is nothing in laws about serving cult at all,only about Ratvar praising.
Remove,remake law to actually make cyborgs work with cult,not run around emag wild and kill everything without cog above head.This is bad,antiintuitive,unfun,smthingsmthing et cetera.

**Comment by Time-Green** [comment]
The wording on that could be alot better yeah

**Comment by ShadowDeath6** [comment]
remove borg conversion from clock cult when

**Comment by EthanMalakay** [comment]
Oh no, who would rekt the shit out of everything then :v

**Comment by Dagdammit** [comment]
Borg conversion's one of the most interesting and distinct bits of clock cult, honestly. Kinda sucks that there's no deconversion method, there should be something interesting- maybe having the chaplain bless a  reboot module idk.

**Comment by AdamElTablawy** [comment]
@Ratvar you get text that you are part of the cult and serve the cult

when converted to cult, you get the cult icon, etc

therefore you are part of the cult

therefore, don't try to loophole it or you'll get banned

**Comment by Cruix** [comment]
You are a team antag, the law is just for flavor.
