### ISSUE TITLE
 Meta SMESes run on magic by default

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#15994]
## Test Merges: 
Not Supplied / None
## Reproduction:
All SMES units on Meta appear to start out charged to 99.7% and outputting at 200kw, if this is changed they'll start working normally, if the output is not changed they'll draw from an infinite reserve of power and keep outputting at max

 Submitted by: Davos (555869314784428032)

**Comment by patpol4** [comment]
Doesnt appear to be a thing
