### ISSUE TITLE
 Pdas able to download traitor programs roundstart as non traitor.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16016]
## Test Merges: 
Not Supplied / None
## Reproduction:
Had access to new programs on my pda roundstart while i was checking out the new pda themes.

 Submitted by: Tawaporah Koko (241348083907166219)

**Comment by Chubbygummibear** [comment]
I'll get to work on this soon, i've been inundated with homework as of late

**Comment by Moltijoe** [comment]
should be fixed
