### ISSUE TITLE
 Could not use machines or gun

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16034]
## Test Merges: 
Not Supplied / None
## Reproduction:
As detective (name Athena Kuznetszov) I spawned in unable to interact with machines such as APCS cams or security records. My fingers also did not fit in a gun I was using. Was fixed after an admin put me in an entirely new body.

 Submitted by: Bucket (188151461241159680)

**Comment by Buckethead390** [comment]
Upon further inspection it just looks like podpeople were entirely replaced by ivymen in character setup. It also shares the same features as ivymen.
