### ISSUE TITLE
TGUI not working

### ISSUE THREAD

**Issue by Auvan** [yogstation13/Yogstation#16036]
### Severity

Round Breaking

### Short Description

TGUI doesn't pop up when I interact with TGUI items

### Reproduction

No idea it just randomly started happening one round
it did fix itself though when I reconnected again as a ghost to look for the Test Merges

### Round ID

Round #43133

### Test Merges

#14802

### BYOND Username

Psychen

**Comment by Bibby0110** [comment]
Likely a client/cache issue, doesn't seem to be too widespread
