### ISSUE TITLE
Can we have Unicorn Raver Cult to balance out the other two cults please?

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1604]
We need more weird stuff and I think a third cult themed after Unicorn ravers is just the thing fitting in with the native american and eastern beliefs of cycles between destruction death and decay(Narsie), Chaos creation and anarchy (Unicorn Cult), and Order control and oppression (Clockwork cult).

 We could have vinyl records for tomes, mix tables for altars, color changing light tiles for floor tiles, dances to perform spells, glow sticks for Unicorn Cult weapons, color changing jumpsuit duped and buffed for armor, and a giant gray alien head wearing a Cat in the Hat style hat as deity.

 Maybe (or maybe not?) It would be interesting to have Narsie cult strong against clockwork, Unicorn strong against Narsie, and Clockwork strong against Unicorn. But some people might object to having in built weaknesses so I am not sure.

**Comment by ShlohGaming** [comment]
With the current way players feel about clockwork cult as it is, I dont think ADDING more problems (because any new addition is going to have problems) on top of what already exists is going to solve the problem for anyone. I think we should focus on fine tuning Clockwork, Narsie, and C Vs N before we add anything else of this type.

**Comment by aphielanis** [comment]
They'll never be balanced lol. We've been re-balancing traitor, ling, and nuke ops since they came out!

 It's just the nature of the game that everything looks fine on paper but some one finds an angle that the design didn't plan for.

**Comment by ShlohGaming** [comment]
The thing is though, people dont HATE traitor, ling or nuke ops, not inherently as game modes anyways. People HATE clockwork cult gamemode especially, and cults in general.

**Comment by ShlohGaming** [comment]
I dont personally dislike cults. I think modes are modes, some will be good some will be bad. But I pay attention to OOC and the forums. people just dislike and rev / gangs.

**Comment by ShadowDeath6** [comment]
group antags r bad
clockcult is bad because nobody knows how to play it
cult is the only good group antag and even then it's still pretty mediocre

**Comment by EthanMalakay** [comment]
I would like it if it had OP shit like lazor shooter mlg unicorn rain over all and horn laser explosions with some unicorn body transformations, some pink fluff spreading to the staion too, and the unicorn god that throws muffins with bombs inside :V

**Comment by AdamElTablawy** [comment]
are you serious

**Comment by AdamElTablawy** [comment]
get the fuck out

**Comment by ShadowDeath6** [comment]
There are a lot of ways to go about a third cult but unicorns is not one of the ones that would fit

**Comment by aphielanis** [comment]
I disagree, the shock reaction to my idea suggests I have discovered an old god that a simple human mind can't comprehend but instead lashes out against in what it perceives as insanity but is in fact the pure word of truth so profound that it drives a normal mind to shock, appall, and if fully embraced enlightened madness.

**Comment by AdamElTablawy** [comment]
Are you actually fucking retarded?

**Comment by enailz** [comment]
i'm gay

**Comment by Cruix** [comment]
It's three months too early for this
