### ISSUE TITLE
 voice announcement broke

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16051]
## Test Merges: 
Not Supplied / None
## Reproduction:
<@900159029098197042> CANT USE VOICE ANNOUNCEMENTS WHAT <@900159029098197042> IS GOING TO DO AS CAP!
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1026752862425976902/lda.png)
 Submitted by: Kojuh (239560674517188609)

**Comment by patpol4** [comment]
duplicate of https://github.com/yogstation13/Yogstation/issues/16121
