### ISSUE TITLE
adminordrazine permanently breaks bloodsuckers' hearts

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#16052]
### Severity

Low

### Short Description

Bloodsuckers have a fatal heart attack on exposure to adminordrazine, and again every time they wake from Torpor, forever

### Reproduction

1. blodsuc
2. adminordrnazin
3. Bloodsucker clutches at her chest as if her heart is stopping!
4. trait_nobreath does nothing
5. Die
6. Torpor
7. Wake up
8. Die instantly
9. Torpor
10. Wake up
11. Die instantly
12. Torpor
13. Wake up
14. Die instantly
15. Get defibbed! Everything's ok now
16. Sol, go to coffin
17. Torpor
18. Wake up
19. Bloodsucker clutches at her chest as if her heart is stopping!
20. Die
21. Torpor
22. Wake up
23. Die instantly

### Round ID

Private server

**Comment by MajManatee** [comment]
Not being fixed because you cannot get it conventionally
