### ISSUE TITLE
 IPC "lungs" are burning up even with internals and space suit

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16065]
## Test Merges: 
Not Supplied / None
## Reproduction:

Description: Playing atmos technician, and I decide to go into space to make a cooling loop. I start to burn up(I was only in a firesuit with internals), and went and upgraded to atmos exosuit. Went back out, and started burning up again. When I went back inside, I didn't stop burning up until I turned off internals, which I checked, and they were normal temps and working just fine. This happens in any room without any substantial atmosphere, or if the air is too hot(plasma fire after roundend started suffocating me regardless of my suit and internals).

Steps to reproduce: Play IPC, get internals and a space suit, go to space,  or any convenient vacuum.

 Submitted by: Trenos301 (209297945600720896)

**Comment by Maia-J** [comment]
Fixed with #16066
