### ISSUE TITLE
 Box north-west solar SMES has inherited some magic powers from the Ghost of Metastation Past

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16077]
## Test Merges: 
Not Supplied / None
## Reproduction:
North-west solar SMES on box appear to be able to output maximum power and not actually take up any regardless of supply available

 Submitted by: Davos (555869314784428032)

**Comment by patpol4** [comment]
doesnt appear to be a thing, the smes in question is exact same as the others
