### ISSUE TITLE
Adding a draw timer for weapons taken out of backpacks/storages

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation#1608]
Hypothetical situation - You walk down a hallway and see someone being beaten to death in an open hallway with a toolbox. Since you're not a complete jerkass you go "Hey let's drag that guy away from this toolbox murderer!". Before you get three tiles away the murderer draws out his taser, stuns you, then finishes you off with a chain stunbatoning (naturally on harm intent). Both of which he had in his backpack or had any prior knowledge of him possessing.

Is the counterplay here just to gitgud assume all people have tasers and stunbatons and have some sort of backup plan (i.e. use stun resist chems beforehand/ stun them first)?

I mean adding a draw timer to weapons taken out of storages would slightly alleviate this situation, at least then you have a chance to react/get away, rather than ggnore u no stun me first now u die

This would also place some weight on what item you put on your belt slot/exosuit slot (let's just assume taking a weapon from the belt or exosuit slot has less/no draw time), as you'd have to make choices of "If I was to spontaneously get fired upon, what weapon would I prefer to draw out in a panic?"

It'd also encourage you to walk around with your weapons out, to avoid suffering that draw timer, which makes you more liable to slips/stuns/disarms and getting your own weapon turned on you. Not exactly sure if this is a bad thing since it helps out the underdog in combat encounters, but worth mentioning.

Another objectively bad thing is that adding a draw timer to weapons might make it somewhat tedious to manage inventories full of them, and even more tedious in combat situations if you go "Right lemme take this gun out of my backpack wait it's the wrong gun, hold on for several more seconds while I take out the other gun - Oh wait I'm dead".

Is having one less situation where you feel as if you could've done nothing to apart from attack him first with stuns worth the hassle of making weapon inventory management more tedious/tactical? Or should people just assume that all toolbox murderers have tasers and stunbatons on them and let people get bashed to death while yelling for security?

Discuss

**Comment by ToGWtF** [comment]
>Nuke ops shoots Captain dead and drags him away
>Stop chasing to pull your taser out
>Get taser out, check the direction they went
>No captain
>Pat yourself on the back and tell yourself "Next time I'll get them"
>beep beep beep boom

**Comment by ShadowDeath6** [comment]
>hey let me drag this guy away from a murderer
>dies
>"wtf dude how'd I die"

**Comment by enailz** [comment]
i ded
