### ISSUE TITLE
 Phazon Comms Bug

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16086]
## Test Merges: 
Not Supplied / None
## Reproduction:
Phazon - RD and I (Captain) entered our phazons and after a few minutes in the mech, we weren't able to type anything into comms at all. Not even the "me" functioned work. Ejecting also didn't fix and the silence persisted. Required reconnecting.

 Submitted by: Azaelus (1002024385185587371)

**Comment by MajManatee** [comment]
Not enough info
