### ISSUE TITLE
New sec barriers cannot give reports

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation#161]
[Note]:  #161 TG security barrier grenades yield sec barriers which cannot be set to broadcast. I thought we were merging yogstation exclusives, not overwriting them all.

Reproduction: Attempt to interact with a deployed sec barrier nade

Solution: Comment out their security grenade, replace instances with yogstation security barriers.

**Comment by Super3222** [comment]
Oisin was going to handle the security barriers along with the map, but he's been running into things.
If he won't, my plan was to keep both barriers in the game. 

I'll leave their security grenades in a box (one to go in the wardens locker and one to go in the back of he armory) and YogBarriers in the armory.

**Comment by EMT321** [comment]
@Super3222 @oisin100 @Cruix @X-TheDark @Kmc2000 

Any updates?

**Comment by Super3222** [comment]
@EMT321 It will be my very next PR, you have my word. Sorry about the long delay
