### ISSUE TITLE
Sterilizine is useless

### ISSUE THREAD

**Issue by puremanbird** [yogstation13/yogstation#1610]
Sterilizine

When applied via touch or vapor, increases the success chance of surgical steps by 20%. Useful for surgery in less than ideal conditions. 
1 part Antitoxin
1 part Chlorine
1 part Ethanol

Holy shit this is useless and never used. I suggest making it also speed up surgery steps to make it something worth stocking in the vendor.

**Comment by Ratvar** [comment]
Make it both speed up process and give better chance,make it reel gud

**Comment by ToGWtF** [comment]
Can we add shit like the laser scalpel back too?

**Comment by Jc1469** [comment]
As far as I can tell, Sterilizine legitimately has no uses in the code, other than messing with kudzu.

**Comment by AdamElTablawy** [comment]
It does not have any uses at the moment.

Our wiki is updated to /tg/'s, which is ahead of us.

**Comment by puremanbird** [comment]
So how hard would it be to implement, but tweak it to speed up surgical steps by a ton? Then maybe we can get more people reviving dead corpses via surgery.

**Comment by X-TheDark** [comment]
I'll see if I can port over /tg/'s Sterilizine as a starting point.
