### ISSUE TITLE
Riot shield doesnt block zombie attack fully

### ISSUE THREAD

**Issue by ThatGuyPhil** [yogstation13/Yogstation#16118]
### Severity

Inconvenience

### Short Description

shield blocked zombie attacks still give the zombie gland organ thing

### Reproduction

1. have zombies exist
2. get riot shield
3. block zombie claw with riot shield
4. still get the zombie toxic organ thing anyway

### Round ID

43246

### BYOND Username

fireclaw787

**Comment by MajManatee** [comment]
should be fixed?
