### ISSUE TITLE
alien fireing pins dont let aliens fire guns

### ISSUE THREAD

**Issue by xbobsherex** [yogstation13/yogstation#1611]
pretty pointless to have alien firing pins when aliens cant use the guns themselves. Their fingers don't fit in the trigger guards

**Comment by AdamElTablawy** [comment]
It's so crew can't fire the alien radpistol.

**Comment by ShadowDeath6** [comment]
If abductors can't use the guns then why have them at all?

**Comment by Cruix** [comment]
Abductor firing pins make it so anyone who is not an abductor cannot fire the gun, but they can only fire guns that do not have a trigger guard, same as golems.
