### ISSUE TITLE
Voice Announcements won't work

### ISSUE THREAD

**Issue by goliathdnd** [yogstation13/Yogstation#16121]
### Severity

Quality of Life

### Short Description

Just says it's an invalid URL when trying to use the voice announcements

### Reproduction

1. Join as swagger ass captain
2. Head to command console (I think?)
3. Use voice announcements
4. Cry when it doesn't work

### Round ID

43249

### BYOND Username

Goliathdnd

### Additional information

PLEASE FIX IT IT'S THE ONLY THING THAT MAKES ME BAREABLE AS A CAPTAIN TO THE REST OF THE CREW

**Comment by patpol4** [comment]
@monster860 not sure if this was fixed

**Comment by MajManatee** [comment]
fixed, thank god
