### ISSUE TITLE
Broken APC - why only with Fire Extinguisher???

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1613]
Broken APC. Breaking it with metal, industrial welder, etc.. no... it only gives when you use red fire extinguisher. Makes no sense, repair this.

**Comment by enailz** [comment]
fight blue with red

**Comment by AdamElTablawy** [comment]
@00aquir 

please don't make stupid nonsensical issues

read the code, it's not just extinguishers

**Comment by 00aquir** [comment]
Please. I was there a thousand times. Without extinguisher you can whack it with metal or else OVER 40 TIMES. I cannot waste my welder on it and don't know why it won't give for other normal tools.  Repair. It.

**Comment by ShadowDeath6** [comment]
Extinguisher is just high damage. Use a toolbox or something else that does decent damage, try it out.

**Comment by AdamElTablawy** [comment]
@00aquir 

Any object that does decent BRUTE damage will knock off a metal cover, Aquir.

Metal does 5 damage, so that won't work.

A welder does 15 BURN damage, so that won't work.

Use something that does heavy brute, such as a stunbaton, fire extinguisher, fire axe, circular saw, et cetera.

**Comment by 00aquir** [comment]
Those are exactly what an engineer doesn't carry around. Lower the required damage, I meant.

**Comment by AdamElTablawy** [comment]
No.

**Comment by ToGWtF** [comment]
Yeah, it requires 10brute damage or more to break off the cover.
