### ISSUE TITLE
 YogStation (fuck latejoins)

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16144]
## Test Merges: 
Not Supplied / None
## Reproduction:
Latejoined on yogstation(the map) after shuttle left, spawned in space and had to get admin teleported out. same thing happened to captain and they just flat died
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1029451769996120135/IspawnedinSpess.png)
 Submitted by: Lichton (271438688100024320)

**Comment by Lichton** [comment]
Singulo consumed arrivals shuttle (this should not happen for obvious reasons)

**Comment by Bibby0110** [comment]
Not a bug
