### ISSUE TITLE
Asteroidstation's Mulebots are identical

### ISSUE THREAD

**Issue by ThatGuyPhil** [yogstation13/Yogstation#16140]
### Severity

Inconvenience

### Short Description

Asteroid's mulebots are identical. Both are mulebot (#1) and have the same home.

### Reproduction

1. play as cargo on asteroid
2. look at the fucking mulebots

### Round ID

43275

### BYOND Username

fireclaw787

**Comment by ToasterBiome** [comment]
Mulebots are #1 and #2 different in current version.
