### ISSUE TITLE
[asteroid] Air Injector for turbine venting unpowered.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16156]
## Test Merges: 
Not Supplied / None
## Reproduction:
This is on AsteroidStation. Just hop on and it's unpowered. Probably doesn't have the area setup for turbine APC.

 Submitted by: iowatt (220761653791293440)

**Comment by ToasterBiome** [comment]
Needs confirmation, area is correct.

**Comment by neeshacark** [comment]
seems like its working fine now
