### ISSUE TITLE
Weird space bug viewing things.

### ISSUE THREAD

**Issue by Slinky5890** [yogstation13/yogstation#1616]
I'm posting this on behalf of someone who's too lazy to do it themselves, so details area little sketchy. I also have no idea how to recreate this.

Ticket logs: http://i.imgur.com/SL91FkC.png
Screenshots: https://s29.postimg.org/jq9uo291z/Bugorsomething.png (mesons on)
https://postimg.org/image/5h5o96ktv/ (mesons on)
https://postimg.org/image/drda9n0qf/ (mesons off)
https://postimg.org/image/o0x1yu8tr/ (lavaland)

**Comment by Slinky5890** [comment]
https://postimg.org/image/4frp28mdz/ in crit

**Comment by Time-Green** [comment]
Known bug, tell him he needs to update byond

**Comment by Slinky5890** [comment]
Told them to update, when I hear from them afterwards i'll close this if it worked.
