### ISSUE TITLE
 The Glorious Clown Ops Gave Out Wrong Uplinks

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16176]
## Test Merges: 
Not Supplied / None
## Reproduction:
So instead of giving out the clown ops uplink to the ops, it instead gave normal uplinks, in which they couldn't use most of the items effectively without blowing themselves up.

 Submitted by: Hisakaki (98481061960351744)

**Comment by MajManatee** [comment]
hisa please this is your third bug report for this.
