### ISSUE TITLE
 Bloodsucker random frenzy bug

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16175]
## Test Merges: 
Not Supplied / None
## Reproduction:
This bug makes bloodsuckers randomly go into a frenzy, needing blood badly, and even start dying, even when they have 300+ blood, and it only stopped once i had gotten my maximum (900)

 Submitted by: purr purr (843557080320442398)

**Comment by MajManatee** [comment]
not enough info
