### ISSUE TITLE
Zippo lighters have no flame

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#16186]
### Severity

Low

### Short Description

Zippo lighters have had no flame on their open sprite for a few weeks now, this does not extend to cheap lighters of any kind.  It is exclusively zippos

### Reproduction

1. buy zippo
2. open
3. no flame
4. cry

### Round ID

N/A

### BYOND Username

Cark

**Comment by MajManatee** [comment]
fixed
