### ISSUE TITLE
Secure briefcase is invisible inhand from certain angle.

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#16187]
### Severity

Low

### Short Description

The secure briefcase can not be seen inhand when it is on the side of your sprite not facing the screen, it just vanishes.

### Reproduction

1. get secure briefcase
2. hold it in left hand
3. face right
4. invisible
5. hold in right hand
6. face left
7. invisible

### Round ID

n/a

### BYOND Username

Cark

**Comment by MajManatee** [comment]
Its behind your leg innit
