### ISSUE TITLE
TG blob and player controlled blobbernauts can fire as a random event

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation#162]
[Note]: #162 TG blob allows for blobbernauts to be player controlled, and additionally can fire during traitor/changeling/other antag rounds. This makes it essentially impossible to defeat, should it not happen early in the shift.

Reproduction: Spawn a blob 30 minutes into a DA/Traitor round, collect stats on blob win rate.

Solution: Separate blob into its own game mode, remove it as a random event.

**Comment by timkoster1** [comment]
This is a feature, on old yogs code blobs could spawn mid-round aswell with no win condition. Pretty much dooming the entire round.

**Comment by Stealthkibbler** [comment]
It should be changed, its already led to rounds being impossible to end causing admins having to force an end.

**Comment by oisin100** [comment]
Blob has been rebalanced since this issue, As for spawning, Blobs were able to spawn midround prior to rebase anyway.
