### ISSUE TITLE
Weapon with 0 shot capacity, fully charged

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#16206]
### Severty

Round Breaking

### Short Decription

Weapon(s) even in backpack can become completely unsalvagably unusable (losing "energy weapon lens"), mostly after experiencing explosion.

### Reprodunction

- disabler was in backpack
- PDA bombed
- disabler had 0 shots when fully charged

Other occurences:
- https://github.com/yogstation13/Yogstation/issues/3981
- https://github.com/yogstation13/Yogstation/issues/14959

### Rouined ID

[43419 - 22:00 , 58:40](https://replays.yogstation.net/?roundid=43419#13102;124.50;191.50;2;[0x2018997];0.0)

### BYOND ussrname

Aquir

**Comment by Notamaniac** [comment]
It could be the explosion destroying the battery inside the disabler

**Comment by MajManatee** [comment]
Unable to reporduce
