### ISSUE TITLE
 be able to see if the ai is rouge using a coms script

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16203]
## Test Merges: 
Not Supplied / None
## Reproduction:
when the ai is rouge using a basic script related to jobs it seems to blank out their name in coms

 Submitted by: Braedon (940453206511743066)

**Comment by Maia-J** [comment]
Please supply the script and I'll try to look into it

**Comment by MajManatee** [comment]
Not enough information
