### ISSUE TITLE
Ghost spawners (Charlie station, free miners, free golems) cannot research or use any science machine

### ISSUE THREAD

**Issue by Necrosium** [yogstation13/Yogstation#16228]
### Severity

Inconvenience

### Short Description

Speaking from the charlie station POV as I've played it a few times, you cannot either research stuff from the console (which I assume makes sense since it's tied to the main station's research points, but still detrimental to the ghost spawn) nor use the robotics machine in the area, which prevents them from making borgs. Furthermore, the fact that the imprinter and the protolathe are science-department and not omni, like they used to be before, it is not directly possible to make an ore silo or other machines, which is once more detrimental to the spawn.

### Reproduction

1. Join as charlie station crew (any role).
2. Fix the stuff, as it's done always.
3. Go to science, fight xenos and risk your life many times through it.
4. Find out that almost the entirety of science is unusable due to ID restrictions.
5. Give up and ghost.

### Round ID

Most of the rounds that the ghost spawn has appeared. Posting this during Round 43469.

### BYOND Username

Time_URSS

### Additional information

I'm aware that this can be both a bug report and a feature one, thus i will bring it up here and in the forums as well. At the very least it'd be nice to fix the ID restrictions in Charlie Station so it can be minimally playable to an extent while something else is thought to make it less impacting to the station (which I do not think it is since most of the stuff charlie researches are teleporters or tcomms from my experience).

It kinda feels weird for a charlie "scientist" not to have access to his science machines. I'd understand if it was other roles, but the scientist should at least have access to those machines. Also it's annoying both to me and probably the admins to have to ahelp everytime to get this fixed.

I apologise as well if this was posted before and/or closed/discussed out, but I truly feel it kills the role enough to make it more unpopular than it was already.

**Comment by ShoziOffical** [comment]
Fixed
