### ISSUE TITLE
"High capacity water tank ? #372" No.2

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1624]
""A specialised high-pressure water tank for holding large amounts of water."
but it holds the same amount of water as a normal one..."

AdamElTablawy: "This should be fixed now. Re open if not the case."

It still contains 1000 units... nothing even changed..

**Comment by Time-Green** [comment]
I just checked, and yep, it has only 1000

**Comment by ParagonPrime** [comment]
I got an email telling me the old issue was closed and I just spent two minutes laughing as soon as I saw this posted.

Stay classy, yogs :')

**Comment by ToGWtF** [comment]
it just holds water specially :^)

**Comment by Jc1469** [comment]
https://github.com/yogstation13/yogstation/blob/f589a9ca72e7273ba8d85d7d115da0ad4de6ce75/code/modules/reagents/reagent_dispenser.dm#L36

Damn, sure was hard to find where this mistake was made :rareparrot:
Max reagents allowed in them is 1000.  Trying to add 100000 to a container able to hold 1000 adds 1000.
Why do people just not test their code, even if it's simple.
