### ISSUE TITLE
Free miners not able to build their own mech on the new ship

### ISSUE THREAD

**Issue by Burger1998** [yogstation13/Yogstation#16254]
### Severity

Inconvenience

### Short Description

The new free miner ship features a clarke wreck chassis and exosuit fabricator at the start the head, arms and torso are unobtainable without the station researching the Clarke themselves. which especially on lower pops isn't going to happen

### Reproduction

join as a free miner engineer see the chassis and no arm see no clarke tab on exosuit fab and cry yourself to sleep.

### Round ID

Round#43497

### BYOND Username

Burger1998

### Additional information

Somewhat related to https://github.com/yogstation13/Yogstation/issues/16228

**Comment by ShoziOffical** [comment]
Fixed
