### ISSUE TITLE
AI Memory leak

### ISSUE THREAD

**Issue by Moggram** [yogstation13/Yogstation#16263]
### Severity

Low

### Short Description

I got to -2800 RAM playing as AI

### Reproduction

So I started by download the Firewall upgrade. After it is done I see that it need two TB of RAM and I only had one. So I get Memory Compressor for more RAM. Test it and run the firewall, works as it should. This is when I turn off the Memory Compressor. I see that I am at -3 RAM, then -6, -9 and so on. By the end of the shift, I was round -2800 RAM.

### Round ID

Round ID: 43514

**Comment by MajManatee** [comment]
Duplicate
