### ISSUE TITLE
Reply button on PDA can beat out a Ouija board

### ISSUE THREAD

**Issue by Addust** [yogstation13/Yogstation#16271]
### Severity

Round Breaking

### Short Description

The reply button on the new PDA, can, when uesd correctly, BE USED POSTMORTEM.

### Reproduction

1. have a PDA chat with someone
2. die
3. press reply button on pda chat
4. 'hey im dead'
5. 'why are you talking postmortem'
6. 'shitcode'
7. fix bug

### Round ID

43526

### Test Merges

16019 and 16229

### BYOND Username

Addust

### Additional information

PDAs care not for mortality.

**Comment by neeshacark** [comment]
Can confirm this is the case, if someone sends you a message you can reply dead or not.

Edit: May be fixed by #16257
