### ISSUE TITLE
 Changeling Unabsorbable bug 

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16284]
## Test Merges: 
Not Supplied / None
## Reproduction:
Changelings that have the obj to absorb other changelings cant absorb 'incompatible with your biology' aka skeletons and tons of other random bs

 Submitted by: Lichton (271438688100024320)

**Comment by neeshacark** [comment]
this is an issue i've seen in the past even without halloween races. i.e xenobiologist becomes a golem and you're fucked.

**Comment by ynot01** [comment]
not a bug

**Comment by ynot01** [comment]
this can be extraordinarily problematic for ling v. ling combat as ling skeletons or IPCs cannot be absorbed and therefore cannot be reasonably combatted by other lings

potential fix being setting ling race to an absorbable race on spawn
