### ISSUE TITLE
 Delta Station R&D

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16303]
## Test Merges: 
Not Supplied / None
## Reproduction:

Optional fields: Cannot print ore silo from R&D console at delta station even though its researched also maybe just maybe put a tool belt or two on that station please.

 Submitted by: FatNasty91 (249055761454333952)

**Comment by FatNasty91** [comment]
Just an update on what i did.. I synced over and over with everthing but didnt work i also tried on the R&D console and the imprinter itself to no avail i could see silo in the tech tree and when i clicked on its icon and press imprint it didnt do nothing nore did it show up on the screen that popped up.

**Comment by ShoziOffical** [comment]
WHO CHANGED IT SMH
