### ISSUE TITLE
 Dynamic Mode not spending any threat or spending wayyyy too little

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16311]
## Test Merges: 
Not Supplied / None
## Reproduction:
Dynamic Modes, (especially on high pop for some reason) are spending no threat, or very little, like a single blood brothers on 60 pop, or, yesterday, 74 pop green shift, it's very very common and i feel like dynamic should be spending more, and or more likely to spend, especially so it makes multiple different antagonists for an interesting shift :p

 Submitted by: purr purr (843557080320442398)

**Comment by MajManatee** [comment]
resolved (i think)
