### ISSUE TITLE
  Ranged holoparasites hit users when moving.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16310]
## Test Merges: 
Not Supplied / None
## Reproduction:
Ranged holoparasites buckled to   the user will shoot like normal if the user is standing still or theyre shooting behind them, but if the user moves in the direction the holoparasite is firing while theyre shooting they will get shot by their own holoparasite. This makes ranged holoparasites much worse, and seems pretty buggy considering they only do this if the user is moving while they shoot.

 Submitted by: Ultra (225615376828989440)

**Comment by MajManatee** [comment]
resolved
