### ISSUE TITLE
AI Voice Recorded Custom Announcement leads to invalid URL.

### ISSUE THREAD

**Issue by BurgerLUA** [yogstation13/Yogstation#16325]
### Severity

Low

### Short Description

The AI custom voice recorded announcement gives an invalid URL.

### Reproduction

1. Try to make a custom announcement by clicking on "Make custom announcement" or whatever it's called.
2. Link leads to Invalid URL.
3. Cry

### Round ID

43623

### BYOND Username

BurgerBB

**Comment by ReddicusDragon** [comment]
duplicate of https://github.com/yogstation13/Yogstation/issues/16121
