### ISSUE TITLE
 Too many Duluhan heads

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16328]
## Test Merges: 
Not Supplied / None
## Reproduction:
I had a lot of fun playing as a duluhan over hallowen. But everytime i playd i spawnd with two heads in my hands. And only one worked. the biggest problem about that whole things was that it confused the hell out of some people and some lad even tryd to clone my "wrong" head for some time. I Always started as medical staff, so i think its maybe because i normally spawn with one item in hand so it just gives me ahead and turns the item into one as well...Ehh. Just an idea what it could be. Not game breaking but kinda ruining the immersion and annoyng for medical or when your acctual head gets lost.

 Submitted by: N.H.C. (344435936299319296)

**Comment by Bibby0110** [comment]
Duplicate
