### ISSUE TITLE
 Space Law book appears to load incorrectly

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16357]
## Test Merges: 
Not Supplied / None
## Reproduction:
The Space Law book in-game only shows "Official: Space Law" briefly, before becoming a blank window. Other books (from Library, Guide to Drinks, etc.) seems to work fine

 Submitted by: Kistrup (150691184270901249)

**Comment by patpol4** [comment]
duplicate of #16973
