### ISSUE TITLE
 Stargazer giving items spirits doesn't work

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16362]
## Test Merges: 
Not Supplied / None
## Reproduction:
I was asked to become a possessed bow, but it spawned me as the stargazer itself (the structure), i think. I picked my name, it put it as stargazer's name, not someone's bow. The only thing i could do was attack the stargazer itself, when i destroyed it, it killed me.

 Submitted by: Marunias (368473582981873664)

**Comment by Oblisk234** [comment]
Same as #17654. Also not reproducible or solvable for same reasons.
