### ISSUE TITLE
 Mesons wallhacks

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16380]
## Test Merges: 
Not Supplied / None
## Reproduction:
When wearing mesons you can see the pickup animations in different rooms. Like if I'm standing outside of chemistry I can see when they pickup beakers, or if people pick up wrenches and stuff. I dont think it happens all the time, but every engineer round I've played I've seen it more than once.

 Submitted by: forhiti3 (294599429996937227)

**Comment by MajManatee** [comment]
resolved (in like a day)
