### ISSUE TITLE
Digital Messenger for pAI's is Broken

### ISSUE THREAD

**Issue by BeastnodeG** [yogstation13/Yogstation#16394]
### Severity

Inconvenience

### Short Description

The Digital Messenger program only lists the AI of the round as "the only pda."

### Reproduction

1. Be installed as a pAI
2. Download the digital messenger program.
3. Attempt to message someone using the digital messenger program.

### Round ID

Round #43717

### Test Merges

#16356

### BYOND Username

Beastnode

### Additional information

This issue is probably directly caused by the update to PDA's leaving digital messenger unsupported.

**Comment by Oblisk234** [comment]
Fixed by #22671
