### ISSUE TITLE
Plasmamen can spawn as antags and special roles, killing them.

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation#164]
[Note]: #164 Player preferences for Plasmamen carry over if made a special antag, including ERT and presumably Nuke Ops. Given the special clothing, you die immediately.

Reproduction: Spawn in as nuke ops/become an ERT member with your character set as a plasmaman.

Solution: Force human for nuke ops and ERT.

**Comment by ParagonPrime** [comment]
also applies to CTF with hilarious but depressing results

i suggest you don't force human, just exclude plasmaman exclusively- i still want to play Phytops.

**Comment by ShadowDeath6** [comment]
solution is disabling plasmaman from roundstart races as a whole

**Comment by Cruix** [comment]
Should be fixed now, has anyone seen this happen recently?
