### ISSUE TITLE
 Explosive fist remember the basics is broken.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16406]
## Test Merges: 
Not Supplied / None
## Reproduction:
The explosive fist remember the basics button seems to only sometimes work, after using it a few times it wont show the text when i click it anymore until i reconnect and then i can do so  a few times before it shuts off again. The combos also feel pretty inconsistent but that might just be a skill issue, not sure though.

 Submitted by: Ultra (225615376828989440)

**Comment by MajManatee** [comment]
Duplicate
