### ISSUE TITLE
Would you like to play as an alien larva?

### ISSUE THREAD

**Issue by YogsMcree** [yogstation13/yogstation#1641]
Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?Would you like to play as an alien larva?

(Add a never for this round option please.)

**Comment by Cruix** [comment]
You can just turn off the pref in game-preferences and not save your preferences. That will keep it off for the rest of the round.

**Comment by ShadowDeath6** [comment]
disable alien pref if you're getting spammed

**Comment by ShlohGaming** [comment]
I didnt even know that was a thing, the more you learn. To the closed with this one!

**Comment by Dagdammit** [comment]
I vote against closing this issue. I love playing as xenomorph in the syndie facility and I'm still very close to turning off the option to play as xeno entirely, just to stop the constant late round xeno larva popup anytime I'm a ghost who doesn't want to be one right this moment. Saying "never for this round" would solve the problem, but so would just making it so there aren't so MANY notices- maybe only sending a max of one every 60 seconds, and treating a "yes" on that first inquiry as a "yes" to any other alien larva in that interval.

**Comment by ShadowDeath6** [comment]
>get spammed by larva notices
>turn off pref
>see larvas on station later
>turn it back on

literally solves the problem and a never button will just make people complain that they can't join the fun when it actually gets to the station

**Comment by Dagdammit** [comment]
Oh, I'm sorry, there's a way to adjust the pref midround?

**Comment by ShadowDeath6** [comment]
yes

**Comment by Slinky5890** [comment]
As I said in another issue, why not just add a 'never for this round' button? pAIs get it, don't see why xenos can't too.

**Comment by ShadowDeath6** [comment]
because people are going to click the 'never' button and when they want to be antag they whine about hitting never, just turn off the alien pref in game preferences until you want to play it.

**Comment by AdamElTablawy** [comment]
Here's the sisue with a 'never for this button' thing.

PaI's use a completely different system than poll_candidates_for_mob. PAI's just have a list of people, etc.

Xenos, like every other thing that isn't pAIs', use Poll_Candidates_for_mob, which has a scripted question of 'yes' or 'no' and such and gives control of the mob etc.

All the code for giving control of the mob is there.

If you change poll_candidates_for_mob to have a 'never for this round' button, that doesn't mean  it's 'never for this round will you be a xenomorph.'

It means never for this round will you ever get this prompt again.

For anything.

Including 'do you want to be an abductor team/revenant/xeno animal' etc. So people who say 'never' to avoid the spam would be fucked out of ever getting any of the other offered roles.

So the other ways to fix it is to snowflake some awful code and re-do the whole 'give control of mob' thing which is far too snowflake code and redundant, especially for JUST xenomorphs, or to do some really fucky shit with the 'icon appears in the top left corner, when you click it they burst' which is really really weird and spaghetti code.

@Slinky5890

**Comment by Super3222** [comment]
lol it would be easy to add in a never option. you would just need to index it, and than find a location to store the list.

**Comment by AdamElTablawy** [comment]
@Super3222 already discussed that with cruix

wouldn't work

never option would apply to everything, not just larva

**Comment by Cruix** [comment]
It would work, you just need to put a little extra effort into coding it.
