### ISSUE TITLE
Minor Suggestions. (Cult Nerf / More pAIs / Map Changes)

### ISSUE THREAD

**Issue by Kombosabo** [yogstation13/yogstation#1643]
Hi, I'm Kombosabo and I'm here to suggest a few changes that I believe are crucial/useful for the server.

**Blood Cult Artificer and Wraith nerf** 
## WARNING/LONG READ
Both of these fellas are, in my opinion, way too fast.
Like, literaly, have you ever been able to catch up with those things? or ran away from one?
Specially Wraths!!!??

I believe their speeds should be lowered as it is extremelly easy to chase victims and drag their corpses away for a sacrifice into the darkness.
Making the cults way more likely to win the rounds.
On the other hand, they could be given new spells aside from the ones they already have with their kit.

Specially wraths, because they are so lame (aka do no f**king damage whatsoever)
Try running away from Artificer and getting cornered by it. Yeah bye, you're done.

**My viewpoint on the game mode.**
I see as it would be more fun just being converted while in your human form rather than dying and becoming a monster, that just runs around and turns stuff into dark tiles/breaks things/kills people. Drawing pentagramic imagery on the floor and making colored paper talismans are way more fun, when you can put them on your bag and slap people in the head with it. (It also increases roleplay possibilities)

**More pAIs around the map:**
_Straightfoward change, easy to implement (would take 10 minutes?).
Why? Easy one. Ghost players will have something to do other than place tickets for admins to solve, thus not making us have endless capture the flag..._
Add more personal AI's around the station, good places in my opinion as follows:

> **Warden's desk**
> _Usually bored at the beginning of the round, put it below the security gas masks, and make it a proper table_
> 
> **Arrivals**
> _For the noobies, yeah, in that wooden table, east of the arrival shuttle_
> 
> **Theatre Stage**
> _So that the mime could "speak" or the clown to get some "advice" HONK,
> that wooden table near the piano seems like a perfect place..._
> 
> **Medbay**
> _Between the cryo cells, I garantee you, 100% of all rounds, someone is gonna pick that pAI up._
> 
> **Engineering**
> _Right outside Chief Engineer's Office (south)_
> 
> **Conference Room**
> _For the HOP or the Captain, come one, has anyone never tought of this? They are the most intense roles, they need that pAI friend!_ :)

I will cover other changes on other requests, as this is my first one. But I have more to cover.

Thank you for your reading, you are all very ballsy and patient, let me know your opinions!

**Comment by Super3222** [comment]
Hello, Kombosabo. I'd like to address / give feedback to some of the points you made.

More pAI's wouldn't hurt, but I don't think they should be in _every_ department. I do support the idea of making them more common even if R&D can make new ones.

As for Wraiths and Artificers, I 100% agree with turning down their speed. Artificers can corrupt, and phase through walls. Wraiths can literally teleport from one place on the station to another. **Both of them can be infinitely created.** If they're still running around, and I quote another player from another server, " at the speed of sanic" than it needs to be turned around. (It can be done by turning this variable into 1 - https://github.com/yogstation13/yogstation/blob/48a335fb419ccf487b1ab0380bb05ee75fda3b2c/code/modules/mob/living/simple_animal/constructs.dm#L11).

Bloodcult has conversion runes for human conversions; I don't agree with the idea of making soul stones more light hearted. The idea is focused around sucking in someones soul/ghost into a stone, and trapping them there to do your bidding. Turning them into monster is fine ATM.

**Comment by ShadowDeath6** [comment]
wraiths are really strong and should be very fast since they die in 2 lasers
artificers can be slow though they can go through walls

also no pAIs are the cancer of this game, R&D can already make them infinitely. More empty shells to spam ghosts with won't help at all, since only like 10 people regularly play them anyway, and there's a button to self-register.

**Comment by AdamElTablawy** [comment]
They actually take 4 lasers to kill. I may tune down their health as a result.

**Comment by Kombosabo** [comment]
Most people don't have lasers, only security. :( 
During security round, they usually don't hand out lasers for everyone, like they do in Nuke Ops
So most of the times, it will be you, the cults and a robust toolbox.
And for them being so fast, makes it hard to laser them if they get close to you
