### ISSUE TITLE
air miz being in cold pipes

### ISSUE THREAD

**Issue by wonderinghost** [yogstation13/Yogstation#16440]
### Severity

Low

### Short Description

somehow air is in this section of piping that i had set up

### Reproduction

freeze a empty pipe
![Screenshot_20221109_101046](https://user-images.githubusercontent.com/88801435/200991897-2f2bd90f-cc24-4a54-ad98-bab5f24fa282.png)

### Round ID

43771

### Additional information

could be dumb and there might be some air in the canisters

**Comment by ShoziOffical** [comment]
Not bug, when you placed the freezer on the pipe, it stored the oxygen south of freezer because there's a pipe there, when you rotate it, it transfer the cold o2 to the east pipe
