### ISSUE TITLE
Lavaland beach biodome black tiles.

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#16467]
### Severity

Low

### Short Description

Certain sand tiles on the lavaland beach tiles show up as pure black, causing an visual annoyance.

### Reproduction

1. find beach biodome
2. see tiles
3. weep

### Round ID

N/A

### BYOND Username

Cark

**Comment by patpol4** [comment]
Might be a mapping issue, might be a spriting issue, will investigate. Probably..
