### ISSUE TITLE
Issues regarding shuttle-movement flinging

### ISSUE THREAD

**Issue by Snellie12** [yogstation13/Yogstation#16497]
### Severity

Round Breaking

### Short Description

Arrivals shuttle clothes causing lag.

### Reproduction

1. Late-join Round 
2. Clothes on Arrivals shuttle fly backwards from shuttle movement
3. Shuttle lands
4. Clothes fly forward
5. Disconnect
6. Shuttle leaves, due to no 'alive' player on.
7. Clothes fly backwards
8. Issue repeats until dragged off of shuttle.

### Round ID

Round #43830

### Test Merges

#16497

### BYOND Username

Snellie

### Additional information

This was only an issue for me currently; but I only make this in a worry that someone else might end up suffering the same issue as I did; as late-joining a round only to be stuck in a disconnecting/reconnecting loop can be annoying.

**Comment by Snellie12** [comment]
As a heads up; the only testmerge shown was 14802; I only followed the Bug Report instructions.

**Comment by Simplehorror** [comment]
dunno what the best fix would be. perhaps remove the arrival shuttle knockback or exclude items from the knockback?

**Comment by Simplehorror** [comment]
although it shouldnt be crashing you in the first place. what's your internet connection like?

**Comment by Snellie12** [comment]
I already have a difficult time connecting to Yogstation; but the best fix making the arrivals shuttle immune to the knockback might be the easiest (And best) option.
