### ISSUE TITLE
 Doomsday mech shunt shouldn't work apparently?

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16501]
## Test Merges: 
Not Supplied / None
## Reproduction:
Apparently the ability to transfer the malf AI to a mech shouldn't carry the doomsday timer along w/ it I believe this also works while regularly shunting but unsure if both cores being destroyed causes the doomsday to stop

 Submitted by: Cowbot (97736956326207488)

**Comment by Simplehorror** [comment]
this isn't a bug

**Comment by MajManatee** [comment]
resolved
