### ISSUE TITLE
 Tool implant is semi-usable without arms

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16508]
## Test Merges: 
Not Supplied / None
## Reproduction:
You can pull tools out of the implant without arms but are stuck with them out, this happened to Vast Atlas
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1041591290426564668/unknown.png)
 Submitted by: Vance Pants (973199365466382396)

**Comment by Moltijoe** [comment]
not entirely true, it was that after extending the toolset implant i was unable to drop it or swap it with another tool using the keybinds. Using the ability button still let me swap tools.

I tried amputating to remove them, but it removed my arms without removing the implant
