### ISSUE TITLE
Let HoP flag roles as high priority

### ISSUE THREAD

**Issue by Dagdammit** [yogstation13/yogstation#1651]
Flavor-wise, they're telling centcomm "we really need more sec officers/a chaplain/etc." All it actually does is somehow flag that role as wanted for those who've hit "join game".

(I really wish there was another space to make suggestions, especially for tiny ones like this)

**Comment by ShadowDeath6** [comment]
this is a good idea but I doubt it'll have much impact on people who want to pick certain jobs when they join

**Comment by Super3222** [comment]
> this is a good idea but I doubt it'll have much impact on people who want to pick certain jobs when they join

It's an OOC notifier that tells players in the lobby what jobs need to be filled. It'd be good to at least _try_ it out for a few days/weeks, and see how it does.

**Comment by puremanbird** [comment]
Sounds neat.

**Comment by Dagdammit** [comment]
Yeah it's not supposed to have an impact on those people. If someone already knows what job they want to be, good for them.

**Comment by Time-Green** [comment]
Could be a fun idea to allow people to leave a small message on the join screen.

**Comment by Slinky5890** [comment]
Time, I think that might slip into the meta side of things. "We have a blob be security!!!" "There's a big breach, be engineers". I'm fine with the 'high priority' stuff however, as that teeters just on the edge for me.

**Comment by doerakpoes** [comment]
I dont see a problem with it

**Comment by nichlas0010** [comment]
@Super3222 please put a "fixes #[issuenumber]" in your PRs when you're fixing bugs, as it'll close the issue.
