### ISSUE TITLE
 Ghost role research problems

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16520]
## Test Merges: 
Not Supplied / None
## Reproduction:
Ghost roles like free golems or delta station now do have their separate research thanks to the patch, but they still can't actually access it with their IDs to research new technologies

 Submitted by: Molti (89554660418936832)

**Comment by warface1234455** [comment]
![image](https://user-images.githubusercontent.com/89688125/201932271-5e924efb-b07f-4ee2-a5ca-5353f8d82223.png)
?

**Comment by warface1234455** [comment]
resolved in discord

**Comment by warface1234455** [comment]
resolved in discord
