### ISSUE TITLE
 The 'fist' upgrade for mechs doesn't work

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16522]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: You can't melee attack with the mech fist (upgrade, NOT standard melee-attack.) If you click on a window/wall/mob it runs it's attack delay b ut doesn't execute the attack.

 Submitted by: WastelandMain (556966533478219816)

**Comment by MajManatee** [comment]
fixed
