### ISSUE TITLE
 Turbine cant take the heat of a trit burn 

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16521]
## Test Merges: 
Not Supplied / None
## Reproduction:
Turbine crumbles to dust while a trit burn is happening within the incin

 Submitted by: Braedon (940453206511743066)

**Comment by ShoziOffical** [comment]
resolved in discord

**Comment by patpol4** [comment]
> resolved in discord

any link or details?

**Comment by ShoziOffical** [comment]
> > resolved in discord
> 
> any link or details?

https://discord.com/channels/134720091576205312/773277250090434640/1042073980619731017
