### ISSUE TITLE
 ipc can turn into zombies 

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16551]
## Test Merges: 
Not Supplied / None
## Reproduction:
desc: if you implant a zombie tumor inside an ipc head and then let it die by any means it will turn into a zombie, trying to decapitate said zombie will fully heal it when the decapitation should happen and make it invincible, only way to decap is with surgery it seems

 Submitted by: cuackles (237761038500626442)

**Comment by Moltijoe** [comment]
bruh, you implanted a tumor inside of an ipc
