### ISSUE TITLE
 PLEASE add clarification for when you're allowed to make a combat mech

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16560]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: Not sure where I'm supposed to put this. The rules are very vague on when you're alloed to make a combat mech. I've heard admins say you can get perms from the RD / other heads, but I've been amessaged for making one as an RD. In-game the idea of unlocking the mechfabs at red alert is useless because you're not actually allowed to make a combat mech at red alert. So what's the damn point of having them unlock?

 Submitted by: WastelandMain (556966533478219816)

**Comment by Bibby0110** [comment]
Rules issue
