### ISSUE TITLE
You can no longer Doomsday while in a mech

### ISSUE THREAD

**Issue by Simplehorror** [yogstation13/Yogstation#16583]
### Severity

Round Breaking

### Short Description

Doomsday no longer works while in a mech

### Reproduction

1. Be malf AI
2. Doomsday
3. Enter mech
4. Doomsday stops

### Round ID

00000

Closes #16501

**Comment by MajManatee** [comment]
this is intentional i believe, so that AI's cant jump into a mech in the corner of the map and be unkillable while they wait for the counter to tick down

**Comment by Simplehorror** [comment]
> this is intentional i believe, so that AI's cant jump into a mech in the corner of the map and be unkillable while they wait for the counter to tick down

pinpointer exists

**Comment by Moltijoe** [comment]
intended
