### ISSUE TITLE
No More pAI hats

### ISSUE THREAD

**Issue by Snellie12** [yogstation13/Yogstation#16593]
### Severity

Inconvenience

### Short Description

pAIs can no longer show on sprite if worn as a hat.

### Reproduction

1. Get a pAI
2. Scoop up pAI
3. Wear pAI as a hat
4. pAI does not show up as a hat on sprite
5. Cry because I cannot have funny cat or rat pAI hat show on my sprite.

### Round ID

Round #43905

### Test Merges

#14802 , #16364 , #16234

### BYOND Username

Snellie

### Additional information

The Test Merges given were just what shown on MOTD; I just follow what the Issue Report instructions say,  as I don't think mech edits and Jungleland would do anything with the lack of pAI hats.

**Comment by Maia-J** [comment]
I promised to look into this and I better should now so gimme a week or two
