### ISSUE TITLE
 Jungleland Fleshwalker wonky

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16629]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: If using a bouquet on a fleshwalker to tame it, it becomes untamed if it transforms into something. Also, the alpha after transforming will appear to be just like a regular one, despite keeping the stats of an alpha

 Submitted by: Molti (89554660418936832)

**Comment by MajManatee** [comment]
Unfinished pr, please refer to jungle land PR
