### ISSUE TITLE
Ivymen Take Damage from Jungleland Temp

### ISSUE THREAD

**Issue by Slauenza12** [yogstation13/Yogstation#16624]
### Severity

Inconvenience

### Short Description

As an ivy man you take some damage from the jungle being too hot

### Reproduction

Join as an ivy man
Wait 
Take a small amount of heat damage
Heal
Repeat 

### Round ID

43938

### BYOND Username

Slauenza12

**Comment by MajManatee** [comment]
Unfinished PR, please refer to jungle land PR
