### ISSUE TITLE
 Railings Block Immoveable Rod

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16638]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: Railings made in medbay were able to block a looping rod, which I don't believe is intentional.

 Submitted by: Ian (128360663436361729)

**Comment by wonderinghost** [comment]
no its funny

**Comment by Firewolf34** [comment]
Having trouble reproducing this one on 8a405ed27d82cdf9edb411c5c9d7015e65813035
Tried corner railings, and straight railings in medbay. Used the admin event to spawn rod aimed at target, it was not a looping rod, don't know if that makes a difference. I personally don't understand how it loops, even, the code doesn't really have a section for it, I think it happens as a side effect of the way the z-levels are set maybe?

It uses the standard move commands to traverse though and the railings block movement using the CanAllowMove() function I believe so I think this might be the area in code that's causing it:
https://github.com/yogstation13/Yogstation/blob/887cc8fcd87c3eb68f08d6a89f4d9ee8e0108800/code/game/objects/structures/railings.dm#L72

Might be some portion of these variables cause it to become blocked by railing, perhaps they are OK when it spawns but get modified after several loops through the z-level.
`return . || mover.throwing || mover.movement_type & checking`

I was unable to reproduce it on a fresh rod with railings but **it probably is a real issue** somehow, I've seen it before. just unsure how to debug it:

![rod-reproduce](https://user-images.githubusercontent.com/2159739/204342813-8db6dbc4-a308-4528-a965-ced5c366c375.gif)

**Comment by MajManatee** [comment]
horizontal rods can be stopped by placing a ralling while facing the way the rod is going

**Comment by MajManatee** [comment]
Unfortuatley resolved
