### ISSUE TITLE
ERT doesn't spawn implanted!!

### ISSUE THREAD

**Issue by Moja10** [yogstation13/Yogstation#1667]
Spawned ERT during revs and they just turned into revs. Makes you think... A lot...

**Comment by ThatLing** [comment]
CentCom can't afford to implant their personnel.

**Comment by ghost** [comment]
Looks like it depends on the ERT.  Centcomm officials do not but ERTs proper do.  I'll test it more.  For now it's not hard to do the modify organs thing in the VV dropdown and add the mindshield implant.

**Comment by Altoids1** [comment]
```dm
/datum/outfit/ert/post_equip(mob/living/carbon/human/H, visualsOnly = FALSE)
	if(visualsOnly)
		return

	var/obj/item/implant/mindshield/L = new/obj/item/implant/mindshield(H)
	L.implant(H, null, 1)
```
ERT are now apparently implanted. Closing issue.
