### ISSUE TITLE
 Aux base dosent work with jungle land

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16689]
## Test Merges: 
Not Supplied / None
## Reproduction:
Step 1: make aux base, Step 2: try to blind drop it/landing designator, step 3: realize you spent 5 minutes building an aux base for it only to not launch

 Submitted by: The Lusty E (302595577793740801)

**Comment by patpol4** [comment]
https://github.com/yogstation13/Yogstation/pull/14802

**Comment by MajManatee** [comment]
oh NOO!! five whole minutes??!?!?!?
Unfinished PR
