### ISSUE TITLE
Cannot surgically remove slime cores

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#1669]
Hitting a slime with a drape causes the slime to  simply be hit with the drape, even when placed on an operating table/table of any kind.

This is a bug as slime removal surgery exists in the code.

**Comment by SephiXarados** [comment]
Isn't that more of a Baystation 12 way of going about things? I mean, I can understand having to resort to this when Xenobiology loses power, but still. You might not even have to use drapes on the slime to extract its cores, I don't think.

**Comment by doerakpoes** [comment]
The TG station wiki even talks about this

**Comment by doerakpoes** [comment]
As in having it
