### ISSUE TITLE
Defib (exploding) bug??

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1672]
I encountered a defibrillator in an earlier round that blew up several times (flipping each time) while damaging everything around it.. apparently that was a bug, maybe this is similar to that.

I was defibbing someone (with a normal-looking defib) and at the exact moment of shocking, something blew up, and ripped my arm off. My PDA was intact and apparently no floor tiles were damaged under me (the windows in the image were already broken before), I was standing on the bottom part of medbay center, apparently only another defib was there, Admin couldn't trace the source of the explosion.

I picked up the "offhand" icon with my remaining hand (I was even able to pull that icon around), and walked away..

![ss13-defib-bug](https://cloud.githubusercontent.com/assets/16806055/22041085/b86f8eb0-dd05-11e6-8a17-4c3bee2c386b.png)

**Comment by Cruix** [comment]
It is possible that someone injected plasma into the power cell of the defib, which would cause it to explode whenever charge is drained from it, as it would be whenever you shocked someone.

The offhand falling was due to a bug with abstract objects and dismemberment.

**Comment by 00aquir** [comment]
but apparently the defib on the south side expoldoed (under the table). Not where I stood.

**Comment by Time-Green** [comment]
This is probably the best thing ever

**Comment by doerakpoes** [comment]
Killer queen already touched the defib

**Comment by Time-Green** [comment]
But yeah, I tested this and someone put plasma in the cell.
It even dismembered my arm and dropped the off hand.
