### ISSUE TITLE
 Turned in to a Light Source

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16721]
## Test Merges: 
Not Supplied / None
## Reproduction:
While in Cargo tried to look at a printed off Bounty Sheet that was about 10 minutes old. Character sprite vanished and turned in to a light source. Could interact with the world around me but couldn't be touched or examine myself with sprite specific actions. 
Steps to Reproduce: Open 10+ old minute printed Bounty Sheet after original Bounty Sheet updates.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1045589831020978316/unknown.png)
 Submitted by: Waywardstrid3r (220985084205858816)

**Comment by MajManatee** [comment]
Unable to repoduce
