### ISSUE TITLE
 You can use jump boot implants when dead

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16769]
## Test Merges: 
Not Supplied / None
## Reproduction:
Wee woo the corpse go BRRT. Probally preety OP, you can activate them perfectly fine when dead or crit and probally other leg implants

 Submitted by: ImmortalPlagueRat (605167460450304019)

**Comment by ChuChu42** [comment]
this also works when handcuffed, we had to dust a clown to stop it from breaking your bones while they are.dead
