### ISSUE TITLE
Atmos Hardsuit does not give full pressure/fire resistance

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation#168]
Event: Wore an atmos hardsuit to burn down an alien hive.Died partially due to pressure and fire damage.

Expectation: Be fully resistant to flame and pressure in an atmos hardsuit.

Solution: Bring back our old atmos hardsuit.

**Comment by X-TheDark** [comment]
Sorry for doubting you, but are you completely sure that atmos suit doesn't protect from the aforementioned circumstances.

Here's a test I've ran, and it seems like atmos suit is working exactly as it should:
http://imgur.com/TBSgGrQ

**Comment by Super3222** [comment]
@EMT321 I'm going to close this in a few days unless you give us some proof of a problem. This seems fine in game.

**Comment by EMT321** [comment]
It's entirely possible I was in the wrong, closing.
