### ISSUE TITLE
Ore redemption machine in golem base alerting scientists

### ISSUE THREAD

**Issue by Slinky5890** [yogstation13/yogstation#1682]
When golems deposit ores into their machine, it alerts science on the requests consoles, making them go to cargo to find nothing there. This has severla times resulted in scientists shouting at cargo for stealing their ores when in all actuality there never were any ores.

**Comment by monster860** [comment]
This is made worse by the fact that free golems deposit ores more frequently than normal miners (Because every ash storm they go inside their ship where the ore machine is on the ship)
