### ISSUE TITLE
Ghost role Surgery Research connecting to computers

### ISSUE THREAD

**Issue by Moltijoe** [yogstation13/Yogstation#16830]
### Severity

Inconvenience

### Short Description

Surgery computer doesn't recognize researched surgeries

### Reproduction

1. Select a ghost role that can research
2. Research surgery
3. try to update surgery computer
4. fail

### Round ID

any

### Additional information

Probably a case of surgery computers always pulling from the station's research web, so ghost role ones are synced to the wrong research web

**Comment by ShoziOffical** [comment]
yep
