### ISSUE TITLE
Hierophant makes vision permamently purple.

### ISSUE THREAD

**Issue by UltraBigRat** [yogstation13/Yogstation#16852]
### Severity

Inconvenience

### Short Description

After being hit by hierophant (not being critted) vision gains a permament purple overlay until i die.

### Reproduction

1. Fight hierophant
2. Get hit by it
3. Everything is now purple and hard to see
4. does not go away
5. keep fighting
6. die and get dusted
7. vision ends up reverting when i die.

### Round ID

Round 44116

### Test Merges

#16232 #16770

### BYOND Username

UltraNumeron

**Comment by MajManatee** [comment]
Unable to reporduce
