### ISSUE TITLE
 Battle Royale Instantly Ends The Game On Round Start

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16862]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: Battle Royale ends the round on gamestart instead of letting people actually play.

 Submitted by: Hisakaki (98481061960351744)

**Comment by Simplehorror** [comment]
the code of this gamemode is the most unfunniest shit i have ever read

**Comment by MajManatee** [comment]
gamemode is unsuported, but i think this was fixed
