### ISSUE TITLE
 VR Characters get on Station

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#16885]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: In the new VR feature you spawn in a "hub" that is surrounded entirely by hyperspace. Breaking any of the multiple windows you are able to jump out and by a small chance, end up in the same Y Level as the station. If you get a good spawn you'll be able to get onto the station and do pretty much anything. I'm sure with xeno fuckery you could even unpacify yourself, not 100% sure. You are even able to go into VR as a VR clone and do this as many times as you want. Not sure if this is a bug, but it definitely doesn't seem intentional.

 Submitted by: Brick (826157005710032926)

**Comment by ChuChu42** [comment]
in theory you can get on the station with OP gear using this
