### ISSUE TITLE
Tcomms traffic control console and tcomms server monitoring console cannot detect servers in "tcommsat" network

### ISSUE THREAD

**Issue by warface1234455** [yogstation13/Yogstation#16960]
### Severity

Inconvenience

### Short Description

The servers are set to "tcommsat" network but the consoles say otherwise

![image](https://user-images.githubusercontent.com/89688125/205676546-49bd9fef-efea-47e9-9985-6ed910cfae70.png)

### Reproduction

1. Join round as network admin
2. checks tsmc or ttcc 
3. it says cannot detect!!

### Round ID

Round #44216

### Test Merges

#16876

### BYOND Username

Warface1234455

**Comment by ShoziOffical** [comment]
used to be working before, not sure why it is broken now, prob testmerge or someone bussed it

**Comment by ShoziOffical** [comment]
nvm this was because not in range, which is dumb
