### ISSUE TITLE
space law books don't contain any space law

### ISSUE THREAD

**Issue by restedwaves** [yogstation13/Yogstation#16973]
### Severity

Quality of Life

### Short Description

how will i ever throw the book at criminals saying their sentance is wrong without a book of law?

### Reproduction

1. open space law
2. gaze upon the blank page
![image](https://user-images.githubusercontent.com/90993960/205798946-1604270a-7639-4af5-ad6f-30343fd1199e.png)

### Round ID

44225

### Test Merges

#16876

### BYOND Username

RestedWaves

**Comment by Notamaniac** [comment]
There's a html error, unfortunately I don't know enough on the backend to fix this (and my HTML is extremely rusty)

![html](https://user-images.githubusercontent.com/17688334/208208318-7870216c-5f68-41a9-b8c4-424b5b23630b.PNG)

**Comment by MajManatee** [comment]
Resolved
