### ISSUE TITLE
Mad scientist syndi kit special sometimes flashbangs you immediatly upon buying it.

### ISSUE THREAD

**Issue by UltraBigRat** [yogstation13/Yogstation#17025]
### Severity

Inconvenience

### Short Description

Bought syndi kit special and upon receiving my mad scientist box, the flashbang clusterbang went off and flashbanged me six times. This left me disoriented for several minutes.

### Reproduction

1. Buy syndi kit special
2. Receive mad scientist kit.
3. Have a chance for one of your random clusterbangs to activate instantly with no trigger and release a shitfuckton of flashbangs near you.
4. Cope as you have random movement for several minutes.

### Round ID

Sadly i forgot, all i know is i was a lawyer traitor that round.

### BYOND Username

UltraNumeron

### Additional information

Forgot to write this earlier when it occured, so didnt get the round id for it.

**Comment by Simplehorror** [comment]
probably because the random clusterbang type doesn't exclude /obj/item/grenade/clusterbuster/segment, lol

**Comment by Firewolf34** [comment]
This is a funny one

**Comment by MajManatee** [comment]
Resolved, technically
