### ISSUE TITLE
 Unholy pitchfork has no sprite

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17023]
## Test Merges: 
Not Supplied / None
## Reproduction:
the null option unholy pitchfork has no sprite and is treated as a empty hand I grabbed a potted plant and it vanished.

 Submitted by: Praise (385228641820344324)

**Comment by Notamaniac** [comment]
Can't replicate, null rod pitchfork has a sprite, and clicking on a plant just made it go into the plants storage.
