### ISSUE TITLE
Hacking booze dispenser causes tools to disapear

### ISSUE THREAD

**Issue by CherryCatGal** [yogstation13/Yogstation#17047]
### Severity

Inconvenience

### Short Description

When using a multitool or wirecutters on a booze dispenser, they disapear instead of opening the hacking menu

### Reproduction

1. Joined as engineer
2. Used screwdriver on Booze Dispenser
3. Used multitool/wirecutters on Booze Dispenser
4. Tool disappears, makes putting item on table sound

### Round ID

Round #44317

### Test Merges

#16989

### BYOND Username

CherryCatGal

### Additional information

I tried removing the table beneath the booze dispenser, had no effect. Have not tested the soda dispenser, or any other machines.

**Comment by ChuChu42** [comment]
booze dispensers on some maps are built on a table, which map is this?

**Comment by CherryCatGal** [comment]
My apologies, this was on yogstation/boxstation

**Comment by Notamaniac** [comment]
all chem dispensers do this - the wirecutters get moved inside of the machine for some reason and are dropped when it's deconstructed
