### ISSUE TITLE
why is bigotry in the filter?

### ISSUE THREAD

**Issue by doerakpoes** [yogstation13/yogstation#1704]
so whenever i say ''Bigotry'' the filter is triggered WHY?

**Comment by Jc1469** [comment]
Our filters used to only affect OOC, so saying "bigotry" in OOC would replace it with "banned words".  
It now also affects IC chat, and instead completely blocks the message.

I expressed my dislike of IC filters, and I still do.
@AsV9 Fix or delete.

**Comment by drderp3635** [comment]
Bigotry is banned as a meme.
