### ISSUE TITLE
 Singo shields spontaniously fail for no reason

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17060]
## Test Merges: 
Not Supplied / None
## Reproduction:
Watch the replay, the fields fail randomly all at once for 0 reason. No outside interference, emitters were fine, undamaged
https://replays.yogstation.net/?roundid=44351&send_credentials=1#49414;117.50;68.73;2;null;1.0

 Submitted by: ImmortalPlagueRat (605167460450304019)

**Comment by Notamaniac** [comment]
Without logs I can't be certain but at 1:22:52 you can see the middle left field generator get destroyed. I would guess that would be because of everything hitting the field generator, causing damage to the machine but I can't see logs so yeah

**Comment by ToasterBiome** [comment]
Not a bug, I suspect the stage 4 singulo is throwing the 3 stacks of iron rods on the left with such force that it broke the shield generator. This engine was also set up incorrectly if it was this size.

https://wiki.yogstation.net/wiki/Singularity_Engine#7._Fire_it_up!
