### ISSUE TITLE
Sepia tinted camera does not work

### ISSUE THREAD

**Issue by UltraBigRat** [yogstation13/Yogstation#17066]
### Severity

Inconvenience

### Short Description

Sepia tinted camera just acts like a normal one use camera, and does not stop time as it should.

### Reproduction

1. make burning sepia extract
2. turn it into sepia tinted camera
3. take a picture of someone
4. it makes a normal picture and time is not stopped
5. the camera no longer has any pictures left it can take
6. Have spent 10 orange extracts and an adult sepia slime on one normal photo.

### Round ID

44358

### Test Merges

#16989 #17049

### BYOND Username

UltraNumeron

### Additional information

I did also click it around after using it, and yep there is only a standard mode, and no other modes to switch to.

**Comment by Notamaniac** [comment]
this feels like deja vu...

The burning sepia camera doesn't stop time, it just captures the state someone was in, then rewinds them to that state after ten seconds. The wiki wasn't updated when that change was made.

**Comment by UltraBigRat** [comment]
Wiki should probably be updated then
