### ISSUE TITLE
Plort redemption machine is permamently invisible after screwdrivering it.

### ISSUE THREAD

**Issue by UltraBigRat** [yogstation13/Yogstation#17065]
### Severity

Inconvenience

### Short Description

When you use a screwdriver on a plort redemption machine (to upgrade it for instance) it will become completely invisible, and even after using the alt click menu to close it up, it will still be invisible until an admin fixes it.

### Reproduction

1. go to xenobio
2. screwdriver plort redemption machine
3. no matter what it will now permamently be invisible

### Round ID

44358

### Test Merges

#16989 #17049

### BYOND Username

UltraNumeron

**Comment by gtdrw** [comment]
It looks like the issue might be fixed, but I'll test it out tonight and confirm. I played last night, checked out a book with my own ID, and was able to access the console/use the features without a hitch multiple times.
