### ISSUE TITLE
Put extended game mode into rotation

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#1708]
Lets get some high quality rp into this shit boi.

 To spice things up, you could give people fluff objectives like: start a new religion, get your department to start a fued with (insert random dept), decorate the station, lead a petition with at least 25 signatures, make as many friends as possible, make as many enemies as possible, etc.

**Comment by Jc1469** [comment]
whats an rp?  can I use it to hunt down the antags easier?

**Comment by AdamElTablawy** [comment]
Honestly, why not? I don't see a problem with it.

Extended is a nice peaceful way to get things done on the station.

Of course it's just the shitter safari for admins.

There's also plenty of antagonism to go around from lavaland hostiles, etc.

**Comment by AdamElTablawy** [comment]
As for the other shit-Eh, I can work on 'station goals' like /tg/ did.

**Comment by Rafael450** [comment]
YEAHHHH, MAKE EXTENDED GREAT AGAIN

**Comment by Dagdammit** [comment]
I'm fine with either option, but extended with station goals sounds really exciting.
