### ISSUE TITLE
Debug hardsuit dosent completelly work

### ISSUE THREAD

**Issue by Gboster-0** [yogstation13/Yogstation#17116]
### Severity

Low

### Short Description

Debug hardsuit shows all 100% defences, but you still take damage inside of it

### Reproduction

1. Get a debug hardsuit
2. Check its defences
3. X defence (100%) across the board
4. Hit yourself with glass (or any item really)
5. Take damage despite the hardsuit having 100% resistance, and saying that your armor "absorbed the hit"

### Round ID

Round #44459

### Test Merges

#17049

### BYOND Username

gboster

### Additional information

the debug hardsuit should probably make the user immortal, aint that its entire goal?

**Comment by Notamaniac** [comment]
I think damage reduction is hard capped at 80%, with additional armour only mattering for AP. Don't quote me on that, dealing damage is layered behind multiple procs and at least a hundred or so lines of cope.

**Comment by MajManatee** [comment]
wont be fixed.
