### ISSUE TITLE
 cannot deconstruct clock cult walls properly

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17117]
## Test Merges: 
Not Supplied / None
## Reproduction:
You can only deconstruct clock cult walls (brass walls or whatever) when they are DIRECTLY infront of you, meaning that you can only slowly open them up 1 by 1, leading to you immediately always getting blasted by anyone on the other side

 Submitted by: Cowbot (97736956326207488)

**Comment by Notamaniac** [comment]
can't replicate, does this only happen on reebe?

**Comment by ReddicusDragon** [comment]
Cowbot says no bug, Issue closed
