### ISSUE TITLE
pAI drops endless stream of datacables

### ISSUE THREAD

**Issue by Colburn3000** [yogstation13/Yogstation#1712]
[Round ID]: # 17277

[Reproduction]: # I think you could try to reproduce this issue by spawning in as a pAI then disconnecting and reconnecting. Though I am not sure what exactly prompted this. Maybe it is in the logs? It was fixed by wiping the pAI.

![data cable](https://user-images.githubusercontent.com/24303426/42632827-810f026a-85ac-11e8-9306-81104e16e855.jpg)

Ahelp log:

01:21:03 - Colburn3000 - Colburn3000/(HONKZILLA) PM'd Pokebro2000/(BLaDOS) 

01:21:03 - Colburn3000 - i understand the memeliciousness of it, but dumping hundreds of datacables on the floor might not be good for the seber 

01:21:44 - Colburn3000 - it seems okay right now, but if it starts lagging, I'll have to ask you to stop 

01:21:46 - Pokebro2000 - Hey, i aint doing this. Im constantly dropping them for some reason, despite not even getting that doorjack thing 

01:21:57 - Pokebro2000 - ill reconnect, see if that stops it 

01:22:05 - Colburn3000 - okay, oh dear 

01:22:13 - Pokebro2000 - yeah, brb 

01:22:14 - Pokebro2000 - Client disconnected. 

01:22:47 - Pokebro2000 - Client reconnected. 

01:23:17 - Pokebro2000 - Hoo boy, i think it sped up 

01:24:50 - Colburn3000 - umm lets try something 

01:26:57 - Colburn3000 - do you know when it started? I am writing up a github issue 

01:28:00 - Pokebro2000 - It started about 10 minutes ago, when i reconnected. Apparently i was making the cables while i was logged out, had to go afk. they were all over the room, though, not in the place i was 

01:28:43 - Colburn3000 - did you try to activate the doork hack before you deconned? 

01:28:57 - Pokebro2000 - They've been randomly dropping since, although it did get more frequent the further from then it happened 

01:29:14 - Pokebro2000 - Nope, i only downloaded it a few seconds ago to see if it would stop(?|F) it 

01:29:26 - Colburn3000 - so strange 

01:29:56 - Pokebro2000 - tbh, i suspect admin fuckery, since it stopped when i went afk and said that, then restarted when i said i was back 

01:30:13 - Colburn3000 - nah its not us 

01:30:21 - Pokebro2000 - Really? wow. 

01:30:33 - Pokebro2000 - I thought it was one of you memeing for a while 

01:32:11 - Pokebro2000 - just got a message saying the spool retracted and the spam stopped. 

01:33:14 - Colburn3000 - weird... what caused that? 

01:33:40 - Pokebro2000 - No idea, but it started back up for a good 20(?|F) seconds before i just got wiped 

01:35:05 - Pokebro2000 - Well, it seems to have stopped since i was wiped, so theres that 

01:35:20 - Colburn3000 - Okay, thanks for the help 

01:35:38 - Pokebro2000 - Its the least i could do. Hopefully we figure out what caused that headache 

01:35:59 - Pokebro2000 - HOLD UP. was that data cable there before? 

01:36:39 - Pokebro2000 - i THINK we're safe now. false alarm, maybe

**Comment by Amelia0010** [comment]
hm
