### ISSUE TITLE
 Heretics can use their knife teleport when jaunting

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17122]
## Test Merges: 
Not Supplied / None
## Reproduction:
Unsure if this is a bug or unintended feature but if a heretic uses a jaunt ability (their ash walk) they can smash their knife, teleporting them to infinite safety, they are also able to do this while stunned.

 Submitted by: Cowbot (97736956326207488)

**Comment by MajManatee** [comment]
resolved
