### ISSUE TITLE
Book inventory management console crash

### ISSUE THREAD

**Issue by YashinHak** [yogstation13/Yogstation#17167]
### Severity

Inconvenience

### Short Description

Book inventory management console randomly went to a NTOS bluescreen.

### Reproduction

1. Join the round as a librarian
2. Print books using the Book inventory management console
3. Then search for a series of books, printing all of them out too
4. Attempt to use the console again after leaving the search menu
5. See the bluescreen

### Round ID

Round #44560

### BYOND Username

yashinhak

### Additional information

Script error.
   at https://cdn.yogstation.net/assetcache/asset.a3bb75a70f4b3ebca2df75d63c5a04d5.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"yashinhak","interface":"LibraryConsole","window":{"key":"[0x200b8b8]-main","size":null,"fancy":1,"locked":0}}

**Comment by ReddicusDragon** [comment]
Hello! Please let me know if this is still an issue.

**Comment by patpol4** [comment]
tested, still an issue

**Comment by patpol4** [comment]
![image](https://user-images.githubusercontent.com/48154165/212410020-89e58b0a-0d3e-4e93-af5f-de8f9c013214.png)

**Comment by patpol4** [comment]
looked through some issues, appears to be duplicate of https://github.com/yogstation13/Yogstation/issues/17056
