### ISSUE TITLE
Neck-grappling aliens don't exist, must be a false alarm

### ISSUE THREAD

**Issue by CurrTheLost** [yogstation13/Yogstation#17165]
### Severity

Inconvenience

### Short Description

Scarves as a Divergency doesn't give scarves. Ever. It's also constantly occurred with a very high chance.

### Reproduction

1. Join game
2. No scarves
3. Divergency alert
4. No scarves
5. It's happened every time
6. No scarves

### Round ID

#44559 (not relevant, though)

### Test Merges

n/a

### BYOND Username

CurrTheLost

### Additional information

WHERE ARE THE SCARVES

**Comment by MajManatee** [comment]
what  the FUCK does this mean
