### ISSUE TITLE
On nuke ops, a nuke that activates off station still destroys the station, but does not end the round.

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#17171]
### Severity

Round Breaking

### Short Description

title

### Reproduction

1.) gamemode : nuke ops
2 activate the nuke but leave the nuke unanchored
3.) push the nuke off station z-level and wait for the nuke to activate
4.) massive lag spike
5.) nuke destroys station despite being off z-level (which shouldn't happen)
6.) nuke does not force the round to end (the round should end)
7.) crew major victory since nuke detonated off station but the station gets destroyed anyways
8.) you now have to wait for the shuttle to arrive because the round doesn't end

### Round ID

#44575

### BYOND Username

TheBombMaker

### Additional information

Crew Major Victory
Nukies take the L

**Comment by SomeguyManperson** [comment]
have noticed that for some reason the nuke always explodes on z 2 rather than wherever it is

**Comment by patpol4** [comment]
didnt this get fixed @JamieD1
