### ISSUE TITLE
 Mesons cant see false walls

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17174]
## Test Merges: 
Not Supplied / None
## Reproduction:
False walls appear as empty tiles to mesons this makes it very easy to find secret bases, which is especially bad on antags that rely on them like bloodsuckers. I heard its something about them not counting as a turf but not sure. Either ways its pretty dumb.

 Submitted by: Ultra (225615376828989440)

**Comment by Notamaniac** [comment]
I think this is an intended feature, rather than a bug, assuming the title is : Mesons _can_ see false walls

**Comment by ynot01** [comment]
i looked through false wall code and im fairly sure the type can be swapped out with a turf version with minimal issue

only question is whether we actually want this

**Comment by ReddicusDragon** [comment]
> i looked through false wall code and im fairly sure the type can be swapped out with a turf version with minimal issue
> 
> only question is whether we actually want this

I think it'd be a bad idea, as it would make it easier for antags to just lazily put a secret base in a main area of maintenance areas.

**Comment by MajManatee** [comment]
This is an intended feature of mesons
