### ISSUE TITLE
 Bluespace bodybag duplication

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17172]
## Test Merges: 
Not Supplied / None
## Reproduction:
get in a bluespace body bag, get someone to pick you up and place you on t table whilst folded, click the folded body bag whilst in it, get someone to pick up and release you, giving you an infinite bodybag

 Submitted by: Vance Pants (973199365466382396)

**Comment by patpol4** [comment]
duplicate of https://github.com/yogstation13/Yogstation/issues/17173
