### ISSUE TITLE
Put on the drip, put on the shoes, get mood... enabled?

### ISSUE THREAD

**Issue by CurrTheLost** [yogstation13/Yogstation#17195]
### Severity

Inconvenience

### Short Description

Mood enabled when incredibly fashionable outfit.

### Reproduction

1. find incredibly fashionable outfit somehow (or the shoes)
2. incredibly fashionable outfit equipped.
3. wait
4. why's my mood on

### Round ID

44619

### Test Merges

13479

### BYOND Username

CurrTheLost

### Additional information

May work on the shoes too.

**Comment by neeshacark** [comment]
intended feature of the item.

**Comment by CurrTheLost** [comment]
Doubt.

**Comment by neeshacark** [comment]
> Doubt.

its the single strongest uniform in game, it needed a downside

#15089

**Comment by Moltijoe** [comment]
intended feature, don't take it off
