### ISSUE TITLE
Sosig in hand gets snipped out of existence

### ISSUE THREAD

**Issue by CurrTheLost** [yogstation13/Yogstation#17201]
### Severity

Inconvenience

### Short Description

Sausage deleted by being snipped with knife when in hand

### Reproduction

1. Be someone with sosig and knife
2. Cut sosig with knife, in-hand and not anywhere else
3.
4. where did it go

### Round ID

44631

### BYOND Username

CurrTheLost

### Additional information

I AM THE BUG FINDER

**Comment by ReddicusDragon** [comment]
I actually vaguely remember this bug, I will investigate
