### ISSUE TITLE
PLEASE, DO NOT mix the Meteor Shuttle and the Atmos System again.

### ISSUE THREAD

**Issue by CurrTheLost** [yogstation13/Yogstation#17202]
### Severity

Round Breaking

### Short Description

Wind proceeded to pull everyone back and forth in the Meteor shuttle... back and forth... killing many people. Kept going until the shuttle essentially spaced itself from leaving.

### Reproduction

1. Meteor Shuttle
2. Attempt to get on
3. Space wind... due to atmos system.

### Round ID

44632

### Test Merges

None, but it's definitely the in-use atmos system.

### BYOND Username

CurrTheLost

### Additional information

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by patpol4** [comment]
probably  #13479, also i think this used to happen before and its why the meteor shuttle has airlocks

**Comment by MajManatee** [comment]
its complicated
