### ISSUE TITLE
 Gibtonite defusal on plasma shotgun occasionally does not work as intended

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17225]
## Test Merges: 
Not Supplied / None
## Reproduction:
While normally the issue I face is that the defusal does not truly defuse the gibtonite and instead continues to let it react compared to the normal case of harvesting a 9 reactions left gibtonite, in this case after installing the upgrade I fired it and the gibtonite detonated instantly, leading to my untimely death.

 Submitted by: iamcooldan (333809822803820544)

**Comment by MajManatee** [comment]
should have been fixed...?
