### ISSUE TITLE
You can sell invicibility talisman from lavaland indefinitely to CentCom via supply shuttle

### ISSUE THREAD

**Issue by LikelessCassidy** [yogstation13/Yogstation#1724]
Issue reported from  Round ID: 17302 (Yogstation 13 [99% LAGFREE!])

Reporting client version: 512

The talisman will not despawn but will still give money everytime

**Comment by Amelia0010** [comment]
💯

**Comment by LikelessCassidy** [comment]
shit's fucked brah

**Comment by ThatLing** [comment]
sounds like a feature

**Comment by Moja10** [comment]
fixed
