### ISSUE TITLE
Traitors can roll survive alone (hijack but kill traitors too) without another traitor having hijack.

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#17278]
### Severity

Round Breaking

### Short Description

Despite the original intention of the pr #16785 - traitors can roll the new objective without another antagonist even having hijack. In this case it happened to Leguminivora Dentata whos ckey is Mochrum1

### Reproduction

1. roll survive alone
2. no other tots have hijack
3. end up redtexting a bunch of people because code

### Round ID

Round #44725

### BYOND Username

Cark

**Comment by MajManatee** [comment]
Definetly doesnt sound roundbreaking. Sounds like you just have hijack and have to survive alone.
