### ISSUE TITLE
Buildmode repair does not work

### ISSUE THREAD

**Issue by ThatLing** [yogstation13/Yogstation#17282]
### Severity

Inconvenience

### Short Description

Buildmode repair does not work

### Reproduction

1. Go into buildmode
2. Select either:
  a. Repair: Reload Block - Mass Delete
  b. Repair: Reload Block - Mass Delete - In Place
3. Use it on a part of the station
4. It just deletes stuff without rebuilding it

### Round ID

44727

### Additional information

Caused by https://github.com/yogstation13/Yogstation/blob/master/code/modules/mapping/reader.dm#L764-L767. The turf is first removed, which will make it NULL when trying to replace it. The previous version of the code didn't have this check, no clue how it worked. I tried putting a ``sleep`` in the repair proc, which made the turf not NULL but it still wouldn't rebuild properly

**Comment by patpol4** [comment]
Also broke placing uploaded map templates

**Comment by MajManatee** [comment]
resolved :)
