### ISSUE TITLE
Pressing the settings gear on the chat crashes tgui

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#17285]
### Severity

Quality of Life

### Short Description

what it says on the tin, you cant configure tgui to add highlights n stuff rn

### Reproduction

1. try to edit your tgui
2. die

### Round ID

N/A

### BYOND Username

Cark

**Comment by ReddicusDragon** [comment]
Hello! Is this still an issue?

**Comment by ThatLing** [comment]
Fixed
