### ISSUE TITLE
Dedicated BSOD button on all tgui 

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/Yogstation#17299]
### Severity

Inconvenience

### Short Description

There is now a dedicated BSOD button on all tgui that will force it to crash

### Reproduction

1. Open a tgui menu
2. Press the bug button
![dedicated bsos button](https://user-images.githubusercontent.com/17688334/210449749-ffd9ca19-23b0-4825-abfa-a3677e517f79.PNG)

3. Crash tgui

### Round ID

44734

### Test Merges

#16933: 'rad weaponry update: xray nerf, bouncer egun addition' by 00ze-cyclone at commit 240231f52c #16821: 'Adds a new melee-focused mech: The Sidewinder!' by Mqiib at commit 51f5ca324f #17284: 'TG UPDATE 1: Juke Build' by JamieD1 at commit 96fb9a0fe4

**Comment by ThatLing** [comment]
its a feature

**Comment by Notamaniac** [comment]
seems to be fixed now
