### ISSUE TITLE
 Plasma converter cannot actually be loaded

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17307]
## Test Merges: 
Not Supplied / None
## Reproduction:
The plasma converter module is unable to actually load plasma sheets
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1060149616399630336/Capture_decran_20230104_115334.png)
 Submitted by: JellyRain (846634033622417470)

**Comment by ReddicusDragon** [comment]
if this isn't tested on the actual server itself I'm not really sure I can call it an issue. Please confirm this to be the case on the server as well.

**Comment by ReddicusDragon** [comment]
Re-open this issue if the case remains the same on the server proper
