### ISSUE TITLE
 PDA power monitor app no longer works

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17314]
## Test Merges: 
Not Supplied / None
## Reproduction:
The PDA power monitor app isn't connected to the station power grid monitor by default but to I believe tcomms or ai sat; PDA one is on the right, console is on the left.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1060269882203181157/image.png)
 Submitted by: Weeb Gamer (305818411462557696)

**Comment by ReddicusDragon** [comment]
seems to be resolved
