### ISSUE TITLE
PanD.E.M.I.C 2200 Symptom Sampling Script

### ISSUE THREAD

**Issue by 0Maltony0** [yogstation13/Yogstation#17320]
### Severity

Round Breaking

### Short Description

Error message while using virology machine

### Reproduction

1. Join round as Virologist
2. Add blood sample with virus of your choosing into the machine
3. Click symptom name to isolate it
4. Receive script error message:
    Script error.
   at https://cdn.yogstation.net/assetcache/asset.9815e7b8933f2b6dfbd050e85012f49c.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"strzelecms","interface":"Pandemic","window":{"key":"[0x2007287]-main","size":null,"fancy":1,"locked":0}}

### Round ID

#44751

### Test Merges

#16933, #16821

### BYOND Username

Strzelec_MS

**Comment by ReddicusDragon** [comment]
Issue confirmed.

**Comment by ReddicusDragon** [comment]
fixed with #17409
