### ISSUE TITLE
 More TGUI BS I'm assuming

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17323]
## Test Merges: 
Not Supplied / None
## Reproduction:
Pressed tab to get hotkeys working, press or click anything and they turn off.

 Submitted by: Gramredhel (124672649782624256)

**Comment by ThatLing** [comment]
For future reference

![image](https://user-images.githubusercontent.com/24573384/210738878-d63e5752-d520-4854-a5f1-34e6e528c8f7.png)
