### ISSUE TITLE
Voice announcements not voicing

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#17337]
### Severity

Inconvenience

### Short Description

Voice announcements not voicing

### Reproduction

1. Make a voice announcement
2. The jingle will happen but no voice comes out

### Round ID

44757

### Test Merges

#16933 #16821

### BYOND Username

Ynot01

**Comment by ReddicusDragon** [comment]
duplicate of https://github.com/yogstation13/Yogstation/issues/16121
