### ISSUE TITLE
Dilithium is... no longer a thing!

### ISSUE THREAD

**Issue by CurrTheLost** [yogstation13/Yogstation#17359]
### Severity

Inconvenience

### Short Description

It's stopped existing. I blame TGUI.

### Reproduction

1. Check your nearest machine (ore silo, Ore Redemption, protolathe)
2. No Dilithium?

### Round ID

44761

### Test Merges

16933, 16821

### BYOND Username

CurrTheLost

### Additional information

freeminers round, so. it could be that. or it could be tgui.

**Comment by ThatLing** [comment]
fixed
