### ISSUE TITLE
Pinpointer Breaking

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation#1737]
A nuke op round someone chased the nukeops back to the shuttle, killed one, and the pinpointer was pointed at the nukeop shuttle door despite the disk not being there. It was most likely in the possession of the nukeop who was killed and gibbed, the disk teleported away when it was deleted, and the pinpointer did not update for some reason.

**Comment by GrayRachnid** [comment]
Toggling the pinpointer off and on should fix it, no?
