### ISSUE TITLE
Admin announcements are not sanitised.

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#1738]
Tested by making something bold and making some text massive and red.

**Comment by YogsMcree** [comment]
Sounds annoying and intrusive. Pictures or that's gonna be a solid please no from me

**Comment by AdamElTablawy** [comment]
Please no what mcree
It's a bug report.

**Comment by YogsMcree** [comment]
Is it ? I thought it was a complaint that admin announcements weren't in your face enough

**Comment by ToGWtF** [comment]
but that means no narsie memes in admins announce

**Comment by Time-Green** [comment]
What's the problem with this? If admins wanna make it cancerous, well, they can.
I assume it's only admin, and I hope they understand not to totally abuse it to crap

**Comment by Groudonmaster** [comment]
Too be fair it's used sometimes because let's be honest the standard announcement text is small and easy to miss unless it's a long message
