### ISSUE TITLE
Abductor objective is incorrect

### ISSUE THREAD

**Issue by Dagdammit** [yogstation13/yogstation#1743]
Abductors are told they must experiment on 6 subjects. What they really have to do is reach a total of 6 unspent research points by experimenting on subjects. 

As it stands, novice abductors are making the very reasonable (and completely incorrect) assumption that there's no penalty for spending the research points at the console. Console itself should probably also warn them that they're about to spend their victory condition.

**Comment by Time-Green** [comment]
Could you do it? You're a coder invite right?
If you don't want to, don't.

**Comment by Dagdammit** [comment]
I... I don't think I am? X added me to the coder chat on yogs discord, but that seems like about it.

I mean at this point I'm not averse to trying to make that leap, would definitely prefer knowing ss13 code well enough to actually implement some of these things and just submit the PR. Got a lot to learn, though.

**Comment by Jc1469** [comment]
WOW. CODER INVITE AND BITCHING INSTEAD OF CODING? WHAT THE FUCK.

really all it needs is a text change for their objective text to "unspent points" or something.
