### ISSUE TITLE
Conflicting Genes can be on the same person, leading to a sort of limbo when unlocking the second conflicting gene

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#17438]
### Severity

Inconvenience

### Short Description

title

### Reproduction

1.) get unlucky with your catatonic monkey humans and get one that has two conflicting mutations (space adapt and heat adapt for instance)
2.) unlock space adapt
3.) try to unlock heat adapt (which is at the moment an unknown gene)
4.) get all A-T and G-C pairs correct
5.) the yellow outline to the previously X-X pairs disappear indicating that you got all the pairs correct and the gene should unlock
6.) the gene does not unlock because space adapt conflicts and is already on the person
7.) the console gives you no indication of this or that it's because space adapt is conflicting
8.) think you're stuck in limbo because you solved the gene but you can't see what the gene is
9.) remove the space adapt gene (if you're somehow able to figure out this is why) 
10.) heat adapt is immediately unlocked

### Round ID

any

### BYOND Username

TheBombMaker

**Comment by Chubbygummibear** [comment]
i have a fix for this coded and ready to go so when generating mutations it just checks if the next mutation it's about to add conflicts with one the DNA already has, but waiting until the freeze is over to PR it
