### ISSUE TITLE
Surgical Arm tools cannot complete certain surgical steps, such as the dissection in experimental dissection

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#17439]
### Severity

Inconvenience

### Short Description

title

### Reproduction

1.) with a surgical arm toolset, attempt to complete certain surgeries
2.) be unable to use the arm for certain steps

Example of steps that the surgical arm cannot complete :
Perform Dissection - Any dissection surgeries
Remove the Fat  - Lipoplasty 
(Possibly) Alter the patient's appearance - Plastic Surgery

### Round ID

any

### Additional information

unsure why these steps can't be done specifically, the only connection between the steps of dissection and extract fat is that it generates an item (the paper for research points + fat, respectively), the surgery might demand specifically scalpel/laser scalpel (spaghetti)

**Comment by ReddicusDragon** [comment]
Going to test.

**Comment by ReddicusDragon** [comment]
Issue confirmed, working on a fix.

**Comment by ReddicusDragon** [comment]
One thing of note, the code says the remove fat step in lipoplasty is with a hemostat, NOT a hemostat. I ran out of time so I can't finish fixing it today.
