### ISSUE TITLE
 transfering golem shells as a golem removes antag status

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17445]
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: title; beint a golem then clicking on a complete golem shell to transfer removes antag

 Submitted by: ImmortalPlagueRat (605167460450304019)

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/issues/13245

same issue

**Comment by MajManatee** [comment]
issue already open x3
