### ISSUE TITLE
Sole Survivor objective restricts Hijack uplink items

### ISSUE THREAD

**Issue by jachlompsky** [yogstation13/Yogstation#17442]
### Severity

Inconvenience

### Short Description

If you get the objective to escape on the shuttle with nobody else, you can't get uplink items that require hijack despite sole survivor being basically the same thing. (and then you gotta bug the admins to TC trade it for you)

### Reproduction

1. be traitor with sole survivor objective
2. attempt to buy hijack-only item (ex: romerol)
3. your objectives do not permit this item

### Round ID

44835

### BYOND Username

Jachlompsky

**Comment by ReddicusDragon** [comment]
As of Feb 3rd, 2019, Romerol was restricted to Glorious Death & Hijack only. Hijack & Sole Survivor are not the same thing. Romerol should not be available to sole survivor solely because the zombies may kill their creator. Do you have any other example of restricted items?

**Comment by jachlompsky** [comment]
> As of Feb 3rd, 2019, Romerol was restricted to Glorious Death & Hijack only. Hijack & Sole Survivor are not the same thing. Romerol should not be available to sole survivor solely because the zombies may kill their creator. Do you have any other example of restricted items?

Looking at the code, there aren't ANY items that are allowed with datum/objective/sole_survivor. Seems like the uplink didn't get updated when sole survivor was added. Also, I don't see the point in restricting Romerol specifically. You could end up getting killed by your own singularity beacon, for example, but that's available to both martyr AND hijack. Romerol can be used to ensure you revive after death, or to try and cut down the station's population, or make sure everyone you're killing is slow and can't hold anything. I'm sure most people buying Romerol would be prepared for the consequences.

**Comment by ReddicusDragon** [comment]
> > As of Feb 3rd, 2019, Romerol was restricted to Glorious Death & Hijack only. Hijack & Sole Survivor are not the same thing. Romerol should not be available to sole survivor solely because the zombies may kill their creator. Do you have any other example of restricted items?
> 
> 
> 
> Looking at the code, there aren't ANY items that are allowed with datum/objective/sole_survivor. Seems like the uplink didn't get updated when sole survivor was added. Also, I don't see the point in restricting Romerol specifically. You could end up getting killed by your own singularity beacon, for example, but that's available to both martyr AND hijack. Romerol can be used to ensure you revive after death, or to try and cut down the station's population, or make sure everyone you're killing is slow and can't hold anything. I'm sure most people buying Romerol would be prepared for the consequences.

I have a PR ready to give more access to hijack items, but Romerol nor the singulo beacon are on the list of items I'm including. If you really want romerol available to sole survivor, please file a feature request instead. This is not a bug nor an issue.

**Comment by jachlompsky** [comment]
Okay. Well, I have no way of knowing that you "have a PR ready" when I report an issue. I was told to report this after sending an ahelp, and romerol aside, not being able to buy any hijack items with sole survivor is indeed an issue.

**Comment by ReddicusDragon** [comment]
> Okay. Well, I have no way of knowing that you "have a PR ready" when I report an issue. I was told to report this after sending an ahelp, and romerol aside, not being able to buy any hijack items with sole survivor is indeed an issue.

Hijack and sole survivor are not the same thing, but I see your point
