### ISSUE TITLE
 Security record console bluespace radio factory

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17452]
## Test Merges: 
Not Supplied / None
## Reproduction:
Screwdriver a security record console to disconnect the monitor, it generate a station bounced radio, reconnect it then disconnect it again, another radio.

 Submitted by: JellyRain (846634033622417470)

**Comment by ThatLing** [comment]
Fixed by https://github.com/yogstation13/Yogstation/pull/17453
