### ISSUE TITLE
drones can not use E to put stuff away

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#17450]
### Severity

Inconvenience

### Short Description

title

### Reproduction

1.) be drone
2.) have backpack
3.) have item in hand
4.) use E
5.) watch as item stays in hand
6.) curse TGUI because now you have to manually put everything back

### Round ID

any

**Comment by ReddicusDragon** [comment]
check your keybinds and get back to me, yeah? The keybind system now lets you pick which keys do what.

**Comment by ThatLing** [comment]
FYI, this wasn't a thing before either

**Comment by ReddicusDragon** [comment]
> FYI, this wasn't a thing before either

That's what I thought. I'm closing this as invalid.
