### ISSUE TITLE
Plasmaman helmet bug

### ISSUE THREAD

**Issue by YashinHak** [yogstation13/Yogstation#17462]
### Severity

Inconvenience

### Short Description

Customization on the Plasmaman helmet disappears after turning the light on.

### Reproduction

1. Join the round as a plasmaman with a set helmet customization option
2. Turn on your light
3. See your helmet is back to blank

### Round ID

44872

### Test Merges

17271

### BYOND Username

YashinHak

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by ThatLing** [comment]
Fucking plasmemes

**Comment by ThatLing** [comment]
Caused by #17271, fixed
