### ISSUE TITLE
Transcendent Olfaction Does Not Work when you're a skeleton

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#17468]
### Severity

Inconvenience

### Short Description

Transcendent Olfaction refuses to work when you're undead/skeleton (possibly noninfectious zombie) and gives a refusal saying that you're in some bloodsucker phase (torpor?)

### Reproduction

1.) get transcendent olfaction
2.) become undead/skeleton/maybe zombie
3.) attempt to use olfaction
4.) be given prompt saying you are in a bloodsucker phase or whatever (torpor? I forget)
5.) be sad

### Round ID

any

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

this is likely because olfaction is some bloodsucker ability and code does not account for nonbloodsucker undead

**Comment by ynot01** [comment]
skeletons dont have noses

**Comment by MajManatee** [comment]
intended feature, but the wording is a bit weird.
