### ISSUE TITLE
 Turning on the Plasmaman light of the helmet changes it's style

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17467]
## Test Merges: 
Not Supplied / None
## Reproduction:
Sometimes it does, sometimes it doesn't, what happens is, i turn on the light and the helmet style (wizard) changes to the "none" style.

 Submitted by: PibeCantina (341102461504716800)

**Comment by ThatLing** [comment]
Duplicate of https://github.com/yogstation13/Yogstation/issues/17462
