### ISSUE TITLE
Geladikinesis STILL doesn't work

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#17473]
### Severity

Inconvenience

### Short Description

title

### Reproduction

geladikinesis button is still a thing
press the button
button doesn't give you snow
cry??
how am I supposed to celebrate christmas now

### Round ID

#44884 (but any should do)

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by ThatLing** [comment]
Duplicate of https://github.com/yogstation13/Yogstation/issues/16210
