### ISSUE TITLE
Seclite isn't shown on pKA after being affixed to pKA

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#17474]
### Severity

Low

### Short Description

a pKA with a seclite attached will not show the seclite, but will still give option to turn seclite on/off

### Reproduction

1.) attach seclite to pka
2.) wow
3.) seclite png not on pKA anymore

### Round ID

any

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

probably because of the recent seclite new sec gun fix

**Comment by ThatLing** [comment]
Was this a thing before?

**Comment by TheBombMakerJL** [comment]
Yes, you should see the seclite before, that was how you’d know if it was actually there, outside of the button to turn it on/off while in hand

**Comment by 00aquir** [comment]
same for USP pistol
edit: hm, seems like this is a thing https://github.com/yogstation13/Yogstation/pull/17412

**Comment by 00aquir** [comment]
okay, light not showing up for disabler, either

**Comment by 00aquir** [comment]
okay, attached light not showing up for disabler, either

**Comment by MajManatee** [comment]
@ynot01 broke it with that update

**Comment by ynot01** [comment]
no i didnt

**Comment by ynot01** [comment]
https://github.com/yogstation13/Yogstation/pull/17271
