### ISSUE TITLE
Can't watch Armory camera

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#17489]
### SeVeRiTy

Inconvenience

### ShORt DeScripTiOn

Armory main camera not showing up on sec camera console - YogStation

### RePrOdUcTiOn

- Armory main camera active
- not showing up on camera console

### RoUnD ID

44909

### BYOND USeRNaMe

Aquir

**Comment by 00aquir** [comment]
Yes actually the 2 inside armory cameras have 0 camera views!

![Armorycameras](https://user-images.githubusercontent.com/16806055/221218118-a52a9a53-0706-4b36-88bc-d58fa73de3fc.png)

**Comment by MajManatee** [comment]
Jamie moment
