### ISSUE TITLE
357 alternate speedloaders (heartpiercer, ironfeather, etc) cant load normal rounds

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#17481]
### Severity

Inconvenience

### Short Description

357 alternate speedloaders (heartpiercer, ironfeather, etc) cant load normal rounds

### Reproduction

1. buy alt speedloader and empty it
2. try to insert normal 357 round via box or bullet
3. fail

### Round ID

44895

### BYOND Username

Ynot01

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

stechkin alt ammo can hold 10mm ammo which is why its good to buy them, the 357 alt rounds are not that bad but the fact that i cant reload them turns me off and forces me to spend a telecrystal for regular speedloaders so i can have reloads

**Comment by MajManatee** [comment]
intended feature, and changed with an upcoming PR to be this way.
