### ISSUE TITLE
Books don't work.

### ISSUE THREAD

**Issue by Yarinoi** [yogstation13/Yogstation#17482]
### Severity

Inconvenience

### Short Description

Books go blank when I try to read them after I open them up.

### Reproduction

1. Take book
2. Read book
3. Book flashes it's information for a second
4. Book goes blank

### Round ID

44897

### BYOND Username

Yarinoi

### Was this done on a locally hosted or non-Yogstation hosted server?

Yes

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/issues/19051 closing in favor of newer one
