### ISSUE TITLE
Robotics console does not get upgraded efficiency from tech levels/components

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation#175]
When tech levels are synched,and components upgraded, the robotics fabricator does not use less material.

This is different from how it has been on yog for some time, and makes robotics that much more challenging.

**Comment by Super3222** [comment]
Compared to the numbers of our old repo, it appears that nerfing robotics was apart of the downfall of science.

Basically everything was nerfed so science is a little more dependent on other departments (via mining and botany) for advancement.

For instance:
Old -

**Comment by Super3222** [comment]
Compared to the numbers of our old repo, it appears that nerfing robotics was apart of the downfall of science.

Basically everything was nerfed so science is a little more dependent on other departments (via mining and botany) for advancement. T4 makes EVERTHING much easier, but is still hard to get.

**Comment by EMT321** [comment]
Considering the differences in servers, where there is far more material sharing being done on TG than Yog (in my experience), it seems premature to apply all their nerfs. If it becomes even the slightest issue, sure. But the fact that even with T3 parts and R&D maxed as high as it can go without resources, robotics gets no practicable benefits other then new expensive tech. 

This doesn't encourage people to do R&D in the first place, and will likely confuse people who are not aware of the code change with regards to science levels.

**Comment by AdamElTablawy** [comment]
@Super3222

Remove all the R&D nerfs and the changes to the level system please
