### ISSUE TITLE
Bring mining asteroid back as an option for miners

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#1750]
For those who want to learn the ropes/more casual mining/working alone/nothing to do with lavalands drama. Just add it to the mining (and labor) shuttle availability and bring the z-level back (though don't make it one of the 9 typically available via space travel. Space exploration is now more exciting. No need to clog it up with the asteroid). I've heard mostly positive feedback and heard it wouldn't be much a lag problem.

**Comment by 00aquir** [comment]
Make Asteroid great again!

**Comment by Super3222** [comment]
It's very possible. The only problem is that it's sort of a waste of space to have because there's a big possibility that no one's going to go there. On top of that the mining hardsuit would have to lose its ash resistance (which isn't that big of a problem), and be taken off the mining vendor because the asteroid requires such.

**Comment by Jc1469** [comment]
sure. as long as I get to add an asteroid-specific megafauna.

**Comment by 00aquir** [comment]
I always wondered why the goldgrub never contained any ore inside of it..

**Comment by drderp3635** [comment]
you could make an unarmored and non-ashproof hardsuit for on the astroid that looks the same to solve the hardsuit problem

**Comment by Drakkon** [comment]
Would like to see more player opinions, at least.

@Super3222 It would be just as visited as the other z-levels (corpses don't count), and would be just as useful/fun to explore if all the ruins are still there.

@Jc1469 On the left side only then, the OG mining "hard mode". (I want to sprite asteroid megafauna >_>)

**Comment by Time-Green** [comment]
Good idea, and then have the asteroid megafauna fuck off into space and bump into the station.

**Comment by Jc1469** [comment]
I think _The Darkness_ would be a good addition to both space and the asteroid, and the station when it inevitably drifts there.

**Comment by nichlas0010** [comment]
Asv is doing this, so no point in keeping this open
