### ISSUE TITLE
Incorrect lumen calculation in some cases

### ISSUE THREAD

**Issue by ThatLing** [yogstation13/Yogstation#17519]
### Severity

Inconvenience

### Short Description

Incorrect lumen calculation in some cases

### Reproduction

Supposedly podpeople struggle on lavaland because they do not get enough light, even though they should have enough

### Round ID

Any

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by GraveHat** [comment]
Note that moving to pre-existing light sources stops them from dying, but turning your light off and on again after getting the message does not. In-game this feels more like the system is lagging behind the player constantly moving but standing still after getting the notification does not seem to stop the suffocation as it still counts as dark.

The forewarning notification Pod people get that warns them that there's not much light in the area will be seen frequently while simply walking around before getting immersed in total "Darkness."

**Comment by ThatLing** [comment]
After some investigating, it seems like some turfs don't have their lighting corners set (e.g. ``lighting_corner_NE``). This happens in ``/datum/light_source/proc/update_corners`` which is called from SSlighting fire.

**Comment by ThatLing** [comment]
> After some investigating, it seems like some turfs don't have their lighting corners set (e.g. `lighting_corner_NE`). This happens in `/datum/light_source/proc/update_corners` which is called from SSlighting fire.

Disregard this, the corners are for static lighting. ``turf.dynamic_lumcount`` is used for dynamic lighting, maybe it's just not high enough?

**Comment by Oblisk234** [comment]
Was fixed by #21221.
