### ISSUE TITLE
Orbital BOMBARDMENT!

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1752]
The asteroid is a mother fucker, sometimes the best solution is the ultimate solution! BOMBARDMENT!

 With a console on the bridge that takes in grid coordinates but can also have targets painted by miners and then it fires a BIG FUCKING GUN at the asteroid.

 What about the T O X I N S  L A B?!! 
SHUT THE FUCK UP I AM GETTING TO IT!!
 There can be improved warheads that do MORE DAMAGE! for ULTIMATE DAMAGE! With special valves that are meant for the warheads but won't mix unless they are in a warhead to prevent ACCIDENTS!

 Safety systems will prevent an area from being targeted if miners are in it unless the console is emagged FOR EXTRA FUN.

UPGRADES! It will have them!! FASTER! STRONGER! BETTER!

 With continuous bombardment the asteroid will yield to our MIGHT!

**Comment by Jc1469** [comment]
let me just close this PR with my non-existant contributor powers. because it's not happening.

**Comment by Super3222** [comment]
what is this

**Comment by ShadowDeath6** [comment]
github doesn't have an emoji for the emotion I'm feeling right now

**Comment by drderp3635** [comment]
sounds like a really good time, sadly it would be broken as hell.

**Comment by aphielanis** [comment]
BOMBARDMENT!!

**Comment by Rocks4Free** [comment]
Is this my replacement? 0/10

**Comment by nichlas0010** [comment]
BSA basically does this
