### ISSUE TITLE
"Adrift station" visually dizzying

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#17549]
### Severity

Inconvenience

### Short Description

"Adrift station" shift divergency 

### Reproduction

1. "Adrift station" is randomly chosen as a shift divergency

### Round ID

Round #44961

### BYOND Username

crazy_drakkon

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

"Adrift station" has been commented on as making multiple people sick/nauseous. Even if that's the point, making people feel unwell for a whole round is probably a lil much. Not only does the background rotate, but when traveling moving, the background moves unnaturally (especially apparent when space walking).
i.e. when the background is rotated to 180 degrees (upside down), the background moves in the direction you move instead of the opposite as you would expect. (In my opinion it would be better completely removed) An alternative could be the background ever slowly drifting in one direction.

**Comment by ThatLing** [comment]
Turn off space parallax in your game settings

**Comment by MajManatee** [comment]
Not a bug
