### ISSUE TITLE
Podpeople/nyctophobes (quirk) more vulnerable to darkness and space

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#17550]
### Severity

Inconvenience

### Short Description

Darkness now triggers always on space/astral carpet tiles, regardless of present light

### Reproduction

1. Be podperson race and/or have nyctophobia quirk
2. Be on space tiles or even astral carpets
3. Negative darkness effects are triggered even if several lights are present and on your person

### Round ID

Round #44961

### BYOND Username

crazy_drakkon

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

I'd guess the most recent lighting update (#17271) caused this. It might be my imagination, but I believe darkness is also triggered much more often in general (than before) even with multiple flashlights (due to light updating slower), which is extremely annoying with the nyctophobia quirk.

**Comment by ThatLing** [comment]
Related to #17519

**Comment by MajManatee** [comment]
@ThatLing still an issue?

**Comment by Oblisk234** [comment]
Was fixed by #21441 it seems.
