### ISSUE TITLE
 Engi sec office doesn't have all the cameras for the engi areas

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17564]
## Test Merges: 
Not Supplied / None
## Reproduction:
Atmos, lobby, aux tool storage, secure storage, and a lot of the cameras for dedicated engi areas are not available.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1065460410255421580/image.png)
 Submitted by: Weeb Gamer (305818411462557696)

**Comment by patpol4** [comment]
Probably intentional, it is called "Engine Monitor" after all
