### ISSUE TITLE
 Clicking the X on tgui results in a "yes" being sent.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17573]
## Test Merges: 
Not Supplied / None
## Reproduction:
For example, this can make you confirm to being posibrain when you dont want to be.

 Submitted by: M4 Sherman (409605569968603136)

**Comment by ThatLing** [comment]
@JamieD1

**Comment by ThatLing** [comment]
https://github.com/tgstation/tgstation/pull/61413

**Comment by MajManatee** [comment]
Resolved
