### ISSUE TITLE
Taking anything off someone with memento mori triggers memento mori 

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#17596]
### Severity

Inconvenience

### Short Description

title

### Reproduction

1.) get memento mori
2.) have someone take off a piece of clothing that isn't memento mori
3.) get dusted

### Round ID

45015

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by Moltijoe** [comment]
get dusted 
"ah just a minor inconvenience"

**Comment by Moltijoe** [comment]
yeah, you don't actually get dusted, it just plays the warning at the wrong time
