### ISSUE TITLE
 Mood Healing is Crazy busted strong and needs fixing.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17608]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Mood Healing is insanity right now and can literally heal like 50 or more damage at a time when it does tick, its literally stronger than some chems and stacks with other healing instead of being a VERY slow passive heal.

 Submitted by: Tawaporah Koko (241348083907166219)

**Comment by ThatLing** [comment]
Related to #17319 

@JamieD1 :)
