### ISSUE TITLE
 Everyone (or at least me) has access to every cape

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17615]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: I, and I assume other people, have access to every skillcape

 Submitted by: Sol_ (465645769328951316)

**Comment by ThatLing** [comment]
Related to #17381

Known issue, it checks if you have access upon spawning.

**Comment by ThatLing** [comment]
Fixed
