### ISSUE TITLE
Supply Console (express console as well) show blue screen error.

### ISSUE THREAD

**Issue by pizzacrisp** [yogstation13/Yogstation#17620]
### Severity

Round Breaking

### Short Description

Console fucked yo. But yeah we can't order anything so Cargo is useless.

### Reproduction

Once unlocked. It shows up as a blue screen with the following

**A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation.** 

 Script error.
   at https://cdn.yogstation.net/assetcache/asset.7cd36c0b496409feaf360d6540ff67a6.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"antoxamtl","interface":"Cargo","window":{"key":"[0x2005dcb]-main","size":null,"fancy":1,"locked":1}}

### Round ID

45044

### BYOND Username

Antoxamtl 

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by pizzacrisp** [comment]
Turns out SMES units also produce the same issue.

**Comment by ThatLing** [comment]
Fixed
