### ISSUE TITLE
New hotkeys mode interferes with old keybind and edit box function

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#17646]
### Severity

Round Breaking

### Short Description

The ability to use Ctrl+key and have a "classic hotkeys" edit box is broken

### Reproduction

1. With or without Classic Hotkeys mode enabled
2. enabled: No "Ctrl+(keypress)" is passed to to the hotkeys
2b. Disabled: The edit box is not interactable with a single (non-combination) keypress that would put focus on the edit box

### Round ID

XXXX

### Test Merges

https://github.com/yogstation13/Yogstation/pull/17216

### BYOND Username

Aphielanisn

### Was this done on a locally hosted or non-Yogstation hosted server?

Yes

### Additional information

"Was this done on a locally hosted or non-Yogstation hosted server?" (that's not a yes or no question). Locally(As in, on Yogstation.).

**Comment by burn1cycle** [comment]
Elaboration:  
1.) In classic hotkeys mode you could press most buttons on the keyboard including shift+combos (for capital letters) and it would go to the bottom edit box. BUT if you hit Ctrl+combo or Alt+combo it became hotkeys
2.) "Edit Box" is a term I used to define the region of the BYOND client screen at the bottom where you can enter text alternatively to using the pop-up edit boxes

**Comment by Bibby0110** [comment]
Deprecated as of new keybinding system
