### ISSUE TITLE
Decal Painter directional decals not working

### ISSUE THREAD

**Issue by GraveHat** [yogstation13/Yogstation#17643]
### Severity

Inconvenience

### Short Description

Choosing a direction does not change the decals direction

### Reproduction

1. Get a decal painter
2. Set the decal painter to any direction and use warning lines or other decals that use directions
3. Paint on the ground then switch direction
4. Repeat and you will see the problem if you didn't catch it by step 3

### Round ID

0

### BYOND Username

TotallyGrey

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

Need to check why this happens, gonna put this here in case someone else wants to do it before then. I forgot the round this happened on

**Comment by ShoziOffical** [comment]
ah funny

**Comment by ShoziOffical** [comment]
this is due to mis args ill get on it
