### ISSUE TITLE
Late Join Menu Locks Up

### ISSUE THREAD

**Issue by ZangoDango** [yogstation13/Yogstation#17647]
### Severity

Inconvenience

### Short Description

Late Join Menu does not load my role and just hangs there.

### Reproduction

1. I late join.
2. I get the late join menu
3. the darn thing locks up, chat and Dreamseeker still is running but latejoin menu just remains there and i have to close Dreamseeker with Task manager.

### Round ID

Round #45089

### BYOND Username

Vinzo

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

I have no idea if its me or just something I am doing wrong.

When joining via Observe, Being Readied up, or ghostrole none of this happens and there is no issue.

**Comment by ThatLing** [comment]
@ZangoDango Is this still an issue?
