### ISSUE TITLE
 THE TALKING STARGAZER

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17654]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: if an item used on a stargazer rolls possession the ghost gets put in the stargazer itself and not the item

 Submitted by: zealot (343805692710486017)

**Comment by MajManatee** [comment]
No idea whats being said here.

**Comment by namjay1170** [comment]
> No idea whats being said here.

Stargazer is a clockcult structure that when something is used on it will roll a d10 and give a random buff one of which is supposed to make the item you're buffing sentient but reportedly makes the stargazer itself sentient.

**Comment by Oblisk234** [comment]
Sentient enchanted stargazer weapons were removed in #19878

**Comment by Oblisk234** [comment]
Marked this wrong apparently.
