### ISSUE TITLE
 IPC'S brains cant fit in a spiderbot

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17661]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: I tried to fir a mmi with the brain of an ipc into a spiderbot, but it wouldnt let me because "the brain was dead", when it clearly wasnt.

 Submitted by: PibeCantina (341102461504716800)

**Comment by MajManatee** [comment]
IPC brains are normal human brains reskinned to look like robot brains. They wouldnt fit.
