### ISSUE TITLE
Preferences don't contain sentience spawn option

### ISSUE THREAD

**Issue by Majkl-J** [yogstation13/Yogstation#17671]
### Severity

Inconvenience

### Short Description

Preferences don't contain sentience spawn option

### Reproduction

1. Join as ghost
2. See xenobio spamming sentience potion
3. No notif ????
4. Check prefs menu
5. No option for sentience potion ???
6. Cry

### Round ID

#45116

### Test Merges

#17381

### BYOND Username

Waterpig

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by ThatLing** [comment]
@JamieD1

**Comment by ThatLing** [comment]
Added
