### ISSUE TITLE
Mercury bugs camera

### ISSUE THREAD

**Issue by ThatLing** [yogstation13/Yogstation#17683]
### Severity

Round Breaking

### Short Description

Eating mercury makes your character move on its own, however the camera doesn't follow you

### Reproduction

1. Eat mercury
2. Don't move
3. Watch character move off screen

### Round ID

45138

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by MajManatee** [comment]
Dont eat fucking mercury????

**Comment by Maia-J** [comment]
After some testing, I was unable to reproduce this on both mercury and lithium, both of which use the same code for moving your char.

**Comment by ReddicusDragon** [comment]
Can't reproduce
