### ISSUE TITLE
"Thrown Lightning" spell does not work.

### ISSUE THREAD

**Issue by Kirbykraze** [yogstation13/Yogstation#17710]
### Severity

Low

### Short Description

"Thrown Lightning" spell does not work.

### Reproduction

1. Sign magic contract from devil.
2. Click "Thrown Lightning" button.
3. Throw mode is enabled, but nothing is placed into your hands..

### Round ID

Round #45175

### Test Merges

#17681

### BYOND Username

Kirbykraze2

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

None relevant.

**Comment by Kirbykraze** [comment]
Update: The spell works as intended if you are currently holding an item in the hand you cast the spell with, dropping the item on the floor.

**Comment by MajManatee** [comment]
Devil is an unsuported gamemode.

**Comment by tattax** [comment]
fixed in antag pr
