### ISSUE TITLE
Sounds tab is gone from the top Bar

### ISSUE THREAD

**Issue by JamieD1** [yogstation13/Yogstation#17736]
### Severity

Inconvenience

### Short Description

Unable to control sound prefs easily and not Stop all sounds button

### Reproduction

n/a

### Round ID

0

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by ThatLing** [comment]
``Stop all sounds`` button was moved to OOC tab. Individual sound dropdown buttons is bloat I will not add back
