### ISSUE TITLE
 Engi borg tools so fucked not even a module reset fixes it

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17789]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: As title states, but nothing really seemed to have caused it, I died, got brought back, but my tools were fucked and a module rese didnt fix them, had to be deconstructed and built back.

 Submitted by: Nickie (842223373789691913)

**Comment by MajManatee** [comment]
what the fuck does this mean "tools were fucked". Cant replicate with no info.
