### ISSUE TITLE
Clerk's office still named Gateway

### ISSUE THREAD

**Issue by Groudonmaster** [yogstation13/yogstation#1778]
In the admin verb jump-to-area and, I'm assuming the mapping, the clerk's office hasn't been renamed and is still defaulting to gateway.

**Comment by Dagdammit** [comment]
Yeah, this should be fixed. Can someone remove the Clerk and replace their office with a gateway? Or a second vacant office, that works too.

**Comment by Rocks4Free** [comment]
>Yeah, this should be fixed. Can someone remove the Clerk and replace their office with a gateway? Or a second vacant office, that works too.

Even if this is a joke suggestion I'd honestly prefer this.

**Comment by Time-Green** [comment]
Not merged yet, but the PR is up and else I'll forget about it

**Comment by Cruix** [comment]
Put closes #1778 in the first post of that PR

**Comment by Time-Green** [comment]
Does it auto close it then? I always wondered...
