### ISSUE TITLE
 Synthetic showing up in AI/Borg area in job slots

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17780]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: As title says, a Synthetic job option is showing up in the non-organic area of job selection. If you click on it, the window bluescreens. I also had, on my crew monitor, a bunch of people up top showing up as the Synthetic job, which doesn't seem to exist.

 Submitted by: Aquizit (168642050915434496)

**Comment by Bibby0110** [comment]
Fixed
