### ISSUE TITLE
 The freeminer ORM cannot hold dilithium

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17798]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: dilithium is gone :crabrave:

 Submitted by: Master Drake (598557108551811073)

**Comment by Aquizit** [comment]
I'll leave what I found here just in case but I unfortunately dunno how to fix this on my own:

When the station ORM is linked to the silo, Dilithium appears correctly on the list of materials you can take out of the ORM directly. However if you unlink the silo the option to withdraw dilithium disappears, even though the machine still appears to be processing it correctly, as it still assigns the depositor the correct amount of points.

So it's a UI issue when an ORM is not linked to a silo, but I could not for the life of me figure out how to correct it while I was looking through the code. But that's the issue.

**Comment by MajManatee** [comment]
Twasnt a UI issue
