### ISSUE TITLE
Preternis no longer gets a skin-tone option in character creation

### ISSUE THREAD

**Issue by killerx09** [yogstation13/yogstation#178]
The title explains it all, really. My character looks like a vampire now.

**Comment by timkoster1** [comment]
I did this on purpose actually. If ya guys want I can turn it back with the hit of a button.

**Comment by killerx09** [comment]
Yes please, I would like to go back to looking like a latino.

**Comment by timkoster1** [comment]
I made a vote about it
https://forums.yogstation.net/index.php?threads/preternis-colors-vote.10855/#post-105974
