### ISSUE TITLE
Atmos fire fighting backpack doesnt launch muh resin globs of easy fix >:(

### ISSUE THREAD

**Issue by Ethan4303** [yogstation13/Yogstation#17902]
### Severity

Round Breaking

### Short Description

atmos firefighter back pack tank set on resin launcher does not spread resin to contain fire, reset atmos, or contain gas

### Reproduction

1 put firefighting tank on back
2 take out the resin gun
3 set to resin launcher
4 fire resin glob
5 cry as the plasma fire from a griefer kills you and your friends because the resin launcher did not infact launch resin

### Round ID

45374

### Test Merges

N/A

### BYOND Username

Ethan4303

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by ThatLing** [comment]
Probably related to #17742
