### ISSUE TITLE
 Lavaland gas station isnt air tight

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17907]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Lavaland gas station has no air and low pressure

 Submitted by: EnglishScotsman (740223180806946946)

**Comment by ThatLing** [comment]
This is NOT related to auxmos btw

**Comment by MajManatee** [comment]
is this not intended?

**Comment by neeshacark** [comment]
seems to be fine as of now
