### ISSUE TITLE
Food placed in vendors disappear

### ISSUE THREAD

**Issue by ktlwjec0** [yogstation13/Yogstation#17912]
### Severity

Inconvenience

### Short Description

Food placed in vendors by the cook just vanish. You cannot vend the food.

### Reproduction

1. Be cook. Make mouse kebabs.
2. Place in getmore food vendor.
3. Vanished food. No trace of it. It is like it never existed.

### Round ID

all

### BYOND Username

ktlwjec

### Was this done on a locally hosted or non-Yogstation hosted server?

Yes

**Comment by MajManatee** [comment]
Sorry i was really hungry

**Comment by ktlwjec0** [comment]
[#18626]

**Comment by hedgehog1029** [comment]
this was fixed by #18626 and can be closed
