### ISSUE TITLE
 QUIRKS DON'T FUCKING SAVE

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17931]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Quirks that are changed are not saved. I don't know if it's an issue with quirks that were restricted to certain races, but apparently Phytosians can't have hemophilia anymore. I had it on my Phytosian character before it was changed, and my guess is that fucked my entire quirks menu. Other than that, I have no idea.

 Submitted by: Archangel (355800566737141761)

**Comment by ThatLing** [comment]
Duplicate of #17925
