### ISSUE TITLE
NVS Gax map has objects-missing in Brig!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#17950]
### Severity

inconvenience-type

### Short Description

The station-mentioned missing sec-related objects.

### Reproduction

- prisoner-IDs are missing from perma hallway + labor.
- warden has no-recharger in their room.
- HoS has no shutter-button!
- there is no-screwdriver in security office!
- there are no firing-pin boxes.
- there are no bomb-suit and sec-biosuit lockers.

### Round ID

Round-45453

### BYOND Username

username-Aquir

**Comment by patpol4** [comment]
@ToasterBiome
