### ISSUE TITLE
 Free Miner combat mech access

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17972]
## Test Merges: 
Not Supplied / None
## Reproduction:
BUG: Free miners can access their exofab to print combat mechs.
That's the bug. It's against the rules for FMs to print combat mechs, yet they can do so anyway from their exofab. The admin's reasoning is that "combat mechs suck at fauna fights", apparently some staff members don't actually understand the balance.. lol. Anyway, it's bizarre & doesn't make any sense from an IC perspective that FMs would be forbidden to make combat mechs, so that function should be removed?

 Submitted by: WastelandMain (556966533478219816)

**Comment by MajManatee** [comment]
Not a bug.
