### ISSUE TITLE
Can't toggle LOOC

### ISSUE THREAD

**Issue by Aquizit** [yogstation13/Yogstation#17981]
### Severity

Inconvenience

### Short Description

There's no way in prefs to turn LOOC on or off.

### Reproduction

1. Open prefs
2. notice LOOC isn't there

### Round ID

All

### BYOND Username

Aquizit

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by MajManatee** [comment]
PR to fix open, if not merged already

**Comment by Aquizit** [comment]
so uh -- this is awkward but...
