### ISSUE TITLE
 Magboot implants don't work

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17983]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Whether magboot implants are inserted via surgery, autosurgeon, or multisurgeon, the action button never is made available to anyone that receives the implants. The implants read as within the individual on a health scan.

 Submitted by: Skrem_7 (118161168731734019)

**Comment by MajManatee** [comment]
lizards rejoice
