### ISSUE TITLE
Transformation bugs

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#18048]
### Severity

Round Breaking

### Short Description

Animal and human transformations appear to have broken in many ways

### Reproduction

Many things to unpack

- [x] 1. Vampires using bat form instantly kill the bat, changing back with nothing appearing to happen
- [x] 2. Bloodsucker vassals using the bat form don't have the luxury of changing back and just die
- [x] 3. Changelings entering monkey form cannot use the human form button, it reportedly does nothing
- [ ] 4. Changelings using panacea to cleanse mutations will be given those mutations back when using transform
- [ ] 5. Potentially directly related to 4, but a changeling (Jed Mull) late this round used Transform and turned into a monkey, despite not having Lesser Form

### Round ID

45568

### BYOND Username

Ynot01

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by MajManatee** [comment]
Ive been able to transform to and from bat form no problem lately, unsure of the source of this issue.
