### ISSUE TITLE
Plated helmet: cannot attach flashlight?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#18046]
### Severity?

Inconvenience

### Short Description?

Cannot attach flashlight for plated helmets, like for other helmets of similar type.

### Reproduction?

- use plated helmet
- cannot attach flashlight

### Round ID?

45567

### BYOND Username?

Aquir

**Comment by MajManatee** [comment]
Show me the mounting point for a flashlight on a plate helmet
