### ISSUE TITLE
First Annual Spring Bug cleaning and merge hold?

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1807]
Well the first issue is that I'm NEVER right so lets just get that out of the way, disagreements welcomed and posted below. 
 The main issue I want to bring up is we are accumulating bugs at an alarming rate like crew monitoring has been broken for months but we're still merging new stuff because new stuff is admittedly very fun and fixing bugs isn't as much.

 So maybe we should do a merge hold like TG has done in the past to clean out some bugs from the issues list? And I mean real bugs not my stupid suggestions  or anything like that.

**Comment by AdamElTablawy** [comment]
That's not a bad idea.

**Comment by ShadowDeath6** [comment]
Feature freezes generally don't work as well since like 2 or 3 people will actually try to fix bugs.
We don't have the same amount of coders that tg does.

**Comment by Super3222** [comment]
We had one in the past already.
If we're doing this maybe 1-2 bug fixes for 1 feature? I say 2 so nobody gets off easy.
