### ISSUE TITLE
Borg and delaming SM

### ISSUE THREAD

**Issue by alexkar598** [yogstation13/Yogstation#1807]
Issue reported from  Round ID: 17430 (Yogstation 13 [99% LAGFREE!])

Reporting client version: 512

Was a borged person via decapitation thenputted in a body and i had to go in a delaming sm

Sm delamed and i have gone boom!
and received this message:

```
You feel reality distort for a moment...

WALLY has died at Supermatter Engine.

Oops! Something went very wrong, your MMI was unable to receive your mind. You have been ghosted. Please make a bug report so we can fix this bug.
```

**Comment by ghost** [comment]
That's because the MMI was fucking gonzoed by the SM.  Not a bug just stupid bugtext.
