### ISSUE TITLE
 ipc ling

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18090]
## Test Merges: 
Not Supplied / None
## Reproduction:
as an ipc character when you're roundstart ling you spawn as a dead human with your original name.

 Submitted by: ♡Parky♡ (682139201084456990)

**Comment by MajManatee** [comment]
skill issue? Seems weird.

**Comment by wonderinghost** [comment]
no this indeed happens

**Comment by wonderinghost** [comment]
they also get zombies but cant convert
