### ISSUE TITLE
Suggestion: Lavaland player spawns cooldown

### ISSUE THREAD

**Issue by AlpacaGoesCrazy** [yogstation13/yogstation#181]
To prevent players from using all spawning sleepers/ashwalkers eggs/etc and rushing into danger of lavaland while not afraid of dying we should add a cooldown between same type of spawns (or between all type of spawns). Without said cooldown a single player can use up all the sleepers effectively preventing everyone else from playing lavaland factions.

Also we could use a rule to remind players that they actually dont have any memories from their past lives (i am constantly seeing newly spawned prisoners from lavaland rushing for their last spawn belongins)

**Comment by Super3222** [comment]
Players should always remember entering a new body/new life they retain no memories of their past life. Common sense covers that if it's not already written in the rules.

I'm thinking of making a check to see if you observed, suicided, or ghosted to get a lavaland role. But all of those ways can easily be loop holed.

**Comment by Super3222** [comment]
Players should always remember entering a new body/new life they retain no memories of their past life. Common sense covers that if it's not already written in the rules.

I'm thinking of making a check to see if you observed, killed yourself (suicide), or ghosted to get a lavaland role. But all of those ways can easily be loop holed.

**Comment by AlpacaGoesCrazy** [comment]
I think it is totally okay to observe/ghost(as non-head/nonantag) and go get a lavaland role. But to use knowledge of you previous role in a new one is a bad thing

**Comment by ParagonPrime** [comment]
ehh, i say it's too hard to enforce- and perhaps not even worth it

lavaland is fucking horrifying as it is unless you're ashwalkers/have survival capsules

metagaming locations is often the only way to have even a tiny chance to survive

**Comment by Stealthkibbler** [comment]
TG had a pull request where it makes all of lavaland except the station and the spawns invisible to ghosts, essentially a fog of war. I think they amended it so ghosts could see what players see so they could orbit active players, although The community shat on the idea pretty hard since metagaming locations is pretty commonplace on TG.
