### ISSUE TITLE
 Genetics glitches

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18116]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: When I had geladikinesis this round, I couldn't get the snow button to make snow, but it did go on cooldown each time I clicked it.  Also, not sure if it's related, but I have noticed that telekinesis does not allow me to interact with consoles at a distance.

 Submitted by: EnkiduAwakened (272858455113596940)

**Comment by MajManatee** [comment]
Ive noticed both these issues lately as well.

**Comment by TheBombMakerJL** [comment]
#16210 
Geladikinesis has not worked in ages, haven't experienced the telekinesis issue

**Comment by Maia-J** [comment]
The telekinesis console thing might be there to prevent trolls like me from making announcements from the cap console
As for geladikinesis, might try to fix
