### ISSUE TITLE
Split gender reassignment between groin and chest.

### ISSUE THREAD

**Issue by The-clown-known-as-Pepe** [yogstation13/yogstation#1812]
We'll never be medium-rp if we can't get dickgirls and cuntbois

**Comment by ShadowDeath6** [comment]
uhhhhhhhhhhhhhh

**Comment by RoboticVodka** [comment]
This is needed.

**Comment by oisin100** [comment]
Well then..

**Comment by Drakkon** [comment]
*slow clap*

**Comment by doerakpoes** [comment]
Why

**Comment by drderp3635** [comment]
Y tho

**Comment by The-clown-known-as-Pepe** [comment]
So we can have diccgrillz and cuntboiz, why else?

**Comment by ShadowDeath6** [comment]
Alright I made a promise to myself to close this if I saw the word "cuntboys" in this issue again. 

Afaik we're not planning to add any weird sex change surgeries anytime soon considering we're not citadel or vorestation or whatever you want to call it. If anybody else has a reason for reopening it go ahead.

**Comment by ShadowDeath6** [comment]
Also this issue has given me omega aids and cancer in like 2 different areas

**Comment by drderp3635** [comment]
Would those two areas happen to be groin and chest?

**Comment by The-clown-known-as-Pepe** [comment]
Yes

**Comment by ShadowDeath6** [comment]
Yes :^)
