### ISSUE TITLE
Stunned with wings sends you flying

### ISSUE THREAD

**Issue by namjay1170** [yogstation13/Yogstation#18135]
### Severity

Inconvenience

### Short Description

With potion of flight wings activated if you're stunned it slips you aswell as launching you in what appears to be a random direction.

### Reproduction

1. Have wings enabled
2. Get hard stunned (Golaith, bananium esword, fulton. (Maybe more those are just what I've tested)
3. Fly into a random direction and if you're me on 2 separate occasions directly into a lava lake

### Round ID

45636

### BYOND Username

Namjay1170

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Has a tiny chance to end your round for no reason

https://gyazo.com/784fde4e2b94d8ac1afed8b869e35c18

Feel free to point and laugh at this death which shows it

**Comment by MajManatee** [comment]
Intended feature. You are flying, then get stunned and come crashing down like a plane.
just dont get stunned 😎

**Comment by namjay1170** [comment]
doesn't sound like a feature when a flying miner fulton's themself it sends them flying into lava
