### ISSUE TITLE
Drones can state laws (and nothing else)

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#1813]
Similar to other silicons. So people can shutup, always asking drones to open doors n shit. May not shut em all up, but it'll help.

**Comment by ShadowDeath6** [comment]
drones cannot see or interact with humans, it's like they don't exist

**Comment by Dagdammit** [comment]
/me cannot involve itself in the affairs of other beings. (idk if this actually works)

Or just tell them OOC after round.

Like if you gave them this button you'd have to change that law to end "...except to inform them of this law."

**Comment by Drakkon** [comment]
@Dagdammit Is that a bad thing?

**Comment by Dagdammit** [comment]
Eh, not especially? In hindsight that last bit was  mostly just me trying to think things through.

I'd still lean towards leaving things as-is, but both options seem fine.

**Comment by doerakpoes** [comment]
Well I mean drones are hugly for some reason allowed to fix a breach which is a HUGE interaction with the crew so thier laws are kinda broken literly the only way for them to not interact with the. crew is to just walk around with their lights off.

**Comment by Dagdammit** [comment]
Their actions can affect crew, they just can't involve themselves in the
affairs of crew. They can fix breaches because that's repairing and
improving the station, they just can't do it, say, in order to help someone
who happens to be in the room.

**Comment by doerakpoes** [comment]
So the moment some one else is fixing it you have to go?

**Comment by Dagdammit** [comment]
You just don't acknowledge them, is how I see it.

Like, you know in abstract that okay, this part of station is now being
repaired by other processes than just my own, maybe I'll focus on other
repairs that aren't currently being worked on AFAIK. Or maybe I'll keep
working on repairing this section until it's ready to go. Botg would be
valid.

If I stay, work on the breach, and as I'm finishing someone runs up and
stabs the repairing person with a spear multiple times before dragging them
off? Maybe consider grabbing some space cleaner and tidying up that blood.
Or find more stuff to improve and repair!

**Comment by doerakpoes** [comment]
So I can do anything regarding improving and building as long as none asked me for it?

**Comment by Dagdammit** [comment]
You can build/fix/improve the station *regardless* of whether anyone asks
you for it. If someone asks me to fix X, I just treat it the same way as if
I'd overheard someone mention that X was broken. It's just me receiving
information about the state of the station.

**Comment by doerakpoes** [comment]
Drones rules are confusing but i get it now

**Comment by doerakpoes** [comment]
1. Don't interact with the crew
2. Repair and improve the station
3. Protect yourself (don't actully remember)

They could use some clarification...

**Comment by Dagdammit** [comment]
Your version of number 1 is too narrow, because it means I could still do things to try and save someone who is bleeding out. Drag them to medbay in a locker, or spraypaint arrows pointing to them. 

That's not what a drone should do. To a drone, someone bleeding out is "not my business". The point is to have them never go beyond a background role in the game (at least, not if they can help it).

**Comment by ShadowDeath6** [comment]
for all intents and purposes the crew does not exist to a drone
