### ISSUE TITLE
 Space Pods Impossibly slow

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18155]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: Space pods are extremely slow and laggy, and also still explode like they're going super fast when they touch something, turning and going different directions are also super duper slow :C it was fine before, i believe it started doing this around when we got the time dilation update

 Submitted by: purr purr (843557080320442398)

**Comment by MajManatee** [comment]
probably delta time related

**Comment by patpol4** [comment]
didnt we disable this on purpose

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/18490
