### ISSUE TITLE
Gasses not flowing

### ISSUE THREAD

**Issue by TheTrueTay** [yogstation13/Yogstation#18158]
### Severity

Inconvenience

### Short Description

About 1 hour in gasses stopped overall flowing be it through pipes or free space

### Reproduction

1. Join the round as Amos engie
2. Set up turbine
3. Start setting up solid hydrogen factory
4. Notice gasses ceased to flow thus breaking the function of the turbine

### Round ID

45673

### Test Merges

Auxmos

### BYOND Username

TheTrueTay

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

None

**Comment by ThatLing** [comment]
Known auxmos issue
