### ISSUE TITLE
Ashe storm bug

### ISSUE THREAD

**Issue by Gintoki1** [yogstation13/yogstation#1815]
Ive recently gotten back into mining, and I've been noticing a small bug with ashe storms.
A few ashe storms I've experienced don't do any damage for some reason.
I'm unsure what is happening, but if I'm out in an ashe storm I wanna die!
![ashe proof](https://cloud.githubusercontent.com/assets/23708263/22872154/8a1dabf6-f17c-11e6-9759-d6c7080d126e.PNG)
![asheproof 2](https://cloud.githubusercontent.com/assets/23708263/22872155/8be3fb7a-f17c-11e6-9f67-942b025c496a.PNG)
(I've haven't drank a dragon potion or anything like that)

**Comment by Gintoki1** [comment]
Also the gibonite dealt damage to me right there that is why I'm hurt.

**Comment by YogsMcree** [comment]
Do you have any form of resistance at all. Are you nonhuman, are you regenerating from a virus, are you in stanard armor? You havent really given any useful information

**Comment by Gintoki1** [comment]
Nope no form of resistance or healing. Just a normal human miner with bunny ears

**Comment by Gintoki1** [comment]
I'm wearing chithen armor that's it

**Comment by Gintoki1** [comment]
I feel like deleteding this issue and reposting it a lot better now

**Comment by Time-Green** [comment]
Did you have an ash of storm with you?

**Comment by Gintoki1** [comment]
what do you mean? The ash storm staff?

**Comment by Time-Green** [comment]
Yeh

**Comment by Gintoki1** [comment]
No I did not.

**Comment by Gintoki1** [comment]
All I had was chitin armor, gauntlets, boots. I've had no legion soul or any form of healing. I didn't kill an Ashe drake(Didn't spawn) or killed the legion for Ashe staff.

**Comment by Gintoki1** [comment]
I took no damage from the full length of the storm .

**Comment by YogsMcree** [comment]
I think chitin gives ash resistance

**Comment by Time-Green** [comment]
I checked, and it doesnt appear to.
