### ISSUE TITLE
Atmosphere Broken

### ISSUE THREAD

**Issue by Osteoglass** [yogstation13/Yogstation#18165]
### Severity

Round Breaking

### Short Description

gas over turf and in pipenets not working correctly

### Reproduction

1. Electrolyzer chamber not producing H2, water vapor stopped moving in and out of electrolyzer tile.
2. SM coolant getting deleted somewhere between gas input and SM chamber (gas never registered on SM monitor).
![Turfs](https://user-images.githubusercontent.com/13265480/222627836-51861823-8eda-4be7-b985-40ee65a3463f.png)

3. Scrubbing air from a tile appeared to lower pressure, but adjacent low and high pressure turfs not exchanging gas and equalizing pressure.
4. SM suffered slow and inevitable delamination .

### Round ID

Round #45679

### Test Merges

#13479: 'Auxmos' 

### BYOND Username

Osteomancer

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by ThatLing** [comment]
Known auxmos issue
