### ISSUE TITLE
Chaplain bible/religion preferences are gone 

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#18185]
### Severity

Inconvenience

### Short Description

You can't name your religion or deity since the preference is gone as of tgui character menu.

### Reproduction

1. look for the prefs
2. gone

### Round ID

N/A

### BYOND Username

Cark

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by MajManatee** [comment]
@ThatLing

**Comment by Maia-J** [comment]
These do appear in the Alternate Names section

**Comment by ReddicusDragon** [comment]
Closed. See above reply. If problem persists, feel free to reopen this and yell at me on discord.

**Comment by Maia-J** [comment]
Additionally yell at me and call me rude words if the problem persists
