### ISSUE TITLE
 Minigun mag unbuyable, has no sprite when taken off

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18186]
## Test Merges: 
Not Supplied / None
## Reproduction:
details: Mags for The M-546 Osprey minigun arent buyable in nukie uplink, if you buy 2 of them and take out the mag on one, the mag has no sprite.

 Submitted by: Karl (191166034168774656)

**Comment by ReddicusDragon** [comment]
This is a bug. You should not be able to unload the Osprey. @Majkl-J is fixing this bug.

**Comment by Maia-J** [comment]
> This is a bug. You should not be able to unload the Osprey. @Majkl-J is fixing this bug.

Right back atcha
👈👈 😎
