### ISSUE TITLE
 Slings still can't veil flashlights

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18203]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: slings can't veil flashlights, dunno if there was a pr that tried to fix it or not, but it's still very broken and killing slings all over, i feel bad when they try to convert me or others and die trying

 Submitted by: purr purr (843557080320442398)

**Comment by MajManatee** [comment]
good

**Comment by Oblisk234** [comment]
Shadowlings no longer exist, see #20581
