### ISSUE TITLE
ynot01 updated: Handheld flashes now knockdown instead of paralyze. NO NO NO

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#18223]
### Severity

Round Breaking

### Short Description

We need this stun equipment that actually stuns so we don't have to hurt people to arrest them

### Reproduction

1. Have Ynot01 code something for no reason

### Round ID

XXXX

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

1. Never underwent discussion phase.
2. Was never voted on.
3. Ynot01's familiarity with security department is questionable
4. Seems unfamiliar with equipment and it's drawbacks already inherent.
5. Has literally functioned the way it has for 10 years and in all that time nobody's had an issue with how the flash functioned.
6. I don't understand Ynot01's motive for changing the flash. Is he a shitter who griefs and gets mad at security for using their gentle stun equipment on him? I don't know.
7. Flash is/was gentle stun equipment for trying to subdue people in the least harmful way possible
8. Stun batons don't work anymore, they're damn useless. (I remember that change too, terrible change. This is like the same change.)
9. Essentially see above, this is the same bad change we got to stun batons and then never had fixed. Every antag in the game gets good stun equipment but the people who are supposed to capture alive get bad stun equipment? What the shit?
10. At no point has anyone mentioned they appreciate the change and more than a few of us are very resentful.
11. As far as I can tell it was never part of a "test merge" to even give us a option it was just shoved down our throats
12. I hate the arrogance of the coding staff that thinks they alone know the best mechanics for the game and don't need to talk to anybody.

**Comment by MajManatee** [comment]
Stop trolling in bug reports
