### ISSUE TITLE
IPC drop equipment when taking off clothing

### ISSUE THREAD

**Issue by yacabo** [yogstation13/Yogstation#18261]
### Severity

Quality of Life

### Short Description

IPCs when removing clothing will drop their ID, belt, and what's in their pockets despite not needing a suit to keep these thingsheir pockets despite 

### Reproduction

1. Be an IPC
2. Put stuff in your ID slot/belt/pockets while also wearing a suit
3. Take off suit
4. Your items will be on the floor and you now have to put them back on

### Round ID

45864

### Test Merges

#17583 #17560 #17815

### BYOND Username

yacabo111

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by ReddicusDragon** [comment]
Please confirm this is still an issue, yaca! If it is I'll look into it but can't promise anything

**Comment by yacabo** [comment]
> Please confirm this is still an issue, yaca! If it is I'll look into it but can't promise anything

Just tested it on the main and yeah it still happens, thanks for looking into it

**Comment by yacabo** [comment]
fuck wrong button

**Comment by Maia-J** [comment]
> Please confirm this is still an issue, yaca! If it is I'll look into it but can't promise anything

I am pretty sure preternis suffer the same

**Comment by MajManatee** [comment]
put items in pocket
take off clothing that has pockets
I wonder why it does that.
