### ISSUE TITLE
 Keybinds menu throws a bluescreen window (https://i.imgur.com/BR7IK2d.png)

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18272]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: Clicking on the View Keybinds tab of Game Preferences throws up an NTOS bluescreen error window.  The rest of the Character Preferences and Game Preferences windows all work fine.

 Submitted by: Snipehamster (228852927010177025)

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/18473
