### ISSUE TITLE
missing random maintenance room

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18307]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: random maint room filled with nothing but empty space (round crashed midway through)

 Submitted by: Master Drake (598557108551811073)

**Comment by Maia-J** [comment]
Which one

**Comment by 00aquir** [comment]
[that one](https://replays.yogstation.net/?roundid=45922#0;166.63;160.03;2;null;0.0)

**Comment by Aquizit** [comment]
Fixed by #19263

**Comment by Aquizit** [comment]
Er, maybe it wasn't fixed by that one specifically but it looks like there's a room there properly now
