### ISSUE TITLE
 Keybinds

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18312]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: Messed with a few keybinds and now just getting nanotrasen bsod everytime i try to change them

User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"conjunctivitiscarl","interface":"PreferencesMenu","window":{"key":"[0x21004348]-main","size":null,"fancy":1,"locked":0}}

 Submitted by: fanta (703340164478533794)

**Comment by tattax** [comment]
needs confirmation as in probably fixed by now but i don't remember which PR

**Comment by tattax** [comment]
nvm found it https://github.com/yogstation13/Yogstation/pull/18473
