### ISSUE TITLE
 Gumball... Bullets...?

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18320]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: mediborg's treat fabricator, while blasting gumballs, if a gumball hits the wall, its sprite turns into a bullet casing which is unable to be eaten... huh..? what the fuck?

 Submitted by: Karl (191166034168774656)

**Comment by ChuChu42** [comment]
update: this also seems to be happening upon blasting lolipops.

round id 45959

unable to replicate on private server

**Comment by Skrem7** [comment]
has to do with #17982

i'll take a look later

**Comment by ChuChu42** [comment]
https://user-images.githubusercontent.com/118483925/226187860-f4d834a1-22d7-4543-b6c0-d38c1d1ba0a6.mp4

**Comment by Skrem7** [comment]
foam darts are bugged too, I'm looking into it

**Comment by Skrem7** [comment]
fixed in latest commit

to clarify foam dart situation: foam dart shotguns (including the crossbow) are not dropping foam darts. Every other foam force weapon is. Currently being investigated
