### ISSUE TITLE
 Bloodsucker clan selection doesn't work.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18344]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: got to level 6 or 7 and never got the prompt to chose a clan other than the information tab about the clans themselves

 Submitted by: stworldcitizen (957714824568143953)

**Comment by Marmio64** [comment]
A way to avoid this may be making sure you only advance to rank 3 if you're not in torpor, as being unconscious when clan selection is given may stop it
