### ISSUE TITLE
Drones(mechanical not alium) can get nanites

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#18351]
### Severity

Low

### Short Description

Public nanite tubes lost their check(or something) for drones recently

### Reproduction

Drones can enter public nanite tubes and use them to get nanites like any person

### Round ID

xx

### Test Merges

xx

### BYOND Username

Aphielanisn

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by MajManatee** [comment]
uhhh so can IPCs, i dont see the issue.
