### ISSUE TITLE
ipc are stuck in cluwn suit on the account of brain in chest

### ISSUE THREAD

**Issue by wonderinghost** [yogstation13/Yogstation#18355]
### Severity

Inconvenience

### Short Description

when cluwned it makes it nearly impossible to "cure" ipc of cluwnification 

### Reproduction

get cluwned. watch as robotics and medical professionals be annoyed.

### Round ID

46016

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

its a massive inconvenience to ipc players and techs everywhere. if there is a way to make it easier like ripping apart other people's jumpsuit or downgrade the cluwn suit to being immune to everything

**Comment by Oblisk234** [comment]
Cluwne spell no longer exists, see #21345
