### ISSUE TITLE
PDA painter doesnt work on the new PDAs

### ISSUE THREAD

**Issue by Reed0506** [yogstation13/Yogstation#18364]
### Severity

Inconvenience

### Short Description

The HOP's PDA painter cant repaint the new PDAs.

### Reproduction

N/A

### Round ID

N/A

### Was this done on a locally hosted or non-Yogstation hosted server?

Yes

**Comment by ktlwjec0** [comment]
this can be closed

**Comment by Oblisk234** [comment]
Was fixed by #22671
