### ISSUE TITLE
Antagonist and Friendly Holoparas aren't visually distinct

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#18361]
### Severity

Quality of Life

### Short Description

There's no easy refferrence to explain the difference between these two, one is kill on sight the other is non-antagonist and results in Ahelps

### Reproduction

 Holparasites can do a lot of damage quickly so reacting to them is often a snap decision or one that gets you killed. It's difficult on everyone including admins when there's what I consider to be a "bait item" that baits players into breaking the rules out of confusion because we don't understand the difference.

Ideas,
*A special color
*A highly visible arrangement of pixels over the para
*A sprite that doesn't look like antagonist holoparas at all(Maybe it can be a geometric shape like a sphere or a cube.).
*Hats!

### Round ID

xx

### Test Merges

xx

### BYOND Username

Aphielanisn

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

xx

**Comment by MajManatee** [comment]
this is not a bug
