### ISSUE TITLE
Can't access keybind menu

### ISSUE THREAD

**Issue by MildlyConcussed** [yogstation13/Yogstation#18367]
### Severity

Quality of Life

### Short Description

When I try to open the keybind menu it immediately blue screens and does not do anything

### Reproduction

Open keybind menu.
Crash.

### Round ID

N/A

### Test Merges

N/A (?)

### BYOND Username

MildlyConcussed

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Only thing I might think that could be helping this error to occur is that I bound z and x to 'use in hand item' and 'swap hands' respectively, as well as biding ability 1 and 2 to those same keys. Beyond that I'm not sure what is going on...

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/18473
