### ISSUE TITLE
Warden Beret is invisible.

### ISSUE THREAD

**Issue by Yarinoi** [yogstation13/Yogstation#18362]
### Severity

Quality of Life

### Short Description

Warden beret is invisible on your sprite, when you wear it.

### Reproduction

1. Take Warden's Beret from the warden's clothing duffel bag.
2. Put it on.
3. Your character sprite doesn't change.

### Round ID

46030

### Test Merges

17815 - Hypertorus Fusion Reactor

17982 - Modern Medievalism

### BYOND Username

Yarinoi

### Was this done on a locally hosted or non-Yogstation hosted server?

Locally Hosted

**Comment by 00aquir** [comment]
same for the HoS beret when starting

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/18417
