### ISSUE TITLE
Stationside radiation storm hits miners on lavaland

### ISSUE THREAD

**Issue by namjay1170** [yogstation13/Yogstation#18370]
### Severity

Round Breaking

### Short Description

Stationside radiation storm hits miners on lavaland for some reason

### Reproduction

I saw a gps not moving so I come to help and find my fellow miner in a glowing green capsule during an ash storm

https://gyazo.com/9cb5ea3915ad7f1e18d928fd98ed0af5

admeme said this not supposed to happen and to make report

### Round ID

46042

### BYOND Username

Namjay1170

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by MajManatee** [comment]
yeah it happens, but this aint game breaking
