### ISSUE TITLE
Preternis-wiki dissonance

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1837]
https://wiki.yogstation.net/index.php?title=Preternis

"While they still take toxin damage from radiation, they will never faint or mutate from it"

Preternis mutated after rad storm, got twitchy and started swearing.

**Comment by Cruix** [comment]
Oh yeah

Radstorms are special snowflakes that manually mutate you instead of just calling rad_act()

You will never mutate from radiation from the sing ot nuke core or PA, but radstorms still will.

**Comment by 00aquir** [comment]
A weird method, but then it's ok I guess.

**Comment by Cruix** [comment]
The wiki is still wrong

**Comment by 00aquir** [comment]
Ah yes I just meant that the game is alright then. I guess there will be a specific sentence about rad storm being somehow different?

**Comment by Super3222** [comment]
I fixed it for you @00aquir

**Comment by 00aquir** [comment]
Thanks

**Comment by 00aquir** [comment]
Although there is a small duplication, mentioning the same thing twice.

**Comment by Cruix** [comment]
>allowing them to survive radiation storms unscathed with only a small amount of antitoxin. Radiation storms however are too powerful to ignore, and must be avoided during time of emergency.

**Comment by 00aquir** [comment]
Thanks again
