### ISSUE TITLE
 Cursed Balloon Box

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18374]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: Box of assorted balloons, can not be examined neither shift click or right click, can be used in hand to infinitely spam balloons-sometimes bugs and gets to -1 balloons left letting you make infinite balloon animals

 Submitted by: Karl (191166034168774656)

**Comment by ChuChu42** [comment]
https://user-images.githubusercontent.com/118483925/227709596-0c71e149-6418-4e55-bb05-8826f5c3f72c.mp4

**Comment by ChuChu42** [comment]
https://user-images.githubusercontent.com/118483925/227709610-865d428d-a790-4391-8d34-3af7fe85f6da.mp4

**Comment by Maia-J** [comment]
I am speed
