### ISSUE TITLE
 Hippie's Delight killing podpeople

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18376]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: Hippie's Delight is a drink intended to be beneficial to podpeople but kills them in 5u. Fanciulli has a similar issue.

 Submitted by: Bucket (188151461241159680)

**Comment by Maia-J** [comment]
I have brought this to Hobo's attention (I have a gun to his head and will force him to fix this)
