### ISSUE TITLE
 invisible foam force pistol magazines

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18387]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: as long as the magazine has a foam dart in it, riot or not, it will appear invisible

 Submitted by: EnglishScotsman (740223180806946946)

**Comment by ToasterBiome** [comment]
![image](https://github.com/yogstation13/Yogstation/assets/5091394/3e08db56-6ef0-4fc2-a33e-14c8917ad3df)
cannot reproduce
