### ISSUE TITLE
Cherry bombs detonate as soon as they are activated

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/Yogstation#18388]
### Severity

Low

### Short Description

Cherry bombs detonate as soon as they are activated, making them only effective as suicide bombs since you immediately blow up

### Reproduction

1 join the round as a podman on lavaland
2 be lucky enough to roll cherry bombs in one of your two crates, then plant and harvest them
3 pluck the stem and get ready to throw
4 blow up as soon as you pull the stem, knocking a few limbs off and critting yourself

### Round ID

46087

### BYOND Username

dr.derp3635

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

I have been told this is due to the black powder change which removes its activation time

**Comment by Maia-J** [comment]
I know exactly what causes this so I will try to fix this
