### ISSUE TITLE
Allow library computer to print books much more efficiently

### ISSUE THREAD

**Issue by ArgyleSweatshop** [yogstation13/yogstation#1838]
The most tedious part of playing librarian is stocking the shelves. It'd be nice to not have to spam click the computer. The librarian menu needs to have specific add to queue buttons that don't cause its menu to reset- it is currently extremely tiring simply to print out 30-40 good books.

**Comment by Dagdammit** [comment]
Oh, you want a queue function like the exosuit fabricator. That would make a ton of sense.
