### ISSUE TITLE
Regal Rat "Rat King's Domain" has no cooldown

### ISSUE THREAD

**Issue by namjay1170** [yogstation13/Yogstation#18415]
### Severity

Round Breaking

### Short Description

Spam that button

### Reproduction

Be regal rat
Spam Rat King's Domain button
Fill entire station with miasma 

### Round ID

46134

### BYOND Username

Namjay1170

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

https://gyazo.com/3e2378fe91f5d0d9bbb610be59818057

gif of it in action, might even work on the other abilities?

**Comment by tattax** [comment]
fixed in THE antag pr
