### ISSUE TITLE
Changeling lesserform permanent

### ISSUE THREAD

**Issue by Magentaformula0** [yogstation13/Yogstation#18428]
### Severity

Inconvenience

### Short Description

The button to turn back into human doesnt seem to work. 

### Reproduction

1. Be changeling
2. Take lesser form
3. return to monke
4. Attempt to return to normal form
5. weep for it doesnt function

### Round ID

46156

### Test Merges

17982

### BYOND Username

magentaformula0

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Sad ling had to go to genetics to get them to turn me human

**Comment by MajManatee** [comment]
lol

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/18651
