### ISSUE TITLE
Comms agent bomberman/frame not working

### ISSUE THREAD

**Issue by AJHcHenry** [yogstation13/Yogstation#18433]
### Severity

Round Breaking

### Short Description

The frame and bomberman programs don't give you a code and don't come with them as comms agent, so you really can't do much

### Reproduction

Join round as comms agent on asteroid post

Install programs

Try to use programs

### Round ID

Round# 46162

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by MajManatee** [comment]
Intended feature. You are a stealth agent, not a free PDA bomber
