### ISSUE TITLE
 Character reset bug.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18436]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: For some time now everytime a round starts my character gets randomized for some reason. As adminhelp suggested I'm submitting a bug report here. Player name (used to be at least hahah): Joseph Stallion.
Occupation preferences are the only thing that stay the same every round (I don't use antag prefs). I would like to be myself again and await eagerly for a response from this marvellous team!
With respect, Joseph Stallion.

 Submitted by: Bepo (728188084029489163)

**Comment by MajManatee** [comment]
Sounds to me like you got appearance banned.
