### ISSUE TITLE
 Screen goes black ramdomly

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18443]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: For some reason, sometimes when im playing my game suddenly goes to 2 fps for around 5 seconds then the screen goes to black, i can still see floating text from people talking and i can interact with things if i know where they are but thats about it, and to solve it i need to reconnect, this has been quite annoying since in some rounds i had to reconnect 7-12 times, not to mention that if this happens in a bad time (nukies, revs, traitor conveniently deciding to strike on me), im fucked, i was told that clearing cache would solve the problem but it did nothing, i also restarted my computer but it still happens.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1091965560830562304/Yogstation_13__Try_not_to_call_the_shuttle_30_mins_in_challenge_Impossible_2023-03-21_22-29-59_Trim.mp4)
 Submitted by: Lolyea (424349874532777984)

**Comment by MajManatee** [comment]
To my knowledge this is client side.

**Comment by Bibby0110** [comment]
BYOND issue
