### ISSUE TITLE
 I think the game wants me to pick jolly as a trait

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18447]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: I've had this happen sometimes, but not this many. I'm unsure if its a client issue or actually yogstation being weird, but the trait "Jolly" normally appears several different times (for me atleast). Doesn't affect other traits it seems.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1092191891182862457/image.png)
 Submitted by: Ham (375839334701727745)

**Comment by MajManatee** [comment]
Duplicate
