### ISSUE TITLE
Normal foam darts act as riot darts too

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#18440]
### Severity

Round Breaking

### Short Description

Riot darts and normal foam darts both cause stun

### Reproduction

shoot person with normal foam darts

### Round ID

46178

### Test Merges

xx

### BYOND Username

Aphielanisn

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by Maia-J** [comment]
They were probably also holding a nerf gun

**Comment by MajManatee** [comment]
once again, not round breaking. Likely intended feature with lack of information.
