### ISSUE TITLE
200u of morphine dose from foam is excessive

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#18441]
### Severity

Round Breaking

### Short Description

Your round is basically over if you get caught in the foam and no medical help is available therefore round breaking

### Reproduction

Get caught in morphine foam during vent ejection event

### Round ID

XXXX

### Test Merges

XXXXX

### BYOND Username

Aphielanisn

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by MajManatee** [comment]
Not really a bug, but it is an issue
