### ISSUE TITLE
 Strange objects are not spawning

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18454]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: i have noticed that strange objects, the things that you discover with the E.X.P.E.R.I.MENTOR were lacking in science and nonexistant at all for some time now, my guess is that a pr that changed maintenance loot messed up with  the strange object spawn rates or removed them accidentally, i tried to search for a recent pr that changes maint loot but didnt find one.

 Submitted by: Lolyea (424349874532777984)

**Comment by MajManatee** [comment]
oh fug yeah that happened
