### ISSUE TITLE
 Couldn't transform back from changeling monkey to human

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18456]
## Test Merges: 
Not Supplied / None
## Reproduction:
Details: As a changeling i couldn't transform back to human, maybe because vents was filled with something, the most weirdest rhings i had waa "You cant think straight". And some instant knockdowns from cargo tech.

 Submitted by: Mosquito (722433162851909684)

**Comment by MajManatee** [comment]
Repeat issue, also made by a schitzophrenic or somthin
