### ISSUE TITLE
Shouldn't Arrivals shuttle be protected from Rad storms?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1846]
Somebody joins, only to find out they are getting retarded, blind / deaf. This kind of a thing happened to  many people... this area should be an exception.

**Comment by Dagdammit** [comment]
It should yeah.

**Comment by doerakpoes** [comment]
Probably

**Comment by Gintoki1** [comment]
The escape shuttle isn't protected from radstorms. I've just witnessed it today, and there was a good amount of puke

**Comment by Dagdammit** [comment]
I'd vote protect escape shuttle too. There's no direct maint connection to it, so radstorms still inhibit crew reaching shuttle in interesting ways.
