### ISSUE TITLE
 Clown Shoes Implant

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18474]
## Test Merges: 
Not Supplied / None
## Reproduction:

the clown shoes impant upon being implanted **IN BOTH LEGS** does not show a button to pop up the clown shoes, you also get a permenent slowdown and a squeaky noise every step you take despite not having the clown shoes on

they also do not protect you from glass shards.

 Submitted by: Karl (191166034168774656)

**Comment by Moltijoe** [comment]
not a bug
