### ISSUE TITLE
 Revival surgery final step doesn't have a cauterizarion step

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18505]
## Test Merges: 
Not Supplied / None
## Reproduction:
Revival surgery is the surgery that allows you to force revive someone, that is mostly used on decayed corpses that cant be defibrilated normally anymore. The surgery is supposed to end with cauterization as with the other 90% of surgeries, but it doesnt, using cauterizer only "cancels" the surgery as you were doing in midway. This is annoying because the "saw bones" step causes damage to the patient, the "clamp bleeders" step is supposed to heal some of it and the "cauterize" step (the missing one) is supposed to heal the rest of the damage, also cancelling a surgery instead of doing the actual step takes longer.

 Submitted by: Lolyea (424349874532777984)

**Comment by MajManatee** [comment]
pretty sure this is intended. When revival is completed, the person is forced to stand up. why would you strap them back down.
