### ISSUE TITLE
Losing all my roles

### ISSUE THREAD

**Issue by ErolThurn** [yogstation13/Yogstation#18529]
### Severity

Inconvenience

### Short Description

Lost all my unlocked roles for no reason

### Reproduction

1.Join the server
2.Play for 2 days unlock scientist (16h as crew)
3.Play alot as scientist
4.Scientist role gets locked for me and it says i need 19 more hours for it ? 
Please gib roles back

### Round ID

round 46358

### BYOND Username

ErolThurn

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Bibby0110** [comment]
Likely sporadic database failure
