### ISSUE TITLE
Miner bug

### ISSUE THREAD

**Issue by Ryublood666** [yogstation13/Yogstation#18558]
### Severity

Game Breaking

### Short Description

Plant people can't mine well in lava lands

### Reproduction

1. be a pod person
2. mine any rock
3. go to where it was and you start dying from lack of light even if you have max brightness.

### Round ID

46397

### BYOND Username

RyuBlood666

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by tattax** [comment]
opting for https://github.com/yogstation13/Yogstation/issues/18610 since it has more info
