### ISSUE TITLE
Mp3's

### ISSUE THREAD

**Issue by EthanMalakay** [yogstation13/yogstation#1856]
What if there is added mp3's that with the ip of youtube, start a music and others hear it, it only is for RP. It would enchance my rp :v why not

**Comment by Jc1469** [comment]
did you know if you have a phone and stand on a stool and suicide, you kill yourself

**Comment by AdamElTablawy** [comment]
no

**Comment by EthanMalakay** [comment]
whyyyy

**Comment by drderp3635** [comment]
Opens up mp3 player.

Spams ear rape versions of people screaming bigotry

**Comment by EthanMalakay** [comment]
:v its not mp3's fault that you got bad music
