### ISSUE TITLE
 Cant see which hand is active

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18571]
## Test Merges: 
Not Supplied / None
## Reproduction:
I had the dono role, then it got removed, but the ratvar hud stayed, but I couldnt see which hand was the active hand in the hud.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1096933551431233690/image.png)
 Submitted by: Nickie (842223373789691913)

**Comment by tattax** [comment]
it is fixed by https://github.com/yogstation13/Yogstation/pull/18514
