### ISSUE TITLE
Slaughter/Laughter Demons not getting speed boost when emerging from blood

### ISSUE THREAD

**Issue by Moja10** [yogstation13/Yogstation#18572]
### Severity

Inconvenience, but round ruining for slaughter/laughter demons!!! Poor demons 

### Short Description

Slaughter/Laughter demons are supposed to get a speedboost when emerging from blood. However, their speedvar is not actually updated when they emerge from blood like it used to. 

### Reproduction

1. Spawn slaughter demon and put yourself in it
2. spawn some blood, or make a mob bleed, or spawn gibs
3. go into the blood, and emerge out of it
4. You will be bloody red which indicates that you SHOULD be speedboosted, but you are not speedboosted
5. you can check cached_multiplicative_slowdown which by default is 4. When emerged from blood, it should be adjusted, however it is still 4. 

My theory is that something about these lines 155 - 159  not working, I am no expert on VARSET_CALLBACK(): https://github.com/yogstation13/Yogstation/blob/8601d98ae36e64f6194d077f9102d37af85faae2/yogstation/code/datums/components/crawl.dm#L155

### Round ID

46427

### Test Merges

18568 (AI 4.0 but that shouldn't matter)

### BYOND Username

yogurtshrimp69

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Did not see a runtime occur when emerging from blood but the speed boost is still not applied.

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/18514
