### ISSUE TITLE
 Synthetics are mislabeled in goals

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18573]
## Test Merges: 
Not Supplied / None
## Reproduction:
I got a synth as a target objective, and the objective lists them as a "synthetic Synthetic"
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1096965144539574412/image.png)
 Submitted by: Zer0 (412038981669355560)

**Comment by BurgerLUA** [comment]
Just want to comment on this. The lowercase s synthetic means the race, the uppercase s Synthetic means the job.

https://github.com/yogstation13/Yogstation/blob/92a14a07edfe6ca86497d3473758656943c7c2e5/code/game/gamemodes/objective.dm#L329

**Comment by Oblisk234** [comment]
While it may seem strange and atypical, not an issue.
