### ISSUE TITLE
Preternis "Finger Gun" Combo in Racial Martial Art Gives Undroppable Stetchkin

### ISSUE THREAD

**Issue by jacobsimmonsrosen** [yogstation13/Yogstation#18611]
### Severity

Inconvenience

### Short Description

Using the third combo, "Finger Gun," (Harm, Disarm, Disarm) from the Preternis traitor racial martial art, "Combat Modules Board," gives the current active hand a suppressed stetchkin with a single bullet that cannot be dropped or unequipped except from having the arm cut off.

### Reproduction

1. Become a Preternis traitor
2. Buy the Combat Modules Board for 11 TC and learn it
3. Attempt the third combo on a fellow crewmember (Ham, Disarm, Disarm)
4. Fire your single-shot suppressed stetchkin at a target
5. Be unable to drop/use the stetchkin in any way and have to switch hands
6. Live life with only one arm

### Round ID

46510

### BYOND Username

clockworkedd

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

The gun does not get dropped even when cuffed, and the suppressor can be taken off while cuffed and drops on the ground. Should the arm be cut off, the gun then appears to stick to whoever picks it up, then disappears, though this information is only second-hand.

**Comment by Oblisk234** [comment]
Was fixed by #19587
