### ISSUE TITLE
ipc revival is broken 

### ISSUE THREAD

**Issue by wonderinghost** [yogstation13/Yogstation#18620]
### Severity

Round Breaking

### Short Description

breaks the revival of ipc and by part synths

### Reproduction

be a ipc/synth
die
watch robotics fail as they try to revive 

### Round ID

46534

### Test Merges

18568

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/18953
