### ISSUE TITLE
Plant names needed

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation#1866]
Basicly, I need alot of names. Male, female and surnames for plants.
Please comment with names and their category

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Timato Vegetable

**Comment by ShadowDeath6** [comment]
I thought we weren't doing the name thing

**Comment by AdamElTablawy** [comment]
Here's your names.

The normal, plantpeople names. No last names.

Ambrosia. Bark. Oak. Quinine. 

Et cetera.

**Comment by drderp3635** [comment]
You just give them a single name of a plant and that's what it is

**Comment by Super3222** [comment]
Male:
Cactus
Prickly
Kel-Blox
Dermaja
Froot

Female:
Anjellyca
May-Twap

Other plant name spinoffs

**Comment by Dagdammit** [comment]
Acacia
Alder
Ash
Aspen
Birch
Cedar
Cypress
Dogwood
Elm
Eucalyptus
Ficus
Fir
Hemlock
Hickory
Juniper
Magnolia
Mangrove
Maple
Oak
Palm
Pine
Poplar
Redwood
Spruce
Sycamore
Willow
Yew

No last names seem fine, and I wouldn't bother distinguishing by gender.

**Comment by drderp3635** [comment]
Pear
Apple
Bush
Berry(Barry if you want people reciting the bee movie)
Cocoa
Groot
Dandylion
Lily
Sapling
(George) melons
Moss
Vine

**Comment by Frostben** [comment]
do some names in different languages like Dris which is the irish name for brambles

**Comment by Drakkon** [comment]
http://www.theplantlist.org/browse/-/-/

Not sorry.

**Comment by Smudged** [comment]
Male:
Borlotti Bean
Asclepias Milk ((Milk Weed pls))
Mick Peppermint

Female:
Linaria Dalmatica ((some sort of weed))
Cherry Blossom 
Willow Weep 
Elastica Ficus ((Rubber tree))

**Comment by Comxy** [comment]
Bando Banana
Corran Cher
Grave Elderberry
Leeks Kiwilemon
Peppe Pepper
Radsin Rhubarb
Satsuma Strawberry
Yam Zucchini
Victoria Plum
Cress Watermelon
