### ISSUE TITLE
another ashwalker buff

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#1869]
make mining fauna take damage from thrown items like spears

you're still doing shit damage and at best you can throw 4 spears at the thing before having to kite around or run back for more spears

**Comment by Super3222** [comment]
they do take damage from thrown things. last time i checked their throw_force had to be 21 or higher

**Comment by ShadowDeath6** [comment]
ah, I guess that's the appeal of bone spears, nevermind
