### ISSUE TITLE
Improvised "Suicide" Vest

### ISSUE THREAD

**Issue by Frostben** [yogstation13/yogstation#1871]
Basically a jacket with extra pockets or holsters on the inside of the jacket that can hold 4 different grenades that are activated simultaneously at the wearers discretion. The way you would make one of these is to take a labcoat or any exosuit clothing type except spacesuits and hardsuits and use a bunch of torn cloth and cable coil to construct the pockets/holsters inside of the jacket which would then hold the 4 grenades of your choice. Upon detonation the vest would be destroyed.

The idea behind this is to give something like the IED an extra "Umph" so instead of throwing one IED and hoping you wing someone with it you detonate 4 of them simultaneously at the cost of your own health and safety but also greatly injuring anyone right next to you.

As a traitor you could have more possibilities since you have access to more explosive ordnance, say you put 4 C4 on you instead of IEDs or even 4 syndicate minibombs! Now that would be some magic right there. Keep in mind it doesn't have to be 4 of the same explosive type. If you are a traitor chemist you could ideally have 4 different grenades in a suicide vest to create all sorts of chaos if one so wished.

There are two ways I believe the grenades could be implemented into the vest
1.) Craft the vest with the 4 grenade types part of the recipe ie. 1 exosuit clothing piece, 4 torn cloth, 8 cable coil, and 4 chemical grenades
or 
2.) Craft the vest without the 4 chem grenades as a part of the recipe ie. 1 exosuit clothing piece, 4 torn cloth, and 8 cable coil. Then make it so that you can click on the vest to open up an inventory in which you can place the 4 grenades in and have a prompt at the top left of the screen to activate all the explosives inside the vest's inventory.

I can already tell that Adam might shit on this and flush it down the sewer especially with the fact they explode instantaneously whenever the wearer decides so maybe instead of an instantaneous activation of the explosives it instead will activate the timers on all the grenades if applicable. For example say the vest is filled with 4 IEDs, well then upon activation all the IED's 3-8 second timers are activated with a text prompt and some beeping to give potential victims a chance to escape.

**Comment by Stealthkibbler** [comment]
Suicide bombing is generally look down upon anywho.

**Comment by Frostben** [comment]
But think about it, if a chemist uses one of these he can make 4 different smoke grenades to wreck total havoc in a single room! Also do we still have that die a glorious death objective for traitors? If so this could come quite in handy for that.

**Comment by drderp3635** [comment]
If a chemist can make four deadly smoke grenades, they can just as easily make the grenades trigger from the same signal/voice activation

**Comment by Frostben** [comment]
Eh good point, this idea was mostly meant to be for assistants or something like that but there seems to be little to no enthusiasm for it considering there are other probably more robust ways to go about something like this. Well thank you both for the feedback and with that I'll close this issue.
