### ISSUE TITLE
 Wormhole jaunters don't save you from chasms if you're stunned/immobilized

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#18814]
## Test Merges: 
Not Supplied / None
## Reproduction:
Was immobilized by a goliath tentacle right as I destroyed a tendril, my jaunter activated after falling into the chasm but I didn't get sent through and ended up dying anyway.

 Submitted by: SapphicOverload (497856657016094730)

**Comment by iamthesilly** [comment]
![image](https://user-images.githubusercontent.com/93578146/236666504-a4a087bf-c55e-41a7-8bb5-4adfa0ef0209.png)
