### ISSUE TITLE
Traitors can afford to buy adrenals and double esword

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation#1882]
its kind of disgusting tbh, after playing a round with it.

**Comment by Super3222** [comment]
Bump stimpacks back to 10 TC.

**Comment by ShadowDeath6** [comment]
how about increasing dual esword price since they're the most complained about cancer in the buy list

**Comment by Stealthkibbler** [comment]
@Super3222 Adrenaline Implant for 8 TC, this has nothing to do with the stimpack, traitors have access to the Nuke Op Adrenaline Implant again.

**Comment by ShadowDeath6** [comment]
lmao

**Comment by Stealthkibbler** [comment]
So basically to give you an idea of how fucked it is.

- It's an implant, so it sits inside you until activated

- It has 3 uses before it wears off

- Each use injects heavy healing omnizine and a pseudo hyper adrenaline chemical that also prevents you from being knocked unconscious EVEN when in critical condition or chloral hydrated; etc. 

- It lasts for more than 3-5 minutes PER USE.

- This only costs 8 TC.

I was a burning plant person in space with orange limbs and a FLASHING RED CHEST and I was still able to stand and run at adrenaline speed for a solid 3 minutes, I didnt even pass out or die, I healed all the way back to full health from the omnizine.

**Comment by ShadowDeath6** [comment]
oh fuck do adrenals give you stimulants

**Comment by ShadowDeath6** [comment]
stimulants got a massive buff recently to make a unique powerful traitor item and I neglected to notice that adrenals gave you stimulants
