### ISSUE TITLE
Tesla depletes nourishment.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1887]
Human and preternis, with engi hardsuit on, and maybe all species...  Tesla sucks you down to a minus level and even when you start go to the kitchen and then eat constantly (as human), it already slowed you down to 1 tile / 2 seconds(!) for approx. 10 minutes(!), and not much better after that for a while.

**Comment by 00aquir** [comment]
Basically, when you save someone from engine you cannot really move for that long, and you only get gradually faster after that.

**Comment by McDonald072** [comment]
Wait, how does tesla deplete nutrition? By shocking you? By you being near it?

**Comment by 00aquir** [comment]
The engineering hardsuit completely shields from tesla shocks, and EMP shouldn't do this basically.

**Comment by YogsMcree** [comment]
Can confirmed this happened to me. Adam saw it

**Comment by ShadowDeath6** [comment]
this is probably happening because of the species rework making preternis' nutrition change when they're shocked? @Cruix

**Comment by Zostroll** [comment]
I can confirm this does happen with humans.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Holy shit you weren't kidding. It took me a few minutes to leave engineering. Ate everything from the food vendor outside, still couldn't walk.
