### ISSUE TITLE
issue with some info carrying over midround

### ISSUE THREAD

**Issue by enkidienne** [yogstation13/Yogstation#18893]
### Severity

bug

### Short Description

Botxa was playing heretic, sec chase etc etc, dies. Lucky fucker then rolls Bad wizard. Thing is, he spawn with his old name instead of the normal randomized wizard names and his wanted status. This could potentially fuck some players. 

### Reproduction

1. be wanted
2. die
3. get midround

### Round ID

47173

### Test Merges

#18627

### BYOND Username

enkidienne

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by Oblisk234** [comment]
Admin issue. Wizards are given a text prompt to choose their names, if they put it in there after dying (and becoming a new person) then they are breaking the rules, not a dev issue.
