### ISSUE TITLE
Podpeople die if they have walls on either side of them

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#18894]
### Severity

Round Breaking

### Short Description

Podpeople die if they have walls on either side of them, as if in darkness.

### Reproduction

1. be pod
2. be between 2 walls
3. die

### Round ID

n/a

### BYOND Username

Cark

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/issues/18610
