### ISSUE TITLE
Labor shuttle is inacessable and broken

### ISSUE THREAD

**Issue by UltraBigRat** [yogstation13/Yogstation#18914]
### Severity

Inconvenience

### Short Description

Stacking machine inserted materials dont add points to the console, gax  labor shuttle upside down.

### Reproduction

got arrested and put in labor camp in gaxstation, labor shuttle upon being called is upside down making the acessable doors lead to the id locked security area, and the door to the prisoner area is locked. Then if you somehow do get in the stacking machine doesnt add points to the console, making leaving labor camp without outside help impossible

### Round ID

47211

### Test Merges

#18627

### BYOND Username

UltraNumeron

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Aquizit** [comment]
The shuttle is aligned correctly, just need to swap two tiles. After flipping the whole thing around thinking the upside down bit was correct.
