### ISSUE TITLE
Sonic jackhammers should be able to break runed metal

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#1893]
They can break rwalls runed shouldn't be nothing to them.

**Comment by ShadowDeath6** [comment]
Runed walls are magic though so they're stronger than rwalls

**Comment by AdamElTablawy** [comment]
they take the same to deconstruct with a welder so no

**Comment by ShadowDeath6** [comment]
Haaaaa technically this is a bug since I did something wrong when I added tomes being able to interact with cultwalls, I'll get on it sooner or later
