### ISSUE TITLE
Monthly Salt Issue : Remove/nerf slaughter demons

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation#1898]
I was going to write an essay, but I decided against it

Points being: 
1. They do stupid amounts of damage, three hits to crit an  unarmoured person, then they're only one grab away from instant ggnore death
2. You need a high DPS weapon to even stand a chance of killing it, they'll just retreat otherwise, or even worse just tank whatever you're hitting them with, crit you and gib you, then recover whatever health they lost 
3.There is no telegraphing when they come out of blood pools, and they come out with a speed boost meaning you require both full health/ stims to even stand a chance of escaping
4.Cleaning blood only delays them, all they need to do is wait around in medbay, or for someone to inevitably drag a corpse, which gives them all the opportunity they need to continue their rampage
5.They're just not fun to play against, there's no outwitting or ambushing a slaughter demon, it's either kill or be kille - sorry did you say you aren't at full health nor conveniently have a combat with buckshot loaded? Ah well y'know gitgud

And saying that they're wizard only is not an argument, it doesn't remove the fact they're a complete pain in the ass to play against, nor does it matter when bubblegum loot can release a slaughter demon too.

**Comment by ShadowDeath6** [comment]
I'll make dismembering legs not stun you once some of my other prs get merged

**Comment by drderp3635** [comment]
in all honesty nothing feels as great at doing something and people ask for it to be removed because people do it "too good"

**Comment by ShadowDeath6** [comment]
I've played with and against slaughter demons and while it's extremely satisfying to do well as one I think that there's a few problems with them, most of them fixed in my pr

**Comment by EthanMalakay** [comment]
why nerf it? its called demon for something. please stop breaking the roleplay and the terror it has to give to people to work.

**Comment by doerakpoes** [comment]
Just let them be

**Comment by The-clown-known-as-Pepe** [comment]
Make Slaughter Demons hug people instead of killing them, problem solved.

**Comment by doerakpoes** [comment]
Don't you mean laughter demons
