### ISSUE TITLE
Lizards can CONSUME power cells

### ISSUE THREAD

**Issue by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [yogstation13/yogstation#1899]
Step 0: Alt-click power cell
Step B: Be amazed as you place your hands on it and start absorbing the power?

Dunno if other races can do that too, or what else can be consumed.

**Comment by ShadowDeath6** [comment]
@Cruix

**Comment by ShadowDeath6** [comment]
![fam](https://cloud.githubusercontent.com/assets/17034893/23335591/c901ff7e-fb7d-11e6-97f9-a7d17edc3d17.PNG)
this is intended

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
kk lemme close this real quick
