### ISSUE TITLE
Port: Tool speed

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation#19]
This is gonna <I>suuuuuck</I>

**Comment by oisin100** [comment]
YEEEEEEEP! your gonna have to update the map with your tools ONCE im done with it.

**Comment by Super3222** [comment]
This is going to be hell.

**Comment by X-TheDark** [comment]
/tg/ seems to have toolspeed, unless you mean coefficient changes https://github.com/yogstation13/-tg-station-yog-rebase/search?utf8=%E2%9C%93&q=toolspeed

**Comment by Cruix** [comment]
Looks like they do. They added a new var to <I>every single item in the game</I> just for tools and they used division instead of multiplication <I>against their own coding standard</I> but I'm not going to fix it if it already works.
