### ISSUE TITLE
 Clock Cultist Watch Bugs when held, Visor button did not work, Kindle is spamable.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19022]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description:  After trying to use clock cultists abilities, holding the Clock Watch, makes all the quickbound spells disappear off the top of the screen.  The Judicial Visor I also could not use at all, plus the new cursor after using the Healing spell stuck on my mouse cursor.  Also someone was able to spam kindle no cooldown like a machine gun.

 Submitted by: Tawaporah Tenderpaw (241348083907166219)

**Comment by ynot01** [comment]
@tattax
