### ISSUE TITLE
HUD bugs

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#19031]
### Severity

Inconvenience

### Short Description

part of HUD stays greyed out, sechud criminal status icons changes are delayed.

### Reproduction

- sechud criminal status icons on people (often) didn't update (only visually) when changed (they stayed the same, or had massive delay at certain times)
- greyed out HUD elements at the top won't become "active" (after slipping, etc.) until you click on them, and you have to start clicking on all of them to restore their opacity.

### Round ID

47377

### BYOND Username

Aquir

**Comment by 00aquir** [comment]
it seems like there are no sechud icons for arrest, paroled, search

**Comment by tattax** [comment]
the status tab is a separate issue that doesn't relate to the other two
