### ISSUE TITLE
Horror can't vent crawl

### ISSUE THREAD

**Issue by Kmla2** [yogstation13/Yogstation#19048]
### Severity

Inconvenience

### Short Description

Trying to vent crawl as an horror doesn't work.

### Reproduction

1. Become an Horror
2. Try to Vent crawl
3. Try to alt click and NOTHING WORKS
4. you  spend rest of your life going into people's departments using maints

### Round ID

round id: 863083

### BYOND Username

Kmla

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

horror doesn't even get an message like "you can ventcrawl if you press alt click on a vent" like they did before

**Comment by tattax** [comment]
couldn't reproduce this in private, possibly something else messed up the VENTCRAWLER_ALWAYS var but it wasn't that pr
