### ISSUE TITLE
 Xenomorph Larva hide ability button no longer works, as well as Eldritch Horror's.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19054]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Xenomorph larva and Eldritch Horrors are unable to hide under tables and similar objects, button just doesn't do anything on the UI.

 Submitted by: Tawaporah Tenderpaw (241348083907166219)

**Comment by tattax** [comment]
eldritch horror can in fact, hide
