### ISSUE TITLE
Polymorphed people should not get silicon laws

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1905]
It's too easy to get confused if someone is turned into a syndicate borg with syndicate laws to get stuck between two rules: Obey Silicon laws Versus Don't antag while being a non-antag

 I think removing the confusion is easy by just removing laws from polymorphed players. They would retain their personalities in RP terms and have their own sense of self to obey or ignore the laws and would still be bound by space law and server rules without getting confused about syndicate law sets.

 This came up because people were debating it in OOC and even a new-min didn't know so fixing this up on the code level should clear up most confusions.

**Comment by Jc1469** [comment]
newmins dont know shit anyways :rofl:

**Comment by Smudged** [comment]
Well, I got word from Adam, If you get changed into a syndi-borg, VIA, staff of change you're an antag, regardless of previous non-antag status.

If there's anything wrong in my reply please repond, but if I'm reading this right, AI laws take rule OVER non-antag status.

**Comment by matskuman5** [comment]
Adam is wrong btw.

2.2.1: Rules still apply to creatures. If you become a slime, a monkey, or are a victim of a staff of transformation, you keep your antagonist/non-antagonist status. When not antagonist, do not use your new form's abilities to grief. This includes syndicate cyborgs. Do not split as a slime in public places.

**Comment by aphielanis** [comment]
I'm guessing this is the ban I missed as I came in to the server with people asking which rules are more important https://forums.yogstation.net/index.php?threads/nervere-matskuman5-other.12998/ or else it's an incredible coincidence.

 Either way it does demonstrate the problem.
