### ISSUE TITLE
Viral Supermatter

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation#1906]
This is a feature idea.

Idea 1:
Emitter beams would go through the supermatter shard and they would be supermatter charged. A new machine would be made, wich converts lasers into energy. So that catches the supermatter beam and creates power. 

The viral part:
Anything the beam would hit, would be supermattered, making it yellow and supermattering anything it comes into contact with. Not adjacten tiles or whatever, that'd be too much. If this happened to mobs, same story, they get turned into supermatter and are dead.

Idea 2: A supermatter shard would be a rare object you'd find on lavaland. It would be weak and not harm miners untill activated. Those shards can be combined and activated to create a bigger shard. Wich can be used for a normal supermatter engine. The longer it gets charged by whatever the engine is, the bigger it becomes. Anything touching it would be supermattered, and be absorbed by a beam into the shard, adding up to it's total mass.

I want to change something about it. I like the second idea most, but I am just gonna ask for opinions here before I start coding something everyone will hate.

**Comment by ShadowDeath6** [comment]
>giving miners the ability to make a supermatter shard

luh

**Comment by Time-Green** [comment]
It would be small pieces, would can only be activated by emitters. It's absolutely useless to them, if you got a better idea of distributing the baby shards, except cargo, tell me.

**Comment by Time-Green** [comment]
I know what I am going to die, I dont need opinions reeeeeeeeeeeeeeeeee
