### ISSUE TITLE
Demon of Sin abilities not working*

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#19061]
### Severity

Round Breaking

### Short Description

Demon of Sin (Pride, assuming others too) button abilities not working

### Round ID

Round #47416

### Test Merges

#18826

### BYOND Username

Crazy_Drakkon; Player affected: CoIoneISanders

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

*Apparently

![image](https://github.com/yogstation13/Yogstation/assets/18729830/3004dc63-7400-4603-985f-52485f0a9de8)

**Comment by tattax** [comment]
it does in fact, work
