### ISSUE TITLE
Add water to watermelons

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#1908]
I mean like really come on, how have we not done this sooner?

(If this gets actually implemented I can't wait for boost trapped exploding plant trays)

**Comment by drderp3635** [comment]
(I meant booby trapped thanks autocorrect)

**Comment by Time-Green** [comment]
"Hey, eat this watermelon!"
"Sure!"
>maxcaps

**Comment by ArgyleSweatshop** [comment]
-Eats banana
-Eats watermelon

-Explodes

**Comment by ShadowDeath6** [comment]
The foods are containers so you'll explode as soon as you harvest them

**Comment by Time-Green** [comment]
There's a mutation that changes that.

**Comment by drderp3635** [comment]
There is on other servers time, but not here sadly
