### ISSUE TITLE
Secure briefcase is invisible inhand from certain angle.

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#19094]
### Severity

Low

### Short Description

The secure briefcase can not be seen inhand when it is on the side of your sprite not facing the screen, it just vanishes.. Manatee closed this issue when I made it before due to 'Its behind your leg innit' but that's not the case.  The normal briefcase is visible on both sides unlike this one.

### Reproduction

get secure briefcase
hold it in left hand
face right
invisible
hold in right hand
face left
invisible

### Round ID

n/a

### BYOND Username

Cark

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by MajManatee** [comment]
Its behind your leg innit. Case is smaller than a normal one or something mate.
