### ISSUE TITLE
Phytosian Martial Art doesn't work

### ISSUE THREAD

**Issue by blakethesnakeLISA** [yogstation13/Yogstation#19097]
### Severity

Round Breaking

### Short Description

Phytosian martial arts don't work

### Reproduction

1. Join the round as a Shaft Miner
2. Buy phytosian martial arts
3. Read it
4. Scroll is unchanged, get Vine snatch, get Remember the Basics verb, it does nothing when clicked, can't re-read scroll
5. Attempt to grab lizard, no combo counter appears, grab is completely normal 

### Round ID

Round #47467

### Test Merges

#18826 #18498 #18502

### BYOND Username

UnscrupulousRealtor

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

I died immediately afterwards because of the bug, so further testing could not be done

**Comment by Oblisk234** [comment]
Can't replicate, martial art works. May have been the fact that you were likely being pushed (which I'm pretty sure can break your grab). Make a new issue if this reoccurs.
