### ISSUE TITLE
Gax tech storage has no insuls or telecomms parts

### ISSUE THREAD

**Issue by UltraBigRat** [yogstation13/Yogstation#19119]
### Severity

Inconvenience

### Short Description

Gax unlike every other station has no insuls or telecommunications parts in tech storage.

### Reproduction

1. Look inside tech storage 
2. no yellow gloves :(
3. want to make makeshift emag or repair broken telecomms
4. nobody ever researches telecomms parts and theres  none on the sad gax tech storage
5. along with none of the other  goodies you may want from it

### Round ID

irrelevant

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Not sure if this fits a bug report but its an expected part of a map that is missing and reduced to a stack of boards.

**Comment by ReddicusDragon** [comment]
tcomms parts in ai satellite; get the gloves from a vendor. Invalid issue.
