### ISSUE TITLE
Gamemode votes default to secret

### ISSUE THREAD

**Issue by UltraBigRat** [yogstation13/Yogstation#19159]
### Severity

Inconvenience

### Short Description

Long standing 'bug' that causes everyone who didnt vote on a gamemode vote to automatically vote secret.

### Reproduction

1. Admin makes gamemode vote
2. people vote
3. the results dont actually matter because a large portion of players didnt vote at all which filled it up with secret votes
4. vote meant absolutely nothing

### Round ID

irrelevant

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

Should probably be changed so that those who didnt vote arent included, instead of being placed as voting for secret. Gamemode votes are rare anyways, and should actually decide the gamemode.

**Comment by tattax** [comment]
possibly intended but i'll leave it open

**Comment by MajManatee** [comment]
is intended. Same thing for map votes. The majority of players wanted Secret and Box so those are the default votes if you do not vote.
