### ISSUE TITLE
Blob + vines? - No visible melee attack against them

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1916]
Apparently noone could use tools. No welder. No fire axe. Any intent. The action doesn't even start.
Melee worked on blob zombie and blob spore. Guns worked.

Server time 2017-03-01 02:30

![ss13-blobbug](https://cloud.githubusercontent.com/assets/16806055/23442333/191ed03e-fe28-11e6-8393-11caf9fe9e67.png)

**Comment by Gintoki1** [comment]
I was abserving this round and gotten tickets saying nobody can attack the blob. I've had no idea what was causing this bug to happen.

**Comment by 00aquir** [comment]
update: We had some vines now, I tried welder and fire axe on harm intent. I thought it will be the same thing.
Except that at the 40th click (still no action visible) the vine tiles started to disappear, but way slower than what would be necessary to fight them back at a normal rate, I tried it and I only could get 2-3 tiles while they already grew back elsewhere, so it was not sustainable.

![ss13-vinebug](https://cloud.githubusercontent.com/assets/16806055/23478417/9bc33d60-fec1-11e6-8012-fe13dee40f45.png)

**Comment by ShadowDeath6** [comment]
is this happening consistently or only sometimes?

**Comment by Gintoki1** [comment]
I haven't been on as much unfortunately, but I had a chaplain said he couldn't attack the blob for some reason with any melee weapon.
I say it's been happening occasionally from time to time, but not every time

**Comment by Time-Green** [comment]
SHIT.
I WONDERED IF TOUCHING ALPHAFADE COULD GO BAD.
WEELLLPPPPPPP.

**Comment by Lightning38088** [comment]
blobs are evolving for the worst scree
also i haven't seen this happen in a while

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/1949
