### ISSUE TITLE
Scrubber controls not working for SM scrubbers

### ISSUE THREAD

**Issue by AJHcHenry** [yogstation13/Yogstation#19179]
### Severity

Round Breaking

### Short Description

Per title, bluescreen on trying to change SM scrubber controls

### Reproduction

Try to set scrubber controls on the control panel for SM, get a fatal exception.

### Round ID

47576

### BYOND Username

AJHcHenry

### Was this done on a locally hosted or non-Yogstation hosted server?

Yes

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/issues/19185
