### ISSUE TITLE
Telekinesis doesn't work on consoles

### ISSUE THREAD

**Issue by Kmla2** [yogstation13/Yogstation#19182]
### Severity

Inconvenience

### Short Description

Interacting with consoles using Telekinesis on range doesn't work

### Reproduction

1. Get Telekinesis from Genetics
2. Try to use TK on a console, ranged
3. Nothing happens but the particles still happen on it

### Round ID

Round id: 47576

### Test Merges

#13479 #14802 #19115 #18502 #18498

### BYOND Username

Kmla

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by neeshacark** [comment]
not a bug iirc, was an intentional nerf to TK
