### ISSUE TITLE
Atmos, SM filters or air alarm scrubbing don't work

### ISSUE THREAD

**Issue by Kmla2** [yogstation13/Yogstation#19185]
### Severity

Inconvenience

### Short Description

filters or air scrubber page show you a NT error page

### Reproduction

1. Be an atmos technician or a ghost
2. Try to Create fusion (or check on the filters on the sm as a ghost)
3. Filters don't work
4. try to just use an air alarm scrubbing instead, NT ERROR AGAIN!@!$
5. maybe cry

### Round ID

round id: 47577

### Test Merges

#13479 #14802 #19115 #18502 #18498

### BYOND Username

Kmla

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

this is what comes up for filters:
![image](https://github.com/yogstation13/Yogstation/assets/117773464/4d38f317-06bf-4a94-a35c-04553aa9114e)

this is what comes up for the air alarm scrubbers:
![image](https://github.com/yogstation13/Yogstation/assets/117773464/0f788357-2a1c-43be-8109-207ddfd1e7ae)

**Comment by ToasterBiome** [comment]
@jupyterkat

**Comment by Kmla2** [comment]
seems fixed
