### ISSUE TITLE
 Time erasure ability for holoparasites does not work at all

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19201]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: When i tested it with my holopara it just did nothing, also using the ability when not manifested "uses" it and puts it on cooldown when nothing actually happened

 Submitted by: masterdrake (598557108551811073)

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/issues/19153
