### ISSUE TITLE
You can't make hydrogen with Space electrolyzer

### ISSUE THREAD

**Issue by Kmla2** [yogstation13/Yogstation#19219]
### Severity

Inconvenience

### Short Description

Space electrolyzer doesn't work for making hydrogen. i don't know if its only for making hydrogen or anything else

### Reproduction

1. Join your round as an atmos technician
2. Plan on making metal hydrogen
3. Make a crystallizer
4. pump BZ in, no problem
5. then make a chamber full of water vapor, and an turned on electrolyzer for hydrogen
6. Perform multiple gas scans, still only water vapor there
7. Wait some minutes, maybe atmos is just updating
8. still nothing, scan all the pipes in the search of HYDROGEN!
9. Nothing is there

### Round ID

Round Id #47609

### Test Merges

#18498 #18502 #19115 #14802 #13479

### BYOND Username

Kmla

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by JohnFulpWillard** [comment]
![image](https://github.com/yogstation13/Yogstation/assets/53777086/7a707f76-8b86-4220-a765-0f60fcba5bde)
