### ISSUE TITLE
Unable to eletrolyze water vapor to produce h2

### ISSUE THREAD

**Issue by Aztronozes** [yogstation13/Yogstation#19217]
### Severity

Inconvenience

### Short Description

Cant make hydrogen because eletrolyzer isnt electrolyzing water vapor

### Reproduction

1.join scientist
2.plan to make powerful bomb
3.make freon
4.get water vapor canister to electrolyze it
5.nothing happens(hydrogen isnt produced)
4.commit suicide because you got nothing better to do

### Round ID

I dont remember

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by tattax** [comment]
closing this one as (https://github.com/yogstation13/Yogstation/issues/19219) has more info
