### ISSUE TITLE
Unholy Staff isn't available in the chap null rod menu anymore.

### ISSUE THREAD

**Issue by Yarinoi** [yogstation13/Yogstation#19252]
### Severity

Inconvenience

### Short Description

Title says it all.

### Reproduction

1. Be chap.
2. Try to change null rod
3. No unholy staff????
4. Depression

### Round ID

47643

### Test Merges

#18498, #14502, #14802, #13479

### BYOND Username

Yarinoi

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by tattax** [comment]
there is no weapon with the name "unholy staff" in the code

**Comment by Yarinoi** [comment]
wtf?? what happened to my cool red staff?

**Comment by tattax** [comment]
> wtf?? what happened to my cool red staff?

got merged into the blue one in:
https://github.com/yogstation13/Yogstation/pull/18373

**Comment by tattax** [comment]
if you want it added back i suggest making a new issue (feature request)
