### ISSUE TITLE
"Metastation" escape pod 1 does not land.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#1925]
-but remains in space after the round end. (at least in round 17573)

**Comment by ThatLing** [comment]
Is this still an issue?

**Comment by 00aquir** [comment]
- yes, seemingly every time.
- also, as ghost after round end, I could only teleport to escape pod 1, not sure that the others exist, even though there are airlocks for them

**Comment by Ktlwjec** [comment]
Doesn't seem to be an issue still.
