### ISSUE TITLE
 The downside of Gangrel is simply non existant

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19269]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Picking Gangrel removes your masquerade ability everything sounds fine right? No you can just instantly buy it again right after picking Gangrel

 Submitted by: DINOSSAUROdoACRE (560477442611871746)

**Comment by tattax** [comment]
intended, you have to spend one rank to get it back, and it's not the only downside
