### ISSUE TITLE
 When standing near an intercomm and using a headset to speak to a deparatamental channel the message gets redirected to common instead

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19285]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Often when I want to say something to a departmental radio channel the message gets sent to common instead and uppon closer examination I discovered that's because I am standing next to an intercom. This is pretty common because the station is littered with them, even the brig, so I end up leaking security comms on accident pretty regularly and that's devastating. I know that it's a bug and not a feature because it didn't used to work like this and weeks ago Waterpig showed me the PR (by Redmoogle I think) which made it this way. It intended to allow for use of departmental comms through the intercomm but its bugged and instead redirects any message to common, no matter it's designated destination

 Submitted by: tipy1802 (294147033848217600)

**Comment by Oblisk234** [comment]
Was fixed by #21991
