### ISSUE TITLE
Candle pack spawns invisible

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/Yogstation#19291]
### Severity

Inconvenience

### Short Description

Candle pack spawns invisible

### Reproduction

1. Choose the spiritual quirk before the round start
2. Join the game
3. Look I your backpack to find a slot filled by an invisible pack of candles

### Round ID

47670

### BYOND Username

Drderp3635

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by ktlwjec0** [comment]
all of the boxes are spawning in with 7 items inside which means things like candle packs and donut boxes are invisible since they have no sprite for it, egg boxes are down to 7 eggs instead of 12, etc

47643 is the round number it seemed to first start happening
