### ISSUE TITLE
 Humans Can't bleed according to quirks

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19315]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Tried to get some quirks back due to quirks resetting, couldnt equip hemophiliac due to "You can't Bleed" while currently playing as a human

 Submitted by: englishscotsman (740223180806946946)

**Comment by tattax** [comment]
see also: https://github.com/yogstation13/Yogstation/issues/18895
