### ISSUE TITLE
Stalwalt doesn't drop a trophy upon defeat

### ISSUE THREAD

**Issue by Kmla2** [yogstation13/Yogstation#19329]
### Severity

Low

### Short Description

Stalwalt doesn't drop a trophy upon defeat

### Reproduction

1. Become a shaft miner
2. Choose crusher as your first weapon
3. Rush Stalwalt without mining anything
4. Kill stalwalt with a crusher
5. open his loot chest
6. There seems to be no trophy in the chest
7. Try to kill other megafauna and live happily

### Round ID

ROUND ID: 47731

### Test Merges

#18498 #18502 #19287 #13479

### BYOND Username

Kmla

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

I don't know if this is intended or not, but its still a problem for the crusher mains

**Comment by tattax** [comment]
pretty sure it was A: never added or B: the sprite is non existant such as the spear

**Comment by Oblisk234** [comment]
Stalwart does not have a crusher trophy.
