### ISSUE TITLE
Implanted icon for antag hud 

### ISSUE THREAD

**Issue by Gintoki1** [yogstation13/yogstation#1945]
Just wondering shouldn't players who are mindslave have an antag icon or some kind of icon to indicate it?

**Comment by AdamElTablawy** [comment]
I discourage the addition of more team huds.

Plus it adds the possibility of someone else, possibly a traitor or ling, impersonating the mindslave.

**Comment by Lightning38088** [comment]
There should'nt be a reason for this since you get a message on who implants you when you're made loyal to them.
