### ISSUE TITLE
Blood altar is broken

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19474]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description:Was a bloodsucker, became a gangrel, built a blood altar, clicked it and it told me i had a task which didnt show up in chat or notes and further clicking even on other nights just said i still had a task, making it unusable.

 Submitted by: ultrabigrat (225615376828989440)

**Comment by Oblisk234** [comment]
Replay clearly shows that you were given a task ("You have gained a new Task! Sacrifice 1 hearts by using them on the altar. Remember to collect it by using the blood altar!").
