### ISSUE TITLE
Welders don't work on blob tiles.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#1948]
Please fix this
(quickly)

**Comment by Daman453** [comment]
Can confirm, no one could defeat me as blob. Broken as all hell.

**Comment by 00aquir** [comment]
reference https://github.com/yogstation13/yogstation/issues/1916

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/1949
