### ISSUE TITLE
Jungle Salad and Melon Fruit Bowl make you explode

### ISSUE THREAD

**Issue by VomitPukeLover123** [yogstation13/Yogstation#19504]
### Severity

Low

### Short Description

Potassium and Water mix during the making of the salads, causing an explosion to occur

### Reproduction

1. Join as Cook/Botanist.
2. Get ingredients for either salad.
3. Go into the crafting creation tab, selecting the "Salads" section.
4. Press "Craft" on the Jungle Salad or Melon Fruit Bowl.
5. Explode.

### Round ID

Round #48016

### Test Merges

#18498 #18502 #19287 #18947 #18054 #13479

### BYOND Username

ServerRoomAccountant

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

The explosion seems big enough to create a small hull breach so this should really get worked on to not create large problems for the engineering department later, as they already have to deal with chemistry methamphetamine-related explosions on a large basis.... :(

**Comment by SomeguyManperson** [comment]
Lol
