### ISSUE TITLE
Add a small medbay room for injured sec can use for prisoners or other sec

### ISSUE THREAD

**Issue by Lightning38088** [yogstation13/yogstation#1952]
Instead of SH-....security just letting people to die in brig or risk being interupted on the way to medbay healing a shitler or a actual threat, they have access to a small medbay in brig with one sleeper, and a burn and brute box. Only security and medical staff can access to this sleeper since we don't need antags camping perma or armory healing their friends quickly.

**Comment by ShadowDeath6** [comment]
Aka security morphine dispenser

**Comment by Super3222** [comment]
It wouldn't hurt. We just need a mapper for it.

**Comment by matskuman5** [comment]
I'll map this, gimme a minute

**Comment by Lightning38088** [comment]
> It wouldn't hurt.

Not if we add it hehehe (bad pun)

**Comment by Penguaro** [comment]
@matskuman5 @Cruix This issue was resolved.
