### ISSUE TITLE
Preternis ID cannot be stripped

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#19533]
### Severity

Round Breaking

### Short Description

Only admin could remove a preternis' ID, it remained hidden.

### Reproduction

- admin had to put clown "Shithead The Irritator" into a new body to separate them from their ID

### Round ID

48055

### BYOND Username

Aquir

**Comment by SomeguyManperson** [comment]
Robot parts allow you to equip things without a jumpsuit that would usually require a jumpsuit
Issue: the strip menu doesnt know this and refuses to display those items unless a jumpsuit is present

I did however have a similar issue with suit storage not showijg up in the strip menu despite the person having a suit and having an item innthe storage slot

**Comment by Oblisk234** [comment]
Can't replicate, able to strip ID perfectly fine from preternis, not hidden.

**Comment by Oblisk234** [comment]
Can't replicate on second test, again able to remove ID, put it on for preternis. Item slot is not hidden.
