### ISSUE TITLE
Automod mutes players if they do a chaplain ritual too many times.

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#19558]
### Severity

Round Breaking

### Short Description

The automod spam mute seems to like to mute players if they do a ritual too many times in a row.  This can be very bad if no staff are on to fix it

### Reproduction

1. be chap
2. do ritual 20 or so times
3. get muted from say

### Round ID

n/a

### BYOND Username

Cark

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by MajManatee** [comment]
good.
