### ISSUE TITLE
Blood demons glitch the fuck out and get erased from the game when exiting blood

### ISSUE THREAD

**Issue by Lightning38088** [yogstation13/yogstation#1957]
Mats can say he saw this happen MULTIPLE TIMES SCREEEEEEEEEEEEEEEEEEEEEEEEEE but for fucks sake its annoying it might have to do with the bubbles? but i couldn't move or been seen when exiting ANY puddle....

**Comment by ShadowDeath6** [comment]
was the blood being cleaned or something

**Comment by Lightning38088** [comment]
no it was just normal and i could not rise out of it even though it said i did

**Comment by ShadowDeath6** [comment]
was a new effect being added to the turf before the progress bar ended? like someone bleeding onto the tile you were popping out of

**Comment by Lightning38088** [comment]
nope it was just a regular blood pool

**Comment by Trojanplunder** [comment]
I had this issue as well a couple days ago. The only difference was that it was a dried blood pool. Someone crowbarred the tile to see if it would do anything and I was ghosted.

**Comment by Trojanplunder** [comment]
Forgot to mention, I was a laughter demon instead of the regular slaughter demon. Don't know if that makes any difference.

**Comment by ShadowDeath6** [comment]
This was most likely fixed in https://github.com/yogstation13/yogstation/pull/1963
