### ISSUE TITLE
Black Powder in Cigars and Cigarettes should explode when lit

### ISSUE THREAD

**Issue by Frostben** [yogstation13/yogstation#1959]
It doesn't make much sense that you hold a lit flame to the end of a cigar or cigarette filled with BP without it blowing up does it?
Also it'd be neat if it did some serious damage to your eyesight and hearing and/or blows off your tounge if you light it in your mouth.

**Comment by Time-Green** [comment]
lit af

**Comment by Frostben** [comment]
Hallelujah.
