### ISSUE TITLE
 Dark blessing is a bonking stick

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19609]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: dark blessing  null rod isnt sharp and makes a blunt object  sond when hitting someone. Despite looking like an armblade

 Submitted by: ultrabigrat (225615376828989440)

**Comment by UltraBigRat** [comment]
im dumb and it just makes odd noises, closing this when possible
