### ISSUE TITLE
Breath mask hud is slighty bugged

### ISSUE THREAD

**Issue by Kmla2** [yogstation13/Yogstation#19668]
### Severity

Low

### Short Description

Breath mask hud being up alyways exists, even if you put the mask down

### Reproduction

1. Join the round as any job
2. Take your breath mask out of backpack
3. Put it on
4. Click Adjust breath mask
5. The earlier hud state icon is still... there? (Additional information has the screenshot on how it looks)
6. Be angry
7. turn your breath mask up 
8. Be happy

### Round ID

Round ID: 48200

### Test Merges

#18498 #18502 #18947

### BYOND Username

Kmla

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

this is what the hud of the oxygen mask while its down looks like:
![Breathmaskstupid](https://github.com/yogstation13/Yogstation/assets/117773464/72620789-e174-4e50-aea5-ac07abf6618f)

**Comment by JohnFulpWillard** [comment]
Issue related to https://github.com/yogstation13/Yogstation/pull/19643 you should've reported it there
Also it's already been fixed.
