### ISSUE TITLE
Make mime be able to speak when clockwork antag

### ISSUE THREAD

**Issue by Lightning38088** [yogstation13/yogstation#1966]
I spent 30 mins into the round not saying a word and unable to do shit since it gave me "ITS TOO EARLY IN THE ROUND, PLAY YOUR PART" (we still won cause I just raided armory and got other people to convert people I caught for me) but yeah it should at least give you the option to break your vow early if your a mime clockwork antag.

**Comment by Super3222** [comment]
Sounds fair. I'll see what I can do.

**Comment by drderp3635** [comment]
A talking mime is no mime at all. 

If you weren't ready to suffer in silence you shouldn't have picked mime

**Comment by Lightning38088** [comment]
Pick mime to not talk> RNG picks mime for antag which uses words and cannot to ANYTHING but use the network to talk with other cultists if unable to speak....

**Comment by Super3222** [comment]
@drderp3635 could say the same thing for clown antags, no? If you weren't ready to act retarded then you shouldn't have picked the clown.
