### ISSUE TITLE
New soundscapes cut out when you move around between them (maint and public areas I THINK!?!?) (BUT ALSO RANDOMLY!?!?!?) , making a constant clicking noise that makes me think my headset is fucked up but its just coders again causing me existential dread. Plus I can hear stuff from REALLY far away sometimes and it confuses the shit out of me when I hear footsteps in a direction but nobody is there and by the time I walk over whoever WAS making those sounds is gone or maybe they never existed in the first place!?!?!?

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#19677]
### Severity

Round Breaking

### Short Description

THE GODDAMN SOUNDS WONT STOP

### Reproduction

1. EXIST
2. MOVE AROUND
3. CLICK CLICK CLICK CLICK CLICK

### Round ID

n/a

### BYOND Username

Cark

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by Mqiib** [comment]
Ok but the distant footsteps are _atmospheric_

**Comment by neeshacark** [comment]
> Ok but the distant footsteps are _atmospheric_

they tend to also be grenades being primed and other stuff and it is deeply concerning to me but the main point of this pr is the clicking noises

**Comment by azzzertyy** [comment]
i literally have no clue what this issue is on about

**Comment by MajManatee** [comment]
his headphones are on backwards
