### ISSUE TITLE
 Visual penlight barrier error

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19693]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Pulsing error sign instead of a holobarrier, probably from the recent testmerge.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1129969518144401408/image.png)
 Submitted by: loiosh42 (886316591342555156)

**Comment by JohnFulpWillard** [comment]
![image](https://github.com/yogstation13/Yogstation/assets/53777086/11c76d19-637f-4ce4-8f10-10732d22497f)

the error on airlocks were too many overlays which has been fixed. Not holobarriers.
