### ISSUE TITLE
Making meth causes a giant explosion

### ISSUE THREAD

**Issue by Yackitori** [yogstation13/yogstation#197]
Making meth causes an explosion that is so explosive, it will actually breach the floors, and instakill you. The explosion only happens when the solution is heated. Gray tells me it might not be a bug.

EDIT: Now that I know it's a feature, remove plz

**Comment by timkoster1** [comment]
Oh my god, I did that when I was on meth and my body flew on fire. 

Feature.

**Comment by EMT321** [comment]
This is hilarious. Keep it.

**Comment by X-TheDark** [comment]
Temperature to mix Meth = 374
Temperature for Meth to explode = 380

Solution is simple, don't explode yourself.

**Comment by Cruix** [comment]
This was always intended, and frankly I think there should be more recipes that do stuff with temperature like this.
