### ISSUE TITLE
Deluxe Syndicate toolbox creates 'Syndicate Combat Gloves'

### ISSUE THREAD

**Issue by Addust** [yogstation13/Yogstation#19708]
### Severity

Quality of Life

### Short Description

uhhh, why are they uniquely syndicate? syndicate combat gloves. why. on god's green earth.

### Reproduction

1. deluxe syndie toolbox
2. syndicate combat gloves
3. what

### Round ID

any round id after the thingymajig was merged

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

werhwerj

**Comment by ynot01** [comment]
SYndicate

**Comment by Oblisk234** [comment]
Because, it's syndicate combat gloves. Who doesn't want syndicate brand gloves?
