### ISSUE TITLE
 Some sprites dont have icons anymore for whatever reason

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19702]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: As title, sprites like cigarette boxes and rolling paper just dont work no more

 Submitted by: azzzertyy (196392067281321985)

**Comment by JohnFulpWillard** [comment]
Issue related to https://github.com/yogstation13/Yogstation/pull/19643 you should've reported it there
Also it's already been fixed.
