### ISSUE TITLE
Clownbug sprites broke

### ISSUE THREAD

**Issue by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [yogstation13/yogstation#1972]
Clownbugs have no sprite so unruly admins can place hundreds of them, and unsuspecting victims will have their ears blown out when they step on the honk mine

**Comment by drderp3635** [comment]
How do you ever remember your username

**Comment by Notamaniac** [comment]
Ctrl-C

**Comment by Super3222** [comment]
Real question is who's cruel enough to spawn clownbugs?

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I suppose you haven't seen the 477 clownbugs on the shuttle

Man the echoing honking sounds they made were epic

**Comment by Gintoki1** [comment]
I feel like it's a feature because of that ^

**Comment by ShadowDeath6** [comment]
@Super3222 fix shit pls
