### ISSUE TITLE
 chasm fishing fails

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19727]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: if you land on top of another mob in a chasm you get moved onto the adjacent turf but not fished out while the other mob is fished out as normally
also things that arent mobs cant be fished out at all

 Submitted by: snoobper (1079798074068709386)

**Comment by Moltijoe** [comment]
Not an issue, mobs are fished out one at a time in an area
Not fishing out items is intended otherwise you could ignore the chest and fish it back up later
