### ISSUE TITLE
Booze dispenser/soda dispenser bug

### ISSUE THREAD

**Issue by Therandomhoboo** [yogstation13/Yogstation#19736]
### Severity

Inconvenience

### Short Description

Glasses keep stacking up in the machine on visual

### Reproduction

1. Put glass/bottle/container holder into machine
2. remove it
3. repeat
4. the glasses dont disappear

### Round ID

48279

### BYOND Username

therandomhoboman

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

![image](https://github.com/yogstation13/Yogstation/assets/116853115/009155b1-a4fb-4dca-bea9-3242735fdb0d)

**Comment by JohnFulpWillard** [comment]
Issue related to https://github.com/yogstation13/Yogstation/pull/19643 you should've reported it there
Also I fixed it in latest commit, testmerge will require updating.

**Comment by Therandomhoboo** [comment]
> Issue related to #19643 you should've reported it there Also I fixed it in latest commit, testmerge will require updating.

didn't know there was a pr relating to it in all honesty
