### ISSUE TITLE
clown's flower has space lube at the start of the round

### ISSUE THREAD

**Issue by Lightning38088** [yogstation13/yogstation#1977]
Honk o<0   It'll be funny to see and give more of a reason to use the flower more since i enjoy watching people slide into sp-  a hallway when walking through i lubed door.

**Comment by Jc1469** [comment]
[how bout no](http://puu.sh/uIAPk/f8c7bc5ac0.png)

**Comment by Gintoki1** [comment]
You shame my horn...

**Comment by Cruix** [comment]
You worded this like a bug report rather than a feature request.
So I am going to act like this is a bug report and say I cannot reproduce this.
