### ISSUE TITLE
 Slimeperson blood isnt blood in the eyes of virology

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19837]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: When slime blood in inserted into the viro machine, it is not recognised as blood, and cant be used to see if you have a stealth virus or not

 Submitted by: englishscotsman (740223180806946946)

**Comment by JohnFulpWillard** [comment]
Assuming this is also the case for Ethereals, non-blood "blood" isn't actually blood, and it's a minor problem.

**Comment by Moltijoe** [comment]
intentional
