### ISSUE TITLE
Potted plant stuck on player model

### ISSUE THREAD

**Issue by ikeetgeenpatatwaterisnat** [yogstation13/Yogstation#19864]
### Severity

Inconvenience

### Short Description

Upon picking up a potted plant it will replace your player model and you can't drop it.

### Reproduction

1. Join the round as assistant
2. Equip the Rod of the White and use it.
3. Pick up a potted plant
4. The potted plant replaces player model
5. The potted plant cannot be dropped as it is not something I am carrying on my character
![Potted plant player model bug](https://github.com/yogstation13/Yogstation/assets/58261527/2e64b36f-f02a-48fa-bb8e-11b3dbf3e3fc)

### Round ID

48381

### BYOND Username

Shadebow

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by tattax** [comment]
@JohnFulpWillard
