### ISSUE TITLE
 Space-time anomalies send you off z-level on icemeta

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19872]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: walking into a vortex has massive chances to send you to either the mining level or other z levels. This, for most roles and people is the equivalent of getting killed and round removed.

 Submitted by: enkidienne (251840624829923328)

**Comment by N3D6** [comment]
i like this lmao it's the icemeta equivalent of one of them spacing you skill issue

**Comment by MajManatee** [comment]
the creator of icemeta has deemed this an intended feature

**Comment by N3D6** [comment]
> the creator of icemeta has deemed this an intended feature

and it also doesn’t infinitely strand you anymore on a level with no comms all 3 levels have comms now

probably can close this
