### ISSUE TITLE
the nukie telecomms mainframe has been invisible for like a year now and NONE OF YOU NOTICED

### ISSUE THREAD

**Issue by Addust** [yogstation13/Yogstation#19883]
### Severity

Inconvenience

### Short Description

nukie comms mainframe invisible

### Reproduction

1. look at nukie comms mainframe
2. realise all you see is empty floor
3. scream

### Round ID

48396

### BYOND Username

Addust

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

has been done on a localhost personal server (where i made myself a custom nukie base for shits and giggles built into an asteroid that does not comply with any form of modern syndie lore but does have a nice hangar)

**Comment by Addust** [comment]
here's yer bloody confirmation
<img width="329" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/82ce5cfd-7c9f-4295-8ac8-6fe54cde68fc">

**Comment by MajManatee** [comment]
do they uh... need that...?
