### ISSUE TITLE
stabilized cerulean dosent work 

### ISSUE THREAD

**Issue by LassiH** [yogstation13/Yogstation#19918]
### Severity

Round Breaking

### Short Description

die with stablized cerulean  did not posess clone

### Reproduction

1 equip stabilized extract
2 die with stablized extract
3 fail to transfer to clone

### Round ID

48440

### Test Merges

#19813

### BYOND Username

lassih

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Oblisk234** [comment]
Was fixed by #22448
