### ISSUE TITLE
 Eldrich horror cant use it's abilities on people that move

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19940]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Trying to consume soul, take control of the body, or trying to get out of the body, all of them start the progress bar, but as soon as the host moves the action cancels itself. Note that this was curator's special horror (same thing, but might be worth knowing).

 Submitted by: pibecantina (341102461504716800)

**Comment by JohnFulpWillard** [comment]
What ability is this called? Or do ALL abilities not work?

**Comment by PibeCantina** [comment]
Abilities are all the ones that require a progress bar

Consume Soul
Assume Control
Release host (not sure if it was called exactly this)

I havent tried Transfer Between Hosts but it would probably not work since the other ones also didnt
