### ISSUE TITLE
 Teleporting out of aggressive grabs breaks your arms

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19953]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: As a luminescent, using bluespace minor to teleport out of someones aggressive grab while buckled will completely break your interactions, you cant pick anything up

 Submitted by: englishscotsman (740223180806946946)

**Comment by tattax** [comment]
pretty sure this is fixed by https://github.com/yogstation13/Yogstation/pull/19954, reopen if there is still a problem
