### ISSUE TITLE
AOs unable to pull up ticket list to view tickets

### ISSUE THREAD

**Issue by Lightning38088** [yogstation13/yogstation#1995]
^ plus we should be able to close tickets when the client has left (also fuck screee)

**Comment by Jc1469** [comment]
:thinking:

im not seeing a problem

**Comment by Lightning38088** [comment]
seems dumb that we're supposed to observe tickets, yet can't pull up the ticket list to view one....

**Comment by Super3222** [comment]
This was an intentional change done by JC awhile ago. Feel free to discuss it.

**Comment by Lightning38088** [comment]
I was told so by slinky, but i thought maybe i could suggest letting AOs be able to view the ticket list since i don't see why it needed to be removed in the first place.

**Comment by Slinky5890** [comment]
It's because of other permissions tied with the adminlisttickets function

**Comment by Jc1469** [comment]
preferences -> monitor all tickets.
