### ISSUE TITLE
 Gloves of the north star don't work as a cat person

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19965]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Gloves of the north star don't work as a cat person, you can click as fast as you’d like, but your attacks will be limited by normal attack time

 Submitted by: zer0tactics (412038981669355560)

**Comment by Addust** [comment]
thats what you get for being a fucking felinid

**Comment by Runian** [comment]
Can't reproduce on local.
![catgloves](https://github.com/yogstation13/Yogstation/assets/30399783/3148f8a3-b7d6-44e1-a647-720d1a467556)

**Comment by BobTheButton** [comment]
NOOO THEY KILLED MOJA

**Comment by Oblisk234** [comment]
Can't replicate on second test.
