### ISSUE TITLE
Make Ghost pointing arrow

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#1997]
Ghosts can point at things, it's in chat, but you can see nothing.. make a purple pointing arrow for ghosts please.

**Comment by ShadowDeath6** [comment]
arrows do show up tho

**Comment by 00aquir** [comment]
Try connecting to the game as Observer from the start. That way I saw nothing when pointed at things.

**Comment by ShadowDeath6** [comment]
arrows are effects so it could be caused by #1880

**Comment by Time-Green** [comment]
no

**Comment by 00aquir** [comment]
apparetnly it's good now
