### ISSUE TITLE
 Vampire 'aquired blood' resets with new mind.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19970]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Latejoined as Hides-The-lockers, vampire, they had like 250 accumulated blood or so, but for some reason I didn't have zilch in my aquired. Could have just chugged blood bags or something, but suspicious enough I'm posting it

 Submitted by: lichton (271438688100024320)

**Comment by tattax** [comment]
apparently was just blood bags from what i saw in the discord
