### ISSUE TITLE
 Hallucinating too much from mushrooms crashes your game over and over and keeps its effect forever till death

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#19975]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: got mushroom hallucinogen and carbon from scrubber event, acted normally until the drugged effect went off, but the screen shake remained, once it ended the screen shake remained and got really really big (if i had to guess i could see 2 or 3 screens away) and started crashing, slowly hobbled my way to medbay to see if i was still had mushrooms in me, i didnt, then asked for death and it stopped when dying. getting revived was normal

 Submitted by: englishscotsman (740223180806946946)

**Comment by tattax** [comment]
see: https://github.com/yogstation13/Yogstation/issues/19537
