### ISSUE TITLE
Some botany trays only produce 1 plant

### ISSUE THREAD

**Issue by TristanSaucy** [yogstation13/yogstation#1999]
Despite having yields like 6,7,8,9,10 or whatever have you, some trays only produce one plant. I will try to isolate and determine what is causing this.
![af7f7bddc140c0a734e5a4a91437aacc](https://cloud.githubusercontent.com/assets/26293183/24022810/958a6ec6-0a76-11e7-8d2b-6156dd3b3cfc.png)
![e81cdf9b47b85da1f5f7b41d4a779c02](https://cloud.githubusercontent.com/assets/26293183/24022812/9938a128-0a76-11e7-8407-b631bd236f8e.png)

Further findings 

Unwrenching and rewrenching into same place does not fix it. Neither does moving it to another spot. Moving another tray into the broken spot does not break it, leading me to believe it is tied to the tray.

**Comment by drderp3635** [comment]
You had left for zed in the trays probably
