### ISSUE TITLE
 Wallets turn invisible when it contains a makeshift ID

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20004]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Title explains it.

 Submitted by: englishscotsman (740223180806946946)

**Comment by 00aquir** [comment]
connected https://github.com/yogstation13/Yogstation/issues/16331
connected https://github.com/yogstation13/Yogstation/issues/19823
