### ISSUE TITLE
 You can mutate fire breath as a non-lizard

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20005]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Shitcode allows you to acquie firebreath as a non-lizard, poorly ported feature, resulting in constant powergaming and overall unfun rounds if you are going against one such bug abuser. In the round ID cited, at around 20mins, you can see how a wizard gets instantly critted by a human with fire breath even through armor

 Submitted by: riquegameplays (494257568324255745)

**Comment by Tenn0x** [comment]
I dont think it's a bug at all. Fire breath can only be found naturally on lizards, but once saved can be printed as mutators and be used on other species. Just like dwarfism can only be found on humans but other species may use mutators of them. It WOULD be a bug if fire breath was being found naturally on other species, which it isnt.

**Comment by Marmio64** [comment]
yes, this is intentional by my knowledge. Even if not intentional, it's not like it is stronger for other species, a lizard could do the same thing to that wizard.

**Comment by solwashere** [comment]
This is a feature

**Comment by SomeguyManperson** [comment]
species restrictions on mutations are just for it being naturally occurring, not for it being applied via a mutator

Of course fire breath is exceptionally nasty for an asspull ability with no tells

**Comment by ToasterBiome** [comment]
not a bug
