### ISSUE TITLE
Mouse's cheese powers don't last

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#20010]
### Severity

Low

### Short Description

Post-cheese powers last like a fraction of a second

### Reproduction

1. Eat cheese as mouse

### Round ID

Round #48609

### Test Merges

#19813, #18054, #19968

### BYOND Username

crazy_drakkon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by MajManatee** [comment]
PROBABLY delta_time related
