### ISSUE TITLE
Mjolnir stuns you

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#20028]
### Severity

Round Breaking

### Short Description

Mjolnir for some reason has started stunning people on hit, it didn't used to do this.

### Reproduction

1. be hit by mjolnir
2. stunned for 5 seconds

### Round ID

Round #48637

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by tattax** [comment]
it has always been like this
