### ISSUE TITLE
Can't ban most ghost roles

### ISSUE THREAD

**Issue by Slinky5890** [yogstation13/yogstation#2006]
I could be entirely wrong here and missing something, but I can't find a way to ban someone from ghost roles outside of pAI, drone, posibrain and deathsquad. This is very irritating as I end up having to ban people from just those roles when they fuck up as an ashwalker. Also the banning panel (the one we use when someone is offline)doesn't have some roles, such as abductor (and many others i'm sure, too tired to recall which are missing).

**Comment by Slinky5890** [comment]
Also, just as a quality of life thing, it'd be great if the banning panel had the same lovely layout as the ban button from someone's online player panel. It'd be nice to ban all head roles at once as opposed to having to ban each one individually just cos the player is offline.

**Comment by Groudonmaster** [comment]
If you open the mobs pp it'll let you access standard banning and you can ban from there

**Comment by Slinky5890** [comment]
I can't use the mob's PP ban when they're offline though

**Comment by doerakpoes** [comment]
We need discord shrugs
