### ISSUE TITLE
ipcs and preternis dont benefit from bloodsucker healing like they are supposed to

### ISSUE THREAD

**Issue by LassiH** [yogstation13/Yogstation#20075]
### Severity

Round Breaking

### Short Description

mechanical races dont heal as bloodsucker like they are supposed to

### Reproduction

1. join as preternis or ipc
2. become bloodsucker
3. hurt your self
4. no healing at all

### Round ID

48779

### Test Merges

#19968 #14802

### BYOND Username

Lassih

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Moltijoe** [comment]
https://github.com/yogstation13/Yogstation/pull/20510
