### ISSUE TITLE
 Syndicate Engineers sent by the Syndicate do not have the access to the syndicate station they were sent to repair and man

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20086]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: The fridge does not have access, there is no microwave to heat the donk pockets and they also arent given access to the ORM (which they are given a board of) the sole solution is robbing the ID off the private security corpse

 Submitted by: dinossaurodoacre (560477442611871746)

**Comment by KingSuperBOB** [comment]
And the ID only works for the ORM but not the fridge

**Comment by Aquizit** [comment]
This is working as intended. You can copy the access from the ID found into your agent ID and the idea is to rebuild a broken station which covers the microwave.
