### ISSUE TITLE
Remove the mimekitty

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#2009]
Something something we aren't tg and don't need to follow their policies

I don't like player references in the game and this is almost as insignificant and dumb as the trophy room that also had something for mimekitty I think

Coincidentally also bring back the honkbot to the map because that is literally yog's best feature
Seriously it's been in the code for like ever since the rebase, add it to the map pls

**Comment by Time-Green** [comment]
Honkbot was the greatest thing in ss13 history, and mimekitty is way to snowflakey

**Comment by Super3222** [comment]
This is incredibly petty. Mimekitty is just a honkbot for the mime. If you really want to get rid of the reference, rename it to something else like mimecat or realize how stupid it is to randomly stress over the name of a cat that we've had for the past year. Honestly.

On the other side, I re-added the honkbot a long while ago, but it may have been reverted around Christmas time or something.

**Comment by ShadowDeath6** [comment]
it's still a player reference and it has snowflake code for a specific character ingame which is even worse

there must have been a map bug with the honkbot because I don't recall it ever existing where it should since the rebase

**Comment by Jc1469** [comment]
dw red dragon will _very much remove wow its gone_ the mimekitty eventually

**Comment by ShadowDeath6** [comment]
>>>>>>>imblyig red dragon will EVER be merged

**Comment by Time-Green** [comment]
Ive spawned a honkbot at centcom, but it dissapeared aswell

**Comment by Super3222** [comment]
Just rename it.

**Comment by ShadowDeath6** [comment]
It's a mime cat, its entire existence is due to a character that dressed up as a cat mime
Renaming does not fix the reference issue

**Comment by Super3222** [comment]
I've never interacted with mimekitty before so I don't really care about the reference. I just like the aspect where the mime has a pet that represents them; just like the clownbot represents the clown. The reference is also barely noticable in the eyes of new players which weren't on yogstation pre-rebase. Nobody knows about it, and the ones who do don't care.

If you take a look at it the icon it's runtime with a mime mask on. Nothing to get winded up about. It's as loosely of a reference as naming a syringe in the brig "Steelpoint".

**Comment by Jc1469** [comment]
I will always know the reference. Me and Memekitty have a deep history.   Of disposal units at roundstart.

**Comment by ShadowDeath6** [comment]
the pr where mimekitty was added also
https://github.com/yogstation13/yogstation-old/pull/101#issuecomment-173314067
