### ISSUE TITLE
Why are harvesters op?

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#2014]
You should be able to put a gas mask on and be able to fend them off with a oxygen tank for at least awhile. They should do next to no damage because they can re-spawn endlessly. But at the moment they can bust a rwindow down in five hits instantly stun you with magic missile and then crit you from full health in 4 hits. It is just fucked. Also why can they bust down rwalls?

**Comment by Time-Green** [comment]
It's end-game, same with ascendants. If you want to defeat them, you should've stopped narnar from being summoned.

**Comment by ShadowDeath6** [comment]
Intended, harvesters have the best traits of all the constructs considering they're ascendant tier

**Comment by Super3222** [comment]
It's basically what Shadow and Time said. I like to look at yog harvesters as a mixture between juggernauts strength and artificer's corruption.

**Comment by Mrcreepssss** [comment]
yeah... they're purposefully OP
