### ISSUE TITLE
 icemoon tavernkeep doesn't have access to their own locker

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20159]
## Test Merges: 
Not Supplied / None
## Reproduction:
it says it's linked to you, but you're unable to open it or bind your ID card to it

 Submitted by: sufferingintensifies (758865103759474732)

**Comment by AMyriad** [comment]
I remember experiencing this issue myself a while back, but this was fixed in an innkeeper rework that I know happened, but can't find the PR for X_X
![image](https://github.com/yogstation13/Yogstation/assets/143908044/a6191a9c-27ba-4e10-9ec6-a90ea2d0f101)
so, close this if ye see this

**Comment by AMyriad** [comment]
aye aye, me
