### ISSUE TITLE
 Xenobiology console addiction

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20224]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: The exit button for the xenobio console is missing, forcing you to reconnect each time you use it, resetting buttons doesnt work and persisted through out the entire round

 Submitted by: englishscotsman (740223180806946946)

**Comment by tattax** [comment]
couldn't reproduce, you probably dragged your button here 
![image](https://github.com/yogstation13/Yogstation/assets/71668564/b4311efb-23e9-4d39-a84d-0d67227925e2)
![image](https://github.com/yogstation13/Yogstation/assets/71668564/982eeb84-62c8-48cf-bba6-8274360d0ff2)
