### ISSUE TITLE
AI Board rename

### ISSUE THREAD

**Issue by YogsMcree** [yogstation13/yogstation#2023]
Change "Oxygen is toxic to humans" to "Oxygen not included". This ambiguity should be added because 1) The name is 50x cooler and 2) The AI should technically be denying access to upload because of the existence of a dangerous board such as this, cant believe ive never seen this excuse used before. But yeah this name is better.

**Comment by drderp3635** [comment]
Ai is already supposed to let people in its core because any law change is potentially harmful

**Comment by drderp3635** [comment]
*not supposed to

**Comment by Super3222** [comment]
YogsMcree, that's an incredibly easy task to accomplish. Why not just set up git and do it yourself.

**Comment by ShadowDeath6** [comment]
Robocop is more harmful to humans than no o2 and people are still trying to upload it

**Comment by Mrcreepssss** [comment]
im pretty much against, one reason is becouse oxygen not included is the [name of a game.](https://www.kleientertainment.com/games/oxygen-not-included)
