### ISSUE TITLE
 Dynamic can still give antagonist to jobs that cannot hold that antagonist role

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20245]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: Brig phys got antagonist despite it being on the protected jobs list for the traitor gamemode. https://i.imgur.com/4kXoXdu.png
https://i.imgur.com/W0RzwjW.png

 Submitted by: maxim6263 (181876893178527744)

**Comment by maxion12345** [comment]
![](https://i.imgur.com/4kXoXdu.png)

![](https://i.imgur.com/W0RzwjW.png)

**Comment by ynot01** [comment]
Dynamic no longer exists
