### ISSUE TITLE
Airlock windows POPPING UP

### ISSUE THREAD

**Issue by McDonald072** [yogstation13/yogstation#2028]
1. Click an airlock as AI and disable main and/or backup power
2. Close the window
3. Scream in pain as it pops up constantly until the power countdown finishes

**Comment by doerakpoes** [comment]
Oh yhea that I believe the same can happen to you if you just hack the door as a humanoid

**Comment by ShadowDeath6** [comment]
I think it runs an adjacency check for humans so it doesn't spam you

**Comment by Mrcreepssss** [comment]
fuck yes please! this is also an issue if you just went to check why a certain door doesn't close/open.

**Comment by 00aquir** [comment]
Reference https://github.com/yogstation13/yogstation/issues/1648
