### ISSUE TITLE
 Blood boil rune kills cult structures

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20288]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: The blood boil rune which does burn damage to non-cultists seemingly destroys the cult's own bloodstone at Evac during the round.

 Submitted by: cowbot (97736956326207488)

**Comment by SomeguyManperson** [comment]
The bloodstones reached the anchor stage, which resulted in an undefended bloodstone becoming the anchor, the cult not moving to defend that one, and the security team obliterating it, which destroys all the other bloodstones
