### ISSUE TITLE
 medibeam arm implant doesn't heal non-humans

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20299]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: if you attempt to heal a non-human (any starting race) with it, they will not heal

 Submitted by: cowbot (97736956326207488)

**Comment by Oblisk234** [comment]
Can't replicate, was able to heal an ethereal with the medibeam implant.

**Comment by Oblisk234** [comment]
Can't replicate on second test, was able to heal an IPC with the medibeam implant.
