### ISSUE TITLE
Cogscarab overpowered

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#2031]
They are tiny and with go with full speed, you cannot even flash them but they can shoot back with guns.. yeah, no.

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/1877

**Comment by AdamElTablawy** [comment]
aquir

They are stunnable with normal stun weapons...

**Comment by 00aquir** [comment]
I'll examine it when they manage to go into my projectile next time.

**Comment by AdamElTablawy** [comment]
They also are dense, so projectiles will hit normally. Stunbatons will work just as well as flashes, and cogscarabs cannot use guns

**Comment by 00aquir** [comment]
well one just shot my ass with tesla

**Comment by AdamElTablawy** [comment]
that was either at the end of the round using ncrzntr, or the LITERAL TESLA that got released

**Comment by ShadowDeath6** [comment]
they can currently use guns still actually

**Comment by AdamElTablawy** [comment]
don't they have noguns?

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/blob/master/code/modules/mob/living/simple_animal/friendly/drone/_drone.dm#L294
