### ISSUE TITLE
 mushroom hallucinogen causes crashes

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20369]
## Test Merges: 
Not Supplied / None
## Reproduction:

Mushroom hallucinogen continuously causes crashes requiring a reconnect; tripping effects also linger after it's been fully metabolised.

 Submitted by: absence (98528128070070272)

**Comment by tattax** [comment]
should be fixed https://github.com/yogstation13/Yogstation/pull/20409
