### ISSUE TITLE
Nar'sie mirror shield doesn't stun

### ISSUE THREAD

**Issue by Laus4Deus** [yogstation13/Yogstation#20370]
### Severity

Inconvenience

### Short Description

People can pic up cult item. It shouldn't be this way for it can lead to confusion as to who is cult

### Reproduction

Pick up shield, no stun no nothing

### Round ID

66666

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by Oblisk234** [comment]
Per #20425 being balance council denied, not an issue.
