### ISSUE TITLE
Sometimes powers won't express if paired up with other powers

### ISSUE THREAD

**Issue by TristanSaucy** [yogstation13/yogstation#2039]
In this game chameleon was 1 and hulk was 2. By itself hulk and chameleon would expressed but when together only chameleon would express.

I've had this happen before with hulk, some rounds do it, I'm not sure what triggers it or whether its intentional but if it is its pretty shitty and dumb.

**Comment by Cruix** [comment]
I could have told you this in game if you had not suicide and disconnected.

The SEs you were using with both chameleon and hulk did not have a high enough gene value for hulk. After you left I was able to raise the hulk gene to a value at least as high as the number in the SEs you were using to get hulk, and I was able to make a human into a hulk with chameleon after several tries.

**Comment by ShadowDeath6** [comment]
also if you didn't know not all powers manifest 100% of the time

**Comment by TristanSaucy** [comment]
How high of a gene value does it have to be for hulk?

**Comment by ShadowDeath6** [comment]
E90 or higher I believe

**Comment by TristanSaucy** [comment]
Do you know where I can find all the info for this that is actually true in the repository ( whatever you call it)

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/blob/master/code/datums/mutations.dm
