### ISSUE TITLE
Atmos techs can't scan content of BZ and N2O canisters

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#204]
Scanners show nothing.

**Comment by Super3222** [comment]
I went ahead and tested this earlier... it works.

**Comment by 00aquir** [comment]
Hold the Atmos PDA or the scanner in your hand. Scan the BZ canister. See nothing, just the pressure.

**Comment by Super3222** [comment]
I'll look into this some more @00quir, you may have stumbled upon something.

**Comment by Groxic** [comment]
Does it not work still?

**Comment by 00aquir** [comment]
The atmos scanner can ONLY scan BZ and other gases if it's in the air, but missing the description when scanning some canisters:

air canister: oxygen 21, nitrogen 79%
n2 canister: nitrogen 100%
o2 canister: oxygen 100%
plasma canister: plasma 100%
n2o canister: nothing! (just pressure)
BZ canister: nothing! (just pressure)

You basically cannot see which of those not scannable gases is in the canister! It should show the gases in the canister in the same way as you see the in the air, like:

Pressure: 292.8 kPa
Nitrogen: 43.44 %
Oxygen: 11.35 %
CO2: 0 %
Plasma: 0 %
BZ: 13.4 %
Nitrous Oxide: 31.8 %
Temperature: 30 °C

**Comment by 00aquir** [comment]
Also, the atmos scanner shows BZ and Nitrous Oxide with red letters regardless how much of those or others like plasma is in the air...
