### ISSUE TITLE
donut's cargo is slightly wack

### ISSUE THREAD

**Issue by Yarinoi** [yogstation13/Yogstation#20414]
### Severity

Inconvenience

### Short Description

shuttle conveyor belts are on the wrong side + arent linked, shuttle doors arent linked to the buttons either

### Reproduction

1. be cargo job
2. interact with the cargo shuttle
3. notice the issues

### Round ID

forgor

### BYOND Username

Yarinoi

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

boxtards when i tell them that the issues with other maps can be fixed if people report them, and that can only happen if people play those maps:

**Comment by neeshacark** [comment]
I'm not entirely sure what this PR is referring to, the levers work for the belts and the buttons open the blast doors?

am i missing something or misunderstanding what your issue is? @Yarinoi

**Comment by neeshacark** [comment]
fixed on the latest commit, in other news i hate conveyor belt dir
