### ISSUE TITLE
Hivemind abilities largely broken

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#20424]
### Severity

Round Breaking

### Short Description

Chaos induction does nothing, hive vision does nothing  Telekinetic hand, Network Invasion, and Induce panic require robes

### Reproduction

1. be admin
2. force hivemind
3. they suck because they cant do much

### Round ID

49375

### BYOND Username

Cark

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

@tattax i'm pretty sure your pr caused this

**Comment by tattax** [comment]
yeah bros it's broken and i'm pretty sure i left a big comment  in the code talking about it. i didn't compromise on working on any disabled gamemodes because it makes no sense to do so

**Comment by neeshacark** [comment]
hrrrrr my funny bus gamemode,.....

**Comment by Oblisk234** [comment]
Hiveminds have been removed per #22635.
