### ISSUE TITLE
 Broken UI

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20430]
## Test Merges: 
Not Supplied / None
## Reproduction:
Partway through the round, I became unable to interact with my on-screen UI. After disconnecting and reconnecting, the backpack slot, and any fold-out slots past ~5 remained broken. Changing to another mob via admin assistance, as well as multiple disconnects/reconnects failed to fix the problem.
This has happened before to me.

 Submitted by: loiosh42 (886316591342555156)

**Comment by tattax** [comment]
probably sticky keys, i'll close soonish since this is, i'm 99% sure, client sided
