### ISSUE TITLE
Cloning issues

### ISSUE THREAD

**Issue by Slinky5890** [yogstation13/yogstation#2045]
A few times recently, ghosts have not been able to go back into their body after being cloned- this has also happened to me once. Unfortunately I can't really think of anything that tied these problems together.

The cloned body will be catatonic while the ghost needs admin intervention to get into their body.

**Comment by doerakpoes** [comment]
Also if the admin helps it apears to not count you as alive as a traitor

**Comment by Slinky5890** [comment]
Actually, some maybe helpful info for my situation atleast is that I was prescanned before I died

**Comment by Time-Green** [comment]
Prescanning adds an implant to your body, you die, it triggers. If it gets qdelled, it also triggers but for some reason it doesn't recognize your ckey. I've tried to fix this before but failed, i'll try again some time

**Comment by Slinky5890** [comment]
Turns out doesnt have to be prescanned earlier, a traitor couldn't get back in their body from a normal cloning.
