### ISSUE TITLE
donut cargo blast doors now suffer from the exact opposite problem they did last time

### ISSUE THREAD

**Issue by Yarinoi** [yogstation13/Yogstation#20469]
### Severity

Inconvenience

### Short Description

the blast doors in cargo are now unlinked, minus the shuttle ones

### Reproduction

1. be cargo staff
2. attempt to open blast doors
3. only the shuttle's blast doors open

### Round ID

49465

### Test Merges

#19968, #20140, #14802

### BYOND Username

Yarinoi

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

![image](https://github.com/yogstation13/Yogstation/assets/122653864/a19cb91b-87d5-43c5-b336-b59876208f8b)
at least the conveyors are fixed, progress will be made

**Comment by neeshacark** [comment]
ffs i fixed this it must've got undone by something

fixed again on latest commit
