### ISSUE TITLE
REPLACE labor shuttle office chair

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#2050]
- When shuttle starts and stops, the chair MOVES and whacks both the prisoner and security.
- A borg was opening the door when shuttle was leaving, and we SLOWLY ROLLED OUT TO SPACE WHILE BUCKLED IN. Terrible.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
the second issue is absolutely hilarious

**Comment by Amelia0010** [comment]
both issues are absolutely hilarious
