### ISSUE TITLE
 clerks spawn in the cargo sec checkpoint for some reason

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20522]
## Test Merges: 
Not Supplied / None
## Reproduction:
dont think i have to explain further
lol, lmao even
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1158561584881336431/image.png?ex=651cb20e&is=651b608e&hm=b1d58c5c9ce7679680391efe7bf3648705cd4bbaa0180bd9640c3d43af42b581&)
 Submitted by: yarinoi (718841144351522967)

**Comment by tattax** [comment]
fixed
