### ISSUE TITLE
 Warden/Security do not have access to open Upper Fridge in Asteroid Station Perma 

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20562]
## Test Merges: 
Not Supplied / None
## Reproduction:
Warden discovered they couldn't open the upper fridge in the station's perma area without breaking in.

 Submitted by: azaelus (1002024385185587371)

**Comment by MajManatee** [comment]
All fridges would be chef only, mappers probably didnt think about that.
