### ISSUE TITLE
Double bars

### ISSUE THREAD

**Issue by Therandomhoboo** [yogstation13/Yogstation#20587]
### Severity

Inconvenience

### Short Description

Bar layout keeps overlapping

### Reproduction

1. Be bartender/not bartender
2. go to bar
3. bar is fucked

### Round ID

49669 and any prev

### BYOND Username

therandomhoboman

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

Something has happened to cause bar to overlap in layouts when spawned on box.

**Comment by ToasterBiome** [comment]
Fixed now, it was an issue with wound loading on punpun.
