### ISSUE TITLE
 Mining Satchel sometimes bugs out, and will not pick up ore.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20598]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Mining Satchel will not pick up ores sometimes underfoot, unless you bring it from your right hand to your pocket sometimes.   Bug is inconsistent.

 Submitted by: tawaporah (241348083907166219)

**Comment by MajManatee** [comment]
Not enough information. Could be intended
