### ISSUE TITLE
Door Remotes are Breaking

### ISSUE THREAD

**Issue by Skyguy345** [yogstation13/Yogstation#20659]
### Severity

Inconvenience

### Short Description

Door remotes stopped working halfway through the round.

### Reproduction

1. Joined the round as captain.
2. Command door remote worked as normal.
3. Halfway through the round, the command door remote did not work on the Vault door (it normally does, and should).
4. The command and security door remotes did not work on their respective doors for the rest of the round.

### Round ID

49774

### Test Merges

#20501 #20547 #20569

### BYOND Username

Skyguy345

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by ShoziOffical** [comment]
did you check the ntnet relay machine? If its gone or inactive then you cant use the door remote and will have to rebuild it

**Comment by ShoziOffical** [comment]
as i saw in the replay the nt relay was destroyed in tcomms by a plasma fire, so yeah that explained why it broke

**Comment by ShoziOffical** [comment]
so this isnt a bug
