### ISSUE TITLE
pAI light stays where activated rather than following the pAI

### ISSUE THREAD

**Issue by tired-wired** [yogstation13/Yogstation#20666]
### Severity

Inconvenience

### Short Description

When activating the integrated light in a holoform, it stays behind where activated until deactivated and re-activated.  Has some similarity to the ghost orbits that are broken.

### Reproduction

1. Get downloaded as a pAI
2. Toggle holoform (mouse was used)
3. activate light
4. Move

### Round ID

49783

### Test Merges

#20501, #20547, #20569

### BYOND Username

faustbyte07

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by JohnFulpWillard** [comment]
Fixed by https://github.com/yogstation13/Yogstation/pull/20569/commits/ded39f87e0e3f0372886ed0bb0a91cbc084f19d3
