### ISSUE TITLE
gangrel werewolf form doesnt exist

### ISSUE THREAD

**Issue by ManofSan** [yogstation13/Yogstation#20671]
### Severity

Round Breaking

### Short Description

getting 3 frenzies as a gangrel doesnt transform you into a werewolf

### Reproduction

1. be a gangrel bloodsucker
2. enter frenzy 3 times
3. no werewolf form
4. feel immense disappointment

### Round ID

Round #49788

### BYOND Username

Man of San

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

im never trusting the wiki again :(

**Comment by MajManatee** [comment]
I blame that big antag PR. Bloodsuckers been busted since.

**Comment by Moltijoe** [comment]
they've never been able to transform into a werewolf
