### ISSUE TITLE
Bath salts cannot currently be made

### ISSUE THREAD

**Issue by MacHac** [yogstation13/yogstation#2067]
Bath salts as a chemical have been around for a while, and I always got the impression from the seven ingredients that they weren't something you were supposed to make, IE they were designed to be too much trouble.  It seems that whoever first added them all that time ago didn't bother to actually mix some, or they would have noticed that enzyme and nutriment in the same bottle produces Moonshine, rendering the recipe unmixable.

Proposal:  Replace Enzyme in the recipe with Atropine, which is similarly inconvenient to procure but won't react with anything else.  This also lowers the barrier to making it from 'sedating the chef and robbing him/her blind' to 'using the microwave for a minute and having lots of patience for mixing things', since you're no longer robbing the chef of their livelihood to go make exotic drugs.

**Comment by ShadowDeath6** [comment]
why was moonshine even added in the first place

**Comment by MacHac** [comment]
Because without its own illegal drugs chef is just a downgraded chemist with a microwave

**Comment by ArgyleSweatshop** [comment]
close this
