### ISSUE TITLE
 Sleepers Cure Toxins button INFLICTS toxins instead.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20681]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Used an upgraded sleeper to try and heal toxins on patients, and it would inflict toxin damage instead.

 Submitted by: tawaporah (241348083907166219)

**Comment by ktlwjec0** [comment]
#20682 this can be closed

**Comment by ShoziOffical** [comment]
> #20682 this can be closed

when molti didnt even link issue to his pr
