### ISSUE TITLE
Mastercrafted space suit's anti magic prevents the magic antag from doing magic

### ISSUE THREAD

**Issue by Joel-682** [yogstation13/Yogstation#20697]
### Severity

Inconvenience

### Short Description

Wizard's anti magic suit prevents them from casting spells-

### Reproduction

1. Spawn as Wizard
2. Equip the mastercrafted armor set (Spaceproof, non shield one)
3. Try to cast rod form
4. Cry because rod form is useless without spaceproof suit

### Round ID

Round #49819

### Test Merges

#20501 #20547

### BYOND Username

Joel The Lost One

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

The problem seem to be due to the antimagic properties of the space suit. The magic spacesuit is still considered a robe.

**Comment by cowbot92** [comment]
this is being resolved with https://github.com/yogstation13/Yogstation/pull/20701
