### ISSUE TITLE
 Bluespace crate teleports you back into station.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20690]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Me and another crewmember were inside a bluespace crate when we bot suddenly got teleported back into the station randomly. The shuttle was already traveling towards CC.

 Submitted by: sunsetwaves (263000681261039616)

**Comment by MajManatee** [comment]
Crate was likely destroyed, and as such this is an intended feature.
