### ISSUE TITLE
 Monster hunter objectives are broken

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20711]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description:
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1165722875643306164/image.png?ex=6547e307&is=65356e07&hm=235a8f5bd69b65429e7aee33d2c605b259734ed1d3215b512197e1eda450e503&)
![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1165722876012408922/image.png?ex=6547e307&is=65356e07&hm=97b15efaf28890797a6b94569df4b36a75bbe3e22b6f8c586d9e1402509150d0&)
 Submitted by: yarinoi (718841144351522967)

**Comment by MajManatee** [comment]
I see no issue. Nothing objectives can happen for anyone.
