### ISSUE TITLE
emag consumes charge but cannot open safes

### ISSUE THREAD

**Issue by LassiH** [yogstation13/Yogstation#20723]
### Severity

Inconvenience

### Short Description

emag consumes charge but dosent open safe

### Reproduction

1 get emag
2 use emag on safe
3 consume all charges fail to open safe

### Round ID

49863

### Test Merges

#20501 #20547

### BYOND Username

LassiH

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by MajManatee** [comment]
you cant emag a safe, its got tumblers you have to crack it manually. While using up charges is annoying, its a non issue.
