### ISSUE TITLE
GHOST ROLES

### ISSUE THREAD

**Issue by EthanMalakay** [yogstation13/yogstation#2072]
[Note]: Show ghost roles avaliable, because many times people wants to play a certain role, one is me, as golem or ash Walker, and i cant because, if i suicide to get it, it didnt spawn this round, or i skipped it thinking it wont spawn this round. :v

**Comment by 00aquir** [comment]
you shouldn't suicide. don't take a role just for that, and ghost roles should be for players who cannot play otherwise because they were permanently killed, really.

**Comment by Super3222** [comment]
It's not happening Ethan. If you suicide, ghost, or somehow die for a ghost role then that's the risk you take. If you want to be a ghost role from the start of it just observe.

**Comment by EthanMalakay** [comment]
but from observe the risk is there too :l

**Comment by 00aquir** [comment]
so you need them as a normal role... but ghost roles were specifically made for dead players who die, that's why you cannot choose them from the list
