### ISSUE TITLE
Ghost of Poly is affected by gravity

### ISSUE THREAD

**Issue by Addust** [yogstation13/Yogstation#20766]
### Severity

Inconvenience

### Short Description

When playing Ghost of Poly, gravity affects them

### Reproduction

1. be ghost of poly
2. gravity dies (or go to space)
3. immobilised
4. FUCK
5. pray for admemes

### Round ID

49907

### Test Merges

just the icemeta disabler

### BYOND Username

Addust

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

why are ghosts affected by gravity

**Comment by MajManatee** [comment]
You aren't really a ghost, you're a simple mob.
