### ISSUE TITLE
Rat King... without his coin powers?

### ISSUE THREAD

**Issue by MommaDragon** [yogstation13/Yogstation#20762]
### Severity

Inconvenience

### Short Description

Rat King has lost one of his only special powers: Create coins and cheese out of thin air.

### Reproduction

1. Become rat king
2. where's the button

### Round ID

49898

### Test Merges

20501, 20547

### BYOND Username

TheMommaDragon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

That's about it... she mostly did whatever to fill out everything. It's probably caused by your Big Antag Update thingy, as a Mentor said.

**Comment by tattax** [comment]
intended
