### ISSUE TITLE
blood splattering only works on delimb/decap, doesnt fly

### ISSUE THREAD

**Issue by ManofSan** [yogstation13/Yogstation#20781]
### Severity

Low

### Short Description

Blood splattering only occurs when delimbing someone, and doesnt fly past 1 tile

### Reproduction

1. Have sharp, robust weapon
2. Use it to delimb humanoid
3. Blood splatter happens on one tile only
4. Use sharp weapon to make a wound on humanoid
5. No blood splatter

### Round ID

Round #50000

### Test Merges

#20501 #20771 #20761

### BYOND Username

Man of San

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

that one blood splattering issue i made a while ago but more informative

**Comment by neeshacark** [comment]
@Moltijoe
