### ISSUE TITLE
 fucked up the mood description

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20811]
## Test Merges: 
Not Supplied / None
## Reproduction:
both the colour span and use of person are fucked up for the holy mood event
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1169317755984560289/image.png?ex=6554f705&is=65428205&hm=53b034d9a1a61e1d572247976c8b03af8e9789ecb9cd1e7bfc488a011d43f397&)
 Submitted by: snoobper (1079798074068709386)

**Comment by redmoogle** [comment]
What?
