### ISSUE TITLE
 fucked up the mood descrption 2

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20812]
## Test Merges: 
Not Supplied / None
## Reproduction:
span goofed up again and the hair one straight up doesnt have one
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1169318659295035512/image.png?ex=6554f7dd&is=654282dd&hm=3293edd7dbd43d4d4476180c9982fac4d9586a4ee80cfb4098dd27bdc5703aa1&)
 Submitted by: snoobper (1079798074068709386)

**Comment by MajManatee** [comment]
duplicate
