### ISSUE TITLE
New antag objective goon code not working?

### ISSUE THREAD

**Issue by Ninawindia** [yogstation13/Yogstation#20826]
### Severity

Inconvenience

### Short Description

Went through all of the stuff to get goon code, got got instead! (nothing)

### Reproduction

Go into the game
do the objective
get text that says "You take out the hard drive" at the end of the list of things needing to be done
get nothing
????
Don't profit!

https://gyazo.com/daebe2af827aab9279f8eda22c337354 I took a snippit of what it said.. but I didn't catch the whole thing. :( just the snippet

### Round ID

50075

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

Tried using open hand and such to try and "Remove" something that might or might not have been there. as I said, it said I took it out but nothing was in my hand or around the area

**Comment by JohnFulpWillard** [comment]
The objective was fiddled around with and is currently named Project Bee instead, and  I also can't replicate this bug and even fucked around with ninja stuff. I looked into the round and saw no helpful logs related to it so I'm gonna mark this as closed and you can open a new one if it happens again.
