### ISSUE TITLE
 nanotrasen saves money on healthcare by making anaesthetic thermite temperature

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20852]
## Test Merges: 
Not Supplied / None
## Reproduction:
BURN THE LAND, BOIL THE SEAS, EVEN ANAESTHETIC I'LL BURN WITH GLEE
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1171879728152588308/image.png?ex=655e490b&is=654bd40b&hm=490d5e10aa9f6dbcd78f34f832778392d6717231868ebe310f115c8e41c34bf5&)
 Submitted by: snoobper (1079798074068709386)

**Comment by ofscarletdreams** [comment]
forgot to mention this is most likely something to do with auxmos
