### ISSUE TITLE
 Burning Black Slime extrac turns you into an slime permanently

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20860]
## Test Merges: 
Not Supplied / None
## Reproduction:
I've used yesterday, and today as well, the burning black slime extract to turn myself into an slime, knowing that I can revert it back to human. The burning black extract doesn't show anymore the revert back to previous form skill, making you permanently an slime.

 Submitted by: sunsetwaves (263000681261039616)

**Comment by Oblisk234** [comment]
Can't reproduce, logs show that it did runtime though.

**Comment by Oblisk234** [comment]
Was fixed by #21143.
