### ISSUE TITLE
 Mime's invisible touch seems to permanently turn two handed objects invisible if you wield it after the touch is applied

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20862]
## Test Merges: 
Not Supplied / None
## Reproduction:
I used it on an explosive lance, wielded it two handed, and then it just didn't reappear before i could use the ability again. Also the invisible touch doesn't have an icon/sprite for the tgui selection menu after you use the mime book so it shows up as the big red "ERROR".

 Submitted by: masterdrake (598557108551811073)

**Comment by Maia-J** [comment]
Oh boy. Well uh I'll try to fix this

**Comment by Oblisk234** [comment]
Think this was fixed by #22015
