### ISSUE TITLE
Ingame characters can see ghosts examining things.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#2087]
@Super3222 @Super3222 @Super3222 @Super3222 @Super3222 
GET
ON
DISCORD

**Comment by Jc1469** [comment]
I am all I am all I am

**Comment by GrayRachnid** [comment]
http://i.imgur.com/2mzAfYQ.png

**Comment by ShadowDeath6** [comment]
bad pr

**Comment by GrayRachnid** [comment]
🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 SMASH THAT🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨 🔨

**Comment by Kmc2000** [comment]
Tested


Confirmed

**Comment by Super3222** [comment]
Uh... April Fools? I think. It's being fixed atm.
