### ISSUE TITLE
nearcrit is missing a linebreak

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#2089]
They looks haunting as they crawl on the ground hanging on for dear life.*---------*

it should be:
They looks haunting as they crawl on the ground hanging on for dear life.
*---------*

**Comment by Super3222** [comment]
Hmmm :thinking:

**Comment by Frostben** [comment]
Looks should be look

**Comment by Lightning38088** [comment]
wot.

**Comment by Super3222** [comment]
It's fixed.
