### ISSUE TITLE
 Light is BROKEN pt2

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20927]
## Test Merges: 
Not Supplied / None
## Reproduction:
I enter med maint as Venus, again the game cant process the fact my light is on (for me and for everyone else)  I am stunlocked. In both of these situations I need an admin to change my race because the issue is so crippling.

 Submitted by: Tbanner (391392319116410881)

**Comment by MajManatee** [comment]
duplicate
