### ISSUE TITLE
 Mind transfer machine issue

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20937]
## Test Merges: 
Not Supplied / None
## Reproduction:
I built a mind transfer machine on the shuttle, I, Draco, got in one side & Miles Gronko in the other. Turned it on. Just as it finished, for some reason it decided to bug out and threw us into space creature bodies
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1176191046913372250/image.png?ex=656df846&is=655b8346&hm=a1ff9bffc4aa242b912800ece709c4d7e86e90f3b091b0072934e1457153aedf&)
 Submitted by: riquegameplays (494257568324255745)

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/pull/20816

40% chance to malfunction, not a bug.
