### ISSUE TITLE
 Custody

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20942]
## Test Merges: 
Not Supplied / None
## Reproduction:
Being in cuffs no longer counts as in custody, there was a pr that added it but for some reason it broke, I dont remember exact replay but it wouldnt matter since end of round report doesnt show

 Submitted by: Tbanner (391392319116410881)

**Comment by MajManatee** [comment]
was never based on being in cuffs, instead involved being on certain floor tiles.
