### ISSUE TITLE
Revenant malfunction (EMP) balance

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#2095]
Revenant's EMP completely discharges everything, you cannot even recharge the weapons while it can send the next EMP. Completely disrupts the round, because if it doesn't want to, it won't be killed. At least baton should have some charge after it..

**Comment by 00aquir** [comment]
and Revenant is one problem, other is it's easy for someone to just use EMP and then sec becomes weaponless.

**Comment by TristanSaucy** [comment]
I have never seen a revenant die.

**Comment by AdamElTablawy** [comment]
As usual, aquir has no idea what he's talking about.

The revenant's emp works like any other emp aside from not discharging smes or breaking gang dominators. All emp's in the STRONG radius will fully discharge energy weapons and damage their cells, and all emp's in the WEAK radius will half the charge of energy weapons.

**Comment by 00aquir** [comment]
Still a revenant can come as close as it wants and send EMPs with too low cooldown.

**Comment by AdamElTablawy** [comment]
The malfunction ability can send one EMP for about 25 essence every thirty seconds, and then the revenant is stuck in place for about ten.

Any other EMP ability can be used multiple times in the span of a single second.

Non-issue, especially as essence = the revenant's health and thus spamming the ability means that the revenant will end up very weak and die very quickly. The only time this isn't the case is when the revenant has many many corpses to feed on and has been around for a long time, and that's security's fault and the chaplain's fault for not holy watering. If there are that many corpses the shift is already fucked anyway so the revenant will have minimal impact.

Non issue.

**Comment by MacHac** [comment]
Holy water screws revs BAD, and chances are if it's powerful enough to use EMP more than once and not die quickly you've put off dealing with it too long.  Flood the morgue with an inch of holy water and have 2 guys with guns in medbay and there's nothing a rev can do but hope for the tesla being released.
