### ISSUE TITLE
You can't open/close someone elses internals

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#20966]
### Severity

Round Breaking

### Short Description

Title

### Reproduction

1. take a tank off a plasmaman on accident
2. they pass out 
3. put it on
4. you cant open it
5. they die

### Round ID

Round #50377

### Test Merges

#13479 #20875 #20501

### BYOND Username

Cark

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by ShoziOffical** [comment]
If you put it on pocket you can't turn it on, only belt slot works

**Comment by ShoziOffical** [comment]
Not a bug just not implemented feature

**Comment by Buckethead390** [comment]
This is a real bug, the internals button on the belt doesn't work.

**Comment by ShoziOffical** [comment]
> This is a real bug, the internals button on the belt doesn't work.

even worse
