### ISSUE TITLE
 cmo doesnt start with the right pda apps

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#20975]
## Test Merges: 
Not Supplied / None
## Reproduction:
they start with the cargo techie ones (i think) instead of the ones they're supposed to have

 Submitted by: yarinoi (718841144351522967)

**Comment by AMyriad** [comment]
confirmed - this is a bug in game
CMO's PDA starts with the NT IRN and cargo bounty board apps alongside the suit sensor monitor and card modification apps

**Comment by redmoogle** [comment]
![image](https://github.com/yogstation13/Yogstation/assets/20369082/0442bba1-aa8f-42b4-9a65-10ba7f6af5a0)


Intended (cmos is a subtype of this)

**Comment by AMyriad** [comment]
truth, I realized this a few days ago when testing but forgot to say it again here
these aren't cargo apps, just apps every crewmember has
