### ISSUE TITLE
SS13 SPYING ON CENTCOM EXPOSED!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#2098]
IT'S ALL A RUSE!

Full fake camera list:

Aft Starboard solar access = Centcom Quartermaser
Dormitory north = Centcom shuttle manipulator north
Locker room east = Centcom Prisioner! Transfer Centre
Prison sanitarium = Centcom Conference room
Solitary = Centcom... medbay area?
Toxins storage = Centcom shuttle manipulator west
Virology airlock = Centcom conference room hallway

**Comment by GrayRachnid** [comment]
@AdamElTablawy

**Comment by AdamElTablawy** [comment]
Why did you tag me? I can't tell what this idiot is saying. If you want your problem fixed put it in understandable language rather than a bunch of locations and equal signs. What the fuck is this supposed to mean? Locations are mislabeled on sec camera consoles? You can see into centcomm? Centcomm locations are showing up as quartermaster's office?

**Comment by Slinky5890** [comment]
They mean that the sec camera consoles show these CC areas instead of where they're supposed to be.

**Comment by 00aquir** [comment]
You could have put the pieces logically together. It amounts to a bug indeed.

**Comment by ShadowDeath6** [comment]
Why does centcomm have cameras again?
Bad pr fix the map

**Comment by AdamElTablawy** [comment]
@00aquir If you want me to give a fuck, make a non-meme issue. I don't want to waste time trying to figure out what you wrote if you're too lazy to put in the effort to make it decent.

**Comment by MacHac** [comment]
@AdamElTablawy 
What the nice man is trying to say is that the cameras in your new centcom have the same c_tag and network as some station cameras, which means that attempts to view those cameras from the station can show people the inside of centcom instead.

The simplest solution is to simply remove the cameras from Centcom.  If you're up for something other than the bare minimum, go through each camera in centcom and change its network to list("Centcom") and its c_tag variable to something descriptive.

**Comment by 00aquir** [comment]
Yeah it was such a long shot. Spying on Centcom..  cameras.. what the HELL could it mean?? I wrote that this camera list is fake. And yes I was so lazy that I checked every single cameras.

**Comment by Slinky5890** [comment]
pls replace the network with centcomm, I wanna do some rp event stuff there and having an AI is fun
