### ISSUE TITLE
Permanently replace interrogation observation with Brig Medical

### ISSUE THREAD

**Issue by TammyTabbit** [yogstation13/yogstation#2100]
Today I saw this and figured at first it was a permanent change already. Interrogation observation is used less than the clerks office as it is and a brig medical with a defib a bed and some medpacks would be nice.

**Comment by Dagdammit** [comment]
Including surgical drapes and table could allow for some interesting human rights violations, plus chances for wardens to get decapitated by circular saws they neglected to lock back up earlier in the shift.
