### ISSUE TITLE
 IPC Don't Die When Brain Taken Out Via Surgery

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21026]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: When taking out an IPC's brain via surgery (when they were online), they don't die and they can move/act as if their brain was never taken out. Their taken-out brain is considered catatonic when put into MMIs.

 Submitted by: rune_knight (257721577028714496)

**Comment by neeshacark** [comment]
them remaining standing and alive was intended, the rest wasnt happening earlier and is definitely not intended

**Comment by neeshacark** [comment]
this also causes issues with reviving gibbed IPCs - you can't anymore.
