### ISSUE TITLE
Phytosian lighting not working as intended

### ISSUE THREAD

**Issue by Buckethead390** [yogstation13/Yogstation#21034]
### Severity

Inconvenience

### Short Description

Lighting bugs for plant making it very difficult to exist and perform several jobs

### Reproduction

1. play as plant
2. walk into dark areas with a flashlight
OR
2. step into tiles with any changes with a flashlight/seclite/etc (e.g. and easiest to replicate is broken rocks in lavaland)

### Round ID

Round #50492

### Test Merges

#21008 #14802

### BYOND Username

Buckethead390

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

This has been a growing issue for the past year with all of the lighting changes, but its been especially bad in the last month or two. If you step into the dark with typical lighting that would have worked a year back (flashlight, seclite, lantern) you will start dying to darkness despite your character being well lit. This will also trigger on any tiles with changes such as lavaland rocks or placing floor tiles in maintenance.

I believe https://github.com/yogstation13/Yogstation/issues/18610 is about the same problem but isn't accurate

EDIT: It does seem pretty variable, at times a single penlight will work fine, and at others I need three different light sources in order to not die. I have no idea why.

**Comment by Oblisk234** [comment]
Can't replicate, not sure if this was fixed by #21221 or not.
