### ISSUE TITLE
Cyborg Mining satchel doesn't auto pick up ores

### ISSUE THREAD

**Issue by Beeper-Skeeper** [yogstation13/Yogstation#21038]
### Severity

Inconvenience

### Short Description

equipping the mining satchel as a borg then putting it away no longer lets you pick up ores when you pass over them, possibly related to the janiborg autoclean change.

### Reproduction

Be a borg, choose the mining module, equip the mining satchel, run over ore, it wont auto pick up.

### Round ID

Any, but possibly only the ones after the janiborg autoclean change.

### Test Merges

#14802

### BYOND Username

GentlePotatoe

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Runian** [comment]
Cannot reproduce on local (with no test merges).
- Be cyborg. 
- Pick mining module.
- Equip/select cyborg mining satchel as first module.
- De-equip/store first module.
- Spawn in diamond ore.
- Walk away and then walk onto diamond ore.
- Diamond ore is auto-picked up.
