### ISSUE TITLE
 Metabolic synthesis nanites  doesnt seem to work properly on humans.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21042]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Metabolic synthesis on nanites gives +0.5 nanite regen, this seems to work normally on its own or on robotic species like preternis, however on humans this doesnt seem to work? Same if they are augmented. Unsure about other species

 Submitted by: ultrabigrat (225615376828989440)

**Comment by Moltijoe** [comment]
the threshold for metabolic synthesis to work is pretty high, the only species likely to maintain nutrition that high consistently are ipc and preterni as they don't get fat from "over eating"
