### ISSUE TITLE
Wrath of Gaia (and probably Corruption too) can spawn infinite mobs. Or at least, way too many.

### ISSUE THREAD

**Issue by MommaDragon** [yogstation13/Yogstation#21040]
### Severity

Inconvenience

### Short Description

Jungeland miniboss (elite?) "Wrath of Gaia/Corruption" spawns WAY too many mobs...

### Reproduction

1. Break a Dryad spawner nest thingy
2. Wrath of Gaia spawns
3. get ganked by 3 spiders 4 yellow jackets maybe like 3 spiders and have NO ABILITY to fight back (if you're an ivyman)

### Round ID

Not necessary.

### Test Merges

14802

### BYOND Username

TheMommaDragon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

_*clears throat*_
IF SOMEONE FINDS A WAY TO BRING ONE UP TO THE STATION, IT CAN BECOME A SERIOUS ISSUE.

Note that this is from personal observation, though it is possible to stop it before it hits critical mass.

**Comment by Oblisk234** [comment]
Was fixed in #22669
