### ISSUE TITLE
 Runechat translates languages now

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21052]
## Test Merges: 
 #14802 and #20798
## Reproduction:
Description: See title. Extremely simple bug - most likely caused by the Runechat testmerge (#20798).

 Submitted by: Momma Dragon (1110997692492038154)

**Comment by JohnFulpWillard** [comment]
What runechat testmerge?

**Comment by neeshacark** [comment]
runechat testmerge?

**Comment by neeshacark** [comment]
PR that caused this was reverted, no longer an issue
