### ISSUE TITLE
Quirks reset themselves randomly for no reason

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#21074]
### Severity

Round Breaking

### Short Description

Set quirks, play for x time, quirks randomly reset and you have none

### Reproduction

1. ????

### Round ID

n/a

### BYOND Username

Cark

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by Oblisk234** [comment]
Could this be because of #21057?

**Comment by AMyriad** [comment]
this was fixed in #21541

**Comment by Oblisk234** [comment]
Apparently this wasn't closed. Was fixed in #21714
