### ISSUE TITLE
 you can understand mice

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21071]
## Test Merges: 
Not Supplied / None
## Reproduction:
why can i understand you, mouse?
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1182505317758677162/image.png?ex=6584f0e5&is=65727be5&hm=30b0d947a124105198ae279b34ae55cd4025ec9da8bd345fc73fe53cf6eb64f9&)
 Submitted by: yarinoi (718841144351522967)

**Comment by JohnFulpWillard** [comment]
i dont get it

**Comment by Yarinoi** [comment]
in chat: squeaks
overhead text: what the mouse is actually saying that i normally shouldnt be able to understand
this also applies to a whole load of other languages too it seems

**Comment by neeshacark** [comment]
Change that caused this was reverted, no longer an issue
