### ISSUE TITLE
 Lasombra bloodsucker cant use more than one fragment to ascend abilities

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21080]
## Test Merges: 
Not Supplied / None
## Reproduction:
Use fragment in the resting place altar, ascend ability as intended, try to do i again, you cant put it inside the altar, rest and unanchor it, still no luck.

 Submitted by: pibecantina (341102461504716800)

**Comment by Oblisk234** [comment]
Seems to be intended.
/obj/structure/bloodsucker/bloodaltar/restingplace/attackby(obj/item/H, mob/user, params)
	if(!IS_BLOODSUCKER(user) && !IS_VASSAL(user))
		return ..()
	if(!awoken)
		if(istype(H, /obj/item/bloodsucker/abyssal_essence))
			to_chat(usr, span_notice("As you touch [src] with the [H], you start sensing something different coming from [src]!"))
			qdel(H)
			awoken = TRUE
		else
			to_chat(user, span_cult("Seems like you need a direct link to the abyss to awaken [src]. Maybe searching a spacial influence would yield something."))
		return
	return ..()
