### ISSUE TITLE
 Extended shock touch has become extremely powerful

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21092]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Bit of an ided but since  electrical armor is now area based, and its a relatively easy gene mutation that can be gotten and infinitely printed, it can now pretty much  just force someone to move  pretty much completely uncontrollably for a minute straight, which tends to be a death sentence as people can shoot/beat you and you cant run, aim melee or dodge. While this was fine before as you could just wear insuls now unless youre clad in engineering gear or wearing a hardsuit which massively slows you down, its an infinitely printable ranged instaconfuse, that cant be dodged, goes through walls and  now cant be reasonably countered.

 Submitted by: ultrabigrat (225615376828989440)

**Comment by JohnFulpWillard** [comment]
yeah idk what we're supposed to do with this. people are free to make whatever change they want but this isn't like a bug or anything
