### ISSUE TITLE
a way to die quickly when critted.

### ISSUE THREAD

**Issue by Mrcreepssss** [yogstation13/yogstation#2110]
we've all had those moments when we got into crit and no-one was gonna do shit to help out and there you are, slowly dying... i wish for a way to end it quickly so you don't have to wait half an hour till you finally die but don't wanna ghost couse then you cant be rezzed.

**Comment by 00aquir** [comment]
you can ghost in crit and be defibbed/cloned afterwards.

**Comment by Jc1469** [comment]
:thinking:

**Comment by Frostben** [comment]
#themoreyouknow

**Comment by Mrcreepssss** [comment]
that i didn't know. i think this would still be a nice idea.

**Comment by 00aquir** [comment]
or with :w you can whisper something as you die

**Comment by RoboticVodka** [comment]
There's also a verb called succumb where you just die tooooooooooo.

**Comment by Mrcreepssss** [comment]
okay then, this is unnecessary, atleast i know these now
