### ISSUE TITLE
 When applying emitters to people in VV, they will always also add an additional smoke effect that is unclearable by removing the emitter.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21103]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: It applies an unclearable smoke effect that is not able to be removed by conventional means. ANY emitter added gets the smoke emitter added onto it. Round ID does not matter

 Submitted by: breadtoucher (183529340267528193)

**Comment by Oblisk234** [comment]
Can't replicate, emitter was creatable and removable, no smoke effect observed. (Also round ID does matter)

**Comment by Oblisk234** [comment]
Can't replicate on second test, emitter existed and removable. No smoke effect.
