### ISSUE TITLE
There is a missing disposals pipe in the new bar design

### ISSUE THREAD

**Issue by Yackitori** [yogstation13/Yogstation#21110]
### Severity

Inconvenience

### Short Description

For some reason there is no disposals pipe at the bar

### Reproduction

1. Round starts
2. There is a missing disposals pipe underneath the airlock
3. Stuff going to disposals ends up in the bar

### Round ID

50656

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

![Screenshot (6)](https://github.com/yogstation13/Yogstation/assets/17297388/593a589d-f85f-4af6-8fad-15b8176b9db4)

**Comment by neeshacark** [comment]
already fixed in #21108
