### ISSUE TITLE
Is malf AI supposed to happen with cult, gang, and slings?

### ISSUE THREAD

**Issue by Lightning38088** [yogstation13/yogstation#2114]
been seeing malf AI happen with these gamemodes and it usually fucks up the other type of antags and i don't remember seeing this before because i thought that malf AI was only avaliable in traitor type gang modes.

**Comment by ShadowDeath6** [comment]
Yes it is

**Comment by Jc1469** [comment]
i question why you use git for questions.  it's almost like the person who asked how to die quickly

**Comment by Mrcreepssss** [comment]
these kinds of questions are quickly answerable and don't take alot of time i don't really see the issue with this.
