### ISSUE TITLE
 Voting problem: Lag means multi-vote

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21146]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: See title. Round ID is not actually applicable. But yeah, if you are in the middle of a lag spike (such as round loading), and you click a voting option multiple times, you cause, say, a map vote multiple times. The effect is that the options for the vote are created several times, and if you were to vote, say, IceMeta, all instances of IceMeta would get 1 vote (but are all separate). They can also later tie and it'll pick between IceMeta and IceMeta, for example. Yeahhhhh...

 Submitted by: Momma Dragon (1110997692492038154)

**Comment by Oblisk234** [comment]
Not sure if this is possible anymore since #22661 changed the voting system entirely.

**Comment by Oblisk234** [comment]
Think this was fixed by #22661, if it reoccurs, make a new issue.
