### ISSUE TITLE
 Non-ability to swap body's when downed/killed as a slime person

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21169]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity : Inconvenience
Description: a Body creating slime-variant you "used to" have the ability to create body's and swap to them. I had tons of body's and yet when I crit I couldn't swap to any of them or even bring up the menu. (Ruined my blood brother round)

 Submitted by: wookyman47 (730272590890926140)

**Comment by Runian** [comment]
Change was by #10116 where you can only swap if you are in a "not_incapacitated_state".

**Comment by Oblisk234** [comment]
Going to say this is intended, per #4411 and #10116.
