### ISSUE TITLE
 Safes are so unsafe, you can open them like how a child plays with their toys.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21175]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: you can open a safe by spamming move left 1, then move right 1 when it reaches 1, repeat until open. Assistant proof my ass.

 Submitted by: englishscotsman (740223180806946946)

**Comment by Runian** [comment]
Can't recreate on station vault's safe.

**Comment by Oblisk234** [comment]
See https://en.wikipedia.org/wiki/Brute-force_attack
