### ISSUE TITLE
 Medical wrench is missing from medbay [BOX]

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21179]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: At least on boxstation, there's just a normal wrench instead of the medical variant, no clue if this affects other maps as well or not

 Submitted by: amyriad (170817240223055872)

**Comment by ToasterBiome** [comment]
![image](https://github.com/yogstation13/Yogstation/assets/5091394/9b4eac23-1bbf-4ee6-8354-25f87c7e4429)

Definitely here
