### ISSUE TITLE
 Decapitating monkeys doesnt show their head missing.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21181]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Decapitating a monkeys head with a gun doesn't show its sprite with its head missing
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1189736341102149693/Screenshot_527.png?ex=659f3f4f&is=658cca4f&hm=7c4ebb987a9cb992596acec912c15109c68e6a6e5c13ec9418e041006527be91&)
 Submitted by: englishscotsman (740223180806946946)

**Comment by tattax** [comment]
https://github.com/yogstation13/Yogstation/issues/17618
