### ISSUE TITLE
APC construction bugged

### ISSUE THREAD

**Issue by AMyriad** [yogstation13/Yogstation#21191]
### Severity

Inconvenience

### Short Description

Placing an APC frame on a wall skips every step, and automatically fabricates a power terminal, power cell, and APC circuit board.

### Reproduction

1. Place APC frame on wall
2. APC is already finished construction, but in a limbo state

- Power terminal is **always** facing south
- Cell and circuit board is already in
- Using a hand on the APC gives a "Nothing happens!" message
- To fix it in this bugged state, the power cell and electronics (not the board) need to be screwed out, then put back in

.mp4 example of the above in google drive format because I don't know what's better to use:
[APCbugged.mp4](https://drive.google.com/file/d/1FAWu4eoX637mvvgjfN8Qrp_SOvZJn_13/view?usp=sharing)

### Round ID

#50853

### Test Merges

#14802 #21008

### BYOND Username

AMyriad

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Been broken for a few weeks I believe, but I'm unsure what PR might've caused it.

**Comment by ShoziOffical** [comment]
my bad
