### ISSUE TITLE
Crew monitoring console is broken.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#212]
Probably has something to do with this.

No away missions found.
Loading ruins...
Loading ruins...
Loading ruins...
Loading ruins...
Initialized pAI subsystem within 0 seconds!
Initialized Server Tasks subsystem within 0 seconds!
Initialized Radio subsystem within 0 seconds!
Initialized NPC Pool subsystem within 0 seconds!
Initialized tgui subsystem within 0 seconds!
Initialized Fast Process subsystem within 0 seconds!
Initialized Objects subsystem within 0.7 seconds!
Initialized Machines subsystem within 0.1 seconds!
Initialized Diseases subsystem within 0 seconds!
Initialized Events subsystem within 0 seconds!
Initialized Jobs subsystem within 0 seconds!
Initialized Mobs subsystem within 0 seconds!
Initialized Shuttles subsystem within 0.3 seconds!
Initialized Sun subsystem within 0 seconds!
Initialized Lighting subsystem within 5.2 seconds!
Initialized Timer subsystem within 0 seconds!
Initialized Ticker subsystem within 0 seconds!
Initialized Air subsystem within 2.6 seconds!
Initialized Garbage subsystem within 0 seconds!
Initialized Vote subsystem within 0 seconds!
**_Minimap generation disabled... Skipping_**
Initialized Assets subsystem within 0 seconds!
Initialized Icon Smoothing subsystem within 0.4 seconds!
Initializations complete!

**Comment by X-TheDark** [comment]
So I was right...it WAS made specifically for crew monitoring console.

Needs a change in the https://github.com/yogstation13/yogstation/blob/master/config/config.txt#L247 for the server config file. I don't think anything should be changed in the repo.

**Comment by oisin100** [comment]
Ill do it.
