### ISSUE TITLE
Let fake moustaches connect to gas tanks

### ISSUE THREAD

**Issue by Dagdammit** [yogstation13/yogstation#2121]
Thus allowing you to breathe from tanks while wearing them, same as many other masks.

Reason: It'll be funny.

**Comment by Frostben** [comment]
How about a version of the fake mustache that has nose tubes that go into your nose, therefore acting like a gas mask? Then that way it would accomplish both things, looking funny and being a gas mask.

**Comment by Dagdammit** [comment]
Sounds legit.

**Comment by Super3222** [comment]
`/obj/item/clothing/mask/fakemoustache/gas
	flags = BLOCK_GAS_SMOKE_EFFECT | MASKINTERNALS
	flags_inv = HIDEEARS|HIDEEYES|HIDEFACE|HIDEFACIALHAIR
	flags_cover = MASKCOVERSEYES | MASKCOVERSMOUTH
	w_class = 2
	gas_transfer_coefficient = 0.01
	permeability_coefficient = 0.01
	burn_state = FIRE_PROOF`

**Comment by Mrcreepssss** [comment]
NOSEBREATHER!
