### ISSUE TITLE
Infrared sight unusable

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#21213]
### Severity

Inconvenience

### Short Description

Infrared weapon sight doesn't work.

### Reproduction

- Infrared weapon sight cannot be turned on

### Round ID

50956

### BYOND Username

Aquir

**Comment by 00aquir** [comment]
Round 51293 around 37:00: Infrared sights didn't work again.

**Comment by 00aquir** [comment]
unusable again at round 51572

**Comment by Oblisk234** [comment]
Can't replicate, IR sight is working.
![image](https://github.com/user-attachments/assets/377982fa-c79e-4b99-872c-64db34053f2c)

**Comment by Oblisk234** [comment]
Can't replicate on second test, IR sight is still working.
