### ISSUE TITLE
 only 2 syndie bounties

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21236]
## Test Merges: 
Not Supplied / None
## Reproduction:
see image
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1195100122489552936/image.png?ex=65b2c2b9&is=65a04db9&hm=2bcae43c7945cbf04199a2873299ee219515183c7ae04d950c27cc63991a5e42&)
 Submitted by: yarinoi (718841144351522967)

**Comment by AMyriad** [comment]
no longer an issue due to #21471
