### ISSUE TITLE
Limb bones break under extreme brute force.

### ISSUE THREAD

**Issue by Frostben** [yogstation13/yogstation#2124]
Quick note: I would post this on the forums but I haven't seen the new thread available yet so as of then I'm putting this here thnx for reading!

So you know how limbs get dismembered from extreme slashing/explosive damage? Well why not make it so that arm and leg bones break under extreme brute/explosive damage? It wouldn't be anywhere near as complicated as baystation with fractures and broken hands dear god. Instead it would just be an arm and leg bone that breaks. No fractures. 

 The negative effects of a broken arm would be being unable to attack with it and if you pick something up it would have a high chance of dropping out of your hand. For broken legs it would be a large movement penalty for one broken leg and very frequent collapsing for two broken legs.

How to treat: First you have to set the bone back in place. Then place a cast/tourniquet on the afflicted limb. To set a bone you have to be laying down and someone else has to have the help intent and target your afflicted limb. Afterwards apply either a cast (which will only be available in medbay) or a tourniquet (which can be improvised). Casts have the benefit of being universal between arm and leg application and also heal the bone much quicker. Tourniquets on the other hand come in two versions, an arm and a leg version, both of these take much longer to heal the broken bones. The arm version requires two cable coil, a metal rod, and some torn cloth for a sling, whereas the leg version just needs the cable coil and metal cloth.

While healing broken arms have a slight chance to drop things and attacking someone or taking damage with the afflicted arm can re-break it, requiring you to take off the cast/tourniquet, reset the bone, then reapply cast/tourniquet. For broken legs that are healing they apply a movement penalty that can be removed with either a cane or crutch which you activate in a hand with a non-broken arm. In the case that you have two broken legs they will apply an even larger movement penalty that you will need to remove with two canes/crutches or just hop in a wheelchair (if there is one? I don't remember) You can also make improvised crutches with wooden planks.

This would add a nice dynamic to fighting with simple brute weapons like toolboxes or stun batons!

If you made it this far thanks for reading! Tell me what you think because why the fuck wouldn't you? This is a feature request after all and requires feedback!oihfaOI:SFHo'IAHFaisghdvf0ga..... fuck im tired.

**Comment by AdamElTablawy** [comment]
Already discussed a med rework with xthedark. Uses broken bones too. No casts though, surgery fix instead.

**Comment by Frostben** [comment]
oh ok thats cool too.... should i just close this then?

**Comment by Super3222** [comment]
Please contact the Council about opening a suggestion forum on our website.
https://forums.yogstation.net/index.php?threads/bring-back-the-suggestion-subforum.13093/

**Comment by Mrcreepssss** [comment]
i do like the idea of using casts though RIP numbers of competent medbay.

**Comment by Super3222** [comment]
Medbay isn't competent because the role lacks depth that veteran / experienced players look for.
