### ISSUE TITLE
really quite round start music

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#2126]
I think it started back when the option to turn off the echo effect, but the round start songs play but are super quite. When asked other players also noted that they faced this same problem.

**Comment by 00aquir** [comment]
Quiet doesn't always seem to be quite ok.

**Comment by 4of92000** [comment]
You're right; the music is quite round.

I prefer pointier start music in my video games too.

**Comment by Super3222** [comment]
It must be a mistake on my part. I'll take a look at it.

**Comment by Frostben** [comment]
If you ask me its quite the way to go.

**Comment by Dagdammit** [comment]
Audio filters have been applying to the roundstart songs for me too.

Never thought to complain about it. Considering how incredibly stale the roundstart songs have become, it was nice to have a tiny bit of variety.

**Comment by Dagdammit** [comment]
Never mind, I've now also had it be super quiet- no other noticeable audio effects at the time, just really freaking quiet.

May somehow relate to where my ghost was at the end of the previous round?

**Comment by Dagdammit** [comment]
Actually no, it happens every roundstart too. Damn.

Haven't been able to get others to confirm the same thing's happening to them.

**Comment by HAMBO123** [comment]
Got it fixed. Its a windows audio mixer problem. BYOND sets itsself pretty low. I think whoever implemented the echoes messed it up.

**Comment by Dagdammit** [comment]
Awesome, thanks for fixing!

**Comment by Super3222** [comment]
What? It's a code problem @HAMBO123 @Dagdammit

**Comment by HAMBO123** [comment]
@Super3222 Im going to commit a fix I have been working on. Give me time because finals have been my main focus.

**Comment by Super3222** [comment]
@HAMBOI123 It's fixed in https://github.com/yogstation13/yogstation/issues/2166
