### ISSUE TITLE
Make it possible for admins/mods to access logs on forums or something

### ISSUE THREAD

**Issue by Lightning38088** [yogstation13/yogstation#2127]
Mats suggested adding a bot with logs to forums, it'd help since we could deal with complaints easier and faster if we could access logs while away from our home computer with our game on it

**Comment by Jc1469** [comment]
request denied. how about you stop being lazy :^)

**Comment by Lightning38088** [comment]
how is it being lazy if i can't even access my game? it's not like i take my big ass desk computer to school or what not. so how about stop being ignorant and assuming we 5 feet away from our home computer :^)

**Comment by Super3222** [comment]
Might want to talk to Oisin100 directly about this. @Lightning38088

**Comment by Super3222** [comment]
Please contact the Council about opening a suggestion forum on our website.
https://forums.yogstation.net/index.php?threads/bring-back-the-suggestion-subforum.13093/
