### ISSUE TITLE
Slabs produces components even in inventory of noncultists.

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2128]
Your slab clunks as it produces a new component.
I am not a cultist myself,i stole it from their base cause lol.
This is a bug,i suppose.

**Comment by Super3222** [comment]
I think this was meant to happen, actually. Being in possession of the slab doesn't shake off the fact that magical components are growing inside of it.

**Comment by Super3222** [comment]
Please contact the Council about opening a suggestion forum on our website.
https://forums.yogstation.net/index.php?threads/bring-back-the-suggestion-subforum.13093/
