### ISSUE TITLE
 AI CPU tech tree dosen't have correct prerequisites

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21290]
## Test Merges: 
 #21008 and #21266
## Reproduction:
The bluespace CPU research needs ADV cpu, instead of EXP cpu

 Submitted by: liljackrabbit25 (302595577793740801)

**Comment by Bibby0110** [comment]
Intentional. Exp is a shdsgrade

**Comment by Moltijoe** [comment]
@TheGamerdk maybe rearrange the nodes so they dont look like progressive upgrades then

**Comment by MajManatee** [comment]
that's what I said when I made a PR to fix it originally thinking it was a bug
