### ISSUE TITLE
 All Languages are English

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21295]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: See image
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1199023617355292813/image.png?ex=65c108c3&is=65ae93c3&hm=cae8f257f08651fa48c4a5e2e726ed80f33e6385cf694547fb0d796fc2685ae4&)
 Submitted by: Obelisk (263223057999462401)

**Comment by Oblisk234** [comment]
For reference, these were at the start of the positive quirks as well, the original languages are there.
![image](https://github.com/yogstation13/Yogstation/assets/61151679/a5cbd08b-eadc-4006-a6d2-204fa6e20ebf)

In total there was 15 of them (excluding the actual English one).

**Comment by Oblisk234** [comment]
Not exclusive to English apparently. For reference, round 51372.
![image](https://github.com/yogstation13/Yogstation/assets/61151679/42ab29e9-f210-401a-9d6b-9b604a1966cb)

**Comment by CrazyDrakkon** [comment]
Issue for a year #17763

**Comment by Oblisk234** [comment]
Self-closing as duplicate.
