### ISSUE TITLE
 armaments disappeared

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21339]
## Test Merges: 
 21221
## Reproduction:
hgurgurg fuyck you gog bot
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1201981396894089276/image.png?ex=65cbcb68&is=65b95668&hm=eb1710d4f7bb0c9373fedcbfa95d06dac946e82cc99515ab03292a10abd96b83&)
 Submitted by: snoobper (1079798074068709386)

**Comment by MajManatee** [comment]
Due to ongoing AI rework, mapping changes are being postponed. Gonna have to wait a bit. Use the one at arrivals.

**Comment by ToasterBiome** [comment]
Incomprehensible. Please resubmit
