### ISSUE TITLE
Warden console breaking 

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#21332]
### Severity

Inconvenience

### Short Description

Warden camera console provides no interaction.

### Reproduction

- after maybe a power outage, I select "secureye" on warden console
- "Interface NtosSecurEye was not found."
- at this point I couldn't go back, or do anything on the console.

### Round ID

Round 51283  around 33:00

### BYOND Username

Aquir

**Comment by 00aquir** [comment]
round 51436 - yeah when I select SecurEye it doesn't work (only normal camera consoles work) and if deleted, then "Software Download" displays "No Access" to the SecurEye for warden.

**Comment by Oblisk234** [comment]
At present this doesn't seem to be reproducible, although from what I looked at in the logs this did occur. Not sure if it's an intermittent issue or that it got fixed by #21370.

**Comment by Oblisk234** [comment]
Going to say that this was fixed by #21370, make a new issue if it reoccurs.
