### ISSUE TITLE
 Light tubes and bulbs don't update their sprite

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21337]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Using a light tube or bulb directly onto a broken light bulb doesnt change the sprite of the held bulb, but acts like a broken light and fixes the new bulb. also states that you attacked the bulb when it clearly fixes itself

 Submitted by: englishscotsman (740223180806946946)

**Comment by Oblisk234** [comment]
Can't replicate, was able to change light tube and sprite updated, tested with both combat mode on and off. No attacking observed.

**Comment by Oblisk234** [comment]
Can't replicate on second test, able to change light tube and bulb, sprite is changed and no attacking.
