### ISSUE TITLE
The two arrivals pods don't reach the centcomm z-level at the end of the round

### ISSUE THREAD

**Issue by SomeguyManperson** [yogstation13/Yogstation#2135]
While the security and engineering pods end up at the recovery ship once the round ends, the two pods in arrivals stay on the transit level. This means they don't count towards the "escape alive" objective, and anyone on them is counted as marooned.

**Comment by ThatLing** [comment]
What map?

**Comment by ThatLing** [comment]
ADMIN LOG: Shuttle the escape pod cannot dock at the recovery ship, error: someone_else_docked

@nichlas0010

**Comment by Amelia0010** [comment]
mane why me

**Comment by Amelia0010** [comment]
this is ninja's fault, probably

**Comment by ThatLing** [comment]
You made yogstation map

**Comment by Amelia0010** [comment]
eeeeeeeeeeeeeeeeeeeee

**Comment by ThatLing** [comment]
https://github.com/tgstation/tgstation/pull/39675

**Comment by Amelia0010** [comment]
told you it was ninja's fault and not mine >:(

**Comment by Amelia0010** [comment]
why would you assign me reeeeeee

**Comment by ThatLing** [comment]
#2189
