### ISSUE TITLE
Traitor's radio jammer doesn't block sec gas mask radio hailer

### ISSUE THREAD

**Issue by kooarbiter** [yogstation13/Yogstation#21350]
### Severity

Inconvenience

### Short Description

The security gas mask hailer can still work while all other radio signatures are blocked by the jammer, it seems like an oversight

### Reproduction

Be traitor

Buy a radio jammer, thinking haha i am gonna outsmart sec this round

Sneak up on a seccie, unload on him with weapon of choice, success! he also cannot call for help!

[requestin backup, code 601, current location]

Enter the hellworld of intersectional oversight

I will never beat the IDED accusations

### Round ID

51319

### Test Merges

21008, 21266

### BYOND Username

kooarbiter

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Being able to actually jam radios when attacking secoffs would be nice, since communication and teamwork are more OP than any traitor item.

Might also need to take a look at other items that aren't radios that send radio messages IE singularity/reactor warnings.

**Comment by redmoogle** [comment]
Did you actually turn it on. It works fine in game

**Comment by kooarbiter** [comment]
> Did you actually turn it on. It works fine in game

I believe so

**Comment by AMyriad** [comment]
unable to replicate this, it probably isn't an actual issue

**Comment by Oblisk234** [comment]
Can't replicate, sechailer is jammed.
