### ISSUE TITLE
 Clockwork Catwalk sprite not appearing on Reebe

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21371]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Purely visual bug, as the tile still works as mapped: catwalk, clockie blocker, etc. Catwalk sounds are heard when walking on it so it's there. My guess is the Void turf is laying overtop of it? I'm not sure.

 Submitted by: aquizit (168642050915434496)

**Comment by Oblisk234** [comment]
Can't replicate, catwalk sprite is present. Do however see on replay that it wasn't there.

**Comment by Oblisk234** [comment]
Can't replicate on second test, likely fixed by a PR I can't find, make a new issue if this reoccurs.
