### ISSUE TITLE
The chapel appears to be experiencing dimensional anomalies

### ISSUE THREAD

**Issue by Addust** [yogstation13/Yogstation#21381]
### Severity

Inconvenience

### Short Description

read title, holy shit

### Reproduction

1. go to chapel
2. 
<img width="358" alt="image" src="https://github.com/yogstation13/Yogstation/assets/80979251/0dc79702-d7e1-489e-92c7-4025f8b428e6">

3. oh shit oh fuck
4. pry a tile
5. space.
6. baseturfs are fucked, maploading is fucked, holy shit

### Round ID

Any round on box past a certain round (ID unknown), reported on #51434

### BYOND Username

addust

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

probably just the maploader thing trying to stack shit

**Comment by ktlwjec0** [comment]
just to add on, this happened to clerk office too (don't remember the round)
