### ISSUE TITLE
Adjust Megafauna/Loot to be more fair and rewarding while retaining their challenge

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation#214]
At the moment Megafauna are insanely unbeatable to the extent you need to pull atleast 6-12 people away from the station and equip them with Riot Shotguns or ST SMGS to even stand a chance at beating them And this is just the bare minimum required to bring them down mind you.

Every single Megafauna has a maximum of 2500 health, does the same damage and has the same stat values, the only difference being their unique abilities. It's pretty clear they were made off a skeleton structure and not adjusted since I assume no-one has officially made an issue out of it. 

The Rewards for beating one are also very unsatisfying, the only one being somewhat good is the Colossus Black Box which allows you to store mementos for the next group who kill one to view or for you to store your own cool loot for the next group to take. 

**Why should we nerf them?**
As it stands they were originally designed as boss concepts for players to take on for really promising rewards and loot. They turned out to be extremely deadly and unstoppable mobs that require an absurd amount of firepower and manpower to bring down and while the experience is quite exhilarating the first few times, it just becomes an exhausting repeat of trying to avoid them since killing tendrils is more rewarding and easier to accomplish, especially on your own.

**So what's wrong with them individually?**

**Ash Drake**
Is way more tanky than it should be, It's health should be lowered considerably down to 1000-1500, this seems like a huge nerf to its health but you have to consider that 60% of the fight the Drake is COMPLETELY Invulnerable due to its flight ability which it uses A LOT during a fight. A lower health pool would reward players who manage to land successful hits on the drake while avoiding its Swoop Dive and the constant fireball and fireblast spam that it can also do while invulnerable. This would also make it feasible for Golems and Ash Walkers to take down a drake considering that the drops are pretty much useless to a miner with fully reinforced explorers suit. We witnessed a round where 15 golems took on a drake for 5-10 minutes, they manage to get its hp down to 350 but all died. It seems very stupid that not even 15 golems that are immune to fire and super resistant to its chomps are unable to take it down. Keeping in mind all 15 were armed and attacking the drake whenever it landed.

**BubbleGum**
Could do with a bit of a health reduction, probably down to 1500-2000, as it stands you cannot engage bubblegum in melee at all without the risk of being blood warped into instant crit. Bubblegums dash could use a bit of a cooldown, at the moment it can consistently dash every 0.5-1 second making it impossible to stop to reload your weapon or to heal up. If you are fighting him in a group he can easily dart from player to player easily slaughtering everyone. Being one of the harder bosses he could drop better loot along with the mark for death.

**Colossus**
As far as it goes the reward for killing a Colossus is pretty solid, the ability to store items into a box that carries on throughout rounds is quite rewarding especially when you consider that someone could toss just about any amount of stuff in there and you could pull out a plethora of weaponry the next time it gets opened. However that being said, aside from putting your bragging rights in there, it's quite useless as you wont be killing it unless its near the end of the round. This established lowering it to 2000 health seems reasonable given that it has motherfucking reflective energy shields that reduce the damage it takes. It could do with slower projectiles, given that it can snipe you from across the map, with that change this would make it a beatable adversary as dodging the projectiles actually becomes a possibility, at the moment the only way to beat a COlossus is by cheesing it since it cant destroy airlocks or computer frames.

**Loot!**
Now that I got that all out of the way lets talk about Loot, Loot being the huge centrepiece of why miners even bother to tackle anything on Lavaland. As it stands spending 3-7 minutes killing a tendril (provided another one hasn't spawned nearby which can double the process, this is apparently fixed in the latest update on tg though) can be quite time consuming considering the fact that the necropolis chest might fuck you over with an Inferno grenade which is useless on lavaland, or better yet, a SORD. Then there's also the additional thing being that miners work together a lot more now and with 5 miners slots it tends to turn into a grissly grudge struggle when you have 5 loot hungry animals fighting over 1 champions hardsuit or one deck of Tarot cards (Aka a Holoparasite).

So with all of those issues in mind tendrils should drop at the very least 1 crate with 2 items in it, 1 item just doesn't cut it half the time and it turns -10-20 minutes of finding a tendril and fighting its spawn, then killing the Tendril itself AND avoiding the chasm- into a huge disappointment. Miners want loot that will help them get more loot, only once did I manage to clear out all the tendrils with the other miners and the best we got out of 8 tendrils was the eye of god and a cult hardsuit, the rest was garbage like the soul stone or the SORD. 

As for the Megafauna they could really use more loot drops, which I'm referring to quantity when I say that, most the time you're still gonna need a group to take one down and the Drake and Bubblegum giving only 1 reward is a giant kick in the teeth for anyone who puts in the effort to take one down.

Finally I wanted to mention the new advanced Kinetic Accelerators, they really dont make a difference. I tested them out on all the monsters while dual wielding them and they only do a slew more damage than the normal KAs and reload 1 second faster. The DPS upgrade you get from bugging R&D to make them is so lackluster you may as well be better off spending your time hunting tendrils.

**Comment by Stealthkibbler** [comment]
I've noticed KAS wont be an issue if we update to the latest lavaland tweaks, since it allows normal miners to buy the modification kits instead of being only exclusive to free golems.

**Comment by KorPhaeron** [comment]
>6 to 12 people with special gear

That's the idea yeah. Science builds all these fancy mechs and guns every round but never has anything to use them on. They're meant to be round end goals for multiple people to cooperate against.

That being said, every boss but the colossus has been solod using the kinetic accelerator on /tg/. I'd give it a couple weeks to let players learn to fight them before making any big changes to them.

Colussolus shield is purely visual by the way, doesnt do anything.

The loot pools are probably a bit small and underwhelming yeah. Had to be toned down because a handful of players on our server started killing the dragons solo or in pairs every round to get dragonsblood. Also having to come up and code so many items is tiring.

**Comment by KorPhaeron** [comment]
I guess loot quantity would be a bigger problem with 5 miners vs 3 though
