### ISSUE TITLE
 The blast doors on the cargo shuttle are not opened by their button

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21444]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Caused by #21221

 Submitted by: masterdrake (598557108551811073)

**Comment by AMyriad** [comment]
confirmed - the buttons and blast doors use the ID "QMLoaddoors" and "QMLoaddoors2" respectively, the supply ship uses "supply_QMLoaddoors" and "supply_QMLoaddoors2" so they don't open each other

I haven't been able to find what sets it to this by searching the code, but I'll check again in an actual map editor soon
