### ISSUE TITLE
 One of the doors in service maint still has fucked up firelocks

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21446]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: See picture
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1208911783671103548/still_broken.PNG?ex=65e501d5&is=65d28cd5&hm=2ba8f0e513b69c89387392ab1a71ecd7b0532ee91569e22d306c610f71cccc06&)
 Submitted by: masterdrake (598557108551811073)

**Comment by AMyriad** [comment]
confirmed - this is a bug on Box
![image](https://github.com/yogstation13/Yogstation/assets/143908044/4f8a0416-01b6-4ad1-bf4b-91be4ead8b77)
