### ISSUE TITLE
 Quirks are initialized before your character is, which is what breaks them

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21451]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: The initialization order for quirks is earlier than it is supposed to be due to an undocumented change to code/__DEFINES/subsystems.dm in #17368. The round ID has nothing to do with this as its not an issue that can be seen in the replays but its required.

 Submitted by: masterdrake (598557108551811073)

**Comment by AMyriad** [comment]
I believe this was fixed in #21541

**Comment by Oblisk234** [comment]
Was fixed by #21714
