### ISSUE TITLE
Legionnaire pit teleport rune doesn't work. 

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/Yogstation#21463]
### Severity

Inconvenience

### Short Description

The Teleport rune that is supposed to teleport you into the legionnaire pit doesn't lead anywhere and doesn't do anything.

### Reproduction

1. Find the legionnaire pit
2. try to go inside using the rune
3. nothing

### Round ID

51556

### BYOND Username

dr.derp3635

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by AMyriad** [comment]
probably just a mapping issue within the ruin, I'll check this in a bit

**Comment by AMyriad** [comment]
can't replicate this, the rune seems to be working just fine
