### ISSUE TITLE
 Game sometimes crashes during Rad Storm event + visual glitch

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21480]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Game crashes to desktop when a rad storm even is about to happen as well as when its about to end. Not sure how to replicate it but someone else also has this problem. Rad storm effect also shows even when event is finished but when you walk into the room with the effect it dissapears

 Submitted by: mah_ko (277567415049519105)

**Comment by AMyriad** [comment]
this is the weather system issue, update your client to avoid crashing
