### ISSUE TITLE
 Holotool light doesnt follow the holotool

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21489]
## Test Merges: 
Not Supplied / None
## Reproduction:
(ANY ROUND FUCK THIS SHIT I CANT PUT ANY) When you activate holotool, it gives out it's light as normal, but when you move, the light doesn't follow the light source and it just stays in one place, changing the tool resets this but it doesn't fix it.

 Submitted by: pibecantina (341102461504716800)

**Comment by JohnFulpWillard** [comment]
This isn't a problem much because of https://github.com/yogstation13/Yogstation/pull/21768 but it caused runtime errors which is being fixed by the PR linked above this, but this issue is done for already.
