### ISSUE TITLE
 god fucking damn it shadowcoder #30000

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21487]
## Test Merges: 
Not Supplied / None
## Reproduction:
chasms ignore jaunters and the ones in the ashwalker village that are usually safe arent anymore
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1209870831979860059/image.png?ex=65e87f04&is=65d60a04&hm=b50e4911340e607c9ded3cdb2f6f1ce037fcc6334436e507bb700e676abefd7c&)
 Submitted by: snoobper (1079798074068709386)

**Comment by AMyriad** [comment]
might've been fixed in #21645
