### ISSUE TITLE
 the mech pipe dispenser doesnt work

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21491]
## Test Merges: 
Not Supplied / None
## Reproduction:
i pressed the rpd button in the top and none of the tgui buttons work
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1210027631035027487/image.png?ex=65e9110c&is=65d69c0c&hm=af8166261abc2e2e6e079bd31e5398c552db0ab26d36e293404bd455bffb2297&)
 Submitted by: snoobper (1079798074068709386)

**Comment by ofscarletdreams** [comment]
ignore this

**Comment by AMyriad** [comment]
this needs closing
