### ISSUE TITLE
 cant fix short circuit on mechs

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21494]
## Test Merges: 
Not Supplied / None
## Reproduction:
firefighter had a short circuit and inserting wire to fix it as usual wouldnt work

 Submitted by: snoobper (1079798074068709386)

**Comment by Oblisk234** [comment]
Can't replicate, was able to fix short circuit on a firefighter.

**Comment by Oblisk234** [comment]
Can't replicate on second test, short circuit fixable.
