### ISSUE TITLE
Randomly died as AI

### ISSUE THREAD

**Issue by bruhlookatthisdood** [yogstation13/Yogstation#21495]
### Severity

Inconvenience

### Short Description

While I was deconstructing a floor with an RCD in an Engineering Shell as AI, I suddenly died with no warning.

### Reproduction

(dunno if this is reproducable)
1. Be in AI shell
2. You are dead

### Round ID

Round #51597

### Test Merges

#21351 , #21455

### BYOND Username

liljackrabbit25

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

When I died:
![image](https://github.com/yogstation13/Yogstation/assets/89947174/24904aeb-4796-4e2f-b3c5-1173ea7bd1de)
Admin help:
![image](https://github.com/yogstation13/Yogstation/assets/89947174/7dfb533d-d9e8-49bc-9785-097bb38594e9)
![image](https://github.com/yogstation13/Yogstation/assets/89947174/d6588b6b-f459-43cc-98f7-6e493f50b429)

**Comment by Oblisk234** [comment]
So, seems that this was a sort of mapping issue, both cores were overheating (and also apparently gave no warning of this), although I think this was rectified in #21266. Same reason mostly why they couldn't force transform you into an AI either. Make a new one if it occurs again with #21266 merged.
