### ISSUE TITLE
miasma doesnt wanna generate

### ISSUE THREAD

**Issue by ManofSan** [yogstation13/Yogstation#21516]
### Severity

Inconvenience

### Short Description

Rotten gibs and corpses don't make any miasma.

### Reproduction

1. Amass pile of corpses and rotted gibs
2. Scan air for miasma
3. No miasma

### Round ID

Round #51625

### Test Merges

#21351 #21455

### BYOND Username

Man of San

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Oblisk234** [comment]
Did you follow the conditions required for miasma to generate? (Temperature is not near or above 373.15K and oxygen level is below 18 kPa)

**Comment by Oblisk234** [comment]
Replay is broken, likely that you weren't following the conditions required for miasma to generate.

**Comment by Oblisk234** [comment]
After testing turns out it is broken.

**Comment by ShoziOffical** [comment]
its very confusing but yeah its somewhat broken
