### ISSUE TITLE
 Cerulean Stabilised doesn't activate for different species.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21512]
## Test Merges: 
Not Supplied / None
## Reproduction:
Get a cerulean stabilised, change species through charged blacks, die because you got a terrible/dangerous race, don't go back to the body created by the stabilised cerulean.

 Submitted by: englishscotsman (740223180806946946)

**Comment by Oblisk234** [comment]
Was fixed by #22448
