### ISSUE TITLE
 oh god daniel hillton

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21518]
## Test Merges: 
Not Supplied / None
## Reproduction:
mechs can now do stuff with the clamp even afte rmoving away
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1211299219273678980/image.png?ex=65edb14e&is=65db3c4e&hm=9eae029e2d05bf7610c312bc6386e3a4bf974babee4e57c4ded52586e5fca1e7&)
 Submitted by: snoobper (1079798074068709386)

**Comment by Oblisk234** [comment]
This is being fixed in #22819, despite this issue being closed for an invalid name.
