### ISSUE TITLE
Some structure missing sprites

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#21533]
### Severity

Low

### Short Description

Cog grille + holodeck tables sprites missing

### Reproduction

👁️ 👁️ 

### Round ID

Round #51640

### Test Merges

#21351 #21455

### BYOND Username

crazy_drakkon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

![image](https://github.com/yogstation13/Yogstation/assets/18729830/270fe4da-4743-4e86-8b0f-fdf4658ccf98)

**Comment by CrazyDrakkon** [comment]
Slot machine (Jungle greed devil ruin)
![image](https://github.com/yogstation13/Yogstation/assets/18729830/dca74ee1-c4a4-411c-8353-4665b0a56880)

**Comment by AMyriad** [comment]
slot machines fixed by #21660 
not sure about the rest, would need confirming
