### ISSUE TITLE
Chaos Dunk is missing a return

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation#2153]
https://github.com/yogstation13/yogstation/blob/ce7102fe89a410492492d684556056c03df9f9b2/code/modules/holodeck/items.dm#L104

If a non-human mob with hands picks it up, and uses the action button somehow it'll result in a runtime error.

**Comment by ShadowDeath6** [comment]
WOAH

**Comment by Cruix** [comment]
Did you test this?

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I'll fix it in the second dunk pr
