### ISSUE TITLE
 The lighting in the farm house on jungleland is mostly pitch black

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21550]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: See image below
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1211934114320748566/image.png?ex=65f00099&is=65dd8b99&hm=fedc5cb796eae4df8e8b8aa1a9c9e62b696a79eb523d507778143375ba5be052&)
 Submitted by: masterdrake (598557108551811073)

**Comment by Oblisk234** [comment]
Image since bot deprecated it:
![image](https://github.com/user-attachments/assets/ec7de054-38f0-4e79-b80a-9081b3e81ee8)

**Comment by Oblisk234** [comment]
Likely fixed by #21467.
