### ISSUE TITLE
Admin AI Interact with Telecomms control console requires ID

### ISSUE THREAD

**Issue by nichlas0010** [yogstation13/yogstation#2156]
If I use admin AI interact to interface with the Tcomms console that uploads scripts, I still need an ID to use it, unlike the AI. This means that I can't remove the tcomms scripts as a mod

**Comment by Cruix** [comment]
Do you not have the verb to reset all tcomms scripts?

**Comment by nichlas0010** [comment]
I don't think so.
I'm 90% sure I don't

**Comment by nichlas0010** [comment]
Just checked, and mods do not have that verb
