### ISSUE TITLE
 closet interactions reversed

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21572]
## Test Merges: 
Not Supplied / None
## Reproduction:
you can now only click closets to put stuff on them when theyre closed, i think #21500 goofed it

 Submitted by: snoobper (1079798074068709386)

**Comment by redmoogle** [comment]
afaik it also works when they're open too; just that you can put items "on top" while they are closed

**Comment by Oblisk234** [comment]
Was fixed by #21529
