### ISSUE TITLE
 chasms ignore jaunters

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21577]
## Test Merges: 
Not Supplied / None
## Reproduction:
chasms ignore jaunters

 Submitted by: snoobper (1079798074068709386)

**Comment by AMyriad** [comment]
might've been fixed in #21645, also this is a duplicate of #21487

**Comment by ToasterBiome** [comment]
fixed in https://github.com/yogstation13/Yogstation/pull/21645
