### ISSUE TITLE
 Dolphins and carp seem to have a living silhouette stuck on them when they die in space

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21579]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Caused by #21221
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1213294804159692910/lighting_bug2.PNG?ex=65f4f3d7&is=65e27ed7&hm=e866c355dd69749bfeb06a5776d4a713ca86ebd57f035613954463ffe7693d79&)
 Submitted by: masterdrake (598557108551811073)

**Comment by AMyriad** [comment]
this was fixed in #21643, feel free to close
