### ISSUE TITLE
Wizard as ED bot cannot be flashbanged or tazed.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#2158]
While it can run around lasering and tazing people. That is some serious imbalance. It can just change back and heal itself...

**Comment by Slinky5890** [comment]
I don't see a problem with this. Always felt like wizard is supposed to be some unfair chaotic mode

**Comment by Cruix** [comment]
None of the shapechange animals can be flashbanged or stunned

**Comment by Time-Green** [comment]
An ED has 50 health, so the damage you DO do, is doubled

**Comment by 00aquir** [comment]
Okay, at least that makes the fight more fair.
