### ISSUE TITLE
 Using a pen on a book doesnt actually give you the option to change it

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21583]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Seems to be caused by #17311. Ive seen every other interaction above line 228 work properly so thats why I assume it breaks there. It also has a weird double comma that might also be the issue.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1213306352114602034/image.png?ex=65f4fe98&is=65e28998&hm=46b389ee5f41c15a63588b91b1af2e727f7849f2be69f8f1bedbb80d925210f9&)
 Submitted by: masterdrake (598557108551811073)

**Comment by redmoogle** [comment]
Fixed by #21418
