### ISSUE TITLE
Shuttle atmos is fucked AGAIN

### ISSUE THREAD

**Issue by Addust** [yogstation13/Yogstation#21603]
### Severity

Round Breaking

### Short Description

shuttles are venting themselves again

### Reproduction

1. become free miner
2. move boat
3. AHH AHH THE AIR VENTED ITSELF FUCK

### Round ID

51752, started before then

### BYOND Username

Addust

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

probably(?) disable atmos on turfs that are:
- about to be moved to hyperspace
- being moved to hyperspace
- just been moved to hyperspace
- same with leaving hyperspace

**Comment by CrazyDrakkon** [comment]
Yeah exit not pressurizing to interior, have to open manually.

**Comment by Addust** [comment]
> Yeah exit not pressurizing to interior, have to open manually.

it is not the airlocks

**Comment by Addust** [comment]
also just tested on local, issue is very much real shit

**Comment by AMyriad** [comment]
probably fixed in #21790

**Comment by cowbot92** [comment]
fixed
