### ISSUE TITLE
 Switching species with the ethereal wire-crawling lets you keep the martial art

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21622]
## Test Merges: 
Not Supplied / None
## Reproduction:
Turned into an ethereal mid-round, took the modified yellow slime extract, turned into a slimeperson, and was still able to use the power-wire crawl, despite not being able the correct species to wire-crawl.

 Submitted by: englishscotsman (740223180806946946)

**Comment by Moltijoe** [comment]
Its not a martial art, this is mostly intentional
