### ISSUE TITLE
 Custom Shuttles fucking EXPLODING

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21634]
## Test Merges: 
 #21025, #15579, #20581
## Reproduction:
You can reproduce this by deconstructing a wall on a custom shuttle, or trying to just fly a custom shuttle anywhere. This can be as severe as game breaking or round ending, because trying to fly it strands you in the middle of nowhere with not much to do unless you have a way to jetpack back to station
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1216894372730110014/bugreport.PNG?ex=66020c33&is=65ef9733&hm=8cc8298201c95628ee2c0c2c1c588c27c9a8f8a8772345d73eabf28ae521ae38&)
![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1216894373003006013/bugreport2.PNG?ex=66020c33&is=65ef9733&hm=352c8579b09b3c06a6dfc3f3b0a6c4625177ce6a4d4861e485654968b67ca725&)
 Submitted by: n3d6 (1070163433544228914)

**Comment by Oblisk234** [comment]
Was fixed by #21838
