### ISSUE TITLE
 Multi-Z prevents stepping onto other Z-levels from the station level (RIP space ruins)

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21642]
## Test Merges: 
 #21025, #15579, #20581, #21623
## Reproduction:
From my experience of trying to escape the station Z-level, I apparently became stuck at the border, with a vast darkness where the seamless transition to another Z-level would be. This was done in the top level of the currently testmerged Multi-Z gax PR.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1217242438373085327/image.png?ex=6603505c&is=65f0db5c&hm=1449ff55311c8080048b5ab4ffc9ce1440d347f5239c5c4ae165012a29fde5d3&)
 Submitted by: amyriad (170817240223055872)

**Comment by ToasterBiome** [comment]
Not a bug
