### ISSUE TITLE
Night vision still sucks?!?!?!?

### ISSUE THREAD

**Issue by ThatGuyPhil** [yogstation13/Yogstation#21657]
### Severity

Round Breaking

### Short Description

Darkness is just too dark for the strongest of eyes.

### Reproduction

1. take a screenshot of yourself in the darkness of maint without nv trait
2. do the same but with nv trait
3. go and look at them, see that shit is still dark!!
4. use some hardware or whatever that makes your computer screen super duper bright. 
5. Oh look, all the stuff I SHOULD BE SEEING!!!!!

### Round ID

all of them

### BYOND Username

fireclaw787

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

So, night vision... it kind of sucks.

why is darkness so dark even with 'night vision'? 
I see pitch black for either unless I use my system tuner to turn my gamma up a whole bunch, and doing that for any game kinda feels like cheating. It makes me think that this trait has been in the game far longer than whatever feature made any dark areas have a virtually opaque shroud.  

I'll also just show the images to help explain what I'm complaining about...

TW: my dusty screen (there is literally no other way i could show you the difference of what changing the LED brightness of my screen does)

Default brightness:
![NObrightness](https://github.com/yogstation13/Yogstation/assets/50330177/084c174d-7240-4c79-8453-1583f380de02)

Using my MSI dragon center system tuner to increase the brightness a shitton (I had to go and shrink this in ms paint because it was just a few bytes too large for github):
![image](https://github.com/yogstation13/Yogstation/assets/50330177/aaff0713-c5bf-4184-800b-0a0adca0b942)

**Comment by Moltijoe** [comment]
Clean your screen, god damn
Not an issue
