### ISSUE TITLE
Forced into Detective job

### ISSUE THREAD

**Issue by Ninawindia** [yogstation13/Yogstation#21652]
### Severity

Inconvenience

### Short Description

Randomly assigned Detective, even though all security occupations are turned off

### Reproduction

I honestly don't know how I'd re-create it! I just joined the round, and became detective, even though I have them off..

### Round ID

51836

### Test Merges

#21025 #20581 #21623

### BYOND Username

NinaWindia

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

Maybe Join as random job if current job you want is unavailable is the culprit? even though, I had no job on high priority so It shoulda just picked from a random Mid priority one.

**Comment by AMyriad** [comment]
probably fixed in #21653

**Comment by ToasterBiome** [comment]
related to https://github.com/yogstation13/Yogstation/pull/21653
