### ISSUE TITLE
 using semi-colon as a message prefix near an intercom routes the message through the intercom instead of your headset

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21651]
## Test Merges: 
Not Supplied / None
## Reproduction:
if  you change the channel of an intercom to something not on the common channel (ai private, or other channels for unlocked intercoms) using semi-colon near it will put the radio message into the intercom channel instead of your own radio's common channel. intercoms are supposed to be spoken into by using .i instead of ;.

 Submitted by: jarod1200 (250794357211398144)

**Comment by Oblisk234** [comment]
Was fixed by #21991
