### ISSUE TITLE
Unable to use robotics R&D console to research as robotocist.

### ISSUE THREAD

**Issue by Oblisk234** [yogstation13/Yogstation#21664]
### Severity

Inconvenience

### Short Description

Console said I did not have access to research anything

### Reproduction

1. Be roboticist
2. Try to research something on the robotics R&D console
3. Get told that you don't have access (???)

Afterwards was able to research with AA.

### Round ID

51858

### Test Merges

#21025, #20581, #21623

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by AMyriad** [comment]
this isn't a bug per se, but the main RnD console doesn't have robotics access, so roboticists can't use it
if someone wants to fix this, giving the windoor there robotics access would be nice too :)

**Comment by Oblisk234** [comment]
This was not at the main RnD console, this was at the robotics one. (I'm already aware of the no access on the other console, which is why it was odd it happened to the one in robotics itself)

**Comment by AMyriad** [comment]
well I'm unable to replicate this in game, couldn't find anything wrong with the console in the editor either
![image](https://github.com/yogstation13/Yogstation/assets/143908044/b7d5f5ef-bda9-4cdb-8454-d6585d9bbbcc)
