### ISSUE TITLE
 oh god oh fuck what happened to the trimming

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21670]
## Test Merges: 
Not Supplied / None
## Reproduction:
why are they colored all weird
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1218550455127511120/image.png?ex=6608128c&is=65f59d8c&hm=38088a9fce05149101bdd3cd5776b53bd0dcc897d99791c5a546b4bd7dd6cf06&)
 Submitted by: yarinoi (718841144351522967)

**Comment by AMyriad** [comment]
this is still an issue, why was it closed?

**Comment by tattax** [comment]
> this is still an issue, why was it closed?

![image](https://github.com/yogstation13/Yogstation/assets/71668564/9ef94f22-8a43-4f6b-ae6b-98765c652e51)

**Comment by AMyriad** [comment]
oh lmao
