### ISSUE TITLE
Unable to deconstruct reinforced tables

### ISSUE THREAD

**Issue by AMyriad** [yogstation13/Yogstation#21684]
### Severity

Inconvenience

### Short Description

Reinforced tables cannot be deconstructed, currently dunno what broke it

### Reproduction

1. Weld reinforced table
2. Use screwdriver/Wrench without being on help intent
3. You place the tool down instead of deconning it

### Round ID

NULL

### BYOND Username

AMyriad

### Was this done on a locally hosted or non-Yogstation hosted server?

Yes

**Comment by redmoogle** [comment]
Just noting this here: They can be deconstructed when not in help or harm mode (eg grab or disarm)

**Comment by AMyriad** [comment]
Localhosting is whack, not an issue apparently
