### ISSUE TITLE
 Mech hydraulic clamp is technically usable in hand

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21698]
## Test Merges: 
Not Supplied / None
## Reproduction:
Can sort of use it on doors, doesn't force open the doors but creates sounds and occasionally the progress bar. Able to use for other crowbar purposes as well.

 Submitted by: obelisk2106 (263223057999462401)

**Comment by AMyriad** [comment]
Confirmed - pretty much works like a fully functioning crowbar
