### ISSUE TITLE
Split /area/medical/sleeper into two as on the old map.

### ISSUE THREAD

**Issue by fizzle7** [yogstation13/yogstation#217]
~~/area/medical/sleeper  has infinite power because no apc.~~
The surgery apc now works for surgery and storage/cryo, it was separate before the rebase.

**Comment by GrayRachnid** [comment]
Are you talking about the area with the sleepers and the cryo? 

If so they do have an APC.

**Comment by fizzle7** [comment]
They used to be 2 apcs in the old map, now its only one, the one from surgery, so either leave it or put another one for the cryo, so most likely not a bug.

**Comment by GrayRachnid** [comment]
Why would we need to add another one for cryo? What's wrong with just one APC controlling the whole area?

**Comment by fizzle7** [comment]
Because it had 2 before, don't ask me i didnt put it there, maybe it's for easier access to cryo, no idea.
