### ISSUE TITLE
Cansiter sprite doesn't update when broken

### ISSUE THREAD

**Issue by Mantlecrawler** [yogstation13/Yogstation#21700]
### Severity

Inconvenience

### Short Description

Canisters, broken by force, dont update to the broken sprite. 

### Reproduction

![dreamseeker_ROrmd6icLe](https://github.com/yogstation13/Yogstation/assets/95545005/7cd6f4a2-8cbe-4e01-bfe6-18dcd7723ebb)

### Round ID

N/A

### Test Merges

#21025 #21623 #21623

### BYOND Username

Boxta

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by AMyriad** [comment]
yeah I don't think a broken canister sprite was put in when GAGS was merged? could be floating around somewhere idk
maybe @tattax knows more about it
![image](https://github.com/yogstation13/Yogstation/assets/143908044/97ef8382-2858-4360-9a4c-8e1935c2f6a7)
