### ISSUE TITLE
Broken ladders on Gax

### ISSUE THREAD

**Issue by Skyguy345** [yogstation13/Yogstation#21703]
### Severity

Inconvenience

### Short Description

On Gax station, the ladders would not let you climb down, only up.

### Reproduction

1) Play on Gax
2) Try to use a ladder to go to the lower Z level (the one located in maintenance between toxins and cargo)
3) Ladder says "There is nothing above you", doesn't allow you to switch to the lower Z level

### Round ID

51920

### Test Merges

#21025 #21623 #20581

### BYOND Username

Skyguy345

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

I noticed a few ladders that did this on the station, but didn't have time to test them all. Stairs were working fine.

**Comment by ToasterBiome** [comment]
you have to ctrl click the ladders to go down
