### ISSUE TITLE
 Radstorm causes mystery crashes.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21711]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Radstorm starts, byond closes. Reconnect, radstorm still active, crash again. No radstorm, no crashes. I suspect it is linked to the same crashes as the random crashes I get on icemeta whenever there is a snowstorm.

 Submitted by: loiosh42 (886316591342555156)

**Comment by AMyriad** [comment]
Related to the weather system issue
