### ISSUE TITLE
error in to toolbelt slot

### ISSUE THREAD

**Issue by wonderinghost** [yogstation13/Yogstation#21712]
### Severity

Inconvenience

### Short Description

this appeared when i joined

### Reproduction

join the round as engineer (anyone with the toolbelt) 
see that
![image](https://github.com/yogstation13/Yogstation/assets/88801435/29b80012-8d9b-4f01-ab94-2e82c20421bd)

### Round ID

51936

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by wonderinghost** [comment]
found out more about it. some weird reason the screwdriver sprite breaks the toolbelt sprite

**Comment by ShoziOffical** [comment]
@tattax 

https://github.com/yogstation13/Yogstation/assets/89688125/dc3c8d2e-057a-42ff-a521-b66ce031a7e8
