### ISSUE TITLE
 Badges invisible

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21710]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Badges no longer appear on your sprite when you attach them to a piece of outerwear, has been so for a while, may apply to other attachables too.
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1220495725239206019/image.png?ex=660f2638&is=65fcb138&hm=97ee80efacb362ab46729059e790b278b6cfdf023a0ed05bf037082059beacf1&)
![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1220495725528350910/image.png?ex=660f2638&is=65fcb138&hm=386431cabe6581818057be63c46809460c0939d6ecd88996a31ebcaaf740e2ac&)
 Submitted by: loiosh42 (886316591342555156)

**Comment by AMyriad** [comment]
this seems to be affecting all accessories
