### ISSUE TITLE
Cozy shuttle losing atmos on launch

### ISSUE THREAD

**Issue by Skyguy345** [yogstation13/Yogstation#21719]
### Severity

Inconvenience

### Short Description

Cozy shuttle (maybe others) losing atmos on launch

### Reproduction

1) Ordered the cozy shuttle at roundstart.
2) Tons of stuff happened, including the infinite gamma alert bug (already fixed)
3) Shuttle arrived, no issues.
4) On shuttle taking off, parts of it immediately became unbreathable.

### Round ID

Round #51941

### Test Merges

#21025 #21623 #20581

### BYOND Username

Skyguy345

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

I think I have seen some of the other shuttles doing this on some rounds yesterday, it might not just be a cozy shuttle issue.

**Comment by Skyguy345** [comment]
I looked at the demo viewer, and it might be an issue with the firelocks on the shuttle not activating correctly.

**Comment by Skyguy345** [comment]
This might need to be upped to game breaking priority, a lot of the shuttles are losing their atmos, and the crew is getting hurt. It's not firelock related, that is a separate bug that is compounding the issue.

**Comment by AMyriad** [comment]
probably fixed in #21790

**Comment by Oblisk234** [comment]
Was fixed by #21790
