### ISSUE TITLE
 the escape alive objective for traitors is gone

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21716]
## Test Merges: 
Not Supplied / None
## Reproduction:
whered it go
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1220722883328741486/image.png?ex=660ff9c7&is=65fd84c7&hm=aa32e531a1bf2355d313db29d93560a2015a398ff06679cb210ad80e8d9f459c&)
 Submitted by: snoobper (1079798074068709386)

**Comment by AMyriad** [comment]
#21659
not an issue
