### ISSUE TITLE
Infinite gamma alert

### ISSUE THREAD

**Issue by Skyguy345** [yogstation13/Yogstation#21717]
### Severity

Round Breaking

### Short Description

Gamma alert came up after all darkspawn were dead, did not turn off

### Reproduction

1) Darkspawn round
2) Kill darkspawn before delta alert
3) Gamma pops up after only known darkspawn is dead
4) There is no other darkspawn alive, just one traitor.

### Round ID

Round #51941

### Test Merges

#21025 #21623 #20581

### BYOND Username

Skyguy345

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Moltijoe** [comment]
fixed
