### ISSUE TITLE
Locker mechs cannot be made

### ISSUE THREAD

**Issue by Oblisk234** [yogstation13/Yogstation#21720]
### Severity

Inconvenience

### Short Description

Locker mech is uncraftable

### Reproduction

1. Gather all the tools and materials
2. Try crafting it
3. Be completely unable to do so

### Round ID

51945

### Test Merges

#21025, #20581, #21623

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Went through mhelp about this step by step. Didn't work through all the steps and things tried.

**Comment by AMyriad** [comment]
Unable to replicate, works fine
![image](https://github.com/yogstation13/Yogstation/assets/143908044/01f5f140-237f-45a3-92b8-3fa8557a5e0f)
Sure you did all the steps right?

**Comment by Oblisk234** [comment]
At the time it didn't, and ran through all the steps correctly. Tested it today and it appears to have worked, oddly enough.
