### ISSUE TITLE
 ipcs get debrained by chasms

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21727]
## Test Merges: 
Not Supplied / None
## Reproduction:
if you walk into a chasm as an ipc the damage makes your brain slip out which makes you completely unrevivable
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1221213482330882099/image.png?ex=6611c2af&is=65ff4daf&hm=9107d5de8f1791db9b7dbf2dcb1377be54fbcce1fe2f77037e5ffdf29efedabc&)
 Submitted by: snoobper (1079798074068709386)

**Comment by redmoogle** [comment]
Doesn't a chasm make you unrevivable?

**Comment by AMyriad** [comment]
> Doesn't a chasm make you unrevivable?

no ye can still be fished out if you fall in one
