### ISSUE TITLE
 Darkspawn kills my game.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21734]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Darkspawn ascends > byond dumps to desktop. Reconnect, dump to desktop after a minute or so. No darkspawn ascended when I rejoin, no crash. I suspect it is linked to the visuals, like the radstorm and icemeta crashes. It has happened on several rounds before.

 Submitted by: loiosh42 (886316591342555156)

**Comment by AMyriad** [comment]
Probably related to the weather system issue

**Comment by AMyriad** [comment]
apparently the fix is to update your client
