### ISSUE TITLE
 Became Vampire as ghostrole 

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21747]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Whilst playing as a syndicate security guard on IceMeta,  i got selected as a Vampire antagonist midround, item spawn for objective completion was normal.

 Submitted by: boatguy1 (802252729111543889)

**Comment by AMyriad** [comment]
yea we should probably restrict ghostroles from this kinda stuff
