### ISSUE TITLE
 blob spores cannot pathfind for the life of them

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21743]
## Test Merges: 
Not Supplied / None
## Reproduction:
blob spore ai is incredibly dumb and doesnt count going through the blob as a clear path when rallied leading to them getting stuck in gaps or in the blob itself

 Submitted by: snoobper (1079798074068709386)

**Comment by ToasterBiome** [comment]
Not a bug or glitch
