### ISSUE TITLE
 Wheely heel implants dont work + caused ethereal to have shrunken vision

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21751]
## Test Merges: 
Not Supplied / None
## Reproduction:
i could activate it twice for some reason which shifted me a little but it just seemed like i was buckled to something, also the whole shrunken vision which was fixed when i cryoed
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1222572319659266178/image.png?ex=6616b433&is=66043f33&hm=6989aa9b6dc651d6eb77a362353ca947df8239c7e44badefa1ae46951c93109d&)
 Submitted by: yarinoi (718841144351522967)

**Comment by JohnFulpWillard** [comment]
I can't replicate this unfortunately, reopen a new one with better reproduction steps if it happens again.
