### ISSUE TITLE
 you can pick up folded bluespace bodybags while inside them

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21759]
## Test Merges: 
Not Supplied / None
## Reproduction:
this inevitably leads to very glitchy (but interesting) behavior from the bags when you unfold the version of the bag you have in your hands, causing the bag to be inside of itself and creating two bags, kind of sort of.
can we keep this one? it's funny.

 Submitted by: yarinoi (718841144351522967)

**Comment by AMyriad** [comment]
How the hell do you pick it up while inside?

**Comment by Oblisk234** [comment]
Can't replicate unless actually given steps to reproduce.

**Comment by AMyriad** [comment]
@Yarinoi

**Comment by Oblisk234** [comment]
A week has passed, no response. Resubmit with reproduction instructions.
