### ISSUE TITLE
Can;t move

### ISSUE THREAD

**Issue by Arachnid-Ass-Pics** [yogstation13/Yogstation#21761]
### Severity

Round Breaking

### Short Description

I couldn't move for alot of the round.

### Reproduction

Pretty much I was an BB where about midround i couldn't move anymore, or use key shortcuts. Any attempt at that just put the corresponding key in my text bar. Attepts at clocking the screen so it removed the cursor from my text bar did nothing. I could drop something from clicking drop oin my ui on screen, but pressing q would just add it to the text bar
 My BB suffered from the same issue about 10 minutes before shuttle. I also couldn;t speak in ooc for some reason.

### Round ID

52017

### BYOND Username

SpiderSpinnerets

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by FireBrandMint** [comment]
_Oh, you were that guy on the bar of sin that couldn't move, but anyone could drag you, that was so funny._

But yeah, **that round was full of bugs** various crewmembers **got their bags invalidated and couldn't open or pick them.**

I had to empty the bag by draggin it to the ground and put the items in a new bag.

**Comment by AMyriad** [comment]
> Pretty much I was an BB where about midround i couldn't move anymore, or use key shortcuts. Any attempt at that just put the corresponding key in my text bar.

You mean this?
![image](https://github.com/yogstation13/Yogstation/assets/143908044/b9f093b2-cd59-4129-bade-5d79405e3364)

**Comment by AMyriad** [comment]
99% sure you just hit tab on accident, just hit tab to toggle the command bar
