### ISSUE TITLE
 icon smoothing subsystem fucked up gpses

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21776]
## Test Merges: 
Not Supplied / None
## Reproduction:
miner gpses are mine0 instead of the name of their owner and the pulsing tumor gps straight up isnt there

 Submitted by: snoobper (1079798074068709386)

**Comment by milk-is-cool** [comment]
this has been a known issue since the smoothing pr was merged
![image](https://github.com/yogstation13/Yogstation/assets/72528859/b6b6ab80-2da4-4d70-afe7-e184052c0134)
