### ISSUE TITLE
Botanists have no maint access

### ISSUE THREAD

**Issue by ThatLing** [yogstation13/Yogstation#2179]
They can get into maint from botany but they can't leave.

**Comment by Amelia0010** [comment]
can't they just leave the maint through botany again?

**Comment by ThatLing** [comment]
Not if machines come alive and attack you so you have to flee through maint but you can't leave maint anywhere but through botany but you can't because there's evil machines there.

**Comment by Amelia0010** [comment]
mang, if we give them maint access they'll get access to all of maint, not just the area they should have

**Comment by ThatLing** [comment]
YES THEY NEED ACCESS TO ALL OF MAINTENANCE

**Comment by Amelia0010** [comment]
this still shouldn't be a thing thoughh

**Comment by 00aquir** [comment]
by that logic remove access level: maint. because everyone should have it too?

**Comment by ThatLing** [comment]
thanks for cockblocking me

**Comment by Amelia0010** [comment]
you're welcome ❤️
