### ISSUE TITLE
Make AI override menu more user friendly

### ISSUE THREAD

**Issue by Slinky5890** [yogstation13/yogstation#2180]
With the menu as it is, I have found this traitor AI module almost completely useless. It takes ages for me to find the item I want to turn alive, and if there's multiple of the machine then it's pot luck if I get it right or not. I'd much rather you be able to select it on the malfunction menu then click the item(s) you wanna override.

**Comment by Time-Green** [comment]
Ehm, you can right click an object to override it
But yeah that list is crappy, realisticly, we should just keep it to right clicking

**Comment by GrayRachnid** [comment]
The only use of the dropdown menu is to blow things up that are not within your camera's range.

Hell, you can blow up the air alarms and APCs on the derelict.

**Comment by Slinky5890** [comment]
Welp i'm being a retard then. If it isn't mentioned then maybe it should mention you can rightclick. Otherwise this issue is useless and is just my ineptitude.
