### ISSUE TITLE
The Taur Golem Missing Sprites

### ISSUE THREAD

**Issue by TheNeMir** [yogstation13/Yogstation#21816]
### Severity

Inconvenience

### Short Description

Taur golem missing torso and head sprites

### Reproduction

1. i walked up to taur golem pillar 2. i clicked on it 3. some time passes and someone joined as taur golem but they were lacking torso and head sprites

### Round ID

52127

### Test Merges

 #21778 #21275

### BYOND Username

Blagomir

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

i got this glitch at end of round so nothing new

**Comment by AMyriad** [comment]
fixed in #21844
