### ISSUE TITLE
More missing floor sprites

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#21827]
### Severity

Low

### Short Description

Floor tiles ("Ameritard" in maint ruins and ".." in heretic Hell which apparently also covers Headache) sprites all black

### Reproduction

1. Have eyes

### Round ID

Round #52136

### Test Merges

#21778 #21275 #21351 #21825

### BYOND Username

crazy_drakkon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

![image](https://github.com/yogstation13/Yogstation/assets/18729830/e68699b3-5ad7-41a1-b52e-0da64c5f372a)

**Comment by AMyriad** [comment]
looking into this

**Comment by AMyriad** [comment]
first half of this issue seems to no longer be a problem
![image](https://github.com/yogstation13/Yogstation/assets/143908044/5c8199d6-35aa-4275-aca7-2b5e1d2bcb46)

as for the ".." those are ballpit floors, which have simply not gotten smoothing
still need to organize doing that

**Comment by CrazyDrakkon** [comment]
> first half of this issue seems to no longer be a problem ![image](https://private-user-images.githubusercontent.com/143908044/324247288-5c8199d6-35aa-4275-aca7-2b5e1d2bcb46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDAwNjYsIm5iZiI6MTcxNDM5OTc2NiwicGF0aCI6Ii8xNDM5MDgwNDQvMzI0MjQ3Mjg4LTVjODE5OWQ2LTM1YWEtNDI3NS1hY2E3LTJiNWUxZDJiY2I0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxNDA5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDM2NjNmMmYzMWNjN2ZiNWRkNDlkOTIxM2E1YmFmZTFmNmRjN2U3M2IwNDQwNDM4ZmEyN2ZlYTU5M2I2NjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wT9UVbb2_hl00VZFAZfxbIewu4xPbJGSS1As-2gH980)
> 
> as for the ".." those are ballpit floors, which have simply not gotten smoothing still need to organize doing that

Learned it was in Backrooms only

**Comment by Oblisk234** [comment]
All sprites mentioned seems to be fixed.
