### ISSUE TITLE
Vendors no longer have maintenance panels (sprite issue)

### ISSUE THREAD

**Issue by MommaDragon** [yogstation13/Yogstation#21841]
### Severity

Inconvenience

### Short Description

See title. Vending machines have been recently updated to have new sprites, lacking their maintenance panel pieces.

### Reproduction

1. Get a screwdriver
2. Screwdriver a vendor
3. No sprite change

### Round ID

Not applicable

### BYOND Username

TheMommaDragon

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

It's really hard to tell if a machine is opened or not, and someone could easily make all vendors impossible to access just by using a screwdriver. #21821 is probably the related issue, considering there's a strong lack of maint panel on each (every) sprite.

**Comment by AMyriad** [comment]
icon smoothing PR bug
