### ISSUE TITLE
Vox (and most likely others) die to oxygen in the air in VR. No equipment?

### ISSUE THREAD

**Issue by MommaDragon** [yogstation13/Yogstation#21843]
### Severity

Inconvenience

### Short Description

Vox do not spawn with their appropriate equipment in the funny VR room.

### Reproduction

1. Vox SigTech appears.
2. Go to enter VR
3. Model materializes
4. **Dying. No gear. Not at all.**

### Round ID

52162

### Test Merges

#21778 #21351 #21825 #21275

### BYOND Username

TheMommaDragon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

"**THE VR IS BULLSHIT!!**" - Yaha

(Note: Can't orbit VR models.)

**Comment by AMyriad** [comment]
@13spacemen

**Comment by 13spacemen** [comment]
after-equip-job code wasnt running in VR
![Screenshot 2024-04-15 191521](https://github.com/yogstation13/Yogstation/assets/46101244/c6f1ea65-b698-4b3d-9d9e-7e06e862c208)
