### ISSUE TITLE
Loose Goose Too Loose It Fall Off's Reality's Kaboose

### ISSUE THREAD

**Issue by Arachnid-Ass-Pics** [yogstation13/Yogstation#21864]
### Severity

Inconvenience

### Short Description

Bar sign deleted itself

### Reproduction

Be bartender
Remeber bar sign exists
Pick The Loose Goose for the bar sign
Bar sign disappears

### Round ID

52184

### Test Merges

21275

### BYOND Username

SpiderSpinnerets

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by cowbot92** [comment]
fixed with https://github.com/yogstation13/Yogstation/pull/21887
