### ISSUE TITLE
Adding new AI datacores to a network does not function

### ISSUE THREAD

**Issue by Oblisk234** [yogstation13/Yogstation#21886]
### Severity

Inconvenience

### Short Description

Make a new datacore and it doesn't connect properly nor work

### Reproduction

Construct a datacore and networking machine, wire them up with ethernet cables, link the networking machines together. Tested whether the core is properly functional by disconnecting the networking machine on my end (which normally gives you a prompt to transfer to another core or stay in yours), but it didn't. Also doesn't appear on like how the roundstart datacores do.

### Round ID

52244

### Test Merges

#21854, #21883

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Bibby0110** [comment]
did you provide a server with 1Thz and 1TB of RAM on the local network?

**Comment by Oblisk234** [comment]
No, I didn't. Didn't even know that I had to do that for the core to be functional.

**Comment by Bibby0110** [comment]
> No, I didn't. Didn't even know that I had to do that for the core to be functional.

I'll make a note to implement a highlight for this
