### ISSUE TITLE
Emergency access lights are invisible - until you open the door.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#21895]
### Severity

Inconvenience

### Short Description

- Doors don't show emergency access lights until you open them

### Reproduction

- Emergency access for maint turned on from bridge
- You couldn't see the emergency access setting, until you open and close the doors, individually.

### Round ID

52256

### BYOND Username

Aquir

**Comment by Oblisk234** [comment]
Can't replicate, doors are showing emergency access lights without needing to open them.

**Comment by Oblisk234** [comment]
Can't replicate on second test, replay doesn't show doors either so can't verify.
