### ISSUE TITLE
Custom objective menu made easier to use

### ISSUE THREAD

**Issue by Rayisken** [yogstation13/Yogstation#2192]
make a menu to use when creating custom steal objectives rather than the scroll list that currently pops up. ie a bar to just enter the object location manually and select x amount of items to be stolen if possible the current scroll box is tiny and slow, honestly, anything is better; I was thinking something close to the spawn object/mob panel.

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.
