### ISSUE TITLE
Ethereals can no longer discharge excess energy

### ISSUE THREAD

**Issue by Oblisk234** [yogstation13/Yogstation#21943]
### Severity

Inconvenience

### Short Description

Try discharging using an APC, doesn't work

### Reproduction

Be an ethereal, overcharge yourself, then try grabbing an APC to discharge.

### Round ID

52340

### Test Merges

#21883

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Probably combat mode testmerge

**Comment by AMyriad** [comment]
I've noticed runtimes concerning ethereal's discharge mechanic before, this oughta be looked into

**Comment by iamthesilly** [comment]
This action was moved to alt-click in #21883.
