### ISSUE TITLE
Radiation storm alarm can still be heard by deaf people

### ISSUE THREAD

**Issue by Oblisk234** [yogstation13/Yogstation#21945]
### Severity

Inconvenience

### Short Description

Alarm is still audible even with the deaf quirk

### Reproduction

Have the deaf quirk, wait for a rad storm, hear the rad storm alarm go off?

### Round ID

52341

### Test Merges

#21883

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Moltijoe** [comment]
Deaf doesnt mean you can hear literally nothing like in zomboid
