### ISSUE TITLE
 Traitor objective on donutstation not working

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21954]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: Inconvenience
Brief Description:  Spawned in as a traitor and got the objective "Destroy the original sleepers in Brig and Medbay Treatment Center" on DonutStation and had destroyed all of them but still hadn't completed the objective
Steps to Reproduce: Get the objective

 Submitted by: _rizzmaster69 (898557153898537000)

**Comment by AMyriad** [comment]
The brig sleepers were never deconstructed during that round, not an issue
![image](https://github.com/yogstation13/Yogstation/assets/143908044/a125ecd9-6744-46a9-86d9-6f4348375b72)
