### ISSUE TITLE
Energy Harvester Module stubbornly refuses to harvest energy

### ISSUE THREAD

**Issue by GirdoMALF** [yogstation13/Yogstation#21977]
### Severity

Inconvenience

### Short Description

Energy Harvester claims to be unpowered when screwed to cabling

### Reproduction

1. Go into maintenance while station has excess power in the grid, create a powered wire node off the main engineering line.
2. Screw Energy Harvester onto wire, turn on.
3. Leave Energy Harvester on, unscrew and screw back in without touching On/Off controls (on Mentor advisement bc this is what usually works.)
4. Energy Harvester will still show as Unpowered in both its in-person controls and on the CE computer console.

![ehm](https://github.com/yogstation13/Yogstation/assets/99637865/393d1fef-9742-4b0b-8d33-70ff9b907488)

### Round ID

52389

### BYOND Username

Girdo

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by Runian** [comment]
Energy Harvester must be directly connected to the power source's powernet.
- SM/Tesla/Thermoelectric --> SME --> Energy Harvester --> Does not work
- SM/Tesla/Thermoelectric --> Energy Harvester --> Works
![image](https://github.com/yogstation13/Yogstation/assets/30399783/16ccbf57-e61c-4a5e-8e3d-9c8de67ccb68)

**Comment by Oblisk234** [comment]
Energy harvester doesn't work after SMES, it seems.
