### ISSUE TITLE
AI datacore on donutstation has no wiring

### ISSUE THREAD

**Issue by Oblisk234** [yogstation13/Yogstation#21994]
### Severity

Round Breaking

### Short Description

Primary datacore has no ethernet cabling or networking machines

### Reproduction

AI primary datacore:
![image](https://github.com/yogstation13/Yogstation/assets/61151679/9ec65ab6-d404-497b-97d3-b3cd87137fb7)

Datacore on examine:
![image](https://github.com/yogstation13/Yogstation/assets/61151679/0ef9e0f5-24dc-465f-93b9-7ac23879f036)

### Round ID

52420

### Test Merges

#21883

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by AMyriad** [comment]
iirc @Aquizit wanted to fix this today or tomorrow
