### ISSUE TITLE
Mediborg Advanced Surgery Suite is not so advanced

### ISSUE THREAD

**Issue by GirdoMALF** [yogstation13/Yogstation#22028]
### Severity

Inconvenience

### Short Description

After upgrade, mediborg surgical tools are still the regular version

### Reproduction

1. Be a medical cyborg
2.  Have a surgical multi-tool
3. Receive the advanced surgerical multi-tool suite upgrade (should provide laser scalpel/pinchers/cautery tool)
4. Enjoy still having a regular circular saw and sterile metal tools.

### Round ID

52498

### BYOND Username

Girdo

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by Moltijoe** [comment]
It was changed to instead upgrade the speed
