### ISSUE TITLE
 Can't repair walls with welder

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22037]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Using M1 with a welder on damaged walls doesn't seem to repair them

 Submitted by: amyriad (170817240223055872)

**Comment by Oblisk234** [comment]
Can't replicate, was able to repair damaged walls of any type.

**Comment by Oblisk234** [comment]
Can't replicate on second test, was able to repair damaged walls of any type.
