### ISSUE TITLE
 CQC says it can be used with other martial arts, when it gets deleted when does so.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22049]
## Test Merges: 
Not Supplied / None
## Reproduction:
Reading the CQC book has the "I could probably combine this with some other martial arts!" remark while reading, yet using the ethereals martial art lightning flow before reading, deletes the ethereal martial art with CQC.

 Submitted by: englishscotsman (740223180806946946)

**Comment by Oblisk234** [comment]
It is not possible to have [more than one martial art at a time](https://github.com/yogstation13/Yogstation/blob/aa3cf475ba356061cc35e9dd8cb303375da3a0dd/code/game/objects/items/granters/martial_arts/_martial_arts.dm#L12). While there are exceptions to this (Combining krav maga with anything other than buster arm), you cannot naturally have two martial arts at once, and I doubt anyone would make it so you could combine them.
