### ISSUE TITLE
 attempting to enter the arenas exit removes doom mode prematurely

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22073]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Arena shuttle happened, got in the arena and had the red screen, chainsaw and demon view as normal, touched the exit because it was so dark and i could barely see, and "Doom mode" was removed from me, leaving me defenseless.

 Submitted by: englishscotsman (740223180806946946)

**Comment by Oblisk234** [comment]
Unfortunately it was just coincidence, doom mode gives you two minutes to kill someone. You hit the 2 min mark when you were at the exit.
