### ISSUE TITLE
 Dropping a red or sepia stabilied still keeps the effects on you even though you dropped it

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22084]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Pick a red and sepia up. drop it because why not. Run around and still see you're affected by speed. cowbots attempts to hinder xenobio has only made it situationally better

 Submitted by: englishscotsman (740223180806946946)

**Comment by cowbot92** [comment]
Dropping a red doesn't do this, dropping the sepia however does and will bee resolved with https://github.com/yogstation13/Yogstation/pull/22086

**Comment by Oblisk234** [comment]
Was fixed by #22086
