### ISSUE TITLE
 Ninja Den Ghost Beacon nullifies Assassinate Objectives

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22114]
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: Inconvenience
Brief Description: If an Assassinate objective target uses ghost beacon in Ninja Den zone to mess around, it'll be alive and not count as dead for the sake of objective
Steps to Produce: be target, die, respawn in ninja den

 Submitted by: kojuh (239560674517188609)

**Comment by Oblisk234** [comment]
Duplicate of #22113 (Not doing this because #22113 is my issue).
