### ISSUE TITLE
 Synth IPCs disguised as gorillapeople appear invisible.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22121]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: use charged blacks to roll for races. get gorillaperson. immediantly after that, get IPC synth and automatically disguise as a gorillaperson. become invisible when naked.

 Submitted by: englishscotsman (740223180806946946)

**Comment by ToasterBiome** [comment]
blacklisted race now
