### ISSUE TITLE
Cargo Shuttle Not Loading

### ISSUE THREAD

**Issue by thecatastrophecat** [yogstation13/Yogstation#22120]
### Severity

Inconvenience

### Short Description

Bluespace ripples constantly but no shuttle

### Reproduction

1. Order shotgun from cargo privately
2. Wait for shuttle
3. Bluespace ripple flashes and then disappears

### Round ID

52705

### Test Merges

#21835

### BYOND Username

thecatastrophecat

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by Oblisk234** [comment]
At present not reproducible, logs do show that the supply shuttle couldn't enter transit space for some reason. Don't see any PRs that fix this, although I haven't observed this happening recently. Make a new issue if this reoccurs.
