### ISSUE TITLE
Teslium not producing

### ISSUE THREAD

**Issue by Cubetastic** [yogstation13/yogstation#2213]
Having issues producing teslium. Following the recipe, on multiple occasions it isnt producing any. Recent changelogs dont show anything concerning teslium. If the recipe IS different, its extremely hard to find.

Wiki recipe:
https://tgstation13.org/wiki/Guide_to_chemistry#Teslium

1 Part Stable Plasma
1 Part Silver
1 Part Black Powder
Temperature 400K

Proof of it not working ingame:
https://puu.sh/vXXyT/af49d0db1e.png

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/blob/master/code/modules/reagents/chemistry/recipes/toxins.dm#L110

Plasma != stable plasma

**Comment by Cruix** [comment]
TG made teslium easier to make in https://github.com/tgstation/tgstation/pull/20448
We forked before that so the wiki recipe is different from ours.

**Comment by Cubetastic** [comment]
Alright, thanks for responding. Had a feeling it would be something silly like that, didnt know where to look.
