### ISSUE TITLE
Lavaland Wastes APC

### ISSUE THREAD

**Issue by nichlas0010** [yogstation13/yogstation#2215]
Attaching an APC to the wall of a mining shelter allows one to power the entire lavaland

http://i.imgur.com/WS41Oco.png

**Comment by Time-Green** [comment]
Wait so, placing an APC on the emergency shelter, wich has its own area, powered whole lavaland?
Can you give more context and details?

**Comment by ShadowDeath6** [comment]
Wew lad

**Comment by Kmc2000** [comment]
Area issue?

**Comment by nichlas0010** [comment]
Put the APC on the outside of the shelter. That seemed to give all of the lavalands power

**Comment by nichlas0010** [comment]
That's all I know
