### ISSUE TITLE
 Plasma thrusters and firelocks deconstruct with M1 instead of M2 (oversight)

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22158]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: The thrusters that spawn on shipbreaking ships plus directional firedoors can't be deconned with M2 using tools, this is an oversight because every other object in the game is deconned with M2, making these stand out

 Submitted by: amyriad (170817240223055872)

**Comment by Oblisk234** [comment]
Can't replicate, was able to deconstruct both shuttle thrusters and directional firelocks only using M2.

**Comment by Oblisk234** [comment]
Can't replicate after second test, would say that this has been fixed by #22045 but it seems far too long for the server to not have been updated.
