### ISSUE TITLE
TGUI Combat update makes drones incapable of doing their job, violating their laws (and the station as a whole).

### ISSUE THREAD

**Issue by MommaDragon** [yogstation13/Yogstation#22207]
### Severity

Inconvenience

### Short Description

Drones can no longer heat up screws in reinforced windows - only burn the window, or repair it.

### Reproduction

1. Animate a drone body through possession
2. Turn on your welder and use it on the Window
3. Activate combat mode and hit the window
4. There is no other way to remove the window other than destruction, turns out, because someone can't code for shit and repair overlaps removal, and combat mode means you always hit things.

### Round ID

n/a

### Test Merges

It's a combat mode problem.

### BYOND Username

TheMommaDragon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Sometimes, you just need to realize that TGUI and the combat mode system needs thorough testing before you make the game shit (on accident).
This might also affect monkeys, as Molti said monkeys are the only other entity to utilize the same system as Drones.
No, right click *does not* work.

**Comment by Oblisk234** [comment]
Are you sure this was a reinforced window and not a normal window? Can't replicate using a reinforced window, and with a normal window I can replicate but this would be intended, since windows aren't deconstructed the same as a reinforced window.

**Comment by Oblisk234** [comment]
#21883 moves heating screws from harm intent to right click.
