### ISSUE TITLE
Paraplegic Players can't use exosuits.

### ISSUE THREAD

**Issue by InfernalNull** [yogstation13/Yogstation#22206]
### Severity

Inconvenience

### Short Description

Paraplegic Players can't use exosuits.

### Reproduction

1: Join round as paraplegic Ex'Hai
2: Build a Ripley Exosuit
3: I drag my sprite into the exosuit, if I try doing it while buckled to the wheelchair it says i can't do it while im buckled, and when I do it while unbuckled, it just says "You can't do that right now."

### Round ID

Round #52906

### Test Merges

#22090 #21275

### BYOND Username

InfernalNull

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

My fellow roboticist could get in no problem.

**Comment by Moltijoe** [comment]
not a bug
even if you can climb in by using wings to prop you up while unbuckles
it still prevents being able to move

perhaps i shall add a text prompt
