### ISSUE TITLE
 Crystalised green pylons clear the mutation they give out.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22200]
## Test Merges: 
Not Supplied / None
## Reproduction:
Wiki and ingame description state they clear any except for the mutation stored in the crystal, but they clear all mutations anyway when leaving the radius

 Submitted by: englishscotsman (740223180806946946)

**Comment by Oblisk234** [comment]
This is intended behaviour, it is meant to remove the selected mutation upon exiting the radius, and it will gradually remove other mutations (not the selected one) while in the radius over time. From testing and reading the code, it doesn't clear all mutations when leaving the radius, only the selected one.

As for the wiki part not mentioning this, asked in discord for wiki to update that, I'll keep track of that myself.
