### ISSUE TITLE
 Shipbreak zone relapsed in on itself

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22226]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: i spawn ship in, after a while of breaking and respawning ships in it ignores clear flooring and thus allowing me to just spawn in any AMOUNT of ship *( thrusters and so on stack )*

 Submitted by: 7.1.2.2.30 (481942123348885535)

**Comment by cowbot92** [comment]
fixed with https://github.com/yogstation13/Yogstation/pull/22368
