### ISSUE TITLE
 Stinger Trident do not work

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22225]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: I cannot stab anything with trident, clicking people with it just don't work. (maybe it's because it's shrapened)

 Submitted by: hwseo7 (271949665207975937)

**Comment by Oblisk234** [comment]
Can't replicate, was able to stab with stinger trident with every variation of sharpening.

**Comment by Oblisk234** [comment]
Can't replicate after testing again.
