### ISSUE TITLE
furniture bounties impossible to complete

### ISSUE THREAD

**Issue by ThatGuyPhil** [yogstation13/Yogstation#22253]
### Severity

Inconvenience

### Short Description

Comfy chairs do not move on conveyors

### Reproduction

1. roll comfy chair bounty
2. construct comfy chairs on conveyor on the input side of the packaging machine.
3. pull conveyor
4. ...
5. cry.

### Round ID

53045

### Test Merges

#18024

### BYOND Username

fireclaw787

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

![image](https://github.com/yogstation13/Yogstation/assets/50330177/06449bd2-a30f-473b-8634-3115410ca478)
Mujeen-Sei is devastated to see  that the five comfy chairs that took him 4000 years to make are unable to go inside of the packaging machine. (2517 colorized)

**Comment by Oblisk234** [comment]
#18024 is currently closed, testmerge issue.
