### ISSUE TITLE
 i have found the dumfock cause for shipbreak zone breaking itself

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22365]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: this goofy SYNDICATE SHUTTLE THAT LOOTS LIKE THIS, is the sole reason why shipbreak is broke
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1261782400850202705/Screenshot_2024-07-14_043043.png?ex=669435ef&is=6692e46f&hm=403579d4e0212072cc07128907e7325884a368ecce41ccd1e4233a52df54da85&)
 Submitted by: 7.1.2.2.30 (481942123348885535)

**Comment by cowbot92** [comment]
fixed with https://github.com/yogstation13/Yogstation/pull/22368
