### ISSUE TITLE
Mass Driver blocked by wall

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#22378]
### Severity

Inconvenience

### Short Description

Chapel Mass Driver path blocked by Shipbreaking room wall

### Reproduction

1. Try to give someone an honorable space burial
2. *thunk*

### Round ID

Round #53227

### Test Merges

#22265 #22269 #22301 #22220 #22220

### BYOND Username

crazy_drakkon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

![image](https://github.com/user-attachments/assets/ebb4eeac-3142-4775-a257-21a596ca7682)

Maybe moving the driver, tables and confessional booth up a tile would be a good fix?

**Comment by cowbot92** [comment]
https://github.com/yogstation13/Yogstation/pull/22383 fixes this
