### ISSUE TITLE
Carpet item sprites invisible

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#22380]
### Severity

Low

### Short Description

The carpet item (not floor sprite) is invisible

### Reproduction

1. Crowbar up carpet
2. Invisible

### Round ID

Round #53229

### Test Merges

#22265 #22269 #22301 #22220 #22353 #22297 #22169

### BYOND Username

crazy_drakkon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

![image](https://github.com/user-attachments/assets/4873ea0c-3ebf-409e-9c80-35eb30d20820)

**Comment by ktlwjec0** [comment]
#21871
