### ISSUE TITLE
Lavaland Prisoner Ruin Sprites Black

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#22391]
### Severity

Low

### Short Description

Walls on Lavaland Prisoner Ruin sprites are black

### Reproduction

1. See

### Round ID

Round #53251

### Test Merges

#22265 #22269 #22301 #22220 #22353 #22297 #22297

### BYOND Username

crazy_drakkon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

![image](https://github.com/user-attachments/assets/f97e025a-fc3d-4091-94c3-cc11ca5780fa)

**Comment by AMyriadseviltwin** [comment]
the hell I thought we disabled this

**Comment by cowbot92** [comment]
@ToasterBiome this is passing the blacklist @Chubbygummibear smooth this

**Comment by Chubbygummibear** [comment]
> @ToasterBiome this is passing the blacklist @Chubbygummibear smooth this

hhhhhhhhhhhhhhhh
