### ISSUE TITLE
Slime goes in and out: Mulebot edition

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2244]
The pink adult slime (372) has let go of the MULEbot!pink adult slime (372) has latched onto the MULEbot!
The pink adult slime (372) has let go of the MULEbot!pink adult slime (372) has latched onto the MULEbot!
The pink adult slime (372) has let go of the MULEbot!pink adult slime (372) has latched onto the MULEbot!
The pink adult slime (372) has let go of the MULEbot!pink adult slime (372) has latched onto the MULEbot!
Slime was hopping on and off MULEbot in seconds.Over and over. Untill the end of time.
Not moving from mulebot an inch. 
luv can bloom

**Comment by ShadowDeath6** [comment]
I think this is a bug with drag + dropping

**Comment by Ratvar** [comment]
Oh well
