### ISSUE TITLE
Plantman slings loose health to unhealable oxygen damage

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2245]
Shadowlings do not heal oxygen damage cause they do not breath. No in darkness, no with rapid rehatch.
Plantmans are damaged in darkness.
HAtch chamber light is NOT enough to make plantman not suffer in darkness, so they get oxygen damage.
Shadowlings do not heal it afterwards.
Congratulation,permament lost health.

**Comment by ShadowDeath6** [comment]
your wish is my command
