### ISSUE TITLE
How to get objectives for free

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2248]
Step 1: Use codex GIgas in hand as non-librarian, spam it. Click Z in hotkey mode and enter to promt it really fast. http://imgur.com/a/WBqwo
Bug 1: you can read codex gigas while you read codex. Imgur image up here shows you are not supposed causr you get "Someone else is reading it!" message.
Step 2: WAIT.
Step 2 alternative: MOVE OFF THE TILE after you spammed it enough. http://imgur.com/a/2osgU
Bug 2: you get sin objectives even when you just started to read book, not when you actually finish it and wait for it.

Plz merge debils already

**Comment by ShadowDeath6** [comment]
actually we added devils as a framework just so people could abuse the book for antag
