### ISSUE TITLE
Drones start in Backrooms

### ISSUE THREAD

**Issue by Aquizit** [yogstation13/Yogstation#22480]
Issue reported from  Round ID: 53454 (Yogstation 13)

Reporting client version: 515.1621

As title states. Picked drone in ghost role list started in the backrooms, needed to find my way out. Unsure if intended.

**Comment by Oblisk234** [comment]
Honestly, not sure if this is an issue or it isn't an issue. Going to say that this is a semi-issue in the fact that it's unclear whether this is intended or not, no clarification anywhere about this.

**Comment by Oblisk234** [comment]
Per the creator, this is intended.
