### ISSUE TITLE
Synthetics don't have access to cloning

### ISSUE THREAD

**Issue by Oblisk234** [yogstation13/Yogstation#22508]
### Severity

Inconvenience

### Short Description

Access PR broke it probably

### Reproduction

Be a synthetic, try to open the cloning lab door, fail.

### Round ID

53539

### Test Merges

#22220

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by AMyriad** [comment]
we killed em
