### ISSUE TITLE
 Swapping beaker while grinder is grinding

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22544]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: If you swap beaker while all-in-one grinder you can skip the grinding and get the result instantly. It merely takes like 5 seconds but whatever cowbot is fat

 Submitted by: kim4565 (329181803573280769)

**Comment by teh4565** [comment]
while all-in-one-grinder is grinding*
