### ISSUE TITLE
 Objects do not fall down stairs when thrown into empty space

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22576]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: when you toss an item (on ministation) above a stairwell they don't fall down to the other z-level but stick as if there's a floor
## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/1280351404766269500/image.png?ex=66d7c3aa&is=66d6722a&hm=b2b3985c46f47f1333f78097f9c6bf93588357f7b1ae55a3153d94c8c381cc93&)
 Submitted by: sadthunder07 (263084474672218112)

**Comment by ToasterBiome** [comment]
fixed in https://github.com/yogstation13/Yogstation/pull/22568
