### ISSUE TITLE
3 blackjack card actinglike an 10

### ISSUE THREAD

**Issue by SabinStauceanu** [yogstation13/Yogstation#22584]
### Severity

Inconvenience

### Short Description

3 blackjack card actinglike an 10

### Reproduction

1. join the round as any role
2. download balckjack on your PDA
3. calculate every round where 3 card is played
4. see some buting hands where you actually you should not bust.

### Round ID

53805

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by ToasterBiome** [comment]
Removed IC screenshot of current round, also, that's a Jack not a 3
