### ISSUE TITLE
 can't add plasma cutter to ripley

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22599]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: when you try putting it on you just get the message that it's at full integrity

 Submitted by: climbupthedown (851100160037617704)

**Comment by Oblisk234** [comment]
Can't reproduce, attached a 217-D plasma cutter with no issues.
![image](https://github.com/user-attachments/assets/87afadc8-3040-42a3-a9a7-ecfae77616f7)

**Comment by Oblisk234** [comment]
Was fixed apparently.
