### ISSUE TITLE
 storyteller failing midrounds

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22612]
## Test Merges: 
Not Supplied / None
## Reproduction:
description: appeared in deadchat chat that space pirate event spawned  (Storyteller was tmd) and then no one who had pirates enabled got a prompt, and the pirate ship was not spawned.

 Submitted by: ultrabigrat (225615376828989440)

**Comment by Kmla2** [comment]
most likely the commit https://github.com/Monkestation/Monkestation2.0/pull/2558/commits/389e5379d3894dc21eed8034a5a5833282f61487 wasn't ported, not gonna check because god 400 files don't really want to show, even if i done more before      #22661
