### ISSUE TITLE
Knowledge System

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation#2267]
# What is it?
The "Knowledge System" changes the way most job interactions work, drasticly cutting down on powergaming. A job would be assigned skills, wich they can use to progress on their job. 
On the other hand, an assistant wouldn't be able to do surgery the way they use too. See, an assistant does not have any surgical knowledge, but instead of preventing him from doing it, it'll just stab him in the dick for it.
## Skills
The current skills include:

	medical 
	virology 
	chemistry 
	genetics 
	surgery 
	
	engineering
	atmospherics 
	
	science 
	robotics 
	
	bartending 
	cooking 
	botanics 
	
	combat 
	command
	
	religion 
	greytide 
	clownery 
	illegal
These skills range from 0-10. 1 for any skill you have nothing to do with, 10 for being skilled.
Having a skill of 0 prevents to individual from doing the skill at all. Only happens when a neuromod has been used, more on that later.
## Second hand skills
Imagine there being no medical do to surgery on you, would you be completely doomed? 
No, a virologist per say, would be able to use his general medical skills (not surgical), to do the surgery. However, don't expect to leave without a few cuts. Surgery formula: surgery + (medical / 2)
(Not the actual formula, It's going to be alot more automated and fancy)
Take in mind, everyone in medbay has a high medical skill, but the medical doctors's will always be higher.

## Neuromods
Knowledge implants! I didn't like the real name and I wanted this reference in.
The head of personel will be supplied with neuromods. He can use this to change someones skillset, at the cost of a horrible side-effect. The person would only be able to use THOSE skills, meaning if you got an assistant neuromod; instead of having surgery of 1, you get surgery of 0, wich would prevent you from doing it. 
You can always pull them out with surgery to reverse their effects. Luckily these newer designs don't feature amnesia, but it still is tiring.
## Antagonist
Antagonists will have a antagonist skills, and cannot loose those.

Requested by: @Slinky5890

Please leave your opinions and suggestions in the comments.

**Comment by Jc1469** [comment]
> The person would only be able to use THOSE skills, meaning if you got an assistant neuromod; instead of having surgery of 1, you get surgery of 0, wich would prevent you from doing it.

:thinking: 

how bout no.  this will become a new cancerous way to demote people, and will be horribly abused.

**Comment by Time-Green** [comment]
>🤔
>
>how bout no. this will become a new cancerous way to demote people, and will be horribly abused.

If you got a better idea, tell me. It needs to have a downside, to prevent powergaming them.

**Comment by Jc1469** [comment]
code shouldn't be making up for people powergaming. admins should be.
so code an admin that actually enforces powergaming. there you go.

**Comment by Time-Green** [comment]
I'll just give hop the skill to apply neuromods then.
HAHA!!

**Comment by matskuman5** [comment]
3rd time it's been suggested.

It's a good idea but very, very hard and time-consuming to implement.

**Comment by Time-Green** [comment]
I already started and it's going fine

**Comment by drderp3635** [comment]
No

**Comment by Super3222** [comment]
It's a fun idea when you get to scale down what every job should be able to do, but it doesn't belong in SS13. Maybe in a different theme, but not vanilla ss13.

> religion 
> greytide 
> clownery 
> illegal

memes.

**Comment by matskuman5** [comment]
Also what's wrong with the original idea of knowledge implants? They could be distributed in an emergency. Those neuromod things sound like a terrible idea, and as John said the possibility for abuse is pretty shit

**Comment by Time-Green** [comment]
They are knowledge implants, and I just really don't like to see them get powergamed.
Anyway, I'll stop the project, as no one seems to like it
