### ISSUE TITLE
Make cells radproof

### ISSUE THREAD

**Issue by Slinky5890** [yogstation13/yogstation#2268]
No sec officer is gunna clear out the cells/perma to save prisoners during a radstorm. I don't think it's too fair to let a 2 minute crime-d criminal to die because of a radstorm

**Comment by matskuman5** [comment]
REEEEEEE SEC POWERCREEP

**Comment by Time-Green** [comment]
Slinky has a point

**Comment by 00aquir** [comment]
Syndie lives matter!

**Comment by LarissaMayrink** [comment]
make perma bathroom radprood, or like the cells bed tile and nothing else

**Comment by Mrcreepssss** [comment]
radproof bedsheets?

**Comment by Mrcreepssss** [comment]
and potty's

**Comment by Mrcreepssss** [comment]
what about giving sec radproof bedsheets?

**Comment by AlpacaGoesCrazy** [comment]
Maybe geneticist/viro monkey pens should also get some radproof love?
