### ISSUE TITLE
New mining strats.

### ISSUE THREAD

**Issue by Bekons** [yogstation13/yogstation#227]
The watchers. 

A huge eye. 

Let miners use a laser pointer on it, to temp stun it.
Use it on goliaths to not let it tenril for a short time, as it cant see you but it can smell you to beat the shit out of you.

No effect on legions or megafauna

**Comment by Stealthkibbler** [comment]
Good idea famalam

**Comment by timkoster1** [comment]
This could work well, as it makes it possibpe to kill watchers without losing health

**Comment by timkoster1** [comment]
I'll take a look at this
