### ISSUE TITLE
Energy Harvesting Module not working (EDIT: flawed functionality)

### ISSUE THREAD

**Issue by DeanYktRu** [yogstation13/Yogstation#22745]
### Severity

Inconvenience

### Short Description

CE's powersink is not taking power from the grid

### Reproduction

1. Make an engine.
2. Take the Energy Harvesting Module.
3. Screwdrive it on cable, set the input limit.
4. Turn it on.
5. Nothing happens.

### Round ID

54219

### BYOND Username

DeanYktRu

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

![image](https://github.com/user-attachments/assets/e023b90f-3594-408a-bec0-ffe1b05d55be)
![image](https://github.com/user-attachments/assets/51cf4a48-c620-4f33-b8fd-3d46da0d7aa5)
I've set the right input limit, didn't I?
Likely related to #8496.
EDIT: The module needed to be unscrewed and screwed back once turned on.

**Comment by ShoziOffical** [comment]
this bug is uh very ackward, but the other way around is, you have to turn it on in your hand first. then screwdriver it in
it will work
