### ISSUE TITLE
Borers spam requests

### ISSUE THREAD

**Issue by Slinky5890** [yogstation13/yogstation#2274]
There's a possibility i'm wrong here and for some reason a bunch of borers were born at once, but I doubt it as this happened a few times.

http://prntscr.com/fhu1r4

All of them are borer requests in a span of a few seconds. Other people witnessed this too

**Comment by MenacingManatee** [comment]
I tested this myself in game not too long ago, the reproduce button lets you spam it as many times you want as long as you have the chems for it (and chems aren't removed until the borers  actually spawn) which means you can press the button just about as much as you want and it creates a notification for ghosts each time it's pressed.
