### ISSUE TITLE
 Yogbot's !info command doesn't update when shuttle was called

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22742]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Self explainatory, It's been happening for quite long time.
When shuttle was called, the shuttle status remains at "Idle" until shuttle docks to station.

 Submitted by: kim4565 (329181803573280769)

**Comment by Oblisk234** [comment]
Yogbot is a separate thing from the server codebase, has been reported [here](https://github.com/yogstation13/yogbot-kt/issues/145) for you.
