### ISSUE TITLE
Singularity energy increasing, but size doesn't

### ISSUE THREAD

**Issue by nichlas0010** [yogstation13/yogstation#2275]
[Note]: Set up a singularity, but it never grew. Slinky looked in the Vars and found that the energy was increasing. A couple of moments later it loosened, while still retaining size 1

**Comment by YogsMcree** [comment]
This did not happen in the round I was just in. Something else happen to the sing to cause this?

**Comment by nichlas0010** [comment]
The singularity generator was next to a field gen, if that makes any difference

**Comment by X-TheDark** [comment]
I believe the singularity requires adjacent squares for it's next stage to be clear of obstructions (aka, it needs space to grow and won't, if the next stage would overlap the fields).

**Comment by nichlas0010** [comment]
Ah, welp. I'll juse close this, since it appears it's more of a "me being dumb" thing than a bug
