### ISSUE TITLE
I am stuck in the edge of the map on Ministation.

### ISSUE THREAD

**Issue by SabinStauceanu** [yogstation13/Yogstation#22797]
### Severity

Round Breaking

### Short Description

I am stuck in the edge of the map on Ministation.

### Reproduction

1.Join as any role on Ministation
2.Wear space suit, internals and throw yourself in space
3.Reach the boootom of the map (you cannot escape even if you throw objects in space)
![Screenshot (2)](https://github.com/user-attachments/assets/35334dd5-1d6d-4e70-9f11-8801885acb76)

### Round ID

54412

### BYOND Username

boyy

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by Oblisk234** [comment]
@ToasterBiome This intended?

**Comment by Oblisk234** [comment]
Per what has been said in the development feedback section for ministation, this is intended.
![image](https://github.com/user-attachments/assets/5220569c-a83f-4d11-b58c-0c868510f198)

**Comment by SabinStauceanu** [comment]
Soo on bottom level is intended to remain stuck?

**Comment by Oblisk234** [comment]
> Soo on bottom level is intended to remain stuck?

Yes. You can throw things to move away, place new flooring, or pray to the gods.
