### ISSUE TITLE
Vox spawn with incorrect internals

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#22805]
### Severity

Low

### Short Description

When spawning in, the vox internals may not be the one you selected in prefs

### Reproduction

1. Select vox & select the vox respirator in prefs
2. Join the round roundstart (NOT MIDROUND)
3. Spawn in with the vox breath mask instead

### Round ID

#54270

### BYOND Username

Ynot01

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

View replay and spectate me

Joining midround has intended behavior

**Comment by Oblisk234** [comment]
Also seems to occur with tank preference.
