### ISSUE TITLE
CTF hardsuits have no item sprite

### ISSUE THREAD

**Issue by Oblisk234** [yogstation13/Yogstation#22801]
### Severity

Low

### Short Description

It has a sprite for when worn but not in hand as an item

### Reproduction

![image](https://github.com/user-attachments/assets/d11e364f-43a1-4231-9aad-7129048c613c)
![image](https://github.com/user-attachments/assets/54df2f73-8ae8-4c0e-8a45-7ee954aff946)

### Round ID

54420

### Test Merges

#22095, #22683, #22796

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Scrambledeggs00** [comment]
![image](https://github.com/user-attachments/assets/e76f7fa7-7c57-4b39-80b8-be4ade672d44)
Seems that it doesn't have any item sprites assigned, so it would be a simple fix of making some and assigning them. I just don't have time to do that right now.
