### ISSUE TITLE
Bluespace harvester/BSA/DNA vault cannot be acquired through cargo

### ISSUE THREAD

**Issue by Buckethead390** [yogstation13/Yogstation#22807]
### Severity

Inconvenience

### Short Description

title

### Reproduction

1. Open cargo console
2. Check engineering tab
3. Machines not available

### Round ID

#54456

### Test Merges

#22095 #22683 #22796

### BYOND Username

Buckethead390

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Oblisk234** [comment]
Seems to be caused by the move from SSticker to SSgamemode in #22661.
![image](https://github.com/user-attachments/assets/fdd21074-4c4a-43df-96ab-883e776838cc)
![image](https://github.com/user-attachments/assets/74062d5c-e3b7-461a-ab35-441fbadf0dec)

**Comment by ShoziOffical** [comment]
@Moltijoe

**Comment by Oblisk234** [comment]
Was fixed by #22856
