### ISSUE TITLE
garden warfare the phytosian martial art dosent let you remember the combos

### ISSUE THREAD

**Issue by LassiH** [yogstation13/Yogstation#22822]
### Severity

Inconvenience

### Short Description

try to remember combos nothing happends

### Reproduction

1. learn garden warfare
2. try to memorize combos
3.  cry as you cant

### Round ID

54567

### Test Merges

#22095 #22683

### BYOND Username

lassih

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by Oblisk234** [comment]
Can't replicate, tested specifically at round end as phytosian, was able to remember combos. No runtimes indicating anything either.

**Comment by Oblisk234** [comment]
Can't replicate on second test, able to remember combos.
