### ISSUE TITLE
'Drag and Drop Containers' only partially fixed. Container-to-container drag and drop still broke

### ISSUE THREAD

**Issue by burn1cycle** [yogstation13/Yogstation#22839]
### Severity

Inconvenience

### Short Description

If you drag one container to another container it doesn't move objects

### Reproduction

1. Click and drag first container
2. Drop on second container
3. No object transfer takes place

### Round ID

XX

### Test Merges

XX

### BYOND Username

XX

### Was this done on a locally hosted or non-Yogstation hosted server?

None

### Additional information

Was this done on a locally hosted or non-Yogstation hosted server? Yogstation's server
This is a continuation of [this issue over here](https://github.com/yogstation13/Yogstation/issues/22831). The bug where item pick up wasn't working is solved but the container-to-container movement issue has not been. 

 I've got to thank the coder for trying their best to fix part of the bug but unfortunately there's a bit more and it may've been my fault for not explaining all of it.

**Comment by ShoziOffical** [comment]
@SapphicOverload
