### ISSUE TITLE
 pAIs cannot access their software interface in card form

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#22842]
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: See title; pAIs can only use the software interface in their mobile form. Otherwise, it acts as if you're a tile away from the interface and prevents usage, only allowing the pAI to look at the menu.

 Submitted by: spacemanspark (132241919026790400)

**Comment by Oblisk234** [comment]
Duplicate of #22779
