### ISSUE TITLE
Atmospherics East camera is not Atmospherics east

### ISSUE THREAD

**Issue by Oblisk234** [yogstation13/Yogstation#22840]
### Severity

Low

### Short Description

Very much bug

### Reproduction

Atmospherics East camera actually shows the chapel instead.

### Round ID

54693

### Test Merges

#22095, #22813, #22683, #22825

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

**Comment by ToasterBiome** [comment]
what map

**Comment by Oblisk234** [comment]
> what map

Yogstation.
