### ISSUE TITLE
Unlimited Spraypaint Useage with Odd Integer of Uses Remaining

### ISSUE THREAD

**Issue by SuperTeaLove** [yogstation13/Yogstation#2312]
[Round ID]: # 18117

[Reproduction]: # Simply put, spraying paint onto any window with a spraypaint can with one use remaining will allow you to infinitely use that spraypaint on any number of windows; so long as the remaining uses in the Spraypaint is 1. You can easily manipulate this by simply spraying one letter onto the ground to convert the starting uses in the Spraypaint to 29, and from there spray windows down to one use, thus allowing you to spray infinite windows.

By default, spraypainting a window consumes two uses. When using Spraypaint on a window with only one use remaining it does tell you in the chatbox that you do not have sufficient uses to perform the action, but it performs just fine and does not consume the one remaining use. Note that inadvertantly consuming this one use by spraying a letter on the floor will then empty the can and render it truly nonfunctional.

Very minor issue, hopefully a minor fix!

**Comment by Altoids1** [comment]
No longer a bug.
