### ISSUE TITLE
Genetics is not working as intended (positive powers won't trigger)

### ISSUE THREAD

**Issue by SyntaxErrorLine3** [yogstation13/Yogstation#2316]
(Closed last issue due to confusion on my part, used tgstation round id's instead of Yog's)

There is an ongoing issue in genetics where positive powers will randomly not trigger. I will get all the traits discovered via injectors and 2-3 positive ones will be missing, along with 2-3 gene nodes whose injectors came up empty. Sticking myself in the scanner with those empty nodes active then has about a 40% chance of triggering one of the missing powers, while the remaining ones will basically be unavailable for the rest of the round.

**Comment by ktstudios2000** [comment]
Can you verify that this is still an issue? I know that powers do not have a 100% chance of triggering when you use occupant:delayed to manifest them, and it's not that rare to have to do it ten times in a row to unlock them all.

**Comment by SyntaxErrorLine3** [comment]
It isn't actually an issue. The wiki said all powers will automatically
trigger above 800. I learned from an admin this is only true for negative
powers, positives trigger at a random point above 800. So if you get a dead
hit like I was describing you just have to keep going higher.

One issue that would be nice to see fixed is lizards not being able to
trigger hulk.

**Comment by Ktlwjec** [comment]
Closing this due to the new genetics system.
