### ISSUE TITLE
Some Cooking bugs.

### ISSUE THREAD

**Issue by Frostben** [yogstation13/yogstation#2316]
So I just played a round as chef and found that there were a few things that I wasn't able to do for one reason or another.

1. Can't cut a potato into potato wedges. I put the tater on the table, poke it with a knife with all intents, and nuffin.
2. Can't process cutlets into bacon. I was trying to put a raw monkey cutlet into the processor and it said it would not blend. A bit odd unless it is specifically cutlets from the cow?
3. Mint toxin does not gib a fat person. I decided to gorge myself on food then waited until the food meter turned gray meaning that i was fat. I then grinded the mint and swallowed the mint toxin and nothing happened at all.

**Comment by ShadowDeath6** [comment]
1. tg has those, we don't

2. tg has bacon, we don't

3. you need to be visibly chubby, examine yourself. The food bar shows when you're overeating, but you aren't "fat" yet

**Comment by Frostben** [comment]
Woops! Ok ima close this then, i guess i should use the yogstation wiki instead of tg huh?
