### ISSUE TITLE
You still have transparent races accesible through magic mirror, and for wizards

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2319]
Fly race. Not manfly, not flyternesis-just fly.
Check other races while you are at it, please

**Comment by Time-Green** [comment]
What do you mean? Fly people aren't invisible

**Comment by Ratvar** [comment]
Those are Manfly, not fly people. Try to become Fly using magic mirror. NOT MANFLY.

**Comment by Time-Green** [comment]
Crap, that was never changed in rebase.
Thank's for the report

**Comment by Ratvar** [comment]
Well, problem solved
