### ISSUE TITLE
Fulton cannot deliver item

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#2321]
Fulton pack can deliver ore box and all other things that are not bolted, however not lockers that you can lock. When you use fulton pack on them, they get unlocked and when you use them on your personal locker, you just get the "access denied" message.

**Comment by SomeguyManperson** [comment]
you have to be on harm intent to move lockers and crates, any other intent will try to open them.

**Comment by 00aquir** [comment]
Because the game makes use of a different intent for when you want to whack lockers. In this case, the "game" should adapt to the usability, this item should work on any intent imho, because using harm intent wouldn't normally make sense here, and is not self-explanatory.
