### ISSUE TITLE
On mysterious lava boat, items BURN IN YOUR HAND!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#2322]
The horror!

**Comment by SomeguyManperson** [comment]
This happens when you pick anything up while on a lava tile, regardless of whether you are lavaproof. I haven't noted whether it affects things taken from jumpsuit/suit storages but it does affect anything taken out of a backpack.

**Comment by MimicFaux** [comment]
iirc it's because it transfers things to the ground for a split-second while moving locations. Try it next time you have floating  over a chasm.
