### ISSUE TITLE
Infinite cosmic walker respawn is bugged to hell

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2324]
Cosmic ashwalker literally cannot die. You cannot kill his egg when he regenerates, and he can talk out of it through memes. If he sufficates-he will regenerate over and over and over and they dont stop comming every seconds, spamming death logs. Oh, yes, you also can push and pull it around, but like it matters on station where you cannot pull him over lava and must do changeling cremation style shit. His regeneration is worse then changeling.Oh, YEAH, he also locks all items he wears with him in egg, so you cannot get that sweet nukedisk if he is inside, or that sweet traitor objective, or just anything sweet.
https://github.com/yogstation13/yogstation/pull/1848 says it is Three TImes only and you can attack egg to eject ashwalker out. Both statements are lie.

**Comment by Super3222** [comment]
It does only regenerate 3 times. The cosmic ashwalkers regeneration process isn't just reviving them, it's slowly healing the damage while they're either unconscious or conscious inside of the egg. In the case that it does die during this process, the egg will revive them.
