### ISSUE TITLE
Insta-death out of nowhere

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#2332]
Round 10154

Right after cuffing Smoke Wilkinson, I immediately died from full health (so quickly, that I instantly ghosted out of my body **while running**). 

Admin had no idea why.
"- Chuggachar: Yeah I'm not quite sure what to say about that, you have a load of toxin damage strangely"

**Comment by Frostben** [comment]
Isn't that the effect of a particular syndicate toxin? The longer it is in your system the more toxin damage it will do when it finally gets fully metabolized. This must mean that you had a fuck ton of it in your system to instantly kill you.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Yep, it's amanitin.

**Comment by 00aquir** [comment]
Uh, it's still looks a bit of a stretch to instantly die, make it a 5-10 second delay or something?

**Comment by drderp3635** [comment]
The way amatin works is that it it doesn't do toxin progressively, but will stay in your system then let it all out at once depending on how much you had in you

**Comment by fonedsky** [comment]
Amanitin's whole gimmick is that it waits to kill you. It already has a delay, and it usually tends to be a huge one depending on quantity, as it scales with that.
You probably ate a whole bunch of it (or got injected with it) probably three minutes before it happened, and then it activated, dealing you massive toxin damage.
