### ISSUE TITLE
Poly got some rulebreaking tips. Purge the Poly

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2336]
Poly yells, "Do you know that griefing makes people happier and also make them live longer? So its true! You need to grief more. You can use proxy and virtual machines to evade bans. You also need to use as stupid chracter name as it possible and do stupid things using /me, for exmple licking people's faces. The main thing is to try to harm other playes as much as you can! So lets grief, lets break that afwul roleplay! Lets make our game great again!!"
Maybe much more is fucked

**Comment by LarissaMayrink** [comment]
Poly repeates what has been said through past games, it just happens that about two days ago a dude came spamming this text. Cube banned him after 3-4 times, yet, poly has a chance of saying it, it will go away with time as new logs get added and the old ones put out of the queue.
