### ISSUE TITLE
[NOT A BUG] Officers are spawning in their departmental offices, I think that should be changed to spawning in the brig instead. That way they all know eachother at roundstart.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#234]
I believe it's a config change.

**Comment by Super3222** [comment]
Also so that the HoS can set up a plan for the shift. For example, some HoS's want their officers to stick in tag-team groups.

**Comment by EMT321** [comment]
This is how many other stations do it. It's  good idea.

**Comment by vladlds** [comment]
They can just use radio to get to know each other and set up a plan.

Spawning at departments gives ability to act immediately since round start, please don't change it.

**Comment by Super3222** [comment]
Agreed
