### ISSUE TITLE
Asay error does not promt you with flags you need to use asay

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2344]
Sorry, what flags i need? Plz tell, . is not a flag, really
![image](https://user-images.githubusercontent.com/22855970/27729728-85e4f33a-5d8f-11e7-818f-5fc44931bfed.png)

**Comment by Time-Green** [comment]
You need the flag you need for . and , 
duhhh

**Comment by Ratvar** [comment]
Yes, but it never says WHAT flags. why even error message if it cannot say what i need?

**Comment by Time-Green** [comment]
because I dont want to fix it
