### ISSUE TITLE
 Broccoli Moon points to the double-bladed energy sword (Wielded) - offhand

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2346]
You can cut off hands from someone holding doublehand object like syndie doubleesword or fireaxe/boneaxe, they will drop offhands, and you can pick it, but not drop it, et cetera

**Comment by Frostben** [comment]
Ok I'm going to "translate" this as well cuz this is some hard shit to understand m8.

What the author is trying to explain is that apparently any weapon that can be wielded with two hands (for example: spears, double bladed energy swords, and fire axes) has an issue where if they are being wielded while their arm is cut off and they drop it it becomes un-droppable after another person picks it up.

Take the ending of this with a grain of salt as some details may have gotten mixed up during translation

**Comment by Ratvar** [comment]
I talk about offhand objects itself, the one that appears in your second hand when you wield such weapons as axe or spear doublehanded. They drop on ground if you cut someone arm off. You can pick offhand objects, but not drop.  The offhand itself, not hands or weapons.

**Comment by Frostben** [comment]
OH! You are talking about the actual word text that appears in your opposite hand when you wield something! That makes much more sense. Also that is a weird bug.

**Comment by LarissaMayrink** [comment]
http://i.imgur.com/gackiy7.png

**Comment by Ratvar** [comment]
fix pr is up duh
