### ISSUE TITLE
Borg Hypospray doesn't go through protection

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#235]
might also be true with regular hypospray too

basically it was supposed to go through hardsuits and biosuits but now it doesn't
also it doesn't go through plasmaman suits which is intensely annoying

**Comment by Super3222** [comment]
I'm going to make injecting someone with a hardsuit take time using a hypospray.

One more thing, I like that last bit Plasamen's suits should be recognized in the code AND in the game. It's a literal protective suit, which shouldn't be completely ignored like 'oh yea it's just another jumpsuit ez".

**Comment by ShadowDeath6** [comment]
1. this makes it so that borgs have no way of treating plasmamen for toxins damage and they're literally supposed to be hyper-advanced medical equipment machinery
2. this makes the off chance of mediborgs being able to help people in space(like someone in a hardsuit dying to nukeops) nil since they can't do jack shit through the hardsuit.

this really isn't that big of a buff, it's just quality of life which makes the meme of "WAIT STOP LET ME HEAL YOU" even more annoying since they have to actually get the person to stand still to either take off their suit or ask them to which very rarely happens.

**Comment by X-TheDark** [comment]
Just take them to the sleepers that inject through the hardsuit. I feel that at this point, we are just trying to get mediborgs to replace medical doctors almost completely with roundstart defibs + hardsuit penning chems.

**Comment by ShadowDeath6** [comment]
yes we are :^)

**Comment by AdamElTablawy** [comment]
@Super3222

This is a prior feature of yogs

Port it

**Comment by ShadowDeath6** [comment]
Adam is right, it was a previous feature of code, and it wasn't unbalanced. (In my opinion at least)
