### ISSUE TITLE
Auxiliary base RCD drone vision bug

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#2351]
This thing cannot see the whole auxiliary base room.

![ss13-auxiliarybase-bug](https://user-images.githubusercontent.com/16806055/44639561-e7a38800-a9bc-11e8-90f1-e4e167d350a1.png)

**Comment by Ludox235** [comment]
I believe its because the drone only sees via cameras, kinda like the AI does, theyres some cameras in the room where you control the drone

**Comment by 00aquir** [comment]
Then how could you build normally when you're placing walls which themselves block the view? You get the point..
