### ISSUE TITLE
Damp rags no longer clean floors

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#2352]
Instead the game is treating them like a container trying to scoop up the blood and gibs, instead of wiping the floor down like they used to. Chef can no longer clean up after self.

**Comment by Altoids1** [comment]
So I tried fixing this by doing a port of morrowwolf/Barony13#183 , but unfortunately it seems like properly fixing this would require making rags no longer a ``/obj/item/reagent_container/glass``, & instead an ``/obj/item/reagent_container/``. Might do a PR to TG about this eventually, I'unno.

**Comment by MegaEmpirical** [comment]
You are my favorite person.

**Comment by MegaEmpirical** [comment]
Couldn't we just re-use the pre-rebase code for it?

**Comment by MegaEmpirical** [comment]
This is still an issue.

**Comment by MegaEmpirical** [comment]
Sad, still no fix.

**Comment by redmoogle** [comment]
Fixed by: https://github.com/yogstation13/Yogstation/pull/10544
