### ISSUE TITLE
Change Service channel color, possibly command too

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#2362]
The service channel is green and thus too similar to general and because it is so light with a white background, it is super hard to see.

As for command, it could possibly stand to have greater contrast. KTL suggested she'd like a change in the color.

I'll see about updating this post with the current colors as soon as I can grab a shot of them (tonight/tomorrow) and post suggestions shortly after.

**Comment by Amelia0010** [comment]
🤔

**Comment by MegaEmpirical** [comment]
Closing this because of this:

https://github.com/yogstation13/Yogstation-TG/pull/2745
