### ISSUE TITLE
Speech Bubble Displacement

### ISSUE THREAD

**Issue by sherbycool** [yogstation13/yogstation#2370]
The new speech bubble system is great, but i spotted a bug when i bucklecuffed someone on the bed.

https://gyazo.com/cb8b266e9d433f52b14b1ab5bb966cbe

When they're trying to speak while resting, the speech bubble appears a tile above the speaker.

**Comment by 00aquir** [comment]
Quickly revert this change.
The speech bubble cannot come up fast enough so it leaves out the first letter when typing!! Pressing escape cannot close it AND THERE'S NO CANCEL BUTTON EITHER.
