### ISSUE TITLE
"Say" window is broken!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#2371]
Quickly revert this change.

- The window cannot come up fast enough so it **omits the first letter when typing**!! (If the word starts with "o", it opens the OOC window behind it... etc.) 
- Pressing "escape" cannot close it AND THERE'S NO CANCEL BUTTON EITHER. Terrible choice.
- When you summon other windows from "say", like the suicide confirmation window, **you cannot use other windows to speak**!! then you get spammed with the windows after closing it!

I would expect something better from a change, not worse..

**Comment by Cruix** [comment]
You can erase all the text in the box and hit "ok" to not say anything. Not being able to use other input windows is an issue with all such windows, and there is nothing that we can do to fix it. The input-based say verb is completely optional and you can avoid using it by using the command line instead.

**Comment by 00aquir** [comment]
> You can erase all the text in the box and hit "ok" to not say anything.
No "escape", no cancel button? is this the 21. century? What's the reasoning behind this? It's clearly worse now and it's not fast enough to see when I start typing...
It is a literal **obstacle**: I could open more "say" windows before, now I cannot open a new one on top of the other! Usability dropped severely, and I cannot see any upside other than that "bubble" that (I guess) is visible to others as you start typing, appearing even after you suicided, when more "say" windows pop up after that...

**Comment by Cruix** [comment]
If you do not like it, you can press Tab instead of T and use the command line.

**Comment by 00aquir** [comment]
I don't see much reasoning here, just the offering of a worse alternative. On the other hand, I reported problems.

**Comment by Cruix** [comment]
The only problem you are reporting that did not already exist was the fact that the say window has no cancel button, which has already been reported on the relevant PR.

**Comment by 00aquir** [comment]
"already", compared to the previous system? The input delay is an obstacle for chat. Other than cancel/escape key for cancelling message, not being able to open other chat window to interrupt what you're saying and address other player in the meantime is also a hindrance. These all made chat worse.
