### ISSUE TITLE
You cannot replace APCs inside the same maintenance

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#2372]
- "This area already has an APC!"
- Connected to https://github.com/yogstation13/Yogstation-TG/issues/855

![ss13-evamaint-clerkapc-bug](https://user-images.githubusercontent.com/16806055/44756922-dda09700-ab2c-11e8-8b4f-b06127cae8c1.png)

**Comment by Altoids1** [comment]
The reason is that the APCs on the maintenance side of their room's wall are actually kinda hacked in by the mapper, where there's a tile owned by the powered room inside of maint for the APC to cling to. You can see this during rad storms.


A workaround comes from the fact that you don't actually have to _remove_ a broken APC frame in order to fix it; clicking on a broken one with an in-tact one is enough to replace it.

**Comment by Amelia0010** [comment]
What altoids said is wrong. The APC code was rewritten so now quite a lot of the APCs that are in maint that covers areas like `clerk's office` which is the APC you were changing, have the area they power in their variables, and only APCs made by players are bound to the area they're actually placed in. 

This means that the APC you were replacing was the one for the clerk's office, and you were trying to put it inside the maintenance, which already had an APC. This is not technically a bug, but intended behaviour as they're supposed to power whichever area they're placed in, unless they're mapped in. 

So the obvious solution: either don't deconstruct the APC fully or just place it inside whichever room you're actually trying to power.

**Comment by Amelia0010** [comment]
wrong button

**Comment by 00aquir** [comment]
- You have to deconstruct APCs in cases when they are unsalvageable or hacked and flashing blue.
- Many APCs are not close to doors, and I don't see the map for APCs, I just guess you would have to go around the area and make a completely new route for them like "medbay APC" when they are isolated in maint between other APCs.

Can't these areas simply just overlap each other? You should be able to select the area you're making APC for, and if several areas are currently powered in that area, you wouldn't be able to select them from a list.

**Comment by Amelia0010** [comment]
>Can't these areas simply just overlap each other?

hahahahahahhaahahahaha no.

**Comment by 00aquir** [comment]
why wasn't this a problem in the past?

**Comment by Amelia0010** [comment]
>why wasn't this a problem in the past?

Because back then, we used to have the actual area dipping into the maintenance, so clerk's area would own the tile the APC terminal was on, as opposed to maintenance. The downside to this, however, was that radstorms would still affect singular tiles in maint due to the weird mapping necessities

**Comment by 00aquir** [comment]
Hm. If this is so problematic, the maint wire should be just connected right to the damn APC on a wall, without any terminals. Otherwise this will always be some clunky thing with unnecessary circumnavigation.

**Comment by Amelia0010** [comment]
So you want the wires to go into walls instead? That'll totally not be a pain in the arse to maintain/repair at all.

**Comment by 00aquir** [comment]
You could be able to click on the APC with wire while you have exposed wire under yourself, and that would make it possible to connect it to the APC. Wouldn't that work? Wires can even go under doors..

**Comment by 00aquir** [comment]
This works now.
