### ISSUE TITLE
Silicon policy update

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#2410]
For new players, silicon policy doesn't mention shadowlings: https://forums.yogstation.net/index.php?pages/silicon-policy/

**Comment by drderp3635** [comment]
this would be a problem to bring up on the forums and not the github

**Comment by Jc1469** [comment]
An orbital satellite will be striking silicon policy eventually anyways.

**Comment by Cruix** [comment]
Not a codebase issue
