### ISSUE TITLE
Carp are constantly breaking into perma

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#2419]
I assume this to kill the mouse Tom, this happens in most rounds and is rarely fixed and is often actually pretty rough to fix because of carp or no insulated gloves if you're an atmos tech. Could we remove/move Tom or maybe move carp spawns further away?

**Comment by Amelia0010** [comment]
>I assume this to kill the mouse Tom

![image](https://user-images.githubusercontent.com/20558591/44948621-446dcb00-ae21-11e8-89e5-076e03d1c6d9.png)

>pretty rough to fix because of carp or no insulated gloves if you're an atmos tech

Two welder hits kills a carp, and [atmos techs have access to engineering.](https://github.com/yogstation13/Yogstation-TG/pull/2085)

**Comment by thehighwayman** [comment]
I agree lets remove Tom

**Comment by MegaEmpirical** [comment]
When did atmos get access to engi? That does resolve that issue though. Not sure why carp keep breaking perma when no one is in it though.

**Comment by thehighwayman** [comment]
25 days ago like the link nich posted says. Carp break into perma because sec like to head in there to check on things triggering any spawned carp

**Comment by MegaEmpirical** [comment]
I missed the link, my mistake. I see the carp break the windows when no one is in there so that's not it. It can be completely devoid of anyone and they still do it and just the window too, not even the grille unless they're trying to get to someone.

**Comment by Amelia0010** [comment]
Okay for some idiotic reason, carp sometimes aggro on him, and sometimes not? I've no clue why, but the carp seem to have a random feel on when they should actually bother doing something contrary to what they should be doing.

Either way, this is such a minor thing that I don't feel that it should be "fixed" by moving tom, since it's literally just fixing a singular window and killing a few carp.

**Comment by thehighwayman** [comment]
After having tested it myself it turns out that carp do go after Tom. I still support Tom's removal

**Comment by Amelia0010** [comment]
again, the whole result of this is that you need to fix a singular window and restore the atmosphere.

**oh and kill a few carp. In the place that's, you know, right next to the place with all the guns in it.**

**Comment by MegaEmpirical** [comment]
My issue is more that perma is so ignored and usually at the bottom of the barrel for worries during a round and so it rarely gets fixed but okay.

**Comment by jcatjmeow** [comment]
Who the fuck is tom

**Comment by alexkar598** [comment]
A mouse in perma
