### ISSUE TITLE
golem mutation fix didn't work

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#2427]
pull #2386 didn't work, you still just become the wierd metal colored golem (that isn't an iron golem)

how to recreate.
go into xeno grab yourself a green slime, radium, and silver
make some golem mutation juice with said ingredients, and inject or ingest it
watch as you become ugly gray golem

**Comment by Cruix** [comment]
The server has not been updated, you can tell because the pull request's changelog entry is not in the changelog.

**Comment by drderp3635** [comment]
oh. my apologies
