### ISSUE TITLE
Toilets have disposal bin overlays

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation#2428]
![untitled](https://user-images.githubusercontent.com/16478175/28740365-21079894-73c1-11e7-8e68-b12d5fd246c0.png)

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
They got upgraded to electric toilets with heated seats and pneumatic flushing

**Comment by Mrcreepssss** [comment]
would you want to sit on a dirty plate of metal?
