### ISSUE TITLE
Cloning rework

### ISSUE THREAD

**Issue by timkoster1** [yogstation13/yogstation#243]
Alright, as of right now, you can simply throw a corpse in the cloning scanner without caring about the poor bastard that could've simply been defibbed.

So add biomass:
This would mean you'd have to put catatonic corpses in a special machine that'd take them apart for biomass, wich could be fed to the cloning pod to make cloning more difficult and defibbing and replacing lost limbs more appealing.

**Comment by X-TheDark** [comment]
Nope. I'd rather just add some tooltip if you put a defibbable body into the DNA Scanner instead.

**Comment by timkoster1** [comment]
Good idea, adding a tooltip that'll say when a body is defibable might be better yeah..
