### ISSUE TITLE
Remove/replace the wizards heart from necropolis tendrils loot

### ISSUE THREAD

**Issue by someoneunkown** [yogstation13/yogstation#2437]
Because as far as I know, it's completely useless. I thought it was taken out for this same reason as before, being completely useless, but it has reared its ugly head once more without any changes to it.

**Comment by X-TheDark** [comment]
```
//Provides a decent heal, need to pump every 6 seconds
/obj/item/organ/heart/cursed/wizard
	pump_delay = 60
	heal_brute = 25
	heal_burn = 25
        heal_oxy = 25
```

Heals, but you need to pump it, or you DIE.

**Comment by someoneunkown** [comment]
Unless you need to get this implanted in surgery, i've pumped it while it was in my hand and it's been completely useless to me. Also, combine with the fact that implanting yourself with a legions soul is probably a much better alternative then pumping the heart every 5 seconds.

**Comment by X-TheDark** [comment]
You need to use it in-hand and it will replace your heart, after which a action button will appear in the top-left pane. And no, it's not implanted by surgery.

You may be right about it being not as useful as a legion soul, though.

**Comment by someoneunkown** [comment]
Trust me. I've tried using it in my hand. I've been a shaft miner and i've gotten this on more then 1 occasion, and I assure you, this does not work.

**Comment by Ratvar** [comment]
I think that necropilis chest heart is broken one and heals nothing. Replace it with working heart, dis it

**Comment by someoneunkown** [comment]
I hope this one will actually work. ty

**Comment by matskuman5** [comment]
The wizard heart works. You need to click your sprite with it, not use it in hand.

**Comment by Mrcreepssss** [comment]
why thefuck would anyone  want this? and what about getting stunned?

**Comment by Ratvar** [comment]
You missed, creeps

**Comment by Mrcreepssss** [comment]
yeah i know i'm late to the part, but the questions are still valid

**Comment by Ratvar** [comment]
why thefuck anyone would want universal heal without patches,chems? Hm, duuuunnooooooo. Whyy anyoone would waant freee spacewalk heaaart. It stacks with viruses, legion cores, chemicals, allows to sirvive medium bloodloses, et cetera-just press one button every six seconds or use macros for it, more passive regen is always good if you. The only minus is that you cannot use it stunned, and it deals gradual oxydamage in process if left unpumped, but oxydamage cannot give you bleedout  and goes away with every pump, tho, so you either die anyway or stand up cuffed/converted and pump it back. And, dunno where you saw part about getting stunned. And it will spam you chat if you will forget, so, cannot miss it. Annoying to use, yeah, but good
