### ISSUE TITLE
Return of the samurai

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#2444]
You can wear a fake katana on your belt which has its own sprite but not the actual one which i find kind of wierd. 

fix: allow the real katana to be worn on the belt

**Comment by Cruix** [comment]
The fake katana is a replica of the sword from the popular 2472 TV show, <I>Space Ninja Rangers</I>, and as such can be worn on your belt. The real katana does much more damage and must be worn on your back.
