### ISSUE TITLE
Detective's office since rebase lacks supplies

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#2446]
There's no paper pin +paper, though this is easily rectified. However, there is only one folder in the entire place and it's just in the suit case, no way to file cases really without them.

Having a miscellaneous crafting recipe for folders using paper might be cool.

**Comment by alexkar598** [comment]
You can create folders using cardboard which is either found in maint or made from folding empty boxes

**Comment by MegaEmpirical** [comment]
Good to know about the cardboard. Closing this out since a fix is incoming.

**Comment by MegaEmpirical** [comment]
Re-opening since the issue is now back again since the detective's got moved.
