### ISSUE TITLE
Lava rivers still going through ruins

### ISSUE THREAD

**Issue by MenacingManatee** [yogstation13/yogstation#2463]
![image](https://user-images.githubusercontent.com/26894750/29001151-567105b6-7a46-11e7-8220-e40ba4b74e01.png)

![image](https://user-images.githubusercontent.com/26894750/29001168-fcce4d2e-7a46-11e7-8e46-9697f664fd73.png)

I wasn't certain on this one if it was intended for the resin walls to be missing in spots
![image](https://user-images.githubusercontent.com/26894750/29001183-316f8a84-7a47-11e7-913f-d5a3c2610498.png)

**Comment by Qustinnus** [comment]
fixed in  https://github.com/yogstation13/yogstation/pull/2409

**Comment by MenacingManatee** [comment]
my fault, I checked the open PRs first but I mustve overlooked it. Is the other 2 intended?

**Comment by Zostroll** [comment]
The middle image with the pirate ruin is normal. It is meant have a lava moat. The xeno nest looks to be fucky though.

**Comment by 00aquir** [comment]
reference https://github.com/yogstation13/yogstation/issues/2388

**Comment by Cruix** [comment]
Leave a comment
