### ISSUE TITLE
Surgically extracting carded AI inside storage implant bugs AI.

### ISSUE THREAD

**Issue by Colburn3000** [yogstation13/Yogstation#2466]
[Round ID]: 142909

[Reproduction]: Card AI and place in a storage implant. Remove the AI by surgically extracting the storage implant. After extraction the AI intellicard will not be visible and the AI will receive the following messages as if it were depowered.

![image](https://user-images.githubusercontent.com/24303426/45158911-5e0d6a80-b1b3-11e8-8350-952005560d06.png)

The AI cannot use cameras or talk, as if it were actually depowered. 

[For Admins]: Calling "Get" on the AI causes the AI core (with AI inside though it should be carded) to appear at the requested location. This AI core cannot be made human, as one would expect, but it can be carded and placed back into the original station AI core to "fix" the AI.

**Comment by Colburn3000** [comment]
I was able to replicate this on the server.

<details>
  <summary>VV from the AI core. </summary>
 
(E) (C) (M) abilities = /list (0)
(E) (C) (M) acceleration = 1
(E) (C) (M) acted_explosions = null
(E) (C) (M) actions = /list (1)
1 [0x2109bd87] = Deploy to AI Shell /datum/action/innate/deploy_shell
(E) (C) (M) active_hand_index = 1
(E) (C) (M) active_storage = null
(E) (C) (M) active_timers = null
(E) (C) (M) add_overlays = null
(E) (C) (M) aicamera [0x202c622] = AI photo camera /obj/item/camera/siliconcam/ai_camera
(E) (C) (M) aiMulti [0x202c61f] = the multitool /obj/item/multitool
(E) (C) (M) aiPDA [0x202c61d] = O.P.U.S. (AI) /obj/item/pda/ai
(E) (C) (M) aiRestorePowerRoutine = 0
(E) (C) (M) alarms = /list (6)
Motion = /list (0)
Fire = /list (1)
Transfer Centre = /list (3)
1 [0x400004a] = Transfer Centre /area/security/execution/transfer
2 = null
3 = /list (1)
1 [0x20030b1] = the fire alarm /obj/machinery/firealarm
Atmosphere = /list (0)
Power = /list (0)
Camera = /list (0)
Burglar = /list (0)
(E) (C) (M) alarms_to_clear = /list (0)
(E) (C) (M) alarms_to_show = /list (0)
(E) (C) (M) alarm_types_clear = /list (5)
Motion = 0
Fire = 0
Atmosphere = 0
Power = 0
Camera = 0
(E) (C) (M) alarm_types_show = /list (5)
Motion = 0
Fire = 0
Atmosphere = 0
Power = 0
Camera = 0
(E) (C) (M) alerts = /list (0)
(E) (C) (M) all_eyes = /list (1)
1 [mob_517] = O.P.U.S. (AI Eye) /mob/camera/aiEye
(E) (C) (M) alpha = 255
(E) (C) (M) alternate_appearances = null
(E) (C) (M) alternate_screams = null
(E) (C) (M) anchored = 1
(E) (C) (M) animate_movement = 2
(E) (C) (M) apc_override = 0
(E) (C) (M) appearance = 
(E) (C) (M) appearance_flags = TILE_BOUND, PIXEL_SCALE
(E) (C) (M) article = null
(E) (C) (M) atom_colours = null
(E) (C) (M) a_intent = "harm"
(E) (C) (M) blend_mode = 0
(E) (C) (M) bloodcrawl = 0
(E) (C) (M) bloody_hands = 0
(E) (C) (M) blood_volume = 0
(E) (C) (M) bodytemperature = 310.15
(E) (C) (M) Bot = null
(E) (C) (M) bottom_left_corner = null
(E) (C) (M) bottom_right_corner = null
(E) (C) (M) bounds = "32,32"
(E) (C) (M) bound_height = 32
(E) (C) (M) bound_width = 32
(E) (C) (M) bound_x = 0
(E) (C) (M) bound_y = 0
(E) (C) (M) bruteloss = 0
(E) (C) (M) bubble_icon = "machine"
(E) (C) (M) buckled = null
(E) (C) (M) buckled_mobs = null
(E) (C) (M) buckle_lying = -1
(E) (C) (M) buckle_message_cooldown = 0
(E) (C) (M) buckle_prevents_pull = 0
(E) (C) (M) buckle_requires_restraints = 0
(E) (C) (M) buckling = null
(E) (C) (M) builtInCamera [0x202c623] = the security camera /obj/machinery/camera
(E) (C) (M) butcher_difficulty = 0
(E) (C) (M) butcher_results = null
(E) (C) (M) cached_multiplicative_slowdown = 2
(E) (C) (M) call_bot_cooldown = 0
(E) (C) (M) cameraFollow = null
(E) (C) (M) camera_light_on = 0
(E) (C) (M) CanAtmosPass = 1
(E) (C) (M) canmove = 0
(E) (C) (M) canSmoothWith = null
(E) (C) (M) can_be_carded = 1
(E) (C) (M) can_be_held = 0
(E) (C) (M) can_be_unanchored = 0
(E) (C) (M) can_buckle = 0
(E) (C) (M) can_dominate_mechs = 0
(E) (C) (M) can_shunt = 1
(E) (C) (M) chameleon_item_actions = null
(E) (C) (M) chnotify = 0
(E) (C) (M) ckey = "colburn3000"
(E) (C) (M) click_intercept = null
(E) (C) (M) client [0x5000007] = Colburn3000 /client
(E) (C) (M) client_colours = /list (0)
(E) (C) (M) client_mobs_in_contents = null
(E) (C) (M) cloneloss = 0
(E) (C) (M) color = null
(E) (C) (M) computer_id = "838595313"
(E) (C) (M) comp_lookup = /list (3)
atom_rad_probe [0x2109bd93] = /datum/component/rad_insulation
atom_rad_contam [0x2109bd93] = /datum/component/rad_insulation
movable_moved [0x2109bd8c] = /datum/component/footstep
(E) (C) (M) confused = 0
(E) (C) (M) connected_robots = /list (0)
(E) (C) (M) container_type = 
(E) (C) (M) contents = /list (6)
1 [0x202c61d] = O.P.U.S. (AI) /obj/item/pda/ai
2 [0x202c61f] = the multitool /obj/item/multitool
3 [0x202c620] = Integrated Subspace Transceiver /obj/item/radio/headset/ai
4 [0x202c622] = AI photo camera /obj/item/camera/siliconcam/ai_camera
5 [0x202c623] = the security camera /obj/machinery/camera
6 [0x202c625] = the proximity checker /obj/effect/abstract/proximity_checker
(E) (C) (M) controlled_mech = null
(E) (C) (M) control_disabled = 1
(E) (C) (M) control_object = null
(E) (C) (M) cooldown = 534431
(E) (C) (M) crit_threshold = 0
(E) (C) (M) cultslurring = 0
(E) (C) (M) current = null
(E) (C) (M) current_modules = /list (0)
(E) (C) (M) datum_components = /list (3)
/datum/component/rad_insulation [0x2109bd93] = /datum/component/rad_insulation
/datum/component = /list (2)
1 [0x2109bd93] = /datum/component/rad_insulation
2 [0x2109bd8c] = /datum/component/footstep
/datum/component/footstep [0x2109bd8c] = /datum/component/footstep
(E) (C) (M) datum_flags = DF_USE_TAG
(E) (C) (M) density = 1
(E) (C) (M) deployed_shell = null
(E) (C) (M) deploy_action [0x2109bd87] = Deploy to AI Shell /datum/action/innate/deploy_shell
(E) (C) (M) derpspeech = 0
(E) (C) (M) desc = null
(E) (C) (M) designation = ""
(E) (C) (M) devillawcheck = /list (5)
1 = null
2 = null
3 = null
4 = null
5 = null
(E) (C) (M) digitalcamo = 0
(E) (C) (M) digitaldisguise = null
(E) (C) (M) digitalinvis = 0
(E) (C) (M) dir = 2
(E) (C) (M) diseases = /list (0)
(E) (C) (M) disease_resistances = /list (0)
(E) (C) (M) dizziness = 0
(E) (C) (M) doomsday_device = null
(E) (C) (M) drowsyness = 0
(E) (C) (M) druggy = 0
(E) (C) (M) d_hud = 6
(E) (C) (M) explosion_block = 0
(E) (C) (M) explosive = 0
(E) (C) (M) eyeobj [mob_517] = O.P.U.S. (AI Eye) /mob/camera/aiEye
(E) (C) (M) eye_blind = 0
(E) (C) (M) eye_blurry = 0
(E) (C) (M) faction = /list (3)
1 = "neutral"
2 = "[mob_516]"
3 = "silicon"
(E) (C) (M) filters = O.P.U.S..filters
(E) (C) (M) filter_data = null
(E) (C) (M) fingerprintslast = null
(E) (C) (M) fireloss = 0
(E) (C) (M) fire_stacks = 0
(E) (C) (M) flags_1 = HEAR_1, INITIALIZED_1
(E) (C) (M) floating = 0
(E) (C) (M) focus [mob_516] = O.P.U.S. /mob/living/silicon/ai
(E) (C) (M) force_moving = null
(E) (C) (M) gc_destroyed = null
(E) (C) (M) gender = "neuter"
(E) (C) (M) glide_size = 8
(E) (C) (M) grab_state = 0
(E) (C) (M) group = /list (0)
(E) (C) (M) guaranteed_butcher_results = null
(E) (C) (M) hackedcheck = /list (1)
1 = null
(E) (C) (M) hack_software = 0
(E) (C) (M) hallucination = 0
(E) (C) (M) has_limbs = 0
(E) (C) (M) has_unlimited_silicon_privilege = 1
(E) (C) (M) health = 88
(E) (C) (M) held_items = /list (0)
(E) (C) (M) hellbound = 0
(E) (C) (M) holder = null
(E) (C) (M) holo_icon = /icon (/icon)
(E) (C) (M) hud_list = /list (4)
22 [0xd004c8b] = /image
8 [0xd004c8c] = /image
9 [0xd004c8d] = /image
14 [0xd004c8e] = /image
(E) (C) (M) hud_possible = /list (4)
1 = "22"
2 = "8"
3 = "9"
4 = "14"
(E) (C) (M) hud_type = /datum/hud/ai
(E) (C) (M) hud_used [0x2109bdb3] = /datum/hud/ai
(E) (C) (M) icon = /icon (icons/mob/ai.dmi)
(E) (C) (M) icon_state = "ai"
(E) (C) (M) implants = null
(E) (C) (M) incorporeal_move = 0
(E) (C) (M) inertia_dir = 0
(E) (C) (M) inertia_last_loc = null
(E) (C) (M) inertia_move_delay = 5
(E) (C) (M) inertia_moving = 0
(E) (C) (M) inertia_next_move = 58371.5
(E) (C) (M) infra_luminosity = 0
(E) (C) (M) initial_language_holder = /datum/language_holder/synthetic
(E) (C) (M) interaction_flags_atom = 
(E) (C) (M) interaction_range = 7
(E) (C) (M) invisibility = 0
(E) (C) (M) in_throw_mode = 0
(E) (C) (M) ioncheck = /list (1)
1 = null
(E) (C) (M) jitteriness = 0
(E) (C) (M) job = "AI"
(E) (C) (M) key = "colburn3000"
(E) (C) (M) language_holder = null
(E) (C) (M) LAssailant = null
(E) (C) (M) lastattacker = null
(E) (C) (M) lastattackerckey = null
(E) (C) (M) lastKnownIP = "128.163.239.56"
(E) (C) (M) last_announcement = ""
(E) (C) (M) last_bumped = 0
(E) (C) (M) last_high_pressure_movement_air_cycle = 0
(E) (C) (M) last_lawchange_announce = 51152.5
(E) (C) (M) last_move = null
(E) (C) (M) last_move_time = 0
(E) (C) (M) last_paper_seen = null
(E) (C) (M) last_played_vent = null
(E) (C) (M) last_special = 0
(E) (C) (M) last_taste_text = null
(E) (C) (M) last_taste_time = null
(E) (C) (M) last_words = null
(E) (C) (M) lawcheck = /list (1)
1 = null
(E) (C) (M) laws [0x2109bcee] = Unknown Laws /datum/ai_laws
(E) (C) (M) law_change_counter = 0
(E) (C) (M) law_history = /list (1)
1 = /list (4)
1 = "Uploaded by UNKNOWN/Innate laws at 01:18:11"
2 = "1: Serve the public trust."
3 = "2: Protect the innocent."
4 = "3: Uphold the law."
(E) (C) (M) layer = 4
(E) (C) (M) level = 2
(E) (C) (M) light = null
(E) (C) (M) lighting_alpha = 255
(E) (C) (M) light_color = null
(E) (C) (M) light_power = 1
(E) (C) (M) light_range = 0
(E) (C) (M) light_sources = null
(E) (C) (M) limb_destroyer = 0
(E) (C) (M) linked_core = null
(E) (C) (M) listed_turf = null
(E) (C) (M) lit_cameras = /list (0)
(E) (C) (M) loc [0x100654a] = the floor /turf/open/floor/plasteel
(E) (C) (M) locs = /list (1)
1 [0x100654a] = the floor /turf/open/floor/plasteel
(E) (C) (M) logging = /list (3)
2048 = /list (4)
1[15:30:02] Colburn3000/(AI) (AI Chamber (113, 128, 2)) = "Client Colburn3000/(AI) has taken ownership of mob AI"
2[15:30:02] Colburn3000/(AI) (AI Chamber (113, 128, 2)) = "AI name changed from to O.P.U.S."
3[15:30:36] *no key*/(O.P.U.S.) (CentCom Docks (178, 106, 1)) = "*no key*/(O.P.U.S.) is no longer owning mob O.P.U.S."
4[15:49:25] colburn3000/(O.P.U.S.) (CentCom Docks (176, 102, 1)) = "Client colburn3000/(O.P.U.S.) has taken ownership of mob O.P.U.S."
2 = /list (2)
1[15:49:28] colburn3000/(O.P.U.S.) (CentCom Docks (176, 102, 1)) = ""hmmm""
2[15:49:31] colburn3000/(O.P.U.S.) (CentCom Docks (176, 102, 1)) = ""BIG THONK""
8192 = /list (8)
1[15:49:47] colburn3000/(O.P.U.S.) (CentCom Docks (176, 102, 1)) = ""okay""
2[15:49:50] colburn3000/(O.P.U.S.) (CentCom Docks (176, 102, 1)) = ""if you orbit me""
3[15:50:01] colburn3000/(O.P.U.S.) (CentCom Docks (176, 102, 1)) = ""this is what you get when you get a mob that has been carded""
4[15:50:21] colburn3000/(O.P.U.S.) (CentCom Docks (176, 102, 1)) = ""and put in a storage implant""
5[15:50:25] colburn3000/(O.P.U.S.) (CentCom Docks (176, 102, 1)) = ""and surgically removed""
6[15:50:28] colburn3000/(O.P.U.S.) (CentCom Docks (176, 102, 1)) = ""nothing come out""
7[15:50:31] colburn3000/(O.P.U.S.) (CentCom Docks (176, 102, 1)) = ""then when you call get""
8[15:50:35] colburn3000/(O.P.U.S.) (CentCom Docks (176, 102, 1)) = ""you get a depowered core""
(E) (C) (M) losebreath = 0
(E) (C) (M) luminosity = 0
(E) (C) (M) lying = 0
(E) (C) (M) lying_prev = 0
(E) (C) (M) machine = null
(E) (C) (M) malfhack = null
(E) (C) (M) malfhacking = 0
(E) (C) (M) malf_cooldown = 0
(E) (C) (M) malf_picker = null
(E) (C) (M) managed_vis_overlays = null
(E) (C) (M) maptext = null
(E) (C) (M) maptext_height = 32
(E) (C) (M) maptext_width = 32
(E) (C) (M) maptext_x = 0
(E) (C) (M) maptext_y = 0
(E) (C) (M) master_multicam = null
(E) (C) (M) maxHealth = 100
(E) (C) (M) max_buckled_mobs = 1
(E) (C) (M) max_multicams = 6
(E) (C) (M) med_hud = 3
(E) (C) (M) metabolism_efficiency = 1
(E) (C) (M) mind [0x2109b81d] = O.P.U.S. /datum/mind
(E) (C) (M) mob_biotypes = /list (1)
1 = "robotic"
(E) (C) (M) mob_size = 3
(E) (C) (M) mob_spell_list = /list (0)
(E) (C) (M) mousemove_intercept_objects = null
(E) (C) (M) mouse_drag_pointer = 1
(E) (C) (M) mouse_drop_pointer = 1
(E) (C) (M) mouse_drop_zone = 0
(E) (C) (M) mouse_opacity = 1
(E) (C) (M) mouse_over_pointer = null
(E) (C) (M) movement_type = GROUND
(E) (C) (M) movespeed_modification = /list (1)
MOB_WALK_RUN = /list (3)
1 = 100
2 = 0
3 = 2
(E) (C) (M) move_on_shuttle = 1
(E) (C) (M) moving_diagonally = 0
(E) (C) (M) multicam_allowed = 1
(E) (C) (M) multicam_on = 0
(E) (C) (M) multicam_screens = /list (0)
(E) (C) (M) m_intent = "run"
(E) (C) (M) name = "O.P.U.S."
(E) (C) (M) name_archive = null
(E) (C) (M) network = /list (1)
1 = "ss13"
(E) (C) (M) next_click = 0
(E) (C) (M) next_mob_id = 563
(E) (C) (M) next_move = 1
(E) (C) (M) next_move_adjust = 0
(E) (C) (M) next_move_modifier = 1
(E) (C) (M) notransform = null
(E) (C) (M) now_pushing = null
(E) (C) (M) nuking = 0
(E) (C) (M) nutrition = 289
(E) (C) (M) observers = null
(E) (C) (M) on_fire = 0
(E) (C) (M) oobe_client [0x5000007] = Colburn3000 /client
(E) (C) (M) opacity = 0
(E) (C) (M) open_uis = /list (0)
(E) (C) (M) orbiters = null
(E) (C) (M) orbiting = null
(E) (C) (M) overeatduration = 0
(E) (C) (M) overlays = /list (0)
(E) (C) (M) override = 0
(E) (C) (M) ownedSoullinks = null
(E) (C) (M) oxyloss = 12
(E) (C) (M) parent = null
(E) (C) (M) parent_type = /mob/living/silicon
(E) (C) (M) pass_flags = 
(E) (C) (M) pipes_shown = /list (0)
(E) (C) (M) pixel_step_size = 8
(E) (C) (M) pixel_w = 0
(E) (C) (M) pixel_x = 0
(E) (C) (M) pixel_y = 0
(E) (C) (M) pixel_z = 0
(E) (C) (M) plane = -1
(E) (C) (M) possible_a_intents = /list (2)
1 = "help"
2 = "harm"
(E) (C) (M) pressure_resistance = 10
(E) (C) (M) priority_overlays = null
(E) (C) (M) progressbars = null
(E) (C) (M) proximity_monitor = null
(E) (C) (M) pulledby = null
(E) (C) (M) pulling = null
(E) (C) (M) radiation = 0
(E) (C) (M) radio [0x202c620] = Integrated Subspace Transceiver /obj/item/radio/headset/ai
(E) (C) (M) radiomod = ";"
(E) (C) (M) radio_enabled = 0
(E) (C) (M) ranged_ability = null
(E) (C) (M) reagents = null
(E) (C) (M) real_name = "O.P.U.S."
(E) (C) (M) redeploy_action [0x2109bd12] = Reconnect to shell /datum/action/innate/deploy_last_shell
(E) (C) (M) registered_z = 1
(E) (C) (M) remote_control = null
(E) (C) (M) remove_overlays = null
(E) (C) (M) requires_power = 1
(E) (C) (M) research_scanner = 0
(E) (C) (M) resize = 1
(E) (C) (M) resting = 0
(E) (C) (M) riding_datum = null
(E) (C) (M) roundstart_quirks = /list (0)
(E) (C) (M) sandbox = null
(E) (C) (M) satiety = 0
(E) (C) (M) screens = /list (2)
lighting_backdrop_lit [0x202c5fa] = /obj/screen/fullscreen/lighting_backdrop/lit
lighting_backdrop_unlit [0x202c5b1] = /obj/screen/fullscreen/lighting_backdrop/unlit
(E) (C) (M) screen_loc = null
(E) (C) (M) sec_hud = 1
(E) (C) (M) see_infrared = 0
(E) (C) (M) see_invisible = 25
(E) (C) (M) see_in_dark = 8
(E) (C) (M) see_override = 0
(E) (C) (M) selected_default_language = null
(E) (C) (M) sensors_on = 0
(E) (C) (M) sharedSoullinks = null
(E) (C) (M) shunted = 0
(E) (C) (M) sight = SEE_MOBS, SEE_OBJS, SEE_TURFS
(E) (C) (M) signal_enabled = 0
(E) (C) (M) signal_procs = null
(E) (C) (M) slurring = 0
(E) (C) (M) smoke_delay = 0
(E) (C) (M) smooth = 
(E) (C) (M) spacewalk = 0
(E) (C) (M) spark_system [0x2109b843] = /datum/effect_system/spark_spread
(E) (C) (M) sprint = 15
(E) (C) (M) staminaloss = 0
(E) (C) (M) stat = 0
(E) (C) (M) status_effects = null
(E) (C) (M) status_flags = 9
(E) (C) (M) status_traits = /list (0)
(E) (C) (M) step_size = 32
(E) (C) (M) step_x = 0
(E) (C) (M) step_y = 0
(E) (C) (M) stun_absorption = null
(E) (C) (M) stuttering = 0
(E) (C) (M) suffix = null
(E) (C) (M) suiciding = 0
(E) (C) (M) surgeries = /list (0)
(E) (C) (M) tag = "mob_516"
(E) (C) (M) text = "A"
(E) (C) (M) throwforce = 10
(E) (C) (M) throwing = null
(E) (C) (M) throw_range = 7
(E) (C) (M) throw_speed = 2
(E) (C) (M) timeofdeath = 0
(E) (C) (M) tod = null
(E) (C) (M) top_left_corner = null
(E) (C) (M) top_right_corner = null
(E) (C) (M) toxloss = 0
(E) (C) (M) track [0x2109bd86] = /datum/trackable
(E) (C) (M) tracking = 0
(E) (C) (M) transform [0x21001925] = /matrix
(E) (C) (M) type = /mob/living/silicon/ai
(E) (C) (M) underlays = /list (0)
(E) (C) (M) unique_name = 0
(E) (C) (M) updating = 0
(E) (C) (M) user_movement_hooks = null
(E) (C) (M) vars = /list (0)
(E) (C) (M) ventcrawler = 0
(E) (C) (M) ventcrawl_layer = 2
(E) (C) (M) verbs = /list (48)
1 = /mob/living/silicon/ai/proc/set_automatic_say_channel
2 = /mob/living/silicon/ai/proc/control_integrated_radio
3 = /mob/living/silicon/ai/proc/botcall
4 = /mob/living/silicon/ai/proc/ai_hologram_change
5 = /mob/living/silicon/ai/proc/ai_statuschange
6 = /mob/living/silicon/ai/proc/ai_network_change
7 = /mob/living/silicon/ai/proc/show_laws_verb
8 = /mob/living/silicon/ai/pick_icon
9 = /mob/living/silicon/ai/resist
10 = /mob/living/silicon/ai/cancel_camera
11 = /mob/living/silicon/ai/verb/toggle_acceleration
12 = /mob/living/silicon/ai/verb/announcement_help
13 = /mob/living/silicon/ai/verb/deploy_to_shell
14 = /mob/living/silicon/ai/verb/toggle_anchor
15 = /mob/living/silicon/ai/verb/pick_icon
16 = /mob/living/silicon/ai/verb/suicide
17 = /mob/living/silicon/ai/verb/cmd_toggle_pda_silent
18 = /mob/living/silicon/ai/verb/cmd_toggle_pda_receiver
19 = /mob/living/silicon/ai/verb/ai_camera_track
20 = /mob/living/cancel_camera
21 = /mob/living/pointed
22 = /mob/living/verb/resist
23 = /mob/living/verb/succumb
24 = /mob/living/verb/stop_pulling1
25 = /mob/living/verb/pulled
26 = /mob/living/verb/ghost
27 = /mob/verb/me_verb
28 = /mob/verb/whisper_verb
29 = /mob/verb/say_verb
30 = /mob/verb/a_intent_change
31 = /mob/verb/open_language_menu
32 = /mob/verb/southface
33 = /mob/verb/northface
34 = /mob/verb/westface
35 = /mob/verb/eastface
36 = /mob/verb/DisDblClick
37 = /mob/verb/DisClick
38 = /mob/verb/cancel_camera
39 = /mob/verb/abandon_mob
40 = /mob/verb/add_memory
41 = /mob/verb/memory
42 = /mob/verb/mode
43 = /mob/verb/pointed
44 = /mob/verb/examinate
45 = /mob/verb/quick_equip
46 = /mob/verb/pray
47 = /mob/verb/vote
48 = /mob/verb/button_pressed_F12
(E) (C) (M) verb_ask = "queries"
(E) (C) (M) verb_exclaim = "declares"
(E) (C) (M) verb_say = "states"
(E) (C) (M) verb_whisper = "whispers"
(E) (C) (M) verb_yell = "alarms"
(E) (C) (M) viewalerts = 0
(E) (C) (M) visibility = 1
(E) (C) (M) vis_contents = /list (0)
(E) (C) (M) vis_locs = /list (0)
(E) (C) (M) waypoint = null
(E) (C) (M) waypoint_mode = 0
(E) (C) (M) weak_reference [0x2109bc9d] = /datum/weakref
(E) (C) (M) weather_immunities = /list (1)
1 = "ash"
(E) (C) (M) wires = null
(E) (C) (M) x = 176
(E) (C) (M) y = 102
(E) (C) (M) z = 1
(E) (C) (M) zone_selected = null 


</details>

**Comment by alexkar598** [comment]
No longer an issue as far as i can tell
