### ISSUE TITLE
OOC is logged 3 times.

### ISSUE THREAD

**Issue by Jc1469** [yogstation13/yogstation#2468]
msg = pretty_filter(msg)

    log_ooc("[mob.name]/[key] : [msg]")

    var/raw_msg = msg

    msg = pretty_filter(msg)

    log_ooc("[mob.name]/[key] : [msg]")

    if((copytext(msg, 1, 2) in list(".",";",":","#")) || (findtext(lowertext(copytext(msg, 1, 5)), "say")))
        if(alert("Your message \"[raw_msg]\" looks like it was meant for in game communication, say it in OOC?", "Meant for OOC?", "No", "Yes") != "Yes")
            return

    log_ooc("[mob.name]/[key] : [raw_msg]")

`

**Comment by Mrcreepssss** [comment]
isn't : used  for emoticons?

**Comment by Jc1469** [comment]
Yes, but it's also used for comm channel shortcuts.  Point is, log_ooc is in there 3 times.

**Comment by Mrcreepssss** [comment]
i know it is, but it gets really annoying to have that message pop up everytime you try to use an emoticon.
