### ISSUE TITLE
Goliath in clown ruins

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#2481]
ouch!

![ss13-clownruins-bug](https://user-images.githubusercontent.com/16806055/45217783-a7d67d80-b2a5-11e8-86f6-f5c831ab5a89.png)

**Comment by MimicFaux** [comment]
Honk!

**Comment by 00aquir** [comment]
Btw how is it not a bug when you cannot move in the ruin while being stunned for quite a while by slipping on the floor and the goliath coming towards you and hitting you 6< times (entering the ruin, you start the whole thing being stunned! because of the floor.). It was clearly not intended this way, since the goliath spawned INSIDE the perimeters of the ruin.
