### ISSUE TITLE
bags now show everything you pick up and its annoying as hell

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#2501]
https://gyazo.com/4a4f79fed888444ece631c3c0e5e797a

i would rather not have that spam my chatbar

**Comment by Ratvar** [comment]
You make a sand pile!
You make a sand pile!
You make a sand pile!
You make a sand pile!
Same thing with squashing sand in hand to make bricks, cutting wood into planks-immensive spam
