### ISSUE TITLE
Voicechanger-NTMLscript interraction breaks the whole deal

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2520]
Well, NTML scripts magically see if anyone got mask on his face. Therefore, any attempt to use voice changer with ID will result in Magic Man (Unknown) instead of job, thus giving away the whole thing.

**Comment by Cruix** [comment]
Radios lookup your name on the crew manifest to determine what job you have. NTSL has nothing to do with it, except for showing everyone what normally only the AI sees. If you use an agent card to set your name to someone else's, it will show up as their job.

**Comment by Ratvar** [comment]
Nope. Telecomms build scripts revealing voicechangers many times, Cruix. Something is wrong.

**Comment by Cruix** [comment]
NTSL scripts reveal that someone not on the crew manifest is speaking over the radio - it will appear exactly the same if a lavaland prisoner or admin-spawned human talks over the radio. Your ID's job name is not sent to the script or radio machinery in any way, in-universe or in code, so it makes perfect sense that voice changers would work like this.

**Comment by ToGWtF** [comment]
I know a certain persons script that catches if a player is trying to impersonate another person's name  :^)

**Comment by Cruix** [comment]
Please supply the script so that we can do something about that.
