### ISSUE TITLE
Atropine mix bug

### ISSUE THREAD

**Issue by Rayisken** [yogstation13/Yogstation#2526]
[Round ID]: # multiple
[Round ID]: # 
[Round ID]: # 

[Reproduction]: # mixing atropine in this order using a 100u beaker:
Add 10u Carbon, Hydrogen, Welding Fuel
Remove 10u
Add 10u Chlorine, Water, Welding Fuel, Oxygen

***Add 5u Nitrogen
Add 15u Hydrogen, Ethanol***
^^^^^^^^^^^^
this is where it seems to bug out mixing in different orders here seems to cause it less 
Remove 30u
Add 20u Ethanol, Sulphuric Acid

results in this 90% of the time

95 Atropine
1u Diethyl, Ethanol,  Sulphuric Acid, Phenol, Acetone

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA I FIXED THIS BEFORE REBASE

**Comment by Rayisken** [comment]
forgot the diethyl can mess up as well at that step and you end up with 10u oil 20u diethyl as well

**Comment by alexkar598** [comment]
Cannot replicate
