### ISSUE TITLE
Medibots are bork and are overdosing people

### ISSUE THREAD

**Issue by Assblasters** [yogstation13/yogstation#2543]
Basically, I was a tator shaft miner, things lead to things as I was permad, then a spontaneous perma escape has happened, leading to me getting a shitton of oxygen damage and pressure damage. after getting to arrivals, there was, who knew, a medibot. i ran towards it as it began injecting me, but soon enough, i noticed that i was getting overdosed, leading to even more oxyloss and injections, in a minute, i was dead
https://prnt.sc/ghutn7
having a quick talk with a council member, they told me that it was a bug and that i should report it, and so i did

**Comment by drderp3635** [comment]
Its because some dumbass put tricord in a medibot. You can't OD on the default chem but if you put in your own shit there is a possibility. Not a bug, but a fault of whoever loaded it with tricord

**Comment by ShadowDeath6** [comment]
medibot injects tricord ingredients, medibot can inject 15u of each ingredient which results in 45u tricord, which overdoses you.
