### ISSUE TITLE
cannot stab someone eyes-they are "concealed", always

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2563]
Apply sharp thing to eye of your foe:
1:no head protection/glasses/wierd race - check
2:eye is being stabbed out - fail
Neither you can remove eye organs, not sure ya is supposed
But first part should work
Reported it to adam, 2m ago, i think, and other coders, and they forgot after swearing inbetween each other about "whoms brokkned it"

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I think its because it was too easy to kill someone by gouging their eyes, as it took only a couple hits with a screwdriver to blind and stun

**Comment by Ratvar** [comment]
Why it wasn't removed properly and got such bandage fix, tho.

**Comment by Dagdammit** [comment]
Yeah this sounds bad.

**Comment by Jc1469** [comment]
This might've been broken for a while, since actual race effects were coded.   All races are meant to have differing resistance to eye gouging.
