### ISSUE TITLE
New mob idea for lavaland

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation#258]
A new NPC mob that I thought would be a cool addition to lavaland fauna.

**Marrow Weaver**
An oversized Sub-race of space Arachnids native to Lavaland it has Opal Black Chitin with glowing laval cracks running throughout its abdomen. It produces its own light source and is relatively easy to spot when not covered in Marrow Web.

**Weaver Durability**
Weavers themselves Are relatively easy to kill alone, should take 5 KA shots per weaver encouraging miners to finish them off as soon as possible and making them priority targets when encountered with other fauna.

**The Mobs AI and how it behaves**
It would be just about as big as a goliath, the catch is that it literally weaves webs of bone marrow which instantly harden. Instead of catching prey, its webs act as makeshift barricades that can be broken for bones. It will cast a certain amount of marrow webs around its general area wherever it goes, it will only aggro if its webs are attacked or run into. Upon being aggro'd it beelines quickly towards its target, does minimal brute damage but injects a venom that does steady stamina damage and if enough venom is injected it will stamina crit the target into unconsciousness. Once its prey is in stamina crit the Weaver sits ontop of them and will quickly weave them into a marrow cocoon. 

While in this cocoon you are still alive, albeit unconscious from the venom, if not removed from the cocoon after 5 minutes you will die and 3-6 weaver spawn will hatch from your corpse. Weaver spawn do similar damage to legion skulls but die in one hit, they are more aggressive than the adult Weavers but do not have any developed venom sacs. The stamina crit will likely only keep you down for half a minute giving you enough ample time to scream for help on radio in the hopes someone comes to rescue you, unless they fall victim to the Weaver/s

**A Different Spawner**
Could also do with an alternative tendril type, similar to the Ash Walkers have a Weaver Nest that is a tendril covered in small round egg clusters with strips of marrow web stretching off the tendril. Unlike normal tendrils the Weaver tendril can be exhausted of its spawns stopping it from spawning anything again, Maybe doesnt even drop a chest? (Could use discussion regarding that), but drops some special similar to how the ash walker nest drops an anomaly core.

**Butcher Remains**
1 Weaver Venom Sac
3 Sinew
1 Bone
5 Weaver Chitin

**Tribal additions**
Along with being a reliable source of bones for Ash Walkers the Venom sac could be applied to sharp weapons such as spears, axes, knives and daggers. Upon hitting a Carbon mob with the spear the first hit will deal a considerable amount of stamina damage along with the brute, the venom effect will then wear off on the weapon. Additionally it could cause the first hit against a fauna to deal double its normal damage, making the venom sac very valuable to Ash Walkers.

**Armor additions**

**Chitin Mail**
Weaver Chitin can be crafted into a jumpsuit type uniform from the tribal menu, it offers miner protection similar to that of the security jumpsuit. Crafted from 2 Weaver Chitin and 1 sinew, meaning 1 weaver supplies enough for 2 jumpsuits with an additional sinew.

**Chitin Gauntlets**
Crafted using 1 Weaver chitin and bone bracers, you reinforce the bone bracers with the chitin giving them more of an armor boost and they now cover your wrists AND your hands.

**Rigid Shield**
Made from 2 Weaver Chitin and 1 bone, blocks 3 melee attacks before breaking.

**Chitin Glaive**
Crafted from 1 Chitin and 2 sinew this weapon when thrown at a carbon mob has a high embed chance and does decent throw damage.

I did up a sprite to show what it would look like, I went with only 4 legs being visible because its bulkier than normal spiders so adding more than four causes a lot of the detail to get cut out from the legs overlapping the Spiders sprite.

**Marrow Weaver Sprites**
![](http://puu.sh/pOFkU/a9995f6f6b.png)

**Death Sprite**
http://puu.sh/pOU7V/ff2b54a5e5.png

**Venom Sac**
![](http://puu.sh/pOVKN/5f0d1a7312.png)

**Chitin mail**
Went with a less armored design, its not really mail, but it looks more tribal this way. Got the inspiration from the heart Protectors from kenshi.
![](http://puu.sh/pONzo/7f6d77a3ce.png)

**Chiten Gauntlets**
Made the gauntlets look really intimidating with the back spikes sticking out from the wrist.
![](http://puu.sh/pOR0v/75fd852563.png)

**Comment by GrayRachnid** [comment]
Dropping bones from the webs they deploy is OP as fuck.

Also, 3 bones and 2 sinew for something easier to kill than both the watcher and goliath with a KA? Hell naw.

**Comment by Stealthkibbler** [comment]
Yeah, changed drops, reworded to 5 KA shots, thing is most mobs are usually easy to kill on their own anyway, Watcher the only one being a problem since it retaliates every shot with a freeze beam. Also added in some unique craftables to spice up the tribal menu, at the moment is pretty dull we could really use some cool new stuff to craft.

Most mobs have some use for miners, goliaths their plates, watchers their diamonds, Legions their souls. Also Legions are literally a free full heal and they die in 2 KA shots, however in a group they are very deadly. As would this mob considering the stamina venom could get stacked onto the same target.

I made this in mind that Miners only ever use bones for skull helmets and sometimes bracers which they get really fast regardless and then bones become useless. Bones are only ever a necessity for Ash Walkers, Prisoners dont have the O2 in their tanks to survive on lavaland for long and the golems cant even wear most the craftables. Seed vault people cant ever leave the vault without someone giving them an O2 tank.

Simply put miners will still find it a threat, its fast, it inflicts stamina damage fairly quickly so you need to focus it down and it can imprison them if they let it get the better of them.

As it stands right now all of the monster drops are used for tribal crafting which is mostly for Ash Walkers, ash walkers need to be taken into huge consideration since you dont want to make the mob too hard for them, at the same time upping the rewards is good. You also have to factor in that these drops aren't for one player, they will be shared among the tribe and even during a 1-2 hr long round ash walkers will only ever amount to 2 bone armors at most without ever getting a complete armor set. This is pretty worrying since they can also lose it to megafauna gibbing, falling into chasms, getting pushed or walking into lava/knocked out of a boat.

**Comment by ShadowDeath6** [comment]
make weavers playable tbh

**Comment by Stealthkibbler** [comment]
As a player controlled character they would be absurd, just like normal spiders.

**Comment by ShadowDeath6** [comment]
good

**Comment by Stealthkibbler** [comment]
@ShadowDeath6 By that I mean they should not be player controlled, it's like letting a player control a goliath, they're going to end up being bored by running around trying to find a carbon mob to fuck with and even then they will probably just rush the mining station. Most monsters that fuck over players easily bring them back into the round, like Xenos or Normal Space Spiders; Maybe when lavaland budget gets raised and we dont end up with rounds where the world gen wastes all the budget on seed vaults and only spawns like 4 tendrils it would be viable to have ghosts jump in as a fauna role.

But as it stands at the moment with Lavaland, we're better off introducing NPC Fauna with unique materials, craftables and loot to add more variety, challenge and exploration to the experience.

**Comment by Stealthkibbler** [comment]
I did up a sprite to show what it would look like, I went with only 4 legs being visible because its bulkier than normal spiders so adding more than four causes a lot of the detail to get cut out from the legs overlapping the Spiders sprite.

http://puu.sh/pOCfc/ba33e2b45f.png
http://puu.sh/pOCjJ/31967edb27.png

**Comment by Cruix** [comment]
:+1: great sprite

**Comment by Stealthkibbler** [comment]
Went with a less armored design, its not really mail, but it looks more tribal this way. Got the inspiration from the heart Protectors from kenshi.

Chitin mail
http://puu.sh/pONzo/7f6d77a3ce.png

**Comment by ShadowDeath6** [comment]
bad idea
