### ISSUE TITLE
Silicons cannot see blood cult runes.

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#2586]
I was just playing a borg and had to have runes pointed out to me. Additionally, the AI could not see them through me either. These runes were in plain sight and I walked past them repeatedly and was not aware they existed until a human was using me as a camera and saw them through me.

**Comment by wwtall1** [comment]
..i swear ive seen bloodcult runes as an ai. Might be a recent PR managed to break it?

**Comment by MegaEmpirical** [comment]
I have seen them but I suspect a reason issue.

**Comment by Ratvar** [comment]
feature this when
