### ISSUE TITLE
Charter needs an admin approve system

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation#259]
Our BYOND hub name was changed to a rule-breaking one for an extended duration of time due to no admins being online when this happened.
It's currently removed but it would be ideal if this asks online admins for confirmation, as the approve link system does.
If none are online, it should default to rejecting it, unlike the /tg/ one.

**Comment by fizzle7** [comment]
Gray linked this, seems like a good idea and still gives you some control with no admins.

**Comment by george99g** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/12787230/16545359/93ab2a0a-4131-11e6-955d-a7d5b780be46.png)


> If none are online, it should default to rejecting it, unlike the /tg/ one.

> unlike the /tg/ one.

I have told you this countless times in coder chat. The /tg/ one does **not** work for our purposes.

**Comment by fizzle7** [comment]
How does it not work?

**Comment by george99g** [comment]
> How does it not work? Oh right, just change autoapprove to autodismiss, it's like 2 seconds.

Then why don't you do it when it's so easy?

**Comment by FluffySurvivor** [comment]
fun removal tag now

**Comment by fizzle7** [comment]
Im saying, if someone ports it, they can switch it to not allow it after 60 seconds.
