### ISSUE TITLE
Syndie/nukeop template spawns with agent card and has no access to shutters leading to nuke shuttle from their base.

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2592]
Well:
Use syndie spawner as admund on nuke base, the one in red rig pinpointer et cetera
Get no access to shutters that lead to shuttle
Emag your way out
 Fix pls

**Comment by Cruix** [comment]
This is deliberate so that only the syndicate commander can open the shutters.

**Comment by Ratvar** [comment]
No shutters on syndiepods, still can fly on it if you use your TC, then. And emagging still works. SO, if it was delebirate-it does nothing
