### ISSUE TITLE
You can spoop admins by changing the arrival message

### ISSUE THREAD

**Issue by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [yogstation13/yogstation#2599]
![image](https://user-images.githubusercontent.com/16842348/30521839-a93dca08-9bc6-11e7-8671-46a08cf93c10.png)

**Comment by Kmc2000** [comment]
LOL

**Comment by Super3222** [comment]
XD

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
You could do some pretty funny stuff with it:
![image](https://user-images.githubusercontent.com/16842348/30524533-d10e1040-9bf5-11e7-99a0-70c16e2a9571.png)
In any case, it was fixed in #2600
