### ISSUE TITLE
Spears don't go through riot shields?

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#261]
> be ashwalker
> attack a miner with a buckler
> he's invincible
> throw spears at him
> he either dodges shitty throwcode or dies

I thought that spears were intended to be throwable through shields AND melee'able? It makes ashwalker a lot harder when miners pick up a wooden shield and are magically immune to any and all melee you have.

**Comment by Super3222** [comment]
NOSHIELD flag was removed ever since we rebased. That's as much as I can get to you from looking into the code and noticing it's loss.

**Comment by Super3222** [comment]
NOSHIELD was removed ever since we rebased. That's as much as I can get to you from looking into the code and noticing it's loss.

**Comment by ShadowDeath6** [comment]
bring back noshield pls

**Comment by X-TheDark** [comment]
Yeah, they removed NOSHIELD and instead gave 100 armour penetration to the items*

(* SIKE! Of course they didn't, in removing NOSHIELD, they arbitrarily nerfed single eswords to pen 50% armour, spears pen 10%, scythes pen like 20%, etc...and since we have the all-melee-attack-block-thing, this kind of sucks)

**Comment by KorPhaeron** [comment]
NOSHIELD had nothing to do with armour though

Esword was buffed to 50 armour pen from 0 (which is by the way enough to still 100% bypass riot shields).

**Comment by X-TheDark** [comment]
Why remove it though, that was two "armour penetration systems" : one for shields, one for actual armour? Armour penetration is now universal, something I think NOSHIELD was really useful for.

**Comment by KorPhaeron** [comment]
Don't think so
