### ISSUE TITLE
MULEbot Crate Dragging Bug

### ISSUE THREAD

**Issue by JupiterFive** [yogstation13/yogstation#264]
[Note]: The bug is that if you drag a crate onto a MULEbot while dragging it and pull away, it duplicates it and they both share variables.# (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: The bug can be easily recreated.# (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by GrayRachnid** [comment]
@Super3222 seems like a similar problem to what I encountered.

**Comment by Super3222** [comment]
I'll look into this soon.
