### ISSUE TITLE
Glowcaps growing on lava

### ISSUE THREAD

**Issue by Sharkeybtm** [yogstation13/yogstation#2648]
Playing as a plant person from the Seed ship. Planted glowcaps outside and they proceeded to grow on lava.

**Comment by nazitra** [comment]
I don't see the problem here, seems realistic.

**Comment by Sharkeybtm** [comment]
Yes. Electric mushrooms growing on molten rock that burns with the fires of hell is perfectly normal. I must have had a moment. Carry on.
