### ISSUE TITLE
Bucklers dont break

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation#266]
If you wield a buckler from the Honk Render Tomb ruin tile set it respectively blocks melee attacks completely, however unlike the changeling shield it doesnt ever break, meaning just carrying one makes you immune to most the fauna on lavaland.

**Comment by fizzle7** [comment]
Actually, a golem wore one vs a colossus and it broke.

**Comment by X-TheDark** [comment]
It's a subtype of riot shield, so it blocks any melee attack that does less than 25 damage.

**Comment by Stealthkibbler** [comment]
@X-TheDark Thats a pretty high damage value for immunity, not even dual wielded spears can bypass it or the Bone axe. Would be better if it was lowered to just block a set amount of hits before it broke, considering that finding one means you've found the other 12 of them.

**Comment by EMT321** [comment]
@Stealthkibbler @Cruix This has been tested, and confirmed by later PR's to no longer be the case WRT shields.

Can this be closed?
