### ISSUE TITLE
Bananium sword doesn't do anything, and doesn't slip

### ISSUE THREAD

**Issue by Moja10** [yogstation13/Yogstation#2667]
[Round ID]: # 18691

[Reproduction]: use bananium sword, it doesn't do anything, clown ops round ruined because of it!!!

Shows up in logs:
2[18:51:13] *no key*/(Allyson Knapp) (CentCom Recovery Ship (196, 83, 1))
has been attacked by YogurtShrimp69/(Moja Manley) with bananium sword[DC] (INTENT: HARM) (DAMTYPE: BRUTE) (NEWHP: 100) 

But nothing happens. Fix!!!

**Comment by MimicFaux** [comment]
Also worth noting. Clown Op reinforcements show up naked with no bomb implant or antag status (with which to use syndie gear), further hurting the round.

**Comment by ThatLing** [comment]
Clown ops is deprecated and I have no clue why it's even enabled.

**Comment by MimicFaux** [comment]
because even with the bugs, it's still fun.

**Comment by Altoids1** [comment]
Fixed by #3464, closing.
