### ISSUE TITLE
Changelings can loose their roundstart genes and still be transformed into them

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2676]
it's fully preventable by transmitting genomes into airwaves, but it's just a hussle of clicking two buttons every time you transform.
Can you protrct roundstart genes and genes of target, like?

**Comment by ShadowDeath6** [comment]
genomes of target are already protected

as for your roundstart genomes, they have no real reason to be protected since it's lore-wise just another disguise or whatever
