### ISSUE TITLE
Aghosting while playing as a blob overmind will not allow you to return to play

### ISSUE THREAD

**Issue by Partheo** [yogstation13/yogstation#2690]
![image](https://user-images.githubusercontent.com/10659549/31581249-a35ddbfe-b134-11e7-9601-d933374d259a.png)

**Comment by Cruix** [comment]
It detects that there is no one playing the blob and replaces you, this is intended

**Comment by Partheo** [comment]
Alright, understood. As far as I could tell though, no-one replaced the blob. Are we sure that works?

**Comment by Cruix** [comment]
As far as I know it has never failed to replace someone who disconnected for a fraction of a second before reconnecting, ruining their bi-yearly blob round.

**Comment by nichlas0010** [comment]
well as far as I can tell, it always fails to do so

I've had plenty of blobs who've lost connection, and then had to wait 5 or 10 minutes waiting for them to come back before replacing them manually, so it seems like it doesn't work
