### ISSUE TITLE
RDM

### ISSUE THREAD

**Issue by subwaysplatter** [yogstation13/yogstation#2695]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
every time i play a player named nicholas daigle kills me for no reason ( this is in ss13 btw) i would like the player to be banned if at all possible because he rdms and bullies me

**Comment by X-TheDark** [comment]
If you have a player complaint, please submit it here https://forums.yogstation.net/index.php?forums/player-complaints.3/

GitHub Issues are not for resolving administrative issues.

**Comment by ShadowDeath6** [comment]
underrated
