### ISSUE TITLE
Lizard People

### ISSUE THREAD

**Issue by WardenOfSecrets** [yogstation13/yogstation#2704]
[Note]: # It seems lizard people take more stamina damage than normal people. Not sure if this was intentional or not. It can be proven if you use a disabler or boxing gloves on them and then attempt to use them on a human. It takes much less to fatigue a lizard person.

[Admins]: # I could recreate the bug if it is one. I never contacted an admin about it.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
It's intentional, they take more stamina damage and regenerate it very slowly
