### ISSUE TITLE
Examining an ID will now show you everything the associated player is holding

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#2712]
Exactly as the name says, even if the ID is just on the floor.

**Comment by MegaEmpirical** [comment]
Seems to only work if the player is not wearing their PDA. If the PDA is off, you get this instead:


That's Antimony LI's ID Card (Atmospheric Technician)
A card used to provide ID and determine access across the station.
It is a tiny item.
The registered account belongs to 'Antimony LI' and reports a balance of $400.
The Engineering Budget reports a balance of $13097.
Use your ID in-hand to pull money from your account in the form of cash.
You can insert cash into your account by smashing the money against the ID.
If you lose this ID card, you can reclaim your account by using a blank ID card inhand and punching in the account ID.

**Comment by MegaEmpirical** [comment]
It will also show their currently physical state, like bleeding and such.

**Comment by MegaEmpirical** [comment]
This has since been fixed.

**Comment by MegaEmpirical** [comment]
Nevermind, it still does this if the PDA is slotted in the ID slot while the ID is elsewhere. Also, examining your ID while it is in your ID slot examines you too.

**Comment by MegaEmpirical** [comment]
Does not show amount in the account either.

**Comment by alexkar598** [comment]
Cannot replicate on master

**Comment by MegaEmpirical** [comment]
I tested it, appears to have been resolved. Was around for a while, glad it's gone.
