### ISSUE TITLE
Can we remove the ability to summon an infinite amount of ratvars?

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#272]
I mean, I understand the meme about having a spare gate somewhere else. However that is a bit OP.

And if we're keeping the meme of having spare gates, atleast make it so that there can only be 1 ratvar on the map, and once there's a ratvar you can't build any more gates.

No fun yeah yeah but the noise is unbearable.

**Comment by timkoster1** [comment]
Feature

**Comment by Super3222** [comment]
Not a feature. There is only one Rat'Var just like there is only one Nair'Se.

**Comment by timkoster1** [comment]
But it's funny as fuck
;_;
