### ISSUE TITLE
borg stuff

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#2736]
Smile Screen has two floating lights in front of it

Borg Charge meter does not display on the HUD

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Can't reproduce either
![image](https://user-images.githubusercontent.com/16842348/32127332-5b886e7e-bb76-11e7-96a0-3ecae8162b97.png)

**Comment by ShadowDeath6** [comment]
![asdiasjkd](https://user-images.githubusercontent.com/17034893/32131496-1cbde170-bb75-11e7-96de-4ce02eb5560b.PNG)


might be an issue on my side then
