### ISSUE TITLE
Plasmamen are immune to radiation but not SM hallucinations

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#2736]
Unsure if this is intended or not but seems odd since they're immune to radiation.

**Comment by Lostlarry** [comment]
well as i understand it SM doesnt do only radiation since you can get SM halucinations by looking at it without proper eye protection. I interpret that as two separate effects not couse and result

**Comment by MegaEmpirical** [comment]
I was going to say that the hallucinations are not from looking at the SM since they're from being near it but given that the means of stopping it is eyewear, fair enough. I'll close this out.
