### ISSUE TITLE
ion laws on server are using old ion_laws.json file with new ion_storm.dm file

### ISSUE THREAD

**Issue by Dagdammit** [yogstation13/yogstation#2740]
https://gyazo.com/bed95a8fd9d75500a1986ab1e00cb2ec
From a test a few rounds back by admins. The prompts ending in "MUST" are supposed to then have an item from the [ionverbs] category, but the old ion_law.json file only has an [ionverb] category. Meanwhile, madlib items like NOT SAYING HELLO WHEN YOU SPEAK are not found in the new ion_law.json that #2655 should have created.

**Comment by Time-Green** [comment]
It needs to be manually done by someone with host acces

**Comment by X-TheDark** [comment]
Should be fixed now.
