### ISSUE TITLE
pAI DNA Request Bug

### ISSUE THREAD

**Issue by Amzahr** [yogstation13/yogstation#2742]
Often during rounds where I play as an observer I take up pAI when requested. When activated, I always request a DNA sample from the person holding me, however when given the DNA sample it tells me the DNA does not match my master's DNA, even though when listed in my directives tab that I am not synced with any master. This issue only appears to happen when I request a DNA sample and not when given a DNA sample when downloaded. I've been on Yogstation since around early or mid-August 2017 and this has been an issue that can happened on numerous occasions.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
it's most likely because you are trying to match your holder's DNA to an empty DNA and these obviously aren't equal so it says they don't match

**Comment by Amzahr** [comment]
I actually never thought about it that way, I was under the assumption that it would take the DNA from the user if no one was registered and sync you to that person. I've been playing that person who still my master even if no one is present since I thought it was a bug. Though if this is the case it just seems like a lot of people don't realize you need to assign DNA to the pAI.
