### ISSUE TITLE
Chem Dispenser Issue

### ISSUE THREAD

**Issue by Amzahr** [yogstation13/yogstation#2743]
So, while trying to mix up to 100 units of chemicals, I got a strange issue with the chem dispenser.

I've have only had this issue today and have been able to replicate this issue in a private session. 

For example:
Salicyclic acid needs 1 part Sodium,1 part Phenol, 1 part Carbon, 1 part Oxygen, 1 part Sulfuric Acid. When added in the last 20 units of Sulfuric acid the chem dispenser doesn't add up the last 5 units even though though it should.

![](https://i.gyazo.com/d96f6e596b3979f587ddfe048a60a156.png)

![](https://i.gyazo.com/e08a8f594ac8b6146dfae40e7d2a9746.png)

I believe this issue is caused by the chemical dispenser believing there is more chemicals in the dispenser than there really is and is possibly also related to the amount of chemicals trying to be mixed at once but also it might be an issue with previous chemical mixtures (Such as phenol having to be added before hand) I haven't has issues with mixtures such as 100 units of Kelotane or Styptic Powder (which use only the base chemicals in the dispenser). However I am not sure if this is the case also because I have no problem with 100 units of Silver Sulfadiazine(requires ammonia to be mixed) either.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Could not reproduce:
![image](https://user-images.githubusercontent.com/16842348/32137890-d30d908e-bc28-11e7-8ee0-3eea6f3a24ce.png)
![image](https://user-images.githubusercontent.com/16842348/32137892-d6e06844-bc28-11e7-9ba1-fed4a97c332a.png)

**Comment by Amzahr** [comment]
Not sure what path you took, but this is what I did to get to the result I had. 
5 Welding Fuel + 5 Carbon + 5 Hydrogen + 15 Water + 15 Chlorine – 25 units + 20 Sodium + 20 Oxygen + 20 Sulfuric Acid + 20 Carbon
I've also found that adding 20 units to a beaker is also in the same result for me.
(such as adding 20 units of phenol from another beaker)

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
OK, following the path you posted leads to this bug. Couldn't reproduce the adding 20 units one though.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Do you use the "-X" button while mixing silver sulfadiazine?

**Comment by Amzahr** [comment]
Yeah, when making Silver Sulfadiazine I use 
30 Hydrogen + 10 Nitrogen – 10 units + 20 Silver + 20 Sulfur + 20 Oxygen + 20 Chlorine

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
So in the end it was caused by ending up with something like 0.99998 units of phenol in the beaker, which got rounded away in the chem dispenser but not in the reaction code
