### ISSUE TITLE
AI medical overlay didn't work

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#2764]
Medical overlay worked at some point in the round 12753 but around the end, even after turning it off and on and a client restart, did not work and never displayed health after that, security and diagnostic huds worked fine. At the middle of the round the client crashed because it couldn't process the medical crew monitoring with 60 players.

**Comment by Cruix** [comment]
The AI's medhud only works on people who have their suit sensors on.

**Comment by 00aquir** [comment]
Ah. Meanwhile I remembered another example where the actual medical HUDglasses didn't work, but it was long time ago: https://github.com/yogstation13/yogstation-old/issues/632
