### ISSUE TITLE
Monkeys can't open or use backpacks, only wear them

### ISSUE THREAD

**Issue by zxmongoose** [yogstation13/Yogstation#2768]
Issue reported from  Round ID: 18833 (Yogstation 13)

Reporting client version: 512

Tested myself after I got an ahelp reporting this. Player controlled monkeys are able to put backpacks on, but not open them to retrieve contents. They CAN, however, place objects INTO backpacks. Clicking a worn backpack as a monkey automatically places it in-hand, skipping the drag-and-drop normally needed.

**Comment by MegaEmpirical** [comment]
This has been the case since rebase but you can get stuff from a backpack, you have to drag the backpack onto your person or open it in hand. It's annoying but does work. Still, would love for the way backpacks normally work to be added.

**Comment by zxmongoose** [comment]
I tried opening it in hand and it just moved it into my other hand

**Comment by MegaEmpirical** [comment]
I may have been mistaken about that but I do know that dragging the backpack to you will work, unless it has changed recently.

**Comment by Altoids1** [comment]
Still a bug; a workaround is to drop your bag on the floor and drag-click to get the backpack menu

**Comment by MegaEmpirical** [comment]
Dragging it from the backpack spot should also work I think. As well as from hand.
