### ISSUE TITLE
Useless Role Rework (I.E Rework Clerk and Curator)

### ISSUE THREAD

**Issue by Smudged** [yogstation13/Yogstation#2787]
Well these idea's stem from Tammy over on the discord we got

Clerk Rework

- Removes Locker room cosmetic vendors from the locker room

- Makes the Clerks Room have the cosmetic vendors instead to sell outfits as he/she pleases

- Clerk can order Refill Crates from Cargo (Maybe from a machine) and starts with a crate with a few refills at round start 

Curator Rework

- Display cases start empty

- Has a bounty list to fill the cases

- Whenever a bounty is fulfilled, he/she get's payed

- Adds Mining Access to the Curator, his bounties come from items from Lavaland 

My only concern is that there'll be alot of same looking Assistants if a clerk isn't there, and if assistants can't find money. Also, Curator's fighting/killing miners for loot found on lavaland.

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.
