### ISSUE TITLE
man this sucks

### ISSUE THREAD

**Issue by HelmutScheiss** [yogstation13/Yogstation#2789]
Issue reported from  Round ID: 18853 (Yogstation 13)

Reporting client version: 512

![image](https://user-images.githubusercontent.com/35412402/46329171-c8120780-c5d9-11e8-9071-2560a1fbb9c2.png)

alright so i downloaded the new byond update and the the game is just unplayable, literally. I load into the game and I cant do anything, its just a still image of when I arrive. If I try to re-connect it's just a black screen, as shown by the screenshot. I have no clue on what to do.

**Comment by ThatLing** [comment]
Revert to 1448

**Comment by Altoids1** [comment]
I'm pretty sure this was all some BYOND thing that has since been rectified. Closing.
