### ISSUE TITLE
Plasmamen clowns don't get a clown mask

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#2795]
Exactly as title, this is a travesty.

**Comment by MegaEmpirical** [comment]
Possibly true for plasmamen mimes too.

**Comment by Smudged** [comment]
They ought to get a plasmaman clown helmet, we need. . . sprites

**Comment by MegaEmpirical** [comment]
That could be pretty cool.

**Comment by Altoids1** [comment]
Probably fixed in that new plasmamen uniform PR.

**Comment by MegaEmpirical** [comment]
I'm pretty sure it's not since TG has plasmaman clowns disabled but I'll test.

**Comment by MegaEmpirical** [comment]
Not resolved.
