### ISSUE TITLE
Horror absorbs can break shit badly

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#2797]
Absorbing lots of people consecutively with horrer form makes it so that you can't transform into anyone, use extract sting, absorb normally, and make you stuck as a monkey if you lesser form/headslug

**Comment by Ratvar** [comment]
You sure you didn't absorb husks/monkeys/people DNA of which you already had? Cause it's already being fixed

**Comment by drderp3635** [comment]
I was absorbing intact human corpses of which i had yet to extract sting. also which pr are you referencing when you say that it is being fixed

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/2758 might be fixing this

horrorform can't use normal changeling abilities while transformed if that's what your issue is

**Comment by drderp3635** [comment]
No its after you revert from horrer form after devouring a lot of corpses.
