### ISSUE TITLE
ashwalker's shouldnt be able to use mechs

### ISSUE THREAD

**Issue by awsmnamedude** [yogstation13/Yogstation#2799]
There I was just a normal non tator miner coming back from an ashstorm when I notice there is a ripely docked. I step inside to see who is inside it, and just as I notice a window is broken, the ripely springs to life and starts drilling me. Im pinned between ash storm and a rogue ripely and lose the fight. Then the pilot steps out and its a goddamn lizard in full stolen miner gear. If ashwalkers are going to be allowed to murderbone, how Is it not for me to just murder anyone else I come across in lavaland in fear they may be a disguised ashwalker. especially crewman lizardpeople. but in this case I couldnt even tell their name, race, etc because they were in an exosuit. primitive ashwalkers shouldnt be able to pilot mechs like that because you cant tell who is inside. It would be bwoinkable/bannable if I were to just kill anyone with a mech or any lizard and it happened to be a crewmate, but the ashwalkers can freely disguise themselves and murderbone?

**Comment by MimicFaux** [comment]
sounds like an IC issue to me, a DNA lock solves the problem outright, ashwalkers already disguise themselves (as miners) for surprise takedowns, and it sounds like your death was purely bad luck to have your back to an ashstorm.

**Comment by Smudged** [comment]
I think this brings up a good issue, considering normal ashwalkers barely know how to use a computer screen (In the past) 
I'm not sure they should be this smart, and this could mean we should add the ashwalker leader back in.

**Comment by Ratvar** [comment]
"Hey dude say a word in human voice if ur ashwalker voice I pewpew u"
Anyone can freely disguise themselves and many antags can do murderbone-like things.
Ashwalkers got digidrate legs, can't change their voice, can't use miner guns
Ask them to say a thing if their face is concealed somehow

Yeah, this sounds like IC issue, ashwalkers using equipmet or not. After all, antag could drill you in ripley juuuust as well and you wouldn't be able to check at all.

**Comment by Firewolf34** [comment]
I disagree. I think the whole point of the ashwalkers is not that they're just a free-antag, but a primitive tribe of lizard-people. So they shouldn't be able to operate technical equipment much less a Mech. The controls for a mech would be insanely complicated, and a lizard that spent it's life living in primitive conditions on a lavaland that doesn't even speak Common wouldn't have a damn clue how to use one / shouldn't be able to by default.
