### ISSUE TITLE
M-90 carbine

### ISSUE THREAD

**Issue by someoneunkown** [yogstation13/yogstation#2800]
I at least believe that is the weapon. It takes 5.56x40mm ammo. Kindly take this weapon off the roster of the syndicate weapons for the time being until the issue with it is fixed. Apparently, it can't be reloaded

**Comment by nichlas0010** [comment]
it uses 5.56mm ammo. If you buy the 5.56mm toploader magazine whose description says it's for the m-90 you can reload it fine, but if you buy the 5.56x45mm ammo which says it's for the l6, then yeah, you can't load it in. Issue with the operatives themselves, not the game.

**Comment by someoneunkown** [comment]
An admin told me otherwise, so that's why i assumed.

**Comment by nichlas0010** [comment]
said admin was wrong
