### ISSUE TITLE
Kinetic Accelerator leave bullet holes

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#2822]
So nearly every single rock you mine leaves a bullet hole on the floor....

**Comment by Koffheatalt** [comment]
https://github.com/yogstation13/yogstation/commit/66d7fe69b935d0b9be0474843e7611d90a35a4ea
Not sure how they normally get deleted but this is how they are made. (I think?)

**Comment by Zostroll** [comment]
@nichlas0010 are you gonna fix this? You added bullet holes.
