### ISSUE TITLE
Invisible objects and players

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#2825]
Objects and even players(!) (in which case you can only spot them if you have sec/med hud) can turn invisible, although rarely, after a while for unknown reason. I even saw only (vertical-) half of a table sprite displayed to me, or only the airlock bolt lights showing up on a tile. This can happen even after the server initiates several redownloads across span of many weeks.

Here, there IS a closed door for sec maint and you can't see it until you bump into it.

![ss13-bug-invisibleobjects](https://user-images.githubusercontent.com/16806055/46403948-26d3a000-c704-11e8-9714-f0d85d115d83.png)

**Comment by ThatLing** [comment]
Probably a BYOND issue
