### ISSUE TITLE
Xenobio-made ashwalker dies in ashstorm

### ISSUE THREAD

**Issue by DiscordWizard** [yogstation13/yogstation#2826]
[Note]: I became an ashwalker using the xenobiology slimes to make the ashwalker potion, and decided to go mining and hunting since I could survive as one. I was a traitor lizard person scientist before that, and while I was hunting stuff as an ashwalker, an ashstorm happened. I thought that, being an ashwalker, I wouldn't get even harmed, but I started to take damage and ended up dead. I was told this was a bug, so I'm reporting it here.

[Admins]:

**Comment by ShadowDeath6** [comment]
just make it apply the weather resistances upon race gain or something

if it doesn't do that already then it's an easy fix

**Comment by Koffheatalt** [comment]
Pretty sure you need to add 
H.weather_immunities |= "ash"
 to
"/datum/species/lizard/ashwalker
	name = "Ash Walker"
	id = "lizard"
	specflags = list(MUTCOLORS,EYECOLOR,LIPS,NOGUNS,NOMACHINERY)
safe_oxygen_min = 5"

**Comment by Cruix** [comment]
It would have to go in the on_species_gain(), because it goes on the mob, not the species.

**Comment by Koffheatalt** [comment]
like this?
/datum/species/lizard/ashwalker/on_species_gain(mob/living/carbon/C, datum/species/old_species)
	. = ..()
        C.weather_immunities |= "ash"

Also I think this bug exists because C.weather_immunities |= "ash" is only assigned on spawn and not on switching.

/obj/effect/mob_spawn/human/ash_walker/special(mob/living/new_spawn)
	new_spawn.real_name = random_unique_lizard_name(gender)
	if(in_tribe)
		to_chat(new_spawn, "<b>Drag the corpses of men and beasts to your nest. It will absorb them to create more of your kind. Glory to the Necropolis, and her chosen son: The Chieftain!</b>")
		new_spawn <<"<b>The chieftain will have a special HUD over their head. Remember to show utmost respect.</b>"
	if(ishuman(new_spawn))
		var/mob/living/carbon/human/H = new_spawn
		H.underwear = "Nude"
		H.update_body()
		H.languages_spoken = ASHWALKER
		H.languages_understood = ASHWALKER
		H.weather_immunities |= "ash"

**Comment by Koffheatalt** [comment]
then again I could be wrong

**Comment by Cruix** [comment]
That is exactly right.

**Comment by Koffheatalt** [comment]
Would you need to add something like
/datum/species/lizard/ashwalker/on_species_loss(mob/living/carbon/C)
	. = ..()
	C.weather_immunities -= "ash"
or would that be unnecessary?

**Comment by Cruix** [comment]
That would be.smart, there is nothing that works like that right now.
