### ISSUE TITLE
Port NTSL

### ISSUE THREAD

**Issue by ThatLing** [yogstation13/Yogstation#284]
This is just a reminder that I wish to port over NTSL in the future. If you're looking to do the same thing, contact me please so we don't do redundant work.

**Comment by DLCabbose** [comment]
@Altoids-kun

**Comment by Amelia0010** [comment]
Also, might I suggest making it a global script, rather than a server-based script? One can always just use $freq to distinguish which channel you're on

**Comment by ThatLing** [comment]
@nichlas0010 I have some stuff planned for NTSL after it's ported.

**Comment by yellowface7** [comment]
I would like to note that I am currently working on bringing back NTSL along with revamping the Signal Technician.

**Comment by Altoids1** [comment]
💋
