### ISSUE TITLE
I figured out a way to Duplicate robot parts infinity 

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#2841]
Due to the nature of this bug I won't post how it is achieved but if you are a trustworthy coder and you want to fix this pm me on dicord for more info.

**Comment by Zostroll** [comment]
Just a added note I am banned on the yogs forum for reasons unknown so I can't be pinged you will need to pm me.

**Comment by Koffheatalt** [comment]
What do you mean with "duplicate robot parts"?

**Comment by Zostroll** [comment]
I can use the same set of cheast, head, arms and legs parts on as many endoskeletons as I want reducing the metal cost of a complete endoskeleton from 100000 metal to 15000

**Comment by joshencounter** [comment]
Sure, what's your discord ID?
