### ISSUE TITLE
Please change ticket logs slightly

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#2842]
I forgot how beautiful they looked before rebase instead of the ADMINPRIVATE thing. Also there are more than just ticket I believe that show with ADMINPRIVATE so this would make it easier searching for just ticket logs.

Please make them like this again:
[05:00:45]ADMIN: Ticket # 6: ckey ->ckey - message

(no space between # and 6 - it linked a pr and that scared me so I spaced it here)

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.
