### ISSUE TITLE
Please make tickets show in chat when unclaimed

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#2844]
Before rebase they appeared in chat as something like "Ticket 5 is unclaimed!" in red text with a bwoink noise. I'm not sure on how often they did this when unclaimed (I think every 30 seconds or a minute from what I can remember). There's been a few incidents recently with admins reconnecting or joining late without realising there is an open unclaimed ticket.

**Comment by MegaEmpirical** [comment]
It also used to show the number of resolved tickets in the status pane for all players, it was nice seeing how many were left but this part is super minor and not particularly useful.
