### ISSUE TITLE
Please restore Ash Drakes as they were... This is horrible.

### ISSUE THREAD

**Issue by toranet2** [yogstation13/Yogstation#2845]
https://github.com/yogstation13/Yogstation-TG/pull/2722
  Please make it back... the change made easiest boss into a mix of bubblegum and colossus on steroids... It can teleport on top of you just like bubblegum when you step on blood without bood, it can deny areas like blood for bubblegum but randomly and with Lava, and he also shoots shotgun flames that are much harder to dodge with fireballs in them of all things which makes it worse then colossus... Oh and dont forget he is now as fast as bubblegum on last stage right off the bat...

**Comment by MegaEmpirical** [comment]
This may help you: https://github.com/yogstation13/Yogstation-TG/pull/2837

**Comment by ThatLing** [comment]
Closing this since #2837 was merged
