### ISSUE TITLE
Return shaft miner body cameras

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#2846]
Would love to see this returned, don't forget the console too.

**Comment by Smudged** [comment]
This would be great, along with Partheo's sprites too.

**Comment by MegaEmpirical** [comment]
Which sprites?

**Comment by Smudged** [comment]
The little body camera sprite that partheo made.

**Comment by MegaEmpirical** [comment]
Ah, I see. I loved finding antag miners as a mining medic. So often a forgotten feature. How I miss it so.

**Comment by Firewolf34** [comment]
On a similar note: why is box stations mining medic area so underequipped? Not even a crew monitor console in there anymore. It's like a closet and a medpack and that's it. If you ask me, it should be better equipped. Basic sleeper, defib, at the least.

**Comment by MegaEmpirical** [comment]
Delayed response: Yeah, would love to see that updated too. I miss doing all the mining medic stuff, haven't been rolling it since rebase.

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.

**Comment by MegaEmpirical** [comment]
Bastards.
