### ISSUE TITLE
New atmos is completely shielded against radstorms.

### ISSUE THREAD

**Issue by Moja10** [yogstation13/yogstation#2851]
Something about the new atmos means that radstorms doesn't affect any of it. During a round, a radstorm hit, and rather than being coated in that delicious green radiation, it was completely shielded, like it's a maint tunnel. 

Should be easy to reproduce, just spawn a rad storm and see how it's not affected.

**Comment by Partheo** [comment]
Thanks for posting this- I'll make a PR that fixes this ASAP.

**Comment by Partheo** [comment]
![image](https://user-images.githubusercontent.com/10659549/34091021-fc96261e-e388-11e7-8906-b8864a120b3b.png)
Just tried to reproduce this now. Radstorm seems to work fine. Are you sure about this?

**Comment by nichlas0010** [comment]
![image](https://user-images.githubusercontent.com/20558591/34735611-55b0e6a0-f570-11e7-8f1a-b9aecc384e0c.png)
