### ISSUE TITLE
Head revs that are created midround spawn with a broken converter

### ISSUE THREAD

**Issue by Enkaaa** [yogstation13/yogstation#2855]
Had this happen to me before, had this happen to someone else just now. When made into a head revolutionary in the middle of the round, the suspicious device generated for you doesn't work. Can be somewhat worked around by making a new one with with the electronic flashbulb hijacker.

Should be easy to recreate, I think. Just acquire head rev mid-round and try to flash someone with the suspicious device spawned in for you.

**Comment by ThatLing** [comment]
Might be fixed by #2856
