### ISSUE TITLE
Fix the surgery guide that is given to abductors.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#2858]
It's wrong.

**Comment by Koffheatalt** [comment]
What's wrong with this? details?

**Comment by Ratvar** [comment]
Wrong steps written, trying to operate hurts abductees this way - guide on TG wiki Abductor page is right

**Comment by joshencounter** [comment]
Yup, makes for an incredibly confusing first abductor round. I found out first hand.
