### ISSUE TITLE
You can meatspike people from any distance for as long as you started doing so

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/yogstation#2862]
"They did it by grabbing somone and tossing them on the spike apparantly as long as you aggressive grab and start the spiking, it doesn't matter how far they run off"
To reproduce:
Doublegrab someone and click meatspike
Someone runs off 
Someone is teleported onto meatspike

**Comment by Ratvar** [comment]
Haw2fix:
"There's probably a check missing then
It should check if the target is next to you at the end of the action. If not, then it would cancel."

**Comment by ThatLing** [comment]
There's also a bug where you can get off a meatspike somehow without your sprite rotating back to it's original position, which makes it look like you are walking on your head.

**Comment by Ratvar** [comment]
shhhhhhhhh
