### ISSUE TITLE
Removes one singular pixel on lizards. (Remove Beepis) 

### ISSUE THREAD

**Issue by Smudged** [yogstation13/yogstation#2872]
Removes one pixel that sticks out of jumpsuits on Male(male) lizards. 
The one sticking Pixel.
![pixel](https://user-images.githubusercontent.com/12579846/34316880-3e89a4e6-e75e-11e7-8f58-8d7afd32a9ee.png)
Nekid
![one pixel lewd close](https://user-images.githubusercontent.com/12579846/34316882-4df9f034-e75e-11e7-9a4d-b1eb2586cc88.png)

TG's Beepis removal technique
![beepis gone](https://user-images.githubusercontent.com/12579846/34316883-5a0284f4-e75e-11e7-83ae-f7945559d8ce.png)

**Comment by Smudged** [comment]
(Can be also called: NT sterilizes lizards PR)

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
good PR

**Comment by ToGWtF** [comment]
the dreaded dixel
