### ISSUE TITLE
Language Feature.

### ISSUE THREAD

**Issue by Smudged** [yogstation13/Yogstation#2880]
- Adds an option and (Maybe a point system) To remove and add languages. 

- Adds in a translator for your ear, that you get when you choose the option NOT to be able to understand or speak Common that will translate Common from the radio channel, and from nearby spoken mobs also speaking common.

**Comment by MegaEmpirical** [comment]
We clearly need a plasmaman language.

**Comment by Smudged** [comment]
That could be do able, there'd need to be sprite work done for the symbols in the languages sooo, that's another hurdle to jump

And how to make it so people can communicate without just using Me" 
I'm still at a loss of how to do it and not make it TOO snow flaky, but that's the stretch (And this might be too MUCH of a snowflake feature) but it's an idea in the air.

**Comment by MegaEmpirical** [comment]
You went deeper than I was intending. I meant like most other languages where it's just out threw a filter. Plasmaman lore suggests they're not super good about using vowels.

**Comment by Smudged** [comment]
Oh, sort of like the lisp for lizards?
That would be interesting to add something like that to Plasmamemes

**Comment by MegaEmpirical** [comment]
Not the lisp but a language like the lizards have. From the language menu.

**Comment by Smudged** [comment]
Oh yeah, I worded it strangely, yeah, I shouldn't have said Sprites for the whole language. 

Just sprites like how Lizards have the little yellow dragon to indicate that, that's lizard language, or the Syndicate "S" for code speak, a draft might be needed to be made about what plasmamen language will be, maybe a little purple gas sprite for them.

**Comment by MegaEmpirical** [comment]
Yeah, that too. Not too much work. Could be a little plasmaman helmet or purple skull.

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.
