### ISSUE TITLE
So... stocks seem still to be unlinked from the cargo order console. When they shouldn't be.

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/Yogstation#2881]
[Round ID]:  yeah

[The bug] Now it seems to be linked with the bounty one

[Reproduction]: Do stocks thing in cargo, this wyrd thing happens

**Comment by ThatLing** [comment]
I have no idea what you mean, care to elaborate?

**Comment by ktstudios2000** [comment]
The stock market is no longer linked to the cargo console. For example, you could make several hundred thousand on the stock market, but it won't transfer over to the cargo console for use. It's effectively become a minigame.
