### ISSUE TITLE
Becoming a hulk breaks sleeping carp

### ISSUE THREAD

**Issue by FMGIV** [yogstation13/yogstation#2886]
You cant deflect projectiles after becoming a hulk
____________________________________________________________________________________________
You have learned the ancient martial art of the Sleeping Carp! Your hand-to-hand combat has become much more effective, and you are now able to deflect any projectiles directed toward you. However, you are also unable to use any ranged weaponry. You can learn more about your newfound art by using the Recall Teachings verb in the Sleeping Carp tab.
The mysterious scroll lights up in fire and quickly burns to ash.
NTP #LL-0400 fires the instakill rifle!
You deflect the projectile!
You drop your the ratvarian spear while deflecting the projectile!
NTP #LL-0400 fires the instakill rifle!
NTP #LL-0400 fires the instakill rifle!
You deflect the projectile!
NTP #LL-0400 fires the instakill rifle!
You deflect the projectile!
NTP #LL-0400 fires the instakill rifle!
NTP #LL-0400 fires the instakill rifle!
Devon Hastings has thrown the ratvarian spear.
John Grayson fires the hybrid taser!
NTP #LL-0400 is hit by an electrode in the head!
John Grayson fires the hybrid taser!
Devon Hastings has thrown the ratvarian spear.
You deflect the projectile!
OOC: TastyCrabLegs: GG from you local PDA terrorist
The APLU "Firefighter" (Dingus) squeezes NTP #LL-0400.
OOC: BananaJack: ya but a pai?
The APLU "Firefighter" (Dingus) squeezes NTP #LL-0400.
Devon Hastings has thrown the ratvarian spear.
John Grayson has been hit by the ratvarian spear.
The ratvarian spear cracks in two and fades away!
The APLU "Firefighter" (Dingus) squeezes John Grayson.
Devon Hastings kicks NTP #LL-0400!
The APLU "Firefighter" (Dingus) squeezes John Grayson.
Devon Hastings chops NTP #LL-0400!
Devon Hastings kicks NTP #LL-0400!
Your muscles hurt!
Devon Hastings gibbers, "PUNY HUMANS!!!!"
The APLU "Firefighter" (Dingus) squeezes Devon Hastings.
Devon Hastings smashes the table!
Devon Hastings gibbers, "HNNNNNNNNNGGGGGGH!!!!!!"
John Grayson fires the laser gun!
Devon Hastings is hit by a laser in the head!
NTP #LL-0400 fires the instakill rifle!
APLU "Firefighter" (Dingus) is hit by the instagib laser.
The APLU "Firefighter" (Dingus) lifts the hybrid taser and starts to load it into cargo compartment.
APLU "Firefighter" (Dingus) is hit by the instagib laser.
NTP #LL-0400 fires the instakill rifle!
John Grayson fires the laser gun!
Devon Hastings is hit by a laser in the head!
________________________________________________________________

**Comment by Time-Green** [comment]
You can’t be a karate hulk, you’d literally be a god

**Comment by Koffheatalt** [comment]
you could still be killed by melee weapons but it would be really unfair yes

**Comment by Ratvar** [comment]
Intended, I think. Maybe it should flash big rad words HULK CAN'T CARP or something

**Comment by AlpacaGoesCrazy** [comment]
The other question, can you reflect projectiles after you dehulk?

**Comment by AdamElTablawy** [comment]
Yes, alpaca
