### ISSUE TITLE
Paintball gun issues.

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#2890]
The paintball gun leaves casings, bullet holes and also sets off welder tanks to explode when it hits them.

**Comment by Ratvar** [comment]
where are the issues here?

**Comment by Kmc2000** [comment]
I don't actually see a problem here, this is working as intended?

You think bullets just magically disappear? no some poor sod has to clean up the damned things.

And if a fuel tank was hit by a speeding pellet of plastic, would that not set it off when striking it once with a lit welder can?

Check your facts dawg.

**Comment by Zostroll** [comment]
Paintball pellets are not bullets. They do not come in a brass casing and are sent out by a primer detonation causing the gun power to go off which then causes a build up of pressure behind the bullet sending it flying. They are propelled by little canisters of compressed air. THEY ARE NOT GUNS THEY DO NOT LEAVE CASINGS. I will admit that when they strike a surface they do leave a little bit of a plastic left from the plastic that surrounds the paint but it doesn't make sense for casing to spill out onto the floor where you fire it.  
Those little pellets have about as much energy as if say you threw a crowbar at someone's face so either make throwing crowbars at a welding tank set it off or them blowing up welding tanks is retarded. 
What paintballs do you use that leave bullets holes?

**Comment by Spider4062** [comment]
PAINTBALL STAINS DONT WASH OFF

**Comment by Zostroll** [comment]
@Kmc2000 You gonna fix this stuff?

**Comment by Tummywumbes** [comment]
ive never been able to figure out how to wash off paintball stains, i dont think you even can.

**Comment by Alexandria404** [comment]
PAINTBALL STAINS DONT WASH OFF
