### ISSUE TITLE
Hotkey (tab) mode delay

### ISSUE THREAD

**Issue by Spider4062** [yogstation13/yogstation#2891]
**_Ever since the update on the 27th of December I have noticed that when pressing tab to switch from hotkey mode to normal, there is a slight delay before the text box opens or closes._**

This is problematic because like me, and other players, we play in both hotkey mode (movement with wasd, r to throw, x to switch, z to activate...) and normal mode (say, me, and cancel-camera-view...). Now with the slight delay it makes the game kind of unplayable, and one of the reasons why I regularly play on yog is because it is a server that doesn't have this issue, until recently.

I hope this is relatively easy to fix, it's kind of an annoying issue. x

**Comment by morrowwolf** [comment]
I have also been experiencing this and it is quite annoying.  It might be from the azerty thing but iunno.

**Comment by Time-Green** [comment]
It’s definitely from azerty. It makes it go through a bunch of shit first, before deciding what to do
If this wont get fixed, we should just revert it

**Comment by ThatLing** [comment]
I'll try to look for a way to do it without delay.
