### ISSUE TITLE
Security records photo doesn't match the person.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#2892]
The person on the photo, checked on security HUD, had blue hair instead of green. The photo (this is ascertained) showed not the real thing, but what was currently visible in the character settings tab / body, when it was set to "random" before.

**Comment by ThatLing** [comment]
Are you sure they didn't change their appearance?

**Comment by 00aquir** [comment]
The person was me, that's why it was "ascertained" because I could look at the game preferences.. the hairstyle was not mine either, but what was on the character settings page with the random body setting.

**Comment by 00aquir** [comment]
Like this, unchanged person (me).

![pasted image 0](https://user-images.githubusercontent.com/16806055/54927516-963b8700-4f12-11e9-9974-7b7bea91d91c.png)
