### ISSUE TITLE
space texture while inside brain

### ISSUE THREAD

**Issue by Tummywumbes** [yogstation13/yogstation#2893]
when your brain is removed from your body, you can still possess it. while possessing your own brain, the texture for space appears lighter than how it normally would. the texture for outside the emergency shuttle while its moving also appears brighter and has a choppier animation.

when inside brain:
![image](https://user-images.githubusercontent.com/34947832/34446833-85ccc722-ecac-11e7-8b94-24464dc1b081.png)

normal:
![image](https://user-images.githubusercontent.com/34947832/34446845-9286990c-ecac-11e7-8122-df5b149079e4.png)

**Comment by Time-Green** [comment]
Same with ghosts, it uses the old space instead.

**Comment by AsV9** [comment]
It's not really something that's worth putting effort into considering this is very minor.
