### ISSUE TITLE
Free soul stone.

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#2895]
With the new PR that sends you to old mine if you keep trying to do it for about 15ish minutes you get sent to old mine and there is a purple soul stone like a 2 minute walk away just lying there for you to take Every Single Round.

**Comment by Zostroll** [comment]
@Time-Green

**Comment by Time-Green** [comment]
Yeah?

**Comment by Zostroll** [comment]
You added the old mine are you gonna fix getting a soul stone 15 minutes into the round every round?

**Comment by Time-Green** [comment]
It’s not a bug
Also if you spam the shuttle for that long, that’s just sad

Asv9 is changing it anyway, don’t wanna cause major conflicts
