### ISSUE TITLE
Refunding discounted syndi items gives you the full value refund

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#2895]
I refunded a 63% off assault borg (23 tc from the regular 65)..... I got 65 back. It was glorious.

**Comment by ThatLing** [comment]
How do you even refund?

**Comment by MegaEmpirical** [comment]
It's only for specific items, namely ones that require a ghost, so a borg or holoparasite. Those items are refundable by just having it in hand and clicking on the uplink.
