### ISSUE TITLE
Bluespace Rped

### ISSUE THREAD

**Issue by DarkRiper** [yogstation13/yogstation#2903]
Alright so its not that big of an issue, but a fieuw days ago I was doing RnD upgrading the machines when I dragged a Bluespace Rped on another bluespace Rped while they where on the ground. the result was that it shot a blue beam from my caracter to the other Rped. And I guess thats it, not a real pressing issue.

**Comment by drderp3635** [comment]
Intended feature

**Comment by Time-Green** [comment]
The rapid part exhanging device rapidly exchanged parts with another rapid part exchange device
Thats a feature now

**Comment by AsV9** [comment]
FEEEATURE
