### ISSUE TITLE
Tearing cloth from clown garment causes sends player to error zone

### ISSUE THREAD

**Issue by Colburn3000** [yogstation13/Yogstation#2908]
[Round ID]:18964

Basically what the title says. Tearing cloth from the clown's jumpsuit turns the screen black and sends you to the error zone. See the attached picture.

![cloth tear bad](https://user-images.githubusercontent.com/24303426/46585261-ac28be80-ca3c-11e8-9cb0-765b6c883e18.jpg)

**Comment by MegaEmpirical** [comment]
This is clearly a feature.

**Comment by ThatLing** [comment]
@morrowwolf 👏
