### ISSUE TITLE
HoP's hat and certain hairstyles

### ISSUE THREAD

**Issue by Megatome** [yogstation13/Yogstation#2910]
...create a line where the hair is cut off and you can see the skin beneath. Specifically, this happens to the HoP's hat and the Over Eye hairstyle, creating an awkward sprite glitch when viewed from the side.
![untitled](https://user-images.githubusercontent.com/32689904/46587048-f5850800-ca54-11e8-8b44-cf0e8f71f084.png)

**Comment by Bawhoppen** [comment]
Upstream issue https://github.com/tgstation/tgstation/issues/30433
