### ISSUE TITLE
Nuke disk in two places at once.

### ISSUE THREAD

**Issue by xjosephx** [yogstation13/Yogstation#2928]
[Round ID]: 19002

Ate a rock had the nuke disk, he dropped it and i picked it up and placed it in my backpack, later the hop came to me to ask me to help him get the disk out of his left pocket, he said he couldn't click it so i used the menu to take it out of his pocket myself, then the disk which was previously in my backpack(and the hop's pocket) was on the floor.
 I'm not sure how to reproduce this,

**Comment by Altoids1** [comment]
Cursed, old, and cannot be replicated. Closing.
