### ISSUE TITLE
North/East/West Facing Colossus Sprites

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#2928]
Here ya go:
![colossus](https://user-images.githubusercontent.com/18729830/34816211-e0e6a336-f679-11e7-90db-3e01944e01da.png)
[96x96megafauna.zip](https://github.com/yogstation13/yogstation/files/1621834/96x96megafauna.zip)

**Comment by Time-Green** [comment]
WEW THANKS

**Comment by Time-Green** [comment]
I'll get on it if no one beats me to it

**Comment by Time-Green** [comment]
Now I need to see a THICC collosus

**Comment by Drakkon** [comment]
We already have Bubblegum's. We appeal to all.

**Comment by Time-Green** [comment]
@Drakkon https://github.com/yogstation13/yogstation/pull/2931
