### ISSUE TITLE
I broke NTSL AND I DON'T KNOW WHY

### ISSUE THREAD

**Issue by Altoids1** [yogstation13/yogstation#2942]
https://github.com/yogstation13/yogstation/pull/2814/files

Apparently my rewrite of a particular part of Scanner.dm has caused NTSL to stop being able to compile correctly. It seems that the pointer it uses to parse through the original code text gets into weird places, resulting in random, nonsensical errors about unknown tokens or unterminated strings.

Looking at the PR, you might say "Aaahh yes, I see. In my wise coder wisdom I notice that you have twochars be created using only one character, not the two required for this to work, causing it to ignore comments."

So I fixed that and recompiled, and it still didn't work.

So you might say "Yes, young Padawan, you must not remove var/commenting from this list, for ye know not what it does."

So I added it back again, recompiled, and it still didn't work.

So you might say "Heed these words newcoder, for I am all-knowing: Reduce ye function to its purest form, and rid thyself of anything suspicious or bug-inducing."

Fine, here is the new version of proc/ReadComment()
```
		ReadComment()
			// Remember that we still have that $codepos "pointer" variable to use.
			var/longeur = lentext(code) // So I don't call for code's length every while loop
			if(copytext(code, codepos, codepos+2) == "//") // If line comment
				while(++codepos>longeur)
					if(copytext(code, codepos, codepos+1) == "\n") // then stop on the newline
						return
			else
				while(++codepos>longeur) // If long comment
					if(copytext(code, codepos, codepos+2) == "*/") // then stop on any */ 's'
						return
				//Else if the longcomment didn't end, do an error
				errors+=new/scriptError/UnterminatedComment()
```
And it's now called like this:
```
		for(, src.codepos<=lentext(code), src.codepos++)

			var/char=copytext(code, codepos, codepos+1)
			var/twochar=copytext(code, codepos, codepos+2) // For finding comment syntax
			if(char=="\n")
				line++
				linepos=codepos

			if(ignore.Find(char))
				continue
			else if(twochar == "//" || twochar == "/*")
				ReadComment()
			else if(end_stmt.Find(char))
				tokens+=new /token/end(char, line, COL)
			else if(string_delim.Find(char))
				codepos++ //skip string delimiter
				tokens+=ReadString(char)
			else if(options.CanStartID(char))
				tokens+=ReadWord()
			else if(options.IsDigit(char))
				tokens+=ReadNumber()
			else if(options.symbols.Find(char))
				tokens+=ReadSymbol()
```

And, guess what, still doesn't work.

I've been trying to fix this for the past 2 hours and have to sleep ,so I'm leaving this here for whenever I/somebody figure out why this is happening or Asv9 reverts the PR. :honk:

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
speedrevert

**Comment by Ratvar** [comment]
NTSL didn't like your aboose and left
