### ISSUE TITLE
Core R&D Console -> Normal View = empty

### ISSUE THREAD

**Issue by redpiller** [yogstation13/Yogstation#2965]
[Round ID]: # 19028 (and earlier same day) 

[Reproduction]: # Click on-> the Core R&D Console -> Click on -> Normal View

**Comment by ThatLing** [comment]
![](https://i.imgur.com/ctZRv7X.png)
Works fine for me

**Comment by MegaEmpirical** [comment]
I was asked to confirm this as an AI, same issue. Normal view was completely blank, just the black/grey background and the buttons to get to the different views and such at the top.
