### ISSUE TITLE
Weird deadchat name bug.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#297]
Guy observed, then became a pAI, then later a drone, then back to ghost. His name was his char name but I couldn't look him up in the player panel. Later discovered he had his pAI name in the player panel instead of his ghost name.

**Comment by SeikoTheSeal** [comment]
We explained it to you in dead chat dumbo. Theres a new button in ghost tab called Restore Ghost Character that is meant to restore your dsay name to your default character name.
