### ISSUE TITLE
Chaplain's armblade - naming

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#2973]
It's still sometimes confusing that chaplain's armblade is indistinguishable from a real one, why not name it so everyone recognizes it as a dark blessing, even though it's on his body? Certainly if chaplain is crew, everyone would know his "item".

**Comment by Ratvar** [comment]
Pay for using snowflake nodrop sharp 18brute valid-to-wear weapon.
Thought, you still can hit any glass/mob with it and it will show it's Dark Blessing, so there is already a check. If you saw chaplain who hit someone and message in chat has shown armblade-it's ling, duh.

**Comment by Ratvar** [comment]
You can, you know, not use armblade nullrod if you don't want consequences. Your problem.
