### ISSUE TITLE
make #2888 not apply to ash drakes

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#2982]
https://github.com/yogstation13/yogstation/pull/2888
above pr makes it so that mobs get thrown when there are nearby explosions but makes fighting ashdrakes a random shitfest due to thier fireball attacks possesing explosive properties

**Comment by ThatLing** [comment]
@Time-Green

**Comment by Time-Green** [comment]
Feature
This makes ash drakes challenging again

**Comment by drderp3635** [comment]
If you want this to be a feature than you need to rebalance the number of fireballs around it, since currently you can't stand on or adjacent to any tile where a fireball is landing. People thought the field wide fireball attack was an install before but now its not even an exaggeration since it will kill you every time without fail
