### ISSUE TITLE
Emag gives "access denied" on HoS locker

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#2985]
Exactly as stated, I assume this applies to all lockers. Unsure if other parts of its use are broken currently.

**Comment by MegaEmpirical** [comment]
Update: Colburn3000 says it works if you use harm intent, on lockers.

**Comment by Bawhoppen** [comment]
Upstream fix is open: https://github.com/tgstation/tgstation/pull/40877

**Comment by MegaEmpirical** [comment]
That fix has since been closed as it wasn't doing it. The TG issue for this issue (for reference): 
https://github.com/tgstation/tgstation/issues/41249
