### ISSUE TITLE
Atmos cameras, pipe system

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#2991]
- Yog Station, new atmos layout now in round 19055, most atmos cameras don't show up on camera console (they are active for AI).

- Air is not mixed:

![ss13-atmosmixer](https://user-images.githubusercontent.com/16806055/46860957-c3d3be80-ce11-11e8-8c4d-2a6e95ac12cc.png)

**Comment by ThatLing** [comment]
#2983

**Comment by thehighwayman** [comment]
someone done fucked up

**Comment by Ktlwjec** [comment]
right back off you I fixed this already

**Comment by 00aquir** [comment]
Dunno if this is fixed already, so reporting this also:
- "Incinerator access console/interior" and the right-side "incinerator airlock control" don't work:

![ss13-atmos-turbine](https://user-images.githubusercontent.com/16806055/46880239-69a22000-ce48-11e8-859c-5bde40946165.png)

**Comment by Ktlwjec** [comment]
Someone mentioned that but didn't explain it at all clearly, I'll fix that today sometime.

**Comment by 00aquir** [comment]
Another one:

- Incinerator air injector should automatically push the gas out, but it doesn't do that.

![ss13-atmosinjector](https://user-images.githubusercontent.com/16806055/46882204-1df27500-ce4e-11e8-907c-5de187291e38.png)

**Comment by Ktlwjec** [comment]
Fixed that already, and the other injector.

**Comment by 00aquir** [comment]
Actually, since the air injector has a transfer rate that can be changed and it's not on max.. there shouldn't be injector at all, because (there is already a pump there, and) atmos techs would have to go into space every round for setting it (for the turbine).

**Comment by Ktlwjec** [comment]
I got turbine working with the fix without going to space.

**Comment by 00aquir** [comment]
another one:
- seemingly trash keep coming up from atmos bin (or rather, the pipes) in different rounds

![ss13-atmosbin](https://user-images.githubusercontent.com/16806055/46884989-e63bfb00-ce56-11e8-8767-eba7a84b91eb.png)

**Comment by 00aquir** [comment]
@ThatLing, it seems that the left-side "incinerator airlock control" button is not working either (as well as the right one does now). Also **after** pushing the right side button (left door bolted, right one unbolted), the "Incinerator Access Console" doesn't do anything..

**Comment by Ktlwjec** [comment]
It worked on my test reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
