### ISSUE TITLE
BOXSTATION:Custodial Closet Vent Pump #1 Error

### ISSUE THREAD

**Issue by Colburn3000** [yogstation13/Yogstation#2996]
[Round ID]: 19060

At Boxstation roundstart Custodial Closet Vent Pump #1 is not connected to the atmos console. It also basically acts as a turbine vent, siphoning the room causing hazardous conditions in a matter of seconds. Deleted and replaced vent pump, and it works fine.

**Comment by Ktlwjec** [comment]
#2983
