### ISSUE TITLE
Curator known languages bugged.

### ISSUE THREAD

**Issue by Peripiptein** [yogstation13/Yogstation#2997]
Issue reported from  Round ID: 19060 (Yogstation 13)

Reporting client version: 512

I was unable to speak anything other then Galactic Common.

**Comment by ThatLing** [comment]
What?

**Comment by Peripiptein** [comment]
The curator starts with a bunch of different languages he can speak, by either selecting them as default in the language menu, or by doing something like ,n before he speaks. Neither of those methods were working. I could only seem to speak Galactic Common.
