### ISSUE TITLE
Make a dev branch for yog content merges

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation#3]
so we can keep a pure master

**Comment by X-TheDark** [comment]
Why? To run vanilla /tg/ on our server or something?

**Comment by oisin100** [comment]
Theres not really any point, I considered using the old system of the dev and master branch, but then I realized it only complicates things for no good reason.

**Comment by fizzle7** [comment]
do we have version control? in case something breaks badly to revert.

**Comment by oisin100** [comment]
> do we have version control? in case something breaks badly to revert.

Ay,Github lets you revert commits.
