### ISSUE TITLE
Le funny ai bug

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#300]
@MacHac goodshit 
![dreamseeker_2016-07-06_02-37-22](https://cloud.githubusercontent.com/assets/6613514/16610819/ba03e68c-432b-11e6-9e59-b94a3528ea82.png)

**Comment by X-TheDark** [comment]
I assume the bug is Objective Number 3?

**Comment by Yackitori** [comment]
And steal the cap's jetpack

**Comment by Super3222** [comment]
> And steal the cap's jetpack

No... I think it's just objective 3.

**Comment by timkoster1** [comment]
I think it's mainly about 1, since thats impossible

**Comment by GrayRachnid** [comment]
It's objective 1 and 3. AI can't do either.

**Comment by timkoster1** [comment]
3 is technicly possible, but retarted and a bug

**Comment by MacHac** [comment]
Could not reproduce on a private server.
