### ISSUE TITLE
express delivery beacon

### ISSUE THREAD

**Issue by aaqe** [yogstation13/Yogstation#3011]
[Round ID]: 19082

[Reproduction]: express delivery beacon unable to be used per ckey Vagner24

**Comment by ThatLing** [comment]
Have more details? What is wrong with the express delivery beacon?

**Comment by aaqe** [comment]
How does it get used? I tried Z and alt click and clicking

**Comment by ktstudios2000** [comment]
Aaqe is talking about the express delivery beacon for the musician quirk. It was patched one day ago, and I just tested it in-game to confirm it now works.
