### ISSUE TITLE
Shadowling thrall darksight provides only a 3x3 grid of vision

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3022]
I assume this is not how it should work, I recall being able to see regardless of the distance:

Darksight off but helmet light on:
![image](https://user-images.githubusercontent.com/36208065/46911577-66815f80-cf2e-11e8-8d3b-f5109f437826.png)

Darksight on and no other lights:
![image](https://user-images.githubusercontent.com/36208065/46911575-5f5a5180-cf2e-11e8-820f-4e5f6039356a.png)

**Comment by Ludox235** [comment]
Its glitched with the night vision quirk.

**Comment by MegaEmpirical** [comment]
Ohhh, the quirk. Well that's good to know.

**Comment by Ludox235** [comment]
Nevermind, even whithout the night vision quirk its only limited to 3x3 vision

**Comment by MegaEmpirical** [comment]
Ah so still shit.
