### ISSUE TITLE
Port machine cult changes and fixes from tg

### ISSUE THREAD

**Issue by ChangelingRain** [yogstation13/yogstation#304]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
[wow rip this link got fucking murdered by oranges]

There's several hundred prs that I've done for it so far, large amounts of which have important changes and fixes.
If you want to take it your own way, that'd be fine, I guess.

**Comment by Super3222** [comment]
From what I hear, we're doing another "short rebase" shortly after coaix finishes datum antags.

**Comment by Greatbigben** [comment]
update?
