### ISSUE TITLE
Can no longer feed unwanted transit tubes to the transit tube dispenser

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3046]
Used to be able to drag them back onto the transit tube dispenser to destroy them, nothing.

**Comment by Ktlwjec** [comment]
Went through every var and there's nothing different there so *shrug* map-side it seems fine

**Comment by MegaEmpirical** [comment]
Yeah, I didn't think it was a map issue. Not sure what has changed other than the last time I tried this was pre-rebase.
