### ISSUE TITLE
Cannot Speak Bug

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#3049]
Round 19126. You try to speak: "You cannot speak in IC (muted)."

Happened now twice in the span of weeks. Admin intervention was needed both times. They happened after I was converted by clock cult. While it was happening maybe I tried to say something, and I had fun lying down and getting up in quick successions when cuffed by clockies.

**Comment by HomocidlePancakes** [comment]
Related: Implanting VoG in to yourself makes spam filter mute you randomly rendering the VoG useless. Removing VoG does not fix this.

I think it has something to do with you performing same actions over and over again. For example when I am mining and i make multiple shots without any other actions in between, somewhere on 15th-ish shot i would get a message that iam about to hit the limit on the identical messages. Then at the same time as i make one more shot i would get the message that i was muted by spam autofilter.

**Comment by 00aquir** [comment]
"I would get a message that iam about to hit the limit on the identical messages."

This kind of thing happened to me before when I was inserting cogs into different APCs maybe for the 10th time, separately.
