### ISSUE TITLE
Jani vendor not fully stocked

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3062]
Both janitor lockers were removed, after I finally got a second one added, and replaced by a vendor. The vendor only has supplies for one janitor and not two.

**Comment by Ktlwjec** [comment]
i gotcha b im a coder

**Comment by thehighwayman** [comment]
yeah it's sad my janitor change is gone now

**Comment by MegaEmpirical** [comment]
Thanks. 

I actually preferred lockers so I'm sad we have vendors now. Found lockers more aesthetically pleasing and they could be used for storage plus not bound by power being on but it's not something I cared that much about.

**Comment by Ktlwjec** [comment]
i hate highwayman that's the only reason i added them

**Comment by MegaEmpirical** [comment]
My beloved lockers. Issue resolved.
