### ISSUE TITLE
Admin log showing in dchat

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#3074]
[Round ID]: # 19159
![image](https://user-images.githubusercontent.com/34506490/47085533-cddd2f00-d20e-11e8-86e8-43b93797ff12.png)

Admin log appeared in deadchat. Player commented on it so I know it was visible by everyone.

**Comment by Bawhoppen** [comment]
Sorry, ignore my previous comment.

**Comment by Ktlwjec** [comment]
actually yeah I'm retarded I just noticed

**Comment by Bawhoppen** [comment]
Oh, wait. Was my previous comment correct? I thought since there was no (F) link for that message, I was the retarded one.
