### ISSUE TITLE
make trash bag break when full

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#3076]
I had a genius idea. When the janitor trash bag is full give it a chance to break, causing the items inside it to fall to the ground.

**Comment by MegaEmpirical** [comment]
You monster, I like it. Suggestion: being full in of itself won't break it but you can keep shoving shit into it with each new item increasing the likelihood of it breaking until it just finally snaps. With bigger items having an even greater likelihood. So if you're a careful jani, nothing to worry about.... but for those careless fools or rebels.

**Comment by aaqe** [comment]
How do I undo my council vote for you?
