### ISSUE TITLE
add teabagging animation to ctf

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation#308]
its mandatory

**Comment by Yackitori** [comment]
Not just to ctf. Make this a mechanic when you use rest on top of a person on the floor.

**Comment by Super3222** [comment]
Rest, stand, rest, stand, rest.
It's no ERP, i-i-i-it's just an ingame mechanic.

**Comment by Super3222** [comment]
Rest, stand, rest, stand, rest.
It's not ERP, i-i-i-it's just an ingame mechanic.

**Comment by Greatbigben** [comment]
is this actually a issue? please close the memes.

**Comment by drderp3635** [comment]
Admins add teabagging 

Teabaggs random 

Banned for ERP

**Comment by oisin100** [comment]
Nope. Nope. Nope.
