### ISSUE TITLE
Singularity won't grow.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#309]
If singularity is at minimum stage and goes next to one of the sides of the containment field, it will not grow at all, even if PA level 2 is directed right at it, engineers can basically kiss the engine goodbye.

**Comment by Cruix** [comment]
This is on purpose so the singularity will not eat the field generators when it grows. If it stayed stuck on one wall without a beacon attracting it, that could be a bug.

**Comment by 00aquir** [comment]
an hour passed and it stayed at the same place.. it stuck to the bottom wall. no beacons beneath the engine

**Comment by halueryphi** [comment]
https://i.gyazo.com/3d1e529b95406bed192c74e0c780ed06.png
Just saw it in a round. Singularity stuck to one of the walls of the generator, and even when the generators turned off, it just sat there and eventually diminished.

**Comment by Greatbigben** [comment]
any update?
