### ISSUE TITLE
Pipes on layers 1 and 3 appear broken/disjointed

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3106]
Only looks like this when they're interrupted by something like a floor tile or wall:

![image](https://user-images.githubusercontent.com/36208065/47128471-4cfa5380-d25f-11e8-8090-4f23ab5d7979.png)

![image](https://user-images.githubusercontent.com/36208065/47128481-55eb2500-d25f-11e8-9f0d-1a8abdce86f9.png)

**Comment by Amelia0010** [comment]
I already made an issue about this upstream, so just close this one

**Comment by MegaEmpirical** [comment]
I didn't see that, sure.
