### ISSUE TITLE
Distro and waste pipes are visible above the the floor in SM room

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3107]
Previously you could only see the engine related pipes above the floor.

![image](https://user-images.githubusercontent.com/36208065/47128530-93e84900-d25f-11e8-945a-a726e427c5ca.png)

**Comment by ThatLing** [comment]
@nichlas0010

**Comment by Amelia0010** [comment]
I did this intentionally

**Comment by Amelia0010** [comment]
I can undo it if you want

**Comment by MegaEmpirical** [comment]
Thanks, I found them both being top more annoying than useful. Engis have a t-ray setting on their scanners anyway.
