### ISSUE TITLE
Viro aux atmos manual pump starts on

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3109]
Should start off and turned on when needed.

![image](https://user-images.githubusercontent.com/36208065/47128748-87b0bb80-d260-11e8-9e92-558e962cb318.png)

**Comment by Amelia0010** [comment]
Aka “viro dies due to pressureloss after 10 minutes of breathing, as he has no air supply”

**Comment by MegaEmpirical** [comment]
I thought they were no longer independent, if they're then sure that works. I assumed you just connected them through the door.
