### ISSUE TITLE
Atmos gas supply consoles do not seem properly set up

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3110]
None, or nearly none, of the supply consoles for each gas tank seem properly connected to their tanks. Preventing proper control.

**Comment by 00aquir** [comment]
At least you can set pressures, but not whether the gas is stopped from the chambers or not (at least there are pumps outside).

**Comment by ThatLing** [comment]
@Ktlwjec

**Comment by Ktlwjec** [comment]
yes i am not a good mapper but it looked nice and thats what counts

**Comment by MegaEmpirical** [comment]
I believe in you.
