### ISSUE TITLE
Issue with pressure in N2O tank/loop in Yogstation

### ISSUE THREAD

**Issue by Mongoon** [yogstation13/Yogstation#3117]
Issue reported from  Round ID: 19183 (Yogstation 13)

Reporting client version: 512

Not sure, but it already happened second time to me. After i modified loops so you can directly connect canister to output of each tank, when i connect tank to N2O output it instantly fills with 50k pressure gas.  Problem did not appear with other gases even though set up is the same. Checked configurations of terminal and everything looks fine. For some reason N2O loop pressurizes with all gas available i guess.

**Comment by MegaEmpirical** [comment]
I was wondering why all the gas was missing in that tank. I'd just assumed someone was doing shit.

**Comment by Ktlwjec** [comment]
Honestly I have 0 idea what this means but does this look like it fixes it at all https://github.com/yogstation13/Yogstation-TG/pull/3116/files
