### ISSUE TITLE
Brain was sawed out and became inactive in MMI while ghost was inside it

### ISSUE THREAD

**Issue by aaqe** [yogstation13/Yogstation#3120]
## Round ID:
19187

## Reproduction:
Hansolo199532/Albert Archibald had their head cut off and their brain put into an MMI. The MMI said the brain wasn't active while the ghost was in it.

**Comment by Ktlwjec** [comment]
Did they suicide?

**Comment by Takahiru** [comment]
This has happened two rounds ive been in, one was a confirmed non-suicide, dont know bout the other

**Comment by ThatLing** [comment]
Maybe https://github.com/yogstation13/Yogstation-TG/pull/3102

**Comment by ThatLing** [comment]
Maybe https://github.com/yogstation13/Yogstation-TG/pull/3054

**Comment by Ratvar** [comment]
upstream feature, more like
