### ISSUE TITLE
Officer chair on labor shuttle

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3122]
Is on fucking wheels so it scoots around between jumps, please use other chair.

**Comment by 00aquir** [comment]
Related to https://github.com/yogstation13/Yogstation-TG/issues/2050

**Comment by Firewolf34** [comment]
Pretty sure I fixed it. I've actually been killed by this before, it's been there for a while. Anyways, it's a normal chair now, as soon as they pull it.
