### ISSUE TITLE
Allow Omnilathes (and Circuit Printers) from Free Golem ships to access the Ore Silo when Made on the Station

### ISSUE THREAD

**Issue by DiamondSentinel** [yogstation13/Yogstation#3134]
Title says it all. 

Omnilathes are a nice upgrade to existing department lathes, and making them a strict upside from the existing lathe would give the station more incentive to work with the golems. As it is, they're 2000 mining points, which is still a decent sum, and require mining to get lucky and find the golem ship (assuming it spawns), so it's not terribly broken, and it typically just means science gets CE tools or medbay machines to shove outside of science. 

At worst, it does mean that they do get guns, but RD no longer has firing pins in their locker; mindshield can't be lathed, meaning that they can't use mindshield pins freely; and testing range pins require Xenobiology to make cerulean slimes, which they rarely do, but it admittedly happens. 

Also, I'd post this upstream, but TG would never change it because they're still stuck on their science nerf circlejerk.

**Comment by ShadowDeath6** [comment]
I don’t really see a point for this since it kind of defeats the idea of the science changes to begin with- this would just make mining/science combo the same as it was back before the nerf except slightly less frequent. Also, it’s really not that hard to get 2k mining points if the golems upgrade their furnace, since miners have significantly faster and more efficient tools to mine with.

**Comment by DiamondSentinel** [comment]
Nothing stops science from getting the omnilathe as it is. And you can't stop it without massacring the Golem's ability to do anything. This is just a convenience merge. 

Additionally, if you added this, Golems could potentially make their own Ore Silo to make it easier.

**Comment by SomeguyManperson** [comment]
You can connect an ore silo to lathes and the ORM by hitting the silo with a multitool, then hitting the lathes/ORM with it.

**Comment by DiamondSentinel** [comment]
Currently does not worth with the old Omnilathes.

**Comment by DiamondSentinel** [comment]
> 
> 
> You can connect an ore silo to lathes and the ORM by hitting the silo with a multitool, then hitting the lathes/ORM with it.

Currently does not work with old Omnilathe.

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.
