### ISSUE TITLE
Nich's pipes are not connected to several meters through out the station.

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3159]
A bunch of meters that were originally connected to waste or distro are just floating now. The one that used to be connected to the scrubber ports outside of atmos and the pipes in north cargo maintenance are two known spots. Likely more.

**Comment by ThatLing** [comment]
@nichlas0010

**Comment by Amelia0010** [comment]
😩

**Comment by ThatLing** [comment]
#3162
