### ISSUE TITLE
Non-Antag Killing Me and most of Crew

### ISSUE THREAD

**Issue by weaponswall** [yogstation13/yogstation#3167]
So, playing a round, some guy, Nick Snapper, goes on a murder spree for no reason and we find out he isn't even an Antag. He killed most of Cargo, an ACTUAL Antag, and numerous other crew. This was around 1:04 am EST on 4/13/18 maybe a little earlier than that. Don't know the username only the in character name. The round was round 15853.

**Comment by nichlas0010** [comment]
yeah you wanna put this on the forums :)
