### ISSUE TITLE
Feature Request: Love potion end round report

### ISSUE THREAD

**Issue by aaqe** [yogstation13/Yogstation#3169]
Put people affected by love potions on end round report so they don't get player complaints.

Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.
