### ISSUE TITLE
Flamethrower cannot be fired

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#3171]
Flamethrower cannot be fired (at all)
- while lit
- with full 1013 kPa plasmatank, regardless of whether it's topped up with plasma or O2
- regardless of throw amount (100-300 kPa, etc.)
- was true for more than one shift

**Comment by GrayRachnid** [comment]
For some reason you need to click on characters to shoot the flamethrower, no idea why. Fixed with rebase.
