### ISSUE TITLE
Cameras don't work properly

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#3176]
Sometimes, making photos with camera works.
But now, the third time:
- The camera makes a photo that is invisible to me, and upon examination the photo window does not appear
- all sounds stop, and never return..
- in a minute, chat displays message: "You are either AFK, experiencing lag or the connection has closed."
- after client restart, I can see the photo and look at it, and I hear sounds again

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
sounds like a good way to assassinate your target

in any case I think this should be in https://github.com/yogstation13/tg-rebase/issues instead

**Comment by 00aquir** [comment]
okay
