### ISSUE TITLE
Can't compile current master

### ISSUE THREAD

**Issue by badonkadong** [yogstation13/yogstation#3177]
is it just me or you really check in uncomplilable code into the master branch ?
`loading yogstation.dme
loading interface\skin.dmf
code\game\mecha\equipment\tools\medical_tools.dm:117:error: : missing expression
code\game\mecha\equipment\tools\medical_tools.dm:119:error: : missing expression
code\game\mecha\equipment\tools\medical_tools.dm:123:error: : missing expression
code\game\mecha\equipment\tools\medical_tools.dm:124:error: =: missing expression
code\game\mecha\equipment\tools\medical_tools.dm:126:error: : missing expression
code\game\mecha\equipment\tools\medical_tools.dm:126:error: : missing expression
code\game\mecha\equipment\tools\medical_tools.dm:116:warning: filter: variable defined but not used
code\game\mecha\equipment\tools\medical_tools.dm:371:error: : missing expression
code\game\mecha\equipment\tools\medical_tools.dm:375:error: : missing expression
code\game\mecha\equipment\tools\medical_tools.dm:382:error: =: missing expression
code\game\mecha\equipment\tools\medical_tools.dm:394:error: : missing expression
code\game\mecha\equipment\tools\medical_tools.dm:396:error: : missing expression
code\game\mecha\equipment\tools\medical_tools.dm:397:error: =: missing expression
code\game\mecha\equipment\tools\medical_tools.dm:401:error: : missing expression
code\game\mecha\equipment\tools\medical_tools.dm:404:error: : missing expression
code\game\mecha\equipment\tools\medical_tools.dm:370:warning: filter: variable defined but not used
code\game\mecha\mecha_control_console.dm:43:error: =: missing expression
code\game\mecha\mecha_control_console.dm:50:error: =: missing expression
code\game\mecha\mecha_control_console.dm:53:error: =: missing expression
code\game\mecha\mecha_control_console.dm:41:warning: filter: variable defined but not used
code\game\mecha\mech_fabricator.dm:343:error: =: missing expression
code\game\mecha\mech_fabricator.dm:351:error: =: missing expression
code\game\mecha\mech_fabricator.dm:362:error: =: missing expression
code\game\mecha\mech_fabricator.dm:371:error: : missing expression
code\game\mecha\mech_fabricator.dm:374:error: : missing expression
code\game\mecha\mech_fabricator.dm:388:error: =: missing expression
code\game\mecha\mech_fabricator.dm:389:error: : missing expression
code\game\mecha\mech_fabricator.dm:400:error: =: missing expression
code\game\mecha\mech_fabricator.dm:341:warning: filter: variable defined but not used
code\game\mecha\mecha_topic.dm:224:error: : missing expression
code\game\mecha\mecha_topic.dm:224:error: : missing expression
code\game\mecha\mecha_topic.dm:227:error: =: missing expression
code\game\mecha\mecha_topic.dm:235:error: : missing expression
code\game\mecha\mecha_topic.dm:238:error: =: missing expression
code\game\mecha\mecha_topic.dm:245:error: : missing expression
code\game\mecha\mecha_topic.dm:246:error: : missing expression
code\game\mecha\mecha_topic.dm:247:error: : missing expression
code\game\mecha\mecha_topic.dm:247:error: : missing expression
code\game\mecha\mecha_topic.dm:249:error: : missing expression
code\game\mecha\mecha_topic.dm:250:error: : missing expression
code\game\mecha\mecha_topic.dm:251:error: : missing expression
code\game\mecha\mecha_topic.dm:251:error: : missing expression
code\game\mecha\mecha_topic.dm:255:error: =: missing expression
code\game\mecha\mecha_topic.dm:265:error: =: missing expression
code\game\mecha\mecha_topic.dm:281:error: : missing expression
code\game\mecha\mecha_topic.dm:219:warning: filter: variable defined but not used
yogstation.dmb - 41 errors, 5 warnings (5/11/18 8:26 am)
`

**Comment by nichlas0010** [comment]
This is an issue that some people have for some reason, most likely related to their BYOND version. I, for one, can compile both this master and the TG-rebase master perfectly fine, while Bawhoppen can't, getting similar errors to you. In case you were looking for the active build that the yogstation server uses, that would be here: https://github.com/yogstation13/tg-rebase

**Comment by badonkadong** [comment]
@nichlas0010 tg-rebase compiles fine, this is really odd
