### ISSUE TITLE
Bullets not properly deleting when the gun/magazine is destroyed in lava.

### ISSUE THREAD

**Issue by SeikoTheSeal** [yogstation13/yogstation#318]
<s>Be a miner. Find prisoner ship. Get hit by 10~ bullets simultaneously, instantly killing you, from an invisible, non existant object according to an admin. Your death is called legittotallintendednotabugyouwonderwhydopeoplehatecurrentadminteam. You wake up on github writing an angry bug report.

Looking at the map in dream maker i cannot see any turrets or the like on ruins template and according to Cruix this isn't something that should happen. Looking around as a ghost i didn't see anything that could possible kill me there either. There was just a corpse of a legion or a prisoner next to me and not a single mob.</s>

See Kor's comment below.

**Comment by KorPhaeron** [comment]
Here is what happened

A gun caught fire (in lava)

The bullets in the gun all got dumped on the tile when the gun/casings deleted

You walked into the bullets, triggering their collision

**Comment by Cruix** [comment]
Oh wow that's definitely a bug.

**Comment by ParagonPrime** [comment]
I'm more concerned as to why the fuck this was called legit.

**Comment by SeikoTheSeal** [comment]
Holy shit, i seem to like a magnet to bugs and retarded deaths.

**Comment by EMT321** [comment]
Thats actually pretty funny

**Comment by Greatbigben** [comment]
i call this a feature
