### ISSUE TITLE
You Tighten your grip on (X),tabling and agressive actions not working

### ISSUE THREAD

**Issue by Code611** [yogstation13/Yogstation#3182]
Round ID:19270
Description: I think this bug is only for me since I really haven't heard of anyone talking about it or admins mentioning someone else with the problem. The problem is that Putting people in a gibber, tabling people, strangling people and tightening grip on somebody doesn't work. I fully reinstalled my byond and it worked for about 1 round. It will show the progress bar and even show it completed it just won't actually grab them.I haven`t seen anyone else with this bug, so it may be external programs

**Comment by Bawhoppen** [comment]
That's pretty strange. Can you show a video demonstration possibly?

**Comment by Code611** [comment]
https://m.youtube.com/watch?v=zqtbvkpZNlg
if you need a clearer version just say

**Comment by Bawhoppen** [comment]
From what I've seen in the video, everything appears to be working as intended. When you have someone grabbed aggressively/tightened, they should still be being dragged behind you as you move. Is this what you're referring to?

**Comment by Code611** [comment]
No, The action of Tightening your grip or even strangling doesnt work for some reason it will just go You Tighten your grip on (X) and then just cancel it I guess? Basically, anything above an aggressive grab just doesnt work. This makes some antags like changeling objectives literally i m p o s s i b l e (absorbing dna)
Even in the pull right-click menu it just straight up doesn`t work.
It`s like if you were trying to tighten your grip something but then just didnt

**Comment by Bawhoppen** [comment]
Ah, I think I see what you mean now. The other individual is supposed to be moved to your tile and be knocked down? Regardless, I tested it in-game myself, and I believe what your video shows is consistent with what happens to me. So either this is intended functioning nowadays, or it's a bug everyone is experiencing and not just you (which it wouldn't be very likely anyways).

**Comment by Code611** [comment]
Okay, from what you can see from the video it looks like I'm tightening my grip on them, yes? When in reality it will fill the progress bar and stay as an aggressive grab. It`s like if I had a secret pacifist stat that didn't allow me to choke people or put people in gibbers

I also just got logs from a helpful admin, in logs, it keeps on saying: Attempted to tighten grip over and over again.

**Comment by GuppyLaxx** [comment]
@Code611 it's because you were on help intent
