### ISSUE TITLE
A few mentor things

### ISSUE THREAD

**Issue by kooarbiter** [yogstation13/Yogstation#3193]
Change the sound mentors hear when someone mentorhelps to be a bwoink or something easily as ear catching, but not mistakable for in game sounds, the current sound is a honk. Give mentors a ticket system like admins, because the only link to the mentor help is a single line which can easily be lost in chat, also this helps keeps everyone's problems seperated and you can check the log of things said if need be. Also dsay would be nice but it isn't neccesary.

**Comment by Amelia0010** [comment]
>Also dsay would be nice but it isn't neccesary. 

no.

>Give mentors a ticket system 

see above

>Change the sound mentors hear

@ThatLing @GuppyLaxx

**Comment by tsaoToast** [comment]
Another mentor thing:
New rounds reset mentor permissions. I think this might be due to it not _technically_ being a rank, which means they reset every round.

**Comment by kooarbiter** [comment]
we really do need a ticket system though, just copy most of the code over from admin, it becomes really hard to keep track of mentorhelps, and when the chat won't stop scrolling it takes forever to click on the name link to respond to people, and dealing with multiple mentorhelps at once is going to be really hard without a way to sort and track them
