### ISSUE TITLE
Search function in RnD console doesn't work properly..

### ISSUE THREAD

**Issue by fizzle7** [yogstation13/yogstation#322]
~~Cant build somatoray in RD, no errors, it does that semicircle animation but nothing comes out of the protolathe.~~
Searching the somatoray in the protolathe menu brings up the wrong recipe, its missing radium, and it lets you craft it when it shouldnt which causes the animation but doesnt spawn anything.

**Comment by McDonald072** [comment]
There's a similar problem in the circuit imprinter where the amount of sulphuric acid needed isn't shown. Although it does tell you when you have an insufficient amount to print.
