### ISSUE TITLE
Bio-hazard disposals no longer exists

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3221]
Since this room can no longer be used for its original purpose we should probably rename it. I assume it's not actually a named room as it's just a part of maintenance but the door should get a new name. Generic name or whatever. Or maybe we can do something new with it?

**Comment by Amelia0010** [comment]
what

**Comment by MegaEmpirical** [comment]
![image](https://user-images.githubusercontent.com/36208065/47586737-ffe94200-d92e-11e8-984b-e9eae0f077e8.png)

You removed the equipment here when you redid the pipes, it's now just an open room in maintenance. So the room's name is pointless.

**Comment by MegaEmpirical** [comment]
Could rename the "Incinerator" room bio-hazard disposals, it has all the same stuff, essentially. Also, it doesn't actually burn anything and people often get it confused with the turbine..... whose room is also called fucking Incinerator.
