### ISSUE TITLE
Gas flow meters are not visible on atmos' large tanks

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3222]
There is a gas flow meter on each of the large holding tanks in atmos, both for gases coming in and going out but they're not visible. They used to be at some point.

![image](https://user-images.githubusercontent.com/36208065/47588353-f31b1d00-d933-11e8-8c38-bd422db325a1.png)

**Comment by ThatLing** [comment]
Pretty sure they never were @Ktlwjec

**Comment by MegaEmpirical** [comment]
They were pre-rebase. I'm not sure why this changed at some point. It was an issue with the default atmos too.
