### ISSUE TITLE
Crew monitoring console map is still disabled.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#323]
If you're going to close the last issue about this, at least resolve the issue.

**Comment by fizzle7** [comment]
It isn't

**Comment by GrayRachnid** [comment]
![dreamseeker_2016-07-10_15-48-18](https://cloud.githubusercontent.com/assets/6613514/16715707/e031472c-46b5-11e6-9a2f-c2422bd7fb3e.png)

Have you cleared your cache recently? Because this is how it looks like.

**Comment by GrayRachnid** [comment]
![dreamseeker_2016-07-10_15-53-21](https://cloud.githubusercontent.com/assets/6613514/16715731/98b24bc0-46b6-11e6-8f55-38c4ef5aa14c.png)

**Comment by Super3222** [comment]
Relevant bug, it also crashes your game if it doesn't open.

**Comment by X-TheDark** [comment]
Requires a server-side configuration change in this line https://github.com/yogstation13/yogstation/blob/f29b139ad9b89d7ed80aec2d795481d6e1214257/config/config.txt#L250

**Comment by BubbaWPro** [comment]
I would just like to add that I am experiencing this bug on yogstation, 10-28-2016.
I know that fixing a bug requires a fucktonne more info than that, but im ridiculously inexperienced and thats the best I can give right now. Uh, I try and answer any questions yall may have.
