### ISSUE TITLE
Can hear slime link as mmi

### ISSUE THREAD

**Issue by alexkar598** [yogstation13/Yogstation#3238]
## Reproduction: 
0)Not sure but i got cloned due to death from a metal adult slime
1)be brainkilled(damaged brain)
2)get brian removed via surgery
3)get inserted into mmi
4)i got my brain removed and placed back in
4)get mannitol splashed on the brain
5)still alive but i can heard slimelinks and it had the little (F) button even tho it dosent work
6)be into borg,cant hear anymore
7)be deconstructed,can hear

**Comment by Altoids1** [comment]
Poor brian.
