### ISSUE TITLE
Screwdrivering survival capsule storage makes it go invisible, but still impassable

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#325]
![bug report](https://cloud.githubusercontent.com/assets/16902787/16713374/f7c9f182-46a5-11e6-94ac-b3137ac36cb8.png)

I screwdrivered the storage, thinking I could move it out of the way.

It instead turned invisible, but I still couldn't bypass it- though I also couldn't screwdriver it shut.

**Comment by Notamaniac** [comment]
Probably because it has no icon state for it

**Comment by AndySok** [comment]
yeah , i found it too.
We just have to make a sprite for it.
