### ISSUE TITLE
Item suggestion: Mining Barometer

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#327]
A not-too-cheap (800, 900 points or so?) item you can buy from the mining vendor.

When used, it will tell you how much time you have until the next Ash Storm on Lavaland- **with a margin of error of one minute.**

You can also buy an upgraded version (1200 or so) that has a much smaller error margin (20 seconds).

Just a simple QOL thing.

Feel free to increase the pricing if necessary.

**Comment by Super3222** [comment]
@ParagonPrime This is a pretty good idea, I'll look into it implementing it some time. Don't quote me, haha
