### ISSUE TITLE
You cant buy the arena shuttle

### ISSUE THREAD

**Issue by fluffe9911** [yogstation13/Yogstation#3275]
(TO REPRODUCE)
1. Have bubblegum killed
2. Get 10000 credits
3. Cry when it says you have not reached the criteria for buying the shuttle

**Comment by Amelia0010** [comment]
@ThatLing probably due to us not enabling medals

**Comment by ThatLing** [comment]
Not happy

**Comment by redmoogle** [comment]
Arena shuttle was moved to admin spawn only due to it being buggy. Furthermore as the code says _you_ have to kill bubblegum ~~`return SSachievements.has_achievement(/datum/achievement/bubblegum, usr.client)`
