### ISSUE TITLE
Missing atmos pipe on yogmap turbine

### ISSUE THREAD

**Issue by miniusAreas** [yogstation13/Yogstation#3279]
Hey, theres a missing atmos pipe at yogmap turbine that leads to space, used to pump gases out of the turbine. Admin sent me here.

**Comment by MegaEmpirical** [comment]
Did you confirm that it wasn't under the floor?

**Comment by ThatLing** [comment]
@nichlas0010

**Comment by miniusAreas** [comment]
@MegaEmpirical It goes through a wall, and it didn't have a pipe when I rightclicked or deconned the wall. SO no, its not under a floor, seeing as its under a wall.

**Comment by Ktlwjec** [comment]
probably my fault I will check

**Comment by Ktlwjec** [comment]
ok i fix in 10 mins
