### ISSUE TITLE
game.log not showing whether say logs were sent over radio

### ISSUE THREAD

**Issue by aaqe** [yogstation13/Yogstation#3285]
## Round ID:
19385

## Reproduction:
When looking at game log I do not see what radio channel is used or whether it was sent over radio at all. Have a blessed day.

**Comment by Amelia0010** [comment]
sounds like a feature request to me

**Comment by ghost** [comment]
I doubt it's the same stuff anymore but I made something similar prebase: https://github.com/yogstation13/yogstation/pull/2848

**Comment by Amelia0010** [comment]
So did I :) https://github.com/yogstation13/yogstation/pull/2681

**Comment by Ktlwjec1** [comment]
telecomms.log
