### ISSUE TITLE
No way to interact with placed & armed C4 or X4 charges

### ISSUE THREAD

**Issue by Firewolf34** [yogstation13/Yogstation#3296]
![c4-1](https://user-images.githubusercontent.com/2159739/47775186-01af5e80-dcbd-11e8-8ce6-784089532fbf.PNG)

Not sure if this is intentional or not, but me and a borgo found this quite vexing today: there's no way to interact with a C4 or X4 charge once it's been placed and is ready to blow. 

Alt-clicking on it shows absolutely nothing. It doesn't even show up in the list. It's not that you can't remove it somehow, it's that you can't even examine it. It feels like some kinda bug that the charge is invisible like this, and though I'm sure there's a technical reason for it (I doubt the image of the flashing charge is a "real" item), it would be great if you could spawn in an invisible and immovable c4 or x4 item copy underneath it (an armed version or something, that cannot be re-used) for a small amount of time until the actual charge explodes, that way it would still be able to be interacted with.

A couple of compelling reasons this should be changed:

- Examining a placed charge to see how much of the timer countdown is left (considering they can have long times, it's really odd to just see a C4 flashing on a wall for 5 minutes)
- Attempting to remove a charge from the wall and throw it back at the traitor that placed it
- Shooting an armed charge off the wall / having it react to other explosions
- Scanning a charge for DNA before it goes off
- Attempting to disarm a charge (maybe)

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.
