### ISSUE TITLE
Tourist Starts With Three Film Cartridges But No Camera

### ISSUE THREAD

**Issue by Nickvr628** [yogstation13/yogstation#330]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Like the title says, the tourist job starts with plenty of film, but no camera. Not sure if bug or intentional. An admin told me to report it here.

Please fix this, I like the roleplay of the tourist job, taking selfies with all the heads of staff.

**Comment by IgnisCorvus** [comment]
it's only change a word in code\modules\jobs\job_types\civilian.dm
Come on, this cant take so much time

`>/datum/outfit/job/tourist
	name = "Tourist"

	uniform = /obj/item/clothing/under/tourist
	shoes = /obj/item/clothing/shoes/sneakers/black
	ears = /obj/item/device/radio/headset
	belt = /obj/item/device/pda
	backpack_contents = list(/obj/item/device/camera_film, /obj/item/stack/spacecash/c20, /obj/item/stack/spacecash/c20, /obj/item/stack/spacecash/c20)
	r_hand =  /obj/item/device/camera // HERE IS THE LINE!!
	l_pocket = /obj/item/device/camera_film
	r_pocket = /obj/item/device/camera_film
`

**Comment by Nickvr628** [comment]
This is 3 days old now, and Ignis already posted the code. Is ANYONE going to fix it?

**Comment by Super3222** [comment]
@Nickvr628 Alright, calm down there buddy. I was under the impression that @IgnisCorvus was out to fix it, since he's interested in coding for us. However, if that's not the case and he was just pointing it out, then I'll go ahead and do it.

**Comment by IgnisCorvus** [comment]
i though that i made a fork fixing this

**Comment by Cruix** [comment]
You did, but you have to make a pull request. Go to the webpage of your repository, select the branch you did the fix on, and look for the "compare and pull request" button.
