### ISSUE TITLE
Face Stealing

### ISSUE THREAD

**Issue by joejoe3421** [yogstation13/yogstation#331]
[Note]: Okay so this is how it happened... I was an ashwalker and i found a corpse that was once legion. With envy's knieve i aimed at the head and i got the messages:

"Deeja-Jeed has attacked Unknown in the head with the envy's knife!"
"You assume the face of Unknown. Are you satisfied?"

I figured all was well and cool until I noticed I was gasping. Ash walkers i don't think breathe so it seemed as though not only did i assume the face but the body as well or perhaps just the race. Hair came with it.

No I was not gasping before i did this.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by ShadowDeath6** [comment]
not too educated on how race data works but I believe cutting him with the knife made you considered human, and since you had no lungs in your ashwalker torso, started dying

**Comment by Super3222** [comment]
I'm not sure whether this is a bug... or an ironic feature from lavaland.

**Comment by timkoster1** [comment]
lol no, ash walkers don't need air, when you became a human you started suffocatin cuz lavaland has no fucking air
