### ISSUE TITLE
Report on Rylan Sandys

### ISSUE THREAD

**Issue by Desayunar** [yogstation13/Yogstation#3312]
Issue reported from  Round ID: 19432 (Yogstation 13)

Reporting client version: 512

Rylan Sandys kept attacking me, John Vaun Shaun, for no reason. He was not antag. He poisoned me and smashed bottles overhead. I had not threatened nor attacked him beforehand.

**Comment by MegaEmpirical** [comment]
This is the wrong place for this. Git is for game related issues like bugs. You want the forums, see link below:

https://forums.yogstation.net/index.php?forums/player-complaints.3/
