### ISSUE TITLE
APC bugs

### ISSUE THREAD

**Issue by fizzle7** [yogstation13/yogstation#332]
- APC batteries wont charge for some reason even after being powered

- Some apcs will brick and wont let you turn the options to on manually, defaults to off, even with auto, even after reconstructing it and removing the battery so it only runs on power.

Happens after they get their power cut and restored due to explosions and stuff, Talking about functioning apcs, not destroyed ones that require reconstructing,

**Comment by GrayRachnid** [comment]
Explosions and EMPs can damage batteries beyond repair.

If it's not the battery, then the power control module is damaged.

**Comment by IgnisCorvus** [comment]
It can pass by explosion or emp. But i saw this a lot of times. Even, i saw it when a rat cut the cable of the APC title. It didnt charge but the rest of apc was charging.

**Comment by GrayRachnid** [comment]
Yeah, that's a powernet issue. To fix that, simply cut the wire knot under the APC and reapply it.

**Comment by fizzle7** [comment]
How can the module be damaged?
