### ISSUE TITLE
Hydrobugs Metastation

### ISSUE THREAD

**Issue by Colburn3000** [yogstation13/Yogstation#3344]
Round ID:19467

## Reproduction:

Metastation round and no water, fertilizer, or mutagen can not be added to hydroponics trays or soil. You get the sound and message, but the container loses no volume. It's pretty much as simple as that. We had just hardbooted the server the round prior, so that could cause the issue.

![image](https://user-images.githubusercontent.com/24303426/47945939-29304200-dedc-11e8-8e4d-f1ad32c00316.png)

**Comment by neeshacark** [comment]
Adding onto this, this isn't exclusive to metastation, it was happening on yog for me too.

**Comment by Ktlwjec** [comment]
tg has a fix so we get it soon

**Comment by Ktlwjec** [comment]
#3352
