### ISSUE TITLE
Can't remove vampire status from someone in TP

### ISSUE THREAD

**Issue by aaqe** [yogstation13/Yogstation#3350]
## Round ID:
19479

## Reproduction:
As mod I can't remove vampire status from someone in TP

**Comment by Ktlwjec** [comment]
fuming again :rage4:

**Comment by ThatLing** [comment]
Is this only mods?

**Comment by zxmongoose** [comment]
I actually had this same issue come up yesterday. Also making people a vampire using TP seems a bit fucky and doesn't change over species, at least from nonhumans, had to set species separately in VV
