### ISSUE TITLE
Wingpotion is still bugged.

### ISSUE THREAD

**Issue by SeikoTheSeal** [yogstation13/yogstation#338]
#299 was supposed to fix this, yet, yesterday we managed to obtain two potions at mining. On me, a human, potion had no effect. On Stealth as cabbage, potion turned him human and gave him wings.

**Comment by GrayRachnid** [comment]
Even though these updates are being merged, the server isn't being updated. blame @oisin100 v0v

**Comment by Stealthkibbler** [comment]
Oisin is supposedly 'Taking a break' from git at the moment, so while he's still merging it may be a bit of time before everything actually goes through.

**Comment by SeikoTheSeal** [comment]
Closing dis den.
