### ISSUE TITLE
Vampires can't suck dirty blood

### ISSUE THREAD

**Issue by Megatome** [yogstation13/Yogstation#3382]
Issue reported from  Round ID: 19528 (Yogstation 13)

Reporting client version: 512

Blood from corpses, blood packs, monkeys, etc. It just doesn't work.

**Comment by ThatLing** [comment]
Why would it?

**Comment by Megatome** [comment]
Because that makes sense? Vampires need blood to fuel their abilities. The /tg/ wiki says that vampires can do it to fuel their abilities, but that blood can't be used for nourishment or to prevent death. Why would you remove such a useful utility from vampires?

**Comment by HomocidlePancakes** [comment]
Tg wiki also says this 
>Removed
>Vampires never fully made it into the game. This page is archived for historical purposes.

**Comment by Megatome** [comment]
Alright, that's understandable.
