### ISSUE TITLE
Plasma glass spears dont show on the players sprite when you hold them

### ISSUE THREAD

**Issue by DeadlyBag** [yogstation13/Yogstation#3387]
Made a plasma glass spear and noticed that it didnt show on my sprite and other players couldnt see it either. After fucking around with it a little more it sometimes did show on my sprite but asoon as i dropped it and picked it back up i couldnt see it anymore.

Note: You can see the Item in your hand and on the floor even the examine text shows that you have a spear in your hand/back.

**Comment by SomeguyManperson** [comment]
For some reason the spear doesn't have a sprite for one hand (I think the left one) or the back, probably the guy who coded it forgot to add those
