### ISSUE TITLE
Inmunity to shadowlings

### ISSUE THREAD

**Issue by IgnisCorvus** [yogstation13/yogstation#339]
[Note]: # In a round of shadowling mode, two shadowling tried to convert me at the same time. When the first finished i was a thrall, but when the second finished moments later, i was deconverted. They tried again, but this time only one, the result: i could not be converted by shadowlings. I was not implanted and the lings spells could affect me. Just i couldnt be convert. We tried a couples of times more.
I wrote this here, but i will try to find the problem later. Honestly i am not sure about what can i do here.

**Comment by FluffySurvivor** [comment]
LOL

**Comment by IgnisCorvus** [comment]
what? i reporte in game two times and i didnt see here.
