### ISSUE TITLE
fix font

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#341]
git is broke halp

i don't like change reeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by ShadowDeath6** [comment]
ask git you weeb

**Comment by Super3222** [comment]
its smooth

**Comment by ShadowDeath6** [comment]
>smooth

no

**Comment by FluffySurvivor** [comment]
me layk

**Comment by oisin100** [comment]
Use Tampermonkey to edit your CSS on pge lod if you dont like it.

**Comment by ParagonPrime** [comment]
i've actually grown to like it, strangely :V
