### ISSUE TITLE
Skeleton action figure - Bugs

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#343]
1. I got an invisible (for everyone) skeleton action figure out of Orion Trail. Mouse hover does not reveal it being on the floor, only right click menu!
2. Using Skeleton action figure (once) interrupts all sounds for everyone for several seconds. (rubber ducky's honk, door sounds, etc.)

**Comment by Stealthkibbler** [comment]
This is fixed by #335

**Comment by 00aquir** [comment]
great
