### ISSUE TITLE
Commissary camera placement is a bit derpy

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3450]
Could we maybe move it opposite? Seeing it hang on an open door like that is just wrong.

![image](https://user-images.githubusercontent.com/36208065/48320880-190b1780-e5ec-11e8-9d13-484351c9de77.png)

**Comment by Ktlwjec** [comment]
There isn't a door there

**Comment by MegaEmpirical** [comment]
I see, some savage added a door where the camera is. Monsters. Thanks.
