### ISSUE TITLE
New Husks for our races

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation#346]
Husks for Preternis would be the same as the human husks, but with tons of wiring sticking out of their body, and their robotic eye hanging from their eye sockets.

Husk for Phytosians would be like ... their body would look like the root of a plant. All sunken up, and you could barely tell if they have limbs or not due to their body parts being so tiny. They'd also have a dark grey complexion.

**Comment by Robertruler77** [comment]
This.
I wanna looks speshul.

**Comment by Kmc2000** [comment]
Working on this
