### ISSUE TITLE
Genetic power bug

### ISSUE THREAD

**Issue by zombieburger** [yogstation13/yogstation#347]
[Note]: # I got powers chameleon and dwarf multiple times and powers kept wearing off after a while and i return to normal, having to click.I contacted one of the admins about this and he had no idea, and said its possible the code was changed.

[Admins]: # I have not edited my game in any way.

**Comment by Yackitori** [comment]
SE injectors are now temporary. Not a bug. If you want permanent powers, someone has to modify your own SE's.

**Comment by ShadowDeath6** [comment]
shitty change IMO

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
press Occupant: Delayed in the buffer menu, then enter the scanner, it will change your DNA
