### ISSUE TITLE
Hand teleporter portal bug

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#348]
Hand teleporter portal not disappearing, ever. At least I ran into the same thing half an hour later, it just stayed there.

**Comment by SKR6DarkVoid** [comment]
Hmm.

I'm looking at the code for the hand tele, and the regular teleportation file..  Timings for portals seem to be fine, it could be that someone else had a hand tele?

**Comment by 00aquir** [comment]
it happened in different shifts. A portal staying in the same place. in the middle of a hallway, so I guessed it was not from a wormhole gun or something, and it teleports you to a random location.

**Comment by Super3222** [comment]
I did a few tests on local, and couldn't find anything wrong with this.

**Comment by 00aquir** [comment]
we still had portals that are not closing for more than 1 minute, I'll make a new issue IF I see it again I guess
