### ISSUE TITLE
Click to follow links don't work

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#3496]
Round 19662 (But any other round too) - Anomaly appears on the side of the screen with the image, and in chat with a link. The image allows you to follow it when clicked, the chat link does not.

**Comment by Amelia0010** [comment]
lol

**Comment by Ktlwjec** [comment]
ffs nich it's not funny

**Comment by Amelia0010** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/3502/files
