### ISSUE TITLE
Borgs with donor skins cannot wear hats

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#3528]
As the title says, I assume it's a fuckup relating to #3426 and #3427 .

**Comment by ThatLing** [comment]
@Kmc2000

**Comment by Kmc2000** [comment]
Uhm what...

I can take a look at this shortly.


To clarify, by not wear hats, you mean you can't put them on? Have you tried varediting a hat onto a borg?

**Comment by Ktlwjec** [comment]
Yeah, you can't put them on borgs. I've only noticed it with donor skins and not normal skins so I assume this to be case. Haven't tried editing one on

**Comment by Kmc2000** [comment]
Whack
