### ISSUE TITLE
Make the engine bay an engine bay area.

### ISSUE THREAD

**Issue by fizzle7** [yogstation13/yogstation#355]
Currently, the engine bay area is space with engineering around it, it should be its own area, engine bay so that if you want to put an air alarm or apc it would work, for example when making a supermatter shard, you can make it the easy way or you can make it the autistic way with pumps and scrubbers because you cant put an air alarm and apc.

**Comment by Cruix** [comment]
I once died as a wizard because I teleported to engineering to steal a suit and appeared in the engine bay. This is a good idea.

**Comment by GrayRachnid** [comment]
:-1:

**Comment by fizzle7** [comment]
Wat?

**Comment by Kmc2000** [comment]
I can do this if people want it

**Comment by Greatbigben** [comment]
Close this mate

**Comment by fizzle7** [comment]
Close for what?

**Comment by Super3222** [comment]
I'll make a new PR for this @fizzle7

**Comment by fizzle7** [comment]
Alright

**Comment by Super3222** [comment]
I mean, I can make it an area. But I'm not making an APC and air alarm.

**Comment by fizzle7** [comment]
Ye thats fine, the rest is easy, but dont include the PA like kmc did, everything outside the windows and grilles that currently is space.

**Comment by Greatbigben** [comment]
Too much of a hug box honestly engineer is supposed to be dangerous.

**Comment by Greatbigben** [comment]
And oisin said no for it I believe

**Comment by Greatbigben** [comment]
See issue 378

**Comment by fizzle7** [comment]
You misunderstand what oisin said, this isn't what KMC did. And anyway, it should be up for discussion, not decided by one person.

**Comment by Super3222** [comment]
Errr what I mean is that i'm going to make the engine bay labeled engine bay instead of engineering, so situations like what Cruix went through don't happen. I'm leaving it space like, which is why I'm not adding in an APC or air alarm.

**Comment by Kmc2000** [comment]
Oisin nuked it

**Comment by fizzle7** [comment]
No no, the point is everything that is space in there shouldn't be space.

**Comment by Kmc2000** [comment]
Which is what oyster didn't like with my PR

**Comment by fizzle7** [comment]
As in the area shouldn't be space, not the tiles.

**Comment by fizzle7** [comment]
You removed the space tiles, I didn't mean that.

**Comment by Kmc2000** [comment]
ohhhhh

**Comment by Greatbigben** [comment]
meh engineering is fine i mean overcrowding it with meme things doesnt make it better. Do you have a suggestion on what should be added?

**Comment by fizzle7** [comment]
> meme
Yeah, I don't think you understand. There is nothing memey about this.
Whenever you want to make a SM engine there are 2 ways: Put it where the tesla and singo go (i.e. the engine bay) or put it inside engineering where the PA goes thereby removing the PA and setting it all up so that it's ready for the SM. 
SM shard needs atmos to function so the PA way is, while fine (and probably faster than the future implementation of the engine bay), a huge hassle and completely ugly. 
The other way is to put it in the engine bay and set everything, which makes it easy though longer cause you need to run more pipes (which should be added in the new engine bay for ease), and a few more minor hassles. The problem with this is that you cant use the pipes because you can't put apcs or air alarms because the area is considered space and you can't power a space area. I don't care if you make it have atmos, make

**Comment by Greatbigben** [comment]
Ok let me understand this you want a area reclassified so you may make a SM engine when 90% of the server can even put Sing up properly?

**Comment by fizzle7** [comment]
Yes, precisely, that's not memey. SM shard is behind the cargo wall which is hard to pass because they are anal about captain permission. No newb is gonna bother with SM if they don't know how to set up the rest. The point is to make this available for those that are good at it and want to do more in this game cause it gets boring. There are a lot of stuff in the game not meant for 90% of the players, but for the other 10% that are committed and actually know what they're doing.

**Comment by Greatbigben** [comment]
that's a elitist attitude but i understand what your saying, no disrespect intended. What will be needed precisely to ensure the area is able to maintain the SM safely? A plasma junction pipe from the tank itself, a waste pipe so you may take out anything you don't want, a APC, and a Air alarm?

**Comment by fizzle7** [comment]
Didn't mean to be elitist. If the pros really wanted some challenge they would do it from scratch which I tried for 5-6 rounds. That didn't work because the shuttle is instantly called when available and I can't manage to make the engine by myself. It would also be there for whoever wants to be adventurous and do it.
SM only works best with supercooled pure oxygen in. It generates N2 and plasma which has to be taken out through a scrubber or a vent that sucks in and a gas filter that then filters the oxygen back to distro and the rest to the waste pipe. Depending on how many emitters you have aimed at it and if your atmos oxygen is high pressure and waste moving fast and cooled, you might require more than one scrubbers and vents. This adds some cooperation between engineering and atmos. You can use freezers for cooling, but most likely if you do full power with 4 emitters it's gonna require space loops to cool everything down which the engine bay, being at vacuum temperature, is ideal, so heat exchange pipes would be best already put there for that for both distro and waste with two manual valves or pumps in engineering that control the flow to the shard so that you dont vent oxygen when there is no shard.

**Comment by fizzle7** [comment]
This could also allow for a quick TEG setup since we don't need that massive room that mac is making in the turbine room. You just need to take out the hot gas and pass it through a 3x1 TEG which you can put anywhere in engineering.
