### ISSUE TITLE
Replace all jobs with SNPC.

### ISSUE THREAD

**Issue by SeikoTheSeal** [yogstation13/yogstation#356]
What did you expect to happen: Enjoy the game with decent human beings.

What happened instead: People are fucking horrible.

How can we fix it: Replace everyone with SNPC.

Please commit a fix asap.

**Comment by Yackitori** [comment]
Add meme zone before closing this coders.

**Comment by SeikoTheSeal** [comment]
This is a serious issue please go away dirty memer.

**Comment by FluffySurvivor** [comment]
better

**Comment by SeikoTheSeal** [comment]
;_;

**Comment by Robertruler77** [comment]
Lets put the Scottish National Party Council in, cause why not?

**Comment by Kmc2000** [comment]
:+1:  :  x :100:

**Comment by oisin100** [comment]
NO FUN ALLOWED

**Comment by SeikoTheSeal** [comment]
This was a serious issue and wasn't fixed yet. Please re-open it.

**Comment by Kmc2000** [comment]
:+1:
