### ISSUE TITLE
Rename the meatball

### ISSUE THREAD

**Issue by Yackitori** [yogstation13/yogstation#358]
Fix the meatball name so it's meatball, and not f*ggot. Sick of hearing chefs spamming that term because "is da name of da food hurr durr"

**Comment by GrayRachnid** [comment]
While you're at it, remove the word faggot from the brain damage random lines.

**Comment by Super3222** [comment]
but... it's just the name of the food xddd
seriously though, I see what you mean.

**Comment by FluffySurvivor** [comment]
inb4 we ban the meatball for bigotry

**Comment by ParagonPrime** [comment]
Grow a thicker shell, people.
