### ISSUE TITLE
Earmuffs do not make you deaf

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation#359]
This might have been an intentional change by tg, but I cannot find any PRs about it.

**Comment by Super3222** [comment]
Insane.

**Comment by FluffySurvivor** [comment]
feature

**Comment by Greatbigben** [comment]
they are suppose to quiet down any sounds near you i think you can hear if someone is 1 tile away but cant confirm.

But seems like a feature in any case

**Comment by Groxic** [comment]
Can you close this if there's nothing wrong?
