### ISSUE TITLE
BlueSpace locker duplication glitch 

### ISSUE THREAD

**Issue by boba247** [yogstation13/Yogstation#3615]
I was able to turn 1 ion carbine into 3 by placing them in the bluespace locker and closing it. One stays in the locker while a new one is made in the separate z level area.

**Comment by ThatLing** [comment]
@monster860

**Comment by monster860** [comment]
show me a screenshot or video of it please.

**Comment by boba247** [comment]
Round number was 19792. 
![ss13 glitch](https://user-images.githubusercontent.com/45266020/48922378-52f1de80-ee74-11e8-8625-e074af8c61ff.jpg)
I was playing as detective and discovered the glitch in security.

**Comment by monster860** [comment]
> One stays in the locker while a new one is made in the separate z level area.

Can you clarify this statement please?

**Comment by boba247** [comment]
I placed the ion carbine in the locker closed it and opened it, the carbine was still there. Then I picked up the carbine and went in the locker and found another carbine that wasn’t there before.

Due to the holiday I can’t get to my computer but I’ll try replicating this bug later.
