### ISSUE TITLE
Remove blob event and from the rotation

### ISSUE THREAD

**Issue by Stealthkibbler** [yogstation13/yogstation#362]
This started happening before the rebase but simply put, nobody wants to bother fighting the blob, blob is set to the highest probability chance to spawn midround, yet we never see any crew bother to fight it because the startround antag/s are usually a bigger threat.

It's just become something that nobody really wants to deal with and because of that the blob just freely grows and expands and usually consumes a large portion of the station forcing the eventual call of the shuttle.

I've never seen a round where crew actively fight the blob as a team anymore, it just gets downright ignored and pushed aside like some side task to deal with later, ontop of that I have yet to see a round where a blob has actually managed to die outside of shenanigans.

**Comment by GrayRachnid** [comment]
I've beat blobs past the rebase, just gotta get xray guns and 4 pieces of uranium which is very easy if done with 3 people.

**Comment by Stealthkibbler** [comment]
@GrayRachnid I know but outside of that its not really something people want to bother fighting because of how much of an annoyance it is.

**Comment by GrayRachnid** [comment]
Well people really need to get gud then /shrug.

I disagree with removing it, maybe up the spawn timer to an hour or 50 minutes, but don't remove it.
And obviously, don't remove it from rotation either.

**Comment by FluffySurvivor** [comment]
Kill blob mulligan and it's fine

**Comment by Stealthkibbler** [comment]
The problem is mainly with mulligan, it just ass blasts rounds into a state of no recovery, even if the blob is somehow killed the damage is usually so colossal that people cant be fucked repairing it because of how popular it is for blobs to kill vital systems.

Also if a blob kills gravity, its gone, for good, there's literally no way afaik to actually build a new grav gen.

**Comment by IgnisCorvus** [comment]
actually it should be: when the blob is dead end of round.
However, the main problem is the crew doesnt want fight the blob until is late. Or they dont have the way to search maint because not all the crew has maint access. 

When the blob is deteted by the automatic warning the access to maint doors should be overide, instead. Because the mostly of the time, the heads or the AI dont do this. 

A coordinate crew attacking the blob meanwhile the engineers setup emitter to destroy the blob can destroy the blob easy, at least in my opinion.

**Comment by Yackitori** [comment]
Just make only 1 blob spawn. If 2 show up, unless science gets xrays, crew's fucked.

**Comment by ShadowDeath6** [comment]
also a huge problem with getting xrays is that there's no widely-known R&D tree to get xrays other than "waste time throwing shit that used to work into the DA for no levels" (at least in my experience)

**Comment by Stealthkibbler** [comment]
@IgnisCorvus This is the problem, they are spawning during other antag rounds, which either provides a free win for the antags or sec or turns the round into an unwinnable stalemate that neither side can win.

**Comment by GrayRachnid** [comment]
>also a huge problem with getting xrays is that there's no widely-known R&D tree to get xrays other than "waste time throwing shit that used to work into the DA for no levels" (at least in my experience)

Why blame the blob because people haven't taken the time to explore the new R&D?

FYI, xrays can be obtained without any of the new shenanigans of boany&R&D. It takes me a minute just look up the the tech needed, and 10~ minutes after to get it.

**Comment by ShadowDeath6** [comment]
Blob is my favorite mode, but mulligan after blob dying is stupid and blob during regular antag rounds is stupid as hell

**Comment by GrayRachnid** [comment]
Remove mulligan, have blob rounds end when blob dies.
As for event blob, lower it's weight to 2 and timer to 60 minutes.
