### ISSUE TITLE
Bring back the better service channel color, maybe command too?

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3621]
At some point service and command color changes were reverted.

**Comment by MegaEmpirical** [comment]
Command has since been changed back so we're half way there now.

**Comment by fluffe9911** [comment]
What are you talking about this is not done we already got new colors you meme

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
