### ISSUE TITLE
Shades immune to die

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#3622]
Issue reported from  Round ID: 19811 (Yogstation 13)

Reporting client version: 512

This round I met a shade who fought a blob head-first, took lasers in the back from his mech buddy, and never took any damage throughout the whole thing.
![image](https://user-images.githubusercontent.com/36427443/48929721-4e034e00-eeb9-11e8-99b5-86032d8631e3.png)
He was hit by the blob itself, by the blob's blobbernaut, by at least one maxcap bomb, and is at 100% health.

**Comment by Altoids1** [comment]
Fixed by #5121 , I think.
