### ISSUE TITLE
B̭̺̜͡l̵ṵ̱͉̖͡ͅeś͈p͖̼͉̥͎͠a̢̞̳̫͈̻̮̬c̦͎̫̣͎̕e̟̬ ̰͙̱̝͉͚ͅl͎͍̲̫͍͕̪͟ǫ̜c͙̳͉̮͍͓̺ḱ̟̬e̻͕̲̺͖̹̟r̵͈ ̮̳̱̲͘i̝͞n̩ͅs͓͓͕̻͎i͖͠d̡͇ę͔ ̝̳̻͉͈͙͜b̟̜̯̲̤̠l̢̻̖͇ụ̵͍͖e̸̗̯s̮̦͝p̠̩͍̹͈á͚̥͈͔c̪̙̦̼̣̗ͅḛ͔͇̙͚͈͙ ̘̱l̹͍o̸͇c̣̗̙͚̰͉k̼̮͢ͅe̖̰̰͞ŕ̼͔͖̜̝̫

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/Yogstation#3639]
![image](https://user-images.githubusercontent.com/7501474/48982261-61dcc900-f0e0-11e8-80ad-ca332c128ec1.png)
D̲̲̩͔̯̣̩o͔̮̩̺̤n͉̩t̵̰̭͓̮̭ ̶̘q̹͚͍͖u̫an̺̺̯͇͙t̵u̲̞͡ṃ̢̰ ̮͕͞p҉̪̝͚̘̭a̱̭̥̠̩d̨͕ ̹̫ḁ̤̪̮ ̼̲̩̮̀ͅb̶̠̪̟͇͈l͍͙͚̙u͙̗̠̜̦̤es̹̻͉͍̺p̹͍a̧̻̟̗̰̳c̮e̮̞ ̫͡l̛̳͙͈o̗̰c͏̱̯k͙͘e͖̤ͅr̀ ̸͙̫̯͚̜ṭ̟͚̥̪̱ơ̙̞̜͚͓̱ ͕͕̥͙t́h͕̠̗͓̹́e̷̯͉͍̣ ͕̯̜͈̞͖͍b̘͓͟l̹͍̘̝̮u͘e̩̝s̸̱̮̭̫p̸a̜̼c͇̰̝̹͔͎e͡ ̪͇̦͢lo̼̳c͕̝̤̻̰ͅk̠͖̼͎̩̳e̠̫̹̗̼͡ͅr͏̪̥

**Comment by Amelia0010** [comment]
oh my fucking god what the actual jesus h christ
