### ISSUE TITLE
TTV Bombs not updating properly

### ISSUE THREAD

**Issue by DiamondSentinel** [yogstation13/Yogstation#3642]
Round ID: 19683

TTV Bombs acting... screwy:

So, the situation that this occurred was thus. A Tritium-Oxygen Bomb was made (258 epicenter, yadda yadda), and was teleported to Lavaland. It was then detonated immediately, or at least triggered. About 3 minutes later (delay was to get access to lavaland), I went down to retrieve the ores, but the bomb didn't detonate. I went to pick it up to inspect it and rearm it at one point, but as soon as I picked it up, it detonated. 

My guess is that nobody was on Lavaland when the bomb was detonated, so it wasn't updated or something? I dunno. Miners were all dead.

**Comment by monster860** [comment]
Theoretically, the updating should happen within 2 seconds. This isn't like Minecraft where if a place is empty nothing gets processed. Everything is processed everywhere whether there's someone there or not.

A possible explanation for this is that process subsystem hung for an entire 3 minutes. Was the game laggy at all?

**Comment by DiamondSentinel** [comment]
I don't remember, but I do not believe it was laggy. And it definitely wasn't multiple minutes worth of laggy.
