### ISSUE TITLE
[Bug] Donator in regular OOC broke.

### ISSUE THREAD

**Issue by Robertruler77** [yogstation13/yogstation#365]
OOC:  : 2 SPOOKEY
OOC:  : WE 2 SPOOKEY

This is literally what we see. Our names don't come up; Only our : is our OOC colour.

**To reproduce**
Step 1. Be donor
Step 2. Talk in regular OOC chat server-side.
Step 3. Become a spectre of the OOC chat.

Donator Chat is fine by the way.

**Comment by FluffySurvivor** [comment]
Ooc tags hate super confirmed

**Comment by Super3222** [comment]
#363
