### ISSUE TITLE
Random event mobs not correctly spawning

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#366]
I dunno if we fixed this yet but we talked about it in coder chat

1. Revenant event fires but no revenant is spawned.
2. Borer event never ever fires / doesn't spawn borers if it does, I think the former.

**Comment by fizzle7** [comment]
Revenant has 20 dead mobs as a minimum, should probably be lowered.
Borers don't have an event attached so they can't be randomly generated.

**Comment by ShadowDeath6** [comment]
@fizzle7 even when the event fires no revenant is spawned

also their event should have been ported by @MacHac but they can't even be spawned in the gamepanel

**Comment by Groxic** [comment]
Still an issue?

**Comment by ShadowDeath6** [comment]
revenants spawn now
@Super3222 have you seen the borer event fire
