### ISSUE TITLE
High capacity water tank ?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#372]
"A specialised high-pressure water tank for holding large amounts of water."
but it holds the same amount of water as a normal one...

**Comment by Super3222** [comment]
High capacity should start with 100000u of water ontop of 1000u.
Normal starts with 1000u of water.

**Comment by ParagonPrime** [comment]
Is it necessary to have a second type? I've absolutely never seen a normal tank depleted.

**Comment by faultlesselm16** [comment]
i have seen a water tank depleted but only when someone is doing botany and that knows what they are doing but thats super duper rare

**Comment by SeikoTheSeal** [comment]
>i have seen a water tank depleted but only when someone is doing botany and that knows what they are doing

Then they would use a sink that has infinite water.

**Comment by 00aquir** [comment]
Atmos has tis special watertank too.
Fighting Plasma fire: one atmos watertank nanofrost shot is 100u = after 10 shots the atmos water tank will get depleted..

**Comment by timkoster1** [comment]
Well, the water tanks have the benefits of allowing more then 5 units to be extracted at a time, making it way quicker.

**Comment by GrayRachnid** [comment]
aquir, it's currently broken. Should be fixed with the promised /tg/ merge. Supposed to have 100,000 units of water, not 1000.

**Comment by 00aquir** [comment]
okay then

**Comment by Greatbigben** [comment]
this should be a extremely easy fix

**Comment by timkoster1** [comment]
This isn't even a bug. A normal container has 1000, and the botany one has like 2000.

**Comment by 00aquir** [comment]
well the description doesn't match the reality, if it's described as "high-pressure water tank", it's supposed to be that.

**Comment by timkoster1** [comment]
It is.
I double checked, the normal one has 1000 and the high-pressure one has 100000
It's called high-pressure because more is fit inside, so it's pressure is high.

What's the bug about that?

**Comment by X-TheDark** [comment]
It is, indeed, bugged. The reagents by default create a holder of 1000 units, so even if you try to put in 100000, it only saves 1000, since that's the amount the reagent holder of the water tank can hold.

**Comment by timkoster1** [comment]
Oh, so that's the problem. I didn't really understand, but yeah, that's a bug.

**Comment by AdamElTablawy** [comment]
This should be fixed now. Re open if not the case.
