### ISSUE TITLE
Remove viro access to viro atmos windoor

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3729]
Virologist already has an entire fortified room to their self. they don't need a place with no cameras to use to store their kills. Alternatively, get rid of the damn flap there and if the flap is going to stay, you should reinforce the walls around the atmos room too.

**Comment by MimicFaux** [comment]
I ded

**Comment by Ktlwjec** [comment]
or add a camera to the little atmos room
