### ISSUE TITLE
[BUG]Straight Jacket issue

### ISSUE THREAD

**Issue by Ahall0943** [yogstation13/yogstation#374]
I tried to get out of a straighjacket after being taken hostage and I waited 5 mins to take it off. It said I succesfully got the jacket off but It was still on me.

**Comment by Super3222** [comment]
Something relevant to add, he was handcuffed as well.

**Comment by Super3222** [comment]
This might be considered a feature. The nerfing of straightjackets may have been reasonable, but at the same time it doesn't 100% make sure someone doesn't get out of it.

This does make sure no one gets out of straight jackets, therefore it's a feature in my eyes.

**Comment by Super3222** [comment]
Any more questions before I close this @Ahall0943?
