### ISSUE TITLE
psicodine doesn't metabolize

### ISSUE THREAD

**Issue by ShattForte** [yogstation13/Yogstation#3768]
## Round ID: 

**20063**

## Testmerges: 

**N/A**

## Reproduction: 

**The "make believe" drug psicodine which is bought from the medical vendor for $100 doesn't actually metabolize in your blood.**

**Comment by ghost** [comment]
By no metabolization, do you mean that the amount in your bloodstream stays constant? Nothing purges it?

**Comment by ShattForte** [comment]
Yeah, stays constant. I haven't tested if Pennetic Acid would purge it or not.

**Comment by ShattForte** [comment]
Adam said in OOC the other day that he tested this, and the usual drug purge drugs (calomel, pennetic acid), doesn't actually purge this chem. You could overdose on this and nothing could be done about it.
