### ISSUE TITLE
Monkey spikes don't seem to work.

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation#377]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

The usual grab intent > reinforce grab > click on spike doesn't seem to do anything anymore.
Clicking and dragging the monkey onto the spike also seems to not work.

**Comment by Kmc2000** [comment]
I'll see if i can fix this

I might be able to

**Comment by Kmc2000** [comment]
can't see anything wrong with it, try reverting to the pre rebase one? (the one that worked)

**Comment by george99g** [comment]
It's probably something to do with the new grab mechanics where you don't actually have a grab object in your hand to click.
