### ISSUE TITLE
Solo changeling can get objective to absorb another changeling

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3776]
Saw this as an objective for a changeling yesterday, and he was the only one. Poor ling had no lings to ling.

**Comment by ghost** [comment]
1. Make an optimistic tider a xenoling
2. Absorb
3. ???
4. Greentext

**Comment by MegaEmpirical** [comment]
I think xenoling is removed now or is about to be.

**Comment by fluffe9911** [comment]
I dont see the problem with this one but whatever

**Comment by MegaEmpirical** [comment]
Same issue: https://github.com/yogstation13/Yogstation/issues/7360

**Comment by MegaEmpirical** [comment]
Though the problem now is that xenoling has been removed so this would be impossible.
