### ISSUE TITLE
Port Goof's PR that splits up food in the crafting menu into different categories/remove TGUI.

### ISSUE THREAD

**Issue by SeikoTheSeal** [yogstation13/yogstation#379]
https://github.com/tgstation/tgstation/pull/19325

Accidently click on food recipes
Opening crafting menu crashes your client every time you do it till new round starts.

TGui is horrible.

**Comment by Super3222** [comment]
No need to make a PR when we're having another rebase.

**Comment by SeikoTheSeal** [comment]
I keep hearing about another rebase for two weeks now. When are you planning to do it? Becouse if its going to take like next few weeks before it happens, then i'll be seriously upset, as this shit is unbearable.

**Comment by Super3222** [comment]
Oisin is the one who said we're going to do it. We've been waiting for weeks on datum antags, and the developer has yet to finish them. I agree, the wait is unbearable, but at the same time there'd be no point towards making PR's porting things when we're going to be porting everything from that same place.

**Comment by FluffySurvivor** [comment]
Cant we just manually port datum antags?

**Comment by Cruix** [comment]
That would not be fun.

**Comment by SeikoTheSeal** [comment]
> at the same time there'd be no point towards making PR's porting things when we're going to be porting everything from that same place.

The point would be actually allowing some people to play the game without issues till the rebase happens.

Playing chef is litteraly impossible for me, and some other people right now. Being unable to access the crafting list becouse it crashes the client instantly. Hell, perfect solution would be to remove the shitty TGUI as a whole and revert back to nanoUI, if someone had time and knowledge how to do it.
Sure, it looks nice, but when it gets into the way of actually being able to play the game, its a shit feature. Just played a chemist round, every 15 or so minutes of using my machines, i had to reconnect becouse dreamseeker started eating up my entire memory, or caused glitches like my entire hud + wall sprites dissapearing.

**Comment by ShadowDeath6** [comment]
tgui is a laggy hell, fuck it

**Comment by Super3222** [comment]
I PR'd this
