### ISSUE TITLE
Labor Camera Bug

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation#381]
12:34:30 - Misty Waters - I think there might be a small bug with the labor camp monitoring console or code?

12:34:30 - Misty Waters - Ticket created by TheBloodWitch

12:35:13 - Slovenian - What kind of bug?

12:36:05 - TheBloodWitch - Well, it has three camera options, mine, maintence, and vending that instead showing different parts of the main station

**Comment by Greatbigben** [comment]
thats been there, also there is a bug with the regular sec camera monitors not showing all locations.

**Comment by Stealthkibbler** [comment]
the console probably has the wrong camera ID set.
