### ISSUE TITLE
Increase windoor durability 

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#3837]
Windoors are made of reinforced glass but it takes little time to break them and people are doing that right after crawling under flaps all the time now.

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.

**Comment by MegaEmpirical** [comment]
Bastards.
