### ISSUE TITLE
fix space bartender spawning on station

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#386]
why play chef or bartender when you can be the SPACE BARTENDER

**Comment by ShadowDeath6** [comment]
cool

**Comment by Super3222** [comment]
#363 eh

**Comment by Greatbigben** [comment]
this is a bug as they are actually spawning in Sec

**Comment by R3DGL4R3** [comment]
I'll work on this if it isn't already fixed.

**Comment by ShadowDeath6** [comment]
@R3DGL4R3 this is fixed in #363

**Comment by GrayRachnid** [comment]
No, this was caused by #363
