### ISSUE TITLE
Why the hell can Aliens stun even the borg ? ?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#389]
There are a few borgs and many humans, how is it fair that aliens cannot be stunned but they can even frickin' do that to borgs?

**Comment by Cruix** [comment]
You can stun aliens by punching them in a mech.

**Comment by 00aquir** [comment]
well.. at least that's 1 man out of 30..

**Comment by timkoster1** [comment]
Xeno's can be stunned like humans and even cuffed.

**Comment by Super3222** [comment]
1. Without it, aliens have almost no counter to borgs without it.
2. It's an RNG chance, and not every disarm will stun them.
3. You'll never know how aggravating it is to fight against a borg as an alien until you actually do.

In conclusion,  it is completely fair that they can stun borgs.

If you want to take out an alien, build a flamethrower or become an engineer borg and use your welder against it.

**Comment by 00aquir** [comment]
Counter what, harm? it's harm vs harm, what's the problem?
As sec borg, both times alien almost took me out, had to go back twice for healing, like it doesn't really matter they immediately stunned me every 3 hits both times (and it was only one alien) I was barely conscious or make it out at all.

**Comment by GrayRachnid** [comment]
Xenos weren't made to be balanced :^)

**Comment by AdamElTablawy** [comment]
good luck fighting an engiborg as a xeno without disarm

>try to hit

>sonics around with VTEC

>spam htis you with welder for 30 damage because sweet 2x damage bonus

>self repairs itslef whenever it takes damage while you have to run and find weeds that it's melting with the welder

>try to escape through vents but it already welded them

>try to run but the doors are shockbolted and it's sounding the harm alarm

>it blows up a welderbomb

>15 more validhunting engiborgs flood in from the sky to kill you sounding their harm alarms

**Comment by Cruix** [comment]
Engiborgs cannot self repair.

**Comment by AdamElTablawy** [comment]
@Cruix 
yes they can

that was added by /tg/

they can selfrepair (w a delay0

**Comment by Cruix** [comment]
What holy crap tg hates borgs why would they do that?

**Comment by Super3222** [comment]
It's one of the many mysteries of life Cruix

**Comment by fizzle7** [comment]
> good luck fighting an engiborg as a xeno without disarm

> try to hit

> sonics around with VTEC

> spam htis you with welder for 30 damage because sweet 2x damage bonus

> self repairs itslef whenever it takes damage while you have to run and find weeds that it's melting with the welder

> try to escape through vents but it already welded them

> try to run but the doors are shockbolted and it's sounding the harm alarm

> it blows up a welderbomb

> 15 more validhunting engiborgs flood in from the sky to kill you sounding their harm alarms

In other words over-exaggeration controls the balancing here.

**Comment by Super3222** [comment]
Like I said before. Try fighting a borg as a Xeno Hunter. You will not win unless you stun them or they're careless.

Besides the stun was nerfed from what it use to be. Xeno > Borg is how it's always going to go, unless you've got an actual vtec engiborg running around / secborg with hacked module upgrade.
