### ISSUE TITLE
Fillable Drink Hats

### ISSUE THREAD

**Issue by Yackitori** [yogstation13/yogstation#390]
Drink hats should be able to hold 2 liquid containers. Beakers, cans, bottles, glasses, ect. It'd be cool if someone made a verb like "Drink Hat" or something, you could be able to take a sip from your hat without taking it off.

**Comment by Kmc2000** [comment]
I actually wanted that adding when i made it, now's the perfect time

**Comment by McDonald072** [comment]
Inb4 put 200 units of meth in the hat and constantly take small sips
