### ISSUE TITLE
Yog Station: Chapel xmas tree spitting out infinite presents to some crew

### ISSUE THREAD

**Issue by Colburn3000** [yogstation13/Yogstation#3901]
Round: 20255

As the title explains. One crew member was somehow able to pull infinite presents from the tree, and as a result was able to bring some lethal weapons and even traitor items into play. Seems that the tree did not add the crew member in question SweetCyanide to the following list, therefore allowing them to pull multiple presents:

(E) (C) (M) took_presents = /list (5)
fillywonk = 1
colburn3000 = 1
magonu123 = 1
aphielanisn = 1
cpthonk = 1

![image](https://user-images.githubusercontent.com/24303426/50167798-f689af80-02b7-11e9-91af-95b27aa73d20.png)

**Comment by ThatLing** [comment]
Partially fixed by removing dangerous stuff
