### ISSUE TITLE
Random Bar Issue: Bar Backroom Doesn't have Appropriate Access

### ISSUE THREAD

**Issue by Colburn3000** [yogstation13/Yogstation#3931]
## Testmerges:

null

## Reproduction:

In the fancy space bar the bartender didn't have access to the back room. Reproduce by double checking the bar backroom airlock privileges for each of the bars that spawn.

**Comment by ThatLing** [comment]
@nichlas0010

**Comment by Amelia0010** [comment]
god dangit
