### ISSUE TITLE
Ninja equipment invisible

### ISSUE THREAD

**Issue by fizzle7** [yogstation13/yogstation#394]
Ninja shoes and mask didn't show for one round, not sure if it happened only once. They don't show on his icon and on examining him. VV shows he had mask and shoes, ninja default ones. Visibility and alpha are all default, 1 and 255.

**Comment by SKR6DarkVoid** [comment]
Looks like sprites are missing, I'll see what I can do.

**Comment by SKR6DarkVoid** [comment]
Could be a code issue too, looking at it, seems the states could be wrongly defined?

@Super3222 @oisin100 

`	icon_state = "s-ninja"
	item_state = "s-ninja_mask"`

**Comment by Stealthkibbler** [comment]
This is most likely due to missing sprites, I asked admins about this and they said nothing was wrong, although when I tested localhost the issue was there for me. I'll Re-open my PR.
