### ISSUE TITLE
Bad wizard doesn't get a loadout

### ISSUE THREAD

**Issue by SomeguyManperson** [yogstation13/Yogstation#3942]
If a bad wizard midround antag is rolled the wizard doesn't actually get a spellset, making them less of a shit wizard and more of a cosplayer

**Comment by Time-Green** [comment]
I got memewizard yesterday and got instant smoke, instant blind and barnyard
May be just one of the loadouts not working

**Comment by ThatLing** [comment]
@nichlas0010

**Comment by fluffe9911** [comment]
feature obv
