### ISSUE TITLE
Pokeballs

### ISSUE THREAD

**Issue by krgii** [yogstation13/yogstation#395]
Add pokeballs to cargo supply console and to mining vendors that let you catch simple animals and can be emagged to catch people.

**Comment by Kmc2000** [comment]
I'll sprite this and the pokemans if someone wants to code this

Also this should be a traitor item IMO, 16 TC, trainer kit, comes with snazzy belt : hipster shorts, trendy jacket, baseball cap and hair wig and 6 pokeballs

**Comment by Super3222** [comment]
Probably not going to become a thing in game. If someone wants to actually spend time on this, make sure it's admin-only.

**Comment by krgii** [comment]
Everyone should know the joy of pokeballs. Besides, if only traitors have it it'll be useless since once you see one everyone will shout traitor and you'd never be able to wear the cool jacket and hat since it's a giveaway you're a traitor.

**Comment by ShadowDeath6** [comment]
wouldn't fit in regular game, immershuns, etc
admin only is fine though

**Comment by SKR6DarkVoid** [comment]
Yea, administration only sorta feature.

IMO, it's space station not pokemon.. we had issues with pony sprites so I don't think Xantam would agree with pokemon either.

**Comment by Kmc2000** [comment]
>griefer
>TRAINER KMC CHALLENGES YOU!
>Throws pokeball
>griefer trapped for enternity
>station saved


Add a throw pokeball option in player panel too while you're at it

**Comment by Yackitori** [comment]
Change the freeze tool to this.

**Comment by R3DGL4R3** [comment]
I already have a mass of pokemon icons we could use.I'm sure a few people remember me sending them via cargo.

**Comment by ToGWtF** [comment]
New dehydrated carp-like traitor item. Spawns a random re-syndie sprited pet (Syndicate Ian? Evil Memekitty?). Can be player-controlled or AI.

**Comment by Alek2ander** [comment]
AR goggles that show you pokemon

**Comment by ParagonPrime** [comment]
SPESSMON GO as a PDA cartridge

all yes
all time

**Comment by Robertruler77** [comment]
Admin event thing, like once every couple months of this would be funny.

**Comment by oisin100** [comment]
Let the memes die.
