### ISSUE TITLE
Mining Shuttle Warning

### ISSUE THREAD

**Issue by MayhemSailor** [yogstation13/yogstation#397]
[issue] folks keep getting spaced at the mining dock when shuttle is moved.

[suggestion] A delay and warning be installed for the mining shuttle before it moves. Something like the siren that plays for the disposal outlets before they eject items, or ion sparkles to warn a player that the shuttle is about to move.

[intended result] less accidental spacing

**Comment by SeikoTheSeal** [comment]
#306

**Comment by Super3222** [comment]
MacHac's lavaland PR prematurely covers this but, only somewhat without the warning. You should leave a comment on his PR about this, since it's not a bad idea.

**Comment by MayhemSailor** [comment]
The issue seems to be that people headed into the airlocks towards a shuttle that is being called remotely are getting spaced. The request is for a delay following console request and some type of audio/visual cue of impending movement.

**Comment by R3DGL4R3** [comment]
I can handle adding a text cue.Piece of cake.

**Comment by AdamElTablawy** [comment]
fixed
