### ISSUE TITLE
Unable to lock lockers with ID in PDA

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation#401]
You used to be able to to lock lockers by clicking on them with any item as long as you had your ID/PDA in your ID slot, Now you cant.

Reported by Slovenian.

**Comment by ParagonPrime** [comment]
Notably unlocking still works.

**Comment by SeikoTheSeal** [comment]
You can alt click the locker now to lock/unlock it as long as the ID you are wearing has proper access.
