### ISSUE TITLE
Pump in wrong direction

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#4053]
In sec maint atmos room

![ss13-atmosbug-secmaint](https://user-images.githubusercontent.com/16806055/50677400-e2ed8100-0ff9-11e9-9131-17e7c18464c8.png)

**Comment by ghost** [comment]
Which one? The top one?

**Comment by 00aquir** [comment]
The blue pipes supply the station with air, coming from Atmospherics. This one leads to security, the upper pump always faced left.

**Comment by Ktlwjec** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/4150
