### ISSUE TITLE
[Mapping] Lattices and catwalks placed by aft port solars and engineering do not spawn

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation#406]
I thought the missing lattices and catwalks were due to someone messing up the map, but when I take a look at them in DM, they're there. Normal turfs still seem to work, it's just specifically lattices and catwalks that don't spawn.

**Comment by Kmc2000** [comment]
They have to spawn on space, if that helps?


They will not spawn when any other kind of turf is on that same tile

**Comment by Notamaniac** [comment]
In DM
![latticebug](https://cloud.githubusercontent.com/assets/17688334/17083940/60ec1bac-51a7-11e6-8d9e-1c662a7ed2dd.PNG)
In game
![lattice bug 2](https://cloud.githubusercontent.com/assets/17688334/17083942/6e7a23a4-51a7-11e6-82ac-f586fd30d565.PNG)
