### ISSUE TITLE
Can't see disease status using health HUDs (nor as AI/borg)

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4065]
Exactly as stated. I've had this issue for a while now though I used to be able to see at least negative diseases and just process of elimination. At least one other person as expressed this same issue to me.

**Comment by MegaEmpirical** [comment]
....as of fucking today I can now see them, after being unable to for a very long fucking time. Will close later today if this persist.

**Comment by MegaEmpirical** [comment]
Back to not working, great.

**Comment by GenericDM** [comment]
I have the same issue, all I can tell is if someone has a virus or not.
