### ISSUE TITLE
Missing wires in medbay maintenance

### ISSUE THREAD

**Issue by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [yogstation13/yogstation#407]
There are a few missing cables just north of biohazard disposals. The wires on the bottom and top should be connected.
![image](https://i.gyazo.com/1cce0c19937c1673aee028f552240eb0.png)

**Comment by 00aquir** [comment]
it's like this for ages. Sometimes I like to connect them but telecoms power can last for any round.

**Comment by ShadowDeath6** [comment]
>been like this for years

pretty sure it's connected

**Comment by 00aquir** [comment]
nah, it was like this for ages. Nobody noticed it :)

**Comment by 00aquir** [comment]
I don't remember it being fixed, because before rebase we definitely had this unconnected part in med maint.

**Comment by Cruix** [comment]
Fixed by #675
