### ISSUE TITLE
Mark Morph's Created by Gluttony's Blessing as Antags

### ISSUE THREAD

**Issue by Colburn3000** [yogstation13/Yogstation#4082]
Morphs created by gluttony's blessing are not labeled as antags, they retain whatever status the former mob held. Under the current rules this means they can't glomp things. If this is the intent, close this and call me a triple nerd, but if this is not intended please make gluttony's blessing change someone to either an antagonist or at least the animal class.

**Comment by MegaEmpirical** [comment]
I always treated it the same as this:

2.2.1: Rules still apply to creatures. If you become an animal you keep your antagonist/non-antagonist status. When not antagonist, do not use your new form's abilities to grief. This includes syndicate cyborgs. Do not split as a slime in public places.

**Comment by ghost** [comment]
@MegaEmpirical Because the mob is deleted on transform, there is no way to confirm if someone got poisoned by gluttony's blessing willingly or not.

Also the intent of the ruin when it was added to /tg/ was free antag, so

**Comment by MegaEmpirical** [comment]
That's why I always treated it as non-antag since it wasn't via a staff of change.

Interesting origin though.

**Comment by ghost** [comment]
Involuntary transformation usually makes the person hostile, not just the staff of change.

Then again, I don't think there's been a ruling on that all around by admins- last I heard, a traitor who announces their plan to slime-gas the entire medbay for hijack so that the slimes kill everyone got the OK and so did the slimes, but w/e

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
