### ISSUE TITLE
Disability/Disfigurement character config options.

### ISSUE THREAD

**Issue by R3DGL4R3** [yogstation13/yogstation#412]
Options to choose various disfigurements/disabilities would be really nice for character building.

You could be that one armed underdog detective that seems to win every fistfight due to sheer robustness.

Every other server has them.Might as well eh?

**Comment by Cruix** [comment]
You could be Taco after 510 and be blind every round, and still be robust.

**Comment by SeikoTheSeal** [comment]
Having more customization options is always good.

**Comment by ToGWtF** [comment]
I want to be able to spawn with no arms or legs and name my character "Dog" and bark at people on the arrivals shuttle. Make it happen and i'll start coding again kthx

**Comment by Alek2ander** [comment]
Only if you have chainsaws for hands instead

**Comment by Super3222** [comment]
Well. If we're going down the path of adding disabilities / disfigurations, we might as well add augmentations like being able to have a single robotic limb.

**Comment by SeikoTheSeal** [comment]
Prosthetics like paradise would be cool.
