### ISSUE TITLE
Floor clowns can make people permenantly invisible and blind, but not gib.

### ISSUE THREAD

**Issue by Tummywumbes** [yogstation13/Yogstation#4127]
## Round ID: 20700

I was playing round as sec officer when suddenly a floor clown came up and "ate" me. I literally had no idea that floor clowns even existed so I had no clue this was a bug at first. I got sucked into the floor, and, according to the admins, I was supposed to be gibbed. Instead I became invisible and blind, but I could still talk, hear, use the radio, move around, interact with other people and objects, and use items like normal. Right clicking on the tile that I was standing on didn't display a sprite of my character (like it would for someone with the invisible superpower from genetics).

Here are a few screenshots if it helps.
![sdafasdf](https://user-images.githubusercontent.com/34947832/50936365-674a6480-143d-11e9-990f-30ed32b49568.PNG)
![sadfasdfasdf](https://user-images.githubusercontent.com/34947832/50936369-6a455500-143d-11e9-9af0-0292ebc3c3a9.PNG)

Sadly, I have no idea what I specifically did to make this bug occur, but I was running around in medbay when it happened. The floor clown appeared on one of the vent pump tiles, so perhaps it being on a vent pump tile caused it to act up or something.

**Comment by ThatLing** [comment]
@fluffe9911

**Comment by Gh0sT2242** [comment]
How to re-enact: 
Step 1:get pulled in by floor
Step 2:clown dies
Step 3:viola

Shouldbe able to fix by changing how long it takes cluwne to grab you/how long it takes for it to go back down
