### ISSUE TITLE
Error with player panel game logs

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#4135]
Round 20731 for logs (game logs).
There's almost 2000 lines of Yogurt and Gh0st checking the player panel for tbanner.

Quote from Yogurtshrimps himself: "I think there's a bug then with if someone is froze frozen and dead and you try to open their player panel the game literally fucks up hard like real bad"

There's something in runtime logs related fix pls.

**Comment by ThatLing** [comment]
```
There's something in runtime logs related fix pls.
```
why not post it????

**Comment by Ktlwjec** [comment]
> 
> 
> ```
> There's something in runtime logs related fix pls.
> ```
> 
> why not post it????

[2019-01-11 08:02:14.310] runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
 - To avoid this safety check, set world.loop_checks=0.
 - proc name: check for rights (/datum/admins/proc/check_for_rights)
 -   usr: Moja Manley (/mob/dead/observer)
 -   src: yogurtshrimp69\'s admin datum ... (/datum/admins)
 -   usr.loc: the holodeck projector floor (150,166,2) (/turf/open/floor/holofloor/plating)
 -   call stack:
 - yogurtshrimp69\'s admin datum ... (/datum/admins): check for rights(null)
 - check rights for(YogurtShrimp69 (/client), null)
 - check rights(null, 1)
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - ...
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))
 - YogurtShrimp69 (/client): Show Player Panel(Unknown (/mob/living/carbon/human))



There's a lot of these.

**Comment by Ktlwjec1** [comment]
round 28259 too
