### ISSUE TITLE
Blackbox save file might be fucked.

### ISSUE THREAD

**Issue by SeikoTheSeal** [yogstation13/yogstation#414]
Kill colossus. Expect to find trinkets from other people inside, pictures of their butts and shit. Open box, its empty. Know for sure that at least two other people killed him before and stuffed shit inside (Mac and Stealth). Cry.

If someone could test it on the server and see if its fucked or not. Box should contain my personal items.

**Comment by Super3222** [comment]
I've never had any problems on my own local server with it. I'm pretty sure it acts like a smartfridge.

**Comment by SeikoTheSeal** [comment]
The issue is that the items are not stored between rounds.

**Comment by Super3222** [comment]
Ahh, I see what you mean.

**Comment by Notamaniac** [comment]
I killed the collosus and found a shaft miner PDA, a silver ID and a bluespace wormhole projector, no names attached.
