### ISSUE TITLE
Re-add borer yummies xoxo

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#4162]
this is an URGENT feature request I've gone too long without them

https://github.com/yogstation13/yogstation/search?q=borer+yummies&unscoped_q=borer+yummies

**Comment by fluffe9911** [comment]
Once we get borers back I will readd them lol

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
