### ISSUE TITLE
Show/Hide OOC does not disable OOC messages from Discord

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4173]
Exactly as title states.

**Comment by Ktlwjec** [comment]
https://github.com/yogstation13/Yogstation-TG/issues/3414

**Comment by MegaEmpirical** [comment]
Ah, I did not see that. Thank you. I am with Mongoose on this.

**Comment by Altoids1** [comment]
Closed based being duplicate.
