### ISSUE TITLE
Bugged chat settings

### ISSUE THREAD

**Issue by sam0oneau** [yogstation13/Yogstation#418]
Problem Description: Some chat settings are bugged currently. 
Attempting to increase or decrease line height seems to break chat (Sets chat line spacing to -0.2, -0.1, 0.1 or 0.2.)
Options are also currently misaligned.

What did you expect to happen: Settings aren't doing what they state and are partially misaligned and sometimes don't work as expected.

Why is this bad/What are the consequences: Broken chat settings

Steps to reproduce the problem: Using the change line height setting in chat settings. The whole chat settings seem incredibly bugged. If you try to click specific settings they seem misaligned.

![tg bug](https://user-images.githubusercontent.com/30634117/38907062-da47ad5c-42b1-11e8-89c3-8d0bf6b7165b.png)

**Comment by ThatLing** [comment]
Reproducible by decreasing the line height to 0.

**Comment by sam0oneau** [comment]
I had it that it was any button would cause this issue. If I clicked decrease line height it would instantly decrease to whatever value it is in button. Maybe bugged byond??

**Comment by sam0oneau** [comment]
*it is in picture

**Comment by sam0oneau** [comment]
When I get in I can try and find a way to record what happens for me.

**Comment by ThatLing** [comment]
Don't set the font size to something tiny. You can reset it by clearing IE cookies and clearing byond cache.
