### ISSUE TITLE
Stock Computer Deletes Half of Your Shares

### ISSUE THREAD

**Issue by Colburn3000** [yogstation13/Yogstation#4190]
## Reproduction:

Seems to only be an issue for certain stocks.
Reproduce by:
1) Buying a stock.
2) Close and reopen stock computer browser
3) Attempt to sell stock
4) The following will happen.

![image](https://user-images.githubusercontent.com/24303426/51255885-1ae9b200-1972-11e9-9160-38a2181f331a.png)

It's really frustrating that this won't let you swing trade.

![image](https://user-images.githubusercontent.com/24303426/51255533-74051600-1971-11e9-8639-3cb5e055854f.png)

**Comment by Gh0sT2242** [comment]
In what stocks does it delete them?

**Comment by ToGWtF** [comment]
There is a stock even that halves your stock but skyrockets the prices. This seems to be the case with both stocks in the picture provided
