### ISSUE TITLE
Remove craftable surgery tables for unanchorable ones

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation#42]
/tg/ lets you build a surgery table for 2 metal rods and a single bar of silver.  remove and change to anchorable and orderable from cargo??

**Comment by Bawhoppen** [comment]
whats wrong with it

**Comment by ToGWtF** [comment]
Nothing wrong with it. I added orderable tables to cargo, that could be unanchored, to yogs. Was getting opinions on which people prefered
