### ISSUE TITLE
Emags do not work on wall safes

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4202]
I know they're not hard to get into, but of all things for them to not work on? I didn't bring tools thinking this would be the issue I would run into.

**Comment by HomocidlePancakes** [comment]
Thats because you have to use C4 to open them you dumdum

**Comment by Time-Green** [comment]
they're not electronic, so yeah

**Comment by MegaEmpirical** [comment]
If that was the case then you wouldn't need to use a multitool on them to reset their memory.

**Comment by Time-Green** [comment]
Eh, either way they aren’t meant to be emaggable

**Comment by MegaEmpirical** [comment]
Is there a reason they shouldn't? Of all things electronic for them to not work on, this strikes me as odd.

**Comment by Time-Green** [comment]
They’re already magical all acces cards, and saves are meant SPECIFCLY not to open.

**Comment by MegaEmpirical** [comment]
Then shouldn't it be harder to hack them? All you have to do is spam the multitool until it says memory reset. They're the least secure thing on the station.

**Comment by Time-Green** [comment]
Wait really? That’s dumb

**Comment by MegaEmpirical** [comment]
![image](https://user-images.githubusercontent.com/36208065/51442000-0412ca80-1ca6-11e9-8298-23a3882eb607.png)

and it does work like this, they are not safe at all.

**Comment by ghost** [comment]
It takes a long time for that to work, @MegaEmpirical -You can get into literally any object by shooting it enough, but each multitooling attempt takes around 15 seconds.

**Comment by Bibby0110** [comment]
I remember stealthing that safe, what a bummer. C4 it if youre nukeop 11/10 faster
