### ISSUE TITLE
Shuttle Manipulator occasionally bugs,only loading half some shuttles.

### ISSUE THREAD

**Issue by R3DGL4R3** [yogstation13/yogstation#421]
Dunno what the issue is but it just happened.Was browsing shuttle templates during a quiet round,and tried to reload the original when I was finished.Only loaded half of it,with the outside rim being missing.Not a major issue as there are plenty of regular shuttle templates but could be a disaster in some cases.

**Comment by Alek2ander** [comment]
Shuttle templates expect the /tg/ shuttle as original. Yog uses a larger default shuttle.

**Comment by Alek2ander** [comment]
Not fixed

**Comment by X-TheDark** [comment]
Yogstation shuttle loads properly after I load another shuttle in, unless you can provide something more concrete than "doesn't work", please don't bother reopening this.
