### ISSUE TITLE
Yogspubby security atmos distribution line doesn't work

### ISSUE THREAD

**Issue by Mqiib** [yogstation13/Yogstation#4232]
Issue reported from  Round ID: 20895 (Yogstation 13)

Reporting client version: 512

The teal pipes (and vents connected to them) used in the distro line for the security wing of the yogspubby station cannot be unwrenched and don't connect with regular pipes like they should. The scrubber pipes work as intended, but the distro pipes need to be replaced for security to get any air. The issue is most clearly seen where the layer manifold is supposed to connect to the pipes coming from the small atmospherics room in maintenance southwest of security, but instead adamantly refuses to connect with any pipe other than the bugged distro line.

**Comment by MegaEmpirical** [comment]
Pretty sure I noticed a disconnected meter over there too.
