### ISSUE TITLE
SUPER FIX MY TAGS REEEEEEEEEEEE

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation#426]
only senior coders have a tag and color, coder inits and coders dont
issue:
![no tags](https://cloud.githubusercontent.com/assets/16919472/17214764/20761502-54e3-11e6-87bf-4d5e913e5837.PNG)

@Super3222 @Super3222 @Super3222 @Super3222 @Super3222 @Super3222 @Super3222 @Super3222 @Super3222 @Super3222 @Super3222 @Super3222 @Super3222 @Super3222 
pls fix it already

**Comment by Super3222** [comment]
https://github.com/yogstation13/yogstation/pull/363

**Comment by FluffySurvivor** [comment]
no you didn't fix them, i am talking about how I don't have a "coder" tag

**Comment by Super3222** [comment]
Next update you will
