### ISSUE TITLE
Clockcult warops 5 minute count starts before round starts, effectively making it 2 minutes

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/Yogstation#4260]
You are meant to have five minutes untill you can't go war clockcult. Instead:
"You don't have 4 minutes anymore. It's bugged. It's 5 minutes from when the round is "started"
So you have like 2 minutes."           -DiamondSentinel, discord salt
Maybe nukeops war is bugged as well, maybe timers are fucked as whole

**Comment by Lostlarry** [comment]
well its 300 sec since the heralds beacon spawns if there is a round start proc call please tell me so i can fix it

**Comment by adamsong** [comment]
This has been fixed
