### ISSUE TITLE
Singularity engine bay windows block radiation from the PA

### ISSUE THREAD

**Issue by Nirnael** [yogstation13/Yogstation#4263]
Thanks to @nichlas0010 for solving this. Normal windows in front of the PA absorb radiation which means leaving the PA on at 0 extinguishes the singularity. Leaving it at 1 is too much and makes it grow. Requires the engineers to babysit the singularity and feed it every so often for 10-20 seconds by pressing two buttons and then leaving. Solution is to swap to plasma windows apparently because they don't absorb rads, and make the shutters rad-proof or rad-blocking or whatever the flag is because it will possibly irradiate engineering. Talk to nich if you want more info.
Relevant breaking point: https://github.com/yogstation13/Yogstation-TG/pull/4229
Seems the solution is not that simple.

**Comment by 00aquir** [comment]
Yes the sing irratiated not just into Engineering, but through reinforced walls, engineering space, which means you cannot fly (even further away) in space without getting irradiated...
