### ISSUE TITLE
Xenobiology timestops are too OP, plz help

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/Yogstation#4266]
Xenobiology is able to produce cores that let them use timestop effect at will (same as wizard's one - stuns projectiles and people in field)
With new addons, xenobiology is able to produce said effect en masse
They are bad and unbalanced because:
 1. They can be stacked, chainstunning your enemy
 2. They are guaranteed to *not* affect the one who made them
 3. You can have a whole bag of those 
 4. They stop enemy projectile attacks
 5. They create area of effect that lasts for a while
 6. They are ass long

They have been rampantly abused for a month by xenobiology players to kill every opposition that there is, combined with methspeed and *other xenobiology powers*.
Can they be nerfed? It's not fun to fight against, it's impossible to fight against.

**Comment by Deamane** [comment]
Yeah as a personal anecdote of something that happened recently, I went to go take down a threat that the AI had reported, I go in there and attempt to stun the guy to no avail, so I prime a flashbang right before the guy tosses his time stop. The stupid part is even though he proceeds to get hit by the flashbang he has enough time to recover entirely, and strip me halfway down before the time stop wears off.

That would be annoying as is, seeing as time stops are ranged, an area of 3x3 (or so?) and can be hurled infinitely if xeno is done right. But to top it off here I managed to land a bola on the dude afterward and ran up to stun him, but the guy also gets a free perma meth speed+stun recovery so he gets up after half a second and disarms me. It's really quite ridiculous that they get all these crazy things for playing some mini game for a half hour.

I think either time stop needs to be removed or heavily nerfed, and the light pink meth stuff should have some kind of downside or a nerf.

**Comment by Notamaniac** [comment]
irrc the sepia chilling extract is being nerfed to one use on the tg codebase.
doesn't help if someone just takes a bio bag full of sepia extracts but eh, balance and ss13 don't go together

**Comment by GenericDM** [comment]
#4269

**Comment by ghost** [comment]
I'd like to point out chainstunning with them is extremely unreliable - I tried getting it to work several times to no avail.

Aside from that, why not make the cores affect the user as well, and have the timestop have a starting lag (take gold cores as an example)? The time stop will now require at least a bit of skill to hit people with.

**Comment by Ratvar** [comment]
Merged PR does absolutely nothing with chainstun problem

**Comment by ghost** [comment]
merged PR fixes the chainstun problem for sepais, which is the only actual problem

the other chainstun requires filling your inventory with sepia cores, which takes a lot of inventory clog, or using a biobag for it, and biobags don't automatically shift empty cores from the stack of 25 cores so you can't just constantly chain w/o some inventory fiddlin

the chainstunning problem is nonexistent

what IS a problem is that timestop is available at all and i'll probably remove timestop from slimes entirely
