### ISSUE TITLE
Handcuff shenanigans

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#428]
Because who doesn't want more stuff to do with handcuffs?

So two ideas:

_1: Handcuffing to pipes, wires, and grilles_
Ever sexually identified as a suffragette or protester?
No?
Well now you can, by handcuffing yourself (or others) to grilles, wires, and pipes!

Takes less time to uncuff than from chairs, and pipes have a unique feature by where you can travel the length of the exposed pipe until the pipe ends. If you step on a tile where there IS no pipe (and the floortile is removed) you free yourself from the pipe.

Ditto applies to wire, but with an added twist; electrifying the wire will shock the person cuffed to it!

_2: Handcuffing one person to another_
Shawshank redemption time!

By clicking on a pair of handcuffs with an empty hand, you make "double cuffs", which puts one ring of cuffs in each hand. You can then use one of these rings on a person and then the other ring on yourself/another person

Has both a benefit and a weakness:

The bad news is that the prisoner can still use their non-cuffed hand (though resisting out of cuffs takes longer)

HOWEVER, the person cuffing automatically pulls the cuff-ee along at full speed. The cuff-ee cannot pull the cuffer while he is standing. If two people are cuffed by a third person, they both suffer from heavy slowdown.

If either person is downed (not resting, but stunned/asleep, to prevent abuse) the standing person will move significantly slower for the duration.

Useful for transferring multiple unruly prisoners and other such things.

**Comment by timkoster1** [comment]
This is awesome, however the slowdown is unnecessary.

PRISONER TRAIN CHOOK CHOOK

**Comment by puremanbird** [comment]
I like this idea. It would make prisoner transfers a more common thing. Right now any idiot greytider can just run up, grab the guy, and run away at top speed.

**Comment by Alek2ander** [comment]
You can buckle people to heat exchange pipes for fun and torture
