### ISSUE TITLE
Diagnostic HUD Broken

### ISSUE THREAD

**Issue by DiamondSentinel** [yogstation13/Yogstation#4285]
Diagnostic HUD currently does not show any of the information it was originally supposed to, including borg/drone power, door status, mech status, etc. Instead just shows everyone who you can see the face of as a HeadRev, except heads of staff, who get an exclamation mark. 

Yogurt thinks it's got something to do with the "Face of the Revolution" change or whatever. I dunno, check the Discord.

**Comment by GenericDM** [comment]
![image](https://user-images.githubusercontent.com/34109002/51720274-c8f3fc80-2001-11e9-8169-b652fd9e662f.png)
me, as the AI

**Comment by Ktlwjec** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/4286
