### ISSUE TITLE
Useless Scrubber in Dorms

### ISSUE THREAD

**Issue by nesisknesis** [yogstation13/Yogstation#4288]
## Round ID:
21011

## Reproduction:
Scrubber 5 in Dorms on yogstation has no pipes at all connected to it.
![image](https://user-images.githubusercontent.com/37936685/51768055-0d050100-20d7-11e9-8028-c1ab7c4b1e28.png)

**Comment by MegaEmpirical** [comment]
Huh, and it's the only scrubber for the common area, and there is no vent either.
