### ISSUE TITLE
Send an alert to admins/discord whenever certain AI laws are uploaded

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#431]
Chiefly Antimov and OxygenIsToxic, but others may also want to be carefully watched.

**Comment by Alek2ander** [comment]
Admins are already alerted when AI laws get changed

**Comment by ParagonPrime** [comment]
yeah but are they specifically told what the law is

**Comment by FluffySurvivor** [comment]
yep

**Comment by ParagonPrime** [comment]
k am retard
