### ISSUE TITLE
Medical Blankets for Virology.

### ISSUE THREAD

**Issue by nesisknesis** [yogstation13/Yogstation#4314]
Currently, Virology has the normal white blankets which are boring. Would be nice if they were placed with the medical blankets with the blue cross.

**Comment by Firewolf34** [comment]
Edit: Nevermind, I'm an idiot, I was looking at the TG version. WHOOPS!

**Comment by Firewolf34** [comment]
This has inspired me to make a new type of blanket, a better type of blanket. A blanket for the ages. A blanket we deserve, but not the blanket we need right now.

![new-blanket](https://user-images.githubusercontent.com/2159739/51969973-5c329500-243b-11e9-83dc-3720a292ff34.PNG)

**Comment by Firewolf34** [comment]
This should be closed now, PR was merged.
