### ISSUE TITLE
3 Air alarms in Virology

### ISSUE THREAD

**Issue by nesisknesis** [yogstation13/Yogstation#4315]
## Round ID:
21072

## Reproduction:
There's 3 air alarms for virology, all with the same name. Due to only needing 1 air alarm to control all atmos systems for a room and it being relatively small, there should really only 1.
![image](https://user-images.githubusercontent.com/37936685/51868715-88b8b500-2346-11e9-868d-b548b9df3fde.png)

**Comment by Amelia0010** [comment]
There's three air alarms because there's 3 somewhat large rooms. Air alarms only detect atmos on the tile they're on, so if one room gets filled up with plasma the air alarms in the other rooms won't trigger.
