### ISSUE TITLE
remove the drone fabricator

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation#433]
it just enables griefers to have infinite lives(during blob especially) and hardly ever brings people back into the game as a drone with all the new lavaland ghost roles

derelict drones should fufill this role since they get niche hats, derelict drone master race 2556

**Comment by Jc1469** [comment]
I agree.  I see more drones griefing and breaking the rules/their laws than I do repairing shit.
And with all the lavaland crap, there really isn't much use for it.

**Comment by EMT321** [comment]
The PR of this was closed. Can this issue be likewise closed? @Shadowdeath6
