### ISSUE TITLE
ADAM'S REALLY COOL BORG IDEAS (99% lagfree!) (BORG BALANCE CHANGES ALERT) (MEME ZONE)

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#436]
Okay so I am still dealing with legal issues and somewhat drunk and also in mexico so forgive me but this may be below my usual qualities (and also why im not on the server)

Anyway
1. BORG NERFS TO MAKE IT LESS (HAVE A FLASH RD CONSOLE OR ION RIFLE OR DIE TO A SECBORG)

-Borgs slow down when damaged (not super severe but similar to how humans are slow as ass when almost ded

-Add an ability to tie up/disable a borg's modules with something like cable coil or duct tape which takes ten seconds for the borg to break and regain use of the module (takes a couple seconds)

-make borg covers pop open if borg drops to 50% health

-Make borgs movement confused if passing over foam

-Make acids/pyrotechnic chemicals do burn damage to borgs

-Make tazer shots drain some cell battery from borgs (low amount, like 500) & mute

-Make stunbatons confuse and slow borgs on hit and stun (2) Must be on, consumes extra energy from baton (5 charged hits tops on a highcap cell

-Make borg health 75% the standard unupgraded

-Make AOE flash also affect borgs in melee range.

-EMPs apply the druggy overlay to borgs temporarily.

-Borgs get the nearsighted/welding helmet overlay below BAD integrity.

BORG BUFFERINOS IN TURN
- Borgs don't take damage from lava, but are extremely slow in it and can get stuck.
- Flashes do not blind borgs, but stun and mute them, and the stun is shorter.

-Borg flashes have 30 uses before burning out instead of the RNG burnout it has now

-Borgs are slightly faster than before.

-All borgs have the HARM ALARM by default.

-Emp's drain less cell and stun for less. They also do not knock borgs unconcious, but do mute them, and unequip all modules
- Flashbangs do not stun borgs, but blind them.
- Borgs all have zipties by default.

-Borgs have inbuilt voice recorders and remote signallers that can be accessed via a menu.

-The robotics control console 'destroy' option does not instakill borgs. It does 30 damage a tick when triggered and drains cell by 3000 charge a tick. It also has a 3 second transmission time, longer if the borg is not synced to an AI, or if the AI is dead. When the health reaches 0 the borg explodes as normal.
If the borg is not destroyed by 8 seconds, the self destruct sequence is aborted.
- Explosions do 40% less damage to borgs.

MODULE SPECIFIC BUFFS/NERFS
ENGIBORG
- Engiborg welders consume power as long as they are turned on

-The RPD consumes as much power as the RCD
- The fire extinguisher is replaced by a nanofrost launcher/metal foam synthesizer, similar to the one in atmos.

-Engiborgs are not affected by space wind or singuloth pull.

-Engiborgs have a tile synthesizer- letting them choose between wood, regular, reinforced and light tiles.

MEDIBORG

-Inbuilt bruise pack/ointment similar to how mediborg also has gauze

-Mediborg injector has an additional variety of chemicals, including- oxylandrone, potassium iodide, antihistamine, mutadone, saline glucose, and morphine (for sedation)

-Mediborg beakers can be put in chemistry machines and withdrawn, so medborgs can use chemmasters.

-Mediborgs can broadcast health status and location of those being treated to med channel similar to how medibots do it.

-Mediborgs now have a penlight inbuilt, and surgical manipulators (for moving/transplanting organs, so they can only carry organs and act as hands for surgical steps otherwise)

JANIBORG

-Trashbag can be activated to process items inside into metal, cardboard, and glass

-Soap is nanotrasen soap, if emagged becomes syndie soap

-Glorious janiborg mop never needs to be re-wetted

-Automatically dries tiles it passes over (toggle ability, drains power fast)

-When emagged, if it drives over someone lying prone they take 20 burn damage, and they scream. Fluff reason is that emagged janiborgs leave acid under them.

SECBORG

-Has an energy bolas launcher-synthesizes bolas and launches them. Bolas do not stun, but slowdown, and can be resisted out of quickly-read the code on bolas

-Stunbaton consumes significant amounts of power to use

-Has a forensic scanner

-Has a JUSTICE HELMET

-Has zipties and harm alarm

All other modules it had previously removed

-Moves slower than other borgs.

(Intent is to combine peacekeeper and secborg-borg is slow and has no ranged stuns but has capability to disorient opponent, slow, and stun in melee range)

PEACEKEEPER

-lol fuck off eggborg, removed

ROBOTICS-DEPENDENT UPGRADES

-Roboticists can reinforce borgs with plasteel, slowing them but making them more durable (125% health). Can be additionally reinforced with uranium, making them far stronger (200% health) but very slow and using more charge.

-Can have metal substituted with rglass, making borg faster, but far more fragile.
- Can have a cell plating of plasma installed, making cell deplete at 50% the normal rate but removing borg fire invulnerability.

-Can have a reflective module inserted, requiring diamond gold and plasma, which makes borgs weaker to melee attacks and flashes, but  gives them ablative-armor chance to reflect incoming energy attacks.

-Can have a reactive module attatched, which causes the borg to take less damage from melee attacks, makes them flashproof, and makes them weaker to ranged attacks.

-Can have an NVG module attatch, giving borgs nightvision and removing nearsighted penalties. Makes borg eyelight green.

-Can have a panic battery module attatche, allowing borgs to get a jumpstart of 1000 charge if cell charge hits 0

-Can have a construction module attatched to engiborgs, lowering rcd and rpd power costs and increasing metal glass and wire storage

-Can have a disabler assembly module attached to secborgs, giving them a swarmer disabler, with the 3 second cooldown and all.

-Can have an advanced tazer assembly module attatched, only with combat 6 and mats 7 and emp 5, giving secborgs an advanced tazer.

-Medborgs can have an expanded chemical storage module attatche, replacing beaker with bluespace beaker and increasing borg hypo storage anount

-Medborgs can have a medibeam module attatched, with high mats, emp, and bio levels, giving medborgs a weaker medibeam.

-Minerborgs can have an advanced treads module attatcged, allowing then to move acriss lava at normal speeds, and even ferry living things across lava safely.

-Ion jets let borgs move freely over chasms if on.

Servicevorgs can get specialization kits, letting them choose exactly the type of of drink they want, no mix required.

A FINAL CHANGE

Emp is changed from iron/uranium to mutagen/iron, thus making emps more common.

**Comment by SeikoTheSeal** [comment]
Don't touch my borgs scum.

**Comment by AdamElTablawy** [comment]
OKAY I FINISHED IT

**Comment by AdamElTablawy** [comment]
WHOOPS

**Comment by SeikoTheSeal** [comment]
Didn't read most of it but i like the idea of replacing secborgs disabler with bolas.

**Comment by Cruix** [comment]
At some point TG was considering making eggborgs turn into secborgs on code red, and turn back on code green.

**Comment by Super3222** [comment]
A few of these ideas I've came up with myself, like use of a medbeam gun in the actual game outside of ERT and bolas I told you about for a revamp of secborgs. Also expanding the module upgrades that borgs can get, making them much better, and more useful the better RnD gets.

Also the eggborg idea /tg/ came up was definitely good in theory, but it would have been bad in implementation to the actual game.

**Comment by Bekons** [comment]
Adam? First of all. Burn damage for borgs, is when there internal wires are burnt up. There bodies dont burn. Fixing borg burn damage is annoying, long and it will make little sense. 
>borg gets polyacided
>gets burned
>POP OPEN COVER, TAKE OUT BATTERY AND REPLACE BURNT WIRES INSIDE THE BORG.

Also removing peacekeeper? Really? He is THE asimov. Dispensing cookies, yelling human harm and being genualy annoying. I've stopped 3 antags one round with peacekeeper moduel using human harm, tirezine.

What you suggest, is nerfing and buffing the borgs in every wrong way. The borgs aren't powerfull cause they are fast. Stop trying to make them slow. They're powerfull cause you cant disarm them. For some fucked reason, yogstation depends on disarms for every combat scenario and antag. Whenever there is an antag, everyone decides to disarm them. Cause it doesnt work on borgs, people see them as "OP". You do nothing to adress this. If unarmed, you can atleast fight a human. Humans unarmed against borgs are complatley powerless.

Also you have to keep in mind, that locking something usefull behind upgrades means that there needs to be someone decent in R&D, robotics and mining. On yogstation, this only mostly never happens.

**Comment by Kmc2000** [comment]
No, don't remove eggborg, he is the best meme.

**Comment by AdamElTablawy** [comment]
As usual, bekons manages to completely misunderstand everything relating to balance and change. How utterly unsuprising.

Secborg becomes peacekeeper, essentially, except with a non-hardstun ranged option and a hardstun, in comparison to peacekeeper's no stuns and reliance that the AI is asimov, or secborg's dual stuns.

It adresses the issue of borgs having two hard counters-flashes and EMP-and nothing else, by giving borgs a lot of soft counters and making the absurd hardcounters softer.

The robotics changes mean that a traitor robo can put effort into making a borg more lethal right from the start, and allow specialized playstyles for borgs.

This is not a borg nerf/buff. This is changing the core mechanics of borgs entirely in their very setup, to be completely different from what they are now, meaning-

1. Roboticists have more to do to borgs even without R&D

2. Borgs have more soft counters, allowing for the nerfing of their retarded hard counters

3. Upgrades can cater to a certain playstyle and have benefits and tradeoffs

4. Modules that need improvement (medborg, secborg) are modified accordingly

5. Engiborgs are not shit at stopping fires

6. EMP's are made more widespread, allowing for more borg buffs in turn

Currently borgs have 2 hard counters and the rd console, and that's it. This changes EVERYTHING about them-hence the points bekons made about them are null since they're in reference to current borgs.

**Comment by fizzle7** [comment]
At the moment secborgs can fire their disabler infinitely as long as they have power, and it doesn't take that much power. I set out to tweak this so it's like before the rebase where it overheats (tg even mentions overheating but doesn't actually implement it for some reason), but I'm too lazy so go check it out if you want.

**Comment by Super3222** [comment]
If we're changing security borgs we have to come up with a new name for them, so people don't security.
Also borgs are not getting a forensic scanner. That is a bad idea, even with these implementations to make them more peacekeepery.

Detective should never be replaced by security borgs unless it gets upgraded with a slightly hard but, fair module to get. Even if we ARE getting rid of the "Oh hey, I'm apart of security!" feel, I have a feeling that it'll be a mad mix to the game. I still see your intentions for listing it as so.

Also:

> -Add an ability to tie up/disable a borg's modules with something like cable coil or duct tape which takes ten seconds for the borg to break and regain use of the module (takes a couple seconds)

How would that even work. 

This:

> -Make AOE flash also affect borgs in melee range.

Sounds like way too much of a nerf, Adam. Maybe making it short will do.

Also:

> Borgs don't take damage from lava, but are extremely slow in it and can get stuck.

What good is that at all with all of these nerfs? This barely compensates for the nerfs you want, man. And this'll also make the mining borg game more easier. There's no need for this at all.

And this:

> Flashbangs do not stun borgs, but blind them.

That's bad. Flashbangs should always be a hardcounter against borgs when officers have them cornered, and know they'll find a way to outrun them. Blocking exits and such, flashbanging, and then running in for the kill.

And this also:

> Inbuilt bruise pack/ointment similar to how mediborg also has gauze

:/

Some of the module buffs could be reconsidered as actual module upgrades, giving more reason to wanting to upgrade your borgs / borgs wanting upgrades themselves.

I'm saying that at round start you shouldn't be THAT good, engiborgs should start with fire extinguishers instead of the nanofrost / metal foam synthesizer.

As research gets better, borgs should get better, that's my saying.

Why? Because they ARE machinery from research, so why shouldn't they? It also calls for some interesting gameplay usage, makes modules less crap, and makes each module worth it with someone doing the research.

**Comment by AdamElTablawy** [comment]
Nerfs are not that bad

Flashes are way weaker so aoe flash buff is ok, or at least blinding borgs

Okay on the flashbangs i guess

Mineborgs at the least need a lavaproof upgrade

There are a shitton of upgrades i added and those modules needed a buff

**Comment by ShadowDeath6** [comment]
main problem with secborg is that it has infinite disabler which is omega cancer since it can be godawful at the game and still take you down no problemo

>making acid more cancer
implying able to hit borgs with acid

I'd be fine with borgs unlocking their cover at low health but definitely not opening the cover

secret xenobio technique already lets borgs get infinite charge, pls no remob

also emp nades have no cap so anyone with a few large beakers of mutagen and iron can kill AIs which I wouldn't really be fond of

>>>>>>>>>>>>>>AoE flash stunning borgs

it better be a 1 second stun then because AoE is the easiest shit to land in the game

I like the place that borgs are in right now and the only REAL problem is secborgs, and a huge part of that will be fixed if the infinite disabler and stunbaton meme is fixed

**Comment by AdamElTablawy** [comment]
At the least aoe flash should blind borgs in melee range making it easier to stun em with a flash/stunbaton

**Comment by Stealthkibbler** [comment]
Blinding seems good, forcing borgs to keep their distance, but an AOE stun is bad considering the abundance of flashes in quite a few locations, anyone can break into robo, tech storage or any sec checkpoint and steal the flashes, also they can steal the mounted flashbulbs at hops line and brig.

**Comment by puremanbird** [comment]
fuck this would be cool to have coded/merged.

**Comment by ShadowDeath6** [comment]
No it would not be

**Comment by Bawhoppen** [comment]
Why was I subscribed to this, one wonders.
