### ISSUE TITLE
Antag changes to discourage roundstart suicides

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#437]
Make traitor and ling show up five or ten minutes into the round so that people don't roundstart suicide if they don't roll antag.

If someone suicides or ghosts/disconnects reset their antag chance if it's within the first five to ten minutes of the round. Won't apply if their cause of death is a hit from another person but walking out an airlock will trigger it.

**Comment by FluffySurvivor** [comment]
What's the problem with antagfishing?

**Comment by AdamElTablawy** [comment]
It's cancer and I jobban people who do it permanently from antag

**Comment by oisin100** [comment]
I imagine that /ONCE/ TG release Datum Antags there will be a system in place for this, For now all we can do is wait, it would be a waste to code something for it to be written over days later.

**Comment by AdamElTablawy** [comment]
Datum antags will never be finished oisin, stop fooling yourself

**Comment by Bekons** [comment]
Adam, if you actually ban people, for suiciding or leaving, maybe you shouldn't have ban buttons.

Let people play how they want.

**Comment by AdamElTablawy** [comment]
No, I ban people for antagfishing from antag

That's not 'how i dont want them to play' it's called 'not being cancer and not shitting on the server rules'

I'll ban them anyway regardless this just makes my job easier

**Comment by drderp3635** [comment]
This is something that definitely shouldn't be implemented

**Comment by X-TheDark** [comment]
I've seem ahelp tickets of type "Are there Ashwalker Eggs spawned"...so I guess it is an issue...

**Comment by AdamElTablawy** [comment]
@drderp3635

Just to clarify

Regardless of if this is implemented or not

I will continue to antagban people who antag fish. So all this does is make my job easier

**Comment by drderp3635** [comment]
There isn't even anything in the rules against antag fishing though

**Comment by AdamElTablawy** [comment]
Sure there is, powergaming rule, and some tiny ass line of text at the end of the forum rules saying don't suicide every round since some people like those iobs

**Comment by AdamElTablawy** [comment]
I can also extend the metagaming/don't be a dickhole rule if i wanted to include thet but that's toeing the line on it's definition but w/e

Eirher way antagfishing is undebatably powergaming in any format and the reform updated rules I am working on will explicitly ban it but that's irrelevant
