### ISSUE TITLE
Change the wait time system for jobs

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#438]
change the wait time system for jobs.
1. Change it from 'days since someone connected to yog' to 'rounds played', ans by played, a olaytime of more than 20 minutes/surviving st round end (for the inevitable shitty 5min wiz round)
2. Lock head roles until person has played every job in the department at least 5 rounds. Security, and Captain, also need a 'rounds played' total as well. Captain cannot be played until at least one head role has been played 5 times.
3. Allow admins to restrict/reset/add to the jobs/times played measurement.

**Comment by Cruix** [comment]
https://github.com/yogstation13/yogstation/pull/417

**Comment by Super3222** [comment]
Yeah, I did this idea. I named it JEXP. There were multiple reasons for why it would never work out and why Yogs would lose players from it.

https://github.com/yogstation13/yogstation/pull/385

**Comment by Robertruler77** [comment]
Yes. 

> Join Yogs for first time and notice antag timings.
> Leave for month.
> Come back and first proper round is Captain.

**Comment by AdamElTablawy** [comment]
@Super3222 the issue is that you did it badly super not that the system doesnt work

It is supposed to do what our current system is supposed to do-force people to play rounds to get access to restricted jobs otherwise so shitler captain newbie is gone forever. If we lose players because of it, good, those were probably shitters anyway

**Comment by Super3222** [comment]
> force people to play rounds to get access to restricted jobs

That's exactly how the system worked. The problem was the amount of people who don't play SS13 24/7 and the amount of people who have knowledge and come from other servers.

When it comes down to it, incompetence will always be a part of SS13 no matter what you do.

**Comment by AdamElTablawy** [comment]
Hence 'rounds played' instead of 'x days'.

**Comment by Stealthkibbler** [comment]
@Super3222 The restrictions on some of the jobs were also fucked

as goof pointed out 30 rounds spanning to like 3-5 each for every medical role was a bit insane even for a dedicated player.

**Comment by Super3222** [comment]
Experienced players crossing over from other servers with a similar code source don't want to be forced into playing a bunch of pointless rounds over again is what I'm saying. Imagine if you were a player, completely experienced, dying to play CMO, and then told you have to play MD 3 times, Chemist 3 times, and maybe Geneticist 3 times? Maybe only 2 times as a MD or Chemist? Who knows, how can we even define that properly with the appropriate stats and variables.

Point is there will be people that aren't meant for the job and people that are meant for the job. We can cover a few blindspots here and there but, that's just what it is. Another round of classic SS13.

Some people jump into bigger jobs to actually do their job, maybe they won't know a thing or two. It's a challenge but, they live and learn.
Some people jump into bigger jobs, they fuck off or do something stupid. That's an admins job to deal with.

**Comment by AdamElTablawy** [comment]
this is for super
