### ISSUE TITLE
Gas mask are not fire proof

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4408]
The normal gas mask burn off when on fire, even when in a fire suit and helmet.

**Comment by nesisknesis** [comment]
Not a bug.

You were using an EMERGENCY fire suit and helmet. These wont protect you from fires while you are in them; only temperature difference, and the helmet does not cover the gas mask. The Atmospheric firesuit, located in Atmospherics, will protect you from fire and higher temperature differences, while also protecting the gas mask from fire as the Atmospheric fire-helmet covers the gas mask.

Gas masks wont typically be made from fire-proof materials neither - though plasma medals are.

**Comment by MegaEmpirical** [comment]
Ahhh, okay. I was not aware of that. Thanks. Though, I didn't have any other issues while being on fire and nothing else burned off but yeah, good to know. Closing.
