### ISSUE TITLE
Make Event-spawned syndicate attackers less invincible

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation#441]
As it currently stands, the anomalystorm-spawned Syndicate attack team is armed with an eshield and esword, and chase you around with mob AI. They all deflect all laser, ballistic, and thrown weaponry. This forces you to essentially play melee fighter with a 25 dps mob. Its very easy for the entire station to get robusted, as toolboxing assistants are stronger against these guys then the HoS with combat shotguns.

Solution: Remove the invincibility to ballistic and thrown weapons, while still screwing with security so they cant be lasered into oblivion.

Implementation: Unknown depending on the limits of mob AI, but spawning them as a mob with a +nodrop eshield +nodrop esword could be dope, so long as they continue to delete themselves upon death.

**Comment by AdamElTablawy** [comment]
The random event isnt even supposed to fire, so

**Comment by fizzle7** [comment]
Why not?

**Comment by AdamElTablawy** [comment]
Because it was disabled on tg but not here

**Comment by AdamElTablawy** [comment]
Not here by accident I should add

The event has a chance of summoning narsie btw, so shut the fucker down, NOW

**Comment by FluffySurvivor** [comment]
UP TO 100% CHANCE OF NARSIE, GO GO GO

**Comment by fizzle7** [comment]
> Not here by accident I should add

The event has a chance of summoning narsie btw, so shut the fucker down, NOW

Badam please check your sources, it doesn't spawn narsie nor it ever will, it just spawns constructs, like 20 or something. I mean this needs a nerf but it's a nice event, though it definitely doesn't spawn narsie.

**Comment by AdamElTablawy** [comment]
It used to spawn narsie guess robustin changed it before we rebased

**Comment by fizzle7** [comment]
Well robustin needs to check himself before he gets rekt.
