### ISSUE TITLE
Lavaland ninja suit still gibs

### ISSUE THREAD

**Issue by Colburn3000** [yogstation13/Yogstation#4436]
![image](https://user-images.githubusercontent.com/24303426/52385530-0b7cf680-2a50-11e9-8812-99299f408901.png)

Despite the PR saying this was fixed, the lavaland variant of the ninja suit still gibs non-ninjas.
Refer to:
https://github.com/yogstation13/Yogstation-TG/pull/4238

**Comment by HomocidlePancakes** [comment]
Does it gib when you put it on or when you try to initialize it? If it's on initialization then it's intended

**Comment by ghost** [comment]
it's not intended.

**Comment by GenericDM** [comment]
should be fixed by #4437

**Comment by Altoids1** [comment]
It is fixed. Closed.
