### ISSUE TITLE
Add some function to emag/malf AI/ new traitor item

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#446]
EMAGGED COMMS CONSOLE-
1. Allow falsified event announcements to be made on a cooldown.

list of allowed announcements-
- Radiation storm-interferes with station inbuilt geiger systems, forcing a radiation alert when there is none incoming.
- External threats -convinces external station motion alarms that a swarm of space carp have been located outside the station when there are none. Alternatively, can trigger a spider alarm and order welding of vents.
- Ion storm announcement- Convinces station ion detector that an ion storm has impacted the station when none has actually impacted.

All of the above have a 8 minute cooldown after forcing a false announcement, and has a 25% chance to create an automatic central command announcement minutes later announcing that the update did not come from them.

Reason-paranoia/sabotage without bombs, mostly fluff, adds some generally harmless functionality. Good for a distraction.
- Atmos console

Emagging the atmospherics/station control console adds the option to force false power/air alarms depending, which deactivate after 30 to 60 seconds-unless air alarm or apc is emagged. Can also force-clear all air and power alarms. Fries air and power alarm consoles, showing an alert message if interacted with.

-Arrivals announcement console

Emagging opens a prompt to create a false crew arrivals announcement of a custom name, job, as long as it is not a head of staff role. Also updates crew manifest with false name. Can also scramble arrivals announcements if emagged again, turning all arrival announcements and station updates into illegible wingdings. Permanently turns Arrivals announcement computer bright red if emagged-multitool disables scrambling.

Malf AI-

Add ability for malf AI to do all of the above for 25 CPU each. As in, each false announcement costs 25 CPU.

Add ability for malf AI to set station alert level to red/delta/gamma for 15 CPU each use.

Add ability for malf AI to falsify central command updates for 65 CPU-meaning it can send out a custom CC announcement. Has a chance to fail and send nothing at all, and a small chance to critfail and send out the same CC announcement as the emag one that the update did not come from them. Reason being is that CC announcements are generally treated as high-up orders and thus very powerful.

Add ability to force gang dominator/blob alert announcements for 80 CPU, triggering the CC (that thar update didnt come from us) announcement 5 minutes later. One use.

Add malf ability to supercharge machines for 15 CPU (3 uses per buy), making them shock humans who interact with them or otherwise malfunction- (gib clones, spray acid, teleport slimes outside of xenobio). 

Add a new endgame for malftraitor- instead of doomsday devicing, allows AI to instead trigger station override like it used to. If completed, gives AI complete control over everything-similar to how retarded powerful ascended shadough or devil is, autocalls the shuttle and makes AI essentially a god, with near-admin tier control over machines, doors, and thermal/NVG/Xray camera vision, and revenant light-overload abilities. AI becomes indestructible and can emag anything by ctrl-shift-alt clicking on it. Much harder than doomsday device, requiring 3x the cpu doomsday device does, 3x the time, triggering a CC announcement, and possibly spawning an amber ERT at 300 seconds or less. It's an ALTERNATIVE to doomsday device, not a replacement.

**Comment by ShadowDeath6** [comment]
I assume that the ion storm announcement is the AI law thing 

>making the AI spend an eighth of their CPU for one announcement

should be 25 for any they want, especially if there's a 25% chance for it to fail

>having a chance to fail for any malf AI abilities

they won't buy them unless they want to gimmick, literally none of the AI abilities have a chance to fail. 

>80 CPU for a distraction for 5 minutes

will never buy because it literally calls the AI out on being malf

>exact same as doomsday timer but instead of making the AI win it just lets the AI stroke itself while it deletes everyone on the station but costs 3x as much and takes 3x as long as well as spawning 3 or more captains with miniature armories in their backpacks

lel

**Comment by AdamElTablawy** [comment]
Shadow

CPU is near infinite since hacking new apc's gets you more cpu, malfs do not have set cpu now

So i mean an ai who hacks every single apc will have THOUSANDS of cpu

**Comment by AdamElTablawy** [comment]
Also CC announcements are by default gimmicks since they have no direct impact but are basically word-of-admin

I'm okay with removing the failchance for blob call i guess

**Comment by ShadowDeath6** [comment]
oh right I forgot about CPU gain

failchance is still dumb though and encourages people to just spam machine override since it can't fail and it's op
