### ISSUE TITLE
Supply request consoles have no way to end emergency calls

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4468]
There seems to be no button, both at the sending and receiving end, to terminate these and swiping IDs seems to do nothing as well.

**Comment by fluffe9911** [comment]
I dont get this one like are you saying supply requests consoles cant recall the shuttle? If so are they even supposed to?

**Comment by MegaEmpirical** [comment]
Supply requests consoles have nothing to do with shuttles, they're about sending requests and relaying information.

**Comment by adamsong** [comment]
The emergency auto clears after 5 minutes
