### ISSUE TITLE
Return Security comms to Burgundy

### ISSUE THREAD

**Issue by nesisknesis** [yogstation13/Yogstation#4478]
Whoever had the thought process of having it be black should be sent to Guantanamo, or shot. It blends in with normal text so you miss it half the time as a ghost, and as a player, confused to if it was near you or not.

if its some hideous bug, heres the report, if it isnt, god help us

**Comment by GenericDM** [comment]
I saw this during only one round, are you sure it wasn't an NTSL script or bug?

**Comment by nesisknesis** [comment]
ive heard it through ooc on previous rounds, and saw it for myself on another. seeing as command was also changed to a blue, i blame that for this disgusting addition

**Comment by GenericDM** [comment]
line 282 of [this file](https://github.com/yogstation13/Yogstation-TG/blob/master/code/modules/goonchat/browserassets/css/browserOutput.css) says it's still red.. maybe a bug somewhere else?

**Comment by Altoids1** [comment]
Yeah that's... weird. Do you have any screenshots of this?

**Comment by GenericDM** [comment]
@monster860 did you fix this with your dirty [master commit](https://github.com/yogstation13/Yogstation-TG/commit/05a759891eccc567f59b6f3c3c7f2888e056e375)?
