### ISSUE TITLE
Lavaland Gas station issues and suggestions

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4481]
The air tank in the back is rotated in such a way that it does not feed into the air tank in the store.

![image](https://user-images.githubusercontent.com/36208065/52749039-171f6e80-2fb6-11e9-9c5b-26efd1b3fa71.png)

Could air vents that prevent air flow be added to each door so the place doesn't constantly loose pressure/air every time a door is opened? 

I do not know if it was there at the start and just taken later (joined late) but if not, could a backpack be added to the back of the store or have the clerk start with one? Similarly I did not notice any keys for the ATV.

The light switch can be accessed from inside and outside the store.

Ditch the cleanbot and just give a mop and bucket since there is already a sink and mop bucket.

**Comment by MegaEmpirical** [comment]
As an aside: the paystand was a cool addition, good idea.

**Comment by fluffe9911** [comment]
Alrighty will fix/take these suggestions into account and work on them in a bit lol also may add some fluff things like display cases for when you want to show off certain valuable items or some other things I cant think of at the moment we will see
