### ISSUE TITLE
Cosmic ashwalker has digurtutate(fuckhowdoispellit) legs

### ISSUE THREAD

**Issue by HomocidlePancakes** [yogstation13/Yogstation#4487]
Cosmic starts with a pair of no-slips. He can't wear them because his legs are scuffed. Fluffy forgot to give him proper legs. Blame Fluffy.

**Comment by fluffe9911** [comment]
Yeah I kinda knew this was a problem but could not think of anyway to fix it other then making a whole new shoe type thingy which I dont exactly know how to do although in hindsight I can just make it a lizard subtype instead of a ashwalker one so will prob do that in a bit

**Comment by GenericDM** [comment]
I'll take a look at this once I get home if fluffe hasn't fixed it by then.
