### ISSUE TITLE
NTSL $Language

### ISSUE THREAD

**Issue by Tename** [yogstation13/Yogstation#4522]
## Reproduction: Use the $Language function in NTS

The $Language function sends common properly as 1, but draconic and probably other languages appear like this. 
![9ababcf5b985773219c79c4a42dda576](https://user-images.githubusercontent.com/37943518/53068737-59512000-348e-11e9-8cd8-71efb19f3337.png)

**Comment by Altoids1** [comment]
Hahahahahahahaahah

**Comment by Altoids1** [comment]
Right, so, I don't think I have enough bit space to give every single language in the game a proper bitwise value, so they can't all resolve to a bit properly.

This means that to display it as a number to NTSL, I would either have to:
- Ditch it being bits and just have a list of what are basically enums (which must be constantly fuckin' updated with every new language)
- Just set all weird languages to have a number value of 0 or -1 to NTSL

The former involves way more effort than I want to put into fixing this goofiness, and the latter would not give NTSL enough information to really interact with these exotic languages in any meaningful way.

So, at the moment, I don't *really* know how to fix this for you, unless someone else has ideas.
