### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Xeans** [yogstation13/yogstation#455]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

Hey folks, I'm getting this texture missing issue. I've already cleared the byond cache per recommendation in OOC and I've still got the same problem. No idea what brought this on, it only started the 3rd of August.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
![bynd1](https://cloud.githubusercontent.com/assets/20825057/17382381/910c7e68-599e-11e6-954e-db2f7003b9ee.png)

**Comment by Cruix** [comment]
Try updating your BYOND version to the latest stable build.

**Comment by Xeans** [comment]
That did it, I was about three number versions behind. Thanks.
