### ISSUE TITLE
spawn object panel is BLANK

### ISSUE THREAD

**Issue by Gh0sT2242** [yogstation13/Yogstation#4550]

**Comment by Bibby0110** [comment]
On a seperate note, the spawn object panel is now laggy when typing stuff in, since it updates per letter instead of when you press search. Feelsbadman

**Comment by Altoids1** [comment]
Fucking Internet Explorer can eat my magnum dong

**Comment by Bibby0110** [comment]
It seems to only be blank for Ghost, its still bad though

**Comment by Gh0sT2242** [comment]
Figured it out, I don't have a good computer at the moment, and it cannot run edge, which is what monster decided was required.

**Comment by Altoids1** [comment]
![image](https://user-images.githubusercontent.com/29939414/53452391-c6146f00-39e6-11e9-86b7-daf66c5b45a9.png)

How do you even run this game with specs that low?

**Comment by Bibby0110** [comment]
1 GHz cpu, such high end

**Comment by ThatLing** [comment]
Caused by #4541
