### ISSUE TITLE
Replace eggborg and secborg 91%lagfree (MEME ZONE) (XDDD)

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation#457]
My idea:

Praetorian borg, they are, like eggborg, here to protect, nothing more.

Their gear:

 A modded hydraulic clamp, whoch after 5 seconds of wait time, grips an enemies' hands and prevents them from using stuff LIKE CUFFS, and the borg can drag them along.

Harm alarm

Barrier projector

Disabler beam with high power draw, which will overheat and cause damage to the borg if spammed too much.

A hypospray which can be filled at chem masters, so the borg is adaptable.

A fire extinguisher

Alternative to adam's textwall of nerfs, discuss

**Comment by Super3222** [comment]
Kmc...

**Comment by ShadowDeath6** [comment]
here's a suggestion

make secborgs not have infinite disablers, how the fuck is that balanced
remove eggborgs because they're just annoying assholes and cannot accomplish anything

**Comment by AdamElTablawy** [comment]
Worse than my proposed secborg changes

Also hello dumbasses you can incorporate part and not all of borg changes so giant wall of nerfs buffs need not be added
