### ISSUE TITLE
Curators have engi foyer access

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4582]
At some point curators were given construction access, I guess to do with space exploring. The engi foyer door uses construction access to let the engi department in and out as well, giving the curator access to the engi lathe.

I imagine this access is mostly for aux base access but I assume it also gives access to the construction room in the engi hall and possibly the vacant office in arrivals.

**Comment by Time-Green** [comment]
delete this

**Comment by MegaEmpirical** [comment]
Why? The curator doesn't need access to the engi foyer and lathe. He's service department.

**Comment by Time-Green** [comment]
delete this

**Comment by MegaEmpirical** [comment]
https://github.com/tgstation/tgstation/pull/44196

They're getting jet packs now too, they're basically becoming shitty engis.

**Comment by Jalleo** [comment]
Construction access is lpbby only. It also does the construction room. Nothing more.

**Comment by MegaEmpirical** [comment]
Exactly. The engi foyer gives a lot of nice tools due to the lathe, like jaws of life. I don't really get why a curator would need this kind of access.

**Comment by adamsong** [comment]
This has been open for a while, curator still has foyer access.
