### ISSUE TITLE
A tool that can check accesses on a door might be nice

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4584]
A little tool that if applied to a door (maybe after screwing it open?) that could read the accesses would mean not having to break the door down to check them. Maybe applicable to buttons (they also use airlock circuits) too would be nice?

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)

**Comment by MegaEmpirical** [comment]
This was actually added to the game, just not closed.

**Comment by MegaEmpirical** [comment]
https://github.com/yogstation13/Yogstation/pull/6479
