### ISSUE TITLE
Manifests Deducting points for arbitrary reasons

### ISSUE THREAD

**Issue by upwardthinking** [yogstation13/yogstation#459]
Credits appear to be deducted for manifest for arbitrary reason, for example a shipment of glass and robotic supplies were received and two approved manifests were sent back but 2000 credits were deducted for the reason of erroneously approved manifests when the items were most certainly received, either something is wrong or the criteria for what constitutes an erroneously approved manifest needs to be made more apparent.

**Comment by Cruix** [comment]
You have to check the station name, order number, and the number of items shipped on the manifest. If any of those are wrong, you need to put a DENIED stamp on the manifest. It will work even if you have already stamped it as APPROVED.

How should we go about making it more apparent?

**Comment by AdamElTablawy** [comment]
Don't.

**Comment by upwardthinking** [comment]
Well I adminhelped the question and the admin was totally unaware it was possible to have points deducted so there's an education gap there, at the very least I'd like to see an update to the wiki what needs be checked on a manifest and possibly an item (book or list) spawning in the QM's office explaining what needs to be checked. Also how is a QM supposed to check the contents of ID locked shipment such as robotics or forensics supplies if he can't open the crate with his ID, departments will flat out refuse to open them for you making it impossible to open these crates to verify their contents.

**Comment by fizzle7** [comment]
https://tgstation13.org/wiki/Supply_crates

Checking locked crates is supposed to be an RP issue, so if you can't check the contents your only solution is to risk it or just dump the manifest.

**Comment by Alek2ander** [comment]
Keep the manifest until someone comes around to pick it up and unlock it.
You get more points from returning crates than from manifests anyway.
