### ISSUE TITLE
Mentor follow shoots out an error

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4598]
When clicking the F for follow on the initial message from an mhelp I get this:

Error: You do not have sufficient rights to do that. You require one of the following flags: +ADMIN.

Click the "Stop Following" button in the Mentor tab to stop following TacticalSpacePilot/(Sawyer Cherry).

It does not stop me from following them but it does spit out an error.

**Comment by Altoids1** [comment]
Caused by #4551, the proc I use to check admin rights I guess automatically complains to the user about bad rights when it returns false. Will fix.
