### ISSUE TITLE
Signal Tech - No Server Room APC and Air Alarm Access

### ISSUE THREAD

**Issue by deh66** [yogstation13/Yogstation#4605]
Issue reported from  Round ID: 21599 (Yogstation 13)

Reporting client version: 512

Signal Tech's do not have access to the server room APC or Air Alarm. I am under the understanding that they are supposed to.

**Comment by MegaEmpirical** [comment]
They should have air alarm access there, or should have. I don't recall them ever having that specific APC access though but cannot confirm.

**Comment by Altoids1** [comment]
Yeah, I know about this bug. Will fix eventually.

**Comment by deh66** [comment]
Cool
