### ISSUE TITLE
Custom Admin Panel for creating custom ghostspawns

### ISSUE THREAD

**Issue by Altoids1** [yogstation13/Yogstation#4608]
![image](https://user-images.githubusercontent.com/29939414/53520421-3bda1280-3a9b-11e9-8b89-eef1a73228ae.png)

Related to #4595

Will do eventually.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
