### ISSUE TITLE
Make Prison Officer start implanted

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation#461]
So I just nearly shot to death a newbie for trying to help me in armory. 

Prison officers are not implanted. Also, theres no changelog for them.

Solution: Add roundstart implant. Also, ensure they are not possible traitors.

**Comment by Silk-Touch** [comment]
How did you spell implanted wrong in the title but correctly in the comment?

**Comment by ShadowDeath6** [comment]
they're like shittier officers so why make them start implanted tbh :^)

**Comment by EMT321** [comment]
I dont know what you're talking about. I spurl reel guud.

And the fact they have access to cells, and all of sec equipment storage+prisoner logs, means its a good idea to implant them.

**Comment by SeikoTheSeal** [comment]
KMC meant to have them implanted but something borked. I'll try posting a PR fixing this next time i touch DM (which probably will be tommorow), unless someone gets to do it before me.

**Comment by Super3222** [comment]
Sec will never be antag, Shadow. Blobs the only exception.

I'm also improving prison officers, I told KMC about how he pathed something wrong, and it'll be fixed in my next commit.

**Comment by SeikoTheSeal** [comment]
Coolio

**Comment by Kmc2000** [comment]
https://github.com/yogstation13/yogstation/pull/465

**Comment by Kmc2000** [comment]
Also they cannot be antag, i got that bit right

**Comment by Kmc2000** [comment]
AND FINALLY


The changelog thing is because george's thing broke, he said he's on that
