### ISSUE TITLE
Summoning a contract on a non-sentient/soulless body as a devil waste the spell

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4642]
When trying to summon a contract of revival on a soulless body, it uses the spell up and says that it can't be used on non-sentients. I don't think the spell should go on cooldown if it never activated to begin with.

**Comment by adamsong** [comment]
This has been fixed

**Comment by adamsong** [comment]
I was mistaken about the nature of this issue, it does still have a cooldown, but after that the spell is usable

**Comment by MegaEmpirical** [comment]
It also doesn't summon a contract.
