### ISSUE TITLE
Plasmamen devils burn eternally

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4643]
As a plamaman devil, I was fine once I reached the lizard stage. Had to ditch my plasma tank but I was fine. Ditched the suit to not be a plasmaman with a tail, I was still fine. However, once I was lit on fire, I was constantly on fire. No amount of rolling helped, eventually I couldn't even use resist/roll any (no longer would activate), I had gained xray vision somehow, and finally I was constantly on fire and taking damage. My only solace was being a medic with lots of healing (even if most of my shit fell off after my uniform fell off) and finding a fire suit.

Does need reproducing, only happened once and devil is quite rare.... plasmamen devils even more so.

**Comment by adamsong** [comment]
Could not reproduce, and devil is no longer in rotation
