### ISSUE TITLE
signal tech question/issue

### ISSUE THREAD

**Issue by Jc1469** [yogstation13/Yogstation#4657]
broadcast/signal can't have a scripted message with a filter anymore. this is unacceptable and ruins the entire server

**Comment by Altoids1** [comment]
What do you mean?

**Comment by Jc1469** [comment]
5th argument for broadcast used to be filters, now it isnt.  quite simple really

**Comment by Jc1469** [comment]
you can't do
`broadcast(signal(sig.content, channels.common, sig.source, sig.job, list(filter_type.commanding)));`

**Comment by Jc1469** [comment]
you can still change filter just by applying it to the sent message but you can't use broadcast to add filters to custom messages anymore

**Comment by Jc1469** [comment]
also what's replaced pass=0?

**Comment by Altoids1** [comment]
If you don't want to pass anything, you just return inside of ``process_signal`` with no signal.

You can replicate the previous behavior by, at the end of ``process_signal``, adding:
```php
if($pass)
{
    return sign;
}
```
