### ISSUE TITLE
Space ninja glitched gear

### ISSUE THREAD

**Issue by AAAbattery** [yogstation13/yogstation#467]
When a space ninja spawns from a random event you cannot see their mask or shoes even though they are ,in fact, there. You can still use internals and not slip on glass but you look like you have no shoes or mask and it is very ugly looking. You are a ninja in space whose face is clearly visible and you are wearing just socks.

**Comment by Yackitori** [comment]
Feature

**Comment by Kmc2000** [comment]
Feature

**Comment by X-TheDark** [comment]
aka 'Missing sprites'

**Comment by Super3222** [comment]
https://github.com/yogstation13/yogstation/pull/370

**Comment by Stealthkibbler** [comment]
scream at cruix or oisin to merge my fix and then the ninja will look badass, i promise hehe xd.
