### ISSUE TITLE
medical techfab and exosuit fabricator printing broken implants

### ISSUE THREAD

**Issue by DeadlyBag** [yogstation13/Yogstation#4686]
like the title says, most of the implants come out as broken when you print them. When you examine the implants it mentions "The ____________ implant seems to be broken!"
happend during multiple rounds today 06/03/2019

**Comment by Altoids1** [comment]
This bug persists even if the admin spawns in new ones; it seems like they just spawn with the BROKEN flag.

**Comment by SomeguyManperson** [comment]
this was an issue caused by implants spawning with the BROKEN flag, since a coder forgot to remove that after testing with it, it has since been fixed
