### ISSUE TITLE
Head borgs+A plethora of robco cybernetics icons to add to our current borg skin roster.

### ISSUE THREAD

**Issue by R3DGL4R3** [yogstation13/yogstation#469]
Title says it all,I already have all the icons if someone wants to do the coding.

A headborg could work like this:Head gets borged,has robotics nerd wipe their ID across the chassis,initiate transformation.jpg with the ID being consumed in the process.

**Comment by X-TheDark** [comment]
Why do you want to rename the AI to Head Cyborg?

**Comment by R3DGL4R3** [comment]
@ShadowDeath6 They'd have all the functionality of a head,instead of having a large amount of modules like the average borg,they'd have a few built in tools of their trade,a small storage space for necessary things they need,and hands.

**Comment by Kmc2000** [comment]
I kinda want to try coding this, as a newb coder...even so i'll wait for more input before i try

**Comment by Super3222** [comment]
Borgs that work as heads aren't really for SS13. In the hierarchy of silicons, only the AI stands above their legion of cyborg assholes.
