### ISSUE TITLE
Bolt of Change turned me into nothing.

### ISSUE THREAD

**Issue by Lynameep** [yogstation13/Yogstation#4704]
## Reproduction:

As an Ethereal Miner I decided with my impeckable luck to try and explore the lavaland wizard ruins only to be Bolt of Change'd into quite literally nothing. http://prntscr.com/mucis0

I was alive and able to be moved by Penguinfisher however I was unable to do anything other then simple exist. I wasn't changed into an item because there were no other items that I didn't previously have on me so I must of been bolt of changed into something nonexistent?

**Comment by Amelia0010** [comment]
nice

**Comment by GenericDM** [comment]
I've seen this from at least one month ago, problem probably unrelated to any new code.

**Comment by HomocidlePancakes** [comment]
https://github.com/tgstation/tgstation/issues/42685
Known bug.

**Comment by Neuroplasty** [comment]
Just had this happen to me and someone's holopara and we were listed as aliens in the roundend screen [here](https://i.imgur.com/Y6L4yxd.png)

**Comment by adamsong** [comment]
I can no longer reproduce this issue, its probably been fixed
