### ISSUE TITLE
Corgi hides are don't give anything when shipped.

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#475]
The following code suggests that corgi hides should be exportable. https://github.com/yogstation13/yogstation/blob/9ca634e7a20196faa263bda7fc5a35f687adab92/code/modules/cargo/exports/sheets.dm#L47  I Tried exporting a number of corgi hides and got nothing, corgi hides also as unexportable with a a export scanner.

**Comment by Cruix** [comment]
Corgi hides are contraband, so you have to unlock their export datum with a multitool.

**Comment by ShadowDeath6** [comment]
why would you ever do such a thing you monster

**Comment by Super3222** [comment]
Seems like this is a feature.

**Comment by Silk-Touch** [comment]
Umm I would like to add that corgi hides are really overpriced and breeding corgis for there hides can deliver 25000 cargo points in 15 minutes maybe someone might want to fix that
