### ISSUE TITLE
Add a 30-Minute timer before you can knock on Legions door.

### ISSUE THREAD

**Issue by Lynameep** [yogstation13/Yogstation#4750]
Since now the outpost can spawn much further into lavaland it seems that Legion's position is now a bit of an issue as Legion will chase the Miner who knocks till death which typically results in said miner unintentionally luring it back to the Outpost.

I would also recommend bringing back the Megafauna aggro notice from pre-rebase since this might become an issue later on.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
