### ISSUE TITLE
Detective lacks department lathe access

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4788]
Detective cannot reach the department lathe since he doesn't have sec office access.

**Comment by fluffe9911** [comment]
*shrug*

**Comment by patpol4** [comment]
Not a bug, detective is not a security officer, hence no access to the security office.

**Comment by MegaEmpirical** [comment]
No shit but he is a memeber of the security department and lacks access to his department lathe so it is an issue.

**Comment by patpol4** [comment]
Alright but this is not a mapping issue, det just needs sec office access
