### ISSUE TITLE
HELP WANTED brig officers cannot be job banned

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation#480]
I'll look into this ASAP , but if anyone else feels like doing it sooner please have a go

**Comment by Super3222** [comment]
I feel like this is a database problem.

**Comment by Kmc2000** [comment]
>I feel like this is a database problem.
Hence why i don't think i ought to be fiddling with it

**Comment by Cruix** [comment]
I am pretty sure this is fixed
