### ISSUE TITLE
Blueprint Can't Rename Rooms Properly

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#481]
(Borg) Blueprint won't let you rename a room long enough to fit "heads of staff meeting room" for example, it has character limit apparently and thus it becomes "heads of staff meeting ro"

**Comment by X-TheDark** [comment]
One line change, if this feature is necessary
https://github.com/yogstation13/yogstation/blob/master/code/_compile_options.dm#L27
(There's still some hardcoded stuff in blueprints that doesn't allow messages over 50 characters long - can be changed, if necessary)

**Comment by 00aquir** [comment]
The original name of the room is actually "heads of staff meeting room", so it should support that...
