### ISSUE TITLE
Cannot fire the KAs

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#4816]
Round 21936 2019-03-18. Sample: server time 15:40-48 round time 1:20:00-28:00 while ahelping.

Sometimes only one, sometimes none of the KAs could be fired. When I went back to station, I checked them and they worked fine, on lavaland they, again, sometimes worked, but mostly did not, at all.

**Comment by Altoids1** [comment]
This might've been the result of us disabling some of the major subsystems 16-ish hours ago, as a result of the massive Sseth hightide.
