### ISSUE TITLE
Blurring of tiles, client freezes

### ISSUE THREAD

**Issue by assmops** [yogstation13/Yogstation#4820]
I'm not even sure how to explain these properly.
Sometimes, very rarely, the entire game window will become extremely saturated and blurry, and the game will freeze. The chatlog will no longer update, sounds will stop playing, and all input is ignored or dropped, i.e, if it happens during an ash storm while I'm walking back to the base, the ash storm sound effect will immediately cut out, and my character will stop dead in their tracks and promptly die to the storm, and if I try to say over supply that I'm dying, nothing will happen, the chat window won't even open. 

Once this happens, the round is completely unplayable, even reinstalling BYOND mid-round won't fix it. The only 'fix' is to wait for the server to restart and the next round to begin.

To my knowledge and experience, this only happens on this server; CM, TG, and Hippie have never given me this issue, despite playing on multiple computers with different settings.

This also happened pre-rebase, but not nearly as often.

Some examples:
![20190128012925_1](https://user-images.githubusercontent.com/45994070/54590064-9fea5980-49fd-11e9-926f-522233fa3060.jpg)
![20190128013003_1](https://user-images.githubusercontent.com/45994070/54590070-a37de080-49fd-11e9-9c41-20027f02fd97.jpg)

**Comment by Altoids1** [comment]
So that's the lighting layer I guess being the only thing that's being displayed on your client, which makes me think that it's a clientside bug. Unless more people come forward about having this bug, I'm just gonna tell you to update your GPU's drivers and your BYOND.

**Comment by alexkar598** [comment]
Reinstall directx 9
