### ISSUE TITLE
Add portable breach shielders to engi

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#485]
Instead of the giant-ass shielders in engi storage being the only shields, add smaller portable breach shielders to engi, and micro-shielders to emergency lockers.

The portable ones shield in a 3x3 box and can be folded up and carried by hand, then deployed to become dense objects.

Micro-shielders only block 3 breached tiles and can be activated inhand.

Reasoning-breach shielders are cool but nobody ever uses them. This might see them get use.

**Comment by X-TheDark** [comment]
> Micro-shielders only block 3 breached tiles and can be activated inhand.

How would this work? Would this be a simple 3 block line?

**Comment by AdamElTablawy** [comment]
No, just a max of 3 tiles
