### ISSUE TITLE
Port baystation webbing

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#486]
Port webbing from bay.

Webbing is an attatchment to the jumpsuit like ties are. Apply to jumpsuit, can hold 3 items that would fit in pockets.

Load bearing vests are a type of engi-specific webbing that holds 5 small items and RCD matter cartridges. 

Black webbing vests are security-specific webbing vests with 4 storage spaces, that can hold small items/one stunbaton.

White webbing vests are medical-specific webbings with 5 storage spaces. Can hold any medical item/small item.

Two webbings start in cargo-one in ct locker, one in qm locker. 

Three webbings start in engineering lockers, one load bearing vest in CE locker, one load bearing in engi locker.

Two webbings start in medbay storage. Three start in paramedic lockers. CMO gets a white webbing vest.

One Webbing is in every security locker. HOS, Captain and Warden get a black webbing vest.

Webbing crates can be ordered from cargo, containing 3x webbing and 1x of each special webbing. Also contains an energy webbing for research, that can hold any science item, such as beakers or TTVs and has two spaces.

Reasoning-STORAGE CREEP. Also, it's cool.

**Comment by Kmc2000** [comment]
I'll take a look at porting this, seems straight forward enough

**Comment by SeikoTheSeal** [comment]
>Storage power creep

**Comment by Kmc2000** [comment]
I'm working on porting this

**Comment by Super3222** [comment]
Idea: MAKE THE WEBBINGS ONLY START INSIDE OF THE CLERK VENDOR, SO THE CLERK CAN HAND THEM OUT AND HAVE AN IMPACT ON THE ROUND.
Oh and give the captain a basic one.
