### ISSUE TITLE
Prison Officers

### ISSUE THREAD

**Issue by ToveyAyyLmao** [yogstation13/yogstation#490]
They don't start the shift with access to perma, aka their job. Also they spawn without an implant.

Give them both at round start.

**Comment by Super3222** [comment]
Already done. They've been re purposed to better suit the brig.

The initial idea (by KMC) was to make them "assistants of the brig".

**Comment by ToveyAyyLmao** [comment]
Err apparently they still dont have access to the perma. I dont see how that is supposed to be good.

**Comment by Super3222** [comment]
The PR hasn't been merged yet.

**Comment by Super3222** [comment]
https://github.com/yogstation13/yogstation/pull/417
