### ISSUE TITLE
Revert back to slow plasmamen without 150% brute damage

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4914]
I didn't mind the speed nerf, it was rough but I could deal with it. Now it barely takes any hits to kill me and it's obnoxious as hell. It was hard enough after they added crawling (I used to rely heavily on stuns from mouth punching to help even the odds).

**Comment by MegaEmpirical** [comment]
A note: I do not know if the species itself was slow or just the suit but I think it should be limited to the suit.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
