### ISSUE TITLE
Using : before speaking cuts off the first character

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4931]
:test
=
![image](https://user-images.githubusercontent.com/36208065/54880742-bb4ecd80-4e1e-11e9-97a9-e2b19f751c1d.png)

**Comment by Altoids1** [comment]
🤔

**Comment by ThatLing** [comment]
NTSL script perhaps?

**Comment by MegaEmpirical** [comment]
I don't think any were running at the time. Semicolon worked fine. I'll try again later.

**Comment by Amelia0010** [comment]
: is a usable operator for choosing radio channel. Doing :test makes you say `est` on the channel with the command `t`, that being the traitor channel.

**Comment by MegaEmpirical** [comment]
But it was being broadcasted to common and I did not have traitor chip?
