### ISSUE TITLE
DECA-CODE Locked Crates don't allow input

### ISSUE THREAD

**Issue by Lynameep** [yogstation13/Yogstation#4951]
DECA-CODE Locked Crates sometimes are not able to be unlocked as attempting to input a 4 digit code will result you instead stop using it as if you entered none giving you the message "You leave the crate alone".

The bug seems to be a bit inconsistent as some crates allowed me to input 2 and some were bugged before i even had the chance to enter a single one or interact with it.

**Comment by SomeguyManperson** [comment]
Did you enter any digit twice? The crate has four unique digits and will stop you from inputting anything twice so you don't play yourself.
