### ISSUE TITLE
I have to double click to do anything and i can't get in mechs. The admins couldn't help me, so how do i fix it

### ISSUE THREAD

**Issue by MrBroTurtle** [yogstation13/yogstation#497]

**Comment by Yackitori** [comment]
Did you try turning it off and back again.

**Comment by MrBroTurtle** [comment]
Yes

**Comment by drderp3635** [comment]
Try uninstalling

**Comment by abdbla** [comment]
Are you using two monitors, if so, is your SS13 window in the primary monitor?
That might be the issue, although im not sure how to fix it. Restarting the computer fixed it temporarily for me.
