### ISSUE TITLE
Pre-rebase engineering/atmos PDA alerts

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4986]
We used to have a togglable alert feature on our PDAs for atmos alerts for atmos techs and a similar feature for power? on engi PDAs.

**Comment by GenericDM** [comment]
You can use the tablet computer that atmos techies and engineers spawn with for that.

**Comment by MegaEmpirical** [comment]
I thought it only did the red light as a notification?

**Comment by jcatjmeow** [comment]
Feature requests go on the forums now sorry :(

**Comment by jcatjmeow** [comment]
Also, tablet computers do an audible alert if you have them in your pocket. Can't hear it through backpacks tho

**Comment by MegaEmpirical** [comment]
Nice to know, at least.
