### ISSUE TITLE
Pre-rebase PDA emergency alerts

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4987]
PDAs used to have a similar feature as supply request consoles to alert medical and some other areas with an SOS and the location of the PDA.

**Comment by oklews** [comment]
Y E S

**Comment by MegaEmpirical** [comment]
I think one of them was a direct emergency thing to the Captain.

**Comment by jcatjmeow** [comment]
Feature requests go on the forums now sorry :(
