### ISSUE TITLE
Vtech is broken

### ISSUE THREAD

**Issue by oklews** [yogstation13/Yogstation#4990]
## Vtech is broken
Round ID 2217

Reproduction: Get Vtech Module, give to borg, be sad as you realize you wasted mats.

**Comment by oklews** [comment]
I reported it that round, it was vaguely a problem forever, it didn't happen that round but it happened soon before it.

**Comment by Jc1469** [comment]
gamebreaking bug. can confirm is real bug. speed does not change

**Comment by oklews** [comment]
it's been a problem since the speed changes

**Comment by oklews** [comment]
Still broken sadly

**Comment by SomeguyManperson** [comment]
fixed by #6736
