### ISSUE TITLE
Delta - Pipes missing near SM engine.

### ISSUE THREAD

**Issue by Jc1469** [yogstation13/Yogstation#4991]
orange pipe no there, send help
so bad an issue that the map should be forever removed from being possible to be picked
ignore the robot person that spent 20 minutes failing to set up the engine
![pipe bad](https://puu.sh/D7mnO/387164bfda.png)

**Comment by oklews** [comment]
it's almost like we play this map once a year so problems like this slip through, that's why you should join me in forcing the stations to cycle regularly.
