### ISSUE TITLE
Im porting the map

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation#5]
Im porting the map along with all of the basic things from it such as:

Mimekitty
Honkbots
Security transceivers
Deployable Barricades(Ill port your updates @Super3222)
Our telescience
Some of our new areas.

**Comment by Bawhoppen** [comment]
Your best bet is redoing the maps by hand, we changed all the turf's paths, and we had to manually fix everything of our own

**Comment by oisin100** [comment]
> Your best bet is redoing the maps by hand, we changed all the turf's paths, and we had to manually fix everything of our own

Updated the map, just need to push it. Notepad++ Is possibly humanities greatest invention.
