### ISSUE TITLE
It's Lethal to stand in engineering due to radiation

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#5036]
If you have singularity, the shutters and walls do not block radiation, stand in engineering long enough, even further away at the lockers, and you will die of rad poisoning. Connected to https://github.com/yogstation13/Yogstation-TG/issues/4263

Sing can irradiate not just engineering, but through reinforced walls, engineering space, which means you cannot fly (even further away) in space without getting irradiated.

**Comment by Altoids1** [comment]
It might make sense, now that we have the radiation collectors so close to the singularity, to make the radiation falloff of the singularity much stronger. Alternatively, I feel like just putting the singulo a tile farther away would probably do good work in fixing this problem.

**Comment by HomocidlePancakes** [comment]
Singulon is dumb.
