### ISSUE TITLE
Janitor's holographic sign projector does not fit into his jani belt

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5037]
Unlike every other holo projector and associated department belts.

**Comment by Lostlarry** [comment]
this is issue of wrong holoprojectors being vended ill see if i can find where their file is

**Comment by MegaEmpirical** [comment]
... There's more than one? Any reason to keep them both in the code?

**Comment by Lostlarry** [comment]
well there is general class holoprojector that defines behaviour common to every type it just happens that this default is almost same as janni one

**Comment by MegaEmpirical** [comment]
Fascinating. Fix merged, closing. Thanks for fixing.
