### ISSUE TITLE
Make D/C'd player logs easier to obtain

### ISSUE THREAD

**Issue by Rayisken** [yogstation13/Yogstation#5039]
When a player disconnects it can be a hassle finding client logs without having to view the current round log.Is it possible to have client logs stick to whichever mob they were d/c'd in?

![ADMIN LOGGING](https://user-images.githubusercontent.com/38535833/55557094-156d4f80-56b7-11e9-9ff7-76c667c9f3a8.PNG)

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
