### ISSUE TITLE
Planty the Cargo Technician grammar issue

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5058]
"About as helpful as a actual cargo tech."

Should be "an".

**Comment by Altoids1** [comment]
Could just fix it yerself, if it's a grammar issue.

**Comment by MegaEmpirical** [comment]
Never done a PR or anything related to that. Intending to learn soon so I will if no one fixes it by the time I get around to learning.

**Comment by Altoids1** [comment]
Great. Have fun, @MegaEmpirical

**Comment by fluffe9911** [comment]
but he never did learn how to code rip

**Comment by RANGERFLNDANGER** [comment]
lot of work but I'm ready

**Comment by RANGERFLNDANGER** [comment]
ready to learn code

**Comment by MegaEmpirical** [comment]
Eventually, I'm usually pretty busy.

**Comment by Kinrany** [comment]
Fixed?

This popped into my github feed; couldn't find the string in the repo

**Comment by MegaEmpirical** [comment]
It's fixed now.
