### ISSUE TITLE
Genetics "Antenna" trait prevents the usage of a headset

### ISSUE THREAD

**Issue by Firewolf34** [yogstation13/Yogstation#5062]
## Round ID: 22326

"Antenna" mutation forces all radio prefixes to output over the Common channel, at standard volume.

For example: I was Acting Captain this round so I had the opportunity of using a command headset with all available comms channels active, set to high volume. Giving myself the "Antenna" mutation resulted in the common channel being the only available comms channel for me. Pressing the semicolon and speaking came out at standard volume, despite high volume being set in my headset. Trying to use a secondary channel like Command or Security resulted in the speech being output to Common instead, with no warning, which could result in sensitive information being spoken over Common.

I believe most people would expect that "Antenna" would give them the permanent ability to speak over Common despite not having a headset. However it should not interfere with the headset if you are wearing one.

**Comment by Altoids1** [comment]
When would there be a situation where you need to talk on comms but lack your headset?

**Comment by Putnam3145** [comment]
The issue (which I noticed earlier today) is that antenna mutation doesn't let you talk in any channel *except* common--if you want to use :m to talk to medical, you just can't, it'll go over common instead, even if you have a headset which lets you talk to medical.

EDIT: Upon reviewing the code, looks like this might actually be a problem with *all* implanted radios, not just the genetic mutation.

**Comment by Firewolf34** [comment]
> 
> 
> When would there be a situation where you need to talk on comms but lack your headset?

Antenna, I would assume, is supposed to work like a station-bounced radio, so you can talk even when the comms are down. At least, that's what I imagine the purpose of it is. pretty pointless otherwise.

It has a picture of a station-bounced as it's icon, after all.

**Comment by Time-Green** [comment]
Just turn it off. You can simply turn the microphone on your antenna off and use your other radio
