### ISSUE TITLE
Hardsuit storage Unlockable without id?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#507]
Apparently you can unlock and lock hardsuit storage without the relevant ID for the department. (as HOS, cannot open atmos doors but can open storage)

**Comment by darkwahn** [comment]
It's been like that forever hasn't it?

**Comment by 00aquir** [comment]
Well, the Lock function doesn't make a damn sense then, right?

**Comment by Cruix** [comment]
The lock function is so that if you stuff someone in the unit, it takes more time for them to get out.

**Comment by Paragonid** [comment]
So how about adding ID restricted access to hardsuit storages?

**Comment by Super3222** [comment]
Wait, there wasn't already ID restriction? Jesus..
