### ISSUE TITLE
Was still considered cultist to an AI even after being converted back to normal

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#5072]
Round ID: 22360

S.A.F.E.T.Y. killed me (presumably because he saw my eyes glow red) even after I was de-converted from 
blood cult

**Comment by HomocidlePancakes** [comment]
Horrible bug!1!1 ORANGE MAN FIX IT!!!!!!!!!!!

**Comment by HomocidlePancakes** [comment]
Oh wait this is yog repo. DRONE MAN FIX IT!!!!!!!!

**Comment by oklews** [comment]
The AIs aren’t actually AIs

**Comment by oklews** [comment]
#3333
