### ISSUE TITLE
Lavaland spawn names are fucked and the golem creation data disk is missing.

### ISSUE THREAD

**Issue by Silk-Touch** [yogstation13/yogstation#508]
When you spawn as a escaped prisoner you don't get a name you just get "a free golem" or "an escaped prisoner" Also the disk to load the golem shells onto the autolathe is missing from the free golem ship.

**Comment by Silk-Touch** [comment]
Did you fix the broken names?

**Comment by Cruix** [comment]
Just fixed that on the host, it was a config file problem.

**Comment by Silk-Touch** [comment]
Sweet 🍬.
