### ISSUE TITLE
Feature: Low levels of radiation

### ISSUE THREAD

**Issue by oklews** [yogstation13/Yogstation#5086]
Occasionally you get a minor wave of radiation, not enough for a mutation, but enough to set off Geiger counters and carry some toxin damage.

Debating whether or not to notify the crew

**Comment by Altoids1** [comment]
As in... a minor variant of the Radiation Storm event?

**Comment by oklews** [comment]
Yeah, Something that would radiate you, but not FORCE you into maint.

**Comment by Altoids1** [comment]
Kinda defeats the purpose of the rad storm in the first place, though, innit?

If anything, it'd be *more* annoying, as tons of people would have minor damage as a result.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
