### ISSUE TITLE
Problem with stabilized Cerulean extract in Xenobiology.

### ISSUE THREAD

**Issue by Saratoubi** [yogstation13/Yogstation#5091]
Issue reported from  Round ID: 22392 (Yogstation 13)

Reporting client version: 512
 
So I noticed this issue in the round before, when I had made a stabilized cerulean extract (Body double), but I didn't re-spawn as it when I died. I made it again this round and noticed that after a while my clone disappeared, and I believe I know why. I'm not 100% sure on this mind you, but it might be worth looking at. It seems that when you pick up said slime extract after making it, WHILE you are logged into the console, it drops the body immediately instead of waiting til you activate it in your hand, and after a couple of minutes the body and the extract seemed to disappear from my inventory entirely. This might have something to do with the other extracts bugging out as well. So example I wanted to make a regenerative light pink extract, but when I gave the light pink slime the final purple extract, the whole thing disappeared. I believe I may have been logged into the console at the time. I might be wrong, but please check it out. Thanks!

**Comment by adamsong** [comment]
Cannot reproduce, even when logged into the console
