### ISSUE TITLE
Syndicate Agent ID card is not able to be used for many Antag Roles

### ISSUE THREAD

**Issue by Firewolf34** [yogstation13/Yogstation#5095]
## Round ID: 22410

Bug with `/obj/item/card/id/syndicate`.

Use an Agent ID card. It does not show the Forge/Show menu, it simply says "You show the Agent ID." 

Clicking it does not work, neither does the Z hotkey. Alt-clicking allows you to set the Account Number for the cash.

Attempting to use the Chameleon Change option in the HUD simply changes the way it looks, but does not let you forge the name or job title. 

This makes it essentially useless.

**Comment by Firewolf34** [comment]
Got a chance to play **Nuke Ops** at round 22413 and the default Agent ID card seems to work fine! Must have just been a bug for **Lone Op**, or maybe for that specific shift. 

I'll test it as Lone Op in a bit and make sure this is repeatable on a private server. If it isn't, I'll close the ticket, because then it's probably just a fluke (ops).

**Comment by MegaEmpirical** [comment]
I had no issues with my ID yesterday as a comms agent.

**Comment by Firewolf34** [comment]
CAN CONFIRM, this bug _**IS REPRODUCIBLE**_ testing on a private server running the latest master branch as of commit 999c91fbe3c587d5225777edf4ee29916c1fe220

It occurs for both Nuclear Operatives and Lone Operatives, but so far testing shows it only happens when they are spawned mid-round (i.e., not at Roundstart) this explains why the Nuclear Ops worked in shift 22413 but the Lone Ops did not in 22410 - Lone Ops is a midround antagonist event.

Changing the player over to a Traitor or IAA will make the Agent ID card work again. I believe it has something to do with it checking to see if the player is an antagonist status before allowing you to forge it. I don't see why it even verifies antagonist status to forge it, in my humble opinion it's okay if a non-antag (e.g. sec officer) can forge the ID... because if they have their hands on your ID you're toast already. But perhaps it prevents metagaming. But they can see the "Chameleon Change" HUD icon if they're antag or not, so it's a little pointless to even check.

In any case the verification process fails if you're a lone op or midround nuke op. I'll take a look at the code in a bit.

The item in question is: `/obj/item/card/id/syndicate `

**Comment by Firewolf34** [comment]
It's due to this check in https://github.com/yogstation13/Yogstation-TG/blob/e60cb77d2a3d37f02c1620cdc946cfd223fea67c/code/game/objects/items/cards_ids.dm#L299

```DM
/obj/item/card/id/syndicate/attack_self(mob/user)

if(isliving(user) && user.mind)
    if(user.mind.special_role || anyone)
        if(alert(user, "Action", "Agent ID", "Show", "Forge") == "Forge")
...
    ..()
```

The `user.mind.special_role` field is not being set correctly for these roles during mid-round, created via the TP menu in the Player Panel, and presumably via the antag spawner when a random midround event occurs. And since the card is not a `/obj/item/card/id/syndicate/anyone`-type card, the access restriction prevents you from forging it. Var-editing the field to anything other than null fixes the problem, confirming this was the issue.

Nasty side-effect is that the same check is performed in the `afterattack()` proc, meaning you cannot copy access from ID cards either. Strangely enough, even the "anyone" card still requires the "special role".

**Comment by Firewolf34** [comment]
So I did some digging. It seems many roles do not set the `special_role` field correctly, hence their role does not show up in the Admin Player Panel and they cannot use this ID, among other consequences. The roles which do not properly set the `special_role` var are:
- Cultist (nar'sie)
- Devil
- Nuke Ops (leader, standard, etc)
- Lone Op
- Clown Ops (leader, standard, etc)
- Space Pirate
- Revolutionaries (heads, non-heads)
- Wizard (imposter, apprentice, teacher, space, etc)
- Gangs (bosses, gangsters)

There's a `user.mind.special_role` used for setting antag status, and a `user.mind.assigned_role` used for setting the player's job/role.

For nukies, the `user.mind.assigned_role = ROLE_SYNDICATE`. See:
https://github.com/yogstation13/Yogstation-TG/blob/141ef8cab22d2d345af8525726bbb78a218cdfbc/code/modules/antagonists/nukeop/nukeop.dm#L120

However it does not set `user.mind.special_role`. This herein lies the problem. I'm not sure if this was a mistake or not, since usually the `assigned_role` is set to a text string and it's meant to be the Job title. Perhaps they meant to set `user.mind.special_role` instead. At roundstart, something else must be setting the var so that this proc doesn't have to because the ID's actually work properly if the nukie team is spawned normally. But this proc really should be the one to set it, as far as I can tell.

Would be really nice if this could be fixed for the other antag types as well.

**Comment by Firewolf34** [comment]
Why was this closed?

**Comment by MegaEmpirical** [comment]
Because Fluff went around closing random issues
