### ISSUE TITLE
Signal engineers are completely broken on donut

### ISSUE THREAD

**Issue by Putnam3145** [yogstation13/Yogstation#5108]
## Round ID: 22442

Signal engineers spawn in the AI chamber and immediately get permastunned by the taser. The telecomms satellite isn't anywhere near this. To access it, there's an airlock (unlabeled) in the southwest, near medbay, and once you get there you will find that the transit tube to tcomms doesn't work.

## Reproduction:

Literally just try playing a signal engineer as intended on donut, at all.

**Comment by MegaEmpirical** [comment]
Should also investigate paramedics and clerks.

**Comment by Putnam3145** [comment]
Psychiatrist spawned on top of me in engineering, this time.

Also, signal technician doesn't have access to maint, so no way to get there or back without help.

Also, the consoles start set on NULL instead of tcommsat.

**Comment by Putnam3145** [comment]
Also, no NTSL, just, at all? None of the monitors let me do it.

**Comment by MegaEmpirical** [comment]
Signal techs don't need maintenence.

**Comment by Putnam3145** [comment]
Sure, I agree, which is why it's odd that the only way to and from tcomms on yogdonut requires maint access.

**Comment by MegaEmpirical** [comment]
Ohh, didn't know that. The one time I played on it I was detective and got killed by revs outside my office 5 minutes in.

Should be settings for map specific access.

**Comment by Lostlarry** [comment]
well i got no clue whats that about weird spawns but im actualy pushing the NTSL console replace on donut and some other maps

**Comment by fluffe9911** [comment]
we dont got donut anymore doesnt matter
