### ISSUE TITLE
Floor tiler

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation#511]
Working on a floor tiler because adam

Gimme anything you think is relevant for coding it here before i get too far

**Comment by Silk-Touch** [comment]
Make it accept all different types of tiles like wood,gold, bananaium etc.

**Comment by ParagonPrime** [comment]
make it replace tiles in a 3x3 radius, and autoreplace damaged/broken tiles

**Comment by ShadowDeath6** [comment]
**_# floorbot_**

**Comment by AdamElTablawy** [comment]
Floorbots are shit

**Comment by Super3222** [comment]
Smells bad and powercreepy. Best for being made in R&D
