### ISSUE TITLE
Wire under window cannot transmit power

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#5116]
- Wire was cut at the left side of the window, after repairing that, the wire under the window itself stopped transmitting power to the right side.
- Disassembling the window solved the problem.

![SS13-bug-wirenottransmittingpower-](https://user-images.githubusercontent.com/16806055/56092217-47ea2a00-5eb9-11e9-9e56-a430537cf6ce.png)

**Comment by adamsong** [comment]
Cannot reproduce
