### ISSUE TITLE
The slime processor on Minsky is actually a food processor

### ISSUE THREAD

**Issue by Oakboscage** [yogstation13/Yogstation#5117]
The slime processor on Minsky is actually a food processor.

**Comment by GenericDM** [comment]
I'm pretty sure that the slime processor is just a renamed food processor.

**Comment by Oakboscage** [comment]
No it doesn't suck in slimes like it should, they're different objects. I checked.

**Comment by Altoids1** [comment]
@fluffe9911

**Comment by AsV9** [comment]
according to my contacts this hasn't been fixed yet idk

**Comment by Ktlwjec1** [comment]
Closing as this map is removed.
