### ISSUE TITLE
Atmos has two APCs that do the same thing

### ISSUE THREAD

**Issue by Enkaaa** [yogstation13/Yogstation#5120]
Issue reported from  Round ID: 22514 (Yogstation 13)

Reporting client version: 512

Atmos has two APCs. Atmos office and Atmos distro. When one is broken or has no power, both areas power down. If you decon one and the other still has power, the area powers back up and you can't replace the APC you just broke because there are two APCs in the same area.

**Comment by Ktlwjec** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/5371
