### ISSUE TITLE
Add Prisoner uniform crate

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5123]
Give cargo access to a crate with more prison uniforms. Por favor.

![image](https://user-images.githubusercontent.com/36208065/56173473-b7e0d900-5fbb-11e9-86a1-23b9d03b9d18.png)

**Comment by Altoids1** [comment]
If anyone who is new to contributing want to try this out, go for it. It isn't a terribly hard change.
