### ISSUE TITLE
Imaginary friends can be heard by ghosts from everywhere 

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5138]
Doesn't matter how far you are from them, you can still hear them speak when you've local ears on.

**Comment by fluffe9911** [comment]
I dont get this one are you saying like ghosts can hear imaginary friends on dead chat if so that doesnt really seem like a issue

**Comment by oklews** [comment]
They are saying if you turn off the ability to hear anything anywhere, the imaginary friend can still be heard anywhere

**Comment by MegaEmpirical** [comment]
Exactly as Ok has said. You're able to disable global hearing/sight as a ghost for various things, this bypasses that setting.
