### ISSUE TITLE
Ripley MK1 unupgradable to MK2 after collecting ore.

### ISSUE THREAD

**Issue by MarcosPauloMarques** [yogstation13/Yogstation#5139]
## Round ID:

[Round ID]: 22601 

## Reproduction:

Get a Ripley MK1 and deposit ores into the Cargo Compartment. 

Even if you release all the ore in your Cargo Compartment it will still be checked as it has something in it and the MK2 upgrade requires a empty Cargo Compartment to be applied to the MK1 Ripley.

![image](https://user-images.githubusercontent.com/18073899/56404817-39946900-623f-11e9-93a2-7618f9617084.png)

![image](https://user-images.githubusercontent.com/18073899/56404832-5a5cbe80-623f-11e9-9290-fb3ef23bfbd2.png)

**Comment by fluffe9911** [comment]
This is most likely still a issue but I have no clue how anybody would go about fixing it in a sane way

**Comment by adamsong** [comment]
This is no longer an issue
