### ISSUE TITLE
Super Fast Speed with Cardboard box

### ISSUE THREAD

**Issue by MarcosPauloMarques** [yogstation13/Yogstation#5150]
## Reproduction:Force the cardbox movement to the corners while touching a wall. I've seen there are plenty of threads about this, but none this year. So i'm leaving it here.

![image](https://user-images.githubusercontent.com/18073899/56454858-78a0e800-632d-11e9-813f-6cc6bb12cc98.png)

**Comment by MegaEmpirical** [comment]
This hasn't been fixed yet? Thought it had been.

**Comment by HomocidlePancakes** [comment]
Never was fixed. Also fucking newfffffffff... FRIENDS re-reporting known bugs

**Comment by Altoids1** [comment]
Dupe of #2324 . Closing.
