### ISSUE TITLE
Nightmares take from the human name pool.

### ISSUE THREAD

**Issue by GenericDM** [yogstation13/Yogstation#5156]
Issue reported from  Round ID: 22642 (Yogstation 13)

Reporting client version: 512
![image](https://user-images.githubusercontent.com/34109002/56464636-9d837280-63a2-11e9-858b-0c71c7fcc828.png)

**Comment by Altoids1** [comment]
```dm
/datum/species/shadow/nightmare/on_species_gain(mob/living/carbon/C, datum/species/old_species)
	. = ..()
	to_chat(C, "[info_text]")

	C.fully_replace_character_name("[pick(GLOB.nightmare_names)]")
```
it *oughtn't* do that.
