### ISSUE TITLE
Red slime water reaction.

### ISSUE THREAD

**Issue by Saratoubi** [yogstation13/Yogstation#5164]
Issue reported from  Round ID: 22663 (Yogstation 13)

Reporting client version: 512

The reaction the red slime extract has when injected with water is supposed to give a speed potion, but atm it does nothing.

**Comment by MegaEmpirical** [comment]
Not a bug, feature.

https://github.com/yogstation13/Yogstation-TG/pull/4178

**Comment by Saratoubi** [comment]
Why is that a feature though? The speed potion was actually fairly useful. The original post you linked states "You may as well remove the speed potions because they do literally nothing", which I don't believe is the case. Did this person not understand that you have to apply the potion to a set of clothing with a speed debuff in order to use it correctly? The speed potion gave a alternative to the stabilized red slime extract. It was one of the more useful reactions in xenobiology.

**Comment by Saratoubi** [comment]
Altoids re-added the speed potions for red slimes.

**Comment by MegaEmpirical** [comment]
... They ended up not simply adding it back in and did something crazy:

https://github.com/yogstation13/Yogstation-TG/pull/5180

**Comment by Altoids1** [comment]
I'd call that resolved.
