### ISSUE TITLE
Pre-rebase feature of disabling seeing jobs in chat for AI

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5166]
Please re-add this so we no longer have to see things like this:

![image](https://user-images.githubusercontent.com/36208065/56481388-bec08d80-648c-11e9-8426-6639bcfffbc4.png)

**Comment by Altoids1** [comment]
Are you *sure* it's not in the rebase?

**Comment by MegaEmpirical** [comment]
No but I've not seen it anywhere, it's possible I've missed it.

**Comment by MegaEmpirical** [comment]
Confirmed. I have seen it as of today.

**Comment by jcatjmeow** [comment]
Feature requests go on the forums now sorry :(
