### ISSUE TITLE
Missing r glass pane in Ai core

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5167]
Yogbox

![image](https://user-images.githubusercontent.com/36208065/56482849-3cd46280-6494-11e9-8976-864193814062.png)

Missing on left.

**Comment by HomocidlePancakes** [comment]
Pretty much half of the rglass panels on box disappeared 4nr. This includes gift shop, genetics and AI corr. Maybe more. Idunno. Too lazy too search

**Comment by HomocidlePancakes** [comment]
Also medbay storage

**Comment by MegaEmpirical** [comment]
Any idea if they're all ones facing the same direction?

**Comment by HomocidlePancakes** [comment]
Yep. They are

**Comment by Putnam3145** [comment]
Probably https://github.com/yogstation13/Yogstation-TG/commit/a7ea58d1254e599dfa155ff7fad62f43b3ca2be1, I don't know enough about .dmm files to know if all these changes are extraneous

**Comment by Altoids1** [comment]
@ChewyPizza

**Comment by Altoids1** [comment]
Fixed by https://github.com/yogstation13/Yogstation-TG/pull/5172, closing
