### ISSUE TITLE
Mentors (non-donors) still only have 3 slots

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5169]
Still only seeing three character slots.

**Comment by Altoids1** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by HomocidlePancakes** [comment]
Why do you need more then 3 lul

**Comment by Altoids1** [comment]
![image](https://user-images.githubusercontent.com/29939414/56611075-947ae700-65d6-11e9-8243-9cb6da42c711.png)

![image](https://user-images.githubusercontent.com/29939414/56611094-9e044f00-65d6-11e9-87a0-57499670df1d.png)

So I'm pretty sure it's just you, Lyis, if anyone. @MegaEmpirical

**Comment by MegaEmpirical** [comment]
Someone else had said they were short to me the other week as well. I'll check again when I get home.

**Comment by MegaEmpirical** [comment]
![image](https://user-images.githubusercontent.com/36208065/56628201-e0e61700-6616-11e9-8390-cb7297d846c4.png)

**Comment by MegaEmpirical** [comment]
Asked another mentor, they said they only had three. Might be a mentor specific issue.

**Comment by MegaEmpirical** [comment]
I've asked around some more. A mentor donor only has 3. Mentors only have 3. Donors have 6. So it's something fucky with being a mentor.

**Comment by MegaEmpirical** [comment]
Donors seem to be excused from the issue currently. Mentors still being fucked though.

**Comment by MegaEmpirical** [comment]
Fucking finally fixed.
