### ISSUE TITLE
Port vox (raiders)

### ISSUE THREAD

**Issue by ThatLing** [yogstation13/Yogstation#5179]
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums here: https://forums.yogstation.net/index.php?forums/rebase-votes.202/
its a fun gamemode

**Comment by HomocidlePancakes** [comment]
Bay man bad

**Comment by oklews** [comment]
Pirates? Operatives?

**Comment by ThatLing** [comment]
Raiders

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
