### ISSUE TITLE
Cannot replace APC on the same wall.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#5181]
- "This area already has an APC!"

![SS13-bug-secAPC](https://user-images.githubusercontent.com/16806055/56586303-bdec4080-65df-11e9-9d9c-a1f63231c5fd.png)

**Comment by MegaEmpirical** [comment]
Generally I just avoid placing APCs where they used to be since map placed APCs are fucky.

**Comment by HomocidlePancakes** [comment]
Um. There is an APC on the opposite wall. No shit it won’t allow you to replace(also I broke that APC lul)

**Comment by 00aquir** [comment]
I put that APC on the opposite wall there, I just wanted to take a picture of where the original APC was, because the game doesn't allow you to put it there anymore, so you must start rewiring the foor.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)

**Comment by MegaEmpirical** [comment]
However it is a duplicate of a pre-existing issue, though this one phrases it better (or it did until I update the other).

https://github.com/yogstation13/Yogstation/issues/5881
