### ISSUE TITLE
HoS can Spawn as Gang Boss

### ISSUE THREAD

**Issue by Colburn3000** [yogstation13/Yogstation#5182]
So the HoS can spawn as a gang boss. Not sure if that is an intended feature, but I am guessing it isn't

**Comment by HomocidlePancakes** [comment]
YOINK

**Comment by HomocidlePancakes** [comment]
Ok now this is epic

**Comment by fluffe9911** [comment]
f e a t u r e

**Comment by Lostlarry** [comment]
so i cheked the code. not only is gang stuff located in the yogstation file separate from the rest of antag files(that i presume we are actualy using) but HoS is among the blacklisted jobs in the main antag file so unless theres a typo or other gang files(with word gang not in their name) this shouldnt happen

**Comment by adamsong** [comment]
HoS is no longer able to spawn as gang boss
