### ISSUE TITLE
Wrong Xenobiology north camera

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#5249]
Round 22772
Xenobiology north:

![SS13-bug-xenonorthcamera](https://user-images.githubusercontent.com/16806055/56849236-50e3ee00-68f2-11e9-980b-8123b41e4fbd.png)

**Comment by Altoids1** [comment]
@ChewyPizza

**Comment by 00aquir** [comment]
Again, yesterday xeno north camera looked at perma holodeck, but in the next shifts, now it's looking at xeno north.. sometimes this happening, sometimes not.

**Comment by 00aquir** [comment]
Again, yesterday in a round xeno north camera showed perma holodeck, but in the next shifts now, it's showing xeno north.. sometimes it happens, sometimes not.

**Comment by Ktlwjec** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/5508
