### ISSUE TITLE
PAI Toolbar Doesn't show

### ISSUE THREAD

**Issue by MysticalJuden** [yogstation13/Yogstation#5296]
Issue reported from  Round ID: 22802 (Yogstation 13)

Reporting client version: 512.1467

**Comment by MysticalJuden** [comment]
Twice ive played as a PAI and the toolbar in the top left doesn't appear. I've tried logging out and back in, plus reinstalling byond and that hasnt solved the issue

**Comment by Altoids1** [comment]
Caused by /TG/. Complain at them to fix their shit.

**Comment by adamsong** [comment]
I'm pretty sure this was fixed
