### ISSUE TITLE
Seriously, Less gang round chance.

### ISSUE THREAD

**Issue by Superscifi** [yogstation13/Yogstation#5298]
So i've played 10 rounds, randomly throughout the day. 7 were gangs. I can't tell if my luck sucks, but other people also agree that it's too common, I dont hate gangs, just let other gamemodes shine?

**Comment by MegaEmpirical** [comment]
There is already a survey for determining this kind of thing:

https://forms.gle/yfPFifsR38oD9gAYA

**Comment by Altoids1** [comment]
As the survey states, gang's at a 7.1% chance of running.

There is also, I *think*, a thing that puts lower weight to gamemodes that have happened recently.

Now, that doesn't mean that it's utterly impossible for there to be 7 gang arounds in a batch of 10. It just means that it's unlikely for that situation to happen a lot.

It doesn't mean that it *can't* happen. Sometimes there will just be 5 Ragin' Mages rounds in a row; that's just the nature of random chance: to cause random clumpage.

There's nothin' to be done of it.

**Comment by MegaEmpirical** [comment]
Would it be possible you to confirm that repeated round types are less likely Alt? Or is that a hassle? I've always been curious and I'd have no idea where to even begin to look for that.
