### ISSUE TITLE
Remove certain phrasing from antag flavor text

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5304]
I think we should remove things like "by any means necessary" from antagonists that are not allowed to murderbone. It sends the wrong message/instruction compared with what is enforced by the rules.

**Comment by Altoids1** [comment]
I'ma just assign you repeatedly to every simple text edit you make a Github issue for.

**Comment by MegaEmpirical** [comment]
Sure, fine. I'll see about learning how Saturday.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
