### ISSUE TITLE
Wizard warps

### ISSUE THREAD

**Issue by johnnyboyz25** [yogstation13/Yogstation#5305]
## Round ID:
**YOG (not a recent round)**

## Reproduction:
Wizard, teleport to atmospherics on Yog-box. The teleport put me inside of the CO2(?) (top-right) tank, which would've caused me to die pretty quickly had I not been using Ethereal Jaunt as well. Please adjust the areas which the Wizard can teleport to within Atmos.

**Comment by MegaEmpirical** [comment]
Huh, must have been screwed up when atmos was changed.

**Comment by johnnyboyz25** [comment]
Absolutely right sir.

Checked last night, I had landed in the CO2 tank of YogBox, right in the middle of the tank. Unprotected, you'll last not longer than 2 minutes in there...

**Comment by MegaEmpirical** [comment]
Just be glad it wasn't N20, wizard nap time. But yeah, suffocation and lots of pressure damage, I'd wager less than 2 minutes.

**Comment by johnnyboyz25** [comment]
How do I get this marked as a bug to be patched?

**Comment by MegaEmpirical** [comment]
By either getting permissions to do so for this git, unlikely. Or having someone with permissions do it, which will happen when they get around to it.

**Comment by Lostlarry** [comment]
bot sometimes tags stuff but the accuracy is... variable. ill take a look at the map but im not sure if i can find the exact stuff since im kinda new to this

**Comment by Lostlarry** [comment]
Found the problem the issue is that the target for wizard TP is first tile of said area so fix is to make the tanks non teleportable area seperate from rest of atmos

**Comment by jcatjmeow** [comment]
Going to confirm this is still a bug right now

**Comment by jcatjmeow** [comment]
Well.
Teleporting to Atmospherics Distrobution does teleport you inside the CO2 tank.

Teleporting to Atmospherics teleports you to the atmos foyer.

**Comment by adamsong** [comment]
I tested this, and get warped into the N2 tank, so still an issue
