### ISSUE TITLE
Rolling a 17 on Die of Fate will always spawn an empty box instead of syndicate bundle

### ISSUE THREAD

**Issue by HomocidlePancakes** [yogstation13/Yogstation#5307]
I already reported that on TG a month ago and we didn't mirror the fix for some reason. This is dumb

**Comment by Altoids1** [comment]
If you can find the exact PR I can get it merged.

**Comment by HomocidlePancakes** [comment]
https://github.com/tgstation/tgstation/pull/43323

@Altoids1

**Comment by Ktlwjec** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/5430
