### ISSUE TITLE
Please change mhelp dark mode text to something readable

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5311]
Currently:

![image](https://user-images.githubusercontent.com/36208065/57052446-2d53d700-6c55-11e9-89ef-24fbe2e6e738.png)

**Comment by Altoids1** [comment]
Will be fixed by https://github.com/yogstation13/Yogstation-TG/pull/4940.

**Comment by MegaEmpirical** [comment]
Does this also change the color of suffocation damage when using items like health analyzers?

![image](https://user-images.githubusercontent.com/36208065/57173253-ee5f8600-6dfa-11e9-8194-db1620dd5cb2.png)

**Comment by MegaEmpirical** [comment]
Was not fixed by https://github.com/yogstation13/Yogstation-TG/pull/4940

will be fixed by https://github.com/yogstation13/Yogstation-TG/pull/5498

**Comment by MegaEmpirical** [comment]
Reopening since only newly incoming mhelps were fixed.

**Comment by MegaEmpirical** [comment]
....if I could reopen, making a new one.
