### ISSUE TITLE
Shadowlings shouldn't be able to use flashes

### ISSUE THREAD

**Issue by wilfredrickson** [yogstation13/Yogstation#5315]
It seems kinda dumb that shadowlings can use flashes to incapacitate people with no negative effects to themselves.  You'd think that a creature made of darkness wouldn't react well to letting out bursts of light in close proximity to their eyes.

**Comment by MegaEmpirical** [comment]
Flashes are directional and nearly instant and shadowings are able to walk in light but it'll slowly kill them so it makes perfect sense that they can use flashes. However, maybe it should do a tiny amount of damage. Though if you disarm them and use it on them, they will pay a dear price.

**Comment by HomocidlePancakes** [comment]
>tfw you call something a bug because it doesn’t fit with your interpretation of lore

**Comment by wilfredrickson** [comment]
I never called it a bug, nor did I make this a bug report.

**Comment by wilfredrickson** [comment]
> However, maybe it should do a tiny amount of damage.

I was thinking something along the lines of just taking direct eye damage (like when you use a welder without goggles)

They already have so many tools at their disposal, why should we allow them to use incredibly powerful ones that logically don’t make sense.

**Comment by MegaEmpirical** [comment]
A flash is not incredibly powerful and I explained why it logically made sense that they could already.

Causing them eye damage on use would be funny/cool.
