### ISSUE TITLE
Could we add a timer/delay to buckling players to chairs?

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5316]
https://forums.yogstation.net/index.php?threads/maybe-add-a-progress-bar-delay-to-buckling-someone.18185/

**Comment by HomocidlePancakes** [comment]
Not again...

**Comment by MegaEmpirical** [comment]
You failed to provide any meaningful commentary in the thread and I've still no idea why you're against it.

**Comment by oklews** [comment]
I mean, this is a bootleg stun, you get buckled you’re getting punched like twice for it. Otherwise there is nothing wrong with adding a timer.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
