### ISSUE TITLE
Moths unable to fly when pressure drops

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5319]
Whilst this is understandable if the pressure drops too low, at 70 kpa that's just dumb. Pressure dropped since there was a hole in the station (other end of the hall) so I'm not sure if it's explicitly pressure or something to do with distance from hole.

**Comment by Putnam3145** [comment]
It's 86.12625 kPa where moths are unable to fly:
https://github.com/yogstation13/Yogstation-TG/blob/f3b7b47aee43288a06d87f6000961dafc0ef4431/code/modules/mob/living/carbon/human/species_types/mothmen.dm#L61

**Comment by MegaEmpirical** [comment]
Ah so it was intentional. Seems a bit low but sure, I'll close this. Thanks.
