### ISSUE TITLE
Character preferences turn me from lizard into a human on server reset sometimes.

### ISSUE THREAD

**Issue by Razoozle** [yogstation13/Yogstation#5331]
## Round ID:
22912

## Reproduction:
So basically I play as a lizardperson. During server start I open character preferences to find that I am turned into a human with long hair and I am given a human surname. I have to manually set my race back to lizard and remove the surname and re-save. It does not seem to remove any other settings besides this, at least from what I've noticed.

**Comment by oklews** [comment]
It happens all the time, watch for them altering your last name if you only have one strain of name

**Comment by k-k-karma** [comment]
good lol

**Comment by Lostlarry** [comment]
I think you have to not load the character until it's subsystem is loaded not sure which one is it tho
