### ISSUE TITLE
Recreational Holodeck

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#5364]
The perma holodeck is called "Recreational Holodeck" on monitoring but isn't that also what the other holodeck is displayed as? If that's the case, alerts can't tell you which area is affected, but basically its name should be descriptive enough so people know it's in perma, thus it should have another name.

**Comment by 00aquir** [comment]
Also I don't think that this camera is visible on sec camera console.

**Comment by Lynameep** [comment]
I'll take a look at this when I get the free time.
