### ISSUE TITLE
Lavaland swarmers can teleport you in to lava

### ISSUE THREAD

**Issue by HomocidlePancakes** [yogstation13/Yogstation#5400]
Nichlas made the base randomly appear on the lavaland but forgot to set teleport points. Thanks Nich. Very cool!

**Comment by fluffe9911** [comment]
f e a t u r e

**Comment by redmoogle** [comment]
Fixed, they now have extended safety checks

**Comment by HomocidlePancakes** [comment]
@redmoogle Actually, this was never bugged. It was later figured out that I was wearing a BoH.
