### ISSUE TITLE
Slimes and extinguishers

### ISSUE THREAD

**Issue by Redlik56** [yogstation13/Yogstation#5470]
Issue reported from  Round ID: 23245 (Yogstation 13)

Reporting client version: 512.1463

When oil slime latched on me, I couldn't resist or use a fire extinguisher on myself to kill him. It just didn't work.

**Comment by HomocidlePancakes** [comment]
Eh, it’s not as simple as pointing the extinguisher in the general direction of the slime and using it. You may end up not hitting the slime with it at all if you don’t aim it properly. Thats one. Two. You have to disarm the slime off, not resist.
