### ISSUE TITLE
I 

### ISSUE THREAD

**Issue by CptHonk92** [yogstation13/Yogstation#5494]
Issue reported from  Round ID: 23282 (Yogstation 13)

Reporting client version: 512.1468 for some reason when I fire my KA or plasma cutter or any other weapon in game I end up firing in the opposite direction. I face down to fire and my shot goes directly behind me. can you guys help me.

**Comment by MegaEmpirical** [comment]
Not a yog issue. It's a byond issue. Revert to version 1467.

**Comment by CptHonk92** [comment]
thanks for the help

**Comment by Altoids1** [comment]
Related to the BYOND issue. Answered by Mega. Closing.
