### ISSUE TITLE
weapon fire calibration issue

### ISSUE THREAD

**Issue by CptHonk92** [yogstation13/Yogstation#5495]
Issue reported from  Round ID: 23284 (Yogstation 13)

Reporting client version: 512.1468
I'm still have an issue with firing it keeps firing in opposite directions when I try to use any ranged weapon

**Comment by MegaEmpirical** [comment]
Not a yog issue. It's a byond issue. Revert to version 1467. Also, this is a duplicate issue, you've opened two for the same thing.
