### ISSUE TITLE
Rearrange gang boss in check antags (for admins)

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#5502]
Add gang bosses to the top of their gang list, currently they're just added in like normal gang members. Just a little thing to make viewing easier.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
