### ISSUE TITLE
Chameleon gang recruitment item

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#553]
To end the "he's holding a pen near me, must be gangs reeeeee" metagame.

Allow the gang recruitment item to be customized between various tiny, pocketable items.

Anything such as:

-Pen
-Crayon
-Electric razor
-Lipstick
-Dropper
-Cigarette

And other _**tiny**_ items.

Should hopefully decrease the metagame a little bit.

**Comment by ShadowDeath6** [comment]
how would a multitool work

would it also function as a multitool

would we see sec trying to use the multitools to open doors to test them

**Comment by ParagonPrime** [comment]
I guess since the pen still works as a pen (right?) the multitool would work as intended.

If that's too OP for a roundstart item, scratch it, it's just one item on the list.

**Comment by ShadowDeath6** [comment]
op

**Comment by Kmc2000** [comment]
You forgot the mixtapes


No x :100:

**Comment by Super3222** [comment]
This is good. We might need individual sprites of those items glowing however.

**Comment by ParagonPrime** [comment]
Yeah but I would assume that to be relatively simple. Just a few blue pixels in select places.

**Comment by Alek2ander** [comment]
Don't hold out your recruitment tools where people can see them!
Whip it out and do the business, then hide it again.
That's the only way.

**Comment by ParagonPrime** [comment]
Yeah, but this should still be implemented because

-It's dead simple (make it a new coder project or something)
-It reduces metagame (always good)
-It doesn't have any downsides that I can think of. At all.

**Comment by Kmc2000** [comment]
PARAGON


ADD.


MIX.


TAPES.

**Comment by AdamElTablawy** [comment]
Chameleon converter so you can change what it looks like on the fly?

**Comment by ParagonPrime** [comment]
Yes, adam, YES.

**Comment by Kmc2000** [comment]
I can work on this when i get back, if no one else does

**Comment by ParagonPrime** [comment]
select whatever items you think are appropriate, KMC, though they have to be

-tiny
-unsuspicious to find on anybody of any occupation
-generally very easy to access/commonplace
-have no major, very useful utility

**Comment by Kmc2000** [comment]
I give you fair warning, one of them will be a dildo

**Comment by AdamElTablawy** [comment]
The sprite for the dildo should be the old command hardsuit
