### ISSUE TITLE
Ninja suit is even easier to get now then before

### ISSUE THREAD

**Issue by HomocidlePancakes** [yogstation13/Yogstation#5545]
1)Mobs by the entrance end up running in to a same corner and shooting each other which leaves you with just one mob to kill.
2)Each of them drops a mosin which makes the killing anything in the ruin trivial
3)You can "picaboo" the entrance turrets 
4)The area after the entrance has plasma mines. None of the mobs are fireproof, so set one off and wait untill all the mobs die.
5)Turrets by the ninja suit vault are super easy to kill thanks to the unholy amount of guns you get from mobs.

@Lynameep

**Comment by Lynameep** [comment]
Already got some stuff in plan for the bunker. Don't worry~
