### ISSUE TITLE
Holochips have no export value

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5586]
Holochips, essentially the new space cash, have no export value for cargo whereas space cash does.

**Comment by MegaEmpirical** [comment]
Hmm I'm too conflicted to commit to bug or not. Definitely oversight.

**Comment by HomocidlePancakes** [comment]
Intended. Was removed after the addition of economy. Use the vault or cargo budget card

**Comment by MegaEmpirical** [comment]
Oh? Interesting, I'll close this then. Thanks.
