### ISSUE TITLE
Borg Welder Bug

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#562]
Every single click on anything (good plate, good floor, etc.) is depleting welder. Chase a space carp on hallway and empty all of your fuel without using it on anything...

**Comment by Alek2ander** [comment]
It's realistic!

**Comment by 00aquir** [comment]
well I see it's every welder but it became apparent only when I was playing borg.. and you're still not using the welder on anything and there is no feedback, ergo it makes zero sense.

**Comment by AdamElTablawy** [comment]
That's because of the change allowing you to attack machines and objects. It includes hitting the floor as an attack and so consumes welding fuel.

**Comment by 00aquir** [comment]
Uh so it's good from robusting point of view so that someone will only have 10-15 hits with it? well.. still it was nice when you didn't have to refuel immediately after you weld 20 broken tiles after a breach.

**Comment by ahamedx** [comment]
I don't think this can be fixed. The way it works currently, the welder issues an attack proc to the clicked object, and if the clicked object has a if(welder) in the attackby proc, it interacts with it. If this is to be fixed, we'd have to make the welder check if the attacked object can interact with the welder in its attack proc, and EVERY time we want to add a new weldable object, we'd have to add it in the attack proc for the welder. I think the current way is much better.

**Comment by 00aquir** [comment]
well.. how did it work before?

**Comment by ahamedx** [comment]
If you wanted to add a weld interaction to an object right now, you would go to the object's attackby proc and make it start the weld interaction when its hit by a welder. If we fixed the bug and then went to add a weld interaction to an object, we'd have to add a check in the welder's attack proc to check if we're attacking the object, then make the object start the interaction. this means we would need to add a huge if tree to the attack proc to check if we're attacking a weldable object every time we attack.
Adding that if tree to the attack proc means we're making the code a lot uglier and also slower.

**Comment by 00aquir** [comment]
What about eliminating the fuel consumption for the most commonplace item that doesn't need welding: the floor. This one change would solve a huge chuck of this "problem".
