### ISSUE TITLE
Add a way to check off crimes that have had time/fines served for already

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5626]
It is really difficult to keep track of which crimes a person has served already without clearing the record which paints a poor picture later on for repeat offenders  so a means of marking stuff as served would be fantastic.

**Comment by ynot01** [comment]
You can check when the crime was added, so just use common sense, if it happened 20 minutes ago it probably isn't the current crime.

**Comment by MegaEmpirical** [comment]
That makes no sense, they could have easily been on the lamb the whole time or even ignored. Happens all the time. I arrested a guy yesterday for shit he did at round start an hour later.

Also, criminal scum are often repeat offenders. I once arrested the same guy three times within 20 minutes because he kept doing the same shit right after being released.

**Comment by Rayisken** [comment]
This would be a nice functionality update for the sec records comp, might see more use if users don't have to type out every crime and come up with their own formatting for ~2hour period at most

**Comment by MegaEmpirical** [comment]
Hmm, if you could apply crimes like how the HoP or an airlock board does access then that would be convient.

I'd just be happy with a way of marking which crimes have been served though. I usually don't have issues filling out the crimes.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
