### ISSUE TITLE
Various service department members lack access to service lathe

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5627]
Can't open service lathe door as clown, mime, and lawyer. Likely curator too, maybe more.

**Comment by MegaEmpirical** [comment]
Not quite a bug, more oversight.

**Comment by Lynameep** [comment]
I shall handle this.

**Comment by MegaEmpirical** [comment]
Mind checking the other service jobs whilst at it? I wouldn't be surprised if mime and curator were missed too.

**Comment by MegaEmpirical** [comment]
I tested mime, mime is fucked too.

**Comment by MegaEmpirical** [comment]
Still a fucking issue.

**Comment by MegaEmpirical** [comment]
Updating title to be more inclusive since this affects clowns, mimes, and lawyers. Possibly curators too.

and linking the lawyer specific issue for this, that I am now closing in favor of the single issue: https://github.com/yogstation13/Yogstation/issues/6371
