### ISSUE TITLE
Internal affairs agent doesn't have a separate pref

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/Yogstation#566]
See title.

To be specific, it seems like internal affair agents doesn't have a specific pref for it, and disabling tator or blood brothers doesn't seem to work for disabling it

inb4 database memes

**Comment by GrayRachnid** [comment]
/tg/ doesn't seem to have it either

https://i.imgur.com/hGtMVcC.png

**Comment by GrayRachnid** [comment]
IA follows the traitor preference, closing this for #569 in exchange.
