### ISSUE TITLE
Both abductors unable to use tool/teleconsole

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/Yogstation#5673]
ROUND ID: 23504
Reproduction:

Be ghost
Join as abductor
Try to use tools/console to buy shit in near teleporter pad
Be unable to do so
Cry because you cannot do anything but teleport down to station

**Comment by Rayisken** [comment]
I have seen at least one ahelp related to this, it used to be only admin spawned abductors would have issues with the tools.

I do not recall if Gamer01 attempted to add organs/implants as a workaround

**Comment by Sniblet** [comment]
![image](https://user-images.githubusercontent.com/36427443/59984648-2c5a7880-95fa-11e9-934d-77eb670d5e64.png)
this is still a thing, we were midround random event-spawned

**Comment by adamsong** [comment]
Which console is not working? It seems they are all working for me

**Comment by adamsong** [comment]
This has been fixed
