### ISSUE TITLE
Signal tech winter coat doesn't allow air tanks to be slot

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5689]
All other winter coats allow small air tanks to be slotted into the exosuit slot, except signal tech winter coat.

**Comment by HomocidlePancakes** [comment]
>applying the label Bug to this issue, with a confidence of 0.57.
0.57

1)If xcom has taught me anything, it’s that anything under 80% is unreliable and anything under 70% is a YOOOOOOLOOOOOO.

2)@Lostlarry it’s an oversight, not a bug. Don’t :thumbs_up: it
