### ISSUE TITLE
People are getting antags despite having them disabled in pref.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/Yogstation#569]
why do dis?

**Comment by Altoids1** [comment]
Does IA actually follow the traitor preference, as you said in #566 ? I had a guy a few rounds back who got IA despite definitely having traitor preferences set to No.

**Comment by ThatLing** [comment]
My guess is that it's picking random people because not enough people have the preference set to enabled.

**Comment by Amelia0010** [comment]
mhm

**Comment by GrayRachnid** [comment]
Still an issue.

**Comment by Amelia0010** [comment]
i'll probably make a TG PR to fix this later
