### ISSUE TITLE
Dark-proof phytosian

### ISSUE THREAD

**Issue by Toskin** [yogstation13/yogstation#570]
Problem is easy. I'm standing as Phytosian in complete dark, and I'm not losing any health.

**Comment by timkoster1** [comment]
Could you actually tell us where and how long?

**Comment by 00aquir** [comment]
complete dark.. that means you didn't have flashlight on.. well after a while phytosian's health should diminish

**Comment by AdamElTablawy** [comment]
Thats the bug aquir

**Comment by 00aquir** [comment]
it's okay, but the effect is not immediate as far as I know..
