### ISSUE TITLE
Unable to terminate 

### ISSUE THREAD

**Issue by Misha600** [yogstation13/Yogstation#5709]
## Testmerges:

![brokenmech](https://user-images.githubusercontent.com/50932223/58992280-5cabb580-87b8-11e9-96e8-df632882d036.PNG)

## Reproduction:
I don't know how to reproduce this, but it happened after the firefighter mech's battery died. I activated maint protocols to try and remove the battery. It worked and i replaced it, but the button to terminate the maintenance protocol didn't do anything, it just caused a scrollbar that did nothing to appear.

**Comment by jcatjmeow** [comment]
I can't reproduce it either
