### ISSUE TITLE
Give chaplains the ability to bless people

### ISSUE THREAD

**Issue by abdbla** [yogstation13/yogstation#571]
Give them a super low cooldown spell (2s or so) which blesses a nearby person. Does nothing beside give a message ("<Chaplain> has blessed <the Blessed>"), plays a sound (HAAALLELUJAH) and slightly damages cultists.

Would give chaplains something to do.

**Comment by Alek2ander** [comment]
Blessing items seems more interesting to me.

You fire the blessed +5 advanced taser.

**Comment by X-TheDark** [comment]
And allow multiple blessings on the same item with an increasing cooldown for each additional blessing.
"[X] fires his blessed blessed blessed blessed blessed blessed blessed blessed blessed blessed..."

**Comment by AdamElTablawy** [comment]
No damaging cultists, but applying a sparkle or yellow color effect temporarily to anyone blessed and blessing items just for the name change would be fun.

I'm worried about midi spam lag however, increase spell cooldown to 5.

**Comment by Alek2ander** [comment]
Note: This won't have MIDI lag, since the sound is already cached in all clients

**Comment by EMT321** [comment]
@Cruix This has been implemented, can it be closed?
