### ISSUE TITLE
BAD turbine doors on Yogspubby and Yogsdelta

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#5710]
Seemingly on both stations, the turbine double-door system can get stuck under certain conditions. For example, when coming back from space, the airlock sensor can handle the doors, but sometimes it got stuck in a state when it didn't repressurize (maybe by pressing buttons also on the other controls on the wall) and I couldn't go inside.

Even on Yogsbox, you can accidentally make the doors stuck (by either standing inside one door when you use the buttons or controls inside or outside, or you press more than one of them, or just one, more than once in succession).

In this latter case (on this station you don't have to repressurize the inner room), if you hack the doors so that you switch the bolted-unbolted state for them, the controls will work again afterwards.

**Comment by HomocidlePancakes** [comment]
Not a bug. Atmos just wasn’t set up

**Comment by 00aquir** [comment]
"Atmos just wasn’t set up" Makes no sense. Even with the vents on and atmos set up, they fail to do repressurization some of the time, even though they often work. On a station where there is no need to repressurize, the controls not being able to handle the doors in any other specific states can make them stuck esily (e.g. when space wind moves someone into the door while they are pressing the button).

An atmos tech would have to be able to hack both doors every time this happens, otherwise either the inner door remains open, or they simply cannot go back to the station there.
