### ISSUE TITLE
Signal technician doesn't have access to engineering (Yogspubby)

### ISSUE THREAD

**Issue by Lunatoid** [yogstation13/Yogstation#5757]
Signal technicians are basically stuck at the telecomms room.
They don't even have access to the "Telecommunications Transit Tube" door. 
Pls fix.

Issue reported from  Round ID: 23599 (Yogstation 13)

Reporting client version: 512.1470

**Comment by Andronnnn** [comment]
There is also no Traffic Control Console to upload scripts. Bug still relevant.
