### ISSUE TITLE
Shapeshift is bugged and OP

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation#576]
![untitled](https://cloud.githubusercontent.com/assets/16478175/17683698/377dd516-630a-11e6-8ae5-2a7317ce78a0.png)

Please
![blue_discus](https://cloud.githubusercontent.com/assets/16478175/17683718/647cf1d2-630a-11e6-8f8e-7b46b00747fc.jpg)

**Comment by ShadowDeath6** [comment]
>controversial

implying everyone who picks it doesn't know it's broken as fuck

**Comment by Super3222** [comment]
It's being fixed right now.

What else is broken?
What else is bugged?
What else is OP?

**Comment by Notamaniac** [comment]
Turning into a mouse gave you O2 damage last time I used shapeshift. I managed to instantly kill myself when I transformed back into a human from oxy loss.
