### ISSUE TITLE
"Boneless" Borgs

### ISSUE THREAD

**Issue by BoxcarPenguin** [yogstation13/Yogstation#5766]
Issue reported from  Round ID: 23604 (Yogstation 13)

Reporting client version: 512.1467

I was playing an engie borg. I was hit by a clown car. I prepared to smack it with my crowbar  when it crashed. Someone destroyed the clown car and I was disabled. A roboticist repaired me, but I couldn't use my modules. He tried to reset my module, but nothing happened. He then tried to deconstruct me, but I only had an endoskeleton appear where I was. If he attempted the procedure again elsewhere, the endoskeleton would teleport to that location. I was boneless. I could not use modules, interact with computers, or anything. The admin online, Generic-DM, did not know of a fix.

**Comment by Altoids1** [comment]
B O N E L E S S borgs

Yeah, okay, I'll see what I can do.

**Comment by adamsong** [comment]
Unable to reproduce
