### ISSUE TITLE
The recipe for Sodium Chloride is wrong. It results into Lye.

### ISSUE THREAD

**Issue by 13gome0220** [yogstation13/yogstation#577]
The recipe on the wiki says: Sodium, Chlorine, Water. But it results into Lye.
Adam couldn't find the real recipe for Sodium Chloride in the code.

**Comment by drderp3635** [comment]
Thats wierd because thats niether of the listed lye recipes either

**Comment by Super3222** [comment]
https://github.com/yogstation13/yogstation/blob/9ca634e7a20196faa263bda7fc5a35f687adab92/code/modules/reagents/chemistry/recipes/others.dm#L504

Lye results from sodium, oxygen, hydrogen.

I'm guessing there was a bit of oxygen inside of the beaker that you didn't know about?

**Comment by FluffySurvivor** [comment]
>Adam couldn't find the real recipe for Sodium Chloride in the code.

he should've looked at himself :^)

**Comment by ParagonPrime** [comment]
Super, I dunno exactly how the chemistry code works (read: I do not know how _any_ of the code works) but is it possible the water somehow gets translated down into oxygen and hydrogen and then that makes the Lye?

**Comment by Super3222** [comment]
Eh, chemistry (in the game) isn't exactly built that way. Water is literally its own reagent.

**Comment by ParagonPrime** [comment]
I know, but I had to make sure.

**Comment by EMT321** [comment]
@Cruix Can this be closed?
