### ISSUE TITLE
We are missing clock cult bans.

### ISSUE THREAD

**Issue by SeikoTheSeal** [yogstation13/yogstation#579]
Try to ban self from clock cult. There is no option. Cry.

**Comment by Robertruler77** [comment]
THERE IS NO ESCAPE.
TRY TO BAN YOURSELF?
ITS LIKE YOU DEVELOPED A FEAR OF CULTS
BUT ITS STILL HERE!
ITS CAN NEVER GO AWA-

Okay, I'll stop with the reference now.

**Comment by Super3222** [comment]
Should be in my clockwork rebase, I saw it. #588

**Comment by AsV9** [comment]
Checking the files it appears that the jobbans have been added.
Please correct if I'm wrong.
