### ISSUE TITLE
Hand teleporter portal bug #2

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#580]
[This issue](https://github.com/yogstation13/yogstation/issues/348) was closed earlier but at Server time 2016-08-16 18:00, after I noticed the everlasting portals again and asked 20thgirl about one of them which stayed on the central hallway for more than 30 minutes while it spaced everyone running into it, she deleted them as bugs. Issue is reported here.

**Comment by timkoster1** [comment]
I saw this as well. It wasn't respawning, I thought it was some weird feature

**Comment by timkoster1** [comment]
Reproduced.

All hand-tele port teleports that use the current teleporters location, are permanent.
This can be stacked to fill a whole room with them.

I will be throwing up a PR soon

**Comment by 00aquir** [comment]
In round 9436, hand tele portal was not closing, admin intervention was necessary.
