### ISSUE TITLE
Catsplosion

### ISSUE THREAD

**Issue by Yackitori** [yogstation13/yogstation#583]
The cats in the CMO office are worse than rabbits. They reproduce faster too.

**Comment by SeikoTheSeal** [comment]
Feature.

**Comment by ShadowDeath6** [comment]
remove runtime being able to spawn more cats at roundstart, server has been getting lagspikes

**Comment by ParagonPrime** [comment]
FEATURE

**Comment by ParagonPrime** [comment]
inb4 rev round where cats block spears and lasers of intruding revs allowing CMO to escape
