### ISSUE TITLE
Feature Freeze

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation#584]
We have over 100 current issues on github, Most of which are actual bugs and need fixing. Please help by fixing these.
No new feature PR's will be accepted and we wont be merging /TG/'s updates until they are fixed.

**Comment by oisin100** [comment]
Update:  Donor Features And Map Changes will be allowed

**Comment by Super3222** [comment]
Or implement a 2 for 1 merge token system for a month.

**Comment by killerx09** [comment]
A lot of them are balance requests though, rather than actual bugs.

**Comment by timkoster1** [comment]
I checked, and there are 19 commits tagged as bugs that are actual bugs or not already fixed.
And only 1 is notable, being the apostrophe bug

**Comment by Groxic** [comment]
If you filter the search to show only issues with the bug tag, there are currently 41 open.

**Comment by timkoster1** [comment]
Most of them aren't even bugs, just annoying strings of codes, while others just can't be replicated and weren't a problem in the first place.

**Comment by Cruix** [comment]
Feature freeze is over.
