### ISSUE TITLE
Outgoing mhelps from other mentors still have poor contrast

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5851]
https://github.com/yogstation13/Yogstation-TG/pull/5648 fixed most things but outgoing mhelps from other mentors are still that wretched old color/contrast. After this everything should be perfect, thanks for the previous fixes.

![image](https://user-images.githubusercontent.com/36208065/59473795-f48d4d00-8e11-11e9-8aff-777a4b7da233.png)

**Comment by MegaEmpirical** [comment]
As an aside, if personal outgoing and incoming mhelps were made to be a different color from common (even if only slightly), that would be fantastic.

**Comment by jcatjmeow** [comment]
No longer an issue
