### ISSUE TITLE
Sleepers not working

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5852]
I have no fucking idea why or what is wrong with them again. Everyone keeps saying they're broke and no one has been putting a git issue even though I keep telling them. I have not been in-game to find out how yet. I'll comment whenever I find out.

**Comment by 00aquir** [comment]
https://github.com/yogstation13/Yogstation-TG/issues/5651

**Comment by MegaEmpirical** [comment]
I'm aware, I made and confirmed that issue but I'm still getting a constant stream of comments about sleepers being broke in mhelps and msay.

**Comment by MegaEmpirical** [comment]
I have confirmed that they're non-responsive save for the open and close button.
