### ISSUE TITLE
AI turrets stun through reinforced windows.

### ISSUE THREAD

**Issue by aaqe** [yogstation13/Yogstation#5863]
## Reproduction:
WIndows were intact and windoor was closed.

42[15:34:00] Qe/(Deep Blood) (AI Chamber (119, 137, 2))
has been shot by the turret with the electrode

**Comment by MegaEmpirical** [comment]
They work within one tile of the window's exterior, were you within one tile?

**Comment by HomocidlePancakes** [comment]
All projectiles do

**Comment by aaqe** [comment]
I could have sworn tasers didn't go through windows. Did that change recently?

**Comment by MegaEmpirical** [comment]
Lasers always did. Teasers only affect up to one block past it (I think this has always been so, you just don't see it mattering often or people trying).

Pancakes suggests bullets alwusb) also hit up to one block but I wasn't aware of that.
