### ISSUE TITLE
Appendix surgery can't be started with headset on ear?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#587]
Apparently that was the reason why doctors couldn't start the surgery.

**Comment by timkoster1** [comment]
I've done the surgery plenty of times, and that never happened.

>Doctors
Most likely they were retarted

**Comment by 00aquir** [comment]
first I thought the same. but not even CMO could start the surgery, then I took off everything (not just jumpsuit) then they could do it. And I had barely anything on my head, maybe gloves too, was not entirely sure why they couldn't do it for other reason than some items blocking surgery...

**Comment by timkoster1** [comment]
Could not reproduce.

**Comment by Super3222** [comment]
They probably weren't on help intent, or you already had a surgery going and it needs to be finished @00aquir
