### ISSUE TITLE
Split personality bug

### ISSUE THREAD

**Issue by sam0oneau** [yogstation13/Yogstation#5889]
Round ID: 23732

## Reproduction:

Became split personality to an antag. The antag then wanted to have his mutations healed. Genetics decided to kill him and clone him to best deal with his issues. When cloned I was the only personality left and I was not antag even though my vessel was intially and had an unlocked pda on syndie network. Admins told me this wasn't intended and to report bug here!
![Untitled234343](https://user-images.githubusercontent.com/30634117/59557642-88a81180-8fd6-11e9-8178-47d996bfe136.png)

**Comment by MegaEmpirical** [comment]
You were the active personality when killed, I'd say keep it and call it a feature.

Especially since it's easily cured. No idea why they killed you. mannitol and or brain surgery should have resolved it.

**Comment by HomocidlePancakes** [comment]
1)Intended
2)The OG personality was still clonable, you just needed to scan the body again to have him revived

**Comment by MegaEmpirical** [comment]
I was wondering if that was doable, that's cool.

**Comment by redmoogle** [comment]
Why was this never closed

**Comment by sam0oneau** [comment]
My Disappointment Is Immeasurable And My Day Is Ruined @redmoogle

**Comment by redmoogle** [comment]
wait fuck did I close the wrong issue _No_

scared me for a second, was thinking of another issue

**Comment by MegaEmpirical** [comment]
No idea but this seems fine to close.

**Comment by sam0oneau** [comment]
Nah it's chill, I'm just mugging you off.
