### ISSUE TITLE
Free miner ripley not space proof

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5901]
Due to a Ripley change from TG, https://github.com/tgstation/tgstation/pull/42828, standard Ripleys are not loner space worthy and need an upgrade. Also, the box of supplies provided for to build a Ripley provide an old unneeded resource (plasteel) and lack a new needed one (10 rods).

**Comment by HomocidlePancakes** [comment]
Good thing you get a spacesuit eh?

**Comment by Lostlarry** [comment]
its Ripley mk. I that one was never space proof

**Comment by MegaEmpirical** [comment]
There are four people on that ship. Two bars suits for the miners, one Ripley for the engi, and I'm unsure of the captain gets one and so without the Ripley being space worthy that means someone else has to give up their suit.

Lostlarry, that is true but that's only true since MK I and II were added. This is a recent addition, there use to be only one Ripley that was space proof.

**Comment by Hopekz** [comment]
This has been fixed in the past. Please close this issue.
Thank you!

**Comment by MegaEmpirical** [comment]
Word is it's fixed. Closing.
