### ISSUE TITLE
There's a line of pixels on berets which are skin coloured, rather than being covered by hair/anything else

### ISSUE THREAD

**Issue by tsaoToast** [yogstation13/Yogstation#591]
![a83c74a6f2d89f3185769ff48a3efe56](https://user-images.githubusercontent.com/26847493/39409533-c68208d4-4be0-11e8-8e92-f97118c6d7e7.png)

![fc0e2f8e93a055d8711c2af07567fb18](https://user-images.githubusercontent.com/26847493/39409516-960652fa-4be0-11e8-9106-1eb95a75b803.png)

![fc5c20675342527d77cc26434ce2280f](https://user-images.githubusercontent.com/26847493/39409517-9888dce6-4be0-11e8-8b31-ee5bcc6522e4.png)

which mugs me off to no fuckin' end. This wasn't present before the rebase, which makes me thing it's something to do with how /tg/ drew them. Isn't there on the right due to the hat slant

**Comment by Partheo** [comment]
Just tested with the red beret. No issue on my end.
![image](https://user-images.githubusercontent.com/10659549/39444275-2a9525fa-4c85-11e8-95d9-a06ee239b922.png)

Tried with the same hairstyle, still nothing.
![image](https://user-images.githubusercontent.com/10659549/39444587-4c445422-4c86-11e8-9706-7f16b5b766a7.png)

There's nothing wrong with the DMI either, so I don't know what could be causing this issue. Needs more testing.
![image](https://user-images.githubusercontent.com/10659549/39444605-5e4e442a-4c86-11e8-81e7-55f5f2967bc6.png)

**Comment by GrayRachnid** [comment]
Officer beret seems to have this issue, try the collectable red beret.

**Comment by Bawhoppen** [comment]
Hair styles are split into a top and bottom nowadays, so that way afros and stuff won't stick throw hats. This is an issue with that (I think).
