### ISSUE TITLE
Some minerals have no sprite

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/Yogstation#593]

**Comment by Amelia0010** [comment]
wow 👏 so descriptive 👏

**Comment by GrayRachnid** [comment]
![image](https://user-images.githubusercontent.com/6613514/39411443-39c332f4-4bd8-11e8-9f73-ff311c6dd4eb.png)

**Comment by GrayRachnid** [comment]
Nevermind it's a /tg/ bug. https://github.com/tgstation/tgstation/pull/37564
