### ISSUE TITLE
When clicking on the mop bucket with a mop it cleans the floor

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5951]
It also actually wets the mop too but it's strange that it begins cleaning the floor, especially if you don't need to clean that tile which is usually the case with where you keep your bucket.

**Comment by monster860** [comment]
I cannot confirm this issue. I have tried it with mopbucket, janicart, a regular bucket, and it works fine.

**Comment by MegaEmpirical** [comment]
I just tested this, I am guess it's fixed. I know some changes occurred to the mop bucket since this was posted. Thanks for trying though.
