### ISSUE TITLE
Sometimes the job preference window reverts to the simplified version without Yog specific jobs

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5979]
Happens on Yogbox and I am unsure of any pattern involving it. I have only ever seen it during round ready up and it persists through.

**Comment by adamsong** [comment]
Is this issue still happening?

**Comment by MegaEmpirical** [comment]
Honestly I've not seen it in some time but I've been less active. If you've not seen it with how active you are then I'll assume not and close jt.
