### ISSUE TITLE
Chefs can no longer use Close Quarters Cooking in bar area.

### ISSUE THREAD

**Issue by CarkTakier** [yogstation13/Yogstation#5980]
Y'know how chefs used to be able to use their CQC in both the kitchen and the bar? Well that no longer works.  Theos thinks it's due to the random bar gen, and thats been my thought on it for a long time aswell.

Reproduction: Attempt to use CQC in the bar area. Fail because mappers broke it.

**Comment by MegaEmpirical** [comment]
Which bar was it? It might not be an issue for all bars.

**Comment by CarkTakier** [comment]
When I made this report, it was for the Diner bar.  But I've mained chef for long periods of times and it seems to not work in all of them.  It might still work in the original bar layout, however.

**Comment by Ktlwjec1** [comment]
Not a bug, only intended to work in the kitchen (/area/crew_quarters/kitchen).
