### ISSUE TITLE
Cloning creating catatonic clones

### ISSUE THREAD

**Issue by Shaggyslav** [yogstation13/Yogstation#5981]
Issue reported from  Round ID: 23820 (Yogstation 13)

Reporting client version: 512.1454

Hello, so today the cloning got kinda screwed up. Every time someone got cloned it popped out a catatonic clone. The soul did not transfer. One shift we had it on autoprocess and when I came back we had like 6 catatonic clones of the guy there

**Comment by MegaEmpirical** [comment]
Popping out brains also fails to associate the ghost to the brain.

**Comment by SomeguyManperson** [comment]
I think this has been fixed recently, correct me if I'm wrong
