### ISSUE TITLE
Simplifying OOC tags

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation#599]
Admin Observer -> [AO] fine

Moderator -> [M]
Moderator level 2 -> [M+]
Moderator with any restrictions -> [M-]

Administrator -> [A]
Administrator with any restrictions -> [A-]
Primary Administrators -> [PA]
Senior Administrators -> [SA]

Retired Admin -> [RA]
Council -> [Council]

(yes i know, it isn't simplified. but this rank means a lot & C is already taken ¯\_(ツ)_/¯ )

Coder -> [C]
Senior Coder -> [SC]
Head Coder -> [HC]

Donator -> [D]

**Comment by ShadowDeath6** [comment]
why would admin observer not be AO

**Comment by Super3222** [comment]
I was thinking players would be misguided and think up names for the O instead of observer.

**Comment by ShadowDeath6** [comment]
they'll probably think of something else as the O
