### ISSUE TITLE
Omegastation Refurbish

### ISSUE THREAD

**Issue by Altoids1** [yogstation13/Yogstation#6034]
![image](https://user-images.githubusercontent.com/29939414/59969624-af56d280-9517-11e9-8b42-b8b4fa393789.png)
## Brief Description
We'll pay for you to make a Yogs revival of Omegastation. We don't have any great options for lowpop maps, so a revival of this one sounds lovely.

## Requirements
- A working revision of Omegastation
- Properly-randomized maintenance
- A fix to the SM potentially leaking radiation into Central Primary
- NTSL-compatible telecomms
- Any other additional minor modifications we may request during PR review and testmerging.

# Bounty: $10
Here's the document describing our process for bounties: https://docs.google.com/document/d/1OCbPb5ccQm8GiSVvnMuzCjWKT9dZV8wdGtvHowoeDd0/edit?usp=sharing

If you are interested, please DM me or a host so we know who is working on it.

**Comment by MegaEmpirical** [comment]
Likely needs lathes for the departments.

And likely an ore silo and a bank machine (or whatever it's called that stores all the monies).

**Comment by Altoids1** [comment]
https://github.com/tgstation/tgstation/pull/40352/files

Here's a copy of some of the relevant files (including the map file), as what Omega looked like right before it was removed by /TG/.

There ought to also be a Yogs version of the station available on the old Yogs repo.
