### ISSUE TITLE
Walking hotkey is not an option.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/Yogstation#604]
It should be, IIRC it's "alt".

**Comment by Amelia0010** [comment]
due to alt being used for stuff like alt+clicking lockers and such, assigning it as a rebindable hotkey is a very bad idea, unless you're fine with alt not being able to be used.

**Comment by GrayRachnid** [comment]
It's not alt that I want, I'd like to have the ability to walk as a hotkey, which is what tg has.

**Comment by Amelia0010** [comment]
so having walk as a hotkey is **alt** that you want?

**Comment by GrayRachnid** [comment]
yes and shitty pun

**Comment by Amelia0010** [comment]
thanks, i'm here all day 🙇
