### ISSUE TITLE
Donor feature to select which pet you get as a head

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6050]
There seemed to be some interest in this after it was discussed:

Making head pets a donator selection (example, QM could get sloth or the fox. HoS the spider or Kreb (Kreb is currently at the arrivals office)) (via a drop pod, to avoid the issue of the map loading first and if the role isn't filled, default drop pod the default animal). My idea was that each head has their own selection rather than all pulling from the same pool or maybe each head can select from a pool that includes generic and job specific options per job. 

Two things to consider with this:

1) Make the spider for HoS the default (my understanding is that it is robust enough to kill a meh HoS). This is to make it so any donator selection is purely a nerf/cosmetic.

2) We may need a few additional pets added so that there are options for certain heads. Though this can take a back seat. A personal recommendation: Guinea pig for the CMO.

**Comment by Altoids1** [comment]
Making the pet appear roundstart wouldn't be that hard; the droppod stuff oughtn't be necessary.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
