### ISSUE TITLE
Free Miner Ripley wreck is broken

### ISSUE THREAD

**Issue by Sun-Soaked** [yogstation13/Yogstation#6059]
## Round ID:
Can be replicated in any round containing free miners.

## Reproduction:
The Free Miners get a ripley by refurbishing an old wreck. The removal of wires via wirecutter and circuits via screwdriver are still functional, but as of the recent Free Miner shuttle revamp, the wreck no longer drops the mech's limbs when welded, which was a vital step to completing the mech. This completely breaks the  ripley construction process, and no free miners will be able to construct their mech without admin intervention until this issue is fixed.

**Comment by ynot01** [comment]
worked for me last round
try welding it before you cut the infinite amount of cable coils off of it
