### ISSUE TITLE
Make miners' lives slightly better

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation#606]
I've seen a few cases where colossuses spawn right outside the mining station- and by right outside, I mean, you walk out of the mining shuttle to suddenly hear _**JUDGEMENT**_ booming from outside and having the walls torn down by death bolts. Naturally, the miners all get fucking murdered.

A lot of people are quite against making Lavaland hugbox. So am I, now, after having gotten gud. But I don't think it's fair for anybody when there's a megafauna that spawns right outside the station and fucks you- or, for that matter, a goliath depressurizing the shuttle as soon as you arrive.

Set a spawn restriction on lavaland mobs for some reasonable radius outside the mining station. It might be funny to see a miner go twenty paces before running into an ash drake, but it's not funny when you're opening the airlock from the shuttle and you suddenly see a pentagram appear.

**Comment by FluffySurvivor** [comment]
sounds like lots of fun

**Comment by SeikoTheSeal** [comment]
>sounds like lots of fun

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/306

mac used to code I think

**Comment by Super3222** [comment]
> mac used to code I think
