### ISSUE TITLE
Constant eye damage without reason

### ISSUE THREAD

**Issue by Nostr0** [yogstation13/Yogstation#6082]
Issue reported from  Round ID: 23907 (Yogstation 13)

Reporting client version: 512.1471

Multiple players got constant eye damage without any reason.
Occuline helped at most for a few minutes until it returned. Unknown what caused this, no addictions. no chemicals. Just severe cellular damage.

**Comment by MegaEmpirical** [comment]
Was there a sentient disease?

Did anyone confirm that there wasn't a nasty hidden disease?

**Comment by Ludox235** [comment]
If it said "Your eyes burn horrifically!" it means it was a disease

**Comment by Nostr0** [comment]
I was a paramedic, I asked these people about it and they just said they can't see.
