### ISSUE TITLE
Lavaland gas station Shop Diplay Case dissapears when item is put inside.

### ISSUE THREAD

**Issue by Nostr0** [yogstation13/Yogstation#6087]
Issue reported from  Round ID: 23909 (Yogstation 13)

Reporting client version: 512.1471

After unlocking I've put a hot donk pocket inside the display case and it disappeared with the item inside. Both is probably still there but just invisible.

Update: After a relog its visible again and works.

**Comment by adamsong** [comment]
Unable to reproduce
