### ISSUE TITLE
Free Miner Ship Controlled by Escape shuttle.

### ISSUE THREAD

**Issue by Nostr0** [yogstation13/Yogstation#6094]
Issue reported from  Round ID: 23928 (Yogstation 13)

Reporting client version: 512.1471

The Free miner ship begins to fly itself when the shuttle departs from the main-station.

**Comment by MegaEmpirical** [comment]
That's not a bug, all ships are suposed to leave the station during evac. The one exception is mining.

**Comment by Nostr0** [comment]
But the free miner ship is not connected to anything that the station does so why would it?

**Comment by MegaEmpirical** [comment]
Because that's how round end works so that people can escape/complete objectives.

**Comment by Nostr0** [comment]
I guess that makes sense
