### ISSUE TITLE
Cargos export system is broken.

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#610]
There are three ways (that I know of) to farm cargo points.
1.Mining: Due to the high price of plasma mining for 15 mins as qm is enough to get a absurd amount of points.
2. Corgi farming: If you get Ian and order enough corgi crates to get Lisa you can breed corgis at a really high rate in the cargo warehouse slaughtering the puppies for there hides. with a supply console set to broad you can set to broad (contraband) you can export corgi hides at 2500 a piece the yields about 25000-35000ish per 15mins.
3.Money trees: you can grow 5000 dollar bills at absurd rates and quantity's which exports for full price. I ordered a shuttle **completely full** of laser crates on blob with this method.

**Comment by SeikoTheSeal** [comment]
>3.Money trees: you can grow 5000 dollar bills at absurd rates and quantity's which exports for full price. I ordered a shuttle completely full of laser crates on blob with this method.

Hey it took me a while to peel those lemons.

**Comment by AdamElTablawy** [comment]
i think it's fine if you go to all that effort

no other department has limits like cargo does that shits all over their ability to do anything

**Comment by SeikoTheSeal** [comment]
>i think it's fine if you go to all that effort

All that effort :laughing:

**Comment by killerx09** [comment]
1 is kinda a problem, 2 is fine since you have to steal Ian from the HoP, 3 probably needs the /tg/ patch.

**Comment by Silk-Touch** [comment]
I have done two like ten times each time I just asked for Ian I have not been refused once.
