### ISSUE TITLE
Very Minor pAI bug

### ISSUE THREAD

**Issue by Sir-Lagsalot** [yogstation13/Yogstation#6101]
Issue reported from  Round ID: 23936 (Yogstation 13)

Reporting client version: 512.1467

When a pAI tablet is in someone's pocket, any pictures it tries to take will show up as black, which, of course, makes sense. However, when a pAI is in a holochassis form that allows it to be worn as an article of clothing, such as the cat or repair drone forms, and is being worn, it is treated as though it is inside a bag, and any photos will show up as blank. It's a very minor issue, but it caused a lot of problems with my journalist pAI character.

**Comment by ReddicusDragon** [comment]
Solved at an indeterminate time, confirmed to no longer be an issue.
