### ISSUE TITLE
Marrow weavers are unfun and unrewarding to fight

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation#611]
1. The chitin they drop is worthless on it's own, and relies on asswalkers spawning to get the other half of the crafting materials for the armour

2. Their venom is annoying as shit, two bites can last upwards of 10 minutes of blurry vision and over 20  brute damage from the histamine itching, even worse if you get hit more than twice.

3. Their web is also annoying as shit and provides no bonus to them as they charge at you out of their web. All they do is slow your progress forwards as you're forced to clear the web away (which takes forever) or take another path

4. They have no unique attack apart from their venom bite. All you do is kite, making them boring to fight.

5. Their death description is perhaps the most unnecessarily flowery thing I've ever read.

**Comment by AdamElTablawy** [comment]
marrow weiners

**Comment by X-TheDark** [comment]
You should have seen them before I made them as slow as regular fat spiders (they were twice as fast in the original PR).

**Comment by Super3222** [comment]
@Stealthkibbler

**Comment by darkwahn** [comment]
Yeah, they seem pretty pointless as they are now. Maybe if miners could actually use them for something other than the absolutely absurd amount of bones they have behind they'd be a little better. 

It'd be silly, but maybe you could build some sort of a web launcher from their parts?

I don't really find the web too much of an issue personally, as it has yet to cause me any problems.

**Comment by Super3222** [comment]
Yes yes, it seems like weavers are pretty shit right now.

My suggestion is this:
- Make them tangible to thrown weapons, unlike legions, goliaths, and watchers. Diversity!
- Make their marrow weavers universal in construction, rather then only being apart of ashwalker trade. This means more craftable weapons and tools.
- Slow them down a bit, but faster then watcher speed. They get their usual speed (what they have now) when on top of web tiles. They become extremely slow on top of lava.
- Make them spin webs at the tile under the target (so it doesn't follow the target). this web will grapple them, and act as a handcuff. It takes 5 seconds to get out of.
- Make marrow weavers run off potential higher, the less their health is.
- Lower the rate of web production and, make it so they don't usually leave their spawn location
- Make special weapons (axe, survival knife, bone dagger, and butcher knife) slice through webs with a `do_after()` of 5 seconds

This will prompt miners to be more careful around weavers and, not disturb their nests. Removing them is a bad decision @whoeverearliersaidtodeletethembutdeletedtheirmessage. They have potential to be fun, and challenging.

Also a rework for watchers need to happen. They are the easiest creatures to fight currently and, dropped immensely in quality. If you played the game, you'd maybe understand this.

- Make watcher's bolamine have a probability based on the amount of bolamine inside of them to secrete "super bolamine". It will NOT produce more super bolamine, if there's already an exisit supplement in the target
- Super bolamine makes them do one of these possible features: puke at least once, dose them in ethanol, make them super dizzy, cause or cause eye irritation. All stuff that's too harmful but, leads for a good distraction so a watcher can get close enough and take you out.
- Upon that instant, bolamine will secrete 10-18u of super bolamine and, every 5th cycle, it will cause one of those effects. Upon the fifth cycle it will also execute half of the current units within the occupant. The deign probably needs tweaking.

The idea is to make watchers harder to hit. Goliaths, you watch out for the tendrils. Legions, pop the heads and run for the creature. Watchers use to be simply attack from a distance but, they still managed to pull off some damage miners had to look out for. 

No but seriously, if you play the game right now, watchers are easy as cheese to beat.

**Comment by darkwahn** [comment]
I agree that watchers need to have at least something done, they're free diamonds right now.

I like your idea because it doesn't put them in the level of guaranteed damage like they used to be, but also makes them a threat.

**Comment by Stealthkibbler** [comment]
@Super3222 implying I knew how to code any of this, it's a miracle that it even works and doesnt break anything.

**Comment by EMT321** [comment]
@Cruix has this been resolved adequately by the listed merges? Can it be closed?

**Comment by X-TheDark** [comment]
The Weavers should be much more manageable now.
