### ISSUE TITLE
Burning Plasmamen don't consume oxygen

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6119]
Whilst being on fire, no oxygen is consumed and if there's so much as 1 mol in the air, plasmamen just keep on burning and burning. As I found out when the remaining one mol of oxygen wouldn't go away but it was low enough for the ensuing plasma fire to burn out. 

https://cdn.discordapp.com/attachments/385278833575723010/517403444622131212/unknown.png

**Comment by MegaEmpirical** [comment]
Similarly, bodies that are burning in space continue to burn even through there is no oxygen to fuel the fire.

**Comment by redmoogle** [comment]
This isnt a bug _believe it or not_ it's just that you could very easily grief with it, so it doesnt consume o2. as for the corpse burning, uhhhhh thats a bit whacky but last time I checked they dont do that anymore?
