### ISSUE TITLE
Body temperature of thralls says it's dangerously low regardless of actual temperature

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6130]
![image](https://user-images.githubusercontent.com/36208065/60318680-f4c53680-9941-11e9-8ce3-7f026fcb866b.png)

Body that is on fire, still dangerously low some how.

Additionally, even if you're a plasmaman it will say your temperature is dangerously low but plasmamen are immune to the cold so it doesn't matter.

**Comment by Sun-Soaked** [comment]
This isn't a bug, this is actually how thralls are detected. Anomalously low body temperature, regardless of environment. Someone should patch in something that extinguishes them if set on fire and reveals their thrall status. (Protip: a tried and true strategy to causing chaos during sling rounds is to slightly modify the temp of the atmos air mix, making it bring people's body temp down.)

**Comment by CarkTakier** [comment]
I'm not sure if memed clarified this is plausible.  It should be defined based on actual body temp, that way sabatoge through fevers/atmos makes it real good

**Comment by MegaEmpirical** [comment]
I have no idea what the point is that you're trying to make Meme. A body temperature over 73,000 C is not dangerously low.

**Comment by SomeguyManperson** [comment]
No longer an issue since thrall detection now works off of eyes
