### ISSUE TITLE
Lone Operative Shotgun explodes on first shot.

### ISSUE THREAD

**Issue by Nostr0** [yogstation13/Yogstation#6134]
Issue reported from  Round ID: 23963 (Yogstation 13)

Reporting client version: 512.1471

When shooting at a borg my gun immediately exploded and did almost crit me.

Ghost saw it as well.

It went like this: 
Unknown fires the Bulldog Shotgun! (I shot)
Artemis fires the cyborg disabler! (Borg shot)
Your armor softens the blow! (Exploded)

**Comment by MegaEmpirical** [comment]
Were you firing at point blank?

**Comment by Nostr0** [comment]
No, like 3 "blocks" away. Does this count as point blank?

**Comment by HomocidlePancakes** [comment]
Fairly certain you had a grenade/c4/bomb on you and it blew due to EMP/getting shot/proximity explosion. There is no reason for a gun to explode
