### ISSUE TITLE
let ascendants target their own thralls with their abilities and give lightning storm no cooldown

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#614]
the above for murderbone and lore reasons

**Comment by timkoster1** [comment]
Oh god no

**Comment by X-TheDark** [comment]
Nah, why bother admins with dozens of possible "Thrall : ASCENDANT DED'ed ME, PLS BAN" just for the sake of letting ascendants being shitters.

**Comment by AdamElTablawy** [comment]
they used to be able to do this though

**Comment by ParagonPrime** [comment]
ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

what's the point of murdering people 4noraisins if they're already thralled

that's really just feeding raging murderboners, which we really don't want to encourage for almost all of the gamemodes of ss13

**Comment by Robertruler77** [comment]
Fuck. That.

Nice Acsendents, they value their pawns. Less tickets, less end-round fuss. Everyone wins!

**Comment by Super3222** [comment]
on one hand, ascendants never really cared about their slaves.
on the other hand, end-round fuss & salt

**Comment by ShadowDeath6** [comment]
>be thrall
help shadowlings a fuckton, win favor of one of them
another one blows you up

shit issue PR please remove adam from repo
