### ISSUE TITLE
Preternis cannot be gibbed and breaks the gibber

### ISSUE THREAD

**Issue by alexkar598** [yogstation13/Yogstation#6175]
they dunt have a meat var defined in their species datum and it breaks the gibber by locking it up

**Comment by Sun-Soaked** [comment]
suggestion: make the gibber spew oil and robot gibs alongside a series of possible synthetic organs.

**Comment by ynot01** [comment]
feels like an unintended feature tbh they's a robot man you gonna damage the gibber's parts with that shit

**Comment by alexkar598** [comment]
No it's a bug because I didn't know not setting the meat var would break shit
