### ISSUE TITLE
Code response visible in player name

### ISSUE THREAD

**Issue by Nostr0** [yogstation13/Yogstation#6191]
Every traitor could see that my name was red and that I was a traitor

One of the code responses was "Hard"

![Unbenan234nt](https://user-images.githubusercontent.com/10816516/60467559-35c98d80-9c57-11e9-9eaa-b97164ffbc64.PNG)
Issue reported from  Round ID: 24032 (Yogstation 13)

Reporting client version: 512.1471

**Comment by oklews** [comment]
Not a bug this is definitely a feature, I love it too much to want it removed

**Comment by adamsong** [comment]
The name highlighting just applies to names as well, this does not indicate the traitor status of the person whose name it highlights.
