### ISSUE TITLE
airlock consoles lock up when you open both internal/external airlocks at once

### ISSUE THREAD

**Issue by Tummywumbes** [yogstation13/Yogstation#6224]
## Reproduction: go up to an airlock console and click on both the internal and external airlock buttons. the status will then indefinitely state: "chamber depressuring, cycling to exterior airlock"

![image](https://user-images.githubusercontent.com/34947832/60632899-14db7680-9dd6-11e9-9e22-7b911f84ca1f.png)

**Comment by 00aquir** [comment]
connected to https://github.com/yogstation13/Yogstation-TG/issues/5710

**Comment by adamsong** [comment]
Unable to reproduce, airlock interface seems to have been updated since this issue was created.
