### ISSUE TITLE
Hair on Ghost (floorlength bedhead) is not displayed correctly

### ISSUE THREAD

**Issue by ghost** [yogstation13/Yogstation#6228]
The hair that shows on your ghost after you die displays incorrectly (missing bottom of "Front"). The hair displays correctly on left, right, and back, however front has a single line of pixels in the center.
Image included below 
![image](https://user-images.githubusercontent.com/50187357/60640493-43f4e680-9ddc-11e9-99b3-6ffe8b66c16e.png)
![image](https://user-images.githubusercontent.com/50187357/60640499-4e16e500-9ddc-11e9-92d4-c5006349501d.png)

Issue reported from  Round ID: 24074 (Yogstation 13)

Reporting client version: 512.1472

**Comment by nesisknesis** [comment]
As far as I know, this won't be able to be fixed as those missing pixels are so that the hair does not clip above the human mob sprite. It would require a separate sprite for ghosts which seems un-necessary seeing how minor this is.

**Comment by ghost** [comment]
Oh, I see. That makes sense to me. Thanks for the info.
