### ISSUE TITLE
[Feature request] Clown-crafting

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation#628]
Just a few shitty ideas I had involving clown items and crafting stuff. 
1. Lound bike horn: Bike horn + duct tape + mimana + clown megaphone (and/or airhorn)

Basically a bike horn but louder. Requires cooperation with botany to obtain, not too difficult but not too easy.
1. Super-slip banana peel: Banana peel + 100u space lube + 50u plasma

A banana peel with all of the effects of space lube and stuns for longer. Requires chemistry to actually give the clown space lube as well as for the clown to find 50u of plasma somewhere, so this usually will not be made by anything but the most charming of honkers.
1. Handheld HoNkER BlAsT 5000: bike horn + rubber duck + emag + HoS megaphone + duct tape

A handheld version of the mech equipment with all of the same effects. It's basically a traitor item, due to emag. Requires the clown to somehow get the HoS megaphone, meaning being in security for at least 5 seconds as a clown without dying.

Now tell me how shitty my ideas are, honk.

**Comment by ShadowDeath6** [comment]
traitor clown with earmuffs and an emag gets a meme flashbang that KOes people

**Comment by Kmc2000** [comment]
Oh god why
