### ISSUE TITLE
Missing sprite

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#6281]
Some sprites are missing.
One example is "assistant's formal uniform" that makes people look naked.

**Comment by nesisknesis** [comment]
what would be nice is if we knew what sprites these are. we arent omniscient

**Comment by 00aquir** [comment]
I don't really know, I just remembered when people had clothes yet looked naked. Probably the rare types of jumpsuits.

**Comment by 00aquir** [comment]
I don't really know, I just remembered when people had clothes yet they looked naked.

**Comment by Potototatoh** [comment]
things such as the security jumpskirt and camo fatigues do this

**Comment by nesisknesis** [comment]
Tested these clothing on a test server and they're not broken. Must be another issue unrelated to sprites.

**Comment by Potototatoh** [comment]
might be a species related thing then because it just seemingly randomly happens on rounds and is generally persistent
