### ISSUE TITLE
Red slime speed potion doesn't work

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#6286]
the item is supposed to remove slowdown from clothing that gives you slowdown

## Reproduction:

inject a red slime extract with water

attempt to use the resulting potion on a piece of clothing that normally gives you slowdown (hardsuit, eva suit)

acknowledge that it refuses to work

**Comment by oklews** [comment]
Not a bug it decided fun was bad and we as a whole deleted any utility out of red slime potion

**Comment by JamieD1** [comment]
Nerfed in #4149
