### ISSUE TITLE
Can no longer apply drying agent to galoshes via rag

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6292]
I used to apply drying agent to rags and then wash the boots with them and then I would get the fancier galoshes but now it doesn't work and to the best of my knowledge there is no other way.

**Comment by GenericDM** [comment]
Spray bottles should work.

**Comment by MegaEmpirical** [comment]
Glad to know there is a potential alternative at least, I'll try that next time.

**Comment by adamsong** [comment]
Is this a bug or intended behavior?

**Comment by MegaEmpirical** [comment]
> Is this a bug or intended behavior?

Yes. No.
