### ISSUE TITLE
Make pAI playtime be tracked.

### ISSUE THREAD

**Issue by nesisknesis** [yogstation13/Yogstation#6294]
would be cool i guess

**Comment by Sir-Lagsalot** [comment]
pAI is one of my most played roles so it's kind of sad I can't tell how long I've played it for :(

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
