### ISSUE TITLE
Blob Core can be hidden under AI core.

### ISSUE THREAD

**Issue by azzzertyy** [yogstation13/Yogstation#6295]
Blob can make a blob thing in the ai core and then relocate to it, making it inside the ai core.  
![image](https://user-images.githubusercontent.com/42524344/60933910-4663ae80-a2bc-11e9-98dc-e3608b0728bf.png)
Becomes almost impossible to kill, must alt click to kill it. Bullets will be hit only by AI core.

**Comment by redmoogle** [comment]
Blobs are set to be below the mob layer

**Comment by adamsong** [comment]
It appears that blobs can no longer be located under the AI core at all, therefore making it impossible to place the core there
