### ISSUE TITLE
Make headphones more then just style

### ISSUE THREAD

**Issue by oklews** [yogstation13/Yogstation#6302]
In my eyes, headphones should be a tool to use, like to make noises quieter, or to actually play music to yourself.

Currently all they are good for is making you look like a hipster DJ.

**Comment by TacticalSpacePilot** [comment]
They should work as earmuffs.

**Comment by oklews** [comment]
Earmuffs should make it quiet if you want, but they don’t.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
