### ISSUE TITLE
Allow a particle accelerator to hit multiple Tesla Generators on the same tile. 

### ISSUE THREAD

**Issue by TacticalSpacePilot** [yogstation13/Yogstation#6307]
I spent a long time one round using a handheld teleporter to stack a few Tesla generators on a single tile in a containment. When I fired up the PA only one of the Tesla generators actually turned into a Tesla, and the rest of the Tesla generators were left unchanged. I was severely disappointed. Tesla’s pass through each other and it is a safe way to maximize power generation within a small space, at a high credit cost.

I really want this feature.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
