### ISSUE TITLE
7 AIs always spawn at round start,6 are inactive

### ISSUE THREAD

**Issue by alexkar598** [yogstation13/Yogstation#6312]
## Testmerges:
#6242 

## Reproduction:
Start the round

Potentially related with the test merged PR

**Comment by MegaEmpirical** [comment]
Yeah, this is pretty annoying, we're getting 7 AIs on the PDA and shit like this at round end:

![image](https://user-images.githubusercontent.com/36208065/61094799-af633780-a41e-11e9-9ed3-442e93509543.png)

**Comment by alexkar598** [comment]
Related to testmerge

**Comment by MegaEmpirical** [comment]
.....this is still a problem and it's causing issues with traitor AIs and their round start borgs not being synced.
