### ISSUE TITLE
Plate feature idea

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6317]
Plates currently do nothing, at least to the best of my knowledge they do nothing. They're occasionally generated by food items after being eaten.... though I think soups and such give plates instead of bowls (I'll make a git issue about that later after I check).

After spit balling in #spriter on discord, I came up with this:

Make plates act like the chef tray and allow you to put multiple food on it but significantly few items than the tray. Maybe one 'large' food item and two 'small' food items (I am not sure what the size ranges on food is but I know it varies) and maybe permit eating directly from the plate itself (hold plate with food and click self) rather than taking the items off it?

After being used the plate would become dirty and need to be cleaned before being used again or hell give it a disease chance for using dirty plates.

**Comment by MegaEmpirical** [comment]
https://forums.yogstation.net/index.php?threads/added-plate-functionality.19374/

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
