### ISSUE TITLE
Spam Examining causes lag

### ISSUE THREAD

**Issue by ghost** [yogstation13/Yogstation#6347]
>Spam examining causes lag
## Reproduction:

1. As a ghost, examine a person really quickly, this causes extreme amounts of lag and increases ping to 400+.

**Comment by HomocidlePancakes** [comment]
Remove goonchat

**Comment by k-k-karma** [comment]
its local retard

**Comment by oklews** [comment]
I mean, that seems to be a user side problem, just don’t examine 24/7 and you’re fine, unless it lags everyone.

**Comment by redmoogle** [comment]
Goonchat is gone 🦀 and also probably just client sided
