### ISSUE TITLE
Ethereal move speed is incredibly slow! Unplayable

### ISSUE THREAD

**Issue by Firewolf34** [yogstation13/Yogstation#6367]
## Reproduction: 

Be an Ethereal race character. Try to walk or run.

Regardless of your attire, even if you are wearing nothing at all, and have fully replenished your energy/food, you move at the pace of someone wearing an extremely heavy hardsuit!

Literally cannot play security at all like this, it's horrible. I really hope this is not a "feature".

I had an admin check the vars of my character, and my move speed was reportedly the same as a human so, we're unsure what's causing this bug.

**Comment by jcatjmeow** [comment]
Either this was fixed or unreproducable

**Comment by Firewolf34** [comment]
Yeah this was fixed many many months ago, I should have closed the ticket. Sorry.

**Comment by jcatjmeow** [comment]
> Yeah this was fixed many many months ago, I should have closed the ticket. Sorry.

No worries! That's what I'm here for, to close all the fixed issues.
