### ISSUE TITLE
Stamping eggs with clown stamp makes them invisible

### ISSUE THREAD

**Issue by swissloaf** [yogstation13/Yogstation#6381]
## Reproduction: Contrary to this PR: https://github.com/yogstation13/Yogstation-TG/pull/6192
Stamping eggs with clown stamp makes it invisible, not clown-decorated.

Steps to reproduce:
1. Spawn/have egg
2. Spawn/have clown stamp
3. Stamp egg with clown stamp
4. Watch it turn invisible

Please fix this quick it is very disappointing to see just how lazy our coders and maintainers have become. Is this a prank? Is this the point of the clown egg? The clown egg should be clown decorated not invisible, please fix this as soon as possible because this means very much to me. Thank you.

![image](https://user-images.githubusercontent.com/39781787/61425242-eed8ca80-a8db-11e9-9d79-93d9f9d84baf.png)

**Comment by swissloaf** [comment]
this needs to be fixed immediately lazy coders

**Comment by SomeguyManperson** [comment]
Sounds like the egg doesn't have an icon state which means the pr either didn't mirror the new icons or something else went wrong

**Comment by jcatjmeow** [comment]
This is STILL not fixed.
