### ISSUE TITLE
Sling Veil Not turning of Mech lights

### ISSUE THREAD

**Issue by Codeatmos** [yogstation13/Yogstation#6384]
## Round ID:
24341

## Testmerges:
#6057: '[Project] OmegaStation 2.0' by Lynameep at commit 75e500c7be

## Reproduction:
1.Have a Mech with Lights on
2.Use Veil as Sling
3.Witness that they are still on

Is this a salt issue?
yes im fucking furious fluffe fix this N O W or I will g u n y o u d o w n .

**Comment by MegaEmpirical** [comment]
Hmm, I wonder if the light eater for nightmares works on mechs now.

**Comment by Ludox235** [comment]
> 
> 
> Hmm, I wonder if the light eater for nightmares works on mechs now.

It doesn't and never did

**Comment by MegaEmpirical** [comment]
OVERSIGHT!

**Comment by adamsong** [comment]
This is still an issue
