### ISSUE TITLE
Make forks useful 

### ISSUE THREAD

**Issue by TacticalSpacePilot** [yogstation13/Yogstation#6387]
The only use for forks currently is to gouge people’s eyes out.. And eat omelettes... An idea is to give functionality to forks by allowing them to be used to eat other food items and giving an additional 1-2 nutriment per bite, instead of stuffing the food in your face or something. Using a fork will let you eat slightly faster as well.

**Comment by MegaEmpirical** [comment]
I think it might be better to just remove forks. I've no idea what they do with omelettes but I think if we can make plates useful which are more ubiquitous we can call it a win and just ditch forks.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
