### ISSUE TITLE
Camera/Photos are bugged

### ISSUE THREAD

**Issue by Slinky5890** [yogstation13/Yogstation#6389]
Round ID 24353

I was taking photos and uploading them to the newscaster throughout the round. New photos became invisible and stacked on my hand after I selected the customise photo action and cancelled each prompt (though nich tried to recreate this and it didnt cause the bug). I think the size was 4x4 both times the bug occured.

After the invisible photos stacking, I stopped seeing anything in chat and could not interact with anything that would bring up a menu- it mentioned this in the chat once though https://i.imgur.com/AVejPUm.png. Though I could interact with everything/everyone else normally. Restarting the game both made the photos (which i had dropped on the floor) visible and my other problems were fixed.

It happened again later without the customisation thing, and so I decided to test it with someone else. To see if they could also not see the photos after I dropped them. They could not. After a reset, the photos showed up for me once more, but not for him. He then got the same bug (an engineering cyborg, I think funbot). A reset fixed it for him.

**Comment by oklews** [comment]
this has been a problem since the dawn of time, I would be shocked if it can be fixed

**Comment by Slinky5890** [comment]
> this has been a problem since the dawn of time, I would be shocked if it can be fixed

man, that's a real shame. It's one of my favourite dumb characters
