### ISSUE TITLE
Syndicate contract dropoff point indicates non-existent engine room.

### ISSUE THREAD

**Issue by TheDL13** [yogstation13/Yogstation#6401]
Round ID:24379

Was an IAA, chose contract kit, took a contract, dropoff point indicated "Supermatter Engine" despite map rolling PA-style setup. Followed compass to the tile under the left shutter of the PA, myself and target were present, but tablet would not accept this location to call for pickup. Thanks for your consideration. Also, SCREEEEE!! ANTAG TOKEN?!!

**Comment by jcatjmeow** [comment]
Unable to reproduce. But due to the rng required it's likely it is reproduce-able.

**Comment by patpol4** [comment]
![utwYwoPUat](https://user-images.githubusercontent.com/48154165/99805656-234a3f80-2b3d-11eb-85a3-11b70ded46ac.png)
nice
