### ISSUE TITLE
bulletproof helmets spriteless when given a flashlight

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#642]
1. attatch flashlight to bulletproof helmet (seclite)
2. no sprite
3. cry

**Comment by utahclock** [comment]
do you even read pr adam.... #627

**Comment by timkoster1** [comment]
Adam, please, you failed me.

**Comment by Super3222** [comment]
Hm... I think the server just hasn't updated @AdamElTablawy There's been a confirmed fix merged.
