### ISSUE TITLE
Unable to print "cloning machine console" circuit boards.

### ISSUE THREAD

**Issue by TheDL13** [yogstation13/Yogstation#6436]
Round ID: 24420

Attempting to print a cloning machine console created a crew monitoring console instead. Set it up and indeed it was a crew monitor. Printing a crew monitoring console created a generic "circuit board", tried to set it up and the "connecting the monitor" step would not complete. An admin (Liberalbiass) attempting to spawn the cloning console also resulted in a crew monitor.

**Comment by Ktlwjec** [comment]
The above pr should fix this issue, let me know and I'll reopen this if it didn't.
