### ISSUE TITLE
Revert Perfluorodecalin to it's old state

### ISSUE THREAD

**Issue by Rayisken** [yogstation13/Yogstation#6445]
Currently Perfluorodecalin will mute and kill someone if they overdose (~35u) in a couple of seconds from toxin damage making it a much better tool for murder than it originally was prior to this change.

Please revert it to the old just heals oxygen damage really well and mutes please. Or at the least remove the converts Oxy to Toxic damage portion.

**Comment by MegaEmpirical** [comment]
I've not used it enough to know which way is better but my first interaction with it was really bad. I was out of plasma and didn't realize the oxy kits had changed, ended up killing myself since it still causes toxin damage even when not purging.

**Comment by Rayisken** [comment]
https://github.com/tgstation/tgstation/pull/44015

for reference

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
