### ISSUE TITLE
Crafting menu bug?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#645]
Crafting menu [**sometimes**] doesn't deign to show up no matter what, I need to restart. Happened at least three times. Rare. It reminds me of occasions when I used a canister or air alarm, and when trying to use them again, the window no longer pops up, but it does for other canisters / air alarms. Since it's good after restart, is it just Byond being crap?

**Comment by timkoster1** [comment]
Did you click the crafting "T"?

**Comment by 00aquir** [comment]
yes. click click, nothing.

**Comment by Super3222** [comment]
It might be a cache problem, really. Or tgui not responding.

**Comment by X-TheDark** [comment]
Unfortunately, this lacks any kind of information that would be possible to use to reproduce/debug and therefore fix this problem.
