### ISSUE TITLE
Make bombs more viable

### ISSUE THREAD

**Issue by oklews** [yogstation13/Yogstation#6458]
The big bomb cases you make with plasteel do not tell you what wires do what, never has been this way and I feel as if it should.

Basically I want to not have to almost (and sometimes actually do) detonate the bombs I make if I want to remotely detonate it. Telling us the makers of the bomb what wires do what would be a godsend.

**Comment by Alek2ander** [comment]
Pulse inactive bomb until you find the activation wire, then cut it to disarm.
There's 0 chance of blowing up if you start with a disarmed bomb and you know what you're doing.

**Comment by oklews** [comment]
@Alek2ander every time I tried that the bomb becomes unusable

**Comment by oklews** [comment]
Additionally the making the bomb unusable is a feature, as it is listed as the interaction on both TG wiki and Yog wiki

**Comment by MegaEmpirical** [comment]
Then make a new bomb, the wires are the same.

**Comment by oklews** [comment]
The wires change on every bomb, to prevent someone just making identical chargeless bombs to find the defusal wire and defuse every bomb without fail

**Comment by oklews** [comment]
nevermind, I am big dumb and @Alek2ander is correct
