### ISSUE TITLE
RCD-Floors

### ISSUE THREAD

**Issue by LerzBerz** [yogstation13/Yogstation#6484]
RCD-made floors end up creating air/pressure, which when used on lavaland pushes creatures on it, causing some unfair deaths.

**Comment by LerzBerz** [comment]
RCD-made floors end up creating air/pressure, which when used on lavaland pushes creatures on it, causing some unfair deaths.

**Comment by MegaEmpirical** [comment]
Likely related to: https://github.com/yogstation13/Yogstation-TG/issues/6375

**Comment by Mr-Space** [comment]
#6633 fixed this, Closed.
