### ISSUE TITLE
Make anaesthetics more rewarding to use

### ISSUE THREAD

**Issue by oklews** [yogstation13/Yogstation#6488]
You have almost no reason to use this for surgery

**Comment by MegaEmpirical** [comment]
The best way seems to be by decreasing surgery success chance.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)

**Comment by MegaEmpirical** [comment]
https://forums.yogstation.net/index.php?forums/feature-requests.221/
