### ISSUE TITLE
Plasmamen Chameleon Kit

### ISSUE THREAD

**Issue by Xoxeyos** [yogstation13/Yogstation#6497]
As far as I know, Plasmamen cannot use a regular Chameleon kit, so one is needed for those wanting to stealth their objectives.

**Comment by MegaEmpirical** [comment]
I just wear a space suit and slip out of it.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
