### ISSUE TITLE
Unable to throw players/creatures if held.

### ISSUE THREAD

**Issue by Tykenn** [yogstation13/yogstation#650]
Long story short, this is an **essential** feature to space station 13 as a whole, and therefor should not be neglected.

What I propose is that damage taken from being thrown by someone(The whole reason why it was removed in the first place) be lessened if not taking out completely. Or additionally have a timer/cool down before you would be able to throw someone again.

**Comment by GrayRachnid** [comment]
You have to click on them again while grabbing them in order to reinforce the grab and throw them.

**Comment by Yackitori** [comment]
No Gray, it isn't even a feature anymore. Like you cannot throw someone.

**Comment by timkoster1** [comment]
I think /tg/ removed it because it was getting abused alot with macro's being used to almost instantly wall someone to death.

**Comment by Super3222** [comment]
> I think /tg/ removed it because it was getting abused

this

**Comment by Tykenn** [comment]
This is why I'm saying we don't bring it back into its current state. We change it for the better and then use that altered version instead. 

What I propose we do, is add a **cooldown timer** before being able to throw someone again(You can still carry, do everything else BUT throw them until that timer is reset.); therefore rendering any macros or abusive nature with throwing, obsolete.
