### ISSUE TITLE
A wizard who buys a gem-encrusted hardsuit does not receive internals.

### ISSUE THREAD

**Issue by nesisknesis** [yogstation13/Yogstation#6500]
Oversight.

## Reproduction:

Buy a gem-encrusted hardsuit. Teleport to space. Die.

**Comment by MegaEmpirical** [comment]
I don't recall having this issue, don't wizards start with an internals box?... Also, did you teleport to space without securing internals first?

**Comment by nesisknesis** [comment]
When I was a wizard, the box was completely empty. No, I ahelped for internals.

**Comment by MegaEmpirical** [comment]
Hmm, it's possible I just teleported somewhere I knew where there would be some. That or they're in one of the side rooms.

**Comment by patpol4** [comment]
https://github.com/yogstation13/Yogstation/pull/9730
