### ISSUE TITLE
Containment Field walls randomly self delete

### ISSUE THREAD

**Issue by Fireiy** [yogstation13/Yogstation#6506]
## Round ID: 24584
Made a standard tesla setup. Containment and generation was fine for a while until suddenly part of one of the containment fields disappeared.
![scrnshot1](https://user-images.githubusercontent.com/18078627/62296855-d9f44f00-b424-11e9-9cf6-27f22e9c52e4.png)

**Comment by redmoogle** [comment]
Likely a one off bug have not seen it replicated
