### ISSUE TITLE
N e r f masks

### ISSUE THREAD

**Issue by oklews** [yogstation13/Yogstation#6511]
You currently have no reason besides look to not always wear masks. While normally that would be fine, I recently discovered I hate fun. The idea of making full face masks block a bit of your vision or making them lower the range of your talking seems reasonable to me.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
