### ISSUE TITLE
Cannot pull people

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#6528]
In one shift, no players could pull a torso on the floor, somebody body bagged it and put it into the morgue, then you were able to do it afterwards.

Also, in another shift, a braindead player thrown onto a table was unable to be pulled afterwards (but could be pushed on the table)

![SS13-bug-cannotpull-but-push](https://user-images.githubusercontent.com/16806055/62477472-52eb0200-b7a9-11e9-8762-d20679e001af.png)

**Comment by redmoogle** [comment]
Likely a one off bug, have not seen the issue pop up
