### ISSUE TITLE
Medical cyborg unable to interact with dead bodies

### ISSUE THREAD

**Issue by Mqiib** [yogstation13/Yogstation#6529]
Issue reported from  Round ID: 24665 (Yogstation 13)

Reporting client version: 512.1463

As a medical cyborg, surgery on dead people to revive them is really useful, but it can't be done because it seems that once you try to use a health scanner on the dead body during wound tending surgery, they become uninteractable beyond simply dragging or examining. This has happened with both brute and mixed wound tending, before and after the point where they cannot be defibbed.

**Comment by Mqiib** [comment]
Oh boy more details on how broken this is. Medical cyborgs can't do ANYTHING to someone that is in the middle of surgery beyond than the actual surgery steps. This means that if they are doing DNA recovery and forget to add in the rezadone before starting the surgery they can't finish it, not can they for whatever reason end it.
Also wound tending surgeries are still broken @jcatjmeow pls fix

**Comment by adamsong** [comment]
This is no longer an issue.
