### ISSUE TITLE
Remove ability to put a pai in a mule bot

### ISSUE THREAD

**Issue by drderp3635** [yogstation13/yogstation#653]
[Note]: if you put a pai in a mule bot with the safety features off it creates an almost industructible monster that can stun and kill in not even three seconds just by walking on someone

**Comment by ShadowDeath6** [comment]
it was never intended to be fully mobile like that, so it does some retarded damage since the chance of being run over was so slim anyway

**Comment by GrayRachnid** [comment]
It's destructible though. 10 hits from a large oxygen tank kills it, that means it has around 100 health.

**Comment by ParagonPrime** [comment]
maybe leave it with "automatic impact brakes" to prevent it from dealing damage normally

when emagged, it becomes a death machine- but also becomes super obvious, á la red lights and spark trail, and maybe an occasional sound clip playing when it drives by

**Comment by tromacodes** [comment]
PAI were supposed to be companion buddies there for advice and companionship they were originally not meant to interact with the game like this. I am not very enthusiastic about the change in PAI philosophy

**Comment by EMT321** [comment]
I ded.

Mulebots can be disarmed from pAI's by literally any borg, AI, or person standing next to them. They also have very bright red flashing lights if they can run you down.

**Comment by Cruix** [comment]
They cannot be ejected by silicons if the radio is turned off and they cannot be ejected by people if the controls are locked.

**Comment by EMT321** [comment]
I have never seen that done.
