### ISSUE TITLE
Internal Affairs pinpointer bugs

### ISSUE THREAD

**Issue by tsaoToast** [yogstation13/Yogstation#653]
1st bug noticed : If you take the same limited job as your target (In my example: Getting CE while being tasked to kill the CE) will have the pinpointer point towards them and the Agent. Seems inconsistent on when exactly it does it

2nd bug noticed : If the person goes braindead, it will act as if they're dead and stop tracking them.

**Comment by GrayRachnid** [comment]
IIRC IA is supposed to change your objective everytime your target dies/becomes braindead, i'll look into how it works and make an issue on /tg/s git.
