### ISSUE TITLE
Speaking Binary as Head

### ISSUE THREAD

**Issue by FlamePrince** [yogstation13/Yogstation#6536]
## Round ID: 
N/A

## Testmerges:
N/A

## Reproduction:
Select "Preternis" as your default class, set a head role to High. 

This should result in you spawning as human with the ability to speak and understand binary and be able to heal yourself with cable and welder (sometimes). I am unsure of what other preternis qualities make it in, but I appear to be fragile like one with the limbs of a human.

**Comment by MegaEmpirical** [comment]
I already beat you to the punch since I saw that you had not made a git issue for it yet, but thanks. Also, I am pretty sure you mean encoding language and not binary.
https://github.com/yogstation13/Yogstation-TG/issues/6535

**Comment by Amelia0010** [comment]
see the other issue
