### ISSUE TITLE
Disposals' Loop causing crashes

### ISSUE THREAD

**Issue by FlamePrince** [yogstation13/Yogstation#6546]
## Round ID:
24744

## Reproduction:
TheDL (CE) built a short three tile disposals loop to secure the nuke disk in Captain's office. This caused client crashes for myself and SirCodey (Captain). Once the disposals loop was admin deleted by Qe, the crashes stopped.

Ezlan came on and reproduced the issue at CentComm, as soon as he started looping the disk it crashed my client.

https://media.discordapp.net/attachments/378318242906636288/609716741676859393/unknown.png

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Also crashed mine

**Comment by SirCodey** [comment]
can confirm, shit's whack

**Comment by redmoogle** [comment]
Replicated

**Comment by adamsong** [comment]
Has this been fixed or is this still an issue? I was unable to replicate it, but it seems like the issue only happens on some clients anyway

**Comment by ReddicusDragon** [comment]
Closing this, I figure if someone crashes again we'll hear about it.
