### ISSUE TITLE
Port tg tweak to let kinetic crushers be carried in one hand

### ISSUE THREAD

**Issue by Fireiy** [yogstation13/Yogstation#6548]
While fun to use, kinetic crushers are incredibly unwieldy to use. This would make them a lot less annoying to inventory juggle, especially for defusing gibtonite.

Link to the tg tweak: https://github.com/tgstation/tgstation/pull/45110

**Comment by Readystorm546** [comment]
Eh im not feeling that one

**Comment by oklews** [comment]
The whole meme of them is to be difficult and unwieldy to use, it’s for trophy hunter miners, otherwise it is an objectively better mining scanner.

**Comment by Fireiy** [comment]
I would argue that the main difficulty of the crusher comes from the fact that you're forced into melee range with mining mobs, while the unwieldiness is simply added tedium.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
