### ISSUE TITLE
Volume Pump does not put all of the gas into the can.

### ISSUE THREAD

**Issue by Readystorm546** [yogstation13/Yogstation#6553]
So i do a trit burn and this trit burn produces alot of trit but some of it is just left sitting in the pump and does not go into the can. im not sure if this is an issue or not but.

**Comment by Bibby0110** [comment]
whats the composition of the gas? 100% trit? at what temperature?

**Comment by MegaEmpirical** [comment]
Was the can full? Also, pumps and connectors have volume too and they do not 'push' it into a canister, they just equalize it across their volume as best as they can.

**Comment by Readystorm546** [comment]
The can was 100% trit and i got 1000 mols in the can but there was like 250 moles that were still in the pump. Also the trit was at 30K. Can as no where near full

**Comment by Readystorm546** [comment]
I tried with a gas pump as well and the gas pump did the same thing.

**Comment by MegaEmpirical** [comment]
A gas pump will stop once the target volume is reached so it won't do. Knowing the volume is more useful than those other bits, I'm not doing the math to convert but that does seem low, I'd suggest trying to recreate the issue and screenshot it.

**Comment by Readystorm546** [comment]
![image](https://user-images.githubusercontent.com/52303581/63054835-a26cb480-beb2-11e9-8e3d-2e6d625192ba.png)

The can of trit 

![image](https://user-images.githubusercontent.com/52303581/63054964-dba52480-beb2-11e9-9ace-58fa8e4f3b4c.png)

The volume pump

![image](https://user-images.githubusercontent.com/52303581/63055009-ef508b00-beb2-11e9-99fb-22996623f4bf.png)

The set up

**Comment by MegaEmpirical** [comment]
Hm reminds me of something I was told a while ago: pumps and shit don't move the full volume over. It's never affected me because of how I set my stuff up so it's not been an issue.

**Comment by Readystorm546** [comment]
Is there any way to fix this or is it a actual bug that needs to be patched out

**Comment by MegaEmpirical** [comment]
I've no idea if it's intended or not but it's at least easily resolved/avoided in game. I just flush my lines, or deconstruct the pump.

**Comment by Readystorm546** [comment]
Well i want the extra moles of tirt into the can not just gone.

**Comment by Bibby0110** [comment]
its hard to create a perfect vacuum. Seems to be working as intended

// Pump mechanism just won't do anything if the pressure is too high/too low unless you overclock it.
if((input_starting_pressure < 0.01) || ((output_starting_pressure > 9000))&&!overclocked)
		return
