### ISSUE TITLE
Please reduce the likelihood that the engine is Tesla/Singulo

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6557]
The tesla/singulo are incredibly boring and uninteresting engines that just sit around and just have a high risk of being let out. The SM is actually engaging, fun, and can be experimented with but also messed with to do really cool stuff (for good and bad).

I am not opposed to having them, I actually like the option, but I would like it if maybe the likelihood of getting the tesla/singulo was closer to 20% of the time instead of 50%.

**Comment by FlamePrince** [comment]
Speaking as someone who is pretty dedicated to the tesla, I definitely support this. As much as I might like the older engines, the supermatter helps engineers to better understand the very stupid basics of atmospherics and construction (if they fuck with the emitters) that will help them perform their job a lot better.

Furthermore, corrective action is a lot easier for a supermatter that has delaminated versus a loose goose. This means longer rounds and less impact from a misclick by a careless engineer. (don't look at me like that!)

I can always order a tesla/PA kit and set it up in a small room, so I'm definitely not against this.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
