### ISSUE TITLE
Mentors can set the Tip of the Round

### ISSUE THREAD

**Issue by TacticalSpacePilot** [yogstation13/Yogstation#6562]
Give mentors the admin verb "Show Tip" because admins rarely ever use it for anything worthwhile.

[Feature Request]

**Comment by FlamePrince** [comment]
This seems like an ideal situation.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
