### ISSUE TITLE
4-Directional Colosus Sprite

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#6566]
Sent these in long ago, got added in a before the re-base and I never re-submitted them. Yes I know, ass.
[Colossus 4 Dir Sprites.zip](https://github.com/yogstation13/Yogstation-TG/files/3499146/Colossus.4.Dir.Sprites.zip)
![colossus](https://user-images.githubusercontent.com/18729830/62981977-683ade80-bdf0-11e9-9b1c-0f5df687a8ae.png)

**Comment by Szyszkrzyneczka** [comment]
Thicc
