### ISSUE TITLE
Legion everything?

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#6567]
I would like to sprite THE LEGION across all species (or at least as much as possible). Would it be worth my time to do so so legion could feel much more terrifying? Here's a preview:
![goliath_e](https://user-images.githubusercontent.com/18729830/62982333-750c0200-bdf1-11e9-8faf-791255038c2f.png)![goliath_n](https://user-images.githubusercontent.com/18729830/62982334-750c0200-bdf1-11e9-9097-2edad3827525.png)![goliath_s](https://user-images.githubusercontent.com/18729830/62982335-750c0200-bdf1-11e9-8898-8bf115a2386b.png)![goliath_w](https://user-images.githubusercontent.com/18729830/62982336-750c0200-bdf1-11e9-8bdb-de7b5b8bcc6c.png)
![watcher_e](https://user-images.githubusercontent.com/18729830/62982337-750c0200-bdf1-11e9-9726-1944cc52d607.png)![watcher_n](https://user-images.githubusercontent.com/18729830/62982338-750c0200-bdf1-11e9-9694-0a855bf1696e.png)![watcher_s](https://user-images.githubusercontent.com/18729830/62982339-750c0200-bdf1-11e9-9217-af05e979c3d8.png)![watcher_w](https://user-images.githubusercontent.com/18729830/62982340-750c0200-bdf1-11e9-9603-0452d5e07c4d.png)
More (8/18):
![spider_e](https://user-images.githubusercontent.com/18729830/63231205-0c040000-c1de-11e9-947c-8b5484e71c76.png)![spider_n](https://user-images.githubusercontent.com/18729830/63231206-10301d80-c1de-11e9-9b18-0ad4c00533c8.png)![spider_s](https://user-images.githubusercontent.com/18729830/63231207-12927780-c1de-11e9-8905-40b40693e4dd.png)![spider_w](https://user-images.githubusercontent.com/18729830/63231209-145c3b00-c1de-11e9-965f-522adcb78773.png)
![carp_w_2](https://user-images.githubusercontent.com/18729830/63231220-3a81db00-c1de-11e9-8d59-f499711607e1.png)![carp_e_2](https://user-images.githubusercontent.com/18729830/63231221-3a81db00-c1de-11e9-9925-8f907765c2b0.png)![carp_n_2](https://user-images.githubusercontent.com/18729830/63231222-3a81db00-c1de-11e9-8261-9dbcc4449532.png)![carp_s_2](https://user-images.githubusercontent.com/18729830/63231223-3a81db00-c1de-11e9-9956-9dbe16611a1c.png)
![bee_1](https://user-images.githubusercontent.com/18729830/63231224-47063380-c1de-11e9-9e45-57cd11069314.png)![bee_2](https://user-images.githubusercontent.com/18729830/63231225-47063380-c1de-11e9-8bbd-e2d1093d7efd.png)
Zip as of 8/18 (more including animation frames, baby & adult slime, and queen bee inside): [Legion Project (Crazy_Drakkon).zip](https://github.com/yogstation13/Yogstation-TG/files/3513638/Legion.Project.Crazy_Drakkon.zip)

**Comment by Ludox235** [comment]
Looks fucking terrifying, I love it

**Comment by fluffe9911** [comment]
yes

**Comment by MegaEmpirical** [comment]
Monkey legions.

**Comment by Szyszkrzyneczka** [comment]
I see this as a positive change, would make for some interesting encounters

**Comment by FlamePrince** [comment]
I like this and I can't see why not

**Comment by CrazyDrakkon** [comment]
Positive feedback noted (& appreciated!) and made a few more posted up there.

**I̴̱̔̚T̷̞̥͗͠ ̷̲͉͛͗ ̵̭̈́ ̵͇̟͑͗S̸͕̋͘P̷̬͛͊Ŕ̵̰̏E̴̾͜A̵͔͕͋Ḍ̸̠̍S̸̲͊̆**

**Comment by alexkar598** [comment]
Thing is unless you are planning on taking the hundreds of mobs in this game,your going to need to decide on one or more generic sprites that would get chosen if it can't find an appropriate sprite for the mob

**Comment by CrazyDrakkon** [comment]
@alexkar598 I got that, just making the ones I want specific ones I want first, like "legIAN".

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
