### ISSUE TITLE
Wizard magic missiles ignore antimagic from hypertool nullrod

### ISSUE THREAD

**Issue by Mqiib** [yogstation13/Yogstation#6569]
Issue reported from  Round ID: 24803 (Yogstation 13)

Reporting client version: 512.1463

As chaplain, I held the hypertool (one of the nullrod variants) in my hand and still was stunned by a magic missile cast by a wizard.
![image](https://user-images.githubusercontent.com/43766432/62994392-9852a380-be29-11e9-90c9-4901e1d7576a.png)

**Comment by SomeguyManperson** [comment]
Magic missiles currently ignore antimagic for some stupid reason
