### ISSUE TITLE
You can expose lavaland to space

### ISSUE THREAD

**Issue by oklews** [yogstation13/Yogstation#6573]
This was done with local testing on this code, so take it with a grain of salt

There are a few Russian ruins on lava land which have windows that when broken expose the room to space, I doubt this was intended. One of the most notable is the Russian Bunker

Reproduction: 

Find Russian Bunker
Break windows
Expose yourself to the vaccume of space

**Comment by MegaEmpirical** [comment]
Nice find.

**Comment by GenericDM** [comment]
From what I recall, this is probably due to some of the ruins being surrounded by space areas instead of lavaland ones. This leads to there being space that appears when destroying rock, instead of lavaland floor.
- [x] Blame fluffe

**Comment by monster860** [comment]
this has been fixed with map changes.
