### ISSUE TITLE
Problem with Layer adapters on Yogsmega Distro/Scrubbers.

### ISSUE THREAD

**Issue by dan2wik** [yogstation13/Yogstation#6597]
## Round ID:
24891

## Reproduction:
On station Yogsmeta, the layer adapter for Distro and Scrubbers inside of atmos appears disconnected on round start. Attaching meters to the pipes causes them to show "Error Lights" sometimes. The layer adapter during this round stopped acting like a layer adapter entirely. Couldn't be unwrenched (unwrenching would instead hit it.), the visuals weren't updating and all pipes and the RPD acted like it did not exist.

![image](https://user-images.githubusercontent.com/1253226/63239197-7758db00-c28d-11e9-91c3-bd2e8cb8ff35.png)

**Comment by MegaEmpirical** [comment]
I was there with him, I can confirm this.

**Comment by Ktlwjec1** [comment]
This should be fixed now, let me know and I'll reopen this if it's not.
