### ISSUE TITLE
Asteroids have no gravity. stranding mining ripleys

### ISSUE THREAD

**Issue by DuathaDruid** [yogstation13/Yogstation#6612]

**Comment by MegaEmpirical** [comment]
That's normal, that's why you don't jump into the abyss.

**Comment by patpol4** [comment]
Doesnt seem to be this way, maybe something changed since this report was made, you only float if you go into space
![fmFZP2K2xF](https://user-images.githubusercontent.com/48154165/88273337-55a47700-ccda-11ea-9dee-e61dd2021ebd.gif)
