### ISSUE TITLE
Surgery not working

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#6635]
Round 25017

"Cerebral traumas detected: subject appears to be suffering from deep-rooted traumatic narcolepsy."

the CMO was not able to fix it with surgery or chemicals.

**Comment by nesisknesis** [comment]
Did the CMO perform lobotomy? Deep-rooted traumas are incurable by any other method other than the lobotomy surgery.

**Comment by MegaEmpirical** [comment]
and even then some traumas become permanent.

**Comment by 00aquir** [comment]
Since I'm not absolutely sure about the surgery type ( because I repeatedly fell asleep ), I'll reopen when I encounter it again.
