### ISSUE TITLE
Robotics Exosuit Fabricator Deletes Materials?

### ISSUE THREAD

**Issue by Cyrvex** [yogstation13/Yogstation#6642]
## Round ID: 

25034
Robotics Exosuit Fabricators broke a little
Oh, No metal to finnish que? alright *hit return*(break starts here)
asks AI if metal is in arrivals. Yes & in EVA.  Arrivals only had 2 sheets of metal & EVA had its full 2x 50 Metal
Alright puts them in fabricator. Realise its broken. Deconstruct & reconstruct since its the only option. No material comes out just the components its built out of.

Basicly deleted the materials.
AI was using the bottom Fabricator for BORIS Borg Boddies
and i was using the top for borgs. & misc

**Comment by Cyrvex** [comment]
Forgot to say both fabricators ran out & both broke the same way.

**Comment by SomeguyManperson** [comment]
I don't think it's deleting the materials, they are connected to the ore silo by default and if broken won't drop anything in that state since all the material is stored on the silo
