### ISSUE TITLE
Holopad ruins normal vision

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#6644]
- you get static for visual as a human if you go to certain areas, after communicating via holopad, and you disappear in it if you keep walking.

![SS13-bug-holopad-view-remains](https://user-images.githubusercontent.com/16806055/63791429-c93bd980-c8fb-11e9-81d0-c84a8428b21d.png)

**Comment by adamsong** [comment]
Cannot reproduce, likely fixed
