### ISSUE TITLE
Could admins get a window that shows prayers, centcomm messages, and syndicate messages

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6647]
It kind of sucks that if you miss these that you have to log dive and that generally a little hard to see at times. It would be nice if there was a window that can be pulled up with a log for them.

**Comment by FlamePrince** [comment]
This would be great.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
