### ISSUE TITLE
Dead and braindeads still prompt ghosts for trauma roles

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6648]
https://github.com/yogstation13/Yogstation-TG/issues/6537 Was supposed to fix this but all it seems to have done is prevent you from taking the role, you still get prompted for the roles as a ghost.

**Comment by FlamePrince** [comment]
please send help

**Comment by MegaEmpirical** [comment]
Believe this was actually resolved.
