### ISSUE TITLE
After borer controlled host gibbed, you get into "you are just a brain" even if you took another role

### ISSUE THREAD

**Issue by Paragonid** [yogstation13/yogstation#665]
1. Become a borer
2. Infect (control, something else)
3. Leave host (get stuck on this step, can not move at all, says i'm out though)
4. Go ghost
5. Become xeno's spider
6. When the host from step 2 gibbed, get teleported to brain, (play as the brain)

Expected: 6. When hosts gibbed, stay spider.

Step 3 might be a bug as well, I didn't realize why could I not move

**Comment by AdamElTablawy** [comment]
not an issue anymore
