### ISSUE TITLE
Oldyog had a feature with Phytosians thralls ignoring darkness and healing near their master + quality of life conversion process. It seems to have been lost.

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/Yogstation#6662]
**Healing near Shadowling master, taken from** https://github.com/yogstation13/yogstation/blob/fe168954fc9417a8fe99f35c059e178f99a4e213/code/modules/mob/living/carbon/human/species_types.dm :
if(A.murders_plants)
		if (H.mind)
			if (H.mind.special_role == "thrall")
				if (H.stat != UNCONSCIOUS && H.stat != DEAD)
					for(var/V in ticker.mode.shadows)
						var/datum/mind/sling_mind = V
						if(sling_mind.current && (get_dist(sling_mind.current, H) < 3))
							light_level = -2
							light_msg = "<span class='warning'>Being in the presence of one of your masters revitalizes you.</span>"
							H.adjustToxLoss(-1, 1)
							H.adjustOxyLoss(-0.5, 1)
							H.heal_overall_damage(1.5, 1.5)
							break

**Everything else from** https://github.com/yogstation13/yogstation/blob/fe168954fc9417a8fe99f35c059e178f99a4e213/code/game/gamemodes/shadowling/shadowling_abilities.dm
**Chemicals to prevent death during conversion process:**
if (target.dna.species.id == "plant")
			//ugh this is the hackiest fix ever but who cares
			target.reagents.add_reagent("salbutamol", 25)
			target.reagents.add_reagent("charcoal", 25)
			to_chat(user, "<span class='danger'>You watch as [target]'s foilage begins to wilt under your influence. You drive a thorned lance into their neck, injecting them with a slew of preserving chemicals. They must survive the process.</span>")
			to_chat(target, "<span class='userdanger'>Held rapt by [usr]'s fell gaze, you are unable to react as they strike out at your neck with a barbed lance, sending a soothing sensation throughout your wilting leaves.</span>")
**Lore tidbits:**
if(3)
					to_chat(user, "<span class='notice'>You begin planting the tumor that will control the new thrall...</span>")
					user.visible_message("<span class='warning'>A strange energy passes from [user]'s hands into [target]'s head!</span>")
					to_chat(target, "<span class='boldannounce'>You feel your memories twisting, morphing. A sense of horror dominates your mind.</span>")
					if (target.dna.species.id == "plant")
						to_chat(target, "<span class='boldannounce'>Primeval memories suddenly surge throughout your consciousness. The Other, the kind of your own shunned by the light of the binary stars. This creature is one of them.</span>")
**Message informing Phytosian that darkness no longer kills him + more lore:**
if (target.dna.species.id == "plant")
			to_chat(target, "<span class='boldannounce'>You suddenly understand. This is the natural order of things. The light must be shunned. Your insides shift and twist as the influence of the Other takes effect. Darkness is no longer lethal to you.</span>")
		target.setOxyLoss(0) //In case the shadowling was choking them out
		var/obj/item/organ/thrall_tumor/T = new/obj/item/organ/thrall_tumor(target)
		T.Insert(target, 1)

**Comment by MegaEmpirical** [comment]
I think it should be considered a feature. As a plasmaman, I get killed by revs usually. Just a racial hazard.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
