### ISSUE TITLE
Missing texture for Ronald Mcdonald ("Mascot") clown mask style

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#668]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
Self-explanatory. I was going to attempt the Ronald Mcdonald gimmick by changing the clown mask, but the mask style displays as nothing.
[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by Kmc2000** [comment]
Fixing , will be done soon

**Comment by Kmc2000** [comment]
Fixed
