### ISSUE TITLE
Make magboots lube proof

### ISSUE THREAD

**Issue by LoliconSlayer** [yogstation13/Yogstation#6687]
Make Magboots impervious to space lube, it just doesn't make sense that you can slip on space lube with magboots on. Magboots keep you anchored through magnetic force not friction so the frictionless surface of a lubed floor shouldn't matter.

**Comment by MegaEmpirical** [comment]
While it is true that mag boots keep you anchored via magnetism, it is not true that they'd be unaffected by friction. The friction is what keeps you from sliding. So if you step in a substance that removes all friction, then yes you will slide with mag boots.

This is not to say that I don't agree with the intent of this request, only that your logic is wrong.

**Comment by oklews** [comment]
The game itself does not follow this logic, as it is immune to slipping via soap

**Comment by MegaEmpirical** [comment]
I don't see any discrepancy with soap.

**Comment by B1gb3ast** [comment]
Chemist buff chemist buff
Now I don’t need to spend TC on no slips and can purchase my Desword and steal CE magboots, smoke machine full of space lube in escape for ez hijack. Impervious to anything but borgs.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
