### ISSUE TITLE
Make releasing viruses a little more reasonable in regards to space law

### ISSUE THREAD

**Issue by kooarbiter** [yogstation13/Yogstation#6688]
Grand sabotage lists releasing viruses as eligible, it's vague as to if it means all viruses, only bad ones, or even all bad ones or just some bad ones, I think a small fix would improve the freedom of virlogy.

First of all, mostly or completely beneficial viruses released by the virologist not approved by the (acting)CMO/whoever their boss happens to be or captain would result in a neglect of duty charge.

Releasing a bad but not lethal or horrible virus, something that is inconvenient or painful but not lethal (or does so little damage you'd have to be a potato to die to it alone) would count as regular sabotage.

Releasing a virus with symptoms that severely hamper the productivity of the crew or is very likely to kill them if not cured would of course count as grand sabotage.

Cough, while seemingly counting for the former, is workable, if tedious and annoying, and getting a cold doesn't necessarily prevent you from working. Itching, while it does do some damage, is not particularly lethal to someone who wasn't already going to die anyways.

Releasing a virus unintentionally, or with some intent other than criminal would count as neglect of duty, unless the specific viruses that were release were approved, then it's on them and anything that happens is their fault icly and oocly, better get those permission slips!

**Comment by MegaEmpirical** [comment]
1) This is not a code issue. Take it to the forums.

2) I've no issues with intentional and illegal releases of any virus being grand sabotage. They're contagious and even something as basic as coughing can lead to serious issues.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
