### ISSUE TITLE
Re-add duct tape (From old code) & crafting recipes

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#669]
We're missing the shank, robust uniform & coat, and glass swords because of the lack of duct tape and re-base. Please re-add?

**Comment by Yackitori** [comment]
Plz don't re add the cancer

**Comment by ShadowDeath6** [comment]
ghetto armory was removed for good reason

**Comment by ParagonPrime** [comment]
duct tape should be re-added for various non-cancer purposes

such as GHETTO MUZZLES

**Comment by Super3222** [comment]
Ghetto armory was abandoned on purpose. It didn't balance out well with the game and the sprites were lowbrow.

**Comment by Drakkon** [comment]
Well there's my first great suggestion. What about re-added as cheap telecrystal filler as cheap multi-purpase restraints? Can be used like any restraints we already have depending on body part selected, takes time to apply, but super easy/fast to break free from piece-by-piece if not interupted.

**Comment by ShadowDeath6** [comment]
goon has traitor ductape as infinite use cuffs, I don't see any problem with adding that
