### ISSUE TITLE
Select equipment options for plasmamen jobs are insufficient

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6692]
They give only a helmet, suit, and mask but no plasma tank and none of the job specific stuff. This is clearly racist.

**Comment by nesisknesis** [comment]
If anyone improves this, also make the outfit names be Plasmaman [Job] so that they're grouped together in the select equipment list instead of mixed with other outfits.

**Comment by MegaEmpirical** [comment]
This was partially resolved. Remaining issues have new tickets.
