### ISSUE TITLE
Paper markdown feature: One use new field entry mark 

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6693]
Basically like %f where you can input new text in the middle of a page but is one use only. So that after you've added it, the [Write] prompt on the paper goes away next time it's used.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
