### ISSUE TITLE
Gary the Goat (clown goat) does not have a sprite

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6701]
/mob/living/simple_animal/hostile/retaliate/goat/clown

Nothing, nada.

**Comment by sam0oneau** [comment]
![Abomination](https://user-images.githubusercontent.com/30634117/64621757-28125000-d3de-11e9-9513-3a4edf4e5f57.png)
![Abomination](https://user-images.githubusercontent.com/30634117/64621817-3e201080-d3de-11e9-8a7c-2d64ae590d51.png)
