### ISSUE TITLE
Space Pod has no pressure, even indoors!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#6703]
- crew is forced to wear hardsuit+ internals inside of it.

**Comment by nesisknesis** [comment]
did you put an oxygen or air canister inside it, they need one of those.

**Comment by 00aquir** [comment]
ah okay then.

**Comment by 00aquir** [comment]
okay then, wiki doesn't mention it.

**Comment by 00aquir** [comment]
at no point was it possible to add any type of oxygen tank to it. does it only work with air tank?
