### ISSUE TITLE
Nuke Ops Shuttle Turrets Shoot Through Walls

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#6704]
- they also shoot impossibly fast through the walls, mostly you cannot even get out of range once they start to shoot you.  Of course ops can place the shuttle right above the Armory. in some way, nerf.

![SS13-bug-syndie-shuttle-turrets-through-walls](https://user-images.githubusercontent.com/16806055/64637611-763a4a00-d404-11e9-831c-09d0feecb735.png)

**Comment by ynot01** [comment]
this isnt a bug

**Comment by 00aquir** [comment]
then still, the penetration should really be decreased because sec cannot even defend the armory when they blow up the walls, as you see.

**Comment by 00aquir** [comment]
still, the penetration should really be decreased because sec cannot even defend the armory when they even partially blow up the walls, and turrets shoot through absolutely anything, as you see.

**Comment by SomeguyManperson** [comment]
Thanks TG

**Comment by Mr-Space** [comment]
This isn't a bug, if you want so, feel free to PR it so the penetration is decreased. I'm closing this.
