### ISSUE TITLE
Braindead Vamps

### ISSUE THREAD

**Issue by Starmonger** [yogstation13/Yogstation#6705]
Issue reported from  Round ID: 25257 (Yogstation 13)

Reporting client version: 512.1479

I don't know if this is a bug or working as intended, but Vampires show up as braindead when put in cloners. I guess this is so they can't be cloned since they're technically dead, but damn.

**Comment by SomeguyManperson** [comment]
I do know vampire brains are similar to ling brains in that they don't hold the actual player when removed

**Comment by adamsong** [comment]
Is this intended or a bug?

**Comment by adamsong** [comment]
Vampires, even fully powered ones, can be cloned
