### ISSUE TITLE
Last Resort didn't gib

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#6708]
## Round ID:

25256 about an hour in

## Reproduction:

Clicking yes on last resort

![Jk1KGsC](https://user-images.githubusercontent.com/28408322/64635732-4b350380-d3ce-11e9-9ee0-963bb82fde0a.png)

**Comment by kooarbiter** [comment]
when i tried using last resort the other day while laying underneath a kill target, they were only wounded, i was critted, and my ears and eyes were destroyed
