### ISSUE TITLE
Cant do revival surgery

### ISSUE THREAD

**Issue by constatinus** [yogstation13/Yogstation#6712]
## Reproduction:

As a borg, and the CMO even tried it, we cant revive a patient. We had it researched, he wasnt on defib, were targeting thew head.

**Comment by SomeguyManperson** [comment]
What failure message did you get?

**Comment by constatinus** [comment]
> 
> 
> What failure message did you get?

I didnt get one, the surgery didnt show up at all... It seems to be working now

**Comment by oklews** [comment]
Did you update the surgical computer?
