### ISSUE TITLE
Add a second stage to the Tesla engine

### ISSUE THREAD

**Issue by LoliconSlayer** [yogstation13/Yogstation#6714]
Now that the Tesla's been limited to 10 balls, it'd be nice if there was a second stage added so that once the Tesla reaches 10 balls it can go beyond and generate more power without destroying the server. Basically just give the Tesla a color change and make it produce 1.5x more power (or whatever seems most balanced) after it gets enough power from the particle accelerator.

Originally altoids' idea.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
