### ISSUE TITLE
Give Ashwalkers a bow and arrow, for reasons.

### ISSUE THREAD

**Issue by neeshacark** [yogstation13/Yogstation#6723]
While this thing says I *should* post it on forums suggestion page, nobody ever looks there, like ever. I feel like posting it here would get it noticed more.  There was a guy talking about how Ashwalkers should get a bow the other day, and I've personally wanted a bow myself.

It could just be a unique spawn at their base (boring) or more likely a craftable with wood and cable coil, and or a custom item which you can get off marrow weavers.  Can also make a quiver from cloth, or more wood. Acts as a belt, can hold arrows which could be made from something, metal rods, or wood?  Arrows are fired much like pneumatic cannon fires random shit, and hit with an incredibly high chance to embed.  Can be fired by any race regardless of their finger size. 

Bowstring must be drawn back before firing, like Mosin-Nagant has the cocking feature. You draw back, load arrow, fire.  Since you could just steal most of the code from the pneumatic cannon, all you'd really need is a sprite.

Edit: As a side note, Crazy_Drakkon on the discord seems to have sprites for such a thing already, but they never got used.  Also, watcher sinew for bowstring.

**Comment by CrazyDrakkon** [comment]
Aaand here they are!:
![pathfinderbow](https://user-images.githubusercontent.com/18729830/64919803-b4bd6500-d774-11e9-97f5-7c39329129d8.png) ![pathfinderbowloaded](https://user-images.githubusercontent.com/18729830/64919804-b555fb80-d774-11e9-88c4-63688a09a7b2.png) ![pathfinderarrow](https://user-images.githubusercontent.com/18729830/64919801-b4bd6500-d774-11e9-8f28-c3a84487660d.png)
![pathfindercrossbow](https://user-images.githubusercontent.com/18729830/64919805-b555fb80-d774-11e9-8796-fd7ff10fe51f.png) ![pathfindercrossbowloaded](https://user-images.githubusercontent.com/18729830/64919806-b555fb80-d774-11e9-9ac2-c7b3b54adbd7.png) ![pathfinderbolt](https://user-images.githubusercontent.com/18729830/64919802-b4bd6500-d774-11e9-9580-9229c4100c2a.png)

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
