### ISSUE TITLE
It's ok, humans don't need blood

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#6724]
Issue reported from  Round ID: 25439 (Yogstation 13)

Reporting client version: 512.1484

Local madman survives with only three centiliters of blood after three vampires consume him at once and takes no damage whatsoever
This happened in several places this round, including with another guy who lost all his limbs, went catatonic, and bled to 0 cl, and several other vampire victims who had to be executed conventionally after losing literally all their blood and continuing to live and breathe as dessicated husks
To the surprise of possibly no one the vampires all ascended handily with the vampiric equivalent of cold fusion generators wandering around eveywhere
![centiliters](https://user-images.githubusercontent.com/36427443/64926894-5a062680-d7d1-11e9-8141-9d4d4cbef50a.png)
![n o b l o o d](https://user-images.githubusercontent.com/36427443/64926895-5a062680-d7d1-11e9-9dc2-94581ff71a0a.png)

**Comment by MegaEmpirical** [comment]
Vampires winning? Now I know you're lying.

**Comment by SomeguyManperson** [comment]
This was caused by altoids' blood system rework since the proc that checks how much blood you have for damage purposes will for some reason always return the first case in its switch, which in our case is super hyper full blood

**Comment by TacticalSpacePilot** [comment]
Yeah this has also happened with IV drips. The person was alive on like 20% blood when I drained it all.
