### ISSUE TITLE
Clock cult start up

### ISSUE THREAD

**Issue by Readystorm546** [yogstation13/Yogstation#6727]
Whenever clock cult starts it lags the game. Pretty bad. I have no idea how to fix it but for thoes who know that this happens it just kinda ruins that round. If someone could fix this that would be great.

**Comment by Amelia0010** [comment]
This isn't a bug, this is what maploading is like. It's why all the other map templates are done at roundstart.

**Comment by Readystorm546** [comment]
So would the fix to be load rebe outside of round start without everything that makes it clock cult
