### ISSUE TITLE
Disposals trash compactor put in backwards

### ISSUE THREAD

**Issue by Doctadeth** [yogstation13/Yogstation#674]
[Round ID]: # (Including the round helps a lot as it allows us to quickly find more information. It can be found in the Status panel.)

[Reproduction]: # conveyor belt to end of disposals trash compacter goes backwards (Back towards the chute entrance) 

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by ThatLing** [comment]
@nichlas0010
