### ISSUE TITLE
Exosuit fabricators freeze when they run out of resources mid-task

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#6743]
Issue reported from  Round ID: 25569 (Yogstation 13)
Multiple rounds, actually. I think it happens every time.

Reporting client version: 512.1485

As the title says. Any option you pick when it gives you the "not enough resources" screen will lead it to saying that it's doing that same task it can't do. You have to deconstruct and reconstruct them after to unlock them from this, which unlinks them from the ore silo, which is a huge pain to resolve as always.

**Comment by CMOisLing** [comment]
Had this happen before just didn’t know why

**Comment by oklews** [comment]
Had this happen to me too
