### ISSUE TITLE
Please merge HoP ticket Counter PRs

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6769]
Main: https://github.com/tgstation/tgstation/pull/45095 (already merged, just need the fixes listed below now)

Fixes (that I know of):
https://github.com/tgstation/tgstation/pull/45417
https://github.com/tgstation/tgstation/pull/45418     (this one is for Delta, not sure if we do those manually)
https://github.com/tgstation/tgstation/pull/45813
https://github.com/tgstation/tgstation/pull/45979

**Comment by alexkar598** [comment]
Already ported

**Comment by MegaEmpirical** [comment]
I did miss that, my bad, but what of the subsequent fixes?
