### ISSUE TITLE
Atmos substation above the disposals starts connected to station

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6774]
![image](https://user-images.githubusercontent.com/36208065/65840939-78e5dc00-e2ec-11e9-8cdf-03a246dcea17.png)

All others have a valve and light blue piping (from tank to valve)

**Comment by oklews** [comment]
this was fixed*

It has a valve but the pressure monitor was also broken

**Comment by MegaEmpirical** [comment]
So it seems closing then. Thanks.
