### ISSUE TITLE
SM shard thingy

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#681]
Make the SM shard not do the
_The supermatter shard beeps, "Danger! Crystal hyperstructure integrity faltering."_
over comms when it's on lavaland. Or specify it is on a different z level.

It causes much confusion. Please and thank you.

**Comment by Amelia0010** [comment]
>It causes much confusion.

that's the point.

**Comment by Ktlwjec** [comment]
Yes niclas it was a request
