### ISSUE TITLE
Changelings can't fix eye damage without doing lesser form or making a new body

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6814]
Regeneration which fixes limbs and shit should cure eye damage and such too. I had to use lesser form to fix this, and someone else had to use last resort.

**Comment by ShadowDeath6** [comment]
I think the augmented eye upgrade will automatically heal eye damage

**Comment by MegaEmpirical** [comment]
Is that a one off on acquisition? And even so, wouldn't fix the issue with regeneration.
