### ISSUE TITLE
Possible Bug while building ED-209s?

### ISSUE THREAD

**Issue by Saratoubi** [yogstation13/Yogstation#6840]
Issue reported from  Round ID: 25811 (Yogstation 13)

Reporting client version: 512.1467

While I was building an ED-209 I accidently used the screwdriver twice. After that I couldn't put the cell in to finish the build. Also the crafting table didn't seem to want to work either. I used the body armor and helmets you can get from cargo.

**Comment by oklews** [comment]
You can dismantle what you build, is it possible you screwed the battery port shut? Did you try and screw it again?
