### ISSUE TITLE
Camera naming

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#6843]
"Permabrig Holodeck" camera is separated by name from all the other perma cameras, e.g. "Prison Common Room", "Prison Hallway", etc.

**Comment by alexkar598** [comment]
Care to give extra info?

**Comment by MayhemSailor** [comment]
It’s a naming consistency issue. Most items are labeled prison (cameras, lockdown, etc). I’ll PR a fix shortly.

**Comment by 00aquir** [comment]
yes, it's really just the names. when switching cameras, this makes less sense and the cameras for the same area are at different places on the camera list, which makes it confusing.

**Comment by MayhemSailor** [comment]
There’s actually a ton of them that are off of naming convention, but I’ll get these squared away.
