### ISSUE TITLE
Give disease in View Variables does not work on mobs spawned using game panel

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6853]
I have tried a few of them and nothing.

**Comment by alexkar598** [comment]
Confirmed as non issue

**Comment by MegaEmpirical** [comment]
Specifically only affects mobs spawned by Game Panel

**Comment by redmoogle** [comment]
Tested, it works fine.

**Comment by MegaEmpirical** [comment]
Apparently it's an issue for any spawned with /species in their line. The human without that is fine.
