### ISSUE TITLE
As a headslug (ghost role headslug), I was stuck as a monkey

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6870]
I had no saved transformations and I could not absorb in this form: "We cannot do that in this form!"

**Comment by neeshacark** [comment]
it broken like that, iirc you need to use anatomic paceomamaamam and you fix into homan

**Comment by adamsong** [comment]
Is this still an issue? I don't appear to be able to spawn one in, have they been removed completely?

**Comment by MegaEmpirical** [comment]
The way to get this normally has been removed, though it might still be possible though wizard fuckery and obviously admin stuff. I'll test it later

**Comment by UselessTheremin** [comment]
ghost role headslugs aren't a part of the game at this point, i don't see this at all being an issue currently, if it comes back up again i'll try and fix it
