### ISSUE TITLE
Make laser pointer actually have a chance to work as a laser pointer

### ISSUE THREAD

**Issue by oklews** [yogstation13/Yogstation#6871]
Bro, take the laser pointer from the beam gun and make put it into, the laser pointer.

one of my many glowing brain ideas /s

**Comment by oklews** [comment]
Maybe make it toggleable via multitool or something

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
