### ISSUE TITLE
VV edit assigned value is broken

### ISSUE THREAD

**Issue by ThatLing** [yogstation13/Yogstation#6885]
Step 1: Open VV
Step 2: Go to a list
Step 3: Change assigned value
Step 4: Sigh as nothing happens

**Comment by MegaEmpirical** [comment]
Not a refresh issue? Things usually update for me but I need to refresh.

**Comment by Bibby0110** [comment]
List editing with VV is very finnicky

**Comment by adamsong** [comment]
Cannot reproduce, possibly been fixed
