### ISSUE TITLE
The donator PDA 'pip boy' can be placed in the exosuit slot

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6905]
If you press E (and the ID slot is taken), the PDA will move to the exosuit slot and be invisible (re-open the outfit panel to see it). I was told it can be placed there manually too. The normal PDA does not behave like this.

![image](https://user-images.githubusercontent.com/36208065/66982996-7d005080-f085-11e9-9cf3-55fb5c1a3280.png)

**Comment by oklews** [comment]
Feature

**Comment by Rayisken** [comment]
Pipboy supremacy
