### ISSUE TITLE
Runtime in carbon.dm, line 621: list index out of bounds

### ISSUE THREAD

**Issue by SomeguyManperson** [yogstation13/Yogstation#6911]
/mob/living/carbon/get_permeability_protection(list/target_zones = list(HANDS = 0, CHEST = 0, GROIN = 0, LEGS = 0, FEET = 0, ARMS = 0, HEAD = 0))
	for(var/obj/item/I in get_equipped_items())
		for(var/zone in target_zones)
			if(I.body_parts_covered & zone)
				target_zones[zone] = max(1 - I.permeability_coefficient, target_zones[zone])
	var/protection = 0
	for(var/zone in target_zones)
		protection += target_zones[zone]
	protection *= INVERSE(target_zones.len)
	return protection

**Comment by Bibby0110** [comment]
TG fixed it, port the fix
This is a blob nerf if it get's fixed
