### ISSUE TITLE
You can wear a toy glock in your exosuit or glove slot

### ISSUE THREAD

**Issue by swissloaf** [yogstation13/Yogstation#6914]
## Reproduction: Take a toy glock and put it in your exosuit or gloves slot.

![image](https://user-images.githubusercontent.com/39781787/67137816-b7422d00-f200-11e9-973a-cbc7547ab31c.png)

https://gyazo.com/bd3837afb0c92d31b58b0eb1fd3d5412

**Comment by Mqiib** [comment]
no wait this is okay i like my glockves please don't remove it :(

**Comment by oklews** [comment]
Feature
