### ISSUE TITLE
Add upgraded tools to available engineering cyborg upgrades

### ISSUE THREAD

**Issue by zxmongoose** [yogstation13/Yogstation#6942]
Based on an offshoot discussion in the thread: https://forums.yogstation.net/index.php?threads/engineering-borg-magnetic-gripper.19847/page-2#post-168824

Engineering borgs don't have a crazy amount of upgrades they can get, so I really like the idea of this.

Once upgraded tools are researched by R&D, add modules that replace the basic cyborg tools with power tools (drill, jaws of life, etc.)

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
