### ISSUE TITLE
Chitin plate armor

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#6946]
...or the chitin gauntlet, or the boots.
I don't think they should block melee 100%, yet monsters didn't do any damage to me (except goliath tentacles).

**Comment by SomeguyManperson** [comment]
chitin armor combined with chitin boots and chitin gloves gives 100 melee armor to the arms and legs, you should still take damage to the chest and head but fauna tend to hit limbs for some reason

**Comment by 00aquir** [comment]
okay then
