### ISSUE TITLE
Dullahan welding

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#6964]
It actually doesn't make sense at all, when the body is welding something while the head is FAR away, and the eyes are blinded, so this is a bug report. Dullahans should be able to weld without going blind if the head is further away.

**Comment by MegaEmpirical** [comment]
They can be flashed too.

**Comment by 00aquir** [comment]
flashing.. It would make sense if the dullahan's body could not be flashed when it's **not** holding or pulling the head. If they throw the head somewhere in the vicinity during fight, sec can just go for the head..

**Comment by MegaEmpirical** [comment]
Why was this closed?

**Comment by 00aquir** [comment]
Maybe it was on the line between bug and feature request, but dullahan really shouldn't get blinded if the body is doing the welding, and the head is not even there..
