### ISSUE TITLE
Hermits aren't spawning.

### ISSUE THREAD

**Issue by Silk-Touch** [yogstation13/yogstation#697]
I haven't seen a single one since they were implemented.

**Comment by Super3222** [comment]
I've never seen any of Stealth's new maps spawn in the game. Probably a config problem.

**Comment by Stealthkibbler** [comment]
@Super3222 yeah man, leave it to the council to pretend to remove me from the community but not only fail in doing that, but failing to fix the issue I was raising awareness and complaining about. 

literal shitcunts.

**Comment by Super3222** [comment]
@Stealthkibbler  Ashwalker map is working fine at least but, it's just the other new-er ones which are having problems. I'll try to get help on the matter

**Comment by Cruix** [comment]
For some reason the templates folder does not update from Github on the host machine. I've added all the map files manually.
