### ISSUE TITLE
It would be nice if AIs can always tell which borgs are slaved to it

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6974]
An AI shouldn't have to check the RD console to know which borgs are slaved to it. It should be able to tell in its status tab or something, which currently only shows the number of active borgs.

**Comment by HomocidlePancakes** [comment]
It already has. Status bar lists all of the slaved borgs.

**Comment by MegaEmpirical** [comment]
I will double check but I believe that just lists all borgs

**Comment by HomocidlePancakes** [comment]
It only lists slaved and unslaved emagged.

**Comment by MegaEmpirical** [comment]
Just had a round with one borg around, not slaved to me and shown as connected. So it is showing borgs that are not slaved.

**Comment by HomocidlePancakes** [comment]
It means it was emagged or had lawsync off.

**Comment by MegaEmpirical** [comment]
I can't confirm if its law sync was off but it was not slaved to me.

**Comment by HomocidlePancakes** [comment]
If it wasn’t emagged, then it had lawsync off.

**Comment by MegaEmpirical** [comment]
Borgs with lawsync off can still be slaved.

**Comment by HomocidlePancakes** [comment]
You can’t lock/blow slaved unsynced borgs, and due to that, they won’t show up on the console

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
