### ISSUE TITLE
Can we remove the unstoppable rod as a random event?

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6975]
It's not interactive and just keeps going. It's more annoying and obnoxious than engaging or fun.

**Comment by HomocidlePancakes** [comment]
Can we remove death? It’s not interactive and just keeps going.

**Comment by neeshacark** [comment]
It can keep going, but that rarely happens and only when it hits a perfect spot where it loops over and over. Other times it passes once aand thats1 it

**Comment by MegaEmpirical** [comment]
What's the determining factor?

**Comment by Bibby0110** [comment]
RnG

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
