### ISSUE TITLE
Ahelp's often show the admin as the one speaking instead of the player

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6976]
This is pretty annoying, looks like you're having a conversation with yourself and makes it a bit harder to follow/read through them. Especially when it wasn't your ticket.

(Specifically the Ticket GUI)

**Comment by MegaEmpirical** [comment]
This is still an issue.

**Comment by adamsong** [comment]
This is caused by pop ups

**Comment by ReddicusDragon** [comment]
even with tgui, appears to still be an issue as of 1/12/2023

**Comment by adamsong** [comment]
Fixed by #19041
