### ISSUE TITLE
Can drone chat get a color or some kind of highlight?

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6979]
It's pretty hard to see and is entirely grey.

**Comment by HomocidlePancakes** [comment]
Goonchat has highlighting feature for a reason

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
