### ISSUE TITLE
Bubblegum loot creates mass nonantag grief (!!PRIORITY!!)

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#698]
1. Bubblegum potion drops after killing bubblegum

2. Use

3. Become a nonantagonist with a chainsaw and insane heal factor and red text to kill everyone

4. Everyone starts hallucinating that everyone is a slaughter demon

5. Station descends into mass grief with nonantagonists killing each other with chainsaws

Solution: Remove bubblegum blood rage potion that makes everyone kill each other for no reason.

This is not arguable. It's against the rules for people to kill people while under the effects of this potion since they're still nonantagonists and just invites a shitton of grief, especially considering there's no logigng for someone using it so admins can't tell if someone's lying without some serious var digging.

Disable it or change it's effects, but it CANNOT stay is it currently is.

**Comment by ShadowDeath6** [comment]
might make it so that it has a chance of covering you with blood or turning into a slaughter demon with objectives to kill everyone probably

**Comment by AdamElTablawy** [comment]
that's retarded

can we stop making megafauna loot literally just 'you are antag now, go murderbone'

**Comment by ShadowDeath6** [comment]
currently no megafauna loot does that actually, I guess other than ash drake but even then it's a bit iffy

**Comment by Super3222** [comment]
if we're taking out the bubblegum blood loot, we have to create something well within yogs rules to compensate it.

i'm all for letting miners get special, rare sorts of loot and all but, when it comes to starting mass grief-o-cide on the station, then there's a problem.

**Comment by Alek2ander** [comment]
Just make it give you some sort of lesser bloodtravel spell which makes you take damage while travelling, or something.

**Comment by AdamElTablawy** [comment]
i'd be fine with bloodtravel, makes sense

bloodtravel or summoning a couple of those blood tendrils that help bubblegum out in a fight-slaughterling-who aggro on anyone who hits you

**Comment by ShadowDeath6** [comment]
blood broods are already in the game adam

**Comment by SeikoTheSeal** [comment]
Bubblegums loot is extremely unintresting (minus the spellblade that we didn't port), the potions get old after the first time you use them. If someone comes up with new intresting loot that would replace the current one, cool.

**Comment by ParagonPrime** [comment]
why is forceantag loot such an issue for a megafauna that gets killed maybe once or twice a day by robust players

**Comment by Super3222** [comment]
I'd say:
Slight max health boost from 100 to 115. Might be slightly buggy but, hey. There's a bar drink that raises the max health too. Trust me, no one will notice that someone has 115 health. It's only here so they can last a bit longer than any other crewmember who hasn't drunken from the remains of the king of slaughter demons.

Lesser bloodtravel. Similar to Slaughter Demons, but the more you're in the blood the more you suffocate. It'll build up until you travel out of the blood. Cannot drag people into the blood. After 3~ minutes of being in the blood, your body will travel to the blood you traveled through (or at least on top of the turf). instantly calling the death proc (I was initially going to go for disintegrate but, this is suppose to be a REWARD).

Summon Bloodbroods. What Adam said, they are only reactionary to whoever hits the user or a bloodbrood in general.

Healing factor - as good as the one we have now

**Comment by ShadowDeath6** [comment]
you can already get blood broods from legion souls

**Comment by AdamElTablawy** [comment]
@ParagonPrime Because it's more grief work for admins and I don't like it.

**Comment by Super3222** [comment]
oh and the chainsaw they can call/recall can't forget about that shit

**Comment by ShadowDeath6** [comment]
Close dis >:^(
