### ISSUE TITLE
Atmos log doesn't log the contents of a canister

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6980]
It shows you in in-game chat, which is logged in the game log not in the atmos log proper.

**Comment by HomocidlePancakes** [comment]
Doesn’t already log contents whenever the canister is open? Might be talking out of my ass here, but I am not sure.

**Comment by MegaEmpirical** [comment]
Maybe it's logged in a different place but in the atmos log it doesn't list the contents, which we are alerted about in-game.

**Comment by adamsong** [comment]
It is currently logged both in the admin chat log as well as the regular admin log

**Comment by MegaEmpirical** [comment]
I awe wahy you're referring to and that's on me but I meant specifically in the atmos log.  Going to edit it to reflect that and re-open it, close it again if you think the game log is sufficient. 

EDIT: I don't need to edit it, I did say atmos log.
