### ISSUE TITLE
Spaceloops delete gas contents, sometimes causing severe SM issues and delaminations.

### ISSUE THREAD

**Issue by ghost** [yogstation13/Yogstation#6986]

**Comment by ghost** [comment]
Yes Nichlas, it occurs above temperatures of 22,7K, seen it happen just 2~3 hours ago on a round where 3 very good atmosians were collaborating on the same engine. We were _very_ sure it was a bug since all of us knew the setup design by heart (we collaborated on its design) and could not be attributed to human error, it happened thrice as well.

**Comment by adamsong** [comment]
Is this still an issue? I have not heard anything about it and its been open a while for what would be a game breaking bug.

**Comment by adamsong** [comment]
Cannot reproduce, This would be a gamebreaking bug yet it has been open for two years with no confirmation. Closing.
