### ISSUE TITLE
Hostile environment preventing shuttle leave ended while hostile environment was still active

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#6990]
Xenos, shuttle couldn't leave, but then it said later on that hostile environment was over but it wasn't It was near that 1:48 (h:mm) so it may have had some kind of conflict with the shuttle call at end?

**Comment by MegaEmpirical** [comment]
Round 26171

**Comment by SomeguyManperson** [comment]
if this was with xenos the queen causes a 30 minute hostile environment so the shuttle doesn't just get called and leave the second someone sees a stray larva.
