### ISSUE TITLE
Plasma objective not working

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#6994]
## Round ID:

26184

## Reproduction:

stole 4 tanks of plasma (~32 mol) 
![sFyCh1W](https://user-images.githubusercontent.com/28408322/68075787-094b8c80-fd83-11e9-9ae0-e16800c182f3.png)

**Comment by oklews** [comment]
It looks for one really full plasma can I think

**Comment by SomeguyManperson** [comment]
It checks your inventory for singular full tanks
