### ISSUE TITLE
Changelings last resort

### ISSUE THREAD

**Issue by SpaceSlug2** [yogstation13/Yogstation#6995]
## Reproduction:

 Last Resort doesn't work and instead just doesn't do anything when you hit yes dooming you to die when you really need it and it doesn't even give you the option when you're dead even though it's suppose to which irks me since I died trying to last resort

**Comment by HomocidlePancakes** [comment]
Hello? Punctuation? Ever heard about that? Pretty useful if you don't want to sound like a retard.
