### ISSUE TITLE
Porting our jobs

### ISSUE THREAD

**Issue by utahclock** [yogstation13/yogstation#7]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by utahclock** [comment]
should be done tomorrow its about 92% done

**Comment by oisin100** [comment]
Damn, 92%? That's very exact.

**Comment by utahclock** [comment]
#30
