### ISSUE TITLE
Initialization errors

### ISSUE THREAD

**Issue by alexkar598** [yogstation13/Yogstation#7006]
## Round ID: local testing
Path : /mob/dview 
- Didn't call atom/Initialize()

Path : /mob/living/simple_animal/hostile/retaliate/goat/tiny 
- Didn't call atom/Initialize()
- Didn't return an Initialize hint

Path : /obj/structure/closet/bluespace/internal 
- Didn't return an Initialize hint

Path : /obj/item/implanter/mindslave 
- Didn't return an Initialize hint

Path : /obj/structure/closet/crate/freezer/blood 
- Didn't return an Initialize hint

Path : /obj/machinery/computer/arcade/minesweeper 
- Didn't return an Initialize hint

Path : /obj/structure/closet/secure_closet/freezer/meat 
- Didn't return an Initialize hint

Path : /obj/structure/closet/secure_closet/freezer/fridge 
- Didn't return an Initialize hint

Path : /obj/structure/closet/secure_closet/freezer/kitchen 
- Didn't return an Initialize hint

Path : /obj/structure/closet/secure_closet/freezer/kitchen/maintenance 
- Didn't return an Initialize hint

Path : /obj/structure/closet/crate/freezer 
- Didn't return an Initialize hint

Path : /obj/structure/guncase/shotgun 
- Didn't return an Initialize hint

Path : /obj/structure/closet/secure_closet/freezer/cream_pie 
- Didn't return an Initialize hint

Path : /obj/structure/closet/crate/freezer/surplus_limbs 
- Didn't return an Initialize hint

Path : /obj/machinery/rnd/production/protolathe/department/science 
- Slept during Initialize()

Path : /obj/machinery/computer/atmos_sim 
- Didn't return an Initialize hint

Path : /obj/structure/spacepoddoor 
- Didn't return an Initialize hint

Path : /obj/structure/closet/secure_closet/freezer/fridge/open 
- Didn't return an Initialize hint

Path : /obj/structure/closet/crate/critter/exoticgoats 
- Didn't call atom/Initialize()
- Didn't return an Initialize hint

Path : /obj/structure/closet/bluespace/external 
- Didn't return an Initialize hint

Path : /obj/structure/closet/secure_closet/freezer 
- Didn't return an Initialize hint

**Comment by Bibby0110** [comment]
feature

**Comment by adamsong** [comment]
Has this been resolved?
