### ISSUE TITLE
important lavaland change for balance

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#701]
make chasms play the looney tunes falling sound when you step in one to slightly alleviate salt with fond childhood memories of YAWAHOOEY

**Comment by ParagonPrime** [comment]
no, play this instead

https://youtu.be/1ytCEuuW2_A

**Comment by timkoster1** [comment]
Adam, if you give me a link to the sound, I will go ahead and do the rest.

**Comment by Super3222** [comment]
^

**Comment by Super3222** [comment]
@timkoster1 @AdamElTablawy MAKE IT HAPPEN
