### ISSUE TITLE
Slimes can only move through pipe layer adapters when moving to layer 2, never from.

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7010]
Unsure if this applies to other vent crawlers. Makes it so you get stuck in atmos.

**Comment by MegaEmpirical** [comment]
True for swarmers too. I hate you people.

**Comment by JamieD1** [comment]
@MegaEmpirical Non Issue, if you are stuck go onto the layer manifold and press left and right to select which pipe you want to go through.

**Comment by MegaEmpirical** [comment]
.... You fucking serious? Closing, thanks.
