### ISSUE TITLE
Opening windows sometimes makes you unable to move

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7020]
Pressing control fixes this but it keeps happening. 

Seems related to: https://github.com/yogstation13/Yogstation/pull/7001

**Comment by Amelia0010** [comment]
@monster860

**Comment by 00aquir** [comment]
I clicked the (F) in chat to follow a ghost, same thing happened. had to press ctrl. Otherwise it happened sometimes when using R&D console/fabricator.

**Comment by Amelia0010** [comment]
Any more steps to reproducing it, because I couldn't do it using either RnD consoles or the (F) in chat?

**Comment by MegaEmpirical** [comment]
It seems somewhat random. I've had it happen while opening a sleeper. The first time I heard of it, a guy hid in a locker and looked at his uplink. It doesn't always happen with the same action.
