### ISSUE TITLE
Can all logs associated with a player be tied to their client and not their mob please?

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7022]
This will make checking things during a round a lot less of a pain in the ass. Goose says it used to be like this too?

**Comment by alexkar598** [comment]
It already is, if you go in PP and LOGS there are options for mob logs and client logs

**Comment by MegaEmpirical** [comment]
Except client logs don't show me everything that client has done.


EDIT: I'll double check tonight to make sure I'm not insane.

**Comment by MegaEmpirical** [comment]
I figured the issue I have: When the client disconnects from the server, there is no longer a client to pull logs from.  Is there something we can do about this?

**Comment by Rayisken** [comment]
I have an open ticket re this a couple of months ago

Make D/C'd player logs easier to obtain #5039

**Comment by MegaEmpirical** [comment]
Nice, closing this then.
