### ISSUE TITLE
Dragging a securitron into lava spawns infinite components, lagging the server horrifically

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation#703]
Dragging a securitron into lava ends up dropping an infinite amount of its components, while not destroying the bot itself. This does not apply to any other bots, including medibots, floorbots, or ED-209.

It nearly forced a restart. This is a critical bug, as beepsky spawns at labor and could be dragged there in an instant to force server lag.

**Comment by EMT321** [comment]
Additionally, it crashed the server at round-end. This is an easily abusable, server breaking bug.

**Comment by tromacodes** [comment]
This was reported, fixed, and must have had it's fix removed with an update recently. The fix should be in an older server pack
