### ISSUE TITLE
Meta signal techs are kind of fucked

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7030]
Tcomms on meta is on the AI sat, that requires you to go through a room with turrets, there may also be a bolted door or two (cannot recall if it is by default).

The AI has to let them out, or someone with access has to come over, or they have to start busting out the tools and getting creative.

Not sure what the best way to fix this is. Easiest seems to be to put a turret control in their room and give them access to that one and the ones by the entrances.

**Comment by HomocidlePancakes** [comment]
Siggytechs exist to suffer.

**Comment by Ktlwjec1** [comment]
https://github.com/yogstation13/Yogstation/pull/7205
