### ISSUE TITLE
Ports over Adam's species reworks

### ISSUE THREAD

**Issue by Smudged** [yogstation13/Yogstation#706]
https://github.com/yogstation13/yogstation/pull/853

Once previous yog races are implemented, this might be a good place to continue

**Comment by ghost** [comment]
why do you think we would implement our previous, terrible races

**Comment by Smudged** [comment]
because the current tg races are boring and terrible, so we add our terrible races and it fixes itself, being a lizard in rebase is just being a human with claws, it's terrible and your changes reaally show how much it's needed

**Comment by ghost** [comment]
my changes were abysmal and our races were boring and terrible

phytosians were literally just podpeople, so all i did was add shitty bonus chems to them for no particular gain

preternis were just fucking awful entirely

lizards were still humans with claws

**Comment by Smudged** [comment]
Yeah, but at least lizards were human with snowflake eye condition, speed nerf, vulnerability to radiation etc. 
Phytosians with the ability to fart language, some of what was changed was nice or well, I got used to 'em

**Comment by ghost** [comment]
languages are better now

**Comment by Smudged** [comment]
Well atleast we'd get phytosians with the ability to fart which'll just add another language, and the temperature changes that you made with Phytosians being weak to the cold and having snow flake temp differences so that cryo can kill them which actually makes them different from pod peoples, I dunno I like'em, it might not be exactly "Adam's Race Reworks" But hopefully aspects will be added and tweaked.

**Comment by ThatLing** [comment]
I already added the phytosian tweaks and adding their shitty fart language requires too much work so I dropped it.
