### ISSUE TITLE
Can we get a way to mute Discord OOC server side

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7082]
It even bypasses global mute, and it can get pretty annoying when you have OOC muted locally and there is a whole conversation happening.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
