### ISSUE TITLE
You have to reload to see the visual to solve sliding block puzzles

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7094]
As title says, it's kind of annoying.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)

**Comment by adamsong** [comment]
I'm pretty sure this has been fixed, you are talking about things like with the puzzle smite right?

**Comment by MegaEmpirical** [comment]
No idea. Yes.

**Comment by adamsong** [comment]
I've never seen it not work, and this is an old issue, it was probably fixed along the way
