### ISSUE TITLE
I Want To Be The Port : Shadowlings

### ISSUE THREAD

**Issue by X-TheDark** [yogstation13/yogstation#71]
I'll take a look at shadowlings, if noone minds.

**Comment by FluffySurvivor** [comment]
Remove slings pls

**Comment by X-TheDark** [comment]
Is there anything wrong with them, @FluffySurvivor ? If so, I'd like to hear it, as I don't play alot these days (and have, in fact, to this day, never played a primary roundstart antag ever).

**Comment by timkoster1** [comment]
Ignore fluffy, shadowlings r awesome

**Comment by X-TheDark** [comment]
Ready to be merged.
