### ISSUE TITLE
Change the surrender text

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7110]
I thought the color change/wobbling would act up for like 2 or 3 seconds and stop, not keep going.

Either make it a consistent thing like everything else or make it stop after a couple of seconds.

**Comment by Reed0506** [comment]
i can confirm that its extremely fucky. the point of the intensity is probably to get sec to not beat you after you surrender but its just way too much. also simple mobs can spam it.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
