### ISSUE TITLE
Dry wet leather in lava!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#7124]
- Let the actual lavaland people who start there make goliath cloak, where it should be created. Also, you cannot dry wet leather for it while it's burning in lava, which is just wrong.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
