### ISSUE TITLE
Bring sec locker back to offices

### ISSUE THREAD

**Issue by Hydre** [yogstation13/yogstation#713]
So I'm not sure if this is a bug or if it was intended (in which case shame on the person who thought it was a good idea) but the lockers in the department security offices are basic bland lockers with nothing in them.

Put back the normal sec lockers instead.

**Comment by tromacodes** [comment]
Security.dm lines 116 to 122 . It's an easy change.
 I would like to see taser guns in them too

**Comment by timkoster1** [comment]
Honestly, tasers are OP. Having them laying around like that is bad IMO

**Comment by AdamElTablawy** [comment]
tazers are armory weapons and stay in the armory.

sec lockers are supposed to be in sec so that security has to go to sec and therefore be seen by other sec and spend some time gearing to do their jobbos

**Comment by X-TheDark** [comment]
I guess this sort of makes sense since officers don't spawn in the department security offices anymore.
Perhaps we should remap security offices into something useful/remove them.

**Comment by EMT321** [comment]
Do officers actually spawn in brig? I feel like they still spawn in their departments.

**Comment by timkoster1** [comment]
They spawn in department offices.

**Comment by X-TheDark** [comment]
Right, that was supposed to have changed in https://github.com/yogstation13/yogstation/pull/417...

**Comment by Super3222** [comment]
Act 7: The Final Chapter on Merge Conflicts is coming soon to a JEXP PR near you, so expect being able to coordinate with the team as a HoS after it's merged.

But, switching sec lockers out for those useless ones will have to be in another PR. JEXP is already bloated with (sec wise) features.
