### ISSUE TITLE
Consciousness transference potion does not stop mob actions

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#7138]
I transferred myself into a goldgrub for fun, but quickly died after it because the game did not stop the goldgrub from burrowing, thus disappeared.

**Comment by adamsong** [comment]
Cannot reproduce

**Comment by ReddicusDragon** [comment]
As of June 30, 2021 Adamsong could not reproduce. If this is an issue in the future, feel free to re-open this issue.
