### ISSUE TITLE
sentient disease adaption menu not working

### ISSUE THREAD

**Issue by overlord12345** [yogstation13/Yogstation#7143]
Issue reported from  Round ID: 26491 (Yogstation 13)

Reporting client version: 512.1488
no idea why this happend so i hope it gets fixed

**Comment by HomocidlePancakes** [comment]
Dude, no round ID, no screenshots, no nothing. “doesn’t work” can’t be interpreted in a lot of different ways. Did it freeze? Were the buttons not working? Did the menu refuse to load? Detail your stuff, bud.

**Comment by overlord12345** [comment]
> Dude, no round ID, no screenshots, no nothing. “doesn’t work” can’t be interpreted in a lot of different ways. Did it freeze? Were the buttons not working? Did the menu refuse to load? Detail your stuff, bud.

well the round ID is there i think you just dident see it. The details are that the menu button dident work and the window dident show up.

**Comment by MegaEmpirical** [comment]
Did you try to relog?

**Comment by redmoogle** [comment]
I dont see this issue happening. Remake/reopen if it keeps happening _with more details please_

**Comment by MegaEmpirical** [comment]
ISSUE IDENTIFIED

**Comment by Readystorm546** [comment]
WOOH ISSUE IDENTIFIED THANKS TO THEOS. The disease made a null issue causing the menu not to open. Removing nulls will fix it. or something ask theos

**Comment by adamsong** [comment]
Did theos fix it or just identify it?

**Comment by MegaEmpirical** [comment]
No idea

**Comment by redmoogle** [comment]
> Did theos fix it or just identify it?

Last I checked fixed iirc it had to do with nulls in something

**Comment by adamsong** [comment]
This has apparently been fixed
