### ISSUE TITLE
Swarmers can accidently murder people

### ISSUE THREAD

**Issue by Sir-Lagsalot** [yogstation13/Yogstation#7157]
Issue reported from  Round ID: 26520 (Yogstation 13)

Reporting client version: 512.1488

So it turns out, according to Theos at least, that windows are considered a "safe" place for swarmers to teleport you. This resulted in the unfortunate scenario where I got teleported to one of the plasma windows next to the singularity, which proceeded to suck me into space and juggle my corpse off the containment field until it had smashed open the particle accelerator windows.
![image](https://user-images.githubusercontent.com/52263717/69591391-9d92c300-0fc0-11ea-9ea5-ef77ef2e9880.png)
In the image above, my ghost is positioned above where the swarmer teleported me.

**Comment by alexkar598** [comment]
Making this safer would be annoyingly hard and this is rare enough that when it does happen, its just bad luck
