### ISSUE TITLE
Blank PDA

### ISSUE THREAD

**Issue by dingdog7** [yogstation13/yogstation#716]
So whenever I touch someones PDA it corrupts I dont know why

**Comment by timkoster1** [comment]
I think you liked the ckey? Or it could be your name irl.
Further on, that's a really weird bug, could you describe the situation and what happened more precise?

**Comment by ParagonPrime** [comment]
>when time doesn't understand sentence splitting

he knows why his ckey is his ckey >:v

**Comment by AdamElTablawy** [comment]
We're looking into it. Whenever he uses ANY PDA, it automatically blanks out and stops working, the only button being 'refresh.'

**Comment by AdamElTablawy** [comment]
It happens to everyone serverwide, not just a visual issue on his side. He used my PDA, gave it back, it blanked out as well for me too.

**Comment by dingdog7** [comment]
Sorry I wasent speaking clearing cache broke my entire game.
