### ISSUE TITLE
Feature Request: Brain Damage Leads to Memory Loss

### ISSUE THREAD

**Issue by GenericDM** [yogstation13/Yogstation#7164]
Currently, there is no real consensus on whether dead borgs being repaired falls under clone memory disorder. This could be remedied by having a system in place to have an IC message (either directed towards the player immediately, or when they next enter their body) stating that their brain has been damaged enough to prevent them from remembering anything leading up to or involved in their death. Depowered/destroyed borgs could take brain damage over time, which would be increased by physical trauma to the chassis. This would also take place with normal brain damage.

**Comment by MegaEmpirical** [comment]
Sounds like a rule issue.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
