### ISSUE TITLE
Shuttle left with a living queen xeno on the station

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7242]
Not sure if it's because they used early launch or what.

Round: 26647

**Comment by SomeguyManperson** [comment]
If the queen was alive for more than 30 minutesit ends the hostile environment

**Comment by MegaEmpirical** [comment]
I never saw a hostile environment announcement. I'll re-watch today to confirm.

**Comment by SomeguyManperson** [comment]
The hostile environment announcement only shows up if the shuttle is prevented from leaving by it

**Comment by Hopekz** [comment]
Confirming that it was more than 30 minutes before it left. This can be closed.

Replay:
https://yogstation13.github.io/demo-viewer/?roundid=26647#18213;163.50;99.50;2;dareb

**Comment by MegaEmpirical** [comment]
Thanks.
