### ISSUE TITLE
Canceling after clicking "Unleash Floor Cluwne" still spawns a floor cluwne

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7243]
As title.

**Comment by CMOisLing** [comment]
Feature

**Comment by alexkar598** [comment]
Feature request, clicking cancel spawns it without a target

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
