### ISSUE TITLE
shit load of bugs

### ISSUE THREAD

**Issue by boodaliboo** [yogstation13/Yogstation#7244]
names of files that are <> in modular computers that are printed destroy chat and can also be used to make a papers contents be stuck in chat box

if a slime attachs to you you can fulton it infinetly

ghosts can buckle people to borgs

miners orebags that spawn in there bags roundstart pick up ores till there full then put more in your backpack

**Comment by adamsong** [comment]
In future, please report different bugs in different issues, so they can be tracked separately

As it stands, 
Bug 1 - Not sure how to make custom named files in a modular computer, possibly removed
Bug 2 - I do not understand what you mean, are you referring to the fulton pack that miners get?
Bug 3 - Working on a fix
Bug 4 - Already fixed

**Comment by adamsong** [comment]
The PR fixes bug 3, if bugs 1 or 2 are a problem, please make them their own issues.

**Comment by boodaliboo** [comment]
> The PR fixes bug 3, if bugs 1 or 2 are a problem, please make them their own issues.

i made this 2 years ago
