### ISSUE TITLE
MISSION CRITICAL: Santa's sack doesn't generate presents!!!

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7250]
Says he can see into them but he can't!

**Comment by MegaEmpirical** [comment]
Santa's heavy sack doesn't generate presents like it says it does! It does start with a few though.

**Comment by Potototatoh** [comment]
the sky is falling

**Comment by MegaEmpirical** [comment]
Some of these issues were resolved by: https://github.com/yogstation13/Yogstation/pull/7363

However, Santa still cannot see what a present contains.

**Comment by MegaEmpirical** [comment]
My god this might finally be fixed now with beta 513.
