### ISSUE TITLE
Tendrils "on top of each other"

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#7257]
- they can be crammed together so close they almost touch, and one takes the other tendril down with them.

**Comment by Hopekz** [comment]
**feature** 
![635161772642271233](https://user-images.githubusercontent.com/24533979/70395686-e7b77380-19c6-11ea-830a-8ba76270cde1.png)

**Comment by SomeguyManperson** [comment]
just get good B)
