### ISSUE TITLE
Cannot purchase food with space cash

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#7258]
- If physical money, bills are convertible for IDs, at least let's make it possible for anyone with coins/bills in their hand to purchase food from vendors without ID card.

**Comment by MegaEmpirical** [comment]
Your money is no good here.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
