### ISSUE TITLE
Metastation distroloop is not connected to atmospherics

### ISSUE THREAD

**Issue by Jarod1200** [yogstation13/Yogstation#7264]
https://i.imgur.com/BQf4LYd.png

This layer adapter is bugged somehow and the distro loop is not connected to main atmospherics. I noticed this when I tried to put extra air in from atmos to fix a hull breach and the distro loop was not getting any air so I traced the problem to this layer adapter. I also could not unwrench it so I destroyed it with a jaws of life and replaced it with a new layer adapter which fixed the issue. 

This happened 2 shifts in a row:
26670
26671

**Comment by Ktlwjec1** [comment]
Should be fixed now, let me know and I'll reopen this if it's not.
