### ISSUE TITLE
OOC chatbox sends to OOC when the no option is selected

### ISSUE THREAD

**Issue by Hopekz** [yogstation13/Yogstation#7266]
![image](https://user-images.githubusercontent.com/24533979/70366668-a73ce600-185e-11ea-9032-82692af450df.png)

## Reproduction:

![image](https://user-images.githubusercontent.com/24533979/70366676-b3c13e80-185e-11ea-951a-e4f0d5e3e6d4.png)

**Comment by alexkar598** [comment]
Failed to reproduce issue

**Comment by Hopekz** [comment]
Unable to reproduce for me too.
I don't even get a box saying "are you sure you want to send this in OOC" message which makes me think we're both testing for this wrong.
Not even sure where that prompt shows up. Word filter maybe?
