### ISSUE TITLE
rapid protein synthesis causes preternis to become incurably hungry for real food

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#7275]
Issue reported from  Round ID: 26684 (Yogstation 13)

Reporting client version: 512.1488

Rapid protein synthesis still heals injured preternis, and still makes them hungry in return. I implanted myself with a nutriment pump PLUS and gorged on holoapples, and I was still starving. It doesn't seem to actually do anything to me other than _you feel less hungry..._ spam for the rest of my natural lifespan. I also lost exactly 18% blood and never recovered it for reasons I couldn't figure out.
![image](https://user-images.githubusercontent.com/36427443/70379153-e61e7a80-18f6-11ea-9316-a8bbdb856c41.png)
Also of interest, a preternis with regenerative coma at a low enough health threshold to trigger it is effectively dead. They collapse repeatedly without healing, too quickly to self-repair or scream.

**Comment by alexkar598** [comment]
The not healing with regenerative comma is intended, preternis cant heal from normal sources

**Comment by alexkar598** [comment]
Could you give a clear list of steps in order to reproduce this issue?

**Comment by Sniblet** [comment]
I got infected, took some random damage here and there, realized I was healing from it, decided to make use of it by working in space, and my hunger suddenly burst into existence and then crashed while I was outside and I stopped healing

**Comment by MegaEmpirical** [comment]
Feature.
