### ISSUE TITLE
BIG PROBLEM: Changeling Chitin armor has no sprite, causing them to become invisible and thus extra unkillable

### ISSUE THREAD

**Issue by ghost** [yogstation13/Yogstation#7279]
## Reproduction:
Dunno, I was a mentor and some poor player who got powergamed mhelp'd it. I suppose regular activation of chitin armor works?

**Comment by MegaEmpirical** [comment]
Well, that's fucked.

**Comment by GenericDM** [comment]
Ling in question said it has something to do with growth serum when bonked

**Comment by nesisknesis** [comment]
growth serum making mobs invisible was fixed, so ill assume this has also been fixed
