### ISSUE TITLE
Entering values in-game

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#7285]
There should be < and > buttons for decreasing and increasing values because if you want to use or test increasing values step-by-step, it is tiresome to always do click, write, enter, click, write, enter, click, write enter... in other places it would be similarly faster, like going through radio frequencies which can only end in odd numbers anyways.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
