### ISSUE TITLE
Deleting the nuke disk causes it to move to a new location

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7297]
I had a duplicate nuke disk I was dealing with and wanted to remove it from play to avoid any issues. Game told me to fuck off when I tried to deleted it and instead moved it elsewhere.

I think it more accurately made a new one in a random location on the station instead of moving the one I deleted.

**Comment by Amelia0010** [comment]
You're gonna need to call the delete proc with the force argument. If the nuke disk didn't respawn when deleted, you'd have a lot of issues with bombs and shit

**Comment by alexkar598** [comment]
Other option is giving admins an option to force delete whichever brings problems of its own

**Comment by MegaEmpirical** [comment]
Didn't realize delete and explosives worked the same way. Thanks for the info.
