### ISSUE TITLE
Have the ability to customize your antagonist character, for example, a nuclear operative.

### ISSUE THREAD

**Issue by Xoxeyos** [yogstation13/Yogstation#7308]
Have a character menu for your antagonist.

**Comment by monster860** [comment]
"Hey look it's antag mcantagface, he's always an antag, LYNCH!"

I mean I guess if you want to screw yourself over that's fine though.

**Comment by Xoxeyos** [comment]
> 
> 
> "Hey look it's antag mcantagface, he's always an antag, LYNCH!"
> 
> I mean I guess if you want to screw yourself over that's fine though.

Might make people fuck off if they're robust enough, though I was thinking for having this for more of a team mode, like nuke ops, or cult. 

I got the idea from here. 
https://old.reddit.com/r/SS13/comments/e8se9j/meet_my_brickhouse_shaped_syndicateloving_izak/

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
