### ISSUE TITLE
Changeling adapt menu no longer shows how many re-adapts you have

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7309]
Used to tell you in the top right corner near the re-adapt button, now no more.

**Comment by MegaEmpirical** [comment]
Apparently re-adapts are not stored either? So I have to absorb someone after adapting to get a new one.

**Comment by adamsong** [comment]
If the re-adapts are stored this seems intentional, requiring lings to reabsorb before re-adapting again.

**Comment by MegaEmpirical** [comment]
It only stores one now and I never found a PR that changed how it worked

**Comment by adamsong** [comment]
From a quick look through the history, it seems lings were never able to store multiple respecs

**Comment by MegaEmpirical** [comment]
Closing since this just seems to be how it is now.
