### ISSUE TITLE
Free Miners no longer have Free Miner Asteroid

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#7314]
Was the ruin intentionally removed? This means the Free Miners can be left without anything to mine. Previously, whenever Free Miners were available as a ghost role, the "Free Miner Asteroid" ruin would spawn as a guaranteed dock to fly to. (Available docks to can be checked as a ghost by simply clicking the Free Miner Ship Console)

![Free Miner Asteroid gone](https://user-images.githubusercontent.com/18729830/70681191-2b78da00-1c60-11ea-82f3-cf8c18a4a2f6.png)

**Comment by SomeguyManperson** [comment]
It spawns seperately for some reason and isn't a garunteed spawn

**Comment by CrazyDrakkon** [comment]
I'm sorry I don't know when this started happening, but there's definitely a difference. It would always spawn with them before but I've never seen it since I've noticed this.

**Comment by Hopekz** [comment]
So freeminers have a % chance of having no purpose in life

**Comment by CrazyDrakkon** [comment]
![Free Miner bad](https://user-images.githubusercontent.com/18729830/71300652-6d8ad580-235c-11ea-8c86-449127f56ef0.png)

**Comment by alexkar598** [comment]
fuixed
