### ISSUE TITLE
"The immovable DUCKs in Centcom Testing trigger ghost auto-follow debris"

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#7318]
Auto-follow debris annoyance still present since an issue was made by Sniblet in June.
https://github.com/yogstation13/Yogstation/issues/6058#issue-459630896

**Comment by Xoxeyos** [comment]
It's been like this forever, I wish somebody would fix it.

**Comment by MegaEmpirical** [comment]
So you made a bug report for an already existing bug report?

**Comment by CrazyDrakkon** [comment]
> 
> 
> So you made a bug report for an already existing bug report?

I don't do github except the occasional yogs issue, don't know how bumps work or if they're okay. Don't hurt me.
