### ISSUE TITLE
Unopress omega station tcomms or im gonna be not happy :(

### ISSUE THREAD

**Issue by gilvian** [yogstation13/Yogstation#7321]
Most of that things dont matter since its about a map

![image](https://user-images.githubusercontent.com/13832819/70821523-97338200-1ddb-11ea-8cd3-b169f08f3456.png)

1. AI has only one camera and its in the corner, to get access to stuff above it has to open the blue marked door.

2. The yellow console only shows common record

3. Top Red console has set Null as default instead of tcommsat

4. Bottom red console dosent work, it should be for scripts but dosent even accept the ID card

Also you die in the machine part even with the hoodie and internals on so :(

**Comment by Lostlarry** [comment]
the yellow console shows only common server because there is only common server it will show more if you make them and connect them
i this case common server all frequencies
