### ISSUE TITLE
Box air alarm fuckery

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7322]
Box map.

The Telecomms Control Room air alarm is duplicated in Telecomms Tech Storage and in Telecomms Access. Instead of each being independent.

Server room access has no air alarm of its own.

and the weirdest: The telecomm sat entrance's air alarm is labeled "Telecomms Teleporter Air Alarm" and the actual teleporter room as no air alarm.

While we're at it, can we just make the vents that are siphoning scrubbers?

**Comment by Lostlarry** [comment]
well the fact that there are multiple air alarms is nothing new since medbay has even more of them and it is pain to differentiate them at first.
also making the vents into scrubbers is a bad idea since scrubbers would just try to siphon the room or do absolutely nothing with vents you can control when they turn on

**Comment by MegaEmpirical** [comment]
It has multiple IDENTICAL air alarms.


I'm pretty sure the drain vent is just doing normal siphon, the pka above is barely hovering above 0.

**Comment by Lostlarry** [comment]
it is survivable also the server room has air alarm

**Comment by MegaEmpirical** [comment]
I wasn't arguing against either of those points.

**Comment by Lostlarry** [comment]
having them as independent rooms with separate air alarms would also mean that each needs an APC

**Comment by MegaEmpirical** [comment]
Good point, I forgot about that. So now that I have looked into it:

The front of the satellite with the tube has an air alarm and no APC.

The teleporter room has an APC and no air alarm.

(These two rooms are apparently the same for some reason)

The central most room has no APC but an air alarm and is the same room as the control room.

Tech storage has an air alarm and no APC.


So clearly an APC is not needed. Though I am not against the idea of having APCs added to the rooms missing them or having some rooms linked together. Such as the control room and central room.

**Comment by MegaEmpirical** [comment]
Closing since telecomms got reworked. I assume these issues did not persist through
