### ISSUE TITLE
Fucky teleport locations

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7323]
Not in the room but the damn hall.

Transfer center puts you in the execution room (which may or may not be exposed to space).

I'll add more as I'll find them.

**Comment by ghost** [comment]
Stupid bot.

Also transfer center is execution room.

**Comment by MegaEmpirical** [comment]
I already said that and it is still technically correct.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)

**Comment by patpol4** [comment]
It's all area based, pretty hard to fix

**Comment by adamsong** [comment]
With what method of teleportation are you using?

**Comment by MegaEmpirical** [comment]
I believe it was either a scroll or spell, wizard stuff.

**Comment by adamsong** [comment]
That just picks a random turf in the area, this is the same as #5305

**Comment by MegaEmpirical** [comment]
Other issue conversation suggests a way to blacklist tiles for teleporting

**Comment by adamsong** [comment]
The suggestion is make the tanks a separate area, and then not allow teleporting to that area, this is not a viable solution for every area.

**Comment by patpol4** [comment]
"danger" children for the areas this is affected by

**Comment by MegaEmpirical** [comment]
Why was this closed?

**Comment by adamsong** [comment]
It was fixed

**Comment by MegaEmpirical** [comment]
Ahh fucking nice
