### ISSUE TITLE
Pressing ghost while in the cloning pod cancels your cloning.

### ISSUE THREAD

**Issue by Saratoubi** [yogstation13/Yogstation#7328]
## Reproduction: Once you are dead and your body is being cloned, pop into the cloning pod, got to OOC, hit ghost, and your newborn unfinished naked body falls out of the cloner dead as a doornail.

See above

**Comment by MegaEmpirical** [comment]
Hmm I'm okay with this. Makes it so they don't waste time cloning you.

**Comment by Hopekz** [comment]
Feature 
![635161772642271233](https://user-images.githubusercontent.com/24533979/70855311-8d1e8b80-1e8e-11ea-8ee5-41f865fb3f74.png)

**Comment by MegaEmpirical** [comment]
That's also just how ghost works.
