### ISSUE TITLE
YogsMeta Psych shutters

### ISSUE THREAD

**Issue by Hopekz** [yogstation13/Yogstation#7337]
**The Psychiatrist doesn't have access to his own shutter button on YogsMeta.**

## Reproduction:
![image](https://user-images.githubusercontent.com/24533979/70853237-e7a8ef00-1e70-11ea-96b9-8f590f579be9.png)
Fly into YogsMeta. 
Be Psych. 
Go to your office. 
Don't have access to your own button. 
Cry. 
Space yourself. 
Get bwoinked for spacing yourself as non assistant. 
Get banned for saying nothing in life matters anymore because you can't have access to your button. 
Become depressed thinking about this. 
Space yourself in real life. 
Get bwoinked by god for SD'ing as human.
Get banned from heaven.
Go to hell.
The button is already waiting for you. 
You can press it over and over and it won't work.
Access Denied.
Access Denied.
The button is stationary but takes up 15% of your hell office wall space.

**Comment by MegaEmpirical** [comment]
Fix this issue and ban this man.
