### ISSUE TITLE
Space bus ruin was constantly spitting out errors non-stop once someone landed on it

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7351]
Round: 26832

Someone landed on it with a space pod, not sure if this was a factor but the spam would not stop.

Kept spitting out this shit: 

ADMIN LOG: Space turf(s) at Unexplored Location (122, 115, 4) (JMP) is connected to planetary turf(s) at Unexplored Location (122, 126, 4) (JMP)!

Slight variations in coords.

**Comment by Rayisken** [comment]
Deleting the associated turf in the log seems to cause it to bounce it around?

**Comment by monster860** [comment]
so what happened is that the spacepod dude mined out the ash rock, spawning lavaland turfs in space.
