### ISSUE TITLE
Lawyer security records

### ISSUE THREAD

**Issue by Oakboscage** [yogstation13/yogstation#736]
Add a console in the lawyers' office so they can review security records and get on security's ass for not updating them. Would also help for building cases in trials if we ever had them. 

The console would be read-only so that lawyers can't fuck with the records.

**Comment by AdamElTablawy** [comment]
just build it yourself you have nothing better to do as a lawyer

**Comment by Oakboscage** [comment]
Adding a console would make the lawyer more useful.

**Comment by Cruix** [comment]
Lawyers can already view security records on their PDA

**Comment by Super3222** [comment]
The Security Records on your PDA is quite literally horrid without a search mechanic. And adding a search mechanic would only make all of security in general not give a shit about security computers, which would lead into power creep, and goes back to the idea of read-only security records and implementing https://github.com/yogstation13/yogstation-old/issues/1175

**Comment by Cruix** [comment]
Even if they had a search, they would not be able to set the security status of people they cannot see, so the computers would get some use.
