### ISSUE TITLE
Free miner asteroid failed to spawn even though there were free miners

### ISSUE THREAD

**Issue by Reed0506** [yogstation13/Yogstation#7362]
Issue reported from  Round ID: 26847 (Yogstation 13)

Reporting client version: 512.1488

**Comment by MegaEmpirical** [comment]
Reposting issues, shameful.

https://github.com/yogstation13/Yogstation/issues/7314

**Comment by CrazyDrakkon** [comment]
![Free Miner bad](https://user-images.githubusercontent.com/18729830/71300660-7c718800-235c-11ea-9310-80ceabd2aa31.png)

**Comment by alexkar598** [comment]
fuixed
