### ISSUE TITLE
Remove PALADIN from roundstart lawset rotation.

### ISSUE THREAD

**Issue by nesisknesis** [yogstation13/Yogstation#7367]
Shitty lawset that promotes validhunting. One step to utopia by getting rid of it from the config.

Pretty sure roundstart lawsets are in the config anyway, under silicon_laws.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
