### ISSUE TITLE
Borg with donor skins have an invisible open/closed hatch sprite, making clarity on whether its toggled hard.

### ISSUE THREAD

**Issue by nesisknesis** [yogstation13/Yogstation#7379]
would like this fixed pronto so i can start with doing donor skins smoothly

code issue most likely, i don't know the cause.

**Comment by Kmc2000** [comment]
you need to include the hatch open / closed state in the separate donor borgs.dmi, I think i did that initially but you may have changed that since I coded the system.

**Comment by nesisknesis** [comment]
They are included, this problem is the same for the ratvarian eyes overlay.

**Comment by adamsong** [comment]
This has been fixed
