### ISSUE TITLE
anatomic pancea does not flush chemicals from body

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#738]
or heal tox damage

**Comment by X-TheDark** [comment]
```
user.reagents.add_reagent("mutadone", 10)
user.reagents.add_reagent("pen_acid", 20)
user.reagents.add_reagent("antihol", 10)
user.reagents.add_reagent("mannitol", 25)

for(var/datum/disease/D in user.viruses)
    D.cure()
```

Working as "intended"?

**Comment by tromacodes** [comment]
I don't think it is meant to do that. Otherwise it will nerf the consequences of adrenaline over use. Please be careful how you adjust this one.

**Comment by McDonald072** [comment]
It injects pentetic acid which heals tox damage, removes chemicals pretty quickly and reduces radiation. I'd say it's working as intended

**Comment by ShadowDeath6** [comment]
anatom is shitty currently, and it doesn't purge shit as much as it should. IMO it should clear all reagents from the body, then inject mutadone, antihol, antitox, etc.

Also I don't think pentetic heals tox

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
pentetic heals 4 rad, 2 tox and purges 2u of chems per tick
/pedantics
