### ISSUE TITLE
Pipboy PDA skin big broke

### ISSUE THREAD

**Issue by gilvian** [yogstation13/Yogstation#7389]
Most of the stuff pointless. NT Pipboy PDA skin is broken, by broken i mean a lot of broken.

You can wear it as glasses, exosuit and a hat sometime for some reason
![dsadas](https://user-images.githubusercontent.com/13832819/71384558-48a79400-25e2-11ea-9311-d3404a3ba558.png)

**Comment by MegaEmpirical** [comment]
Duplicate of https://github.com/yogstation13/Yogstation/issues/6905
