### ISSUE TITLE
Traitors & al. can have the objectives to kill and "prevent from escaping alive" both for a single, same person.

### ISSUE THREAD

**Issue by Altoids1** [yogstation13/Yogstation#739]

**Comment by Amelia0010** [comment]
so what. If you're killing them then you're preventing them from escaping alive

**Comment by Altoids1** [comment]
I mean, yeah, ultimately it just gives admins more chances to push their meme objectives onto people. I just thought I'd bother saying it here in case someone thought it wasn't a feature.
