### ISSUE TITLE
riot dart boxes don't count their contents' metal value until you remove one, thus infinite metal

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#7390]
Issue reported from  Round ID: 26922 (Yogstation 13)

Reporting client version: 512.1488

![image](https://user-images.githubusercontent.com/36427443/71386226-4c272500-25ba-11ea-8b08-281c91719fdd.png)

**Comment by alexkar598** [comment]
Material amount is set by autolathe after creation of item leading into a race condition between the item initializing ,setting its base_cost and bullet_cost vars and the autolathe giving it the amount of material it has inside

**Comment by alexkar598** [comment]
Nvm, found a fix that should be easy enough
