### ISSUE TITLE
Can't unresolve ahelps

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7408]
They don't unresolve.

Also, sometimes when I send an admin PM when all previous tickets for that player are closed, it sends it to their last ticket thread instead of a new one, and then I can't unresolve it.

**Comment by alexkar598** [comment]
Follow the template, round ID are critical to fix these kind of weird doesn't always happen bugs

**Comment by MegaEmpirical** [comment]
Round 30851
Ticket 6 with Liberal
Could not unresolve and a new ticket was not being made when messaged.

**Comment by MegaEmpirical** [comment]
Apparently an issue with admins making tickets, when we do we don't get a ticket in the ticket log.
