### ISSUE TITLE
Skateboard camera and player positioning are off.

### ISSUE THREAD

**Issue by UnknownBry** [yogstation13/yogstation#741]
When clicking and dragging the player model onto the skateboard, it brings the character model to the same tile as the skate board, but when the player moves, only the skate board moves, keeping the player model and camera at the starting tile. Other players see the skateboard as just the skateboard. Things like electrified doors still effect the player and knock them off the skateboard, but they still remain at the original tile.

**Comment by timkoster1** [comment]
Could not reproduce. Could you give more specifics of where you were, and any special attributes that may've been into play?

**Comment by UnknownBry** [comment]
The board was on the escape wing, hugging the wall that shares the RnD's table that leads out into escape. No special attributes come into mind, and the only thing that could have played a part was that the board was used for about 10-15 minutes (by someone else, whom I did not observe), and they could have done any number of things to have caused this bug.
