### ISSUE TITLE
Plasma tank icon bug

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#7416]
1.  Place igniter and remote signaller on the floor, screwdriver both, attach both together, place on floor.
2. Use plasma tank on the assembly (assembly on the floor).

All normal plasma tanks have the singletank bomb icon state now (/obj/item/onetankbomb). Tested with admin spawning tanks after and getting them out of tank dispensers. Tested this twice and both times the icon changed.

![image](https://user-images.githubusercontent.com/34506490/71522729-cf4bc200-28bd-11ea-8dc8-d90859c2a8fd.png)

**Comment by redmoogle** [comment]
![image](https://user-images.githubusercontent.com/20369082/104321863-2b29be80-54b2-11eb-83ec-9e82f309abb8.png)
seems to be fixed
