### ISSUE TITLE
Cameras don't work properly

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#742]
Sometimes, making photos with camera works.
But now, the third time:

- The camera makes a photo that is invisible to me, and upon examination the photo window does not appear
- all sounds stop, and never return..
- in a minute, chat displays message: "You are either AFK, experiencing lag or the connection has closed."
- after client restart, I can see the photo and look at it, and I hear sounds again

**Comment by Altoids1** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/38134 , closing
