### ISSUE TITLE
Admins need a way to review NTSL Scripts

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7430]
Currently I don't see anyway for us to access scripts that are in play without making a body and checking manually, assuming the code wasn't clear. AI interact doesn't even work.

Either way, no way to check once its cleared (that I know of).

**Comment by ThatLing** [comment]
Thanks @Altoids1

**Comment by Bibby0110** [comment]
On the actual tcomms servers, there's a var that contains the raw code, actual way to see this would be nice though

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
