### ISSUE TITLE
Borg's light unable to be repaired after getting hit by nightmare?

### ISSUE THREAD

**Issue by Saratoubi** [yogstation13/Yogstation#7441]
Issue reported from  Round ID: 27005 (Yogstation 13)

Reporting client version: 512.1467
 
Waited a long time for my lights to come back on, but they never did. Went to robos for help but they couldn't fix em either. Had to deconstruct me to get them to work.

**Comment by Hopekz** [comment]
The issue here might be that it's not clear enough how to repair borg lights. 
What robo can do to repair this:
Put a lightbulb inside of the borg (the ones found in janitor's lightbulb box or all around the station)
