### ISSUE TITLE
Civilian door remote does not work on cargo doors

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7454]
Cargo is a civilian department. HoP only gets the Civ remote, Hop is in charge of cargo.

This is madness.

**Comment by Reed0506** [comment]
he also cant lock his own office which sucks

**Comment by MegaEmpirical** [comment]
Didn't know that, that's fucking weird.

**Comment by ToGWtF** [comment]
it basically only works on hallway doors which have no id restrictions and clerks office

**Comment by MegaEmpirical** [comment]
Does it not work on other civilian departs like Botany and lawyer?
