### ISSUE TITLE
Add way to unbuckle people from self as borg

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7455]
As title.

**Comment by zxmongoose** [comment]
You can *spin to get people off though it will toss them in the direction you're facing

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
