### ISSUE TITLE
Give mobs a damned stop pull button

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7458]
Named xenos, or anything with a hud at least.

**Comment by Ktlwjec** [comment]
for now you can press delete

**Comment by Xoxeyos** [comment]
Or you can press B!

**Comment by MegaEmpirical** [comment]
I do keep forgetting that exists, would still be a good edition.

Delete is OOC for me. Fuck accidentally hitting the O key.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
