### ISSUE TITLE
Status display logging please

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7459]
Would be super useful.

**Comment by Bibby0110** [comment]
Current way to do this:
href logs

**Comment by MegaEmpirical** [comment]
Href don't log what was said, only that someone accessed the display status input.

**Comment by Bibby0110** [comment]
nope,
it logs inputs too afaik

**Comment by MegaEmpirical** [comment]
We had need of this the other night, it doesn't.

**Comment by Bibby0110** [comment]
Round ID & guys CKEY? (DM me)

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
