### ISSUE TITLE
Chemical suggestions from SnowJohn

### ISSUE THREAD

**Issue by Hopekz** [yogstation13/Yogstation#7464]
![image](https://user-images.githubusercontent.com/24533979/71613832-1bbd2900-2b6e-11ea-9eee-9b6f7fe2b11b.png)

Paste:
**Chemical suggestions**

Azidoazide Azide:
-------

 same thing as current nitroglycerin but it is a bit stronger and if it somehow fails to make a breach it puts nitrogen in the air (2 carbon 10 nitrogen -> 2u Azidoazide Azide)

Fluoroantimonic acid:
----
 take Floralsulfuric acid make it stronger, and give it the effects of thermite when splashed on a structure (2 Hydrogen 1 antinomy 5 florine 5 floralsulfuric acid (catalyst) -> 1u fluoroantimonic acid)

Nitroglycerin (update): 
-----
explodes when splashed instead of upon creation (same as before)

Dimethylcadmium:
-----
 deals fuck tonnes of toxin damage in the short term, and if it is in your system for some time and you somehow you aren't dead, it gives you the tumor trait, explodes at 380K (2 carbon 5 hydrogen 1 cadmium 370K -> 1 Dimethylcadmium)

Cadmium: 
------
Deals small amounts of toxin damage, similar to chlorine, found in once upgraded chem dispenser

Antinomy: 
------
Found in once upgraded chem dispenser, no other affects

Antinomy trichloride: 
------
when splashed makes a spot on the ground stained with the chemical similarly to thermite, when stepped on creates fire on that tile and disappears (1 antimony 3 chlorine -> 3u antinomy trichloride)

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
