### ISSUE TITLE
Reflector jacket sprite

### ISSUE THREAD

**Issue by Ktlwjec** [yogstation13/Yogstation#7488]
https://github.com/yogstation13/Yogstation/pull/6892

The sprite from that pr got reverted by accident, likely sometime when the iconbot was down. I'd pr it back but it needs new sprites for the in-hand sprites, tg forgot to make those.

**Comment by Partheo** [comment]
![image](https://user-images.githubusercontent.com/10659549/86492289-a5c39580-bd3b-11ea-8c6b-6f1f57aaabd2.png)
![image](https://user-images.githubusercontent.com/10659549/86492294-ab20e000-bd3b-11ea-8cda-3b00032df106.png)
