### ISSUE TITLE
Bring back fucking triple refill on air alarms

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7500]
There is no operating mode for just refilling a room now, sometimes you just need to add air without changing the damn settings.

**Comment by Hopekz** [comment]
Lyis mad

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
