### ISSUE TITLE
Cloned sheltered people can speak common

### ISSUE THREAD

**Issue by DerelictDrone** [yogstation13/Yogstation#7508]
## Round ID:

27093

## Testmerges:

None

## Reproduction:

Die and be cloned as a sheltered human, you now speak common and not japanese(test with other races?)

**Comment by Firewolf34** [comment]
I think it makes it impossible for you to understand your native tongue, too.

I spawned as a Lizard, and was unable to understand other people speaking Draconic, even though I was speaking it myself.

**Comment by Cartlord** [comment]
Cloning, as far as I can tell, removes all Quirks.

**Comment by ReddicusDragon** [comment]
> Cloning, as far as I can tell, removes all Quirks.

:amlookin:
