### ISSUE TITLE
Implanter UNUSABLE

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#7527]
Round 27132 or 27133, not sure because the server reverted back to a server restart in the next round.
I don't know what caused it but even after client restart, the mindshield implanter was not working, at all. When we could print a new implanter from protolathe, it worked, then after awhile when we came back, it also **didn't**. Always had to switch implanters..

**Comment by ToGWtF** [comment]
Can fix in-game by putting implant back into empty implant case. dont know root cause

**Comment by redmoogle** [comment]
I believe this was fixed by the pr that fixed gangs mindshield fuckery reopen if you see it again
