### ISSUE TITLE
Xenological Containment Unit can pick up the AI

### ISSUE THREAD

**Issue by Hopekz** [yogstation13/Yogstation#7537]
Hate to be a party pooper by reporting this but it is an oversight so here we go.
It is hilarious.

## Reproduction:
Walk up to AI
pick up the whole core with the Xenological Containment Unit.

**Comment by SomeguyManperson** [comment]
It can pick up any normal sized mob, including people

**Comment by Hopekz** [comment]
> It can pick up any normal sized mob, including people

Does that seem intended I can't tell

**Comment by alexkar598** [comment]
Its made by nick vr so its buggy and badly implemented

**Comment by ToGWtF** [comment]
AI's can't use cameras while picked up in this , though they don't lose health as long as they are in an area with an APC. It basically intellicards them. also they need to manually unbolt themselves
