### ISSUE TITLE
Bed and bedsheet directional sprites please

### ISSUE THREAD

**Issue by Ktlwjec1** [yogstation13/Yogstation#7539]
I just want to flip a bed to make the maps look prettier, but 2 of the directions look ass just rotated and I'd rather not make a separate sprite for every single bedsheet just to do this.

**Comment by nesisknesis** [comment]
the bot doesnt understand sprites, it only understands feature request and bug, give it a chance

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
