### ISSUE TITLE
Apparently Defibrillators are bugged.

### ISSUE THREAD

**Issue by Altoids1** [yogstation13/Yogstation#754]
t
**[Round ID]**: 15948

**[Reproduction]**: Putting the defibrillator pack on your back and clicking on it or using the action button just results in "The paddles snap back into the main unit." over and over, never actually deploying into your hands.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
i am shocked

**Comment by Amelia0010** [comment]
🥁

**Comment by Smudged** [comment]
The same occurs on wall-defiberlators, you pick up the defiberlator, but it's a spooky ghost one that doesn't work.

**Comment by YeOldeSheriff** [comment]
This seems to be happening with all back based things like that, such as water tank packs like the jani has.

Happens with compact defibs as well.

**Comment by 00aquir** [comment]
Indeed, atmos cannot use metal foam or nanofrost either.

**Comment by Amelia0010** [comment]
https://github.com/tgstation/tgstation/pull/37792
