### ISSUE TITLE
Can it be made so that janitor carts and people with golashes can move through wet floor signs freely?

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7549]
Currently you have to walk only and it blocks the cart.

Note, I am referring to holosigns.

Also, normal signs are still broken you monsters.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
