### ISSUE TITLE
Darkspawns kill plasmamen too effectively. 

### ISSUE THREAD

**Issue by azzzertyy** [yogstation13/Yogstation#7562]
Due to the fact plasmamen helmets were made flashlights a while ago now, darkspawn now instantly destroy plasmamen helmets causing them to burn and die almost instantly.
This is ridiculous and needs to be changed; 
i'd suggest making them no longer function as flashlights once a darkspawn has killed it.

**Comment by MegaEmpirical** [comment]
They've had flashlights for the entire duration I have played SS13, not a recent thing.

Nightmares destroy only when the light is on, do Darkspawn always destroy them? If not then you just have to adapt.

**Comment by azzzertyy** [comment]
flashlights arent new as far as im aware, just that darkspawn outlives it in terms of creation

**Comment by UselessTheremin** [comment]
this ain't a bug plus they can turn their helmet lights off if they really need to be careful and just carry a flashlight instead
