### ISSUE TITLE
Backpack preferences for plasmamen are not working

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7579]
Does not give the correct backpack as per setting. I have mine set to department satchel and only get the normal grey backpack. I do get the nice sec backpack when I play sec though, though not a satchel.

**Comment by Mr-Space** [comment]
They just aren't defined for plasmemes, if my bugfix gets merged I'll try working on this next.

**Comment by MegaEmpirical** [comment]
NOT FIXED
