### ISSUE TITLE
3x3 enclosed wish granter spawns in open terrain when near other ruins

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation#758]
Issue: Wish granter, powerful reward, can spawn in the middle of the ground if its too close to another ruin.

Example: https://gyazo.com/d90d4824bbc43c513682938054bc7b73

Solution: Remove the 3x3 invincible wall wishgranter ruin, or modify its proximity.

**Comment by ShadowDeath6** [comment]
Immortality would be so abusable in the greed ruin too

**Comment by ParagonPrime** [comment]
why the fuck does a wish granter ruin even exist if we're not meant to use it

**Comment by Cruix** [comment]
You are supposed to spam bluespace crystals and get stuck in the cube forever while the gods laugh at you.

**Comment by Super3222** [comment]
> You are supposed to spam bluespace crystals and get stuck in the cube forever while the gods laugh at you.

Cruix nails it. You need bluespace crystals to get to it.

**Comment by EMT321** [comment]
Or anyone in telescience.

**Comment by EMT321** [comment]
This needs to be resolved.

https://gyazo.com/9b8a96061e81da80315367d54c781101
