### ISSUE TITLE
Refill extinguishers with sink.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#7584]
Cargo can be a pain in the ass when they steal ALL water tanks. Sink holds the same water, make it possible to refill extinguishers there.

**Comment by MegaEmpirical** [comment]
Cargo is generally filled with assholes, yeah.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
