### ISSUE TITLE
New poltergeist gamemode

### ISSUE THREAD

**Issue by AsV9** [yogstation13/Yogstation#7585]
## Brief Description
Implement a new gamemode based on the following design document: [google doc](https://docs.google.com/document/d/1jEDPKJuLicx4S4vHObE49GaQ1X1sEoLdiQNhdjhdRr8/edit?usp=sharing)

## Requirements

- The gamemode should ideally function at around 15-20 players.

- You should focus on stealth and subterfuge elements.

Obviously this is a really open bounty. You may make whichever adjustments to the design you see fit, the only real requirement is for this to function as a low-pop gamemode.

If you wish to consult with anyone on design-elements, speak with Kay#7465 or zxmongoose#2622 on Discord.

For any technical details on the bounty, consult AsV9#0001 on Discord.
If you wish to have access to the #coder channel on Discord for assistance, please let me know, and I'll set you up with it.

# Bounty: 35 €

You will be paid via PayPal at the time of merge. In the event of multiple people competing to complete the bounty, the first PR to be merged will win. Obviously, the PR will need to meet code-standards to be merged.

**Comment by Mr-Space** [comment]
Ghostbusting intensifies

**Comment by swissloaf** [comment]
revenant gamemode

**Comment by zxmongoose** [comment]
I definitely did not hit that but okay phone

**Comment by MegaEmpirical** [comment]
Someone going to unpin this?
