### ISSUE TITLE
Make traitor codewords show up in red to other traitors

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#759]
# Make traitor codewords show up in red to other traitors.

Someone says a codeword, it's missed in common chat.

This fixes it, making it easier for traitors to collaborate-simply make a traitor codeword show up in red or bold to other traitors if said. Not only if said by a traitor, said by anyone, and only to other traitors.

**Comment by puremanbird** [comment]
yesssssss.

**Comment by Alek2ander** [comment]
Only if mindshield implants enforce loyalty to _**Nanotrasen**_ and your _**Captain, Long May He Reign**_

**Comment by Oakboscage** [comment]
Do me really need to make it easier for traitors? Remembering a few words isn't that difficult.

**Comment by AdamElTablawy** [comment]
i only posted this because @puremanbird requested i did

**Comment by Super3222** [comment]
Very interesting

**Comment by MacHac** [comment]
Traitors don't usually check their words, and those that do don't often think about them unless they recieve a PDA message.  The big concern with this would be, if traitors can pool their points and share equipment, this gives them a lot more TC for buying weapons and such;  Making it easier to identify other traitors will almost certainly increase teaming up, which might screw game balance.

**Comment by ClaudeWicked** [comment]
I would really, really, like this. Ive said the code words maybe 30 rounds, multiple times. Ive only ever got a response twice. This isn't making tators stronger, it just makes the people who cant be assed to remember code words actually notice.
