### ISSUE TITLE
Make the tricoder stop giving atmos read outs when you fucking click on something

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7590]
I am so sick and tired of getting atmos read outs while fixing comms with the tricoder, just make it activate the atmos read out when I click it in hand.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
