### ISSUE TITLE
Change access requirements on radiant dance machine

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7593]
Apparently it uses something engineers have but bartenders and clowns can't use it which seems weird. At the very least bartenders should be able to.

**Comment by alexkar598** [comment]
Feature requests are no longer handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums [here](https://forums.yogstation.net/index.php?forums/feature-requests.221/)
