### ISSUE TITLE
Burning while buckled to lavaboat.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#7598]
![SS13-bug-boatfire](https://user-images.githubusercontent.com/16806055/72272180-7f445d80-3628-11ea-91cc-9413b8533744.png)

- When travelling on lavaboat, you often have to fight enemies that are wandering on the lava.
- This could be somewhat ok on the boat. But you are slower, and when goliaths stun you, you **shouldn't** start to burn while on the boat, just be stunned, otherwise you immediately die.
- It would also be a better option than carving out rock every time and trying to attract monsters from there.

**Comment by jcatjmeow** [comment]
this isn't a bug. Make a forum post about it.
