### ISSUE TITLE
Bug raffle

### ISSUE THREAD

**Issue by AsV9** [yogstation13/Yogstation#7605]
## Brief description
Fix any bug and open a PR to enter the raffle. When it gets merged, you get one entry.

## Bounty
Winner gets a 15 € steam gift card (converted to whichever currency steam uses in your region).
Limited to 10 entries per participant.

Bother AsV9#0001 on Discord for more details

Open for one week, closes January 20th 2020 at 6 PM CET.

**Comment by nesisknesis** [comment]
fix borg skin overlays, they also need light overlay code

**Comment by AsV9** [comment]
![image](https://user-images.githubusercontent.com/13056792/72295650-4b812c00-3658-11ea-9f61-c1c132c5a9ca.png)

**Comment by Mr-Space** [comment]
I fixed #7318 and #6058 tickets pls

**Comment by Mr-Space** [comment]
This raffle is won by @monster860 . Congrats.
