### ISSUE TITLE
add back holo PaIs

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#763]
let pai's go holographic form again that was a great feature

**Comment by ShadowDeath6** [comment]
Remove putting pAIs into things then :^)

**Comment by timkoster1** [comment]
No, medbot and mulebot pAI is bae

**Comment by tromacodes** [comment]
I didn't like the put pai into stuff feature. Pai were meant for advice and companionship.  A lot of people do like the feature though so I don't know.

**Comment by Kmc2000** [comment]
George was working on this, but he stopped.


Looks like a nasty one to port though..

**Comment by Ephemeralis** [comment]
I'm working on porting it back again. There's probably going to be so many fucking issues with the medbot/mulebot placing but I'll see what I can do.

**Comment by puremanbird** [comment]
Having PAI's run around was stupid and defeated the purpose of a PAI.

**Comment by ShadowDeath6** [comment]
>having pAIs run around was stupid and defeatred the purpose of a pAI

then why haven't we removed the retarded bot functionality they have

**Comment by puremanbird** [comment]
You should.

**Comment by Ephemeralis** [comment]
The purpose of a pAI was not to provide a neutered ghostrole for dead players, but rather to provide a platform for people to meaningfully contribute to a round in a different way. Obviously, this role comes with some very prominent restrictions, but pAI players generally enjoy the intensely cooperative nature of the role.

I'll be tweaking the way pAI software is assigned and will probably relegate the holographic form to a software "build" which allows them to choose that mobility at the expense of other things. RC pAI are already very powerful in their own right when tethered to the correct consoles.

**Comment by EMT321** [comment]
@Adameltablawy Seeing as how this was merged, can this issue be closed?
