### ISSUE TITLE
Text sometimes goes deadchat purple

### ISSUE THREAD

**Issue by Ktlwjec1** [yogstation13/Yogstation#7637]
This image will explain it better than I ever could, there seems to be no in-game reason for it, happened across multiple rounds. If there is a reason then at least my confusion will be resolved:

![image](https://user-images.githubusercontent.com/59522545/72327100-5794da00-36a8-11ea-9cdb-69719810d630.png)

**Comment by SomeguyManperson** [comment]
Sometimes messages will inherit a previous message's span class if they happen at roughly the same time i.e. someone talking while you use a health analyzer to scan them might result in their text being cyan; probably related

**Comment by SomeguyManperson** [comment]
appears to have been fixed since as i have not seen it occur in a while
