### ISSUE TITLE
[1$] space vines bounty

### ISSUE THREAD

**Issue by boodaliboo** [yogstation13/Yogstation#7638]
the only request for this bounty is to make it so space vines from the random event will only be able to spawn in maintence for two reason it makes more sense and also it gives time for kudzu to become a actual threat instead of the minor inconvenience it is now

**Comment by boodaliboo** [comment]
can i get bounty tag

**Comment by Mr-Space** [comment]
All feature requests are to be made on forums from now on. You can use this link for it: https://forums.yogstation.net/index.php?forums/feature-requests.221/

I'm closing this.

**Comment by boodaliboo** [comment]
IT ISNT A FEATURE REQUEST ITS A BOUNTY JUST LIKE ASVS IT GAVE ME THE WRONG TAG
