### ISSUE TITLE
implant breaker allows gang members to convert when not lt

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#7647]
title

**Comment by Amelia0010** [comment]
what did he mean by this

**Comment by SomeguyManperson** [comment]
The implant breakwr can be used by any gangster to convert people into their gang, bypassing the lieutenant/boss requirement on pens

**Comment by MegaEmpirical** [comment]
Isn't the implant breaker removed?

**Comment by ynot01** [comment]
it was taken away from the buy menu not removed

not to say that i remembered that when making this issue

**Comment by MegaEmpirical** [comment]
Didn't know that. Fair enough then.

**Comment by ynot01** [comment]
Gang no longer exists
