### ISSUE TITLE
Can no longer manually set SMES'

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7651]
Have to use the buttons like some animals.

**Comment by Bibby0110** [comment]
Could be solved by adding a TGUI-Next NumberInput

**Comment by MegaEmpirical** [comment]
Isn't that the source of the issue?

**Comment by Neotwr** [comment]
https://github.com/tgstation/tgstation/pull/48838

**Comment by MegaEmpirical** [comment]
That.
