### ISSUE TITLE
Pirate's, despite being made of bone, still get shocked. This must be a bug, because its retarded any other way.

### ISSUE THREAD

**Issue by maxion12345** [yogstation13/Yogstation#7652]
## Reproduction: >be pirate >touch spicy vault window

https://i.gyazo.com/4b0f8bf6742449786e257ea10dd61bef.png
🤔

**Comment by overlord12345** [comment]
Its not a bug, they get shocked for the same reason they take stamna damage even if they dont have muscles so skeletons dont become mega op

**Comment by MegaEmpirical** [comment]
Electricity can harm many things.
