### ISSUE TITLE
flat gun bug

### ISSUE THREAD

**Issue by boodaliboo** [yogstation13/Yogstation#7658]
Round ID: many

Testmerges: #7553: 'Lag removal, try 2' by 1fbff5f83b23d39d38b1dfcb4cac8d9b at commit d4a739397e (this bug has existed for months

Reproduction:

pick up a flat gun 
if it disapeers the item stays in your hand but is unusable you must press q to drop it

**Comment by jcatjmeow** [comment]
fixed afaik
