### ISSUE TITLE
Nothing displays in the chatbox

### ISSUE THREAD

**Issue by FunkyPutin** [yogstation13/Yogstation#7673]
From couple of weeks I can't see what's going on the game because any message display, neither mine nor ingame actions, etc.

I tried to clean the caché of byond, internet explorer's one, reinstalling byond... but nothing helped.

In the image you can see my chatbox, and you can see it's totally blank:

![blank](https://user-images.githubusercontent.com/60070770/72684669-e491c600-3ae2-11ea-89f5-c9be3cea8cd3.PNG)

Help, please

**Comment by boodaliboo** [comment]
lol go to ooc section then press fix chat

**Comment by FunkyPutin** [comment]
> lol go to ooc section then press fix chat

I already tried that and nothing. It keeps displaying lots of nothing

**Comment by JamieD1** [comment]
Is this still an issue?

**Comment by FunkyPutin** [comment]
Yeah, it's not solved yet, althought, there is a change. The windows now display this: 
![ss13](https://user-images.githubusercontent.com/60070770/82806261-b1db4e00-9e85-11ea-803b-23e01f8b4084.PNG)

**Comment by ShoziOffical** [comment]
left corner, file, reconnect

**Comment by ReddicusDragon** [comment]
no further reply from the author, closing. If this is still an issue feel free to re-open this issue.
