### ISSUE TITLE
chokeing on air

### ISSUE THREAD

**Issue by overlord12345** [yogstation13/Yogstation#7680]
if air is pumped into a oxy tank you will start chokeing, unshure if its a bug but it is dumb

**Comment by MegaEmpirical** [comment]
This is not a bug and it's not dumb. Air is a oxy-nitrogen mix. Pure oxy tank pressure regulators are set to the minimum needed for a pure gas so as to get the most use. If you mix in nitrogen then you need to change the pressure regulator to account for this change. Without the change, you're not getting enough oxygen in a breath to breath.

**Comment by overlord12345** [comment]
ah il close this then
