### ISSUE TITLE
Add firelocks to the outer escape firelocks.

### ISSUE THREAD

**Issue by dominuslucian** [yogstation13/Yogstation#7681]
monstermos likes to fling people out into space when they open these doors without the shuttle docked, bit annoying

**Comment by Lynameep** [comment]
It seems like firelocks are only placed on the innermost airlock for ones that connect to space so I assumed this was a design choice but there again there are some cases where this isn't true so I'm not entirely sure if it's intended to be this way.

**Comment by JamieD1** [comment]
Fixed with new airlocks
