### ISSUE TITLE
Clogged vent (scrubber) event bypasses fucking plasmaman suits

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7686]
It's a sealed environmental suit, this shit should not be getting in.

**Comment by maxion12345** [comment]
Damaged plasma envirosuits from scrubber acid now breach the suit and kill the plasmaperson inside

**Comment by MegaEmpirical** [comment]
Acid breaching the suit would make sense which it'll do as it dissolves it. The issue is shit like morphine getting in.

**Comment by zxmongoose** [comment]
To be fair envirosuits do allow puncturing from needles with no bad effect, though iirc they can't have touch chems applied through them. I've never tried it through a spray-type application, though, only patches.

**Comment by MegaEmpirical** [comment]
Touch chems work on the suit but not the helmet (patches and sprays aside). A syringe has a pointy needle, suit could easily have a small patching system but such. As for a foam liquid getting in, if it is then so is the oxygen in the air.

**Comment by zxmongoose** [comment]
I do agree, but I've also just remembered that cryo also works on plasmamen, and that would be a similar function as the scrubber events. I think if one doesn't work, the other shouldn't either logically

**Comment by MegaEmpirical** [comment]
That's a trade I'm willing to make.

**Comment by UselessTheremin** [comment]
imo this is not a bug, they don't have hardsuits on. possibly the ic reasoning is that their suit can absorb chemicals from around them to absorb patches, idk. if you disagree dm me on discord

**Comment by MegaEmpirical** [comment]
I think it's a little fucky but your comment on patches won me over. Well done.
