### ISSUE TITLE
Taking off a O2 tank on a hardsuit also turns off the plasma air tank in the pocket

### ISSUE THREAD

**Issue by Zebra03** [yogstation13/Yogstation#7688]
## Round ID: 27382

The plasmatank valve was closed when clearly the O2 tank in hardsuit that was closed by the action
First time this ever happened, never seen this before.

**Comment by Zebra03** [comment]
This happened in 00:57:12 from the round replay - (https://yogstation13.github.io/demo-viewer/?roundid=27382#34320;113.50;90.50;2;sirbullbirt ), The O2 tank in Plasmion's hardsuit(My disconnected Character) valve is closed by the lizard causing the plasmaman tank in my pocket to be disabled too some how, you can see that I plasmion(My disconnected character) starts gasping but the plasmaman air tank (In the pocket)was not interfered in any or even taken out of the pocket.

**Comment by MegaEmpirical** [comment]
Likely due to how tanks work, there is only the one button for them. May actually be a feature request.

**Comment by Zebra03** [comment]
That explains a lot

**Comment by MegaEmpirical** [comment]
It's why I don't bother with that shit as a precaution as a plasmaman.

**Comment by redmoogle** [comment]
You can only have 1 tank open at a time, so it likely switched
