### ISSUE TITLE
Getting welder flashes while welding in plasmaman paramedic helmet

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7692]
Reeeeeeeeeeeeeeee

It's not stunning me and I've not had issues with resisting flashes or flashbangs and I don't seem to be getting eye damage. Just the flashing light overlay when I weld.

**Comment by JamieD1** [comment]
Take away flash image overlay.

**Comment by MegaEmpirical** [comment]
Didn't seem to be an issue anymore when I tested it earlier.

**Comment by MegaEmpirical** [comment]
Going to close this as it seems resolved.
