### ISSUE TITLE
Herald (Elite of Colossus) does zero or almost zero damage to non-owner players

### ISSUE THREAD

**Issue by TavinHead** [yogstation13/Yogstation#7708]
Round ID: 27423

Problem Description: Herald (Elite of Colossus) does zero or almost zero damage to non-owner players

What did you expect to happen: I expected it to do anything. In combat with another player who wasn't their owner, the herald shot them 12 times with death bolts, and so I expected they would be fairly injured.

What happened instead: They has slight bruising I am not even sure the herald caused.

Steps to reproduce the problem: Kill herald, re-summon with shard, they get into a fight, no damage is dealt out.

**Comment by overlord12345** [comment]
its just coders being lazy and not setting the factions right

**Comment by Takahiru** [comment]
seems like its on purpose to be honest theres even a comment mentioning they cant other members of the faction
