### ISSUE TITLE
Missing sprites or not appearing on the model

### ISSUE THREAD

**Issue by Gintoki1** [yogstation13/Yogstation#7728]
**Chameleon jumpsuit outfits that aren’t properly appearing on model or is missing a sprite.**
Armory officer uniform, Signal Technician's jumpsuit, Signal Technician's jumpsuit skirt, Recovery medic's jumpsuit, Clerk's skirt, Clerk's Suit, Hawaiian shirt (tourist), Tacky sweater (cosby), zoot suit (zootsuit), Very Fancy captain uniform (captaienfemailformal_s), Draculass coat, Gondola suit, Ronald mcdonald uniform. (Many more can be listed)

**Chameleon suits that aren’t properly appearing on model or is missing a sprite.**
Messiah Robes(jesus), Varisty jacket, biker jacket, Blue detective jacket, Monk robes, Soldier webbing, Black Trench coat, detective long coat, Janitor coat fur coat, Gold detective jacket, Russian gangster suit, Denime jacket, Trainman suit, Fiend scowl suit, nt sweater, spess hoodie, Jester coat, Witch hunter suit

**Chameleon Backpacks aren’t properly appearing on model or is missing a sprite.** 
Green shell backpack(snail_green), Banana backpack, Clown face backpack

**Chameleon Glasses that aren’t properly appearing on model or is missing a sprite.**
Hypno-spectackles and 3D glasses

**Comment by ToGWtF** [comment]
Fixed in https://github.com/yogstation13/Yogstation/pull/10615
