### ISSUE TITLE
Quite a few guns at centcomm are missing there firing pins.

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#773]
The X-Ray laser gun, biological demolecularisor, advanced energy gun, accelerator laser cannon all have no firing pins. The alien pistol has a alien firing pin and won't fire.

**Comment by Super3222** [comment]
It's all non-canon

**Comment by 00aquir** [comment]
What's non canon? R&D can make some of them.

**Comment by Super3222** [comment]
Yes but, I mean the entire room is non-canon. I'm sure some of those guns aren't just for people to kill each other with at the end but, for admins to mess around with and such.

**Comment by Zostroll** [comment]
It's just annoying when at round end you go to pick up a gun and it doesn't work and you are then shot to death.
