### ISSUE TITLE
Air Pressure GOES THROUGH WALLS

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#7735]
Round 27506

Pyro anomaly went off in toxins storage with above 20000kpa, and after that, with a delay, the surrounding rooms started to have elevated pressures (research sec room was first for some reason), even though I frickin' bolted the door.

**Comment by MegaEmpirical** [comment]
I believe heat still transfers through walls and doors but have a much higher threshold than say glass.

**Comment by Bibby0110** [comment]
Heat is not intended to transfer through walls according to the code. There's some magic going on, that's for sure

**Comment by patpol4** [comment]
Pretty sure heat can go through doors

**Comment by 00aquir** [comment]
okay then, I just thought something weird was going on when the sec room had the first alarm.
