### ISSUE TITLE
acievements not working

### ISSUE THREAD

**Issue by overlord12345** [yogstation13/Yogstation#7757]
i keep getting acievements yet in the acievement window all of them show up as locked

**Comment by alexkar598** [comment]
Known issue, fix is yet unmerged

**Comment by overlord12345** [comment]
Ok

**Comment by adamsong** [comment]
@alexkar598 Was the fix merged?

**Comment by alexkar598** [comment]
probably idk

**Comment by adamsong** [comment]
Fix was merged 'probably idk' closing
