### ISSUE TITLE
The description for HE Grenades is shit. 

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#776]
"A compact shrapnel grenade meant to devestate nearby organisms and cause some damage in the process. Pull pin and throw opposite direction.
" They spelt devastate wrong and its not a shrapnel grenade (frag grenade) its a high explosives grenade.

**Comment by 00aquir** [comment]
*throw in opposite direction

**Comment by 00aquir** [comment]
*throw it in the opposite direction

**Comment by AndySok** [comment]
And the sprite is 2 big.

**Comment by AdamElTablawy** [comment]
will fix
