### ISSUE TITLE
Add something to do in the ninja hell.

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#779]
When a ninja energy nets you you get teleported to a place were there is about three things to do:drink, play with foam force stuff and kill yourself. It is worse than being killed cause you can't be cloned. A drinks machine were you can all the bar drinks could be added. Or a small botany like perma. Or a r&d console. Or a chem dispencer. Or a arcade. Or any combination of these. There needs something to do to make this less hell.

**Comment by AdamElTablawy** [comment]
Just suicide. It's not supposed to be fun. No other antagonist gives you fun things to do when they kill you.

**Comment by ShadowDeath6** [comment]
just have it put you into the adminbus room :^)

**Comment by tromacodes** [comment]
Coooooooome on spider clan initiates.  With a cursed katana and sleeping carp scroll!!!

**Comment by Super3222** [comment]
From what I hear, you're not even suppose to arrive on centcomm if the ninja is a syndicate. there was suppose to be a mapped out area somewhere separate where captured people were suppose to drop. it never got added/mapped/sprited however.
