### ISSUE TITLE
Port comin' right up: Antag Weight

### ISSUE THREAD

**Issue by X-TheDark** [yogstation13/yogstation#78]
Most of the groundwork has already been ported during the Admin Tickets, it's just a matter of replacing the picking of antags with the antag_weight enabled function now (I think and hope for this to be this easy).

**Comment by ParagonPrime** [comment]
Except antag weight still needs to be fixed as it doesn't reset like it's supposed to.

**Comment by X-TheDark** [comment]
*sigh*

**Comment by X-TheDark** [comment]
And done. Ports and fixes the antag weights not working properly.

Doesn't include Show Antag Weight button thing, but that seems to broken as well, so I'll probably do it in another PR. There are things more important to port (donor stuff, for example).
