### ISSUE TITLE
New spiders

### ISSUE THREAD

**Issue by darkwahn** [yogstation13/yogstation#781]
Spiders now basically teleport stick to you, which wouldn't be a big issue if two bites wasn't guaranteed death.

I'm not sure what we should do with them, but this doesn't seem like the right choice.

**Comment by Super3222** [comment]
If the weaver problem continues to persist despite how many times people open up PR's tweaking them here and there, I'll go with my plan to revamp them.

**Comment by AdamElTablawy** [comment]
i'll just remove them if weavers are aids after this last revert

**Comment by Super3222** [comment]
> i'll just remove them if weavers are aids after this last revert

But we're not removing them. We're just making them better, more fair, and balanced into the game.
