### ISSUE TITLE
Asteroid Syndie Comms overheat

### ISSUE THREAD

**Issue by fira** [yogstation13/Yogstation#7852]
Issue reported from  Round ID: 27812 (Yogstation 13)
Reporting client version: 512.1488

-- Beginning Encrypted Communication --

Syndicate Asteroid Listening post has apparently no way to cool the Relay producing heat in its Comms Room.
After about one hour ON, the whole room reaches about 90°C which is unsurprisingly annoying and a workplace hasard.
I couldn't find a way to cool this down other than by dilluting it with the rest of the station's air.
The Asteroid post is not even supplied with an hardsuit, as we are not normally allowed to leave, so i figure you'd eventually just die scorched or have to walk outside without EVA. That or turn off Relay and not do your job. Either way, it's not much of a win.

I wasn't expecting such oversights from Syndicate Engineering. This really is undeserving of the higher standard we strive for, barely fit for Nanotrasen. Please advise.

**Comment by MegaEmpirical** [comment]
Should be able to turn it off, doesn't need to be on by default.
