### ISSUE TITLE
Disappearing Gang Icons?

### ISSUE THREAD

**Issue by PettyOfficer** [yogstation13/Yogstation#7858]
Issue reported from  Round ID: 27846 (Yogstation 13)

Reporting client version: 512.1488

Played as a standard Gang Member using character "Angel Strange." Mid-round, became an "Obsessed" and lost all Gang Icons to see fellow Gang Members and Gang Heads. Probably does not return after death and cloning.

**Comment by Moltijoe** [comment]
gags is dead
