### ISSUE TITLE
Setting Tourist as a HIGH Occupation Chance Does Nothing

### ISSUE THREAD

**Issue by PettyOfficer** [yogstation13/Yogstation#7889]
Issue reported from  Round ID: 27925 (Yogstation 13)

Reporting client version: 512.1488

Prior to roundstart, set all Occupation Chances to NEVER, except for Mime and Clown, which were set to MEDIUM. Set Tourist to HIGH. Roundstart, given message, "You have failed to qualify for any job you desired."

Previous rounds, set Tourist to HIGH and received different occupation, i.e., Cargo Technician, etc. For some reason, Tourist is not allowed for me as a roundstart occupation.

**Comment by Bibby0110** [comment]
Intended
`total_positions = -1
spawn_positions = 0`
Aka
Unlimited jobs
No roundstart spawns

**Comment by AsV9** [comment]
Intended behavior.

**Comment by HomocidlePancakes** [comment]
@AsV9 Doesn’t this mean you can safely assume a tourist won’t be antag because he isn’t a roundstart job? Seems meta to me.

**Comment by Bibby0110** [comment]
> Doesn’t this mean you can safely assume a tourist won’t be antag because he isn’t a roundstart job? Seems meta to me.

Late join antags are a thing :)
