### ISSUE TITLE
Exosuits cannot open closed firelocks

### ISSUE THREAD

**Issue by Jarod1200** [yogstation13/Yogstation#7891]
Round ID 27925

https://i.imgur.com/kqQ3s62.png

while walking down the hallway towards an explosion, the firelocks prevented my mech from moving south. I asked the other mentors about this and they said "You don't get through because its broken".

seems like this kinda defeats the purpose of having the mech if you have to dismount to open the firelocks without spending time destroying them.

**Comment by Hopekz** [comment]
@monster860

**Comment by redmoogle** [comment]
Was fixed.
