### ISSUE TITLE
Medical Cyborgs unable to do the "tend wounds" step of advanced repair surgery

### ISSUE THREAD

**Issue by Mqiib** [yogstation13/Yogstation#7904]
Issue reported from  Round ID: 28008 (Yogstation 13)

Reporting client version: 513.1512

No tools, including the hemostat, work on that step.

**Comment by jcatjmeow** [comment]
While the info on the wiki is inaccurate, I was able to complete the surgery as a mediborg.

**Comment by Mqiib** [comment]
Did you try it on a dead target?

**Comment by jcatjmeow** [comment]
No, but I will now, just for you

**Comment by jcatjmeow** [comment]
@Mqiib works just fine.

**Comment by Mqiib** [comment]
It still doesn't work on the live server.
