### ISSUE TITLE
Coughing Not Work Like Sneezing 

### ISSUE THREAD

**Issue by aaqe** [yogstation13/Yogstation#7914]
## Reproduction:

Coughing symptom does not spread like sneezing, sneezing bypasses a low transmit value.  Unable to create COVID-19 

If you tell me this is a feature request then you should not have told me that.

Please fix, not bitch.

**Comment by alexkar598** [comment]
feature request, it only spreads to nearby humans if transmissibility is 7 or higher so fuck off you cunt
