### ISSUE TITLE
Free golem ORM breaks when deconstructed partially

### ISSUE THREAD

**Issue by methodicsin** [yogstation13/Yogstation#7915]
Issue reported from  Round ID: 28044 (Yogstation 13)

Reporting client version: 512.1488

when spawned in as a free golem ghost role, I went and mined some ores as you would. returned ores in ore box and placed box above ORM. did not realize at the time that the free golem ORM does not accept ores from boxes and so thought it was bugged or something. opened maintenance panel with a screwdriver and removed parts with a crowbar. reinstalled parts but then was completely unable to interface with the ORM, and it would not accept ore in any way, loose on the ground, from a bag, or from a box. admin at the time suggested I open a bug report

**Comment by jcatjmeow** [comment]
This bug no longer occurs in game. Fixed by tgui probably?
