### ISSUE TITLE
Bug report: When you have a online cap jetpack in your bag, and the bag is in your hand they still let you travel in space.

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#792]
Reporting for Omsomething.

**Comment by Kmc2000** [comment]
Feature, captain jetpack is best jetpack

**Comment by X-TheDark** [comment]
Pretty sure this is true for all hand-holdable jetpacks.

**Comment by Super3222** [comment]
How does the cap's jetpack manage to get within a bag? unless it's bluespace of course

**Comment by AdamElTablawy** [comment]
was already fixed
