### ISSUE TITLE
Space airlocks don't really open.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#7930]
The space airlock leading to sec office.. Cannot skip the depressurization process from the outside, and it took waaaay longer to cycle than in other places (the atmos system was probably compromised at the time). Maybe make it possible to skip the process, from the outside, with the right access?

**Comment by Hopekz** [comment]
Tagging @monster860 since he's the airlock man.

**Comment by MegaEmpirical** [comment]
This doesn't sound like a bug. That room is larger than most other airlocks and they're not meant to skip depressurization.

**Comment by jcatjmeow** [comment]
This isn't a bug
