### ISSUE TITLE
Double payday announcements

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#7958]
It was better when it was broke!

![image](https://user-images.githubusercontent.com/36208065/76335907-996a8700-62cb-11ea-96f5-2eaf2da90f21.png)

Also, is this announcing it so everyone can hear it again and not just as a whisper?

**Comment by ToGWtF** [comment]
Fixed with https://github.com/yogstation13/Yogstation/pull/8492

**Comment by MegaEmpirical** [comment]
That's a fix for the broken setting. Does it also fix the double speak?

**Comment by jcatjmeow** [comment]
fixed

**Comment by MegaEmpirical** [comment]
![image](https://user-images.githubusercontent.com/36208065/86679705-d28ddc00-bfcb-11ea-83c4-4e603121cd4a.png)


LIESSSSSS

**Comment by MegaEmpirical** [comment]
Fucking reopening you lying bastard.

**Comment by adamsong** [comment]
I have not observed this behavior, is it still happening or has it been fixed in the past year?

**Comment by MegaEmpirical** [comment]
I am not seeing this any more, closing.
