### ISSUE TITLE
Please revamp AI Machine Overload and Override!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#796]
It is a mess. First of all, when I first tried it I expected that I would activate the mode then click on a machine. Instead there are these... lists in Non-alphabetical order! The hell is that.. the stuff I want is on the screen in an improvised place and I would **never** find it on the list soon enough, not to mention some weren't even on the list as far as I know.

So would it be possible to change it so I could just click on the object after selecting the mode and it blows up? Or at least some alphabetical order starting with the room name, at least...

**Comment by timkoster1** [comment]
Hit the first letter off the machine and it will automaticly go through all of those.

**Comment by 00aquir** [comment]
It's jumping between those words ACROSS the whole list, you cannot see them in order, you cannot search with your eye and if you miss it then you would have to go back, it is as slow as can be!

The list should be by Room names first, and in alphabetical order, but clicking on a machine would be better.

**Comment by timkoster1** [comment]
Just clicking on a machine to blow it up? I'll go do that right now.

**Comment by 00aquir** [comment]
Thanks, both the overload and override has these weird lists...

**Comment by Cruix** [comment]
It's a verb, so you can click it to get the whole list or right-click and select it from the context menu of the machine you want to blow up.

**Comment by timkoster1** [comment]
oooooooooooooooooooooooooooooooooooooh
Ok, yeah.

Ok,

Well fuck.

I will abort mission then.

Wew.

Much info, many wow

**Comment by 00aquir** [comment]
next time I'll check it out then..
