### ISSUE TITLE
fake walls broken

### ISSUE THREAD

**Issue by enkidienne** [yogstation13/Yogstation#7969]
## Reproduction:

fake walls acting like real walls when opened. cant see throught, cant pass, cant close it. bug occurring every time fake wall is opened. Bug is occurring on mutliple fake walls.

sorry if i did things wrong here, first timer!

**Comment by Spl99** [comment]
I'm not sure of the issue, I can't seem to recreate it.  I've built a fake wall and it's worked and I've turned a normal wall into a fake wall and still nothing. Was this a once off issue for you?

**Comment by enkidienne** [comment]
well, this was 14 days ago. I too haven't seen it since, maybe it was just a one round thing?

**Comment by Bibby0110** [comment]
I've noticed this happening sometimes too, doesn't seem to be triggered by anything in particular

**Comment by Partheo** [comment]
Tried to recreate this specific issue and wasn't able.

Possibly related: #9114

**Comment by adamsong** [comment]
Cannot reproduce
