### ISSUE TITLE
Changeling is unable to absorb past 8 DNA?

### ISSUE THREAD

**Issue by PettyOfficer** [yogstation13/Yogstation#7992]
Issue reported from  Round ID: 28285 (Yogstation 13)

Reporting client version: 513.1513

Objectives:
Objective #1: Absorb another Changeling.
Objective #2: Steal a reflective jacket.
Objective #3: Prevent Whitaker Robertson, the Roboticist, from escaping alive.
Objective #4: Steal the brain of Whitaker Robertson, the Roboticist.
Objective #5: Escape on the shuttle or an escape pod alive and without being in custody.

I absorbed 8 bodies from lavaland to get 8 DNA. Could not proceed absorbing lavaland bodies, so I originally thought there was a limit on lavaland. 

Original objective #4 was to take the identity of Whitaker Robertson and impersonate him with his ID. Changed with Adminhelp since I could not absorb his DNA to transform, but Objective #1: Absorb another Changeling was also impossible because I could not absorb Changelings.

**Comment by HomocidlePancakes** [comment]
Yep, there is a limit on disguises. You are supposed to delete one of your forms if you want to absorb some more. Or I may be completely bullshitting you and have no idea what I am saying.

P.S. Why were you even absorbing lavaland bodies, dork?

**Comment by jcatjmeow** [comment]
Not a bug.

To absorb new genomes you have to delete old once when you hit the limit
