### ISSUE TITLE
Flat guns firing pin bugged

### ISSUE THREAD

**Issue by Nostr0** [yogstation13/Yogstation#8008]
## Reproduction:

- Went space exploring
- Took Flat Gun from the paper planet (asteroid?)
- When inspected it said it had an electronic firing pin installed [Screenshot](https://imgur.com/a/owo2rdB)
- Tried to fire it: "There is no firing pin installed" message appears

**Comment by SomeguyManperson** [comment]
Happens if the flat gun deletes itself which can happen on being picked up
