### ISSUE TITLE
Issue with Crafting Toilets

### ISSUE THREAD

**Issue by alao3alao3** [yogstation13/Yogstation#8020]
## Reproduction: I had attempted to create a toilet as seen in the above photo. Though all materials are present, I am unable to craft a toilet. I've attempted this with all materials on the ground and an empty mop bucket, all materials on hand and a filled mop bucket, and I have not been able to craft it.
![aaaa](https://user-images.githubusercontent.com/62276730/77593403-84484780-6eca-11ea-9253-08cfa6e2f5d3.png)

**Comment by MegaEmpirical** [comment]
Not a bug. Your materials need to be on a table or in your hand.
