### ISSUE TITLE
Atmosphere system in mining is bugged?

### ISSUE THREAD

**Issue by Silvore** [yogstation13/Yogstation#8054]
Issue reported from  Round ID: 28483 (Yogstation 13)

Reporting client version: 513.1511

So, I was at the hierophant arena to get out of an ash-storm, when I was suddenly launched a few tiles, and I noticed that air kept getting sucked in and out of the arena, even though it should have been the same atmosphere. It kept knocking me around until the hierophant killed me. I think this is a bug, as it also said there was low pressure, even though lavaland shouldn't have low pressure.

**Comment by adamsong** [comment]
Lavaland does have lower pressure than is comfortable, but I do no see any evidence of airflow around hierophant or lavaland in general.
