### ISSUE TITLE
Crew monitoring console is displaying random suitsensors of unknowns

### ISSUE THREAD

**Issue by Nostr0** [yogstation13/Yogstation#8073]
## Reproduction:
Click on the crew monitoring console as AI at highpop??
That is it.
[See here](https://imgur.com/a/lWm2gY8)

**Comment by Hopekz** [comment]
Moving Gif here so people don't have to use the imgur link
![KLoPWeC](https://user-images.githubusercontent.com/24533979/78212437-57210980-7475-11ea-93ab-60ea696a3d1d.gif)

**Comment by HomocidlePancakes** [comment]
Well, It seems that the crew monitoring is duping entries. You can see multiple unknowns in the armory, for example, which is probably the same guy. Some have same damage values, location and etc.

**Comment by Bibby0110** [comment]
Don't think this happens anymore?

**Comment by Nostr0** [comment]
I've never seen it happen again ever since

**Comment by adamsong** [comment]
Closing an unreproduceable
