### ISSUE TITLE
The game sometimes does not end when the shuttle docks at Centcom.

### ISSUE THREAD

**Issue by Altoids1** [yogstation13/Yogstation#809]
t
**[Round ID]:** 16024

**[Reproduction]:** I have no idea how to replicate it, but on round 16024 the shuttle docked at Centcom without ending the round, requiring me to come on and end it. The gamemode was traitor+ling, there were a fuckton of unclaimed tickets, and there was a lot of recalling back and forth, if that helps any.

**Comment by ThatLing** [comment]
@nichlas0010 Any idea?

**Comment by Amelia0010** [comment]
/shrug/

**Comment by Amelia0010** [comment]
![image](https://user-images.githubusercontent.com/20558591/39968041-e79e9744-56c6-11e8-96ff-ac294a057ef8.png)
can't reproduce

**Comment by ThatLing** [comment]
Can't find any runtimes related to this
