### ISSUE TITLE
Yogstation escape shuttle template.

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation#81]
Most of you probably don't know this but with the new /tg/ build there's a button that allows you to change how the escape shuttle looks. I haven't looked into how it works but i'm just going to report that we should probably add our shuttle design into the templates list incase an admin switches to it and doesn't switch back.
Right now in the rebase map file the shuttle is /tg/ one, not the yogs one.
Alternatively you can just forget about our shuttle and just keep the same templates as /tg/.

**Comment by Bawhoppen** [comment]
Adding in new shuttle templates is super simple, just add the map file to a folder and edit a file somewhere to add it to the list.

**Comment by ShadowDeath6** [comment]
>keeping tg shuttle

no

**Comment by Bawhoppen** [comment]
your shuttle is barely different? it doesn't justify meme arrows

**Comment by oisin100** [comment]
Ive already updated the docking area to fit it.

Also @Bawhoppen our shuttle is very different, your shuttle is so small... and featureless.

**Comment by X-TheDark** [comment]
There's plenty of shuttles /tg/ have that are pretty damn awesome. I'll see if I can get around adding our shuttle to the list, but honestly, as I said, /tg/ have so many hilarious shuttles like Nar-Sie/Clown/Bar, etc.

**Comment by oisin100** [comment]
> There's plenty of shuttles /tg/ have that are pretty damn awesome. I'll see if I can get around adding our shuttle to the list, but honestly, as I said, /tg/ have so many hilarious shuttles like Nar-Sie/Clown/Bar-themed etc.

As far as I know they only spawn from adminbus? Shuttles aren't randomly picked right?

**Comment by Bawhoppen** [comment]
iirc I believe you can set which template it uses by default actually
