### ISSUE TITLE
Graphic window keeps stopping

### ISSUE THREAD

**Issue by goldengames128** [yogstation13/yogstation#815]
My graphic window, the one with all the visual activity just stops, seemingly randomly. The chat still works, the sound still works, and the top right buttons and thing still works, its just the graphic window. Byond is up to date and so are my drivers. What do?

**Comment by goldengames128** [comment]
New thing, instead of the graphic window stoppping space station just crashes

**Comment by Super3222** [comment]
Seems a bit out of hand for the code but, I suggest clearing your cache, re-installing byond, or running an anti-virus scan through your computer.

**Comment by ToGWtF** [comment]
Do you have any sort of recording software? Make sure the background process is ended with task manager and restart DreamSeaker.  I had the same probem for days, until I read on the BYOND fourms that Raptr and PlaysTV recording software were the cause
