### ISSUE TITLE
Head closet bloat

### ISSUE THREAD

**Issue by Featherfield** [yogstation13/Yogstation#8154]
Heads have so much random bloat in their closet some cannot even fit everything after opening them and closing again and you end up with random crap outside of the lockers.

**Comment by Jumps0** [comment]
From what i've seen the ones who have a serious problem is the CE and HoS lockers who can't hold everything. Captains locker seems fine due to the CapDrobe in the office, that could be one solution but placement in cramped offices like the CE's would be difficult.
