### ISSUE TITLE
Cult game mode softlock

### ISSUE THREAD

**Issue by Hopekz** [yogstation13/Yogstation#8168]
If the sacrifice target for the blood cult is the chaplain and he uses his holypara and gets dusted before he gets sacrificed; the game is now soft locked.

Cult can't win and you can't even bring the chaplain back using admin powers to get him sacrificed because it won't count.

**Comment by ToGWtF** [comment]
I dont see this as an issue. Just a game mechanic.

**Comment by Hopekz** [comment]
> I dont see this as an issue. Just a game mechanic.

It is an issue because the shift can't end.
It's basically permanent extended if the cult takes over

**Comment by Bibby0110** [comment]
> > I dont see this as an issue. Just a game mechanic.
> 
> It is an issue because the shift can't end.
> It's basically permanent extended if the cult takes over

How about the shuttle?

**Comment by Hopekz** [comment]
> > > I dont see this as an issue. Just a game mechanic.
> > 
> > 
> > It is an issue because the shift can't end.
> > It's basically permanent extended if the cult takes over
> 
> How about the shuttle?

The shuttle doesn't get called because the cult controls the station.
Usually in these situations the cult has taken over all crew.

**Comment by Jarod1200** [comment]
this has happened twice in like the last week

**Comment by Takahiru** [comment]
what happens if the sacrifice target's body is destroyed any other way?

**Comment by overlord12345** [comment]
> what happens if the sacrifice target's body is destroyed any other way?

unless the body can be put back together the cult cant win
