### ISSUE TITLE
Copy pasting icon files.

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation#82]
So it looks like some people have been using copy and paste to port our .DMI files or Icon files. This is a problem because /TG/ might have renamed icons and added new icons to that file, by copypasting Yogstation icons over it we remove those changes /TG/ did.

# Dont copypaste! It just makes headaches when we find out theres missing textures.
 
Use the DreamMaker inbuilt Import/Export options for adding new icons to the DMI files.

**Comment by Bawhoppen** [comment]
More on copypasting: you should have remade your map (which is barely different than tg box) by hand, so you don't miss any of the new things in there, which I heard rumors you might have missed key things like xenobio shit
