### ISSUE TITLE
healing and limited healing holoparas/gaurdians can heal borgs, mechs and bots

### ISSUE THREAD

**Issue by overlord12345** [yogstation13/Yogstation#8220]
they should only healing liveing things

**Comment by Hopekz** [comment]
Actually;
For some stupid reason, #7999 was merged to make them have forced healing.

It doesn't make sense in-game and I argued for it before it was merged because it is very immersion breaking.

**Comment by Hopekz** [comment]
Looks like this is the way it is meant to be with these new holoparas.
