### ISSUE TITLE
Preternis clock cult

### ISSUE THREAD

**Issue by Readystorm546** [yogstation13/Yogstation#8222]
## Reproduction:

I spawned in as a clock cult. Was a preternis everything was fine until i went  to use a vitality rune. The rune stuck me in place and did not heal me. Im pretty sure it drained all of out vitality and just did not heal me.

**Comment by Moggram** [comment]
The healing part is not a bug. Healing spells don't work on preternis. If you give the rune the code that looks for TRAIT_MEDICALIGNORE, it 'should' stop preternis from getting stuck.
