### ISSUE TITLE
Putting Bomb (C4) in a full bag detonates the bomb

### ISSUE THREAD

**Issue by ValoTheValo** [yogstation13/Yogstation#8225]
## Reproduction:

I Was Playing Nukies For The First Time And I Was Getting Items. I Decided To Get C4 i put a few in no issue but when i tried to put another bomb in it told me the bag was full then planted the C4 on it. Then Promptly Blew Up. Causing Me To Die

**Comment by ToGWtF** [comment]
Maybe putting a check on if what you are planting it on is a backpack and instead giving you a "are you sure" popup like a BoH bomb

**Comment by Featherfield** [comment]
Did you not notice the timer and message about planting C4

**Comment by ToGWtF** [comment]
Fixed with https://github.com/yogstation13/Yogstation/pull/8367
