### ISSUE TITLE
Turbine doors at Yogsmeta are not working

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#8260]
In several rounds:
- the inner turbine doors cannot cycle at all, and once they close, they lock the player in permanently. Cannot abort "cycling", which gets stuck.

the same problem might occur in Yogspubby.

**Comment by jcatjmeow** [comment]
this used to occur in the syndie base too. But I think monster may? have fixed it.

If anyone knows if this is still an issue please let me know, otherwise I'll test it myself later

**Comment by 00aquir** [comment]
Yogsmeta turbine doors still cannot cycle properly.

**Comment by patpol4** [comment]
Same issue as https://github.com/yogstation13/Yogstation/issues/5710, it's a mapping thing, just switch out the system all the other maps use for simple cycling like on box. This applies to turbine and toxins

**Comment by 00aquir** [comment]
https://github.com/yogstation13/Yogstation/pull/9299

**Comment by patpol4** [comment]
I'll reopen since #9299 was not merged
