### ISSUE TITLE
No images for RPD pipes

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#828]
we're building blindly

![ss13-rpd-noimage](https://user-images.githubusercontent.com/16806055/40009821-589de0a8-57a3-11e8-8c60-14db7f2f506a.png)

**Comment by Notamaniac** [comment]
You can hover your mouse over to get a tooltip on what direction the pipe is laying, but yeah icons are broken for me too, and for some people on tg

**Comment by Amelia0010** [comment]
https://github.com/tgstation/tgstation/issues/37828 upstream issue
