### ISSUE TITLE
Blood cult ban not working

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#8307]
Round 29103
Rorimor (banned player)

Blood cult banned and still got converted. I was a ghost at the time and there was no prompt to take him over either.

**Comment by JamieD1** [comment]
How did he get converted please elaborate @MegaEmpirical

**Comment by MegaEmpirical** [comment]
I assume he was converted on a normal blood circle. I no longer recall but since I didn't say more that's the most likely way.
