### ISSUE TITLE
revamping Cursed heart

### ISSUE THREAD

**Issue by xbobsherex** [yogstation13/yogstation#832]
As we all know cursed hearts are useless at best, death at worst. to my knowledge you beat the heart to survive. it heals you a little bit but costs you blood and precious life if you dont.

 my idea is have the cursed heart be directly related to speed. the faster you pump it the faster you move. if you dont pump it your frozen. you dont die but you just stop moving.

**Comment by ShadowDeath6** [comment]
we don't need more speed boosts in this game

**Comment by Cruix** [comment]
The cursed heart is supposed to be a wizard item and rare lavaland loot, there is no reason to discard this idea based on that.

**Comment by xbobsherex** [comment]
its not just a "speed boost" item with this idea. if someone has to beat the heart quickly to move fast then they shouldnt really be able to fight. how i picture it is if they are trying to fight and click the heart then they will either fight badly, or actually move slower
