### ISSUE TITLE
Mimes can use advanced mimery as zombies

### ISSUE THREAD

**Issue by MenacingManatee** [yogstation13/Yogstation#8341]
Round 29136: as traitor mom I purchased advanced mimery. Random event zombie happened, and by the end of the round I was converted. Despite being a zombie, I still had access to my invisible bullets and 3x1 invisible walls, which seems unintended

**Comment by MegaEmpirical** [comment]
Once a mime, always a mime. I say feature.

**Comment by Xoxeyos** [comment]
Not a bug, you're a zombie with it's brain mostly intact.

**Comment by overlord12345** [comment]
zombies could always use spells they had before being infected not a bug, nor unintended

**Comment by Takahiru** [comment]
feature

**Comment by jcatjmeow** [comment]
It's a feature.
