### ISSUE TITLE
Ghost orbits off by 1 tile to the left

### ISSUE THREAD

**Issue by Hopekz** [yogstation13/Yogstation#8357]
I've asked multiple people and it seems to be happening on their game as well.
The ghost orbit is off by 1 tile to the left. 
Might be a remnant of our April fools changes?

![image](https://user-images.githubusercontent.com/24533979/80825440-04d32580-8ba6-11ea-8018-74b865d0c60f.png)

**Comment by azzzertyy** [comment]
i believe its to do with the byond update, i didn't get this until i updated my game.
