### ISSUE TITLE
Fire extinguisher unremovable from backpack

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#836]
In the backpack, only the fire extinguishers were stuck inside the backpack, everything else was removable with hands.

![ss13-unremovable-fireextinguishers](https://user-images.githubusercontent.com/16806055/40029836-fcc02eaa-57e6-11e8-9704-19a5e0319dc1.png)

**Comment by ThatLing** [comment]
Sounds like an upstream issue

**Comment by Amelia0010** [comment]
![2018-05-19_17-53-49](https://user-images.githubusercontent.com/20558591/40270437-d57b5db0-5b8d-11e8-8f7e-758ce34dca8a.gif)

**Comment by 00aquir** [comment]
I still can't remove them..
