### ISSUE TITLE
Engiborg LOSES METAL

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#836]
1. Use all metal up while building (repairing) walls.
2. Metal remains disappeared even after recharge.
3. Cry 
4. Please also check this for all other materials

**Comment by ahamedx** [comment]
Just tried this and it worked. Can you give more details?

**Comment by 00aquir** [comment]
Engiborg used metal to make girder or put metal on girder for walls, **or these processes together in one time**, then the metal sheet disappears from slot.

**Comment by Oakboscage** [comment]
I had this issue earlier, happened when I cleared the tool slot after using up all my metal.

**Comment by AdamElTablawy** [comment]
doesn't seem to occur anymore
