### ISSUE TITLE
Peaceborg dizzy solution is behaving oddly

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#8380]
I believe it is supposed to knock you out? So far I have not been able to get it to do so. Also, the stamina damage heals completely if you keep pushing yourself, it does slow you down considerably but then it just full heals. It will also heal slowly if you stay still, as it should.

**Comment by SomeguyManperson** [comment]
peaceborg tiring spray will only deal up to 50 stamina damage, dizzying spray only causes dizziness and stuff
