### ISSUE TITLE
The ass scanning and printing feature is broken

### ISSUE THREAD

**Issue by RobertRoberts2020** [yogstation13/Yogstation#8395]
## Round ID:
29248

## Reproduction:
I tried printing my own ass by dragging my sprite into a phocotopier, but instead of printing the picture of my ass it printed an object with no icon that doesn't do anything.

**Comment by MegaEmpirical** [comment]
Did you try relogging? Pictures have been weird in recent months and soemtimes require a relog.

**Comment by Partheo** [comment]
Seems broken completely. Tried jumping on photocopier and copying, toner was consumed but no paper produced at all. No message appears either.

**Comment by RobertRoberts2020** [comment]
This is a crucial gameplay feature that needs fixing can you change it to medium priority at least ? :(

**Comment by ToGWtF** [comment]
Cannot confirm this is still an issue

**Comment by adamsong** [comment]
Thoroughly tested, seems to be working
