### ISSUE TITLE
Buff Chloral hydrate or chemical Neurotoxin 

### ISSUE THREAD

**Issue by puremanbird** [yogstation13/yogstation#840]
No military grade bar chemicals, okay. How about some military grade chemical chemicals? Right now chloral is extremely weak. It takes ages to kick in and it burns through your system extremely fast. Chemical neurotoxin is also useless. I suggest speeding up the time it takes for chloral to kick in and/or making neurotoxin work as a slightly weaker version of the old bar neurotoxin (kicks in after 1-2 seconds instead of instantly, adds a fluff message when you are injected that basically lets the person know they are fucked and give them time to react or call for help) I also suggest changing the recipe for neurotoxin so that it is more complicated to make and requires more steps.

**Comment by ShadowDeath6** [comment]
does chem neuro not knock you out instantly and deal like a bazillion brain damage

**Comment by puremanbird** [comment]
chem neuro does nothing. some slight toxin damage and slight brain damage right now

**Comment by EMT321** [comment]
Why?

Chemistry is powerful enough as is.

**Comment by ShadowDeath6** [comment]
can't validhunt people with lethal chems, emt

**Comment by EMT321** [comment]
If you want to validhunt go security.

This change is unnecessary.
