### ISSUE TITLE
Sec record unsearchable word

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#8402]
Round 29252
This entry couldn't be found at all if you wrote the word "viro", tried it multiple times and at different locations.

![SS13-secrecbug](https://user-images.githubusercontent.com/16806055/81127361-42390980-8f3e-11ea-8760-a0860eebd137.png)

**Comment by Nostr0** [comment]
Had a similar case a few days ago with another name. Some names just can't be found via the search

**Comment by Oblisk234** [comment]
Can't replicate, likely because of #9164 changing the console entirely.
