### ISSUE TITLE
Augmentation is disabled on preternis

### ISSUE THREAD

**Issue by galaxyxd94** [yogstation13/Yogstation#8411]
Issue reported from  Round ID: 29263 (Yogstation 13)

Reporting client version: 512.1488

So i tried to get fully augmented as cyborg parts are much better than preternis basic, but augmentation is dissabled on them.

**Comment by jcatjmeow** [comment]
This might be a feature and not a bug but i don't actually know let me check it out

**Comment by Moggram** [comment]
Not a bug. You are already augmented. You have to remove the base parts first, then you can add what you like.

**Comment by Moggram** [comment]
This can be closed do to this PR [https://github.com/yogstation13/Yogstation/pull/9401](url)
