### ISSUE TITLE
Typo "You feel nauseous."

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#842]
Whatever prompts the "You feel nauseous." status notification should be corrected to say "You feel nauseated." Nauseous means to cause nausea. Like when something is poisonous, it causes poison.

**Comment by 00aquir** [comment]
> "Usage Note: Traditional usage lore has insisted that _nauseous_ should be used only to mean "causing nausea" and that it is incorrect to use it to mean "feeling sick to one's stomach." Back in 1965, the Usage Panel was in step with this thinking, with 88 percent rejecting the "feeling sick" meaning of _nauseous_ in the sentence _Roller coasters make me nauseous_, preferring _nauseated_ instead. Over the years, however, this attitude has shifted dramatically. The proportion of Panelists who disapproved of this same sentence dropped to 72 percent in 1988, 39 percent in 1999, and a slim 23 percent in 2013. This change may have been inevitable once people began to think that _nauseous_ did not properly mean "causing nausea." Even in our 1988 survey, this was the case, as 88 percent preferred _nauseating_ in the sentence _The children looked a little green from too many candy apples and nauseating_ (not _nauseous_) _rides_. In 2013, the Panel was presented with this sentence using the word _nauseous_, and only 30 percent found it acceptable. Since there is abundant evidence for the "feeling sick" use of _nauseous_, the word presents a classic example of a word whose traditional, "correct" usage has largely been supplanted by a newer, "incorrect" one. In other words, what was once considered an error is now standard practice. _Nauseous_ is now far more common than _nauseated_ in describing the sick feeling." _American Heritage Dictionary_

**Comment by MegaEmpirical** [comment]
Yeah, an unfortunate consequence of misuse over time. Should be stomped out to correct the issue, lest we all start saying poisonous to mean poisoned.

**Comment by Amelia0010** [comment]
https://github.com/tgstation/tgstation/pull/37927
