### ISSUE TITLE
Server occasionally glitching at lobby startup

### ISSUE THREAD

**Issue by zxmongoose** [yogstation13/Yogstation#845]
[Round ID]: # Startup of 16108

[Reproduction]: Twice that I've seen, the lobby crashes at it's loading the different subsystems. Trying to rejoin starts with weird, messed up sounds, kind of like when a game lags or when you change resolution on a computer screen and everything stutters for a few moments. That goes on permanently and Byond goes unresponsive. I can't say for sure about the first time it happened, but this time it happened immediately after I hit reject on a ticket that came up almost as soon as the lobby started, so I'm not sure what that could have contributed or if something like that happened the first time as well, but I do remember at least one ticket coming in before the game had fully loaded that time too.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Amelia0010** [comment]
No runtimes at roundstart, hm.

**Comment by Altoids1** [comment]
Haven't seen or heard about this bug in a while so I'ma just say it's gone. *shrug
