### ISSUE TITLE
Stealthmin no longer shows the used name in deadchat

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#8453]
Instead it shows you as:

![image](https://user-images.githubusercontent.com/36208065/81492656-a07c2a00-9267-11ea-87f5-69665afb08c3.png)

**Comment by MegaEmpirical** [comment]
Correction, it never did. It just used to be a period or soem thing so I'm guess this isn't really much of an issue or why it behaves like it does. I'll think on this and see if I need to close it.

**Comment by redmoogle** [comment]
Tested

**Comment by adamsong** [comment]
This is intended behavior, should it be changed?

**Comment by MegaEmpirical** [comment]
Well if you've a fix already I say go with that. Not sure why it was done this way.

**Comment by adamsong** [comment]
I posted that comment then almost immediately decided to fix the ghost issue and figured might as well lump this in
