### ISSUE TITLE
narsie makes inf gas when spawned

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#8472]
![dreamseeker_K93ULo05cv](https://user-images.githubusercontent.com/28408322/81513904-d9fd7580-92f9-11ea-8919-7546c20c02d5.png)
![dreamseeker_0FqYt2rWLX](https://user-images.githubusercontent.com/28408322/81513914-ec77af00-92f9-11ea-8f53-737d7deda129.png)

**Comment by MegaEmpirical** [comment]
Feature, may all be sanctified in her fire.

**Comment by athena413** [comment]
its funny tho

**Comment by SomeguyManperson** [comment]
find out what causes this and make ratvar do it instead

**Comment by jcatjmeow** [comment]
going to test if this still happens today. If so, ima fix it

**Comment by jcatjmeow** [comment]
Was unable to reproduce. Probably been fixed.
