### ISSUE TITLE
Looking at other zlevels while holding the disk teleports it away

### ISSUE THREAD

**Issue by patpol4** [yogstation13/Yogstation#8475]
## Reproduction:

Disk carrier (HoP) looks at cams, probably views lavaland, disk teleports off of him because of the zlevel safeties. Happens at around minute 50 if I recall correctly, might be a bit earlier.

**Comment by jcatjmeow** [comment]
#8912 Fixes this.

Unless you're an ai. But ai's can't hold disks.
