### ISSUE TITLE
preternis with nicotine addiction still suffer the effects of addiction withdrawal despite actively smoking a cigar

### ISSUE THREAD

**Issue by athena413** [yogstation13/Yogstation#8476]

**Comment by Moggram** [comment]
Can confirm. Cigarettes don't do this, but cigars do. (also why I stopped using the quirk)

**Comment by MegaEmpirical** [comment]
Do cigars have nicotine?

**Comment by Moggram** [comment]
So I did some digging in the code. A single cigarette will last 6 minutes and will put 15 nicotine into the body over that time. The cigars on the other hand are all different. 
Premium cigar: 11 minutes / 25 nicotine
Cohiba Robusto cigar: 20 minutes / 40 nicotine
Havanian cigar: Goes for 30 minutes and only has 15 nicotine!

I think thay are just running out of nicotine whit the long burn times. So preternis should use the Premium or Cohiba Robusto and the Havanian is for humans.

**Comment by MegaEmpirical** [comment]
Sounds like this can be closed then.
