### ISSUE TITLE
Krav Maga Disarm

### ISSUE THREAD

**Issue by LazennG** [yogstation13/Yogstation#8479]
Nothing gamebreaking, but the krav maga gloves can't disarm an item in the victim's right hand. It just stays in their grip and warden gets owned liberal style when the disarms dont do jack

**Comment by SomeguyManperson** [comment]
seems to work fine when I tried to reproduce it, the gloves will only disarm stuff in the active hand though

**Comment by jcatjmeow** [comment]
> the gloves will only disarm stuff in the active hand
