### ISSUE TITLE
Hot Dog Stand Does Not Dispense Drinks In Glass

### ISSUE THREAD

**Issue by alao3alao3** [yogstation13/Yogstation#8507]
## Round ID:

<!--- **INCLUDE THE ROUND ID**
[Round ID]: # 29476

## Reproduction:
This occured on the escape shuttle as it was in transit.
I clicked the button that claimed to dispense drinks into a glass. At this point, the portion was changed to 15u and I was trying to dispense that from 160u of space cola. 40u of orange juice was also present.
Upon trying to dispense into glass, only an empty glass came out, depleting the supply of 8 glasses I had to 7.

I had repeated this multiple times during the flight, each with the same result. Note that none of the mentioned reservoirs depleted.

**Comment by jcatjmeow** [comment]
low quality issue report
