### ISSUE TITLE
repost of my old medical rework thing XTHEDARK please add this to projects

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#851]
https://github.com/yogstation13/yogstation-old/issues/1183

okay i know

EXACTLY

what the reaction to this is going to be

there needs to be a balance between the new medical system NOT being crippling to go through since our rounds are fast paced, but having enough complexity to it so that doctors can actually have fun

so here's where we start

Critical

So critical as is is, while generally okay, a little dull and a little irritating in how easy it is to walk off.

So we change critical SLIGHTLY.

Upon hitting 0 health, a human enters 'shock.' In shock, the human can still move-slowly, EXTREMELY slowly-by dragging themselves along the floor. I'm talking like one tile per two or three seconds here dragging. They're also losing health due to oxygen drain, like normal crit, and cannot talk, only whisper. Upon entering -20, they enter normal crit, which is essentially unchanged.

Crit, however, cannot just be walked off. You can recover from shock simply by healing out of it-past -20 to -40, the person in crit gains the condition 'Deep shock', meaning that even if healed out, they'll still take oxygen and brain damage consistently until deep shock is treated-deep shock can be treated with epiphenerine or atropine, so that anyone on the station can epipen you to stop deep shock.

Damage

We're breaking it down.

Brain Damage

Brain damage is changed from being almost a completely harmless meme to something that could actually be dangerous. Past 20 to 30 brain damage, steady increments of toxin damage is dealt scaling on amount of brain damage, and the confused status is added. Past 60 brain damage, the brain is in danger, and heavy toxin damage is taken, in addition to stumbling movement, sudden stuns, and seizures. With 60+ brain damage, someone could probably only live for four or so minutes without treatment.

With 80-100 brain damage, the brain is dying. The person passes out periodically while suffering severe toxin damage and random oxygen damage. Organs, such as the eyes, also start taking periodic damage, before death onsets altogether through complete shutdown of the brain. It's unlikely anyone will get to 100 brain damage outside of tripping the shit out of meth, but it'll be nasty if it does happen.

The reason brain damage is being made dangerous is that it's basically a gimmick damage type that has no real effects aside from being annoying and sometimes making you forget how to use machines, and it has an easy as fuck cure.

Brute

Brute damage is being made more complex, being separated into BLUNT and SHARP damage, with the addition of EXPLOSIVE damage as well.

Blunt damage is dealt through heavy duty objects. Toolboxes, fire extinguishers, crowbars, screwdrivers, fists, stunbatons, telebatons-that sort of thing. Blunt damage is special, in that after reaching 55 damage to a single limb-or 80 damage to the chest or head- there is a steadily rising chance that is multiplied by amount of damage to the attacked area that a bone will fracture in the area. I'll touch more on this later, but don't worry-it's not going to be as godawful as it is to deal with broken bones on bay/para/cm code. BLUNT damage also cannot induce bleeding on it's own.

SHARP damage is dealt through, well, sharp objects. Rarer than blunt, knives, circular saws (and really most surgery tools), eswords, fire axes, and really any other sharp object, apply SHARP damage. They cannot crack bones, but instead, have a high chance (ramped up based on force of the object and amount of brute to one area-remember, BRUTE will still be BRUTE no matter what it's applied by, it's only the objects themselves that will have different effects by flagging them with SHARP or BLUNT)-to induce bleeding through severing arteries and veins, and in the case of 75-120~ damage to the chest or head, damage the internal organs as well. Bleeding can be treated as normal through gauze or bruise packs in minor cases-In more severe cases, it'll require a trauma pack, which I'll touch on later. SHARP objects can also dismember-take a look at /tg/'s dismemberment for an exact, word for word, idea on how this will work and how it's balanced and implemented and how dismemberment can be fixed. Dismemberment is actually really fun-and it's also fairly rare to occur so you don't have to worry about it often, so I'd feel it's a good add on.

EXPLOSIVE is just a flag to indicate that it's applying both BLUNT and BRUTE to it's force, so that being hit by a bomb can both crack bones AND damage organs and sever limbs.

BURN

We're not changing burn damage.

Toxin

In the hopes of increasing the lethality of poisons, which are rarely used since the pyrotechnic chems/beating is more effective, TOXIN damage will be more effective at it's given job of screwing people over.

TOXIN will work in a three step process. In addition to it's normal effects, it goes to a new organ-the liver, which I will touch on later-and as toxin damage ramps up past 40-50, does light damage to the liver. This continues steadily until the liver has reached 40 damage and dies outright. Then toxin will move on to cause brain damage as well as the toxin attacks the brain, damaging it. Meaning that a debilitating shot of poison will, if not treated (and I mean not treated long enough for them to have died from the toxin anyway if it's that potent) screw over their organs too, so that if defibbed they don't just pop up because they choked down some charcoal.

Organs

We're adding some and redoing the way they work.

There are a few more organs we are going to add.

Liver, and eyes-yes, we are making the eyes an organ. A removable organ.

Liver

It slowly, over time, removes toxins from the body. Verrrry slowly, but it's a steady rate of decline. But too much toxin damage also starts damaging the liver itself as it purges the toxin, and if it's overwhelmed you end up getting the whole hog (poison in your brain lad)

Eyes

they're eyes you fucking mongoloid

Organ Damage

Organ damage can be dealt through SHARP or TOXIN damage. All organs have a maxhealth of 40, except for the heart, which has a maxhealth of 60, and the brain, which is it's aforementioned brain damage system, and xeno/ling organs, with a maxhealth of 150.

Basically the way it works is that if some fuck stabs you in the chest with an esword a bunch eventually one of the stabs will nick your heart or lungs, and if passing twenty damage you start racking up debilitating effects, and if it hits the maxhealth the organ stops working entirely and dies. Thankfully, organ damage is fairly rare and also increases slowly, so it'd more be that to actually get an organ completely dead and gone beyond repair you'd have to have someone go absolutely apeshit on you even after you were dead with a heavy weapon-like whacking you fifteen or twenty times with a fire axe. Organ damage is calculated based on brute damage prior to the head or chest, then the force of the hit, and then divided by 600, and then takes a scaling percent chance to see if it's applied-the more hits you take consecutively the more likely it is to apply organ damage, with the chance starting at 20% and scaling by 5%.

So assuming someone stabs you in the chest with an esword five times. You have to be over 100 to 120 damage to the head or chest to take organ damage in the first place, so the first four stabs have no chance at doing organ damage. The fifth sees that your chest has 120 damage, multiplies this by the force of the esword (30), divides this by 600, and so now you have a 20% chance to take 7.2 organ damage distributed equally among all organs in the chest. If that fails, then they stab you again, and so it's 150 x 30 / 600 with a 25% chance of applying and so forth.

So it'll take numerous stabbings with something heavy to actually have any major impact on an organ-so combat-stabbing out someone's lungs or heart is not gonna happen, but saving someone from critical or recovering from a REALLY bad deathmatch will leave you out of it for just a bit longer.

Don't worry, i'm making it easy to treat.

BONE(ers)

There are two states.

Fractured

Fractured comes in at 55+ damage to a limb or 80 damage to the torso (you'll probably not see it until 100+ damage though). A fracture caps the minimum amount of damage to that body part at 15, and causes, if in arms, sudden dropping of objects, and if in legs, setting to walk mode. It's fairly minor, but unpleasant, and bombards you with messages like 'Your arm hurts like shit!' if you fuck around with your broken arm.

Broken

Broken comes in at 160 damage to torso and 70 damage to limbs automatically. Remember, it's only BRUTE that can apply these. Anyway, Broken caps minimum brute damage on that body part at 40-apply all the bruise packs and chems all you want, but it'll go right back up to 40 if not fixed. The maximum amount of damage dealt is 99, so that if every single limb is broken you're not permalocked in crit if a doctor doesn't fix you. It also will lead to very, very slow movement if in the legs-and if both legs are broken, randomly falling over if you try to walk and laying there weaken (2). So, not fun. If the arms are broken, there's a high drop chance that fires quite often, and you can't interact with items that require a lot of dexterity-no writing, no guns, but you can still use a flash or stunbaton, for example. Remember that it is EXTREMELY uncommon someone will have all that damage JUST to a single area, because blows randomly fall around the body.

Don't worry, bones are easy to fix too.

Infections

Infection is now a real thing aside from virology. Immediately identifiable on medHUD's with the same 'SICK' icon, if something above 40 damage is left to fester untreated for 2-4 minutes, a surgery is done with bloody hands or gloves, 20u of virus food is eaten, or on eating the chef's Bad Food if he fucks it up in the grinder, an infection is created. There are three stages.

The first stage is a weak infection, that does light toxin damage and can be treated with 5u of spaceallin or cryptobolin. Infected wounds can simply be seared with a lighter at this stage to remove it.

The second stage is a medium infection. They require a full dose of 15u of spaceallin to fix, or the body temperature of the infected person should raise to temperatures where the little heat icon is orange. It does medium toxin damage until treated.

The last stage takes about ten minutes to reach and is a lethal infection. It requires 31u of spaceallin to fix (overdose levels) or the body temperature of the infected person hitting the point where the heat icon is bright red. Histamine and Toxin (the actual chemical toxin) can also purge the infection. It does severe toxin damage and will kill from full health within five minutes if left untreated-it's unlikely they'll be at full health.

Treatment

Thankfully, all these things are easy to fix, to keep with the fast-paced combat we often have. Self medication is, while still possible, going to be somewhat less effective, but not to the point of any severity-it just means you can't be as reckless as usual.

Advanced Medical Kits

The first item on the list is an advanced medical kit. There will be three in med storage, just like all the other medkits, and be standard issue for doctors. They're also orderable from cargo.

They contain-

Stack of Advanced Trauma Kit

Stack of Advanced Burn Kit

Stack of Splint

1x Atropine bottle

1x Health Analyzer

Advanced Trauma Kits

They're basically better versions of the bruise pack-where the bruise pack heals 20 damage, these heal 40. They also disinfect wounds for anything less than a last-stage infection, seal severed arteries from really sharp objects (esword slashes), and provide some nice flavor texts when applied (such as 'You clean and seal the gaping cut on X's abdomen' or 'You smear some bio-glue over X's wounds.') They have an 8 second self-application time. They come in a stack of 3, meaning you need to be more careful with their use than bruise packs.

Advanced Burn Kit

Basically a better version of ointment, healing 40 burn damage and disinfecting wounds for mild infections and mild infections only. 8 second self application time. Come in stacks of 3, just like the trauma kits.

Splint

Splints are for fractures. They go on a fracture (NOT A BREAK) and stabilize it, negating the downsides except for the minimum damage cap. Comes in a stack of 5.

Organ Kits

Organ kits also come in the medbay storage, two of them. They're for organ damage.

They come equipped with-

4x Peridoxin pill (5u)

1x Mannitol pill

1x Oculine pill

Peridoxin

Peridoxin is a new chemical. It is made from Cyroxadone and Plasma (catalyst) plus oxygen. It slowly heals organ damage at a rate of 1 a tick and revives dead organs. It overdoses at 10u. It decays at a rate of 0.05 per tick.

Bone Treatment Set

Bone damage can be treated with a new chemical, Ostyclastin.

Ostyclastin

Made from Oxygen, Aluminum, and Sulfur, heated to 555K. Makes one unit, not three. Ostyclastin fixes broken bones and fractures over time-After injection, fractures will take about thirty seconds to fix, and broken bones about a minute. Even one unit is effective, but it has to last long enough for the effects to kick in, so the reccomended dose is 5u. Decays at a rate of 0.3 per tick. Overdoses at 20u, is addictive at 15u.

Surgeries

The most debatably fun part of medical, mostly ignored due to lack of access and difficulty. Difficult no longer!

Surgery time delay

Removed. All surgical actions are instant like they once were-the moment you start the scapel swipe you completed it.

Multiple surgery rooms

There will be multiple surgery rooms to support the new medical system using surgery, all of which are default med access, not med doctor only access.

The surgery rooms-and robotics-will be equipped with all standard surgery tools, plus one advanced trauma kit, one bone gel, and one fixovein.

Organ Repair surgery

Organ repair is a new surgery. The steps are, in order, scapel, hemostat, retractor, circular saw, advanced trauma kit to repair organs. When completed, instantly repairs all organs in the targeted area.

Bone Repair

Bone repair is a new surgery. The steps are, in order, scapel, hemostat, bone gel, cautery. If the limb is still damaged to the extent where it was broken, it'll immediately rebreak on doing the surgery, so make sure the brute is treated before doing the surgery. The re-breaking of the bone will display a message as 'Maybe you should try to fix their damage before you fix their bones?'

Brain damage surgery

Brain damage surgery is a surgery to fix brain damage, if no mannitol is around. The steps are in order, scapel, hemostat, hemostat (remapping blood vessels) fix o vein (repairing blood vessels), cautery.

Brute and Burn damage surgery

Brute and burn damage surgeries are surgeries that fix 100 brute or burn on the chosen area. The steps are, in order, scapel, hemostat, retractor, scapel (scraping off burned flesh or severing ruined flesh), bruise pack/ointment, cautery. Can't be used on dead bodies, no cheese defibs

Sleepers

Sleepers now have new functions-they automatically notify you of any infections or broken bones and locations of them in the target body, and any damaged organs. It will also tell you what's causing someone damage if you put them in-for example, it'll highlight any toxin causing chemicals in them in red.

Medical Scanners

Medscanners now notify you of infection and infection stage, and tell you how much antibiotics are needed, and of any broken/fractured bones and where they are. They also notify you of organ damage and if the person is in deep shock.

Cyro

Cyro now doesn't tell you what chemicals are in it, only if a beaker is loaded, to allow for cyro sabotage. Having the clumsy gene gives you a random chance to trip and fall in yourself when cyroing someone.

To address antags/races

Race autoheal will automatically remove deep shock-this applies to podpeople, phytosians, shadowlings.

Fleshmend will also automatically remove it and fix broken bones and organs.

The adrenal implant will remove Deep Shock on activation.

Wand of healing will also obviously fix this.

**Comment by timkoster1** [comment]
This is beautiful, and with the new project dealio, we could probably code it in parts and have a gisnt rework,.

**Comment by Super3222** [comment]
Oh yeah, someone should really take this. It might seem like a lot but, you could always ask other coders for help on #coder. It'd also be a fun project.

Anyway, this is basically lightbaymed. Which we could call... YogMed.

**Comment by puremanbird** [comment]
woo! more stuff to do in medbay!

**Comment by ShadowDeath6** [comment]
remove gooncrit

**Comment by timkoster1** [comment]
Since we're doing the cool project thing, assign me to it.
Because I can't really do it myself, but I really want to do it.

**Comment by Dagdammit** [comment]
I like the sound of this alot.
