### ISSUE TITLE
text2ratvar isn't working properly

### ISSUE THREAD

**Issue by SomeguyManperson** [yogstation13/Yogstation#8523]
## Reproduction:

say anything in ratvarian/see thing that uses text2ratvar
it will be missing most spaces and half the characters
example is ratvar's summon monologue being BAALGFAFBAGFCGGFGEF which is gibberish

**Comment by Jarod1200** [comment]
It seems to be deleting letters A through M on the English translation (N through Z in ratvarian) 
(Hopefully this picture helps)

![20200518_033956](https://user-images.githubusercontent.com/54733446/82186865-8373d680-98b9-11ea-89d9-e4cebbc2de08.jpg)
