### ISSUE TITLE
Time erasure stand ability makes c20-r unusuable

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#8548]
and presumably other guns

notes:
was holding the gun
holoparasite had C in potential
had 2 additional arms and 3 eswords held

**Comment by jcatjmeow** [comment]
not a bug. You can't use guns in stopped time. its a balance thing.

If you can't fire the bug after the effect is over, then yeah that's a bug. @ynot01 can u tell me which one u meant

**Comment by ynot01** [comment]
@jcatjmeow yes you can't fire after it's over thats what i meant by unusable in the title
