### ISSUE TITLE
Mech bay 2APCs1room

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#855]
Red squares are APCs' locations, one in maintenance.
"This area already has an APC" - cannot replace the one for Mech bay.
If this is true for all locations, then just nearby, Paramedic room has 3 APCs on it, Morgue has 2, etc. ...

![ss13-2apcs1room](https://user-images.githubusercontent.com/16806055/40181891-75032a0c-59ea-11e8-9bbe-c756dd03a826.png)

**Comment by Amelia0010** [comment]
![image](https://user-images.githubusercontent.com/20558591/40206164-280fff32-5a2f-11e8-94c0-7d03d9579437.png)
the APC in the bottom right is the APC for the robotics lab, not the one for the mech bay.

**Comment by 00aquir** [comment]
@nichlas0010 The game didn't let us replace the APC for **the same wall on which it was**, in the maintenance, as stated earlier: the one for Mech bay.
You can only replace the APC from inside the room (or standing inside the maint door), and it won't let you do that anywhere from the maintenance side.

Is this interpreted as it's in the morgue maint because the terminal portion of it belongs to that area?

**Comment by 00aquir** [comment]
Update: you can only replace the APC from inside the room (or standing inside the maint door), and it won't let you do that anywhere from the maintenance side.

**Comment by Amelia0010** [comment]
yes.
