### ISSUE TITLE
can someone fucking nerf virology please

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#857]
like i mean i know there's no reason but come the fuck on dying of this bullshit and then watching a traitor viro release beesease is really triggering me

**Comment by ShadowDeath6** [comment]
drink sugar, take your own blood, go to viro, drink vaccine

**Comment by tromacodes** [comment]
What if RnD could make cures at high research levels? Like nanotechnology-robots from Star Trek or something.  It would add some redundancy to cures incase medical can't do it. A lot of station crisii have redundant solutions but not virology. This might be a good nerf solution without directly nerfing viro to uselessness.

**Comment by ShadowDeath6** [comment]
>>>>>>>>>>>>>>>>>>>>>buffing R&D

**Comment by AdamElTablawy** [comment]
i am literally dying and this was a joke ffs

**Comment by EMT321** [comment]
@Cruix can we close this, if it's been resolved?

**Comment by X-TheDark** [comment]
Hope you get well soon, Adam.
