### ISSUE TITLE
Generic golem start text is inaccurate pending on golem type

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#8573]
Generic text:

You are a Golem.
You move slowly, but are highly resistant to heat and cold **as well as blunt trauma**. You are unable to wear clothes, but can still use most tools. Serve [xxx], and assist her in completing her goals at any cost.

I was a glass golem:

As a Glass Golem, you reflect lasers and energy weapons, and are very resistant to burn damage. However, **you are extremely vulnerable to brute damage**. On death, you'll shatter beyond any hope of recovery.

You get both these messages, this makes no sense.

**Comment by jcatjmeow** [comment]
This isn't really an issue... but I'll keep it open for now.

**Comment by MegaEmpirical** [comment]
Slanderous lies, false information is always an issue.
