### ISSUE TITLE
Imaginary friends cannot see their self

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#8574]
What is this horse shit?

Also, I had to aghost and re-enter my body just to be able to move.

**Comment by adamsong** [comment]
I've done a little testing with imaginary friends for a different issue and didn't experience this, is this still happening?

**Comment by MegaEmpirical** [comment]
Are there two types of imaginary friends as that might have been the issue

**Comment by MegaEmpirical** [comment]
Since Adam didn't find anything and I've not seen nor heard anything new about this, closing.
