### ISSUE TITLE
Broken Ruin

### ISSUE THREAD

**Issue by Super3222** [yogstation13/yogstation#858]
![](http://image.prntscr.com/image/275d666ca77742d19e1fef77f0d2697c.png)

I don't know it's name.

**Comment by ShadowDeath6** [comment]
it's the clown ruin or whatever

also I've never seen that happen

also also why do you have a donk pocket in your pocket you fuckboi

**Comment by AdamElTablawy** [comment]
it isnt' REALLY open to space it just looks like that

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Also why do you have a pickaxe instead of a KA and why do you not put the knife in your shoes

you suck at mining

**Comment by Super3222** [comment]
KA is in my backpack
and i just left a survival capsule, munching on a donkpocket, and was in a rush
buuut that's besides the point

I know Stealth had a similar problem with one of his maps being exposed to space, so I suspect this one is like that as well.

**Comment by ClaudeWicked** [comment]
Okay, no, actually, it really is exposed to space. Those rusted walls, if clicked, will actually open to space.
