### ISSUE TITLE
Give maintenance back to the people. 

### ISSUE THREAD

**Issue by tromacodes** [yogstation13/yogstation#860]
I saw a few servers that allowed maintenance access but it could be restricted to security and engineering from a key-swipe console. We do the opposite and rely on command to unlock maintenance when rad storm events hit or other emergencies which rarely works.

**Comment by ShadowDeath6** [comment]
meh, maybe give one for sec to use but not engi

**Comment by AdamElTablawy** [comment]
assistants and clowns having maint access is a config option
