### ISSUE TITLE
ERT overhaul

### ISSUE THREAD

**Issue by tromacodes** [yogstation13/yogstation#861]
Admins rarely initiate ERT. I would like to go to the bay system where a twin swipe at two different swipe-consoles can call an ERT.

 I would also like to see a gear center for ERT at centcomm, all types of ERT getting the same gun (advanced energy gun), maybe telecrystal-like system for them to get additional gear, and a micro-bomb that goes off when they die to destroy gear and prevent antags from playing ERT dress-up and impersonation. 

 We might need to add some rules for ERT play but I think a lot of them already exist in generalized form with the current rules governing security and command staff.

**Comment by Super3222** [comment]
I've always thought about and, even previously mapped out an ERT overahul system.

It's pretty much everything you mentioned, given that the ERT's are more spread out through green, blue, red, and delta emergency.

I also wanted to make each individual ERT have their own advanced weapon/tool that represents their own division. They're lacking that, sort of.

**Comment by tromacodes** [comment]
I want the main weapon ert uses to be standardized. Otherwise people are going to loathe getting medical or engineering ert roles.
