### ISSUE TITLE
Ghosts not getting a notification to re enter corpse when defibrilator paddles placed on chest

### ISSUE THREAD

**Issue by Jarod1200** [yogstation13/Yogstation#8651]
Round ID: 29647

I was the CMO and a blob started growing in the brig. The blob killed multiple people and their bodies were brought to me. I defibbed multiple people and they all got the "brain inactive future attempts may be useful" or whatever it is text. After the round I asked the warden and she said she didn't get a notification while I was defibbing her even though I tried like 10 times or something.

**Comment by jcatjmeow** [comment]
Tested. Was able to reproduce. It simply does not alert you anymore.
