### ISSUE TITLE
Player was able to hear deadchat while alive

### ISSUE THREAD

**Issue by MenacingManatee** [yogstation13/Yogstation#8686]
## Round ID: 0

Player reported being able to see deadchat while living. I had them relog, which didn't fix it

**Comment by Hopekz** [comment]
> Player reported being able to see deadchat while living. I had them relog, which didn't fix it

Any more detail?
Round ID?
Who was the player during that round?
(To troubleshoot when we go log diving)

**Comment by boodaliboo** [comment]
theres a brain trauma that does this alongside the scrying orb

**Comment by jcatjmeow** [comment]
unfortunately there is no real possible way to reproduce this given the vague nature of it. If it ever happens again, please let me know, and try to get as much info as you can
