### ISSUE TITLE
 AI's will be moved, even if bolted, when ran into.

### ISSUE THREAD

**Issue by Xoxeyos** [yogstation13/Yogstation#8706]
## Round ID: 29706

AI's will be moved, even if bolted, when ran into.

**Comment by jcatjmeow** [comment]
Well, I was unable to reproduce this bug.

I did find that you can push an unbolted ai into a door to open it. Which is pretty funny. But it's not a bug.

I watched the replay for that round and it appears the ai simply forgot to renable their bolts.
