### ISSUE TITLE
Alternative medical rework suggestions

### ISSUE THREAD

**Issue by Ephemeralis** [yogstation13/yogstation#871]
Adam's design for the med rework while pretty exceptional and honestly spot on, probably isn't for most of our playerbase. Complexity in medical frustrates more people than it gives enjoyment to, but the long-standing issue of letting medical roles pretty much be useless can't really stand.

Bandages pretty much showed that healing over time effects are good, and instant healing pretty much wrecks any purpose for medbay.

Stemming from that, I think there's a few things we can do to help improve the system as-is short of reworking the entire thing into paradise-med:
1. Cap all self-healing (bandages, self-applied patches) at a reasonable value.

Patches/bruisepacks/ointment in general are responsible for most of medical's uselessness as a department. I nerfed them once relatively unsuccessfully by quartering their total value, which didn't really improve things and just frustrated people to no end.
- Improv. bandages cap at 60 _limb_ health
- Medical bandages cap at 80 _limb health_
- These values decrease by 5 for each successive use of the "used" bandage, eventually depleting their effectiveness along with their overall healing rate
- Patches lose no potency overall, but have their instant healing severely reduced to 20% of their overall healing value, and the subsequent chemical metabolism rate decreased to 0.6x overall.
- You apply a patch, it heals a reasonable chunk of instant damage, then takes time to work after that.
- Repeated use of patch or TOUCH healing chemicals confers a loss in potency. This will last across an entire round, scaling down to 50% of their total potency after say.. 200-300u's worth of ingestion via the TOUCH method.
- Alternatively, give toxicity levels to chemicals introduced via TOUCH effects.
- Bruise packs and ointments will no longer heal serious wounds (above 65 limb damage) at all for non-medical roles.

Doctor roles will receive natural bonuses due to their training when using these items, negating some of these deficits (not the patches ones or the potency loss).
1. Cryoxadone and its associated improvements will no longer heal non-clone damage above 20 health.

This alone will stop people using them as a crux to negate most of medbay's work. This is important for the following changes.
1. Equip medical centers/areas with infinite sal-glu clone reagents (not actually sal-glu because that would be dumb, but a "generic" reagent type that pretty much does the same thing) which can be used via injection or IV to provide "quick" healing to wounds.

This reagent will have a reasonably low toxicity threshold compared to other medical chemicals meaning that trying to flood someone with it will just make their wounds worse. This relies on the following change as well:
1. Add (or increase the prevalence of) drugs that increase the metabolism rates of other drugs, or specifically medical chemicals.

This will encourage the ever-beneficial chemist-doctor relationship and have a good pair of players essentially bringing back the old instant-healing days of yore, except through actual work and supply in-game. The values of this will need to be tweaked heavily, as it could potentially impact a lot of things.
1. Add a flat increase to healing speed chemicals when "resting" or buckled to a bed of some description.

Lying down and talking to people in your near vicinity while you heal faster will encourage interaction and also open vulnerability windows for opportunistic people to take advantage of. You obviously don't need to do this, but I think this is some innate functionality that should be in the game anyway.

**Comment by AdamElTablawy** [comment]
no, i want my goddamn rework i spent ten minutes on that

if people don't like it they can get fucking good and play it

not to mention people don't play doctor because it's lame

this makes it less lame

**Comment by Zostroll** [comment]
What about minners?

**Comment by AdamElTablawy** [comment]
miners can choke on a fat dick

**Comment by Zostroll** [comment]
Adam no need to mince your words. Say what you really mean!

**Comment by tromacodes** [comment]
No medical nerfs please. It's just going to be the same issues we had last year because these are the nerfs from last year with a slight twist.
 Bandages are not the problem. Do nothing medical staff, nonexistent staff, and shove them in a sleeper and let cryox figure it out are the problems.

 And anyone with a brain should figure out that if medical is working that they can be frugal with thier medkits and let them do it instead.

 How about something we need like dialysis?  Bay has dialysis in their sleepers.

**Comment by Ephemeralis** [comment]
Did you even read what I wrote fully? Judging from your comments, it seems not.

**Comment by Dagdammit** [comment]
How will the changes to touch patch mechanics be communicated in game? 

Initial message could be changed to something like "you feel your injuries **beginning** to heal" or "You apply the patch. The chemicals start to take effect..." 

When the potency starts being reduced: "You apply the patch. The chemicals take a second to kick in..."

When the reduction is nearing 50%: "You apply the patch. It doesn't feel as effective..."

Toxicity as in toxin damage seems like dumb idea, but maybe there's a chance to vomit & drop held items if you take another patch while touch-delivered chems are still in your system. "You apply another patch at the same time. It makes you feel kinda nauseous..." and maybe "the patch has stopped tingling" when the chems are gone.

**Comment by Dagdammit** [comment]
Patches definitely need SOME interesting downside. As is they clearly outdo everything else way too often.
