### ISSUE TITLE
Rapid Piping Device (RPD) images for what it'll output are fucked

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#874]
Exactly as the title says, see image. Been like this for about two days, as of post.

![image](https://user-images.githubusercontent.com/36208065/40209653-87f8dae8-5a0e-11e8-8fb1-00c1ce274339.png)

**Comment by ThatLing** [comment]
Did you clear your BYOND cache?

**Comment by MegaEmpirical** [comment]
I have now and it is still an issue. Was it not for you?

**Comment by Amelia0010** [comment]
https://github.com/tgstation/tgstation/pull/37905
