### ISSUE TITLE
Outdated Canvas Included in YogsPubby

### ISSUE THREAD

**Issue by alao3alao3** [yogstation13/Yogstation#8802]
## Reproduction:
![apng](https://user-images.githubusercontent.com/62276730/83726146-19756400-a611-11ea-89c3-3b0de358815a.png)

YogsPubby starts out with a canvas on an easel in the perma. When interacting with the canvas, a bluescreen appears. Given how canvases were removed, this too should be removed. Kind of testament to how little pubby gets picked.

**Comment by jcatjmeow** [comment]
Hilarious. Feature, lol!

**Comment by jcatjmeow** [comment]
#8291
