### ISSUE TITLE
[admin] cant remove antag status from vamps

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#8812]
![](https://i.imgur.com/4tmnX5M.png)

fancy varedit required to actually remove it and even then it doesn't remove most of the shit just from checkantags

according to tbanner same goes for malf ai

**Comment by ToGWtF** [comment]
Going to tack onto this, you need to VV their mind.antag daum and delete it as well as change their mind.specialrole VV to fix them iirc

Here are some other issues
Vampire has no remove objective
Cannot give a vampire a blood objective
