### ISSUE TITLE
Wizard shard should give wiz hud to constructs (and shades).

### ISSUE THREAD

**Issue by ghost** [yogstation13/Yogstation#882]

**Comment by Amelia0010** [comment]
i'm so proud

**Comment by ghost** [comment]
I would try to code this in, but I do not know how to code. Also, please confirm that wiz hud is also given to constructs so this issue can be closed.

**Comment by Mr-Space** [comment]
This has been untouched for over a year. If you want to request this feature please use the forums (https://forums.yogstation.net/index.php?forums/suggestions.9/) instead.
