### ISSUE TITLE
You can have a bag's inventory open while it goes into a bluespace body bag

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#8821]
What this means is you can then put the bluespace body bag inside of the bag, which is inside of the bluespace body bag

This makes the bbg and the contents within unaccessible

UNLESS

When deleting the person that did this, the body bag's contents to spill out where they were deleted

![](https://i.imgur.com/iT3jDig.gif)

**Comment by ToGWtF** [comment]
also applies for lockers. if you have your backpack menu open when sec puts it in a cell locker you can still get your stunbaton out of it
