### ISSUE TITLE
Proposed pAI improvements

### ISSUE THREAD

**Issue by Ephemeralis** [yogstation13/yogstation#883]
With the pAI software refactor completed and holoform ported over from the old codebase, we now need to sit down and hash out the limitations of the pAI role and what we can actually give it without breaking things.

Fundamentally, the pAI role is as follows (from my perspective, at least):
- Based heavily on cooperative gameplay. pAI players are very weak on their own and have very little agency for furthering their own agendas.
- Equipped with tools (software) to assist other players in largely **intelligence gathering and information processing** affairs. Think a digital scout.
- Highly mobile when in holographic form, but vulnerable to dedicated pursuit and disabling

What I essentially envision for a good pAI player is someone that understands a variety of game mechanics, and is particularly suited towards helping other people achieve their aims in the game. 

For example, an engineer that takes a pAI should have a companion that is suitably mobile and equipped with enough metrics-based software to help him determine where power outages are and so on. A traitor that takes a pAI should have a guaranteed assistant companion that can rove around the station looking for targets and scoping out the general state of the round for them.

So, this is what I propose we get started with first, once the nuances of holoform implementation are sorted out:
1. Introduce new "cloaking" software for holographic pAI units. At a huge ram cost (60+), this software will permit pAI players to turn themselves invisible for lengthy durations of time at the expense of periodically damaging themselves. Cloaked pAI units can be knocked out of stealth by moving into the tile they're sitting in. Cloaked pAI units can also move, but at significantly reduced speeds. This would provide a clandestine options for players who prefer to spy themselves, rather than having software do it for them. The ram cost will be tailored to specifically deny the useful metric-based software from cloaking pAIs, meaning that they will need to physically endanger themselves and risk being revealed in order to gather information.
2. Reintroduce the ventcrawling software package. At a nominal ram cost (30+), this will permit the pAI to use the vent system to snoop around areas they could never normally access, with all the limitations associated with ventcrawling as it currently exists in the game. An intrepid stealth pAI could take both cloaking, ventcrawling and the PDA messenger to stalk targets in high-security areas away from their host.
3. Massively expand the suite of metrics software available, and the general quality of it. Medical and security suites will have their huds bundled in with read-only access to the records. Search functionality by fingerprint, dna and blood id will be added. Engineering metrics software will be added, such as viewing station powernet status, SMES values and drain rate, and potentially even a list of all APC units along with their status. Science equipment could involve reagent scanners
4. Reintroduce camera-jacking software at a high ram cost (60+). A pAI would be able to take control of up to 4 cameras and their motion alarms with nominal risk of alerting the station AI. This information would then be fed to the pAI and its host, allowing them to use such things to their advantage.
5. Luminosity "beacon" hardware upgrade. This would allow the pAI to expend some of their health to temporarily increase the amount of light they give off in holographic form by a significant degree. As this has potential to interrupt some antag types, it would be balanced to be a very high-cost exchange for the pAI, probably taking more than a third of their health to perform.
6. Add a round-start option to become an unbound pAI for donators and above. Unbound pAI would be initially locked to no master, have full access to holoform from the get-go.
7. Introduce a "flash" software type for 5 ram that removes all active software, refunding 60% of the overall ram spent to acquire it. Allows emergency software respeccing on the fly, but only once or twice per life, ever.

This sounds like a lot, but the software refactor I've pushed forward makes pretty much everything here trivial to add. Thoughts?

**Comment by Ephemeralis** [comment]
I've also had ideas mulling around for the players that prefer to remain stationary with their hosts, specifically involving being inserted into their normal PDA and subsequently turning the thing into a hellish monstrosity of information access and hacking-type goodness.

Double speed doorjacking, ability to infiltrate the AI systems (to a limited degree), ability to remote control multiple machines at once, that sort of thing.

**Comment by Drakkon** [comment]
D.A.R.K.O. approves with minimal respect.

**Comment by Alek2ander** [comment]
pAI is a role for people who ***died***. Stop buffing it.

**Comment by puremanbird** [comment]
An unbound PAI completely defeats the purpose. Remove the ventcrawl, the stealth, and the unbound Ai parts. The other stuff looks good.

**Comment by Drakkon** [comment]
I agree with the unbound pAI thing. Kills the purpose unless the master decides to free them. I'm fine with any new powers (preferable post-emag) until people start playing pAI without actually role playing.

**Comment by Ephemeralis** [comment]
I don't see why ghostroles need to be intrinsically neutered. You still can't influence a round in the same way as you could if you were alive, so what's the problem with playing a role that gives you actual options?

**Comment by doerakpoes** [comment]
Unbound PAI sounds more like some form of antag
would be pretty funny
but yhea i don't see a reason for unbound unless antag of sorts beceus what are you going too do as an unbound PAI troll people?
Also like vent crawl dont like stealth
