### ISSUE TITLE
Unsure the bug itself, but clockwork slab wouldn't work for me.

### ISSUE THREAD

**Issue by azzzertyy** [yogstation13/Yogstation#8834]
## Round ID: 29928

Unsure as to what the issue was or how it could've been caused, i was a mime, had not broken voweof silence, was using clockwork slab in my hand and yet it just repeated the same message stating it was humming and not reacting. I was a cultist of course. I could not return to reebee or do anything except sit there.

**Comment by Takahiru** [comment]
![image](https://user-images.githubusercontent.com/30001910/83982898-37d0ad80-a8f8-11ea-900a-a4846609eaf2.png)
It's on purpose. You need to be able to talk

**Comment by Takahiru** [comment]
delet this

**Comment by azzzertyy** [comment]
then why not add a message saying that, or, make it work for mimes. blood cults dont have this.
