### ISSUE TITLE
Space Ninja almost always spawns with one or more Nothing objectives

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#8835]
not game breaking just annoying to look at ya feel

**Comment by JamieD1** [comment]
> not game breaking just annoying to look at ya feel

Pretty sure this is intended as its a chance

**Comment by MegaEmpirical** [comment]
This is pretty well known and I can vouch for it, pretty sure it's confirmed. Though I assume it's intentional.

**Comment by adamsong** [comment]
If its intentional this should be closed
