### ISSUE TITLE
create a monster exlcusion zone around mining station where monsters dont spawn we just had mining station shuttle breached by golaith

### ISSUE THREAD

**Issue by immortalartisan** [yogstation13/Yogstation#8850]
# Feature requests are not handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums here: https://forums.yogstation.net/index.php?forums/feature-requests.221/

```
*************************************************************************************
**DO NOT POST THAT HERE.DO NOT POST THAT HERE.DO NOT POST THAT HERE.**
*************************************************************************************
**DO NOT POST THAT HERE.DO NOT POST THAT HERE.DO NOT POST THAT HERE.**
*************************************************************************************
**DO NOT POST THAT HERE.DO NOT POST THAT HERE.DO NOT POST THAT HERE.**
*************************************************************************************
**DO NOT POST THAT HERE.DO NOT POST THAT HERE.DO NOT POST THAT HERE.**
*************************************************************************************
```

**Comment by Ktlwjec1** [comment]
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the Yogstation13 forums here: https://forums.yogstation.net/index.php?forums/feature-requests.221/
*************************************************************************************
**DO NOT POST THAT HERE.DO NOT POST THAT HERE.DO NOT POST THAT HERE.**
*************************************************************************************
**DO NOT POST THAT HERE.DO NOT POST THAT HERE.DO NOT POST THAT HERE.**
*************************************************************************************
**DO NOT POST THAT HERE.DO NOT POST THAT HERE.DO NOT POST THAT HERE.**
*************************************************************************************
**DO NOT POST THAT HERE.DO NOT POST THAT HERE.DO NOT POST THAT HERE.**
*************************************************************************************
