### ISSUE TITLE
Head of security can apparently be a roundstart gang leader

### ISSUE THREAD

**Issue by Jarod1200** [yogstation13/Yogstation#8884]
see round 30015
HOS was a roundstart gang leader which was wack as hell and as far as I know not intended to happen.
round replay:
https://yogstation13.github.io/demo-viewer/?roundid=30015

**Comment by MegaEmpirical** [comment]
Extention of this issue, get in line:

https://github.com/yogstation13/Yogstation/issues/7677

**Comment by MegaEmpirical** [comment]
Also, already an issue, get in line:

https://github.com/yogstation13/Yogstation/issues/5182

**Comment by adamsong** [comment]
HoS is no longer able to roll as gang leader
