### ISSUE TITLE
Opening Cyborg Remote Monitoring Bricks Tablet Computers.

### ISSUE THREAD

**Issue by alao3alao3** [yogstation13/Yogstation#8885]
## Round ID:
30017

## Testmerges:
#8291: 'Ports tgui-next 3.0, removes tgui 1.0 + Smart Asset Cache' by TheGamerdk at commit ed55b235d6
#8598: 'Rebalances Security Grenades' by MacHac at commit ea19643320
#8864: 'Memory Profiler for Server use' by JamieD1 at commit 4002456f1f

## Reproduction:
I had downloaded Cyborg Remote Monitoring on my Tablet Computer (The one HoP recieves roundstart). I do not recall what other applications were installed. Upon opening said application, the screen read "Interface ntos_cyborg_monitor was not found." There was no way that the application could be closed. The window itself could be closed, but this made all other applications inaccessible, which sucked as I had downloaded a number of other programs. The mentor Xoxeyos tried to remedy this, but there was no way that the application could be "refreshed."

I was told that we did infact have a cyborg, named G.U.B, so the lack of borgs may not have caused this.

**Comment by ToGWtF** [comment]
you can screwdriver a part out and put it back in to fix this as a player

**Comment by Bibby0110** [comment]
Fixed
