### ISSUE TITLE
Shooting the podbay shutters with a beam rifle crashes the server

### ISSUE THREAD

**Issue by jcatjmeow** [yogstation13/Yogstation#8889]
## Reproduction: Shoot the spacepod podbay shutters with a beam rifle.
[11:27:52] Runtime in atoms_movable.dm,455: No valid destination passed into forceMove

This error occurred repeatedly even after my client crashed. The dream daemon log shows the error happening roughly 4 times every second until [11:28:26] when I managed to stop the server by pressing the little stop sign.

**Comment by redmoogle** [comment]
Jamie didnt close this, argh
