### ISSUE TITLE
Possessions and Ghost Hunting

### ISSUE THREAD

**Issue by Cruix** [yogstation13/yogstation#889]
A player asked if we could port this in a ticket:
http://hippiestation.com/showthread.php?tid=4828

**Comment by timkoster1** [comment]
Yesyesyeyseyaeseyea.
I am also adding ghost buster gear.

**Comment by darkwahn** [comment]
Sounds like it could be fun/interesting, feel like I'd need to see it in action to have a "real" feeling on it though.

**Comment by EMT321** [comment]
We have posibrains, cloning, defibs, lavaland roles, and drones + ouija boards. Ghosts should not have an active role in the game, except as spectators.

**Comment by Kmc2000** [comment]
Add this as a random event and it'll be cool

**Comment by timkoster1** [comment]
NO, WE'RE DOING THIS THE WAY IT'S INTENDED

**Comment by Alek2ander** [comment]
Don't port spooky ghosts. Port the gear though, and make it work against revenants, shades, blood demons, and other spooky shit that walks through walls.

**Comment by Super3222** [comment]
> Port the gear though, and make it work against revenants, shades, blood demons, and other spooky shit that walks through walls.

This. Ghosts are irrelevant unless conjured up by a spirit board.
