### ISSUE TITLE
tgui breaks and cant reopen

### ISSUE THREAD

**Issue by redmoogle** [yogstation13/Yogstation#8894]
TGUI cant reopen once open, only happens on yogstation and not private servers
Round ID: N/A(30047 if you're gonna pester me)

**Comment by ToGWtF** [comment]
I have a similar problem when I am on two servers at once

**Comment by jcatjmeow** [comment]
unable to reproduce, although I didn't try two servers at once.

I think this is fixed by now? Not sure. I think it's been fixed. @ me if you experience this bug still and I will reopen this
