### ISSUE TITLE
Paramedic Space Suit and Helmet Have Broken Sprites

### ISSUE THREAD

**Issue by alao3alao3** [yogstation13/Yogstation#8896]
[Round ID]: # 30047

## Reproduction:
On BoxStation, the Paramedic Space Suit and Helmet can be found in one of the paramedic lockers. The sprites as items are broken, the space suit being an array of dots and the helmet being invisible. When worn, the space suit is very revealing and cosmetically makes the wearer nude (save for undergarments). The helmet cosmetically removes hair, masks and glasses. This presents obvious practical problems.

It should be noted however that both the suit and helmet function normally.

**Comment by jcatjmeow** [comment]
Unable to reproduce. Likely fixed
