### ISSUE TITLE
DJ station being actually fun more than once in awhile.

### ISSUE THREAD

**Issue by R3DGL4R3** [yogstation13/yogstation#891]
Simply put,stick a sleeper similar to a lavaland sleeper on DJ station that spawns the player who gets to it first in as a DJ.An assistant with possibly a bit of fluff gear,like headphones or other guff.

**Comment by EMT321** [comment]
Reminder you can get to DJ station consistently by going west from the top of the Derelict. Which can be accessed easily at roundstart via the teleporter->Abandoned satellite->White Ship

**Comment by ParagonPrime** [comment]
i think he's suggesting more some sort of quasi fluff character, which i'm starting to like the idea of

it would be a rogue, independent station that NT just can't seem to suppress, run either by the Syndicate or somebody totally freelance, which broadcasts random stuff- and can listen in to all the radios, as well as being able to send out a report much like the heads of staff occasionally

radio frequencies include the syndicate channel, HOWEVER, the radio operator is technically an enemy of NT and should not be feeding security information on who's a syndishit unless they've struck up a really lovely deal- it's just there to make things a lil' bit risky for tators

the catch is that every time the station broadcasts something, from a simple radio message to a full-on announcement, there's a chance (raised with each broadcast) that security and command are alerted of the precise directions to get to the radio station (plus the teleporter suddenly being able to visit it), being able to raid it if they feel it's terrible enough

sorta like escaped prisoners, but with an emphasis on RP

**Comment by ClaudeWicked** [comment]
Maybe if the DJstation was made RNG, this would be fine.
