### ISSUE TITLE
can't open a locker with an ID in a PDA by swiping

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#894]
swipe locker with PDA with ID in it

it does not respond or react

put PDA in ID slot

you can open locker

#BRING BACK OPENING LOCKERS WITH ID-STUFFED PDAS 2016

**Comment by ShadowDeath6** [comment]
did u tri alt clic

**Comment by Cruix** [comment]
It's another problem caused by NOBLUDGEON
