### ISSUE TITLE
No is_a_number check on radio / intercom frequency input field

### ISSUE THREAD

**Issue by Delams-The-SM** [yogstation13/Yogstation#8941]
Issue reported from  Round ID: 30110 (Yogstation 13)

Reporting client version: 513.1525

Currently it appears that there is no check on frequency imputed into radio/intercoms allowing frequency to be set to NaN by inputting a non number character.

Once radio is set to that frequency it is impossible to set a normal numeric frequency making the radio unusable.

![NaN_Comms](https://user-images.githubusercontent.com/66973657/84932784-1ed4b300-b0d5-11ea-9a4c-b0d2f3d6426f.png)

**Comment by jcatjmeow** [comment]
I will take a crack at this and see if I can't bang it out

**Comment by jcatjmeow** [comment]
@o0unknonw0o1 Can you tell me what steps you took to reproduce this? I cannot reproduce it on my local branch

**Comment by Delams-The-SM** [comment]
Just inputed a non number character, like for example first time it happend i inputed a "," insted of "." for frequency

**Comment by Delams-The-SM** [comment]
I just tried it by inputing "a" as frequency 

![nanradio](https://user-images.githubusercontent.com/66973657/85069054-bf99a000-b1b3-11ea-8365-f3b9d5c6f5da.jpg)
