### ISSUE TITLE
singal tech translating powergaming!!

### ISSUE THREAD

**Issue by Hopekz** [yogstation13/Yogstation#8948]
Tcomms scripts can translate codespeak and other languages they probably shouldn't be able to translate.

Long time bug but finally making an "issue" for it

**Comment by Jumps0** [comment]
mouse is yelling cringe over comms ban he

**Comment by redmoogle** [comment]
well it's because you can set the sig.language to 1 but it should be a read-only var

**Comment by MegaEmpirical** [comment]
Sounds more like feature.
