### ISSUE TITLE
Dynamic Zombie dysfunctional

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#8950]
when zombie midround is rolled on dynamic it just spawns the chosen player (un-mulliganned) unclothed at the arrivals shuttle fully alive without zombie status or romerol tumor

**Comment by Xoxeyos** [comment]
Working on this now.

**Comment by jcatjmeow** [comment]
@Xoxeyos still working on this?

**Comment by Xoxeyos** [comment]
@jcatjmeow I can't confirm if it works until dynamic is rolled / forced, and zombie is rolled / forced.

**Comment by ynot01** [comment]
Dynamic no longer exists
