### ISSUE TITLE
new airlocks won't stop areas from being spaced if they are open when a shuttle leaves

### ISSUE THREAD

**Issue by SomeguyManperson** [yogstation13/Yogstation#8965]
door is open
shuttle departs
door begins to close
door is technically not "closed" the instant the shuttle leaves
air falls out

**Comment by gaminada** [comment]
I saw this happening on meta station where the airlocks don't have the cycling pressure mechanism where they automatically bolt, any time the Arrivals shuttle would leave, the whole area would get space through the airlock the person used to get off the ship

**Comment by SomeguyManperson** [comment]
even occurs in areas where the doors do automatically bolt if the exterior door is open, usually results in the airlock and the nearby room being decompressed since the interior door will be bolted open

**Comment by ynot01** [comment]
directly related to https://github.com/yogstation13/Yogstation/pull/8811

**Comment by monster860** [comment]
fixed by #10398
