### ISSUE TITLE
"mime" block

### ISSUE THREAD

**Issue by Darthkill** [yogstation13/Yogstation#8966]
Issue reported from  Round ID: 30148 (Yogstation 13)

Reporting client version: 513.1526

![Mime block](https://user-images.githubusercontent.com/33874385/85185024-1a053000-b28a-11ea-9a20-16d2c6cfa6f3.png)

I cannot move into this tile.
I spawn on this tile, i moved off it and then was unable to get back to it.
Another person came to see and they had the same issue.
I had this occur another time but on an escape pod where the front seat was blocked.

**Comment by ToGWtF** [comment]
Fixed in https://github.com/yogstation13/Yogstation/pull/8971
