### ISSUE TITLE
Medibot speech font is incorrect

### ISSUE THREAD

**Issue by Yewmi** [yogstation13/yogstation#897]
The Medibot's speech font is incorrecty displayed as the default human speech font when stating something. However for all other speech the font is correct.
![dreamseeker_2016-09-27_17-23-39](https://cloud.githubusercontent.com/assets/22177874/18894192/365e4f14-84d7-11e6-98f5-ee7702cab5cc.png)

**Comment by AdamElTablawy** [comment]
Already resolved
