### ISSUE TITLE
Blank pop-up windows

### ISSUE THREAD

**Issue by gaminada** [yogstation13/Yogstation#8980]
Any time i interact with something that produces a pop-up window, such as consoles, machines, hacking airlocks, the main lobby menu, also mid-round antag pop-ups. They all appear blank the first time they come up. With most machines i can just close the window and open it again, or reconnect, but with mid-round antag windows there's nothing i can do other than close them. 

This didn't happen prior to the smooth airlock update

![image](https://user-images.githubusercontent.com/67234303/85228901-6482cb80-b3b4-11ea-8680-bb9366c191d8.png)

**Comment by gaminada** [comment]
it was just a matter of reinstalling byond.

**Comment by gaminada** [comment]
im an idiot, the midround antag pop-up still comes up blank after reinstall

**Comment by jcatjmeow** [comment]
Was able to reproduce @gaminada but I'd appreciate help from you or others on exactly *when* it happens. Seems to happen at random for me

**Comment by adamsong** [comment]
I'm pretty sure its just the windows being slow to load

**Comment by UselessTheremin** [comment]
this has most likely been rectified with the tgui updates, i've never had any report of this and if it comes back up i will deal with it but this does not seem to be a solveable issue
