### ISSUE TITLE
Nerf secway

### ISSUE THREAD

**Issue by daklj** [yogstation13/Yogstation#900]
With the movement speed change secway became stupidly overpowered. In the current state secway:
+ gives you permanent bullshit speed increase
+ gives you slip resistance
+ gives you thrown weapon resistance
+ removes the speed penalty from low stamina/health
+ removes the speed penalty from wearing hardsuits and such
+ covers your chracter sprite making it harder to click you
+ blocks some special projectiles (colossus bolts etc.)

Same applies to other "vehicles" which clearly weren't balanced around the new reduced movement speed and should have their speed relative to RUN_DELAY rather than absolute

**Comment by Altoids1** [comment]
Basically resolved by #1205, and by my double-check they're no longer on YogsBox anymore. Closing.
