### ISSUE TITLE
Computer console sprites all black forever

### ISSUE THREAD

**Issue by ynot01** [yogstation13/Yogstation#9007]
Reporting client version: 513.1524
others also report same

The following pull requests are currently test merged:
#8917: 'Adds the ability to tip medbots over (and they cry too)' by swissloaf at commit e92dcdcd49
#8893: 'Techweb UI layout rework' by monster860 at commit 97d8ecee43
#8819: 'Ports body cams from prebase!' by jcatjmeow at commit 2354a31f77
#8964: 'Port my SM rework to Yogstation' by redmoogle at commit 374437efc0
#8901: 'Smooth Doors' by monster860 at commit 9cfad04f06
#8874: 'The Devil wears a suit and tie' by ToGWtF at commit ace067ccf3
#8727: 'Cryopods' by JamieD1 at commit 0c70fef908
#8697: 'Removes BSQL' by TheGamerdk at commit b0cdd8c32

**Comment by Bibby0110** [comment]
very helpful issue report

**Comment by jcatjmeow** [comment]
This is a related issue to some others, including conveyors not animating and having a weird arrow on them.

Basically what is happening is the map sprites for everything are existing as their in game sprites. Why? Dunno.

**Comment by redmoogle** [comment]
I think this is related to apcs appearing black because it failed to add the overlay

**Comment by jcatjmeow** [comment]
> I think this is related to apcs appearing black because it failed to add the overlay

yes this is the same issue

**Comment by jcatjmeow** [comment]
https://github.com/yogstation13/Yogstation/pull/9016
