### ISSUE TITLE
Suggestion: Add a couple welding goggles near engineering hardsuits

### ISSUE THREAD

**Issue by Dagdammit** [yogstation13/yogstation#902]
The same change that gave hardsuits jetpacks took away their eye protection. I actually prefer this to a straight hardsuit buff, but sometimes you gotta weld in vacuum.

**Comment by Zostroll** [comment]
Umm no it didn't....

**Comment by Zostroll** [comment]
I only gave them jetpacks https://github.com/yogstation13/yogstation/pull/780/files if the engineering isn't welder resistant anymore it wasn't me. Also the atmos hardsuit is still welder resistant. I haven't tested the engineering one yet.

**Comment by EMT321** [comment]
Upon testing, atmos hardsuit is still welder resistant.

**Comment by Dagdammit** [comment]
But engie is not?

(sorry, at work so I can't double check myself)

**Comment by EMT321** [comment]
Both are.

**Comment by Dagdammit** [comment]
Huh, weird! Ignore me then, maybe I had my helmet down and didn't realize or something.
