### ISSUE TITLE
Drone's problem

### ISSUE THREAD

**Issue by ghost** [yogstation13/Yogstation#9023]
Issue reported from  Round ID: 30233 (Yogstation 13)

Reporting client version: 513.1525

hello, I had a problem today with the drone, because it can't get under the airlocks, so opening them up instead of going underneath, I don't know if this is a bug but it gets in the way of the gameplay as a drone. I hope you fix this, as the gameplay with the Drone is supposed to be something "discreet", but with it opening airlocks can make it difficult. I appreciate the possible help :)

**Comment by jcatjmeow** [comment]
HC's dreamchecker is the issue. Related to #9025
