### ISSUE TITLE
Crew manifest app printing HTML markup.

### ISSUE THREAD

**Issue by Delams-The-SM** [yogstation13/Yogstation#9033]
Issue reported from  Round ID: 30248 (Yogstation 13)

Reporting client version: 513.1525

Crew manifest app on modular consoles prints with HTML and not proper paperwork markup making it unusable.

To replicate: open Crew manifest on modular console (for example in bridge) and use print option, the paper will have HTML markup insted of paperwork one

![Crew_manifest](https://user-images.githubusercontent.com/66973657/85805538-ea07d200-b74c-11ea-815d-3f56579edc6a.jpg)

**Comment by redmoogle** [comment]
Tested
