### ISSUE TITLE
Painting Frames Pop Out of Walls When Placed

### ISSUE THREAD

**Issue by alao3alao3** [yogstation13/Yogstation#9038]
[Round ID]: #30254

## Reproduction:

I had crafted painting frames from wood, and placed them blank onto a wall. They visibly stick out of the wall.

![apng](https://user-images.githubusercontent.com/62276730/85830432-97cdad80-b75a-11ea-92e5-f5e61c017d90.png)

**Comment by jcatjmeow** [comment]
This seems like someone has the pixel_x and pixel_y values wrong. Shouldn't be that hard of a fix

**Comment by jcatjmeow** [comment]
Turns out that wasn't the issue... 😩 but I got it down
