### ISSUE TITLE
Poor tendril drops.

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#906]
The tendril drops a sad trombone implant that has no sprite and can only be picked up with a right/alt click on the opened crate. You then can't really do anything with it. It also takes up the hand slot you picked it up with until you drop it. It is worse than useless.

**Comment by Super3222** [comment]
It came from https://github.com/yogstation13/yogstation/pull/788. Quiet literally as useless as the SORD which was removed in the same PR. Please change it to something valuable.
