### ISSUE TITLE
Mediborgs Sometimes Can't Interact With People

### ISSUE THREAD

**Issue by fenn96** [yogstation13/Yogstation#9073]

**Comment by jcatjmeow** [comment]
I wasn't able to replicate this.
I'll leave it open since it apparently only happens sometimes but i can't for the life of me find out why or when

**Comment by Moggram** [comment]
I have had this happen to me in a round I just played. Did it when I was changing chems in the Cyborg Hypospray and when I was using Advanced Surgery: Tend Wounds Max.

**Comment by Xoxeyos** [comment]
Yup, I've had this bug too, usually doing surgery, and sometimes you cannot apply chems to a guy lying down.
