### ISSUE TITLE
Miners having QM Office Access

### ISSUE THREAD

**Issue by Dzlan** [yogstation13/yogstation#909]
A miner had access to the QM office, immediately after joining.
They should not. It was during a low population (8 ish people) round.

**Comment by timkoster1** [comment]
Everyone has all acces at round start because the subsystem didn't start, everyone is invincible then aswell.

**Comment by Dzlan** [comment]
No, this is throughout the entire round. Miners have access to QM office.

**Comment by timkoster1** [comment]
Forget what I said then.
Likely because of the skeleton crew

**Comment by AdamElTablawy** [comment]
@Dzlan 

Skeleton crew-AKA extremely low pop such as 8 or so-Gives people access they do not normally  have.

**Comment by Dzlan** [comment]
I am aware of that Adam, but that does not mean they should be given access to their superiors office. There is absolutely no reason a miner requires access to the QM's office.

**Comment by AdamElTablawy** [comment]
it does on lowpop.

**Comment by Dzlan** [comment]
Can this be fixed? That shouldn't need to happen. There is nothing in the QM office for miners, at all.

**Comment by EMT321** [comment]
It's meant for lowpop, when there might be just a single miner running cargo.

Feature, and a good one at that.

**Comment by Dzlan** [comment]
So, why do they require QM office access?
Why don't they go to the HoP like Intended. A miner can run cargo with legitimate cargo access during low pop, which I agree is a nice feature. But they do not require access to the QM's office to do so.

**Comment by EMT321** [comment]
Because when there are <15 people, and no HoP, that's an impossible task.

This is an edge case, only applicable on super-lowpop. The pros (increased access so 1 person departments dont stagnate) outweigh the cons (Possible sharing of space between multiple people).

**Comment by Dzlan** [comment]
I disagree plainly because, it is not needed for the miner to have "QM Access to do the cargo job."
"Cargo access works perfectly fine."

**Comment by EMT321** [comment]
Someone running cargo could also need the door remote and top level PDA cartridge. Both of which spawn in QM's locker.

**Comment by Groudonmaster** [comment]
The real question is, is this really a problem? What's in the QM's office that is round altering? Absolutely nothing is what.

**Comment by Time-Green** [comment]
It's a personal space.

**Comment by Groudonmaster** [comment]
That's a retarded argument and you know that Time

**Comment by Groudonmaster** [comment]
If somebody tries to break into your office with access just telebaton and beat them with said telebaton until they get the hint to fuck off

**Comment by Time-Green** [comment]
How?
It's the QM's office and there isn't anything that's vital should the miner decide to run cargo.
And if they necessarily want some pda cartridge just ask for freaking acces.

**Comment by Cruix** [comment]
The QM doesn't get a telebaton or a flash. All he can do is yell at the person with his megaphone.

**Comment by EMT321** [comment]
The door remote is absolutely a useful tool. It spawns in the QM locker.

**Comment by AdamElTablawy** [comment]
# WHO CARES

**Comment by puremanbird** [comment]
I dont know, i see Dzlans point. Theres literally nothing in the office that a miner would need, under almost any situation. If i spawned as a QM on super low pop and some miner just kept walking in, i'd be annoyed. Especially if i played QM 98% of the time.

**Comment by Super3222** [comment]
Miners shouldn't have access to the QM's office at all. If you don't need it, than you don't get it.

Cargo Techs, I'm skeptical.

**Comment by Groudonmaster** [comment]
The only argument people are having is that they don't want people walking in there.

But if there's nothing in there why would they walk in there?

**Comment by Time-Green** [comment]
This is space station 13.
Even if the caps office is cleared of important items, the cap still wouldn't be fine with people being able to walk in and out, and they will.

Personal space. If miners want to run cargo, they don't need QM's office, they can ask HoP for acces if needed

**Comment by Dzlan** [comment]
For as long as I've played SS, A single cargo tech without QM access has been able to run cargo.
Giving miners access to the cargo bay and the console, is enough during low pop. But that is all they need. The door remote, by the way, is not supposed to be readily accessible by miners and cargo techs for the same reason, door remotes in other departments are not supposed to be accessible by non heads.

The only other things in that office, are all accessible by default in the cargo office.

The reason I care, is because the entire point of playing QM above a cargo tech is to be recognised as the head of the department and to have you're own personal space when you feel the need for it.
Yes, in 99% of cases this doesn't pose a problem. Most of the time, a miner or tech won't bother to walk into the office, but that isn't the point.

The point is, they shouldn't need that access. Plain and Simple. Honesty, just saying we should let this go for the sake of it because it's a miner issue  (Pun intended, ha), when it is so easily fixable, is pretty arrogant, and so are comments such as "Who cares" which makes me question why you're even involving you're opinion.

I don't want to make a huge deal, like this is the most important thing.
But the fact is, there is little to no reason for it and it's easily fixable. And it kind of takes out the entire point of having a separate QM role during these low pop rounds (Which by the way, occur very often so it's NOT a once a week thing.

**Comment by EMT321** [comment]
I've explained how access to the PDA cartridge and door remote is useful.

If there's nothing of value in there, there's no reason to be worried of people going in. If there is something of value, then their is justification for low-pop rounds where a single miner is all of cargo to have access.

Frankly, you should just learn to share.

**Comment by AdamElTablawy** [comment]
# THERE ARE 8 PEOPLE

This is a LOWPOP shift with 8 people

chances are the shaft miner is the **ONLY**
person in cargo

and therefore running it

So it is NOT an issue and NOT a concern

simply because there are too few people to actually MATTER

**Comment by Time-Green** [comment]
Noooo
Merge this anyway, you don't need their judgement

**Comment by Cruix** [comment]
I could not merge this even if I wanted to.

**Comment by Time-Green** [comment]
Shit, I thought this was the PR

**Comment by Dzlan** [comment]
This was already fixed by Super a long time ago.
