### ISSUE TITLE
Fake walls act transparent if you close them while standing on their tile

### ISSUE THREAD

**Issue by Partheo** [yogstation13/Yogstation#9114]
Possibly related: #7969

![image](https://user-images.githubusercontent.com/10659549/86492849-50888380-bd3d-11ea-87b4-dd3942b55fda.png)

![jBduOR22uZ](https://user-images.githubusercontent.com/10659549/86492878-6c8c2500-bd3d-11ea-9589-d5a2e54985f8.gif)

## Reproduction:

Create a fake wall. Open it. Stand on the tile, then close the fake wall. The wall will then remain transparent and fully passable, until it is clicked on again- it will then fix itself. Nothing happens if you click on the bugged fake wall if you are on its tile.

**Comment by jcatjmeow** [comment]
Whats prolly happening:

When you stand on the tile and click it, it plays the animation. Then it checks if it can close. It can't. So it stays as an open false wall. But the animation already played. So now you have an open false wall on the last frame of the closing animation.

This should be an easy fix, just change the order
