### ISSUE TITLE
Inhands layering issues

### ISSUE THREAD

**Issue by Partheo** [yogstation13/Yogstation#9119]
Issue 1:

When facing left, the right hand inhand sprite displays over everything else, despite it being in the back. It also displays over the left hand inhand, which should be in front.
![image](https://user-images.githubusercontent.com/10659549/86500991-1cc05480-bd63-11ea-94ce-c87f782ee5e1.png)

The reverse is not true- when facing right, the right hand inhand displays on top normally.
![image](https://user-images.githubusercontent.com/10659549/86500995-221d9f00-bd63-11ea-9d2c-c01d68eb3bdd.png)

Issue 2:

When facing either left or right, the inhand that is further back displays above the suit layer.
![image](https://user-images.githubusercontent.com/10659549/86501023-5d1fd280-bd63-11ea-9d05-febba7250512.png) ![image](https://user-images.githubusercontent.com/10659549/86501028-63ae4a00-bd63-11ea-93a4-4c0a1883a128.png)

**Comment by adamsong** [comment]
This is no longer an issue
