### ISSUE TITLE
exterior airlocks in monstermos airlocks won't block atmosphere if a shuttle has left from them

### ISSUE THREAD

**Issue by SomeguyManperson** [yogstation13/Yogstation#9137]
## Reproduction:
1: ensure the mining shuttle is not present
2: cycle the airlock to exterior
3: cycle the airlock to interior
4: notice how the airlock will refuse to fill up
5: manually skip the airlock cycling, notice how the entire mining prep room is depressurized when the interior airlock opens even though the exterior airlock is bolted shut

**Comment by ReddicusDragon** [comment]
workaround: deconstruct and rebuild airlock, update airlock controller
alternative workaround: holofan

**Comment by monster860** [comment]
fixed #10398
