### ISSUE TITLE
Busted tanks

### ISSUE THREAD

**Issue by Drakkon** [yogstation13/yogstation#916]
Large canisters can already be busted. What about the ability to slash/shoot water/fuel tanks and tiny chance to bust containers (via ranged or slashing weapon) on someone such as jet packs, oxy tanks, and extinguishers, adding a sprite for slash or bullet hole, instantly emptying the chemical/liquid from the container, and hilariously launching the holder in a random direction (in space) if it was compressed or releasing a 3x3 extinguish. Metal containers could be welded to repair.

**Comment by Zostroll** [comment]
Welding tanks explode if shot.

**Comment by Drakkon** [comment]
Isn't that only lasers? Calling BS if regular bullets do that. But yeah that's fine and I don't think the features would conflict.

**Comment by Zostroll** [comment]
I know the detectives gun does it. I am not sure about other guns.

**Comment by Drakkon** [comment]
@Zostroll Huh. Well I'm mostly just interested in the hold-able tank effect (R.I.P. plasmamen and their life support. Maybe their tanks should just be written off as stronger metal and immune to it)

**Comment by Zostroll** [comment]
Maybe have the plasma man tanks be self sealing like the suit is self extinguishing.
