### ISSUE TITLE
Medbay door's any-access indicator isn't transparent anymore

### ISSUE THREAD

**Issue by Partheo** [yogstation13/Yogstation#9168]
## Round ID: 30490

I'm pretty sure this is caused by #8901, but I can't be sure.

## Reproduction:

Look at medbay doors. The little shower spray next to them is opaque. 

![image](https://user-images.githubusercontent.com/10659549/87033491-51de0400-c1b4-11ea-9151-365829c8b543.png)

**Comment by maxion12345** [comment]
That's uh
Not a shower
That indicates what side of the door you can exit without needing access. Cloning has one as well to let cloned people out without cloning access.

**Comment by Partheo** [comment]
> 
> 
> That's uh
> Not a shower
> That indicates what side of the door you can exit without needing access. Cloning has one as well to let cloned people out without cloning access.

Lmao, you can see how out of touch I am then. I assumed it was a rinse spray thing that sanitized you as you entered/exited.

**Comment by redmoogle** [comment]
Issue was fixed at some point, reopen if you find it again
