### ISSUE TITLE
Rapid cable layer is still broke, the fix was a lie.

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#9174]
It's doing this now:

![image](https://user-images.githubusercontent.com/36208065/87092318-3a7d3600-c209-11ea-8fd5-0163f2a5b010.png)

Should be one line.

https://github.com/yogstation13/Yogstation/pull/7631 was supposed to fix it, it liesssss

**Comment by redmoogle** [comment]
Works fine for me, reopen if your cable layer dislikes you
