### ISSUE TITLE
Stray spacepod event can land in hallways and space hallways when landing on a window

### ISSUE THREAD

**Issue by Hopekz** [yogstation13/Yogstation#9175]
Thought this was only meant for maint so posting this but close if intended

![iRoV5YKiIr](https://user-images.githubusercontent.com/24533979/87109042-3eb94b80-c229-11ea-9310-653e2096554e.png)

**Comment by patpol4** [comment]
Pretty sure they can spawn in any area on the station.

**Comment by Hopekz** [comment]
> Pretty sure they can spawn in any area on the station.

I'd be fine with deeming this a feature.

Just reporting it so it can be written somewhere or maybe referenced years in the future when someone makes an argument on whether or not these pods are a good event.
