### ISSUE TITLE
Shuttle door sprite broken

### ISSUE THREAD

**Issue by Partheo** [yogstation13/Yogstation#9193]
![image](https://user-images.githubusercontent.com/10659549/87212710-ea2bd400-c2ed-11ea-969a-ca9a35094ff4.png)

**Comment by 00aquir** [comment]
Yes, if you use the airlock painter, it cannot load sprites for some of the available door types. (Also you cannot check all possible door paints if you're painting just one type of door.)

**Comment by Partheo** [comment]
@00aquir That would be good to write in its own issue, as this one will be fixed by #9194 but the airlock painting issue will still exist.

**Comment by 00aquir** [comment]
okay
