### ISSUE TITLE
Artificer cult wall construction deletes floor

### ISSUE THREAD

**Issue by Mqiib** [yogstation13/Yogstation#9235]
Issue reported from  Round ID: 30615 (Yogstation 13)

Reporting client version: 513.1527

When an artificer from a blood cult builds a cult wall with their ability, the floor underneath seems to get deleted as, if that wall is destroyed in some way, it doesn't leave a hull tile under it. This ends up spacing just about every cult base that happens to use said walls
![image](https://user-images.githubusercontent.com/43766432/87742831-928ddc80-c7b5-11ea-951a-073f4ef2c51e.png)

**Comment by adamsong** [comment]
Still an issue
