### ISSUE TITLE
No way to interact with budgets now

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#9240]
No way for officers to deposit manually paid fines. 

No way to increase service budget save for the few using mood.

**Comment by Bibby0110** [comment]
tough luck, deal with it

**Comment by MegaEmpirical** [comment]
This is me dealing with it.

**Comment by jcatjmeow** [comment]
This isn't a bug or oversight, as confirmed by gamer.

Tbh we just need to remove the entire economy system but that's neither here nor there

**Comment by MegaEmpirical** [comment]
Mother fucker, you can intentionally remove the gravity generator and not give any kind of replacement whilst changes are made but you'll be fucking with the station until then, which means the best way forward is to leave it in until a replacement is made.

Now if you wanted to close it because there is a PR in the works that'll resolve it fine, though you should wait until it's merged. 

Until then this is still an issue even if intentional.

**Comment by jcatjmeow** [comment]
@MegaEmpirical 
The **Entire** point of removing budget cards was so that you can't access the budgets.

This is literally the feature of the pr.
