### ISSUE TITLE
Lifting "ameridiner" floor tiles with a crowbar then replacing them causes their icon to break

### ISSUE THREAD

**Issue by Partheo** [yogstation13/Yogstation#9269]
## Round ID: 30678
A floor tile in the kitchen had a broken icon due to being lifted off and placed back.

![image](https://user-images.githubusercontent.com/10659549/88012440-e5360400-cae7-11ea-888a-97abdad05cbf.png)

Note the different icon file.

![image](https://user-images.githubusercontent.com/10659549/88012489-072f8680-cae8-11ea-8974-b39170742fbf.png)

## Reproduction:

![LmeQmopnC4](https://user-images.githubusercontent.com/10659549/88012631-67262d00-cae8-11ea-8518-573d855056f3.gif)

**Comment by patpol4** [comment]
Same happens for bronze tiles but it's black
