### ISSUE TITLE
Port : Telescience Rework

### ISSUE THREAD

**Issue by X-TheDark** [yogstation13/yogstation#93]
I'll port this over soon.

**Comment by X-TheDark** [comment]
Actually, I changed my mind, I think I'll port over the Telescience being required to be built first, because I legitimately want to see if that would be a good solution.

**Comment by X-TheDark** [comment]
Yup, still doing it.

**Comment by X-TheDark** [comment]
Done. Also buffs telescience to not have the ridiculous cooldowns it had:
* Old Cooldowns : 120/53/30/19 (Basic/Advanced/Super/Quadratic Capacitors)
* New Cooldowns: 30/13/8/5

**Comment by oisin100** [comment]
Much better cooldowns, God, They were a nightmare, I dont really think there should be cooldowns at all.

**Comment by killerx09** [comment]
You broke it somehow, computer frames don't accept Telescience Console circuit boards in it's construction now.

**Comment by X-TheDark** [comment]
I most certainly did...will fix as soon as I can.
