### ISSUE TITLE
Make chemical implants trigger on crit

### ISSUE THREAD

**Issue by puremanbird** [yogstation13/yogstation#930]
An implant that triggers on death is fairly stupid. Make it trigger on crit so its slightly more useful.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
try deathgasping, it releases them even in crit

**Comment by puremanbird** [comment]
Doesnt work from crit.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
@puremanbird 
![Discrepancy Detected](http://i.imgur.com/tf9Bwb9.png)

**Comment by McDonald072** [comment]
Don't add a feature request tag if the feature already exists, doofus

**Comment by Super3222** [comment]
Wasn't looking.
