### ISSUE TITLE
Vendors not giving shit that is labeled as free

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#9317]
Gonna stab a bitch, I suspect the item isn't actually free for me but it fucking says it is.

Example: Doctor using NanoMed Plus vendor trying to buy bottle of psicodine pills. I have seen this elsewhere too.

**Comment by jcatjmeow** [comment]
Was unable to reproduce but I will keep you posted

**Comment by MegaEmpirical** [comment]
I'll try again later.

**Comment by Georgeur** [comment]
pretty sure even the advanced medkits are labelled as free, which they certainly are not

**Comment by redmoogle** [comment]
This was fixed _but not linked to the pr_
