### ISSUE TITLE
Prayer sounds don't work

### ISSUE THREAD

**Issue by matskuman5** [yogstation13/yogstation#932]
In the preference tab you have the prayer sounds button. If you have it on whenever someone sends a prayer you hear a HALLELUJAH sound effect. This no longer works, the sound effect never plays.

To reproduce: get yourself into a body, turn prayer sounds on in the preferences tab, and PRAY to the holy gods, commit sudoku as you never hear the glorious hymn of the heavenly choir grace your mortal ears.

**Comment by utahclock** [comment]
it works if chapplain prays just not normal players

**Comment by EMT321** [comment]
Only the chaplain gets the divine intervention. Can this issue be closed?

**Comment by matskuman5** [comment]
Sure didnt know that

4.10.2016 14.49 "EMT321" <notifications@github.com> kirjoitti:
