### ISSUE TITLE
Bounty console broke

### ISSUE THREAD

**Issue by redmoogle** [yogstation13/Yogstation#9324]
Issue reported from  Round ID: 30791 (Yogstation 13)

Reporting client version: 513.1528

Reproduction:
Open the console

![image](https://user-images.githubusercontent.com/20369082/88567403-6ec46500-d005-11ea-9ddb-d8da7507795e.png)

Forbidden BIOS

**Comment by jcatjmeow** [comment]
@TheGamerdk

**Comment by redmoogle** [comment]
Was fixed at somepoint
