### ISSUE TITLE
Cancer

### ISSUE THREAD

**Issue by Rocks4Free** [yogstation13/yogstation#933]
Players would get cancer by extended exposure to radiation, or excessive honking. 

Cancer tumors in chest would cause respiratory + toxin damage
Brain tumors would cause brain + toxin damage
Tumors in crotch area would cause malnourishment + toxin damage
Tumors in limbs would cause brute + toxin damage to the limb

Tumors would keep dealing damage until removed via surgery or possibly an advanced chemical. They would also be about as rare as appendicitis, if that's still a thing.

Bonus: Removed tumors would be a usable substitute for meatballs in recipies

H0nk.

**Comment by Super3222** [comment]
the meme returns

**Comment by Time-Green** [comment]
I thought about that aswell.
Different kinds, your arm could come to life and beat you to death etc

**Comment by Rocks4Free** [comment]
Also remove all rad suits from the engine room so anybody who uses singulo gets dick cancer

**Comment by X-TheDark** [comment]
All we need is "ass cancer", really.

**Comment by puremanbird** [comment]
Give tumors a medical research level, and make them grind able to be used in some kind of medicine.

**Comment by AdamElTablawy** [comment]
it's fitting that time-green comments in an idea about cancer

**Comment by ShadowDeath6** [comment]
players get cancer by reading this meme PR >:^(

anyway this is going to make genetics suffer because they're going to be shoving infinity radiation syringes up their dick and nobody is competent enough to rely on consistent removal of meatballs from various areas
