### ISSUE TITLE
Nuclear operatives cannot buy more then 1 extra arm. Hovewer, your friend, also nuclear operative, can buy an extra arm for you.

### ISSUE THREAD

**Issue by Ratvar** [yogstation13/Yogstation#9333]
![image](https://user-images.githubusercontent.com/22855970/88743244-d3d6a280-d14c-11ea-9691-46533d4d69e6.png)

**Comment by ynot01** [comment]
I assume you mean he can give you his uplink, which I don't believe can be easily fixed

**Comment by jcatjmeow** [comment]
Not a bug.

Kind of an oversight tho. Not super fixable? I dunoo.

**Comment by Ratvar** [comment]
Remove arms as standalone items from nuclear operatives, let whole team buy one nuclear arm dispenser that gives each nukeop an arm?

**Comment by ToGWtF** [comment]
nevermind i take it back I think you still can buy more than one, it just costs 15tc for nuke ops compared to 5tc a normal traitor has to spend

**Comment by adamsong** [comment]
Its now just possible to buy as many arms as you can afford
