### ISSUE TITLE
Security cameras don't show whom you see

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#9347]
- when the person is unmasked
- or is that intentional?

**Comment by jcatjmeow** [comment]
No clue if intentional. @TheGamerdk

**Comment by Bibby0110** [comment]
If we're talking about the security camera console you can examine things through it, but there's no way to show it in the bottom left like when you're seeing it live

**Comment by 00aquir** [comment]
yeah it's alright
