### ISSUE TITLE
Omega Engineers lack tcomm and gravity accesses

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#9355]
As title.

**Comment by MegaEmpirical** [comment]
nor gravity

**Comment by jcatjmeow** [comment]
Not a bug.

Is an oversight

**Comment by MegaEmpirical** [comment]
No fucking shit.

**Comment by athena413** [comment]
this can be fixed by going into the file for the station engineer, each job has special accesses in their own file specifically for omegastation

it's like a 1-5 minute fix but i wont be at my computer for another 3 hours

**Comment by patpol4** [comment]
Gravity access fixed in https://github.com/yogstation13/Yogstation/pull/11328
the tcomms access is a code issue
