### ISSUE TITLE
Temperature remains even when air is gone

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#9356]
What is this shit.

**Comment by ToGWtF** [comment]
"intended"

"its not atmos code thats wrong its mob code"

**Comment by ynot01** [comment]
shouldn't affect new introduced atmos since its so small it wont make a difference

you're likely experiencing an incredibly small but not gone amount of gas in the room that still retains its temperature, just being small amount

**Comment by jcatjmeow** [comment]
Can you reproduce the issue?

**Comment by MegaEmpirical** [comment]
I'll take a stab when I have some time. I know I've heard others talk about it before too.

**Comment by adamsong** [comment]
Reading the gasses of a spaced room will still show the temp has what it was, but any new gas will reset the temp. Is this still an issue?
