### ISSUE TITLE
photo album/secret sauce recipe persistence doesn't work as intended

### ISSUE THREAD

**Issue by SomeguyManperson** [yogstation13/Yogstation#9375]
photo albums should (I think) retain pictures between rounds, and the secret sauce recipe should only re-generate every 7 days or something but neither retain information past the current round

**Comment by Bibby0110** [comment]
Secret sauce thing fixed in 
https://github.com/yogstation13/Yogstation/pull/10921
I'd wager the photoalbums were fixed when we went over that
