### ISSUE TITLE
Visible ghosts kill Shadowlings. 

### ISSUE THREAD

**Issue by johnnyboyz25** [yogstation13/Yogstation#9378]
## Reproduction:

As a sling, you are allergic to light.
As a wizard, you have the opportunity to make ghosts visible to living players.
Ghosts produce a small amount of light.
On a sling-wizard round, this creates a conflict. Ghosts, who are spectating an active sling, should not passively kill it by being there. It simply ruins a sling.

Please make slings immune to ghost luminescence.

**Comment by ynot01** [comment]
not a bug imo

**Comment by johnnyboyz25** [comment]
If it's not a bug, what is it? Is there anything that you think should be fixed, or do you think slings should just perish because wizard enabled ghosts?

**Comment by jcatjmeow** [comment]
This might an oversight, maaaybe.
I personally think it doesn't need "fixing" and works as intended. But I will leave this open

**Comment by adamsong** [comment]
Is this a bug and needs fixed, or is it working as intended and needs closed?

**Comment by SomeguyManperson** [comment]
With dynamic being a big thing this is actually something that should be addressed

**Comment by VaelophisNyx** [comment]
just make ghosts not emit light

**Comment by Oblisk234** [comment]
Shadowlings no longer exist, see #20581
