### ISSUE TITLE
Items blocking the floor!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#938]
Floor was unaccessible and thus unrepairable for at least two players because many items completely block the sprite of lattice/space now, **no matter where you click**. You have to remove items constantly sucked onto the space tile before you can reach it.
When opening a locker, many different items (e.g. analyzer) won't let you close the locker with just one click, because they occupy the whole tile.

The floor tiles cannot be placed here, and alt+clicking on space only interacts with the metal on it.

![ss13-cantplacefloorsonitems](https://user-images.githubusercontent.com/16806055/40336660-41dac16a-5d6b-11e8-8ee6-5adbca4d089a.png)

**Comment by ThatLing** [comment]
Round ID?

**Comment by 00aquir** [comment]
All I know that it happens to this hour, after the client downloaded the game again around yesterday. Round was ongoing at the time of posting the issue.

**Comment by makkenhoff** [comment]
Happens quite a bit - being hard to target the floor and a lot of items get displaced, anytime when bombs are involved; but I also notice that you've got a partially intact grille in your square, which is odd.

**Comment by 00aquir** [comment]
I haven't seen this problem for months now.
