### ISSUE TITLE
Blood cult tiles dont resist atmos changes

### ISSUE THREAD

**Issue by Jarod1200** [yogstation13/Yogstation#9384]
Blood cult tiles produced by artificers, pylons, etc. are supposed to resist atmospheric changes but haven't done so since I think monstermos was added. this makes it so a single miner or engineer can RCD 1 wall or window, space a cult base and essentially kill half or more of said cult.

There is basically evidence of this on 90% of cult rounds.

**Comment by MegaEmpirical** [comment]
They're supposed to resist atmos changes?

**Comment by adamsong** [comment]
Are they supposed to resist atmos changes?

**Comment by Jarod1200** [comment]
The wiki says they are. And I believe they did before monstermos

**Comment by Jarod1200** [comment]
Cant seem to find it on the wiki. Presumably it was removed during the 11 months this issue was opened

**Comment by adamsong** [comment]
Seems this is now intentional, closing
