### ISSUE TITLE
TK Glitch

### ISSUE THREAD

**Issue by woahmanchillout** [yogstation13/yogstation#939]
So far this is all I have found it works on. If you have TK you can grab a evidence bag and any thing in it get a summond to your hand. I do not know if this can be used with any thing else. I will do more tests in future.

**Comment by X-TheDark** [comment]
Anything that has a reaction to being clicked in their hand will do this, since the TK click calls attack_hand on the item, meaning it would do exactly the same thing it would do if you clicked it in your hand.

**Comment by woahmanchillout** [comment]
It takes the item out of the bag and puts it in your hand like it teleport it through walls and doors

**Comment by Time-Green** [comment]
Also works with items such as cardboard wrapped stuff, not really much we can do about it

**Comment by 00aquir** [comment]
Is it not possible to make an exception in this action for people who have TK to define how far the object is from the player?

**Comment by Cruix** [comment]
It is absolutely possible and important to fix. I'll mess with TK sometime soon, it has a lot of very old and buggy code that has not been looked at in a while.

**Comment by woahmanchillout** [comment]
Thanks Cruix that's all I wanted to hear. Personally it gives people an upper hand.
