### ISSUE TITLE
Mhelps sent from discord are unreadable

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#9413]
Fucking contrast, this is like the third issue I've made for this exact shit.

![image](https://user-images.githubusercontent.com/36208065/89706212-84089000-d931-11ea-91d0-4b5eb1751a8b.png)

**Comment by jcatjmeow** [comment]
"I meant when the bat"

It's readable, wdym. Plus its fine on light theme.

**Comment by MegaEmpirical** [comment]
1) This is not light theme.

2) The contrast makes it very hard on the eyes and difficult to read and notice.

**Comment by adamsong** [comment]
This is still an issue
