### ISSUE TITLE
Revenant thought messages are unreadable

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#9414]
God damn savages:

![image](https://user-images.githubusercontent.com/36208065/89706238-c29e4a80-d931-11ea-94b9-a22b259717f7.png)

**Comment by jcatjmeow** [comment]
That's readable wdym

**Comment by MegaEmpirical** [comment]
It is not literally unreadable but the contrast is so bad that it is very hard to read, and very easy to miss.

**Comment by jcatjmeow** [comment]
For this one i agree

**Comment by redmoogle** [comment]
![image](https://user-images.githubusercontent.com/20369082/100555671-16c79480-326b-11eb-9759-44492d8cdf34.png)
