### ISSUE TITLE
quiet round prefs don't save

### ISSUE THREAD

**Issue by GenericDM** [yogstation13/Yogstation#9416]
## Round ID: 
N/A

## Reproduction:
 try to save quiet round pref, wait for server to restart, find that it has not saved

**Comment by MegaEmpirical** [comment]
Likely a failsafe for when donor expires.

**Comment by adamsong** [comment]
I've seen people express that this is intentional, is it?

**Comment by MegaEmpirical** [comment]
I actually have no idea but I can understand why it would be so I'll close this
