### ISSUE TITLE
Dynamic Clock Cult spawned two City of Cogs

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/Yogstation#9417]
## Reproduction:

>Force Dynamic
>Pray it rolls Clock Cult

No but seriously. Somehow two city of cogs were spawned. 

One with cultists, the other had no cultists and the placeholder Ark that spawns with map. Seemed like an equal amount of crew who took portals got sent to the fake one as crew that got sent to the correct one.

My bet is it had something to do with Dynamic, rather than just

**Comment by ToGWtF** [comment]
Round 31075 as well. We forced dynamic, it RNG'd clock cult, happened again.

**Comment by MegaEmpirical** [comment]
Clock vs clock.

**Comment by Xoxeyos** [comment]
Just assign this to me, I'll try and come up with a fix.

**Comment by MegaEmpirical** [comment]
Solution should just be that you can't roll the same conversation antag more than once. Should be true for all conversion antags.

**Comment by Xoxeyos** [comment]
Should be fixed.
