### ISSUE TITLE
Clicking on a machine doesnt bring the window to the front

### ISSUE THREAD

**Issue by puremanbird** [yogstation13/yogstation#944]
If you have multiple machine tabs opened, like the chem master and the chem dispenser, clicking on the chem dispenser wont bring the chem dispenser window to the front. This can be particularly annoying when you are working in virology, or you are trying to get at the chemical heater's tiny window. Its a minor thing, but if it could be fixed it should be.

**Comment by Dagdammit** [comment]
This would make life alot easier for chem and botany too.
