### ISSUE TITLE
make lavaland have unsimulated atmos tiles

### ISSUE THREAD

**Issue by AdamElTablawy** [yogstation13/yogstation#950]
who the fuck thought space wind on a map where moving on the wrong tile will bake you harder than a goddamn hippie in the 80's in the middle of california was a good idea

**Comment by Time-Green** [comment]
/tg/ did

**Comment by AdamElTablawy** [comment]
do you know what rhymes with 'eat dicks and go away time-green'

nothing

nothing but exactly that

**Comment by darkwahn** [comment]
I'd be pretty up for this, would make the skeleton ruin with the honk render "easier" but that's pretty much a non-issue.

**Comment by Super3222** [comment]
The obstacle in the skeleton ruin is the pressure, which I imagine is why there is so much lava inside. You have to close the doors, and get trapped with a bunch of skeletons or risk plunging into the lava.

**Comment by darkwahn** [comment]
I thought the pressure was "tied" with that, but wasn't really sure.

**Comment by AdamElTablawy** [comment]
the pressure also destroys the honk render and minerals because it pushes them into the lava so there's 0 reason to go in

**Comment by Super3222** [comment]
I've had almost no trouble with it in past, and you can always pick back up those items that have fallen into the lava.

**Comment by ClaudeWicked** [comment]
I support the fuck out of this-- there are a few doors that make you take random damage because atmos trolls, and bombs act weird as heck.

**Comment by ClearedObject** [comment]
I support this wholeheartedly. Finally, I won't be sucked into lava because of a door opening or window breaking.

**Comment by darkwahn** [comment]
@Super3222  Don't the items become unable to be picked up since they burn your hand?

**Comment by EMT321** [comment]
This is a much needed change. I've seen several people step off a lavaland boat and die from being sucked out.

**Comment by Dagdammit** [comment]
I support this change; if some lavaland ruins have it as a deliberate challenge element, I'm sure it can be replaced with some other factor.
