### ISSUE TITLE
Pasting github links in mhelps trips the bigot filter.

### ISSUE THREAD

**Issue by maxion12345** [yogstation13/Yogstation#9515]
Issue reported from  Round ID: 31324 (Yogstation 13 (Main))

Reporting client version: 513.1528

I just wanna link PR's goddammit.

**Comment by jcatjmeow** [comment]
I uh....I don't know how to reproduce this on a private server 😅 
I'll just take your word for it I guess? What part of it triggers the filter? Do you have an example?

**Comment by GenericDM** [comment]
Any link that is not to yogstation.net is filtered from anything that uses the pretty filter. Headcoder or council would have to fix this.
