### ISSUE TITLE
Player rolled antag (gang boss) in the lobby

### ISSUE THREAD

**Issue by JasioPL321** [yogstation13/Yogstation#9537]
## Reproduction:
A player rolled antag while in the lobby. Seems like he didn't get any role from his prefs and had "Return to lobby if preferences unavailable" set. He joined as warden and spawned with gang boss status, no implant and no gangtool etc.
Most likely same bug as #8370 
![1](https://user-images.githubusercontent.com/39873060/90952942-d1bfe500-e467-11ea-8006-57cd3568e22c.png)

**Comment by ToGWtF** [comment]
repeat of https://github.com/yogstation13/Yogstation/issues/5182

**Comment by boodaliboo** [comment]
known issue think tg patched it

**Comment by adamsong** [comment]
This issue is caused because they will roll antag, and then not have any valid jobs available with roll random job disabled. Similar things happen in other antags, but not all.

**Comment by Moltijoe** [comment]
pretty sure this was fixed
