### ISSUE TITLE
Mech Request Form has poor formatting.

### ISSUE THREAD

**Issue by MrHorizons** [yogstation13/Yogstation#9559]
They have "Write" on them instead of actual fields.

## Reproduction:
Use the Bluespace Paperwork Printer found on certain PDA cartridges or perhaps the RD's clipboard.

**Comment by MrHorizons** [comment]
And yes, I know I'm a dev, but I'm working on other projects.

**Comment by ReddicusDragon** [comment]
\>:L this was MY BABY
