### ISSUE TITLE
Yogsmeta has no camera for security in Upload

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#9583]
- security has no camera view in AI Upload
- is this a bug or intentional?

**Comment by boodaliboo** [comment]
but it does though

**Comment by 00aquir** [comment]
that's for AI, not sec

**Comment by boodaliboo** [comment]
> that's for AI, not sec

but its named security camera????

**Comment by boodaliboo** [comment]
![image](https://user-images.githubusercontent.com/40642354/91905947-31827100-ec5c-11ea-833d-134e34912d00.png)

**Comment by 00aquir** [comment]
The Upload is not in the AI satellite in Yogsmeta. And there, none of them are sec cameras.

**Comment by patpol4** [comment]
Pretty sure that is intended 
![chrome_gKp0ned52n](https://user-images.githubusercontent.com/48154165/98534064-3844ea00-2284-11eb-8359-45e56bfff64b.png)
