### ISSUE TITLE
On the latest byond update (513.1529) the game randomly crashes

### ISSUE THREAD

**Issue by GenericDM** [yogstation13/Yogstation#9585]
## Round ID:
N/A
## Reproduction:
exist, crash
there is a consistent crash at round end once the shuttle docks, that initially freezes the screen with the chatbox still moving, then eventually crashes the game as a whole.
aside from that, opening certain admin panels will cause the game to crash (without any consistency, they just randomly crash sometimes and not others)
interacting with objects can cause the game to crash, again inconsistently.
this has all started after updating to the latest byond version

**Comment by CrazyDrakkon** [comment]
Same problem, except as an observer, got sent back to lobby as if I never joined, with the option to join or observe again (Round ID: 31470).

**Comment by jcatjmeow** [comment]
![Capture](https://user-images.githubusercontent.com/40673387/91641854-0518eb80-e9f5-11ea-8d8a-a1580ca57b92.PNG)
Please update to 513.1530
