### ISSUE TITLE
Mutation toxins not mixing.

### ISSUE THREAD

**Issue by joejoe3421** [yogstation13/yogstation#961]
[Note]: # Well I was reading on the Wiki about the different combinations of mutation toxin like skeleton etc yet only like two of them work, Mutation toxin and unstable mutation toxin are able to be made. the other don't seem to be.

https://tgstation13.org/wiki/Guide_to_chemistry#Mutation_Toxins

[Admins]: # It occurs every time I try to mix them.

**Comment by X-TheDark** [comment]
We do not currently have the "Stabilized" mutation toxin version in our code,

**Comment by joejoe3421** [comment]
oh, any idea when we might?
