### ISSUE TITLE
Suggestion: Allow pens to act as dyes.

### ISSUE THREAD

**Issue by ClaudeWicked** [yogstation13/yogstation#963]
Simply put, in this station, I feel like we should have more options to bleed colors. I think that pens should be able to dye bedsheets, gloves, and jumpsuits their respective ink colors. Notably, regular pens should dye black, while blue pens and red pens should dye things dark blue or dark red. They're nice colors, and I dont see how this would present any coding issues.

**Comment by Kmc2000** [comment]
Seems neat
