### ISSUE TITLE
You can survive shuttle gib while hiding in a transit tube.

### ISSUE THREAD

**Issue by GenericDM** [yogstation13/Yogstation#9638]
## Reproduction:
Place down a looping transit tube on a shuttle dock. Sit yourself down in the tube and wait for the shuttle to arrive. Pop up instantly inside the shuttle completely unharmed.

**Comment by MegaEmpirical** [comment]
This is obviously an oversight and is working as intended so it's a feature request.

Right Jcat?!

**Comment by redmoogle** [comment]
Fixed by Jamie
