### ISSUE TITLE
Fireman Carrying Does Not Work Through Teleporter

### ISSUE THREAD

**Issue by UselessTheremin** [yogstation13/Yogstation#9648]
Title. Whenever you are fireman carrying someone and walk through the portal, they are left behind and you still have the offhand from carrying them. Someone died because of this lol

**Comment by redmoogle** [comment]
it's due to the fact they are buckled, you have to drop em and throw em/push them in

**Comment by jcatjmeow** [comment]
it is buggy tho, that uh, you still have the offhand cause the game thinks ur still carrying it

**Comment by redmoogle** [comment]
Yeah I didnt notice the last part. https://github.com/yogstation13/Yogstation/pull/9649 partially fixes this. To fix the whole buckle thing I will probably need to make the teleporter have something like a 0.5-0.1 second delay and then teleport everything on that tile.
