### ISSUE TITLE
Runtime in bodycamera.dm, line 115

### ISSUE THREAD

**Issue by GenericDM** [yogstation13/Yogstation#9662]
## Round ID:
31685

## Testmerges:
#9582 
#9659 
#9285 

`[17:58:46] Runtime in bodycamera.dm, line 115: Cannot read null.status
proc name: dropped (/obj/item/clothing/neck/bodycam/dropped)
usr: LynxJynx/(LynxJynx)
usr.loc: (start area (8, 174, 1))
src: the miner body camera (/obj/item/clothing/neck/bodycam/miner)
src.loc: James Jameson (/mob/living/carbon/human/dummy)
call stack:
the miner body camera (/obj/item/clothing/neck/bodycam/miner): dropped(James Jameson (/mob/living/carbon/human/dummy))
James Jameson (/mob/living/carbon/human/dummy): doUnEquip(the miner body camera (/obj/item/clothing/neck/bodycam/miner), 1, null, 1, 1)
James Jameson (/mob/living/carbon/human/dummy): doUnEquip(the miner body camera (/obj/item/clothing/neck/bodycam/miner), 1, null, 1, 1)
James Jameson (/mob/living/carbon/human/dummy): doUnEquip(the miner body camera (/obj/item/clothing/neck/bodycam/miner), 1, null, 1, 1)
James Jameson (/mob/living/carbon/human/dummy): temporarilyRemoveItemFromInventory(the miner body camera (/obj/item/clothing/neck/bodycam/miner), 1, 1)
the miner body camera (/obj/item/clothing/neck/bodycam/miner): Destroy(0)
the miner body camera (/obj/item/clothing/neck/bodycam/miner): Destroy(0)
the miner body camera (/obj/item/clothing/neck/bodycam/miner): Destroy(0)
qdel(the miner body camera (/obj/item/clothing/neck/bodycam/miner), 0)
James Jameson (/mob/living/carbon/human/dummy): delete equipment()
James Jameson (/mob/living/carbon/human/dummy): wipe state()
unset busy human dummy("dummy_preference_preview")
/datum/preferences (/datum/preferences): update preview icon()
/datum/preferences (/datum/preferences): ShowChoices(LynxJynx (/mob/dead/new_player))
/datum/preferences (/datum/preferences): process link(LynxJynx (/mob/dead/new_player), /list (/list))
LynxJynx (/client): Topic("_src_=prefs;preference=changes...", /list (/list), null)
LynxJynx (/client): Topic("_src_=prefs;preference=changes...", /list (/list), null)
`

**Comment by redmoogle** [comment]
Fixed by #10349
