### ISSUE TITLE
Runtime in unsorted.dm, line 1162

### ISSUE THREAD

**Issue by GenericDM** [yogstation13/Yogstation#9663]
## Round ID:
31685

## Testmerges:
#9582 
#9659 
#9285 
`[17:58:51] Runtime in unsorted.dm, line 1162: Bad areastring path for Port Bow Solar APC, /area/solar/aux/port
proc name: stack trace (/datum/proc/stack_trace)
src: Port Bow Solar APC (/obj/machinery/power/apc)
src.loc: the plating (208,197,2) (/turf/open/floor/plating)
call stack:
Port Bow Solar APC (/obj/machinery/power/apc): stack trace("Bad areastring path for Port B...")
Port Bow Solar APC (/obj/machinery/power/apc): Initialize(1)
Atoms (/datum/controller/subsystem/atoms): InitAtom(Port Bow Solar APC (/obj/machinery/power/apc), /list (/list))
Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
Atoms (/datum/controller/subsystem/atoms): Initialize(647156)
Master (/datum/controller/master): Initialize(10, 0, 1)
`

**Comment by redmoogle** [comment]
Some point this disappeared. havent seen it replicated, gone from code too
