### ISSUE TITLE
Unexplained Gibbing

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#967]
I was a miner given escape alone by the wishgranter and I was just about to release the singloo and tesla at the same time. On my body I had a engineering hardsuit, insulated gloves, magboots(on), toolbelt(full), sec flashlight(pocket), brute patch(pocket), and in my bag I had a russian .375 gun. lots of .375 ammo In my box i had all the starting minner stuff plus a automatic minning scanner and a telescience beacon.

I was in space removing a window to get the singloo beacon closer to the the tesla containment field. I then collapsed due to radiation and realised that I was dumb for doing this and ran to the west holding my a key I was then gibbed unsuspectingly. I never hit the field containment. I also had a legion implant and all the genetic powers other than hulk. EMT was the admin online and informed me there were no logs of anything happening.

**Comment by killerx09** [comment]
Implants used to be able to blow up around the singularity. The syndicate ones, anyway.

Source: Learnt this the hard way.

**Comment by Zostroll** [comment]
The only implant I had was a legion soul and the singloo hadn't started up yet.

**Comment by Time-Green** [comment]
Alright, can you explain the time just before you gibbed more precise?
Also how you gibbed, as in all gibs fly around, or some other gibbing.
Please describe the environment you were in.

**Comment by EMT321** [comment]
I watched this occur, they were wearing a CE hardsuit and standing in the path of the firing PA, next to an emitter-powered energy field. Nothing in admin or attack logs indicates why they were gibbed.

**Comment by Time-Green** [comment]
Could it be the singulo generated at your location?
Or were you hit by the electric field and then knocked back and sent to the field again a few hundred times? 
Was he gibbed or turned to ash

**Comment by EMT321** [comment]
Gibbed, and the singulo had not generate.

**Comment by Zostroll** [comment]
I was gibbed not ashed. I was wearing a normal hardsuit not the CE's one. The singloo had not manifested as didn't wrench it down. The singloo never manifested. Just before the gibbing I was being hit by the the radiation beams from the tesla/singloo starter I then ran to the west and I was gibbed about three tiles away from the centre ling of the singloo/tesla area in-front of the windows. The gibbing felt instant. No hitting the field over and over just running then I was a brain.

**Comment by Time-Green** [comment]
I checked all code including gibbing, and the only possibilities I see are:

1. You got hit by a meteor
2. You were infected by an alien larva
3. You died and got infected by a changeling egg
4. EMT went rogue (I trust you EMT, but I am listing all thing possible)
5. The game derped and treated the radiation as an explosion.
6. Uhm, this is kinda likely, the PA may have a special beam that rarely fires and instakills (I found a beam that does that, however I can't find it being used)
7. You both dreamed it.

**Comment by Zostroll** [comment]
1. There was no meteor. All the walls were intact.
2. Nothing poped out of me and I has no contact with any face huggers.
3. I have no idea what this is.
4. I really really doubt it.
5. I was out of the radiation beams when I was gibbed.
6. I was out of the PAs stream when I exploded.
7. Last time me and EMT tripped out together was at least two weeks ago.

**Comment by EMT321** [comment]
Can the wishgranter powers gib you after a time?

**Comment by Time-Green** [comment]
I checked and they shoudln't

**Comment by killerx09** [comment]
Space dust?

**Comment by utahclock** [comment]
nothing in wishgranter code suggest a thing... only thing I can think of is
Chemical/explosive implant. of face hugger. or radiation mutation.

**Comment by Super3222** [comment]
@EMT321 @Zostroll Can you help me get the exact time and date of the incident? Hopefully this mystery doesn't go unsolved
