### ISSUE TITLE
Cannot damage monsters with thrown items

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#9699]
- Many xeno or lavaland monsters brought to station are impervious to lasers/fire, much stronger in melee fights, and yet it's impossible to damage them with any thrown object.

**Comment by UselessTheremin** [comment]
Bruh that's a feature it's intentional

**Comment by 00aquir** [comment]
Even then, it doesn't make sense to negate this effect entirely.

**Comment by UselessTheremin** [comment]
But it aint a bug, if you want it gone request it on forums / code it
