### ISSUE TITLE
Give animals health factors!

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#971]
I was a bit disappointed that you can't even take blood from certain pets while other animals like monkeys have it (you can only hug/whack them), and I haven't seen any food made from other pets than Ian that can send a "sign" to a certain head. It would also add to the gameplay if someone "borrowed" a head's pet because he wanted blood for a recipe or just a dramatic display of hatred by mopping the floor red with Ian because the HoP was incompetent :)

**Comment by Cruix** [comment]
Monkeys have blood because they are carbon mobs. Most pets are simple_animal mobs, which do not have blood or DNA, have simpler breathing, and are immune to most diseases.
