### ISSUE TITLE
Wizards get an internals box when they spawn but it has no mask or oxygen tank

### ISSUE THREAD

**Issue by Jarod1200** [yogstation13/Yogstation#9729]
Wizards spawn with an internals box but no internals mask or oxygen tank. Seems like an oversight but should probably be fixed considering many of their spells cause hull breaches and they can even buy a magic hardsuit which is kinda useless without internals. 

Reproduction: spawn as a wizard

**Comment by JamieD1** [comment]
Fixed apparently
