### ISSUE TITLE
AI upload is rad proof

### ISSUE THREAD

**Issue by Moja10** [yogstation13/Yogstation#9731]
AI upload is not a maintenance room so it should not be rad proof. 

![image](https://user-images.githubusercontent.com/17183762/93382222-72b37d00-f827-11ea-96fd-0419ba6f03e0.png)

**Comment by MegaEmpirical** [comment]
Can't recall if that's normal or if the core being rad proof is normal. I've always humored the idea of taking people into it to keep them safe but never had to.

**Comment by patpol4** [comment]
The radproofness is area based, it's a simple one line code fix if we really want to change this

**Comment by Bibby0110** [comment]
Always been this way due to AI core being right next to it

**Comment by JamieD1** [comment]
Non issue, could be shielded to prevent bit flips
