### ISSUE TITLE
Healing holopara can heal windows etc.

### ISSUE THREAD

**Issue by TheLinuxOS** [yogstation13/Yogstation#9735]
## Round ID: 

N/A It can happen in any round and I have seen it happen in multiple

## Reproduction:

Simply hit destructible objects such as a window until it is badly damaged or something similar. Then swap to healing on a healing holopara and hit it, not only do you hit the window at mach 2 when doing so, but it also heals the window so the window is no longer damaged. I have also seen this work on the control console in an escape pod so I'm assuming it works on most things. An additional thing to note is the fact that if you do it to the window the sprite for it doesn't revert to the state it was in before it was damaged, so you can have a window that is covered in cracks that isn't actually damaged.

**Comment by boodaliboo** [comment]
the only problem from this is that the window shgould revert sprites

**Comment by SomeguyManperson** [comment]
objects being healed is intended the speed punch isn't
