### ISSUE TITLE
map loading fucks up with icebox

### ISSUE THREAD

**Issue by athena413** [yogstation13/Yogstation#9748]
## Round ID:31833

<!--- **INCLUDE THE ROUND ID**
If you discovered this issue from playing tgstation hosted servers:
[Round ID]: 31833

## Testmerges:

![image](https://user-images.githubusercontent.com/15719834/93619530-4a01c380-f99e-11ea-8a36-f00996ff9a7d.png)

## Reproduction:

I loaded icebox after a boxstation round. That's it.

![image](https://user-images.githubusercontent.com/15719834/93619609-69005580-f99e-11ea-97fa-a0e0bd7292cc.png)

**Comment by adamsong** [comment]
Can you provide any more details?
