### ISSUE TITLE
Mindslave 

### ISSUE THREAD

**Issue by Badspler** [yogstation13/yogstation#975]
A person who has been mind-slave implanted keeps their objectives after being cloned.

Given the implant is enslaving them, removing the implant should free the victim.
The cloning process removes all implants and thus should free the victim. 

Its unknown to me if surgery or other means of implant removal frees the slaved victim.

**Comment by Zostroll** [comment]
I would say lore wise the mindslave implant doesn't operate on the implant being present but on it changing you thoughts and memory's to aline with the person who implants you.

**Comment by Time-Green** [comment]
You can fix someone that's mindslaved with a mind-shield implant.

**Comment by puremanbird** [comment]
surgery completely removes the objective. Cloning doenst, which im not sure if i agree with or not. Really you should have to deconvert someone to get them back, like gangs or revs.

**Comment by Badspler** [comment]
I think the major inconsistency is that cloning removes loyalty implants. I thought this was the case with all other implants.

**Comment by Super3222** [comment]
Yes, this is definitely a consistency issue and should be fixed.

**Comment by AdamElTablawy** [comment]
this IS fixed
