### ISSUE TITLE
Cannot make Teslium?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation#976]
"1 Part Stable Plasma 1 Part Silver 1 Part Black Powder
Temperature 400K"

no matter how slowly I heat it (I have to heat it over 460K), it disappears at certain temperature and a small shock happens.. I can't really understand why.

**Comment by Cruix** [comment]
The sparks are because the black powder is igniting. Telsium requires regular plasma, not stable plasma.

**Comment by 00aquir** [comment]
dammn recipe
