### ISSUE TITLE
Unlinking a borg from a traitor AI. 

### ISSUE THREAD

**Issue by puremanbird** [yogstation13/yogstation#980]
Why is this a thing? You couldn't do this before on malf ai, why can you do it on traitor AI?

**Comment by Ephemeralis** [comment]
You've always been able to forcefully disable AI linkage by hand, I thought?

**Comment by puremanbird** [comment]
not on malf ai. it just resynced itself. otherwise one borg can just walk in and kill the ai.

**Comment by ShadowDeath6** [comment]
borgs could always be unbound from malf, but they kept the ion law so it didn't matter, so you actually had to make a new AI to bind them to

unsyncing a borg from a traitor AI is retarded though
