### ISSUE TITLE
Get Server Logs not displaying in order

### ISSUE THREAD

**Issue by Spl99** [yogstation13/Yogstation#9808]
Issue reported from  Round ID: 31976 (Yogstation 13 (Main))

Reporting client version: 513.1532

Basically, when you click the 'Get Server Logs' command, none of the dates are in order. 
![image](https://user-images.githubusercontent.com/6018842/94348001-deb89100-0030-11eb-9d77-0d969c5815e1.png)
![image](https://user-images.githubusercontent.com/6018842/94348003-e8da8f80-0030-11eb-9acb-8ec655874000.png)
![image](https://user-images.githubusercontent.com/6018842/94348006-f09a3400-0030-11eb-8abe-878e0187e90d.png)

I've only just noticed this happening but I'm not sure how long it has been an issue.

**Comment by JamieD1** [comment]
Resolved in #9833
