### ISSUE TITLE
crew manifest broke

### ISSUE THREAD

**Issue by TheBombMakerJL** [yogstation13/Yogstation#9852]
![Screenshot (32)](https://user-images.githubusercontent.com/39393885/94768055-49910180-037c-11eb-8c7c-124b4db2a646.png)

Crew manifest on start-up doesn't show all of the people in the game. Round ID and information is in the SC.

**Comment by redmoogle** [comment]
Have you been able to replicate this?

**Comment by adamsong** [comment]
Cannot replicate
