### ISSUE TITLE
Tesloose caused timers to die

### ISSUE THREAD

**Issue by PrinceKirze** [yogstation13/Yogstation#9877]
Issue reported from  Round ID: 32107 (Yogstation 13 (Main))

Reporting client version: 513.1532

Tesla loosed and shortly after the timer subsystem die a kill. Runechat fucked, sec timers fucked, the whole nine yards. Map is boxstation.

**Comment by UselessTheremin** [comment]
yeah it also caused particles to just stay put, progress bars to not complete, and characters not being able to stand up iirc. i think its just a problem with extreme lag, in this scenario caused by tesloose.

**Comment by ToGWtF** [comment]
Timers have a lower priority than some other systems, so during extreme lag situations the server pauses timers so something else can run first.
