### ISSUE TITLE
Tile that feeds mining station atmos from the exterior vent is not updating

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#9909]
Mining atmos cannot refill itself due to the tile that feeds the vent that feeds the system not updating. Once it has siphoned the air on that tile (assuming it starts with any) no new air flows in and it remains at 0 kpa. Alexkar was able to fix it on the live server during a round, appears to be an area/turf issue.

**Comment by MegaEmpirical** [comment]
![image](https://user-images.githubusercontent.com/36208065/95416843-90917080-0901-11eb-9f43-fe3e3a522a87.png)

**Comment by Jarod1200** [comment]
i have also noticed this

**Comment by MegaEmpirical** [comment]
This will not stop me from repairing all of their broken windows using build mode and replacing them with a wall to force them to use the doors like normal people.
