### ISSUE TITLE
Defib won't alert ghosts.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#9947]
- No notification at all, players can entirely miss out on (valid) defib attempts on their body.

**Comment by jcatjmeow** [comment]
UGH I ALREADY FIXED THIS WHY IS IT BROKEN AGAIN

sorry.

Uh, anyway, steps to reproduce? Does it happen every time?

**Comment by MegaEmpirical** [comment]
I can confirm that this is a thing, I had Theos come test it out with me the other night.

We killed me, I wandered away from the body, he defibbed me, and I got fucking jack shit, no notification. Theos got feedback saying there was no brain activity.

We tried defibbing again but this time with me in the body, I was revived.

Shit be fucked.

**Comment by jcatjmeow** [comment]
Well
Fuck
