### ISSUE TITLE
Unintended way of discovering the bluespace locker

### ISSUE THREAD

**Issue by Moja10** [yogstation13/Yogstation#9960]
![image](https://user-images.githubusercontent.com/17183762/95804304-f138f880-0cc7-11eb-8f40-3616be610219.png)

The bluespace locker can be easily cheesed using this method rather than doing it the old fashioned way. Perhaps it can be fixed by having it simply not show up in the area teleport selection.

**Comment by alexkar598** [comment]
People can just navigate to it by teleporting to CC and going to the bluespace locker. This is an administration issue not a code one

**Comment by alexkar598** [comment]
Also this is a feature request, not a bug, move this to the forums.
