### ISSUE TITLE
Protect X objective for traitors

### ISSUE THREAD

**Issue by sagaty** [yogstation13/yogstation#997]
title

**Comment by utahclock** [comment]
what about it?

**Comment by sagaty** [comment]
I could be wrong but I think traitors doesn't have the protect objective, only traitor AI/ninja, however protecting someone as AI or ninja is quite easy depending on the rest of your objectives.

**Comment by Super3222** [comment]
Only ninjas and possibly traitor AI's (though I never heard of it) have that objective

**Comment by Zostroll** [comment]
I have seen a traitor ai with it on a gang round recently.

**Comment by ShadowDeath6** [comment]
yandere objectives for AI means to protect someone from dying and to maroon them

**Comment by AdamElTablawy** [comment]
council said no when i asked a month ago
