### ISSUE TITLE
Opening the rules in game gives error. 

### ISSUE THREAD

**Issue by Xantam-13** [yogstation13/Yogstation#9973]

**Comment by Altoids1** [comment]
I'm assuming this is due to a change in the rules URL?

**Comment by Altoids1** [comment]
@alexkar598 while I'm pretty sure Xantam's bug is solely because his BYOND client wasn't updated, I do want to point out that it looks like the current Rules URL in-config is incorrect. I'd recommend fixing the config to be the new URL instead

**Comment by alexkar598** [comment]
Known BYOND bug, update BYOND, the old rules page has a redirect in it so idrc but feel free to make a pr to update the link if you really want to
